### ISSUE TITLE
[Feature] Automatically assign category "Starting Balances" when reconciling account with no transactions

### ISSUE THREAD

**Issue by grahamjpark** [actualbudget/actual#1009]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I evaluated Actual budget previously but eventually stopped using it. Today I returned to get it setup again. I deleted previous transactions on my accounts and reconciled the balances. I wasn't sure how best to categorize the reconciliation transaction in this case and then realized that "Starting Balances" exists.

It would be a nice flow if the reconciliation process recognized that this is the first and only transaction on the account and automatically categorized it as "Starting Balances". Getting back to budgeting can be tricky enough and one less decision would be nice.

### Describe your ideal solution to this problem

When creating the reconciliation transaction it performs a check for other transactions on the account, and if there are none it assigns it to the "Starting Balances" category that is used when creating a new account.

### Teaching and learning

This feature would happen automatically

**Comment by alex-t-grey** [comment]
This is actually a great idea
