### ISSUE TITLE
[Bug]: Reconciling accounts doesn't show cleared checkboxes

### ISSUE THREAD

**Issue by DistroByte** [actualbudget/actual#1013]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When reconciling an account with "show cleared checkboxes" disabled (no checkboxes), a notice is shown to the user stating the cleared vs uncleared balance of the account. If this is hidden, then the UI is inconsistent. Either force enabling the checkboxes or notifying the user they have them off would be a solution to this problem.

To reproduce, create an account, add some uncleared transactions, hide the checkboxes, reconcile the account.

![image](https://user-images.githubusercontent.com/58866873/236706156-59f9f3b8-a6ab-48e8-a15a-dc098f286e1e.png)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 11

**Comment by DistroByte** [comment]
Not really a silly question, but with the addition of the "hide checkboxes" for accounts (like cash, where transaction is instant), reconciling cash balances should be instant.

**Comment by shall0pass** [comment]
If you set a rule to automatically clear transactions for that account, it would give the desired behavior since you assume all those transactions are cleared anyways.

**Comment by DistroByte** [comment]
That's valid, however the UI is still inconsistent without that rule, which I imagine most people won't think to create (myself included)
