### ISSUE TITLE
[Bug]: select transactions only selects a range, and if filter is applied, selecting outside of filter crashes the app

### ISSUE THREAD

**Issue by joaociocca** [actualbudget/actual#1021]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I was trying to select a few transactions, and noticed the select behavior is strange: it won't select anything which is not a range. If you try to select 1 then 2 then 5 it'll also select 3 and 4.

Worse, if you did a select when a filter is applied, then remove the filter and try to select something, you'll crash the app.

I can privately share a video replicating the issue, considering sensitive information shown.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome, Other

### Operating System

Linux

**Comment by j-f1** [comment]
I think this may have something to do with the system believing the shift key is being held down. Pressing and releasing Shift usually fixes the issue for me, but it would be nice to fix it more permanently.

**Comment by joaociocca** [comment]
I was going to say I never pressed the shift key, but I remembered I did, twice, one for starting Capital letter and another for ^ in a letter for what I was searching... but it's in the middle of the word, and none of the rest of the letters come out shifted.

**Comment by joaociocca** [comment]
ok, confirmed it's shift on the search field that bleeds. I searched something without hitting shift and selection works as expected.

![image](https://github.com/actualbudget/actual/assets/6473725/6b5c2526-a929-45b0-a40e-418ff341f169)

(padaria = bakery)

Weird thing, doing a second search using the shifted string, after doing a plain one, doesn't seem to trigger the bug anymore?

![image](https://github.com/actualbudget/actual/assets/6473725/9ddbedf7-07ec-43e7-a2a1-f1db2e537720)

Clearing the search, clicking again on the search field and doing the shifted search again, hitting enter at the end of typing (I haven't hit it on that second test) seems to trigger it again...

But then, clearing the search and clicking a select square won't crash the app again O.o geez, this is one weird bug.

**Comment by j-f1** [comment]
Can you try the preview at https://deploy-preview-1022--actualbudget.netlify.app/ and see if it fixes your issue?

**Comment by joaociocca** [comment]
looks fixed - holding on to test with the docker deploy using my data =)
