### ISSUE TITLE
[Feature] Retain months viewed range

### ISSUE THREAD

**Issue by youngcw** [actualbudget/actual#1039]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

When viewing multiple months in the budget window I like to set the view to last/current/next month. Ex. at time of writing I would look at the budgets for April/May/June.

The next time I open the browser window I still can view 3 months, but it starts at the current month instead of remembering the last used range.

### Describe your ideal solution to this problem

Save the viewed months in the cached data along with the number of months viewed so a user can jump back in to the same setup as the last time.

**Comment by j-f1** [comment]
I believe they are stored on the local prefs object which should be separate for each budget file.

**Comment by youngcw** [comment]
Im seeing the view retained between different files.  I can set it to something crazy like 6 months starting a year ago, then close the file and open another and get that same view

**Comment by youngcw** [comment]
hmm, I was seeing it sometimes, but now it seems to be gone.  Maybe the version I was on before updating didn't have that PR yet.  

I am still consistently seeing that the number of viewed months doesn't stay within a single file.

**Comment by j-f1** [comment]
> hmm, I was seeing it sometimes, but now it seems to be gone. Maybe the version I was on before updating didn't have that PR yet.

Phew! I checked the code and it looks like the local prefs are always cleared when closing a file, but maybe we missed something since the current open budget state is stored on both the server and client sides in the browser independently.

> I am still consistently seeing that the number of viewed months doesn't stay within a single file.

That is intentional since the `maxMonths` pref is stored in the globalPrefs. I don’t really feel strongly that it needs to be there, though.

**Comment by youngcw** [comment]
> That is intentional since the `maxMonths` pref is stored in the globalPrefs. I don’t really feel strongly that it needs to be there, though.

I would be onboard with changing that pref to be per file instead of global.

**Comment by youngcw** [comment]
probably can remove `needs votes`.  Maybe if the number of months being across all files is annoying enough it can get its own feature request.

**Comment by j-f1** [comment]
Yep! The automation failed 🤦

Hopefully fixing in #1411
