### ISSUE TITLE
[Feature] Hide Account Balances

### ISSUE THREAD

**Issue by grahamjpark** [actualbudget/actual#1041]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

There are some situations I want to update or reference my budget without someone glancing at it and seeing my account balances. This should be something that is easy to toggle on and off when you need it and not something buried deep in the settings.

### Describe your ideal solution to this problem

A privacy-mode button that would hide the account balances on the side-bar and at the top of the account. A similar feature is implemented in the [Toolkit for YNAB](https://github.com/toolkit-for-ynab/toolkit-for-ynab/blob/main/docs/feature-list.md#hide-account-balances).

**Comment by joel-jeremy** [comment]
Is this a feature that can be worked on or does it still need more votes? I'd be happy to take a stab at implementing this. :)

**Comment by joel-jeremy** [comment]
This has been released as an experimental feature. For feedback, please comment on #1360.
