### ISSUE TITLE
[Bug]: Mobile budget screen shift

### ISSUE THREAD

**Issue by shall0pass** [actualbudget/actual#1046]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

If i touch a balance column, the curser selects a value and shift the budget page to the left.  I can only reproduce this in chrome mobile on Android.  Brave mobile and Firefox mobile don't do this.

BEFORE 
![Screenshot_20230518-072921](https://github.com/actualbudget/actual/assets/20625555/25dfe6b6-a774-45ed-bde6-9585fc784cea)

AFTER
![Screenshot_20230518-072927](https://github.com/actualbudget/actual/assets/20625555/42ce471d-d721-4117-936b-24aee03982dc)

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mobile Device

**Comment by j-f1** [comment]
No repro on iOS

**Comment by shall0pass** [comment]
This is no longer happening for me.  It must have been a bug in chrome.
