### ISSUE TITLE
[Bug]: Importing cents imports as whole numbers if no leading zero

### ISSUE THREAD

**Issue by kstockk** [actualbudget/actual#1051]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When importing cents with no leading zero from a CSV file, they are converted to whole numbers instead of cents. 

For example:
Date,Description,Debit,Credit
17/05/2023,Transaction,,.47,

This csv imports as $47 where it should be $0.47

### Where are you hosting Actual?

Docker

### Operating System

None

**Comment by j-f1** [comment]
Related: #1029 (cc @chylex)

**Comment by chylex** [comment]
> Related: #1029 (cc @chylex)

Parsing numbers with no integral parts is covered by the `handles division` test, maybe the problem is with the CSV parser?

**Comment by j-f1** [comment]
Oh yes, sorry. The code path for imports is completely separate from the code path for typing in numbers.

**Comment by Shazib** [comment]
I believe the offending line causing this is somewhere [here](https://github.com/actualbudget/actual/blob/287fb9b9d67e6643eb9d0062f17d415e1d76b033/packages/loot-core/src/shared/util.ts#L399) where it ends up inside extractNumbers and removes the leading decimal. I think that match fails.

**Comment by jhollowe** [comment]
Just as a note, this also affects QIF files (I think it would affect any import since they use the same number parsing code path)
