### ISSUE TITLE
[Bug]: Repeating Weekly Goal Template freezes budget

### ISSUE THREAD

**Issue by dlrobson** [actualbudget/actual#1055]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

This is my goal template:
```
#template $3 repeat every week starting 2023-04-01
```
Which is nearly identical to the template found here: https://actualbudget.github.io/docs/Advanced/Experimental-Features/goal-templates#how-to-use-the-templates
```
#template $10 repeat every week starting 2022-01-03
```
Neither templates can be applied as it never finishes processing.

I'm currently on the latest version, 23.5. It was previously working before.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

**Comment by youngcw** [comment]
Are you using the edge image or the latest image? I fixed a similar issue the other day that is available in the edge image.

**Comment by dlrobson** [comment]
Just tried out the edge build, and it works there. Thanks!
