### ISSUE TITLE
Version number not updating

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#106]
Version number in package.json is not reflected on the login screen on actual web. 

Raised on the 29th June's live stream and it was discussed that it was an error in the tooling as the electron app version isn't updating.

**Comment by PartyLich** [comment]
A little more detail (for myself, if no one else):
- the version number in `package.json` (4.0.2) is reflected, but does not match the latest version pushed to npm (4.1.0) https://github.com/actualbudget/actual/blob/33ca432ea6f793570529ab5adfff603ce7c7d7db/packages/desktop-electron/package.json#L6
- the displayed client version number is pulled from the `desktop-electron/package.json` https://github.com/actualbudget/actual/blob/33ca432ea6f793570529ab5adfff603ce7c7d7db/packages/desktop-client/bin/build-browser#L6

**Comment by rich-howell** [comment]
This is now in 22.10.25
