### ISSUE TITLE
[Bug]: New OFX Importer:

### ISSUE THREAD

**Issue by Mel-24** [actualbudget/actual#1065]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

A bug happened!

Not really sure what the issue is but with each OFX file I am importing, I keep getting the error. Just jumped back to Actual after trying some other software and I am getting this with everything. 

### What error did you receive?

possible error importing file, please [file a bug report](https://github.com/actualbudget/actual/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug-report.yml&title=%5BBug%5D%3A+New+OFX+Importer:) and attach a redacted version of the file.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 11

**Comment by j-f1** [comment]
Can you attach a redacted version of the OFX file as requested?

fyi @sinistersnare
