### ISSUE TITLE
[Feature] Use date from manual transaction instead of imported transaction

### ISSUE THREAD

**Issue by neilguertin** [actualbudget/actual#1071]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

My bank reports incorrect dates on transactions, usually the posted date, and transactions on the weekend are always delayed until Monday. This means that transactions are often several days off. When I import the transactions, they overwrite the existing manually entered transactions or previously corrected transactions with the incorrect date.

This sometimes even moves transactions to a different month, causing chaos in my budget.

The [Import Transactions documentation](https://actualbudget.github.io/docs/Accounts/Transactions/importing-trans/) says

> It will always favor the imported transaction. It if matches a manually-entered transaction, it will update the date to match the imported transaction. Keeping dates in sync with your bank is important as it allows you compare the balance at any point in time with your bank.

I consider my budget a better source of truth than my bank and so I don't think it makes sense to put incorrect information in the budget just to match my bank statement which I never look at anyways.

### Describe your ideal solution to this problem

This could be controlled with either a global setting or an option on the import confirmation page.

**Comment by axelson** [comment]
I wonder if another solution to this is to keep a separate posted date that can be different from the transaction date.

**Comment by mcalligator** [comment]
> I wonder if another solution to this is to keep a separate posted date that can be different from the transaction date.

I think that's quite a good idea, as it preserves the integrity of data imported from one's bank, whilst enabling one's budget to be the authoritative source of truth for the transaction date if preferred.

**Comment by TorC8** [comment]
It looks to me there can be only one transaction post date, and the only sensible date for that is when the transaction posts to the account.  Given that, AB's method would be correct.

A field in the transaction record for budget withdrawal date, defaulting to manually entered transaction date if different from account posted date, would be a good option.
