### ISSUE TITLE
Add tests for the API

### ISSUE THREAD

**Issue by j-f1** [actualbudget/actual#1074]
Presently, there are no automated tests for the API beyond making sure it builds successfully. We should have some tests that spin up a server, run through some/all of the supported ops, and check a few error cases. This would make it less likely that unrelated changes would accidentally break the API.

**Comment by MatissJanis** [comment]
@twk3 I believe we can now close this issue. Can you confirm?

**Comment by twk3** [comment]
Yes let's close it. There are a few less common handlers like runQuery that aren't covered. But all the ones that represent entities are now in place.
