### ISSUE TITLE
[Feature] Specify when months run from and to

### ISSUE THREAD

**Issue by IAmParadox27** [actualbudget/actual#1080]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

People get paid on different days of the month.

To help people better budget instead of forcing to budget strictly to the month, it would be better if people could budget for payday to payday.

Allow the user to specify when their months should run from and to.

### Describe your ideal solution to this problem

I would recommend having a setting where the user can specify when they would like their month to start. 

Options:
- Set day of the month (including 1st)
- Last working day of the month

A setting should exist to say what happens on weekends (bring forward)

The last day of the monthly cycle should either be the day before the next month is due to start and shouldn't have a setting to specify its rule OR a fixed duration of time after month start (eg for people that get paid weekly or every X weeks).

**Comment by jpdsc** [comment]
As someone who gets paid on the 24, this feature is actually needed for me to start using this software.
I've tried and setting up the budget flow from 1st till last day of month but it will not match current finances and needs too much manual intervention to make it work.

+1 for this feature.

**Comment by gitchap** [comment]
I can see how this feature would make things LOOK tidier... but how does it actually change anything? How are you paying your bills before the 24th? I'm assuming you use funds from your last paycheck. (Unless all your bills are due between the 24th and the 1st of next month, in that case, just wait till the 24th to budget.)

I get that not everyone is in a position to budget this month's income as next month's budget. 

I guess my point is that this is more of a "nice to have" feature, and not a "need." Most people don't get paid on the 1st of the month. Many people are paid weekly or bi-weekly. Most bills are monthly. In the end all that matters is do you have enough money to pay the bill when it is due. 

I don't see how being able to pick the day of the month that the software splits the budget into changes anything other than aesthetics.

I'm curious what kind of "manual intervention" is needed to make the budget "work"? I'm not paid monthly, so maybe I don't get it.

**Comment by jpdsc** [comment]
> I can see how this feature would make things LOOK tidier... but how does it actually change anything? How are you paying your bills before the 24th? I'm assuming you use funds from your last paycheck. (Unless all your bills are due between the 24th and the 1st of next month, in that case, just wait till the 24th to budget.)
> 
> I get that not everyone is in a position to budget this month's income as next month's budget.
> 
> I guess my point is that this is more of a "nice to have" feature, and not a "need." Most people don't get paid on the 1st of the month. Many people are paid weekly or bi-weekly. Most bills are monthly. In the end all that matters is do you have enough money to pay the bill when it is due.
> 
> I don't see how being able to pick the day of the month that the software splits the budget into changes anything other than aesthetics.
> 
> I'm curious what kind of "manual intervention" is needed to make the budget "work"? I'm not paid monthly, so maybe I don't get it.

I've been using Actual for a while now. After doing quite some research on "best way to budget" and you're right, you should budget for next month with the income of this month.
I re-arranged my finances, got some recurring transactions changed to be booked from the 1st onwards and kept anything between 24 and 1 as low as possible.

I feel, budgetting 1st till last day of the month is a lot easier than doing pay > pay (what is was doing previously). It's one time bridging the expenses from 24 till end of the month. But if you contact the recurring payment provider/company, often you can change the recurring date and set it to beginning of the month (if not enough funds to initiate this faster).

**Comment by IAmParadox27** [comment]
My issue with it is mostly aesthetic. But there's a frustration when being paid on the last working day of the month. Mostly because that pay **is** for the following month, but appears in the month prior. So things like budgeting looks proper wonky.

Lets say I start now, putting in a budget for April onwards. I put in my pay that I'll receive on 31st March, that appears in the March tab as "To Budget" but there's no spending or budgeting because I'm going from 1st April. So then we head to April and put all the budget in, track the spending etc etc, then we get to the end of the month and we put the pay in for 30th April and the April tab is then updated with "To Budget" of my salary again. 

By adding a pay cycle into the software, what ends up happening is there is only ever 1 pay per month to budget.

Mostly this is useful for those that currently live paycheck to paycheck and are wanting to get a grip on finances to be free from the pay to pay lifestyle. But that's difficult to do and making that as easy as possible to manage is only ever a good thing. My view here is its a feature that's opted for rather than a feature forced upon a user, and anything that can help an individual (like myself) get a grip on their finances to shift mindsets and budget better should be something worth supporting.

I'd do it myself, but I'm not massively familiar with the stack that's used to write it and I'd probably get lost and "do it wrong" :D

**Comment by sidvishnoi** [comment]
Duplicate of https://github.com/actualbudget/actual/issues/975?

**Comment by IAmParadox27** [comment]
Looks like it yes

**Comment by Juulz** [comment]
You can use auto-hold for next month or change the date on the deposit.
