### ISSUE TITLE
Add support for Passkeys

### ISSUE THREAD

**Issue by j-f1** [actualbudget/actual#1089]
We can use [SimpleWebAuthn](https://simplewebauthn.dev) to set this up, but it is not particularly simple to set up. This would be an optional replacement for passwords, so the database schema would need to be updated to support switching between the two credentials. (Maybe we should switch the accounts DB to JSON to make it easier to handle? See also actualbudget/actual-server#104 which would be a reason to stick with SQL.)

**Comment by youngcw** [comment]
closing in favor of #2042
