### ISSUE TITLE
Multi-user Support

### ISSUE THREAD

**Issue by NathanaelA** [actualbudget/actual#1091]
Since this software originally started as a multi-user SaaS service, is their a way to enable multi-users for the server.     I've scanned the docs, the repos, and not seeing anything obvious...    

For me, I have several older kids, it would be nice to run a single instance of the server and allow each of us our own "data" files so that one they can start handling their own finances much easier and I wouldn't have to run multiple instances of the docker container...

**Comment by kyrias** [comment]
Since this appears to be the same as #524 maybe the `needs votes` label should be removed from this in favor of that issue?

**Comment by j-f1** [comment]
Good catch! Please go 👍 that issue if you haven’t already.
