### ISSUE TITLE
[Feature] Allow negating a rule conditon

### ISSUE THREAD

**Issue by Jackenmen** [actualbudget/actual#1093]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

In rules, I'd like to be able to specify conditions that I would like to not be met in order for the rule to be applied.

For example, right now I'm often using the "contains" condition to match the first and last name of the imported payee such that I don't have to create rules for each way that their name may appear as in the imported transactions (which depends on the bank of both the recipient and sender). However, this falls short for two of my payees who share their last name and one's middle name is the other's first name. 

### Describe your ideal solution to this problem

What I want to do is simply add a "does not contain" condition for the first name of the other person so that their middle name doesn't get matched into the wrong payee but this is currently not a thing.

I think that it would be best to be able to just allow negating the condition *but* it might be easier to just add "is/does not" counterparts to each of the existing conditions.

### Teaching and learning

If this would be implemented with counterparts then this is as discoverable as the regular conditions. If proper condition negation is added then I guess that there should be some kind of "NOT" switch before the select list in each condition.

**Comment by carkom** [comment]
Fixed by #1287
