### ISSUE TITLE
Ability to resize LH sidebar of account listings 

### ISSUE THREAD

**Issue by SaveYourMoney** [actualbudget/actual#1094]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I have found that the account names that I wish to use are too long to neatly fit into the sidebar. The account names run into the dollar amounts shown for that account.

### Describe your ideal solution to this problem

The ideal solution to this issue would be to either create a toggle to enlarge the sidebar or to allow the sidebar to be dragged to the desired width by the user.  There is plenty of screen space on a wide-screen monitor to allow room for the sidebar to grow.

**Comment by MikesGlitch** [comment]
100%. I'd be willing to work on this if I ever find time. The ellipsis is annoying.

![image](https://github.com/actualbudget/actual/assets/5285928/c7cff8a4-c0dd-45b0-9954-3359dd904096)

**Comment by SaveYourMoney** [comment]
> 100%. I'd be willing to work on this if I ever find time. The ellipsis is annoying.

I have zero coding experience or I would have tackled this before.  This one has got some age to it but it still bugs me that I can't adjust the sidebar.  I've gotten pretty good at tweaking account names to make them fit.

**Comment by MikesGlitch** [comment]
This is completed as per #2993

**Comment by SaveYourMoney** [comment]
> This is completed as per #2993 so can be closed. Work completed by @YusefOuda

Thanks!  Looks great!
