### ISSUE TITLE
[Bug]: No simple way to undo "Split" transaction categorization

### ISSUE THREAD

**Issue by bstritesky** [actualbudget/actual#1096]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Once you click on the Split option in Categorization, you cannot change it to non-split. The only workaround is to delete the transaction and re-create/re-import.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by biohzrddd** [comment]
Also seeing this. I think the split transaction functionality needs a UX uplift in general. For example, if you accidentally add another split transaction that is empty, it should be deleted when the split transactions sum up to the split amount and the user clicks "Add".
![image](https://github.com/actualbudget/actual/assets/10577752/1160c2dc-8b3d-4b60-abf1-015d8fed3d7c)
 Instead, it leaves an empty split transaction. 
![image](https://github.com/actualbudget/actual/assets/10577752/7a801c47-a433-4089-b9f2-88f6d28f37d9)

**Comment by trevdor** [comment]
I agree 100% this would useful functionality. However, as far as I'm aware, this functionality has never existed in Actual.
Please correct me if I'm mistaken, otherwise I'll reclassify as a feature request.

**Comment by youngcw** [comment]
You can select the child transactions and delete them.  No need to create a new transaction to remove the split.
