### ISSUE TITLE
[Bug]: Using math in Payment or Deposit fields sometimes inaccurate

### ISSUE THREAD

**Issue by bstritesky** [actualbudget/actual#1097]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

In a split transaction, I often use math in the Payment and Deposit fields to calculate things like tax, so I put in the split item amount before tax and enter *1.07875 for our tax rate.

When I enter `6.78*1.07875`, I get this value: 731,392.50
When I enter `6.78*1.0787`, I get this value: 73,135.86
When I enter `6.78*1.078`, I get this value: 7,308.84
When I enter `6.78*1.07`, I get this value: 6.42

This makes me think that the math doesn't handle more than 3 decimal places properly.

In my settings, I am using the Numbers format "1,000.33" and Hide decimal places is unchecked.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by j-f1** [comment]
This is a result of https://github.com/actualbudget/actual/pull/1029, which was intended to make number parsing format style agnostic. (fyi @chylex). This is definitely an important use case we should support, not sure how best to balance parsing different number styles with handling non-currency amounts here.

**Comment by j-f1** [comment]
Just reverted this change in #1144, so the next release should go back to the old behavior.
