### ISSUE TITLE
[Bug]: Attempting to run end of month cleanup triggers error "Unknown method: budget/cleanup-goal-template"

### ISSUE THREAD

**Issue by grayter** [actualbudget/actual#1103]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I'm running the 23.6.0 docker image for actual-server and am interacting with it via a web browser. I've created a basic test budget in order to better understand how the #template and #cleanup experimental options work. Unfortunately I'm having no success with the cleanup script, as when the "End of month cleanup" option is selected in any given month's drop down list of actions the web browsers console reports "Unknown method: budget/cleanup-goal-template" and the following trace:

> Unknown method: budget/cleanup-goal-template
> (anonymous) @ index.web.ts:91
> Uncaught (in promise) TypeError: Cannot read properties of null (reading 'id')
>     at Et (notifications.ts:9:24)
>     at queries.ts:42:11
> Et @ notifications.ts:9
> (anonymous) @ queries.ts:42
> await in (anonymous) (async)
> (anonymous) @ index.js:16
> (anonymous) @ redux.js:578
> onBudgetAction @ index.js:331
> onMenuSelect @ BudgetSummary.tsx:388
> onClick @ common.tsx:607
> Re @ react-dom.production.min.js:54
> Ue @ react-dom.production.min.js:54
> (anonymous) @ react-dom.production.min.js:55
> Lr @ react-dom.production.min.js:105
> Fr @ react-dom.production.min.js:106
> (anonymous) @ react-dom.production.min.js:117
> cu @ react-dom.production.min.js:274
> Me @ react-dom.production.min.js:52
> Kr @ react-dom.production.min.js:109
> qt @ react-dom.production.min.js:74
> $t @ react-dom.production.min.js:73

This appears to happen in Firefox, Chrome and Edge. I'm using a default new budget with the following setup to test:

- "Bills (Flexible)" has a comment added "#cleanup source"
- "Savings" has a comment added "#cleanup sink 1"
- I create a starting balance of 1000 in a test month (e.g. 1st May 2023)
- I allocate 600 to "Bills (Flexible)"
- I allocate 300 to "Savings"
- 100 is left "To Budget"

I was expecting the allocated money in "Bills (Flexible)" plus the unallocated "To Budget" money would have been reallocated to "Savings" but this does not happen as the relevant script has not run.

Thanks!

### What error did you receive?

Unknown method: budget/cleanup-goal-template appears in the web browers console view.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Operating System

Windows 11

**Comment by shall0pass** [comment]
I am unable to reproduce this.  Could you try using the http://actualbudget.netlify.app preview to see if it creates the same error for you?

**Comment by grayter** [comment]
I’ve also just connected to my docker actual server from the netlify hosted version. Using exactly the same test budget that fails if I go directly to my server, it works going via the netlify webpage.

**Comment by shall0pass** [comment]
The netlify link uses the latest code in the master repository, so it's a little newer than 23.6.0, but not by much.

I would try recreating the docker container using the 'latest' build, and if you still have the same issue, trying the 'edge' build if your comfortable.

**Comment by grayter** [comment]
Cloning and building the master branch for actual-server did not resolve the problem, but building the edge version did work as expected. Thanks for pointing me in that direction - I assume a future release will include whatever change can be found in edge?

**Comment by shall0pass** [comment]
Yes.  The edge branch is current with master from the previous day and those changes will be in the next release along with other bug fixes and improvements this month.

I'm happy its working for you!

**Comment by grayter** [comment]
Thanks again. Commenting here to close.
