### ISSUE TITLE
[Bug]: New OFX Importer:

### ISSUE THREAD

**Issue by rreveley** [actualbudget/actual#1112]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Actual reports an error every time I import. However, the imports largely work with maybe the occasional skipped row. The import transaction panel looks fine including all transactions but in this specific case the final transaction for 182.56 is skipped and not imported.
  
Attached is an example file.

[Statement Download 2023-Jun-08 15-32-08.txt](https://github.com/actualbudget/actual/files/11689699/Statement.Download.2023-Jun-08.15-32-08.txt)

### What error did you receive?

possible error importing file, please [file a bug report](https://github.com/actualbudget/actual/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug-report.yml&title=%5BBug%5D%3A+New+OFX+Importer:) and attach a redacted version of the file.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 11

**Comment by j-f1** [comment]
Hi! Thanks for the feedback. Due to this and other issues we’ve decided not to continue using the new importer. Once #1111 is merged, the next release will no longer give you this error message.
