### ISSUE TITLE
[Feature]: Add + sign beside the category group name to add new categories 

### ISSUE THREAD

**Issue by joel-jeremy** [actualbudget/actual#1123]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I just recently discovered Actual Budget and loving it so far! I would just like to pitch some possible improvements to the app. For total beginners, the UX to add a new category could use some improvements. The option to add a new category is hidden under the group's dropdown menu and on top of that, the caret of the group dropdown menu is hidden unless you hover over the group name which makes it hard to discover.

### Describe your ideal solution to this problem

Add a `+` sign beside the group name to make it easy to see and use. This would also reduce the needed button clicks from 2 to just 1. The 2 clicks proved to be a pain point when I was initially setting up my categories on my mobile phone.

**Comment by Kidglove57** [comment]
The current UI design is consistent with the design ethos of Actual generally. There is much functionality to be discovered by hovering over various interface areas. This is what keeps its appearance clean and pleasing. I would not wish to see undue clutter added that might detract from this.

For example, the hide, rename, and delete options for each category are also neatly hidden in exactly the same way. As is functionality under "To Budget".

If I want to add a category and do not know how to then the first thing I would intuitively do would be to move my mouse to the category group to investigate further. Having done that, the down arrow would be revealed and I would have my answer.

Just my viewpoint - even if I do feel quite strongly about this and the preservation of the fundamental design principles of Actual!
