### ISSUE TITLE
[Bug]: Checking 'Payee' checkbox on find schedules crashes app

### ISSUE THREAD

**Issue by Shazib** [actualbudget/actual#1125]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

If you click the 'Payee' checkbox on the find schedules page **while the spinner is still going**, it crashes the app. Reproduced on my stable version as well as dev.

### What error did you receive?

![image](https://github.com/actualbudget/actual/assets/4405777/913b7abd-0c2f-4a26-8326-b0d55a90bf56)

![image](https://github.com/actualbudget/actual/assets/4405777/43b2172d-ace2-4033-9dd4-e16d0e5529fa)

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 11

**Comment by rich-howell** [comment]
This is reproduceable on https://demo.actualbudget.org/

`TypeError: Cannot read properties of null (reading '830cffb9-651f-4ac9-92aa-4d9b690779d0') at children (https://demo.actualbudget.org/static/js/main.2c9cd1eb.js:2:1006552) at Qf (https://demo.actualbudget.org/static/js/main.2c9cd1eb.js:2:484273) at ka (https://demo.actualbudget.org/static/js/main.2c9cd1eb.js:2:166681) at ks (https://demo.actualbudget.org/static/js/main.2c9cd1eb.js:2:223794) at xu (https://demo.actualbudget.org/static/js/main.2c9cd1eb.js:2:212900) at vu (https://demo.actualbudget.org/static/js/main.2c9cd1eb.js:2:212828) at mu (https://demo.actualbudget.org/static/js/main.2c9cd1eb.js:2:212691) at au (https://demo.actualbudget.org/static/js/main.2c9cd1eb.js:2:209471) at uu (https://demo.actualbudget.org/static/js/main.2c9cd1eb.js:2:209862) at Ho (https://demo.actualbudget.org/static/js/main.2c9cd1eb.js:2:150402)`
