### ISSUE TITLE
[Feature] Guide on How to Handle Credit Cards in the Budget

### ISSUE THREAD

**Issue by joel-jeremy** [actualbudget/actual#1142]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I'm only getting starting to budgeting and using the zero based budgeting system and I'm currently having trouble wrapping my head around how to handle credit cards in the budget. Maybe it's a silly question but how should we budgets for credit card payments that are due for the month and not for the other cards that are due next month? How do we correctly reflect the credit card payment transaction when the statement arrives? 

Currently what I did is:

1. Create transactions in Actual where payee is set to my `Credit Card` account and categorize them appropriately.

![image](https://github.com/actualbudget/actual/assets/20313680/f61ed6b6-f239-4572-96ab-9d274d7c5c2a)

2.  Let's say today is June 1 and I got my credit card statement amounting to $100 and is due on the June 15 and I have 200 on my `Checking` account.

![image](https://github.com/actualbudget/actual/assets/20313680/e0043beb-8703-478a-ac1b-1bc1bf56e6f8)

3. To set aside some funds for the upcoming credit card bill, I have budgeted $100 in the "Credit Card" category under the "Credit Card Payments" group.

![image](https://github.com/actualbudget/actual/assets/20313680/4f40db0b-b44d-4cb0-9a46-306520534a0a)

4. June 15 comes and I pay my credit card bill and in Actual, I transfer $100 from my `Checking` account to my `Credit Card` account.

![image](https://github.com/actualbudget/actual/assets/20313680/f4894161-7edc-4cd2-8fcd-953d563fea45)

![image](https://github.com/actualbudget/actual/assets/20313680/0799b2fc-3331-4f03-affb-3515505bfb69)

5. My `Checking` and `Credit Card` accounts now reflect the actual (no pun intended 😅) amounts.

![image](https://github.com/actualbudget/actual/assets/20313680/c427bfba-61b5-45ee-8db2-2105ff68e40e)

6. But my `Credit Card` category still have a balance.

![image](https://github.com/actualbudget/actual/assets/20313680/07dae9aa-ab4a-42bc-8bf6-f39461f38a1d)

Is this the correct way to go about it? Is the balance still supposed be non-zero? Because in my mind I already spent that money (paid credit card) but why is still showing a balance as if I still some remaining money to spend? Am I missing something? Please let me know your thoughts. Thank you!

### Describe your ideal solution to this problem

It would be great if the "Managing Credit Cards" documentation can be updated to include information of how to budget for credit card payments.

### Teaching and learning

It would be great if the "Managing Credit Cards" documentation can be updated to include information of how to budget for credit card payments.

**Comment by j-f1** [comment]
This is covered by https://actualbudget.org/docs/budgeting/creditcards, is there something we could improve there (or somewhere in the app we should be linking to that page) to help guide new users in the right direction?

**Comment by rafacla** [comment]
Hi guys,

I'm so happy to discover that Actual actually exists 🤣 
After a few trials myself on building something like Actual/YNAB, I had gave up and migrated for a local paid Finance website and while it worked great, it wasn't a Zero Based budget tool.

So, I'm still figuring out as this tool works, one thing that I'm feeling it could be improved is the credit card scenario, but I'm not sure if this is just a problem on my side, I mean: here in Brazil (but I think the same applies globally), we have great advantages on using credit cards for basicly everything, as we have cashback using credit cards (like 1% to 1,5% on every transaction).

For budgeting is really ok: when transaction happened is when category should incur the cost, but to conciliate the statements is like a nightmare, once Banks filters transactions by statement due date it's hard to not mess one statement with transactions from another one.

It'd be hard to deploy a view to filter transactions by due date?
Also, one thing I heard that is not common in another countries is the possibility to split the payment of a purchase in no interest installments, for example, a couple months ago I've paid half of a car in 10 installments, so I'd really like to have a option to incur each installment in its budget month, as this make senses for recurring subscriptions and big assets purchases like a car.

I mean, I'd be happy to help on building those features if those features are something devs would like to see in the future.

I'm also available to translate Actual to Brazilian Portuguese.

So, many thanks for this fantastic tool and I'd love to see if you guys have any interest on this.

**Comment by piyushpaliwal** [comment]
I am also in a similar situation. Basically, the guide that's available covers the scenario where you pay off credit card completely on the same month. However, the real use-case is a little different.

For me, I get paid on 1st June and do my budgets the same day; the credit card bills get generated in the middle of the month, say 15th June. This includes transactions from previous month (16th May to 15th June), and at the same time I am making transactions for the current month on credit card (starting 1st june), putting them in actual and tagging appropriate category to it.

So, there is indeed a balance that I am carrying, thus making the credit card category required. Based on the guide, I set it up in such a way that am carrying the overspending on CC category to the next month but the moment I pay/transfer the previous month's CC bill, I end up in exactly the same situation as OP; credit card account shows 0, however, I am left with cc category budged amount.

Am super confused, pretty new to budgeting and actual in general. Any help around this would be really appreciated.

**Comment by diraol** [comment]
100% with @rafacla that would be really an outstanding feature!
