### ISSUE TITLE
Proper bookkeeping layout and terms [Feature] 

### ISSUE THREAD

**Issue by vinstaal0** [actualbudget/actual#1148]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Currently debit and credit (payments and deposits) and reversed from what is typical for bookkeeping. I am aware that banks also do this since they look from their point of view. However, for personal finances or business finances debit and credit should be used. (also helps people if they ever need to do some actual bookkeeping).

### Describe your ideal solution to this problem

Personally I would like to see the option to reverse them, especially cause there is no mass delete for transactions or a proper backup.,

### Teaching and learning

You can just add it as a setting

**Comment by j-f1** [comment]
Hi! I’m not quite sure what you mean here — are you saying that the “Deposit” column should be moved to the left of the “Payment” column?


> […] especially cause there is no mass delete for transactions or a proper backup.,

You can select with the checkboxes (or filter and then select all), then press D (or choose “Delete” from the action menu. There’s also undo support (cmd/ctrl+z) which I’d recommend using.

**Comment by Kidglove57** [comment]
Actual is primarily a budgeting app and (from my understanding) was not designed, from ground up,  around true debit and credit book keeping principles.

 It is better compared to Apps like YNAB, GoodBudget or Moneywell than to the likes of Moneydance, GnuCash etc.

**Comment by vinstaal0** [comment]
Hey, well I can understand that it is designed as a budgetting app, but that doesn't mean it doesn't reverse the order of wich the debit and credit (or Deposit and Payment) colomns should be. Best practise is to follow proper bookkeeping guidelines otherwise people. You never know when you actually need to start doing some actuall bookkeeping.

And thanks for the tip on deleting, that works!
