### ISSUE TITLE
[Bug]: Formula in payment/deposit not using decimal correctly

### ISSUE THREAD

**Issue by bsmarsh333** [actualbudget/actual#1151]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

A bug happened!

I often use calculations in my "payment" field. For example, multiplying the cost of goods sold by the sales tax. 

Prior to this last release, it would calculate it correctly. For example, 81.98 * 1.0725 would equal $87.92. However, since the last release when I enter 81.98 * 1.0725 it now equals $879,235.50.

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by j-f1** [comment]
Good catch! We got a report of this issue earlier, and recently undid the underlying behavior change in #1144. The “edge” version should have the fix in it, and we typically release a new stable release at the start of each month.
