### ISSUE TITLE
[Bug]: Category is not set automatically

### ISSUE THREAD

**Issue by joel-jeremy** [actualbudget/actual#1152]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When adding a transaction to a category via category transactions page (the page after clicking a category's spent amount in the budget table), the category is not automatically set to the clicked category.

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mobile Device

**Comment by j-f1** [comment]
This is a great idea! I’m going to recategorize it as a feature request since this functionality does not exist yet, and you can see that the category is missing by looking at the table.

**Comment by j-f1** [comment]
*impersonates bot since it isn’t working for some reason*

:tada: This feature has been implemented in #1176 and will be released in the next version. Thanks for sharing your idea! :tada:
