### ISSUE TITLE
I cannot edit/add new entries on Android

### ISSUE THREAD

**Issue by astingengo** [actualbudget/actual#1154]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I cannot edit/add new entries on Android

### What error did you receive?

I can do so only if I'll use desktop view

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Mobile Device

**Comment by j-f1** [comment]
This is currently intended behavior, see #604 for the issue tracking adding transactions on mobile.
