### ISSUE TITLE
[Bug]: Guided Tour link dead

### ISSUE THREAD

**Issue by stevans** [actualbudget/actual#1159]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I just installed Virtual for the first time and it mentioned a guided tour twice (once on the create a password page and once on the page after creating a password). When I click on it, a file is downloaded like "I74QVftD.dms" and this can't be opened. I notice the link is to https://actualbudget.github.io/docs/Getting-Started/using-actual/ which is dead as the docs moved. I think it should be something like https://actualbudget.org/docs/tour/.

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Firefox

### Operating System

Mac OSX

**Comment by j-f1** [comment]
Thanks for calling this out! I’m gonna contact GitHub support — this *should* be working, and https://actualbudget.github.io/docs/Getting-Started/using-actual/index.html does redirect as expected.

**Comment by j-f1** [comment]
Figured it out and avoided the bug. Should work now. Let me know if you’re still having issues. For posterity, the fix was: https://github.com/actualbudget/actualbudget.github.io/commit/668516857f8d1ee0d2b6827890c373ce50c8afec
