### ISSUE TITLE
Refactor Rules Editor page to copy Schedules and Filters modals

### ISSUE THREAD

**Issue by carkom** [actualbudget/actual#1162]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

The schedules editor uses a newer format for implementing the list and serving the editor form modal. The rules list (and possibly payees) should follow the newer layout.

**Comment by j-f1** [comment]
Closing this since #1270 goes the other way and removes the route-based modals (they cause some complications with routing/the sidebar and they weren’t used anywhere else, so I decided to go that way in removing them). Sorry for the confusion here!
