### ISSUE TITLE
[Feature] Automatically split sales tax, proportionally to split categories

### ISSUE THREAD

**Issue by MattDemers** [actualbudget/actual#1166]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

When using the split transactions, I would like to be able to proportionally assign remaining post-tax amounts to categories.

For example:

Total amount, with tax: $100
Category 1: $60
Category 2: $30
Pre-Tax total: $90
Money left-over (tax): $10

I'd like to have it so that more of the remaining $10 (the tax) would be assigned to Category 1, than Category 2, because Category 1 is a larger proportion of the transaction.

I searched GitHub for "proportional sales tax", "sales tax" and "split transactions tax" and found nothing that addressed this. Since Reddit is currently locked, I cannot search there. I've seen topics asking about clarity/bugs when it comes to calculations in-field, but I am unfamiliar about how to calculate these proportions myself.

I am using self-hosted Actual, using Docker.

### Describe your ideal solution to this problem

With YNAB4 (Classic), having a remaining unassigned amount of a split transaction, and attempting to click off of the transaction, would give a popup asking what the user would like to do with the remaining amount. One of the options was "Assign proportionally to categories (Sales Tax)" which did the behavior described above.

**Comment by ToniCipriani** [comment]
Was trying out the Distribute functionality and found it only does equal splits. Was looking for this. instead.

Basically it is re-implementing YNAB4's split transaction functionality, and like @MattDemers mentioned, it is good for splitting taxes, tips and even currency conversion.

![image](https://github.com/actualbudget/actual/assets/2412685/09525a47-1aa9-43bf-9a5b-1ddde66f2753)

**Comment by jkrehm** [comment]
The lack of this feature is my biggest stumbling block to using Actual. A Walmart trip may include 5 different categories and having to do the math to proportionally distribute the taxes is prohibitively time consuming. I could swag the amounts, but I would much prefer the tool figure out for me at the press of a button.

**Comment by ToniCipriani** [comment]
> The lack of this feature is my biggest stumbling block to using Actual. A Walmart trip may include 5 different categories and having to do the math to proportionally distribute the taxes is prohibitively time consuming. I could swag the amounts, but I would much prefer the tool figure out for me at the press of a button.

As a workaround right now, I just copy it as a mathematical formula, e.g. if I have a foreign transaction that is $10, but in my currency it's $13 when processed, I just take `*(13/10)"` and paste it to all the subcategory lines.  
  
Likewise if your tax rate is 5%, you can just paste `*(1+0.05)` to all the lines.

But in your situation, I do it manually anyways even with YNAB, simply because some items are not taxed (e.g. grocery food items vs household cleaning stuff).

**Comment by MattDemers** [comment]
For people looking for something to achieve this function, I've created a Google Sheet with formulas/instructions to get the same end result: proportional tax distribution for your big receipts (Costco, I'm looking at you...).

[Google Sheet (Protected, but make a copy)](https://docs.google.com/spreadsheets/d/1nwgqnWvegZLLRvsPraqmZuK0bxvGhm2idweEmDGjmGY/edit?usp=sharing)

**Comment by mcalligator** [comment]
A later, more generic form of this feature request is tracked at [Automatically enter remaining amount in split #2872](https://github.com/actualbudget/actual/issues/2872).

**Comment by Kerrick** [comment]
> A later, more generic form of this feature request is tracked at [Automatically enter remaining amount in split #2872](https://github.com/actualbudget/actual/issues/2872).

I don't think that is the same feature, or a more generic form of the same feature. This is a request to ‘divide the remaining amount among all existing splits proportional to their amounts. This is not currently possible with any workflow; you have to pull out a separate calculator. That is a request to streamline the functionality of an existing button without needing a click.

**Comment by schnps** [comment]
Thank you @victle for doing this! It was my main hang up with adopting Actual.

Do we need to add a separate issue to request this feature be added to the PWA mobile view?
