### ISSUE TITLE
[Feature] Split transactions in schedules

### ISSUE THREAD

**Issue by joel-jeremy** [actualbudget/actual#1168]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Can we allow schedules to post split transactions? This will make it easier for users to track what's included in a transaction. An example of where this could be useful is if a user has multiple installments that are charged to an account on the same statement date, users will be able to identify which portion of the transaction is for which purchase.

### Describe your ideal solution to this problem

Allow schedules to post split transactions

**Comment by j-f1** [comment]
This is a good idea. I think it would require a new design for the schedule editor (which does need some improvements anyway). I’m not sure what that would look like, but feel free to pitch something if you want!

**Comment by ElDubsNZ** [comment]
I too would appreciate this feature.

**Comment by jfdoming** [comment]
> I too would appreciate this feature.
> 
> In the rule it should have a rule to say "split transaction", then a set of rule actions for each child transaction.

Yep, that's exactly the implementation I'm working on!
