### ISSUE TITLE
[Bug]: When you create a new local account the modal to choose account type doesn't go away

### ISSUE THREAD

**Issue by Shazib** [actualbudget/actual#1172]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Apologies if this is intentional behaviour, but I feel like the expected route should be to pop the entire modal stack and take you to your new account (which is does in the background)?

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 11

**Comment by j-f1** [comment]
That’s definitely a bug!

**Comment by MatissJanis** [comment]
Fixed by: https://github.com/actualbudget/actual/pull/1219
