### ISSUE TITLE
[Question]: Moving funds from onbudget to offbudget does not set category to "Off budget"

### ISSUE THREAD

**Issue by joel-jeremy** [actualbudget/actual#1177]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Shouldn't a transaction which moves funds from an on budget account to an off budget account have its category set to "Off budget"?

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mobile Device

**Comment by Kidglove57** [comment]
In my view the transfer out of the on budget account must debit a category. Money is leaving your budget and this has to be taken from one category (envelope) or another for the budget to stay in balance.

There will not of course be any category for the credit side in the off budget account. The category column there simply says “off budget”
