### ISSUE TITLE
Move IDL definitions and associated code to `crdt` package.

### ISSUE THREAD

**Issue by TomAFrench** [actualbudget/actual#1188]
https://github.com/actualbudget/actual/pull/1150 resulted in codegen'd code being moved to a different package from the definition files from which it was generated. This is incorrect and so we should move these together again.

See https://github.com/actualbudget/actual/pull/1150#issuecomment-1606136335

**Comment by MatissJanis** [comment]
Makes sense. I must have missed this when I created the package.
