### ISSUE TITLE
Hidden Categories on Read Only iOS Mobile

### ISSUE THREAD

**Issue by Kidglove57** [actualbudget/actual#1196]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

If I use Actual, on iOS mobile, zoomed to 85% and in landscape mode, my hidden categories remain hidden.

However, when I am in portrait/read-only mode my hidden categories are still visible.

### What error did you receive?

Hidden categories remain visible on mobile/read only

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Safari

### Operating System

Mobile Device

**Comment by Cldfire** [comment]
If I have a hidden category in the budget view:

<img width="808" alt="Screenshot 2023-08-08 at 7 31 21 PM" src="https://github.com/actualbudget/actual/assets/13814214/b5715d4d-752f-43de-8b9a-424e4ad957fd">

It is hidden when "toggle hidden" is toggled off in the desktop budget view:

<img width="765" alt="Screenshot 2023-08-08 at 7 31 40 PM" src="https://github.com/actualbudget/actual/assets/13814214/0c09b6fe-4176-418d-a3fb-bed9e5056e24">

But in the mobile budget view it's always visible:

<img width="483" alt="Screenshot 2023-08-08 at 7 31 55 PM" src="https://github.com/actualbudget/actual/assets/13814214/066b408b-4194-4936-894b-894f77fee5f3">

@Kidglove57 is that the bug you're describing, or is there something else to it as well?

**Comment by Kidglove57** [comment]
@Cldfire Thank you so much for looking at this! Yes, you have summarised the issue perfectly. Additionally, if I turn my phone to landscape then desktop view kicks in and the hidden category is hidden again.
PS I am loving the new mobile transaction entry!
