### ISSUE TITLE
Wallet App by Budgetbakers Import

### ISSUE THREAD

**Issue by joshuabeny1999** [actualbudget/actual#1198]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I currently using the wallet app by budgetbakers. (https://budgetbakers.com/) Actual seems to be a nice alternative, when also the mobile gets some work done. I mainly use wallet on mobile. It is an app a lot of people I know using and has a lot og downloads so importing for this app would benefit actual for getting user to switch. 

### Describe your ideal solution to this problem

Offer import of wallets CSV or XSLX Exports. I think the bank csv export won't work due it lacking categories, etc. Currently export is only possible via android app: https://support.budgetbakers.com/hc/en-us/articles/7151606064018-How-to-export-transactions-from-Wallet-

### Teaching and learning

Extend migration section of documentation https://actualbudget.org/docs/migration/

**Comment by j-f1** [comment]
If you’re interested in implementing this a good starting point would be our YNAB importer code: https://github.com/actualbudget/actual/blob/master/packages/import-ynab4/importer.js
