### ISSUE TITLE
[Feature] Custom budget periods (e.g., yearly, etc)

### ISSUE THREAD

**Issue by dima-ser** [actualbudget/actual#1201]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

My cash flows vary wildly from month to month so monthly budget is not useful to me. I would love a yearly budget though. 

### Describe your ideal solution to this problem

Ideally the app would allow us to specify the time period over which we want to budget (month, quarter, year, etc). Either granular to monthly (so you can enter the number of months) or just preset to 1, 3, 6, 12 , and 24 months would be fine too.

### Teaching and learning

This could be part of the initial setup wizard where the app asks the user which time period they want to budget for. It can also be in the settings in case users want to change it after.

**Comment by willem-h** [comment]
Would love to even be able to specify a period of every two weeks. This would line up with fortnightly salary payments that happen in a lot of Australia.

**Comment by martipoe** [comment]
I would like to set yearly budgets for categories such as holiday spendings if possible :)

**Comment by ihatetoregister** [comment]
Agree, I would rather have a yearly budget and be able to compare the outcome with earlier years. Monthly is to granular and does not compare well for a lot of expenses like energy cost, vacation or service of vehicle to name a few. I’m more interested in what the average is per month, so I made a simple report that just to sum the whole year and displays the average per month YTD. But the budgeting could do something similar.
