### ISSUE TITLE
[Bug]: Filtering by amount is non-intuitive

### ISSUE THREAD

**Issue by shall0pass** [actualbudget/actual#1215]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When filtering by amount, the filter requires a negative symbol to be present to retrieve the payment field.  I think it would be more intuitive if the filter would capture the amount in either the payment or deposit columns.  There are no negative symbols shown in the table, so it wasn't immediately apparent that it was needed for the filter.

Image showing an account ledger
![image](https://github.com/actualbudget/actual/assets/20625555/3ff5147a-e4ea-42cd-a4dd-3c06d6386afa)

Filtering amount for the top transaction of 92.46.
![image](https://github.com/actualbudget/actual/assets/20625555/6d44efb4-b433-4496-b477-593c3bc94732)

Changed the filter to -92.46 and it now shows the entry.  
![image](https://github.com/actualbudget/actual/assets/20625555/ba30850f-1b8f-42db-9db4-24a57515aa1c)

### Where are you hosting Actual?

NAS

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by shall0pass** [comment]
I didn't realize this dropdown box was available.  I'm going to close this in light of this revelation.

![image](https://github.com/actualbudget/actual/assets/20625555/fbd96b82-f8d0-43b0-aab8-20508beb4f50)

**Comment by Kidglove57** [comment]
Thank you @shall0pas. I've learned something here too!
