### ISSUE TITLE
[Feature] Invert filters

### ISSUE THREAD

**Issue by YagiOoda** [actualbudget/actual#1225]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I'd like to be able to invert a filter, as in filter out categories or accounts. 

An example of this is that on the Cash Flow report, I'd like to filter out the category I use for transferring off-budget to investments. As it is now, I have to manually select all categories with the "one of" filter option except for one.

<img width="302" alt="Screenshot 2023-06-29 at 08 18 34" src="https://github.com/actualbudget/actual/assets/35860689/13d5a874-64fc-47ef-a9eb-19c9b0157ae6">

### Describe your ideal solution to this problem

This could be a new filter option or maybe a slider that inverts the existing options for the next selection.

**Comment by carkom** [comment]
Fixed by #1287
