### ISSUE TITLE
[Bug][release-blocker]: "link schedule" is broken

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#1236]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Link schedule used to open in a modal. Now it opens in a new page. Thus it's broken.

<img width="1204" alt="Screenshot 2023-06-30 at 22 06 31" src="https://github.com/actualbudget/actual/assets/886567/b81a7583-fc83-453e-a96a-13560d95e82e">

### Where are you hosting Actual?

None

### Operating System

None

**Comment by j-f1** [comment]
Probably needs `navigate` replaced with `pushModal`
