### ISSUE TITLE
[Bug]: Transactions list scrolling is jittery

### ISSUE THREAD

**Issue by joel-jeremy** [actualbudget/actual#1241]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Scrolling through the transactions table is a bit jittery and the table itself is moving when scrolling.

https://github.com/actualbudget/actual/assets/20313680/8863b627-ff3d-4bd1-b8d9-0f4147aca6c7

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mobile Device

**Comment by j-f1** [comment]
It looks like something is computing the height of the viewport wrong

**Comment by MatissJanis** [comment]
Related: https://github.com/actualbudget/actual/issues/655

**Comment by j-f1** [comment]
I’m trying to reproduce this locally in both Safari and Chrome (macOS) and am unable to, even if I artificially inflate the number of transactions by 100x. Could there be some factor I’m missing? 

<details>

```patch
From a799a556093d9409c1e3edafae9ac1e1f78288cb Mon Sep 17 00:00:00 2001
From: Jed Fox <git@jedfox.com>
Date: Sun, 2 Jul 2023 12:28:36 -0400
Subject: [PATCH] artificially inflate the number of transactions

---
 .../desktop-client/src/components/accounts/Account.js  | 10 +++++++++-
 1 file changed, 9 insertions(+), 1 deletion(-)

diff --git a/packages/desktop-client/src/components/accounts/Account.js b/packages/desktop-client/src/components/accounts/Account.js
index 998825bf..b995a1f8 100644
--- a/packages/desktop-client/src/components/accounts/Account.js
+++ b/packages/desktop-client/src/components/accounts/Account.js
@@ -1242,7 +1242,15 @@ class AccountInternal extends PureComponent {
 
         this.setState(
           {
-            transactions: data,
+            // artificially inflate the number of transactions
+            transactions: Array(100)
+              .fill(data)
+              .flatMap((ts, i) =>
+                ts.map(t => ({
+                  ...t,
+                  id: `${t.id}-${i}`,
+                })),
+              ),
             transactionCount: this.paged.getTotalCount(),
             transactionsFiltered: isFiltered,
             loading: false,
-- 
2.38.1
```

**Comment by j-f1** [comment]
Alternatively, if you *are* able to reproduce it, I would appreciate if you could run a [`git bisect`](https://stackoverflow.com/q/4713088/5244995) and follow the steps to track down exactly which commit introduced the issue. (Make sure you re-run `yarn install` at each step to make sure you have the right dependencies installed).

**Comment by j-f1** [comment]
@joel-jeremy can you try out #1260 and see if it fixes the scrolling for you too?

**Comment by joel-jeremy** [comment]
I'm still seeing the same behavior.


https://github.com/actualbudget/actual/assets/20313680/763d8057-a0af-482b-ba65-7c98ee7e578b

**Comment by j-f1** [comment]
Ok, I can reproduce that issue now with a very tall and narrow window size. It seems unrelated to the fix in #1260.

**Comment by j-f1** [comment]
Does #1262 work for you?

**Comment by joel-jeremy** [comment]
Nice! That fixed the height of the table. Scrolling is still a bit jittery especially when scrolling fast but UX is better than before with the table height fix.


https://github.com/actualbudget/actual/assets/20313680/dd1cdee0-8f4a-42f0-aa87-f1e85bfcd05c

**Comment by j-f1** [comment]
Alright! I think any remaining jank would be due to your phone not being able to render new rows fast enough.
