### ISSUE TITLE
[Maintenance] Rename "Nordigen" to "GoCardless"

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#1244]
Nordigen has been acquired and integrated in GoCardless. We should rename all usages of "nordigen" to "gocardless".

https://gocardless.com/bank-account-data/

**Comment by MatissJanis** [comment]
Related:
We should also upgrade to `nordigen-node` v1.2.5 once it is released

https://github.com/nordigen/nordigen-node/issues/49

**Comment by itsajay1029** [comment]
I'd love to work on this. Can you assign this to me @MatissJanis ?

**Comment by j-f1** [comment]
Hi @itsajay1029, we generally don’t assign issues to people but feel free to open a PR anyway!

**Comment by MatissJanis** [comment]
Web & server: almost complete. Only remaining to rename `nordigen_secretId` and key id, but those will need some sort of smart migration in the short term.

Docs: needs to be done

**Comment by MatissJanis** [comment]
Docs: done

Final change before closing this issue: https://github.com/actualbudget/actual-server/pull/293
