### ISSUE TITLE
[Bug]: Goals: Unable to close error dialog box if too many errors are present

### ISSUE THREAD

**Issue by shall0pass** [actualbudget/actual#1245]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I know I'm intentionally breaking this, but I ran my goal templates before I had income in my account and was heavily using priorities.  If there are too many errors, the close (x) option to release the error dialog becomes unavailable.  The only way to get back is to zoom out on desktop to expose the close option or refresh the page.  The issue is even less workable on mobile (2nd image).  I had to kill the window and reload the page as my mobile browser doesn't allow zooming in or out.  I had the same interactions on both Windows 11 and Android Chrome.

![image](https://github.com/actualbudget/actual/assets/20625555/56d56e94-02ed-4053-a065-70b3e41366fc)
![image](https://github.com/actualbudget/actual/assets/20625555/dd7c8fae-6906-4bb1-8f1c-9af0ef0ab843)

### Where are you hosting Actual?

NAS

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by youngcw** [comment]
The template code has been changed and wont show warnings anymore starting the next release.  Only confirmations and errors.  Closing this
