### ISSUE TITLE
[Bug]: clicking on the balance does not show/hide cleared/uncleared pill

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#1249]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Clicking on the balance pill is not toggling the cleared/uncleared pill. This is only reproducible on "all accounts" view. Individual account views work as expected.

<img width="507" alt="Screenshot 2023-07-01 at 19 24 00" src="https://github.com/actualbudget/actual/assets/886567/1361f30d-f0a0-4c31-9362-c7f6cf35f2a9">

### Where are you hosting Actual?

None

### Operating System

None

**Comment by Teprifer** [comment]
@MatissJanis Looks like this bug has returned, can it be re-opened? 

Discovered when trying out #2408 (but then confirmed it's present the latest release and few days old edge).

**Comment by MatissJanis** [comment]
This seems to have been patched on edge.
