### ISSUE TITLE
Remove dependency on `@jlongster/lively`

### ISSUE THREAD

**Issue by TomAFrench** [actualbudget/actual#126]
We've got a couple of components in `loot-design` that use https://github.com/jlongster/lively. This seems to be some experiment to create something vaguely hookish in React before there were hooks.

As mentioned in the readme:
> Note: Do not use, or even plan to use, this. I'm just explaining some ideas I have and giving code to back it up. I don't plan on marketing or fleshing out this repo at all.

We should update these components so that we can remove this dependency.

**Comment by MatissJanis** [comment]
Only remaining component using lively is autocomplete. There is work ongoing to migirate it to react-select. See here: https://github.com/actualbudget/actual/issues/773

**Comment by MatissJanis** [comment]
Done
