### ISSUE TITLE
[Feature] Make categories on the mobile budget page clickable

### ISSUE THREAD

**Issue by j-f1** [actualbudget/actual#1261]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

On desktop, cells in the “spent” column of the budget page can be clicked to show a list of transactions in that category for that month. There is no way to see this page on mobile. (Additionally, opening this page on desktop then switching to mobile just displays the list of accounts)

### Describe your ideal solution to this problem

Make some part of the row clickable. Maybe the name of the category?

### Teaching and learning

Not sure. It would be important to make the clickable element obviously clickable. Maybe clicking on the category name could show options for adding a note/renaming/deleting/showing transactions?

**Comment by youngcw** [comment]
Closing in favor of #2018
