### ISSUE TITLE
[Feature] Add button to add the remaining split amount as a split transaction

### ISSUE THREAD

**Issue by j-f1** [actualbudget/actual#1273]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

When entering a new split transaction, an indicator shows how much money is left to be allocated to a split. There should be a way to create a new split with this exact amount quickly.

### Describe your ideal solution to this problem

- Add a button to do this
- Automatically set the amount of a newly created split to the remaining amount, allowing the user to edit it if they want more splits
- other options?

**Comment by youngcw** [comment]
Added #2151
