### ISSUE TITLE
[Bug]: Multiple budgets, only newest one opens

### ISSUE THREAD

**Issue by andrewt918** [actualbudget/actual#1274]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When multiple budget files are present, closing a file and attempting to load a different one always loads the most recently added file regardless of selection. I've tested this with importing two YNAB4 budgets as well as just importing one and creating one new one. In each case, the second is opened no matter what file is selected.

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by j-f1** [comment]
Are you accessing the server via `localhost` or another domain? Do you have to click through a warning about `SharedArrayBuffer`?

**Comment by andrewt918** [comment]
actual-server is hosted on a local Ubuntu VM and yes, I do have to click through the SharedArrayBuffer warning. Looks like that will require HTTPS which wasn't a priority for LAN usage. Is this necessary for multiple budget selection to work?

**Comment by j-f1** [comment]
Yes, one of the known bugs with the fallback mode you get if you don’t use HTTPS is that your budgets will get merged together. (This is why we have that warning!)
