### ISSUE TITLE
[Tech Debt] Refactor "Select" component usage to "CustomSelect"

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#1275]
We currently have 2x Select components - Select & CustomSelect.

The goal would be to remove the Select component in favor of CustomSelect/Autocomplete.

This would make all the select-s in the app have a consistent UI and UX.

**Comment by biohzrddd** [comment]
Agreed we need just one. The CustomSelect component from the reach package is quite a pain to style (e.g. I can't figure out how to get rid of the blue flashes in #922) and doesn't offer much that I can see over the built-in Select. Can we not style the built-in good enough?

**Comment by j-f1** [comment]
Still one more: 

https://github.com/actualbudget/actual/blob/927c859456475b98611c9078a4657dcaacc156a5/packages/desktop-client/src/components/modals/ConfirmCategoryDelete.js#L80-L99

https://github.com/actualbudget/actual/blob/927c859456475b98611c9078a4657dcaacc156a5/packages/desktop-client/src/components/autocomplete/CategorySelect.tsx#L22-L44
