### ISSUE TITLE
[US Banking Integration] Add additional integration with Sophtron & Plaid

### ISSUE THREAD

**Issue by jinB2021** [actualbudget/actual#1278]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Importing bank data for high-profile banks from US/Canada isn't available through Nordigen/GoCardless. Having options to integrate through [Plaid](https://plaid.com/) or [Sophtron](https://sophtron.com/) would go a long way in terms of automation/sync of banking history compared to manually porting OFX, QFX or CSV data.

### Describe your ideal solution to this problem

We can probably follow a similar pattern to Nordigen implementation, update the UI to accept API tokens for Plaid or Sohptron(maybe this can be behind a set of toggles?) and update data models to factor in the type of responses we might anticipate from the API calls. For MVP#1, we can try grabbing data from a few endpoints only and if there is a need for more we can add additional endpoints.

### Teaching and learning

API's:

- [Plaid](https://plaid.com/)
- [Sophtron](https://sophtron.com/)

**Comment by j-f1** [comment]
Related: #898. The main tasks that would need to happen:

* Update the frontend to support configuring multiple bank sync providers
* Implement Plaid/Sophtron support on the server (this may be already started, or somewhere in the git history for Plaid)
* Add the relevant functionality to the frontend

**Comment by jinB2021** [comment]
@j-f1 is the issue being actively worked on? If not I can give a crack at it.

**Comment by j-f1** [comment]
Closing this issue as a duplicate to centralize discussion.
