### ISSUE TITLE
Rules page fails to load after merging payee with a Schedule

### ISSUE THREAD

**Issue by kitforbes** [actualbudget/actual#128]
Nice project. Started using it recently and enjoying it so far.

I just merged the transactions from one payee into another, and now the rules page for this particular payee won't load. No idea how to recreate the issue but now if I go to "Manage Payees", search for the payee, select "n associated rules", I'm taken to a blank white page. There are no requests in my browser's dev tools, and no logs in the Docker container that I am aware of.

If I select "Manage rules" instead of "Manage payees", I am taken to the blank white page right away. I'm going to assume that the rule data for this payee is now corrupt. Is there another way to get at the data to remove the associated rules?

**Comment by kitforbes** [comment]
I solved this, but it does appear to be an issue.

I had a Schedule associated with the old Payee. I deleted it and then I was able to view rules once again. Feel free to close this issue.

**Comment by rich-howell** [comment]
@kitforbes are you able to test this is still a thing in the latest version of Actual? I have tried to replicate but was unable.

**Comment by rich-howell** [comment]
Hey @kitforbes 

I am going to go ahead and close this issue out, if you are still having a problem please let us know and we can re-open it. 

Cheers
Rich
