### ISSUE TITLE
[Bug]: saved filters are not sorted

### ISSUE THREAD

**Issue by Kidglove57** [actualbudget/actual#1284]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I love the new saved filters! So much so that I have already created thirteen of them. However, these remain listed in the order that I created them. It would be ideal if they could list in alphabetical order.

### What error did you receive?

Saved filters are not listed in a logical order

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Safari

### Operating System

Mac OSX

**Comment by avinashji1302** [comment]
Please assign me this issue!
