### ISSUE TITLE
[Bug]: View Saved Filters on Mobile

### ISSUE THREAD

**Issue by Kidglove57** [actualbudget/actual#1285]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I am using Actual on iPhone in desktop mode and zoomed to 85% (landscape orientation). Saved Filters cannot be searched or viewed. This is a minor quality of life issue since as yet we do not have a fully responsive mobile versiono

### What error did you receive?

Searching saved filters on mobile gives a result of "nothing"

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Safari

### Operating System

Mobile Device

**Comment by trevdor** [comment]
Could you try this again on the latest version, @Kidglove57? 
I've been unable to reproduce on v23.8.1. My saved filters populate the dropdown when viewed on mobile in landscape.

**Comment by Kidglove57** [comment]
Thanks for looking into this @trevdor  I am very pleased to confirm that this is working for me, as expected, in the latest version, on mobile, in landscape orientation.

**Comment by Kidglove57** [comment]
I am therefore very happy for this issue to be closed.
