### ISSUE TITLE
[Bug]: CustomSelect does not have a scrollbar

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#1286]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

The `CustomSelect` component does not have a scrollbar. So sometimes you end up in a situation such as this..

<img width="183" alt="Screenshot 2023-07-05 at 08 36 52" src="https://github.com/actualbudget/actual/assets/886567/56eb6e8e-6315-4a10-8eba-78138a48793b">

To consider: perhaps the existing `CustomSelect` component just doesn't cut it? Perhaps we should move to react-aria (while still keeping the same look & feel)?

### Where are you hosting Actual?

None

### Operating System

None

**Comment by aleetsaiya** [comment]
Hi, I'm currently try to refactor some usages of `Select` component to `CustomSelect` component.

I've created a PR to change some part of the code inside `CustomSelect` component. I add `style={{ maxHeight: 250, overflowY: 'scroll' }}` to make is scrollable. But I don't really sure it's a good approach.

Here's the reference for my changed in `CustomSelect` component:
https://github.com/actualbudget/actual/pull/1277/files#diff-07149e52bf936b1efc7e9568048f8891bb85e018083816f3897625995e34badbL20-R40

**Comment by MatissJanis** [comment]
That's great @aleetsaiya !

I've added your fix in this PR just so we could get it out a bit quicker: https://github.com/actualbudget/actual/pull/1294

Hope you don't mind.
