### ISSUE TITLE
[Bug]: Sync error after upgrade to v23.7.1

### ISSUE THREAD

**Issue by joel-jeremy** [actualbudget/actual#1296]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Upgraded to v23.7.1 and now I'm getting this error when I'm syncing:
![image](https://github.com/actualbudget/actual/assets/20313680/3cabc44c-8f68-45ad-9bfc-1b48c975ebfc)

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by j-f1** [comment]
Did you previously run 23.7.0?

**Comment by joel-jeremy** [comment]
Yes, I did. I was able to workaround the problem by exporting my 23.7.0 file and importing on 23.7.1.

**Comment by MatissJanis** [comment]
I managed to reproduce a version of this.

Steps:
1. downgrade to a older version (for example v23.4.0)
2. create a new budget
3. create a new account
4. sync it to the server
5. upgrade to latest version
6. start the server
7. local version will load without issues
8. open a new incognito window and connect to the server
9. download the budget
10. it will break

Issue:
```
Error: no such column: type in table accounts
```

**Comment by MatissJanis** [comment]
The very easiest solution we could do is: create a new migration that adds back the `type` field. We won't be using it.. but it would solve this problem.

**Comment by kekwkappa** [comment]
I I have solved the problem for myself by creating data export and importing it.
