### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by gbdavidx** [actualbudget/actual#13]
Hi,

Im on debian 11 with most recent git and npm version

i tried to install after cloning the repository and am getting the following error;
Error: [Erno 2] No such file or directory: install

**Comment by cuken** [comment]
Solved in discord;

For others that run into this try `npm install -g yarn` -> relaunch terminal and try again.

**Comment by rich-howell** [comment]
This has been resovled, readme updated with information from [here](https://github.com/actualbudget/actual/issues/13#issuecomment-1113920856) thanks @cuken
