### ISSUE TITLE
Add ability to manually enter single transaction

### ISSUE THREAD

**Issue by SaveYourMoney** [actualbudget/actual#1310]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Currently when entering transactions manually, after entering the details of the transaction, the user has the option to either hit the Enter key or to click the "Add" button.  When either of these is done, the transaction is entered and new, blank transaction is opened.  
If a user wishes to enter only a single transaction for the account they are currently in, the only way to do this is to hit enter or click add, and then hit the Escape key twice to close the blank transaction.
This is somewhat related to #1301 that points out how a transaction could be mistakenly entered in the wrong account because of the fact that the new open transaction persists while moving between account.

### Describe your ideal solution to this problem

I propose that a new method be added to enable the entry of a single transaction by either hitting Shift+Enter or CMD+Enter.  Another option would be to add another button in this area in addition to the "Add" button, similar to YNAB 4, which has a "Save and New" as well as a "Save and Close" button in the data entry area.

**Comment by shawalli** [comment]
Alternatively, add another button that differentiates between "Add" and "Add and Start New Transaction" (this is how YNAB 4 did it).
