### ISSUE TITLE
[Feature] Add subcategory

### ISSUE THREAD

**Issue by andreapx** [actualbudget/actual#1320]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I feel the need to divide some expenses into subcategory.
For example for leasure I would like to have a group called _leasure_, then add a category _rent_ and a subcategory _expenses_
Or another example:
 --> house
 ---->bills
 ------>electricity
 ------>Internet
 ------>Insurance
 ------> ...
 ---->furniture
 ---->...
...

### Describe your ideal solution to this problem

Add the possibility to add a subcategory (maybe with multiple levels)

**Comment by normanu** [comment]
Would love this aswell!

**Comment by carkom** [comment]
Could this be remedied with tags? I can see a use case where you could tag the smallest tier and be able to use it all successfully. Thoughts?

**Comment by binarygituser** [comment]
> Could this be remedied with tags? I can see a use case where you could tag the smallest tier and be able to use it all successfully. Thoughts?

tags could work in scenarios where we need to search/filter. Another advantages with tags is to ability to tag expenses that are related/similar but fall under different categories. For ex. Child1 and Child2 going to different clubs, all of those budgeted as Fun Activites but tagged per child. Will be good if reports can pick up expenses that are tagged.

**Comment by danielo515** [comment]
I think I will like more the ability to use tags, or be able to assign  several cathegories

**Comment by bchooxg** [comment]
+1 for this feature

I would like to track my food spendings ( $300 per mth )
But also like to be able to categorize how much i spend for each meal ( Breakfast, Lunch, Dinner )

-Food
— Breakfast
— Lunch
— Dinner

**Comment by mailuminatti** [comment]
+1 for this feature!

**Comment by CrazyKidJack** [comment]
Infinite nesting please!

**Comment by Hydro8** [comment]
I vote for tags, it could be awesome to add a feature like this.

You have your classical categories like food... and for special event you could use categories with tag.
This way on report, you can filter transactions and categories to see what you need.

Very helpful feature !

**Comment by Hydro8** [comment]
Awesome :)

I didn't find a way, but is it possible, in custom reports, to filter by transaction's tag ?

**Comment by Hydro8** [comment]
Very nice ! Thanks to both of you. 

Actual Budget is really a step above YNAB with feature like this.

Just a question, is it possible to add tag to a category ?
For example, I have multiple leisure categories and I tried to add #leisure to them.

Then in custom report, I tried to filter by category "has tag" but I have errors.

**Comment by thiswillbeyourgithub** [comment]
Hi. I don't get it. This seems to have been implemented but I can't find in [the documentation](https://actualbudget.org/docs/transactions/filters#how-to-use-the-filter-tool) nor in the UI. Am I missing something? I'm using 24.10.1

**Comment by youngcw** [comment]
@thiswillbeyourgithub This request is still open as a feature request and has not been added yet

**Comment by ElDubsNZ** [comment]
Absolutely support this. Being able to set arbitrary levels of nested categories is a feature that double-entry bookkeeping allows, and I want to see Actual align with how that works as much as possible so the systems could be compatible.

**Comment by atticcat** [comment]
This is something I am really hoping to see implemented. An example of how it would be useful for me - subscriptions/memberships. Particularly when annual subscriptions which are all paid out at different times of year get involved, it can be pretty challenging to make sure you're budgeting the right amount, and have the right amount already saved, for everything when it's all in one subscriptions category. The better solution is to have a category for each annual subscription which is able to accrue budgeted money the entire year and accurately show the amount allocated for that subscription in the lead up to the date it is actually paid for.

The current solution, of course, is to just have Subscriptions as its own group, and each annual subscription as a category within it. But if I have multiple categories needing sub categories, which have to be their own groups under this scheme, this quickly leads to a real mess of a budget. It also makes it so I can't have my Subscriptions in general as part of a larger group, like "Discretionary Spending," which I can be tracking overall spending on.

All that to say, this would be a great boon to organized budgeting in my mind and I would have immediate use cases for it if implemented.

**Comment by gitchap** [comment]
@atticcat I use the templates to keep track of what's needed and make sure I'm budgeting the right amount. But I also have a category for each sub, within a subscription group. I have considered using one category and just having several templates for it.

If there were nesting groups, I would probably use them, but honestly an implantation with tags might be more useful. 

YNAB has category filters, which is similar to how tags might work.

**Comment by XtremeOwnageDotCom** [comment]
This- would drastically improve management for me.

**Comment by ApertureEngineer** [comment]
I also want a thumbs up for this feature. I'm dealing with my finances now since 2006 just with Excel. Tried so many tools but Excel was the most flexible way until now.

If actual can have Categories and subcategories or would be a game changer. 

Regarding the Tags. I use Cost Centers to book the expenses.

Here the example: 
Transaction: Hotel (7 nights) 
  | Category: Holiday 
       | Subcategory: accommodation 
          | Cost Center: Indonesia_2025

So I can easily sum up all costs per holiday. 
But also can calculate the accommodations per year. If you travel a lot, you will see that once you are not at home you need less budget for the house and eating.

**Comment by AndyDaSilva52** [comment]
> subscriptions/memberships. Particularly when annual subscriptions which are all paid out at different times of year get involved, it can be pretty challenging to make sure you're budgeting the right amount, and have the right amount already saved, for everything when it's all in one subscriptions category.

@atticcat as mentioned by @gitchap you could use the template feature

There is an example in the docs exactly with your case. [Budget Templates | Actual Budget Documentation](https://actualbudget.com/docs/experimental/goal-templates#multiple-template-lines) and with the `by YYYY-MM-DD` you can set a budget for a yearly subscription.

After trying this, in most cases, I would prefer the template over a third or more levels of category. It forces you to simplify your budget.

Also, contributing to the discussion:

There is a complexity that might appear with the implementation of a third or as many levels you want (like double entry bookkeeping/GNUCash). 
So, independently of how many levels, I suggest defining the Budgeted Value only in the nested categories of the tree. This seems like the most reasonable option.

| Category       | Budgeted       |
|----------------|----------------|
| House          | =105      |
| - Bills        | =80       |
| -- Electricity | =80       |
| --- House A    | Budgeted 50    |
| --- House B    | Budgeted 30    |
| -- Internet    | Budgeted 10    |
| -- Insurance   | Budgeted 10    |
| -- ...         | ...            |
| - Furniture    | Budgeted 5     |
| - ...          | ...            |

**Comment by BobWs** [comment]
> We do already support tags inside the 'notes' field of a transaction! Just start with a #. Does that help?

I recently discovered that tags are already supported, which is great! However, I have a suggestion for improving their appearance and functionality.

Currently, when I assign a tag to a transaction, it appears as `#bills` with a colored background. It would be much cleaner if it could simply display as "bills" with the colored background.

Additionally, it would be helpful if we could customize the colors of the tags. Perhaps this feature could be integrated into the settings, allowing users to pre-create tags with their chosen colors.

**Comment by DiegoTheWolf** [comment]
This would greatly go together with the templates.
Giving a parent category a budget and use templates to populate sub categories accordingly (with factors or splits)

**Comment by astro-msk** [comment]
Started using Actual recently, and I though this would be an existing feature.
Hence, I would love to have this feature. Me being a dev, I could also contribute in implementing this feature.

**Comment by jcasanchez** [comment]
I just started using actual and would like to see the feature

**Comment by matttk** [comment]
I'm not even sure how to budget properly without this feature. There's no way I can keep track of what makes up the final number for a budget category, so I guess the only solution is categories and groups (which limits to only 2 levels).

Living Actual so far - but this feels like a pretty critical feature that YNAB had from the start.

**Comment by kennyrkun** [comment]
Similar to this, I would like to be able to keep track of what parts of a single transaction go to a particular category. For example, a trip to Costco may have purchases including entertainment, groceries, medicine, clothing, all in a single transaction.

**Comment by atticcat** [comment]
> Similar to this, I would like to be able to keep track of what parts of a single transaction go to a particular category. For example, a trip to Costco may have purchases including entertainment, groceries, medicine, clothing, all in a single transaction.

@kennyrkun This is already a feature - just choose "split transaction" when you choose the category for a transaction.

**Comment by kennyrkun** [comment]
> > Similar to this, I would like to be able to keep track of what parts of a single transaction go to a particular category. For example, a trip to Costco may have purchases including entertainment, groceries, medicine, clothing, all in a single transaction.
> 
> @kennyrkun This is already a feature - just choose "split transaction" when you choose the category for a transaction.

That is absolutely brilliant, thank you! I was looking for "multiple transactions grouped" and couldn't find anything using those search terms. I'm so glad Actual can do this!

**Comment by PencilKnot** [comment]
I am currently working on implementation of [focused groups (similar to those in YNAB)](https://github.com/actualbudget/actual/issues/4090) whose feature request I noticed linked back to this feature. Not sure if it would be useful to anyone here but theoretically would add another layer of categorization.

**Comment by savissimo** [comment]
Would you accept contributions on this feature? I'm not promising anything, I still have to download the code and set up a dev environment, just to know if it would be allowed/interesting before starting work on it.

**Comment by ReticentEclectic** [comment]
I'm currently developing this feature for myself, not 100% finished yet, but all the major functional pieces are in place. Groups can be nested at arbitrary depths, and group nesting can be done via drag-and-drop or a group's context menu.


If anyone wants to check out my work. [Here's the link to my fork — Nested Category Groups](https://github.com/ReticentEclectic/actual) I would greatly appreciate anyone's feedback.
