### ISSUE TITLE
[Feature] Import transaction on synchronized account

### ISSUE THREAD

**Issue by andreapx** [actualbudget/actual#1321]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I've setup 3 accounts with Nordigen (GoCardless) but it has imported only a few transactions.
It would be nice to be able to import past transaction into synchronized accounts

### Describe your ideal solution to this problem

Import transaction on synchronized accounts to0.

### Teaching and learning

I think that this is a problem that almost everyone has.

**Comment by matt-fidd** [comment]
This has now been added
