### ISSUE TITLE
[Feature] Support for CSV files without a header row

### ISSUE THREAD

**Issue by tywjohn** [actualbudget/actual#1326]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

It would be nice for the import CSV feature to allow for the possibility that the CSV does not contain a header row

### Describe your ideal solution to this problem

A simple tick box in the CSV import window to ignore header the first row (header) if one exists.
Whether a header row exists or not, the user should be given the option to assign a purpose for each column instead of the current implementation which tries to assign values from the first row.
An example can be seen from GnuCash (although it looks as though GnuCash assumes there is no header row).
https://wiki.gnucash.org/wiki/CSV_Import/Export
https://imgur.com/F17CZwK

### Teaching and learning

This should be obvious to the user when importing a CSV file.

**Comment by clonejo** [comment]
This has been implemented, label "needs votes" is on this issue by mistake?

**Comment by MatissJanis** [comment]
Thanks @clonejo . Tag removed
