### ISSUE TITLE
[Bug]: Viewing an account with a scheduled "is between" transaction generates a fatal error. 

### ISSUE THREAD

**Issue by adamkelly86** [actualbudget/actual#1328]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Steps to replicate

1) Create a scheduled transaction between two accounts and set this to "Automatically add transaction"

Example: Choose to move money between one account to another
Set Payee as the receiving account 
Set Account as the sending account 
Set the Amount to "is between" and enter two values that differ (added following kidglove57's comment on non-replication)

2) Go to the receiving account and check the box next to the Scheduled transaction that is upcoming to generate the error

I have reset budget cache and reset sync in an attempt to clear the issue locally. 

### What error did you receive?

Error: safeNumber: number is not an integer: null at m (https://redacted.URL/static/js/main.6ae08084.js:2:231825) at v (https://redacted.URL/static/js/main.6ae08084.js:2:232072) at o (https://redacted.URL/static/js/main.6ae08084.js:2:137255) at lo (https://redacted.URL/static/js/main.6ae08084.js:2:710141) at ja (https://redacted.URL/static/js/main.6ae08084.js:2:431693) at jl (https://redacted.URL/static/js/main.6ae08084.js:2:488806) at bu (https://redacted.URL/static/js/main.6ae08084.js:2:477912) at vu (https://redacted.URL/static/js/main.6ae08084.js:2:477840) at yu (https://redacted.URL/static/js/main.6ae08084.js:2:477703) at au (https://redacted.URL/static/js/main.6ae08084.js:2:474483)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 10

**Comment by Kidglove57** [comment]
It seems that there may perhaps be something else going on here? 

I have followed your instructions, setting up a scheduled monthly inter account transfer, starting from tomorrow, and then selected this in the receiving account. However, I have been unable to replicate the error in Safari or in Chrome. I am hosting on Fly and using a Mac.

Possibly someone out there who is more technical may be able to interpret the error message.

**Comment by adamkelly86** [comment]
Looks like this bug has expanded to the sending and receiving accounts since v23.8.0

Show Error
Error: safeNumber: number is not an integer: null at m (https://redacted.URL/static/js/main.f758b66a.js:2:298232) at v (https://redacted.URL/static/js/main.f758b66a.js:2:298537) at https://redacted.URL/static/js/wide-components.6cb72932.chunk.js:1:110759 at Ca (https://redacted.URL/static/js/main.f758b66a.js:2:497928) at Tl (https://redacted.URL/static/js/main.f758b66a.js:2:509616) at Cl (https://redacted.URL/static/js/main.f758b66a.js:2:508822) at Cs (https://redacted.URL/static/js/main.f758b66a.js:2:558423) at wu (https://redacted.URL/static/js/main.f758b66a.js:2:544147) at vu (https://redacted.URL/static/js/main.f758b66a.js:2:544075) at yu (https://redacted.URL/static/js/main.f758b66a.js:2:543938)
