### ISSUE TITLE
[Feature] Resizable columns in account views

### ISSUE THREAD

**Issue by hallboyone** [actualbudget/actual#1330]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I am a new user with a locally hosted actual-server running, and I don't see a way to resize the column sizes in the account view. When large payments/running balances are made, this will clip their values (see screenshot below). I'd like to just resize the columns but, again, I don't think that is an available feature. This is a minor annoyance, but it feels counter to the UX of Actual. 
![Screenshot 2023-07-11 at 9 18 29 PM](https://github.com/actualbudget/actual/assets/43862841/73127f8f-f257-48ba-88e6-dd223b6346cb)

### Describe your ideal solution to this problem

1. Faint lines between column descriptions that can be clicked and dragged to resize the column.
2. Resize the font down to some minimum value if text will be clipped.

**Comment by Thiago-Morais** [comment]
looks like a duplicate of #536
