### ISSUE TITLE
Autosync nordigen integration automatically or via script

### ISSUE THREAD

**Issue by alekslyse** [actualbudget/actual#1332]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

In the documentation, you have to click sync to sync the Nordigen transactions. Is the sync button exposed over the API so I can create a script that triggers sync regularly?

**Comment by youngcw** [comment]
There is an api call now to run the bank syncing.  Ill close this since that was an option.
