### ISSUE TITLE
[Feature] Budget templates: Modal to confirm or override budgets that will be applied

### ISSUE THREAD

**Issue by joel-jeremy** [actualbudget/actual#1337]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Before applying the budget template, show a modal which displays the categories and the budgets that are going to be applied to each. Budget amount should also be editable to allow user to override the budget template.

**Comment by diktomat** [comment]
> Or maybe inline apply the budgets to the budget table but set the budgets as somewhat "pending". Actual could then display a ✔️ and ❌ buttons somewhere in the screen to commit or cancel the application of the budget template.

I think this would be much better than a modal, as one can see the context (other months, available amount) while reviewing.
