### ISSUE TITLE
[Feature] Allow transfers in split transactions

### ISSUE THREAD

**Issue by joel-jeremy** [actualbudget/actual#1339]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

When doing transfers that have fees, users have to create a separate transaction for the fee. It would be nice if users could create a split transaction with the transfer and the fee bundled together.

### Describe your ideal solution to this problem

Allow transfers in split transactions

**Comment by youngcw** [comment]
This is possible in all the ways I've tried.  Are there cases that don't allow a transfer and charge in a split? If not we should close this.

**Comment by joel-jeremy** [comment]
Thanks for the reminder. This has been resolved by https://github.com/actualbudget/actual/pull/1573 and can be closed. :)

**Comment by youngcw** [comment]
Closing
