### ISSUE TITLE
[Feedback] Privacy mode

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#1360]
Author: @joel-jeremy 

Original PR: https://github.com/actualbudget/actual/pull/1272

This feature must be enabled as an experimental feature.

--

Please post your feedback and or bug reports as comments to this issue.

**Comment by MatissJanis** [comment]
**bug**

privacy mode is not masking balances in the "reports" page

**Comment by shall0pass** [comment]
Privacy mode isn't masking values in the schedules page.  I'm not sure if this is intentional or not.

**Comment by Crazypkr1099** [comment]
Privacy mode needs to completely mask out number, ATM it's extremely easy to see how much people have  since the blurring effect is very light. Increasing the blurring effect and potentially changing the numbers to be gibberish would severely make this feature better.

**Comment by shall0pass** [comment]
I don't understand the comment about being able to read the values.  If I were casually walking by and glanced at a screen, there is absolutely no way I could read this.  I asked someone today to try to read it not knowing what was behind it.  He got real close, squinted, removed his glasses, and probably tried crossing his eyes.  He couldn't read it.  Can you provide an example where it is easy?  Maybe there's a rendering difference between our browsers?
![Screenshot_20230809-174004-838](https://github.com/actualbudget/actual/assets/20625555/8ec267a2-b763-41bd-b586-e57c3ef9eddd)

**Comment by joel-jeremy** [comment]
Thats a good point. Maybe the blur is being rendered differently by the browser? Would a setting which adjusts the global blur intensity help with this?

**Comment by joel-jeremy** [comment]
> Privacy mode isn't masking values in the schedules page. I'm not sure if this is intentional or not.

I haven't worked on the schedules page yet. I'll address this in a future PR. Thanks!

**Comment by joel-jeremy** [comment]
Ideas/items for succeeding PRs for privacy mode:

- Unblur the entire row when the row is hovered over (both in budget and transactions tables)
- Fix the clipping on the right side of the blur on Spent and Balance budget table columns.
- Add a toggle to unblur the budget table (leave account totals blurred). Maybe put an eye icon on the budget table header columns which shows up on hover?

**Comment by SaveYourMoney** [comment]
> I don't understand the comment about being able to read the values. If I were casually walking by and glanced at a screen, there is absolutely no way I could read this. I asked someone today to try to read it not knowing what was behind it. He got real close, squinted, removed his glasses, and probably tried crossing his eyes. He couldn't read it. Can you provide an example where it is easy? Maybe there's a rendering difference between our browsers? ![Screenshot_20230809-174004-838](https://user-images.githubusercontent.com/20625555/259567298-8ec267a2-b763-41bd-b586-e57c3ef9eddd.png)

While I agree that it isn't easy to read, I was able to pop into my budget yesterday and glance at a blurred amount that I intentionally had not seen recently and was able to read it to the point where I was only off by one digit.  The amount was $1,929.39 and with little effort I guessed it to be $1,929.29.  Perhaps different browsers provide different results. I am using Brave.

The other thing that I don't like is that it is trivial to see how many digits are being blurred.  With a quick glance anyone can tell whether the masked amount is in the 3, 4, 5 or 6 digit range.

Love the idea though, just feel it could be taken a step further.  Thanks!

**Comment by MatissJanis** [comment]
Feel free to submit a PR for this.

If you don't know how to code: feel free to open a feature request and lets see if the community likes the idea and if someone else is willing to pick it up.

**Comment by jnimmo** [comment]
Appreciate all work by Actual's contributors, personally this isn't a feature I see myself using so the extra button just makes the display a bit busier, might've been okay to stay as an experimental feature?
