### ISSUE TITLE
[Bug]: CSV import skips first line

### ISSUE THREAD

**Issue by master-bobo** [actualbudget/actual#1364]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When importing transactions from a CSV file downloaded from my bank, Actual reads the first line to select what info goes to each column. The first line is not used as a transaction.

My bank does not provide headers on the first line in the CSV file.

Temporary fix is to edit the CSV file manually and copy the first line so the transactions start at line 2.

Possible fix would me the option to tell Actual that the CSV file does not contain headers and should import transactions from the first line.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Windows 11

**Comment by j-f1** [comment]
Thanks for opening this issue! We’re tracking support for headerless CSV files at https://github.com/actualbudget/actual/issues/1326 — please 👍 that feature request.
