### ISSUE TITLE
[Feature] Show actual approximate amount thresholds in UI

### ISSUE THREAD

**Issue by kyrias** [actualbudget/actual#1365]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

When creating a schedule with the amount set to "is approximately" there is no way to know what the actual thresholds that will actually be used are, so you can't know whether your expected transactions will match the rule as written.

### Describe your ideal solution to this problem

Showing the actual bounds on the rule edit page and when hovering over the amount in the rules table.

**Comment by j-f1** [comment]
This is a good idea! For dates, it looks like it’s ±2 days:

https://github.com/actualbudget/actual/blob/717de22f583dbeb79f3ad5c8d7b8fe9d8a1701d5/packages/loot-core/src/server/accounts/rules.ts#L298-L302

For numbers, it’s ±7.5%.

https://github.com/actualbudget/actual/blob/717de22f583dbeb79f3ad5c8d7b8fe9d8a1701d5/packages/loot-core/src/shared/rules.ts#L222-L224

https://github.com/actualbudget/actual/blob/717de22f583dbeb79f3ad5c8d7b8fe9d8a1701d5/packages/loot-core/src/server/accounts/rules.ts#L318-L322

**Comment by SimonMayerhofer** [comment]
I'd prefer to be able to set that amount myself. Because I notice, that every month there are quite a lot of transactions which are not within the 2 day treshhold. So I'd actually like to set it to 7 days so it matches more of my transactions.
