### ISSUE TITLE
[Bug]: Critical Monthly "To Budget" Calculation Issue

### ISSUE THREAD

**Issue by pcchristie** [actualbudget/actual#1377]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Hi Guys,

This is a bit hard to explain and I can't even really nail down what's happening. There is an issue where "To Budget" is consistently calculating incorrectly

It seems to be two things: 
1. "From last month" is not equalling what I actually hold over from last month.
2. Additionally, the calculation seems flat out wrong even in and of itself. e.g. 0 income + $172 held from last month = $260 available funds. 

Example: 
![image](https://github.com/actualbudget/actual/assets/105041457/fcd78938-fd8e-48b4-a825-870b426b4ad6)

![image](https://github.com/actualbudget/actual/assets/105041457/6da6b349-1c6e-46b8-af2e-aef8588c9649)

Few interesting notes
I reset the cache and fixed all the incorrect errors, now I have $400 leftover from historical months as far as I can scroll. On second look, refreshing the page makes this vanish and show different numbers. I can refresh again and get different numbers again.
Sometimes just clicking in and out of cells and not changing any data will change the numbers up top.
Changing figures to rectify what seems to be my incorrect budgeting re-calculates the numbers up top *incorrectly in a different way*.

Thanks guys

23.7.2 via PikaPods

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 11

**Comment by youngcw** [comment]
"From Last Month" includes both the held funds and the leftover "To Budget" funds.  So in your first picture the "From Last Month" value is correct.  The second one is definitely weird though.

**Comment by MatissJanis** [comment]
👋 Are you able to reproduce this on the demo instance?

https://demo.actualbudget.org/

If so: could you please export the budget and upload here. And then give me detailed instructions how to reproduce? So far I've not been able to reproduce this issue.

**Comment by MatissJanis** [comment]
Closing this off due to inactivity. Without a way to reproduce there's not much we can do to help here.
