### ISSUE TITLE
[Feature] Implement Restfull API so that I can integrate with Home Automation or other home server tools 

### ISSUE THREAD

**Issue by faspina** [actualbudget/actual#1384]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Restful API with token so that I can push and pull data utilizing home automation and other local server apps that I have. 

### Describe your ideal solution to this problem

Set of Restful API calls. 
PutTransaction
GetTransaction
etc.

**Comment by j-f1** [comment]
We’ve discussed doing this before, but it’s complicated by the way Actual runs — the server doesn’t actually have the ability to open up a budget file and view/make changes to it. Additionally, budget files take a nonzero amount of time to open, sync, and close so any API would likely have disappointing performance or be very tricky/un-RESTful to use.

I think your best option would be to run your own program that uses our existing JS API package to respond to requests and make any modifications to the budget that are requested.

**Comment by jhonderson** [comment]
I created a project to achieve something similar, an Actual http api: https://github.com/jhonderson/actual-http-api.

It has the following limitations, but for common uses cases (self-hosted, single Actual server, non concurrent access) it should be sufficient:
1. A running instance is tied to a single Actual server 
2. It doesn’t support accessing multiple budgets concurrently

**Comment by faspina** [comment]
This is cool, I will give it a try.
