### ISSUE TITLE
[Feature] Category spent view doesn't show whether transaction was scheduled

### ISSUE THREAD

**Issue by kyrias** [actualbudget/actual#1386]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

On the Budget page if you click on the Spent column of a category the resulting list does not mark scheduled transactions as such.

**Comment by youngcw** [comment]
Im going to change this to be a bug instead of a feature request.
