### ISSUE TITLE
[Bug]: Wrong Calculation of some spendings when opening Actual on Mobile Device

### ISSUE THREAD

**Issue by LimesRunner** [actualbudget/actual#1393]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When I open Actual (which is running on my Synology NAS via Docker) via Browser on my Smartphone, some calculations of spendings seems to be wrong. When I open Actual on my Laptop via Browser, everything seems to be right. I wonder, how this can happen, as the calculations and everything should run on the server, not on the client, or am I wrong here?
It also does not happen to all spendings, some are correct, some are wrong.

Here is an example (Remark: I switched to Desktop View on my Smartphone, to check, whether this issue is caused by the mobile view - it is not.):

Screenshot from Smartphone:
![image](https://github.com/actualbudget/actual/assets/127417356/ccee8893-807b-46f9-9676-5daa5be5ca72)

Screenshot from Desktop:
![image](https://github.com/actualbudget/actual/assets/127417356/c5be0ac4-b8d6-4210-b969-ca9e3402135b)

When I click on my Smartphone on the spending (the -402,85 in my example), the calculation fits to the calculation on my Desktop:
![image](https://github.com/actualbudget/actual/assets/127417356/4e45b50e-9b61-4294-8fdb-3ba8f72f912f)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mobile Device

**Comment by Kidglove57** [comment]
I don't have technical skills so forgive this comment but you do not mention if:
- It has been correct at any point in the past on your smartphone?
- If you have cleared the cache on your smartphone and the reloaded?

**Comment by shall0pass** [comment]
Actual runs locally, which means that the calculations are happening on your laptop and your mobile device.  It appears that one, or both, of your devices are not syncing properly to the server.  You have the server status cut out of your screenshot, but that should say "Server online".

I would export a backup of the budget you feel is correct before trying to troubleshoot this.

The first thing I would do is @Kidglove57 's suggestion.

The second thing I would try is the "Reset Sync" button in the settings page under the "Advanced" section (preferably on the device that has the most up to date budget).  When you do this, you will have to redownload the budget on your second device.

**Comment by 1bubble1** [comment]
There is something similar on demo.actualbudget.org. Please fix who can. In the test file it says "No server"

**Comment by Kidglove57** [comment]
It does look as if the clue is in the message “no server”and that your mobile app is not connected to your host server (but presumably your desktop version is?).
