### ISSUE TITLE
iPad Mini 6 issue with Actual Open source 

### ISSUE THREAD

**Issue by Kidglove57** [actualbudget/actual#140]
I have been running Actual (via Fly) on a number of devices - iMac, iPad Air 4 and iPad Mini. For the most part trouble free. However, on the iPad Mini when I try to enter a transaction the Payee, Notes and Category will not select or enter. The iPad Air is fine.

**Comment by rich-howell** [comment]
I wonder if this is best waiting until https://github.com/actualbudget/actual/pull/79 is implemented further?

**Comment by Kidglove57** [comment]
I agree - however I am guessing the screen size of the iPad Mini may always be an issue for this and other web apps in that it sits half way between a typical phone size and a typical tablet size. So not a priority

**Comment by rich-howell** [comment]
Hey @Kidglove57 

I am going to go ahead and close this off, #79 should resolve this issue, if when it gets merged it doesn't we can re-open it. 

Cheers
Rich
