### ISSUE TITLE
[Feature] Search bar changes

### ISSUE THREAD

**Issue by carkom** [actualbudget/actual#1407]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

The search bar is difficult to distinguish since it's the same color as the background header. It doesn't reveal upon hover - the box only shows up once you click on it but it's tough to know where to click since there's no border or anything. Also, the closing "x" is pretty disconnected on wide format monitors since it is so far away and also a different color than the rest of the search bar items (icon and actual search term)

### Describe your ideal solution to this problem

Make it a bit easier to see/interact with. I'd like to see it be more intuitive.

### Teaching and learning

That's what I'd like to discuss. Make it more visible without being too loud.

**Comment by carkom** [comment]
There's a lot of UI examples for search bars. Take discords for example. It's small, off to the right of the header. Once clicked it expands a bit. If you add more than can be fit into the box could add an ellipses like we do with write-in filters.

The closing "x" is ecapsulated in the search box

Maybe just have a white background for light mode and a gray one for dark mode and remove the onClick border that presents?

Thoughts?

**Comment by kcollett** [comment]
Hmmm. For me, I can easily distinguish the search bar (albeit a bit less easily when using the Light theme). Are you perhaps using a custom theme?
