### ISSUE TITLE
[Bug]: Templates--Bad available_remaining tracking

### ISSUE THREAD

**Issue by youngcw** [actualbudget/actual#1409]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

@shall0pass 
The recent template speed up that is manually tracking the available_remaining gets messed up if there are multiple priority levels in the same category.

Since the template processing includes previous priority level values in the to_budget variable, when subtracting to_budget from available_funds the previous pass values get removed again.  This will keep happening for every pass if there is a template with that priority level. 

Ex
Start with $50
Cat1  :`#template 10`, `#template-1 15`
Cat2: `#template remainder`

The remainder should should get $25 but will end up with $15 since the first $10 gets deducted twice from available_funds in the main loop.

There may be a quick way to fix this, but I wonder if the best way would be to reorganize how the templates are processed. So that the processing of a single template doesn't care about what was there before, and the top loop adds in the previous funds instead of the previous funds being added during the processing.  I would have to check all the processing to make sure that setup doesn't break anything.

### Where are you hosting Actual?

None

### Operating System

None

**Comment by shall0pass** [comment]
You're right.  I'm seeing it.  The easiest way I can think of at the moment to is to pass the 'increment' value back to the calling function and subtract it instead of the whole amount.

**Comment by youngcw** [comment]
If the previous budgeted amount is only used for checks then maybe the addition of previous amounts could happen outside the process loop and somewhere up higher like in the setGoalBudget function.  That wouldn't be as much duplication of work, but more time to implement.

**Comment by youngcw** [comment]
I guess splitting up the to_Budget into an increment and prev values would work ok and be easy to work with afterwords.

**Comment by shall0pass** [comment]
Check out this branch.  I only tested it for this scenario.  I probably needs a little more stress testing.  It passes the increment back.  I don't quite follow moving it out of the loop, so If you think it's a better approach you could try it.

https://github.com/shall0pass/actual/tree/available_remaining

**Comment by youngcw** [comment]
I think that could work.  We would need to make sure that each of the template types use increment in their calculations.  I can see that remainder currently doesn't and would need changed.

I also whipped up one :smile:.  This excludes previous amounts and adds them back in when saving.  A quick search showed that only the remainder goal really used the existing values anyway.  It passes all my tests, but I don't think there is a spend goal in here.
https://github.com/youngcw/actual/pull/new/goals_fixRemaining

**Comment by shall0pass** [comment]
That looks like it works too :)  I'm not really sure which is considered the best approach, but yours touches fewer lines of code so I'm leaning that way 😅.  Will you open a PR?

**Comment by youngcw** [comment]
Will do
