### ISSUE TITLE
[Bug]: Reports Month Dropdown Menus

### ISSUE THREAD

**Issue by carkom** [actualbudget/actual#1425]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

The box border has no radius on it.

Also the menus are showing horizontal scroll bars when they are no needed. I'm on a wide screen monitor with plenty of space for wider menus on this element. They should auto adjust the content so this doesn't happen.

![image](https://github.com/actualbudget/actual/assets/55785687/be2f8421-0bcc-4ada-93fe-245631d997cb)

### Where are you hosting Actual?

None

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Windows 10

**Comment by syukronrm** [comment]
Hi @carkom, is this issue persist on your environment at the latest actual release?

**Comment by carkom** [comment]
Yes, still shows horizontal scroll bars. Checked other browsers. I've noticed the issue is not present in Chrome but only exists in firefox.

**Comment by miqh** [comment]
@carkom,

Applying [`scrollbar-gutter: stable`](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-gutter) to the `ListboxList` usages inside the common `Select` component should resolve the unwanted scroll bar overlay in Firefox and have it positioned like it would be in Chromium browsers.

https://github.com/actualbudget/actual/blob/5fe146ee0a2baf1a9804a823d3b3447fc635cbfb/packages/desktop-client/src/components/common/Select.tsx#L118

However, at this time of writing, a quick web search would suggest some ongoing implementation issues raised by users regarding that CSS property.

https://caniuse.com/mdn-css_properties_scrollbar-gutter

And if Safari is of concern, the property isn't supported at all. I don't have access to any devices to observe what currently happens there.

**Comment by lelemm** [comment]
@carkom , is this persists?
tried on the latest firefox and chrome, no problems:

firefox:
![image](https://github.com/user-attachments/assets/931f794b-549a-49d8-b33e-342c9504afdd)

chrome:
![image](https://github.com/user-attachments/assets/92bea33b-72bd-41d4-8bdb-7414e88ad769)

**Comment by carkom** [comment]
I just checked it on Firefox again and the issue has been resolved somewhere along the way. Thanks!
