### ISSUE TITLE
[Tech Debt] TypeScript - enable `strictNullChecks`

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#1426]
We should enable `strictNullChecks`. It is disabled by default.

Doing this won't be simple and will require fixing a lot of existing types.

**Comment by j-f1** [comment]
Some work on this at https://github.com/actualbudget/actual/tree/jed/strict-null, but there are several hundred errors left to track down.

**Comment by MatissJanis** [comment]
I recently enabled strict mode everywhere: https://github.com/actualbudget/actual/pull/2230

So I'll close this off now. We can continue the migration (i.e. removal of strict comments) without needing an issue.
