### ISSUE TITLE
[Bug]: category autocomplete does not show if budget not visited

### ISSUE THREAD

**Issue by dominicm00** [actualbudget/actual#1439]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

- Visit a page where you can open a category picker (e.g. payees or rules) directly on a fresh session without visiting the budget page
- Attempt to type in a category
- No category picker shows up and it is impossible to select a category
- Visit the budget page
- Category picker now shows up

This appears to be because the store, as accessed [here](https://github.com/actualbudget/actual/blob/907571bd83c105812e57c5421b4af7ef9035ff34/packages/desktop-client/src/components/modals/EditField.js#L24C28-L24C28), does not have group categories populated. Going to the budget populates the store and fixes the issue.

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

**Comment by MatissJanis** [comment]
This will be solved by the new `useCategories` hook that was added here: https://github.com/actualbudget/actual/pull/1382

We just need to make sure it's actually used in all the places where we have categories.
