### ISSUE TITLE
[Bug] [Budget templates]: Do not apply budget templates to hidden categories

### ISSUE THREAD

**Issue by joel-jeremy** [actualbudget/actual#1441]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I have a category that has a schedule budget template e.g. `#template schedule My installment`. Since I have completed paying off the installment this July, I have already hidden this category and completed the schedule. When I applied budget templates in August, it still attempted to apply the budget template to the hidden category which resulted in an error because the schedule (which has already been completed) could not be located by Actual.

Maybe we could introduce a default `Archive` group where users can add categories that are already completed? We could then add an "Archive" option in the category menu to automatically move categories to the default `Archive` group. Actual will then ignore categories in this group when applying budget templates or other types of processing we may add in the future.

### What error did you receive?

Actual could not find the schedule defined in the budget template (as it was already completed)

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mobile Device

**Comment by kyrias** [comment]
I do feel like it would make sense to not apply templates to hidden categories, but also to evaluate completed schedules to 0.

**Comment by shall0pass** [comment]
It should now ignore completed schedules.  I'll look at the hidden categories next.
