### ISSUE TITLE
[Feature] Projected balance in new transactions

### ISSUE THREAD

**Issue by joel-jeremy** [actualbudget/actual#1454]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

When creating a new transaction and the `Show running balance` option is enabled, we see a blank `Balance` cell in the new transaction row. I would like to propose that we show the projected balance on the cell calculated based on the latest running balance and the amount of the new transaction.

### Describe your ideal solution to this problem

Show projected running balance on the `Balance` column if the new transaction is added.

**Comment by youngcw** [comment]
Closing as finished.
