### ISSUE TITLE
[Bug]: income is going as negative balance

### ISSUE THREAD

**Issue by BeeTwenty** [actualbudget/actual#1459]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When i add income it goes as negative balance

![image](https://github.com/actualbudget/actual/assets/43971937/0509ecfb-a4a2-4391-8d27-670d61421413)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Linux

**Comment by shall0pass** [comment]
Have you entered your income in the correct column?  It should be a deposit.
![Screenshot_20230804-064644-023](https://github.com/actualbudget/actual/assets/20625555/91a46f7a-3b8f-47c6-b3e2-20cccdf20282)

**Comment by BeeTwenty** [comment]
Ohh, it was so close to the checkmark i though i had to use rhat check if
it was a deposit thanks

fre. 4. aug. 2023, 13:48 skrev shall0pass ***@***.***>:

**Comment by shall0pass** [comment]
Glad that solved it!
