### ISSUE TITLE
[Bug]: Fatal error on one of my accounts after latest update

### ISSUE THREAD

**Issue by mfolnovic** [actualbudget/actual#1471]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

After latest update (v23.8.0), when I open one my accounts, I get:

![image](https://github.com/actualbudget/actual/assets/20919/cc957211-6b9a-4ddf-9646-303a5f01e805)

It only happens on this one account, and it doesn't happen if I go to "All accounts" or "For budget".

Thank you! :) 

### What error did you receive?

```
m@https://actual.mydomain.com/static/js/main.f758b66a.js:2:298232 v@https://actual.mydomain.com/static/js/main.f758b66a.js:2:298537 8821/Fn<@https://actual.mydomain.com/static/js/wide-components.6cb72932.chunk.js:1:110759 Ca@https://actual.mydomain.com/static/js/main.f758b66a.js:2:497928 Tl@https://actual.mydomain.com/static/js/main.f758b66a.js:2:509616 Cl@https://actual.mydomain.com/static/js/main.f758b66a.js:2:508822 Cs@https://actual.mydomain.com/static/js/main.f758b66a.js:2:558423 wu@https://actual.mydomain.com/static/js/main.f758b66a.js:2:544149 vu@https://actual.mydomain.com/static/js/main.f758b66a.js:2:544077 yu@https://actual.mydomain.com/static/js/main.f758b66a.js:2:543938 au@https://actual.mydomain.com/static/js/main.f758b66a.js:2:540718 iu@https://actual.mydomain.com/static/js/main.f758b66a.js:2:539269 S@https://actual.mydomain.com/static/js/main.f758b66a.js:2:673686 D@https://actual.mydomain.com/static/js/main.f758b66a.js:2:674219 
```

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Linux

**Comment by adamkelly86** [comment]
@mfolnovic : Can you go to Schedules and complete any marked with a ~ to isolate if its linked to #1328 or if its a wider error

![image](https://github.com/actualbudget/actual/assets/37782715/40cd62e1-0ea7-4ce4-9075-02db48070312)

**Comment by MatissJanis** [comment]
👋 Is there anything interesting in console logs that you might be able to share?

**Comment by adamkelly86** [comment]
I've been unable to get DEBUG to print anything in logs for the docker instance
Replicated in a clean docker and budget instance - scheduled transaction is there.  Error occurs as soon as "Show Running Balance" is toggled

 [2023-08-06-My-Finances-496feb6.zip](https://github.com/actualbudget/actual/files/12269946/2023-08-06-My-Finances-496feb6.zip)

**Comment by MatissJanis** [comment]
The fix is here: https://github.com/actualbudget/actual/pull/1473

Feel free to test it out here: https://deploy-preview-1473.demo.actualbudget.org

**Comment by adamkelly86** [comment]
Tested by importing the test budget above and it resolves the fatal error previously given.

**Comment by mfolnovic** [comment]
Yes, same issue here. :)

I'll close it as it's duplicated (#1328).

Thank you for your quick response!
