### ISSUE TITLE
[Feature] Refresh all active clients when new changes sync to server

### ISSUE THREAD

**Issue by Cldfire** [actualbudget/actual#1496]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I could have sworn closed-source Actual auto-refreshed all active clients when a change was made on one client. However, looking through the initial open-source server commit (https://github.com/actualbudget/actual-server/blob/dd541e5f70e9f451b017d41816a5b5c87bc06199/app-sync.js), I can't find anything that would have caused that to happen. Maybe I'm misremembering 🤔 or maybe I'm confusing it with James' tweet from a while back demonstrating instant sync between browser tabs via the service worker: https://twitter.com/jlongster/status/1241040807093768194

In any case, it feels like something we should have and it also feels very simple to implement:

* Use [SSE](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events)
* Whenever there are new messages:
  <img width="462" alt="Screenshot 2023-08-08 at 10 52 03 PM" src="https://github.com/actualbudget/actual/assets/13814214/c03aa173-9524-4883-8e31-c1e4d37ae794">
* Send an event to each connected client telling them to sync now
* Each connected client calls `fullSync` in response to the event

Thoughts?

**Comment by Cldfire** [comment]
Threw together a super quick example of this working with SSE tonight:

https://github.com/actualbudget/actual/assets/13814214/ff05360d-6a17-4233-955c-aac0f956da4d

It'll take a decent amount more work to actually make this mergeable, but it looks promising.

**Comment by youngcw** [comment]
@Cldfire can this be closed as finished?

**Comment by Cldfire** [comment]
No, this hasn't been implemented. The related MR above was an improvement, but it doesn't implement what this issue describes.
