### ISSUE TITLE
[Bug]: Schedule table in Link Schedule modal is collapsed

### ISSUE THREAD

**Issue by trevdor** [actualbudget/actual#1500]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Can be seen on demo.actualbudget.org. 

Repro steps:
0. Ensure at least one schedule exists
1. In any For Budget account, select one or more rows. 
2. On the Transaction menu, click Link Schedule
  <img width="300" alt="Screenshot 2023-08-09 at 9 20 15 PM" src="https://github.com/actualbudget/actual/assets/5862724/5c85dea0-c861-4fd4-92a7-539a775c163a">

3. Observe how the table of schedules shows no rows (they're there, just squished to height 0)
  <img width="668" alt="Screenshot 2023-08-09 at 9 17 38 PM" src="https://github.com/actualbudget/actual/assets/5862724/79ed9913-3e56-4c97-bb8a-2333c77cc593">

### What error did you receive?

No errors in the devtools console.

### Where are you hosting Actual?

None

### Operating System

None

**Comment by kyrias** [comment]
I'm pretty sure that the actual fix is

```diff
diff --git a/packages/loot-core/src/client/data-hooks/schedules.tsx b/packages/loot-core/src/client/data-hooks/schedules.tsx
index 61e24192..3603561f 100644
--- a/packages/loot-core/src/client/data-hooks/schedules.tsx
+++ b/packages/loot-core/src/client/data-hooks/schedules.tsx
@@ -1,5 +1,6 @@
 import React, { createContext, useEffect, useState, useContext } from 'react';
 
+import { type Query } from '../../shared/query';
 import { getStatus, getHasTransactionsQuery } from '../../shared/schedules';
 import q, { liveQuery } from '../query-helpers';
 
@@ -18,7 +19,7 @@ function loadStatuses(schedules, onData) {
   });
 }
 
-type UseSchedulesArgs = { transform?: <T>(v: T) => T };
+type UseSchedulesArgs = { transform?: (q: Query) => Query };
 export function useSchedules({ transform }: UseSchedulesArgs = {}) {
   let [data, setData] = useState(null);
 
```

Then you can have the `useCallback` call either un-annotated or be `(q: Query)`.
