### ISSUE TITLE
Improve documentation for gocardless.com

### ISSUE THREAD

**Issue by thomasaull** [actualbudget/actual#1504]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I'm just setting up bank sync with actual budget. At the end I did work, but I actually created a regular account on gocardless.com instead of bankaccountdata.gocardless.com (which is the service they aquired from Nordigen I guess) and can be used independently.

### Describe your ideal solution to this problem

A small note or the correct URL in the dialog in the software would probably prevented me from creating the account on the "wrong" service.

**Comment by kyrias** [comment]
C.f. https://github.com/actualbudget/docs/pull/254 and https://github.com/actualbudget/docs/issues/250

**Comment by thomasaull** [comment]
@kyrias Great to see it's already taken care of :)
