### ISSUE TITLE
[Bug]: Goals: Error messages don't present after appying

### ISSUE THREAD

**Issue by shall0pass** [actualbudget/actual#1507]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When you apply the goal templates, after completion there is supposed to be a pop up dialog informing how many templates were applied, how many had errors, and how many couldn't be applied.  These messages no longer pop up.

### What error did you receive?

There are no errors in the Dev console.

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 10

**Comment by joel-jeremy** [comment]
This issue is still present in 23.10.0.
