### ISSUE TITLE
Mobile - record GPS location of transaction entry to auto-suggest future entries

### ISSUE THREAD

**Issue by htims05** [actualbudget/actual#1511]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Speed up the transaction entry on mobile when traveling by auto suggesting payees at the time of transaction entry based on the mobile devices current location.

### Describe your ideal solution to this problem

Using the mobile phone's GPS location during every transaction entry on the mobile device tie the location/GPS coordinates to that transaction entry.  On subsequent transaction entries within a to be determined radius of that GPS location (relatively small distance), have the Actual app auto-suggest the payee based on known previous entries with GPS locations within the radius of the current location.

There should be an option within the settings to enable or disable this feature as some users may not want the app to record their location history.  It should be disabled by default.

### Teaching and learning

This could be documented as a usability feature that (presumably) other apps do not have.  It would aid in speeding up transaction entries on the go, potentially one handed (not having to type the payee).  Simple documentation in the guides to explain the toggle on/off in the settings.

**Comment by ElDubsNZ** [comment]
Support this. YNAB has it and it's such a time saver. Combined with remembering the last category used for a transaction to that payee, and what your default spending account is, pretty much all you have to do at checkout is enter the amount and hit save.

**Comment by jj33** [comment]
Giving a vote for this one, as stated above YNAB does this and makes it super easy when out and about to easily add a transaction.

**Comment by SunFlowerOwl** [comment]
I'd also like to voice my support for this issue.

**Comment by mannkind** [comment]
Yes, please. This would help make mobile entry far less painful.

**Comment by xela-zone** [comment]
Up and coming #6706
