### ISSUE TITLE
[Feature] Display montly savings rate

### ISSUE THREAD

**Issue by ChrisKolan** [actualbudget/actual#1516]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

It would be very helpful to quickly assess the current financial situation to add a monthly savings rate. The savings rate should be presented as a percentage, which would make it easier to compare between months. In this era of rampant inflation, we would be able to see at a glance how it affects our finances.

![image](https://github.com/actualbudget/actual/assets/9021862/e996a94a-4d54-4cc7-8dd0-2721daefcab1)

### Describe your ideal solution to this problem

The implementation for a given month might look like the following: 

`SavingsRate = (IncomeReceived - Spent) / IncomeReceived * 100`

or

`SavingsRate = (IncomeReceived - Budgeted) / IncomeReceived * 100`

**Comment by OlegWock** [comment]
I can take care of implementing this. Not sure does it requires some 👍-threshold or confirmation from maintainer or if I can just do pull-request right-away though

**Comment by kcollett** [comment]
I like the idea but dubious about placing it in the budget summary. I think it makes more sense to include this as an option to the data table report (which seems the closest that AB can get to a standard Income and Expense report). For example, in the YNAB Toolkit implementation of this, if there is positive Net Income for a given month, then a "Savings Ratio" is presented which is Net Income / Total Income.

**Comment by kaibagley** [comment]
I'd love a feature like this, I imagine there could be a percentage in each of the category groups, showing the distribution percentages of the income going to Savings, Bills, General Expenses etc.

Not sure where it could fit, maybe just next to the Budgeted value in the corresponding group's row?
