### ISSUE TITLE
[Feature] 'Refund' option in the Dropdown Menu

### ISSUE THREAD

**Issue by HStep20** [actualbudget/actual#1519]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

When dealing with the refund of a purchase, right now I duplicate a transaction, change the date, and move the 'payment' to the 'deposit' column, but that could be easily automated with a new 'Refund' option in the transaction dropdown menu

### Describe your ideal solution to this problem

When a transaction is selected and the refund option is pressed, Actual should set the date to the current date, set the note equal to the note in the existing transaction with the suffix `- Refund`, and set the Deposit Column == Original Transactions 'payment' column when the option is selected.

**Comment by Jackenmen** [comment]
Personally, I'd prefer a "Refund - " prefix rather than a suffix. Either way though, I don't know how people will feel about a fixed English-specific string being added to the transaction description when using this feature.
