### ISSUE TITLE
[Bug]: Mobile entry will enter positive value instead of negative 

### ISSUE THREAD

**Issue by shall0pass** [actualbudget/actual#1520]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When entering data on the new Mobile entry page, a transaction may be entered as a deposit rather than a payment without toggling the - to + button.

To reproduce: 
Go to an account.
Enter the mobile entry screen.
1. Fill in the Payee
2. Fill in the amount (don't remove focus from the amount cell before step 3)
3. Add transaction

You'll see the entry is a deposit rather than the default payment.

If you remove focus from the amount cell before adding the transaction, it will add the transaction correctly.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Mobile Device

**Comment by Kidglove57** [comment]
I must be doing something wrong! I have tried over and over again in mobile Firefox and Safari without being able to reproduce this bug. The act of selecting “add transaction” removes focus from the amount for me.

**Comment by shall0pass** [comment]
This is using the edge image.

https://github.com/actualbudget/actual/assets/20625555/7e864c46-2367-4a7a-b241-48fc95c89b3b

**Comment by shall0pass** [comment]
This is if I remove focus first.  It's working normally.

https://github.com/actualbudget/actual/assets/20625555/13dba97e-6185-43a8-af5f-3725c23093ca

**Comment by Kidglove57** [comment]
Thanks for the visual explanations @shall0pass. I have tried and tried (on latest Edge) but still cant make it happen. I'm on iOS but I can't see what difference that would make?

**Comment by shall0pass** [comment]
Strange.  Both of those demos were using chrome on android.  I can get the same results by using the demo site.

**Comment by Kidglove57** [comment]
Maybe a silly question but how do you enter the transaction without switching focus to the “add tranasction” button?

As an aside I probably would not normally come across this as I follow the screen entry sequence ie amount/payee/category.

**Comment by shall0pass** [comment]
> Maybe a silly question but how do you enter the transaction without switching focus to the “add tranasction” button?

There is a button on the keyboard to stow it away.  It's in the bottom left of my keyboard when it's open.

> As an aside I probably would not normally come across this as I follow the screen entry sequence ie amount/payee/category.

I found this at the grocery store yesterday.  I was waiting for the cashier to finish ringing up my items, so I didn't have the total amount yet but I had the payee and the category.  I was just waiting for the amount to be filled before entering.

**Comment by Kidglove57** [comment]
Ah got it thanks for your patience - the reason I was lost is because there is no equivalent keyboard "enter" button on the Apple iOS keyboard in transaction mode, so I have to physically select "add transaction.

**Comment by shall0pass** [comment]
Just to clarify, I did use the "add transaction" button, but when I selected it the amount box still had focus.  I did not use the enter button on my keyboard at any time.

**Comment by Kidglove57** [comment]
Thanks for clarifying! It maybe does not help resolve this but I have now entered test transactions a dozen times or more without any of my payments turning into deposits.🫢

**Comment by shall0pass** [comment]
I am able to replicate this on my laptop.  If no one else is able to replicate this, I may dig into it later.  It must have something to do with touch events.  This laptop is running Win 11.

![mobile_entry](https://github.com/actualbudget/actual/assets/20625555/07564828-9b4f-47af-ac74-3a60cb746daa)

**Comment by trevdor** [comment]
Think I got to the bottom of it! `onBlur` is applying the negation we rely on. More details in the description of the PR I just linked
.
@shall0pass mind verifying the fix on the linked PR preview addresses it for you?

**Comment by shall0pass** [comment]
This solves it!  Thanks!
