### ISSUE TITLE
[Bug]: OFX Import "Notes" & "Payee" Fields Switched

### ISSUE THREAD

**Issue by themadman0980** [actualbudget/actual#1524]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I have been happily using Actual for the last 8 months, and the OFX import tool has worked beautifully until now (first attempt in the last 3-4 weeks, so I'm assuming it's the new OFX importer).

Basically, the "Notes" and "Payee" fields have all been swapped, which is immensely painful and makes the import tool basically unusable. Below is an example of what I am seeing now, with all the purchase details in the payee field instead of notes. This means that every new transaction imported has a new payee, as every payment description is unique.

![image](https://github.com/actualbudget/actual/assets/107305060/5438d6d9-2ec1-455d-99cf-d69f5f11def0)

#521 seems like a related problem but I'm unsure what ended up happening.

FWIW I attempted to re-import some old OFX files that worked beautifully several months ago, and they're all exhibiting the same behaviour. This leads me to believe its not an issue with my bank's OFX export tool.

I'm currently running 23.8.1 using Docker and Google Chrome.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by MatissJanis** [comment]
👋 Would you mind providing a redacted version of your OFX export? We really need a way to reproduce the issue in order to fix it.

**Comment by themadman0980** [comment]
Here's a sample file I've exported from my bank that I've confirmed has the issue on my current setup.

[OFXData-Sample.zip](https://github.com/actualbudget/actual/files/12339733/OFXData-Sample.zip)

I can't see any personal info here, but please let me know if there's any issues.

**Comment by joel-jeremy** [comment]
The way our ofx importer is implemented right now is that is checks first if the ofx transaction has a `NAME` field and use that as the payee. Otherwise, it will use the `MEMO` as the payee. 

Banks do not generate the ofx file the same. Some banks populate the `NAME` field with the name of the payee but others just use the `MEMO` field with the transaction details. In your case, it is the latter.

I think one possible solution is just put the `MEMO` in the Notes field and provide a way to easily create a rule inside the import modal so that users can easily create a rule to populate the Payee based on the Notes e.g.

![image](https://github.com/actualbudget/actual/assets/20313680/18b557b2-1e51-4c18-a59a-c192c347d499)

**Comment by themadman0980** [comment]
Yeah, that sounds like exactly what used to happen tbh. Thanks for following up!

**Comment by themadman0980** [comment]
This issue seems to be derived from the outcome of #1268.

**Comment by Shazib** [comment]
In this case the memo field seems to be some hybrid of the payee and some other notes. I guess we need a flag/option for the user to be able to use memo as payee optionally. @themadman0980

I will look this weekend if I can implement this - alternatively we could unwind #1268 as a regression in the interim @MatissJanis?

**Comment by MatissJanis** [comment]
> I will look this weekend if I can implement this - alternatively we could unwind #1268 as a regression in the interim @MatissJanis?

I would prefer not to rollback. If we did that, then another group of people would start reporting bug reports about the inverse problem. Lets just try to patch this issue for the next release. If you don't have time this weekend, then I'll try to take a look at it next week.
