### ISSUE TITLE
[Feature] Add way of limiting scheduled payments to weekdays only.

### ISSUE THREAD

**Issue by AdamGaffney96** [actualbudget/actual#1528]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

It's possible this is linked to [this feature request](https://github.com/actualbudget/actual/issues/929) however I didn't think it quite fit my issue.

Essentially there are many payments of mine that cannot take place on a weekend, for example finance payments. There are scheduled, regular payments for a set date, however if that date falls on a weekend then they're usually pushed to the Monday immediately following the date. So for example, if I had a scheduled payment for the 20th of each month, then this month that's a Sunday, so the payment would be taken on the 21st. However there's no option to exclude weekends from the calculation when setting up repeats for scheduled payments.

### Describe your ideal solution to this problem

It would be great if you could have a checkbox to the effect of "Exclude weekends?" where when ticked, the scheduler will set any weekend dates to be the closest following weekday (i.e. Monday) after the expected schedule date. This would mean that the scheduled payments would be more accurate without having to skip and add manually each time this happens.

### Teaching and learning

I think as long as there's documentation or an info-bubble explaining what the checkbox does, then that would suffice. I think seeing the dates change in the scheduler preview for the expected dates of scheduled payments would suffice to explain what's going on.

**Comment by youngcw** [comment]
Any reason that this shouldn't be marked as finished?  Schedules can be set to apply to before or after weekends since #1505.

**Comment by zotabee** [comment]
Linked to https://github.com/actualbudget/actual/issues/6209

> Any reason that this shouldn't be marked as finished? Schedules can be set to apply to before or after weekends since [#1505](https://github.com/actualbudget/actual/pull/1505).

This is a "move" schedule outside of weekends but definitively not a "skip" weekends / weekdays schedule.

Scenario example: user wants a daily recurring scheduled transaction that occurs only on weekdays (Mo-Fr) and not on weekends (Sa-Su) aka skip on weekend.
