### ISSUE TITLE
[Feature] Budget view: show upcoming transaction

### ISSUE THREAD

**Issue by RogerSik** [actualbudget/actual#1534]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

It would be nice to see all upcoming transcation in the month. So it is possible to budget for all upcoming transaction.

Currently view:
![17_12-45-56](https://github.com/actualbudget/actual/assets/165814/abf7e7d6-60f0-46fc-b09a-3122d622173f)

Same view with the data in YNAB:
![17_12-46-52](https://github.com/actualbudget/actual/assets/165814/c7359ec5-1d09-4c11-b6a3-6bc252b6c0e4)

Currently my workaround is look the month before but if there are schedules which are every 2 months as example I will be overlook it.

**Comment by drgndrp** [comment]
This seems like an essential feature to me. It's weird this doesn't have enough upvotes.
Because the way schedules work right now, they don't really add anything for me. To plan ahead with the income i will get every month i need that to show up in the Budget view, so i do a workaround of adding future transactions which makes the upcoming transactions in the account view obsolete. 

I love the app and right now I can live with the Workaround and I recognize this is a bigger design problem and possibly affects the design philosophy of the entire app, but again, it feels essential. 

Maybe someone is already working on it i couldn't find anything yet.

**Comment by Kidglove57** [comment]
I did not "up vote" this simply because I already budget automatically for all upcoming transactions (including annual ones) by making a monthly contribution towards them, using the Goal Template tool. I budget using last months income so all is taken care of.

**Comment by ntucker1** [comment]
> I did not "up vote" this simply because I already budget automatically for all upcoming transactions (including annual ones) by making a monthly contribution towards them, using the Goal Template tool. I budget using last months income so all is taken care of. PS I forecast account balances by viewing upcoming scheduled transactions in each account and the resultant forecast running balance.

Thanks for sharing this, I didn't even know about Budget Goal Templates until I read this comment, it looks like exactly what I needed.

**Comment by TorC8** [comment]
Looks like this and https://github.com/actualbudget/actual/issues/2376 are more or less duplicates of each other.

**Comment by joel-jeremy** [comment]
If you are on [Actual 25.6.0](https://actualbudget.org/docs/releases/#2560) or later and using goal templates feature, the upcoming/due/missed schedules should show up in the budget table.

**Comment by TorC8** [comment]
On 25.08.0 when I try "#template schedule $SCHEDULE" it shows that there's an upcoming transaction IFF it's within the "upcoming length" window, but 1. it doesn't show anywhere in the budget how much that upcoming transaction is for and 2. it adds the amount of that schedule to the total budgeted.  "#goal schedule $SCHEDULE" does nothing that I can see.

Point two can be worked around, but given point one, I don't see a way to solve the primary issue this feature request (and 2376) is designed to address: how to show in the budget how much is available in a category for one-off purchases, assuming scheduled transactions complete as expected.  Even worse, the display of upcoming is tied to the view length under schedules, meaning that unless one always maintains the upcoming length of "end of current month," it can fail to show a known upcoming transaction, although it does appear to correctly stop at the month boundary.

I've gone into more detail on how I would see best to fix this on 2376.

**Comment by kalenbjorn** [comment]
Been wanting this as well cause in my scenario, my Groceries category have subscriptions such as our kid's milk and diaper. Not knowing what our total left over budget is after the upcoming transactions sometimes leads us to overspending.
