### ISSUE TITLE
[Bug]: Mobile Too Budget amount is inconsistent 

### ISSUE THREAD

**Issue by shall0pass** [actualbudget/actual#1538]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When clicking in the mobile Top Budget amount, the pop up window shows a different value .

![Screenshot_20230818-051918-857](https://github.com/actualbudget/actual/assets/20625555/37ee1aa7-1fa5-46de-873e-ddc558c8b12e)

### Where are you hosting Actual?

NAS

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mobile Device

**Comment by Kidglove57** [comment]
Also confirmed in my set up (iOS). Thanks for uncovering this bug!

**Comment by shall0pass** [comment]
This line: 
`const budgetAmount = useSheetValue(rolloverBudget.toBudget);`
in
[packages/desktop-client/src/components/modals/BudgetSummary.js](https://github.com/actualbudget/actual/blob/master/packages/desktop-client/src/components/modals/BudgetSummary.js)

is returning a null value when called from Mobile.
