### ISSUE TITLE
[Bug]: Mobile Header

### ISSUE THREAD

**Issue by shall0pass** [actualbudget/actual#1544]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

This is easily seen if there are very few categories to view in the Mobile budget view.  The Budgeted and Balance columns appear to be TOP aligned, while the To Budget/Overbudgeted column appears to be center aligned.  This can sometimes create a large header that looks awkward.

Image with few categories
![image](https://github.com/actualbudget/actual/assets/20625555/8ea5a53f-26c2-4773-824e-9222edc77134)

Same budget with more categories shown
![image](https://github.com/actualbudget/actual/assets/20625555/301e2ae3-ea0c-4268-9d50-719d7b0d16dc)

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by MatissJanis** [comment]
This is Chrome + OSX.

<img width="368" alt="Screenshot 2023-08-19 at 20 06 04" src="https://github.com/actualbudget/actual/assets/886567/55871571-fe21-409b-b6e9-e19f5e7c6d32">
