### ISSUE TITLE
[Feature] Mobile Payee and Account autocomplete text size

### ISSUE THREAD

**Issue by shall0pass** [actualbudget/actual#1555]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

My wife and I have made the move to 100% using Actual whereas previously we were running parallel budgets with ynab4.  It's a big event for us 😀.  One nitpick she has made is that the payee and account selection fields feel small and are a little more difficult to select.  

### Describe your ideal solution to this problem

The request is to have a larger font size in these selection models to have a larger target to select.

**Comment by Cldfire** [comment]
💯, this was one of the follow-up needs listed in the original PR.

**Comment by shall0pass** [comment]
> 💯, this was one of the follow-up needs listed in the original PR.

Ahh.  I'm sorry!  I should have looked at that list again before submitting.

**Comment by Cldfire** [comment]
Oh no worries, it's better to have these filed as issues anyhow!

**Comment by shall0pass** [comment]
Maybe we should move those ideas to the mobile RFC so they're a little easier to find.

**Comment by Cldfire** [comment]
Yeah, that sounds like a good idea.

**Comment by joel-jeremy** [comment]
Closing as auto complete fonts are now larger: https://github.com/actualbudget/actual/pull/1900
