### ISSUE TITLE
[Feature] Actual Mobile - Adding calculation feature in the amount field while adding new transaction

### ISSUE THREAD

**Issue by nmathey** [actualbudget/actual#1556]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Handling multi currency account, I'm calculating manually using my own exchange rate to add new transaction.
Formulas calculations are working on the web version but not the mobile one.

### Describe your ideal solution to this problem

Being able to use simple calculation formula in the "Amount" field while adding a new transaction on Actual Mobile

**Comment by Cldfire** [comment]
The hard part here is the UI design.

**Comment by nmathey** [comment]
Yeah it might be. 
Or maybe using local mobile OS features with react call (?): I noticed that only numeric keyboard is poping without +-/x signs.
So maybe delegating this feature to the mobile os directly (just guessing here).

**Comment by joel-jeremy** [comment]
The new new budget modal would be a good place to add this feature
