### ISSUE TITLE
[Feature] Rules have no "contains" option

### ISSUE THREAD

**Issue by Rand72889** [actualbudget/actual#1558]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

It seems that the rules module have no "contains" option.

There are a lot payees that have unique numbers for there store location. "McDonalds" is called "McDonalds 8429", "McDonalds 9475", "McDonalds 9472" which makes it impossible to apply rules.

After creating a rule it would be nice to be requested if you want to apply the rules to the existing entries or not.

**Comment by youngcw** [comment]
You may really be looking for the imported_payee field which does have a "contains" option.  Closing this since it was already determined to be a duplicate.
