### ISSUE TITLE
[Feature] Allow split transaction to have different payees

### ISSUE THREAD

**Issue by joel-jeremy** [actualbudget/actual#1567]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

When doing transfers/bill payments in fintech apps, there's usually fees associated with every transaction. It would be great if we could model these fees through split transactions. Right now, users will need to create a separate transaction for fees which can make it hard to track which parent transaction that fee is for.

### Describe your ideal solution to this problem

Allow split transactions to have multiple payees

**Comment by kyrias** [comment]
Child transactions _can_ already have different payees.

**Comment by joel-jeremy** [comment]
That is true for transfer payees but for regular payees, they do not show up on the payee selection.

**Comment by joel-jeremy** [comment]
I think we should show regular payees too in the payee selection for child transactions. This is useful for entering transaction fees.

**Comment by joel-jeremy** [comment]
Sorry, yeah - I meant show them by default. I agree.

**Comment by kyrias** [comment]
Ah, that's because the payee of the parent transaction is the transfer payee.  The simple work-around would be to have the non-off-budget payee as the payee of the parent transaction.

I have a feeling that this will be involved to fix, but please do file a bug issue about it.
