### ISSUE TITLE
[Feature] Add end date to repeated Schedules

### ISSUE THREAD

**Issue by gravelfreeman** [actualbudget/actual#1568]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Hello,

In this screen I searched a long time and figured out it was probably a missing feature.

We can set when the schedule starts but we can't end it by choosing a date.

![image](https://github.com/actualbudget/actual/assets/44218371/79b95cdf-59a0-4233-b09f-12cca9512b05)

For example; I had to set 23x scheduled entries for all the individual payments for my appliances, which are monthly payments.

### Describe your ideal solution to this problem

Add a date field and date picker to be able to select an ending date. Once the end date is reached the schedule would be moved under "Show completed schedules".

**Comment by Rick-Thomas** [comment]
Can this feature request, which has 7 votes be the same as the [#506] which has 12?   I have the sensation they are both addressing the same problem of setting and end to scheduled transactions...

**Comment by jfdoming** [comment]
> Can this feature request, which has 7 votes be the same as the [#506] which has 12? I have the sensation they are both addressing the same problem of setting and end to scheduled transactions...

Yes, I believe both will be resolved from the above PR! Hoping to get this merged soon.

**Comment by Rick-Thomas** [comment]
> 🎉 This feature has been implemented in #1899 and will be released in the next version. Thanks for sharing your idea! 🎉

Bravoooo!!!    Fantastic news!!!!   Thanks and congratulations...
