### ISSUE TITLE
[Bug]: Budgeted column doesn't update based on upcoming Schedules

### ISSUE THREAD

**Issue by gravelfreeman** [actualbudget/actual#1569]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I think this is a bug, at least it doesn't make sense to me how it's working at the moment.

I spent quite some time adding all my upcoming payments under the Schedules tab. After adding my schedules to a category by modifying the rule, I was surprised that I had to manually add them in the Budgeted column.

I think the current behaviour is so that the schedule task creates an entry in the database and then that expense will appear under the Spent column prior to the category line you've set the rule to.

The same logic should apply to the Budgeted column; since I know it'll be an expense and that I took the time to add it as a schedule, I'm expecting to see it there, without manual intervention.

I hope this makes sense, long life to actual server, you guys rock!

### What error did you receive?

The budgeted column remained at zero even though I had setup schedules.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 10

**Comment by oliverjkb** [comment]
I set up actual-server yesterday and was wondering if I might just be doing something wrong. 
I kinda know my schedules, coming from an excel based budget that I want to get rid of. 
Having schedules (bills, income, etc.) being reflected in the budget without the need of manually entering it each month would be just great. :+1:

**Comment by youngcw** [comment]
One way to automatically add a schedule amount to the budgeted column is to use goal templates. There is a goal option that budgets enough for the schedule.

**Comment by gravelfreeman** [comment]
> One way to automatically add a schedule amount to the budgeted column is to use goal templates. There is a goal option that budgets enough for the schedule.

Do you mind sharing how to do this? I can't find it. Thank you!

**Comment by oliverjkb** [comment]
Should be here in the Docs: https://actualbudget.org/docs/experimental/goal-templates

Since this is an experimental Feature, I didn't want to go that route though.

**Comment by gravelfreeman** [comment]
> Since this is an experimental Feature, I didn't want to go that route though.

Yep, exactly what I'm thinking. Already spent and invested time in the past on features that got removed. I still think this is a bug and that there's no reason for the column not to update in real time as it's a budget app and that a schedule IS budgeted.

**Comment by oliverjkb** [comment]
Agreed. 
I couldn't resist trying out the goal templates.. 
While I do see that this might be interesting for some use cases, I'd rather not add 30+ template lines to different categories and have to manually update, each time a budget ceases to exist or changes to another category I see fit's better.

**Comment by Kidglove57** [comment]
To be technical about it, this is a feature request rather than a bug. I say that simply because, for right or wrong,  the original developer designed it as it currently is.

I have been using the "experimental" goal templates for well over a year now. They have not given me even a moment's trouble. I use them in a  fairly simple way but they populate my budget in seconds each month. I recommend them highly.

**Comment by youngcw** [comment]
I'm going to close this. If the function described is still desired, then it would be best as a feature request.

**Comment by gravelfreeman** [comment]
Added a feature request [here](https://github.com/actualbudget/actual/issues/2376). Please go comment if you'd like to see this.
