### ISSUE TITLE
[Feature] Add category to schedules

### ISSUE THREAD

**Issue by gravelfreeman** [actualbudget/actual#1570]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

At the moment to add a category to my Schedules I need to;

1. Navigate to the rules
2. Find the one I created from in Schedules
3. Add "category" under "Then apply these actions"
4. Save

### Describe your ideal solution to this problem

Ability to add a category directly on the add schedule window.

![image](https://github.com/actualbudget/actual/assets/44218371/728b714f-5a6a-49bc-a444-cf889ecbf80c)

**Comment by Cldfire** [comment]
I fully agree! I actually posted this idea on Discord as well a couple days ago, so thanks for filing this.

I already prototyped this locally:

https://github.com/actualbudget/actual/assets/13814214/c95ea19d-0581-4ccc-96ce-f8a76f85083a

When I have time I'll open a PR.

**Comment by gravelfreeman** [comment]
Wow! So happy to hear this! Hope you could add this once you got some time :)

**Comment by Rick-Thomas** [comment]
Fantastic solution to having Category in Schedules!!!   Hope you find the time to be able to materialize it!!!   Thanks...

**Comment by atgrey24** [comment]
Just want to revive this old request. Selecting the category directly on schedule creation makes sense to me. I don't quite understand why that currently requires a separate edit of the rule.

Is the thought that currently there is already a separate global rule for categorizing based off the payee so that it isn't necessary for the schedule?

**Comment by jesstokes** [comment]
Yes, this would save me a step for every schedule I create!

**Comment by gottifire** [comment]
YES
