### ISSUE TITLE
[Bug]: Cannot Import and Sync Large File

### ISSUE THREAD

**Issue by jcdickinson** [actualbudget/actual#1575]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

After having sync issues I followed the steps in the documentation to migrate to the new format: export the DB, delete the file from Actual, then re-import. Sync continued to fail.

I then searched through the issues and found #867, but I cannot reset sync because "Reset Sync is only available when syncing is enabled." I also found #838, which describes my issue exactly (but is closed) - only I don't have an old server to go back to in order to re-import.

What can I do to restore sync with my data?

### What error did you receive?

"Reset sync is only available when syncing is enabled."

"Request entity too large"

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Windows 11

**Comment by jcdickinson** [comment]
I temporarily increased the limit for actual in my nginx config. Still, it seems like this catch-22 should be addressed: it should be possible to reset sync for a file that is not yet synced.

**Comment by MatissJanis** [comment]
You'll be able to configure the server max-file-size after this PR is merged: https://github.com/actualbudget/actual-server/pull/245

That should solve the problem. In the short term: I'd recommend applying the patch locally to unblock yourself.
