### ISSUE TITLE
[Bug]: Upcoming Schedules show up when looking at all Off-budget accounts

### ISSUE THREAD

**Issue by youngcw** [actualbudget/actual#1577]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Im seeing a pending schedule show up in the list of all off budget transactions, but the account the schedule applies to is an On-Budget account.

The schedule seems to be working as expected for the other two full lists, On-Budget and All accounts.

### What error did you receive?

none

### Where are you hosting Actual?

None

### Operating System

None

**Comment by MatissJanis** [comment]
👋 Would you be able to provide an example budget export?

Thanks

**Comment by youngcw** [comment]
Here is a test budget that I setup.  All I had to do was set an on-budget schedule to happen a few days from now and it shows up in the all off-budget transaction list.
[2023-08-26-_test-budget.zip](https://github.com/actualbudget/actual/files/12446713/2023-08-26-_test-budget.zip)

**Comment by Kidglove57** [comment]
I can confirm that this happens in my Actual Budget (approx 4 years old). I can't say it worries me much (at all) but it is definitely an anomaly.

**Comment by MatissJanis** [comment]
Great! Thanks for the repro @youngcw !
