### ISSUE TITLE
[Bug]: Gocardless - Payee is empty

### ISSUE THREAD

**Issue by LasseLegarth** [actualbudget/actual#1588]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I've set up the GoCardless sync, and set it to import my transactions from Denmark->Handelsbanken.

It does import transactions, but I can only see the following data:
- Date
- Account
- Payment/Deposit

There isn't any Payee so I have no idea what the transaction is actually about :(

I use the same GoCardless integration for firefly and the same bank/account - I get all the information about the payment there. So the data must be available, but for some reason it doesn't make it into ActualBudget

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

**Comment by MatissJanis** [comment]
👋 Can you take a look at the server logs to see what data the server gets? And post a redacted version of this data here for folks to analyze.

**Comment by LasseLegarth** [comment]
> 👋 Can you take a look at the server logs to see what data the server gets? And post a redacted version of this data here for folks to analyze.

Yes.. I'm running it in Docker, I tried to look after a serverlog in the docker container, but failed to find anything. Where can I find this serverlog, if you can help me :) Thanks

**Comment by LasseLegarth** [comment]
I thnik I found it? 💪

`  {"transactionId":"STRING-ID","entryReference":"2023-07-13-12.25.04.739430","bookingDate":"2023-07-13","valueDate":"2023-08-01","transactionAmount":{"amount":"-440.06","currency":"DKK"},"additionalInformation":"MasterCard   proshop.dk","balanceAfterTransaction":{"balanceAmount":{"amount":"YYY","currency":"DKK"},"balanceType":"closingBooked"},"internalTransactionId":"STR-ID"},
  {"transactionId":"STRING-ID","entryReference":"2023-07-13-12.25.04.734776","bookingDate":"2023-07-13","valueDate":"2023-08-01","transactionAmount":{"amount":"-9.95","currency":"DKK"},"additionalInformation":"MasterCard   NETTO H@RNING","balanceAfterTransaction":{"balanceAmount":{"amount":"YYY","currency":"DKK"},"balanceType":"closingBooked"},"internalTransactionId":"STR-ID"}]'
`

**Comment by MatissJanis** [comment]
Great, so I can see that the payee name is in `additionalInformation`. It shouldn't really be there. It should be in `debtorName`.

There are two approaches you can take:

1. reach out to Gocardless and report this as a bug - they have been quite quick to respond and resolve issues so far;
2. create a new bank adapter for your bank that converts `additionalInformation` field to `debtorName`; sample how some folks have done similar things for other banks: https://github.com/actualbudget/actual-server/blob/master/src/app-gocardless/banks/american-express-aesudef1.js

**Comment by LasseLegarth** [comment]
I got a reply from GoCardless:
`Hi Lasse,

Thank you for reaching out to us. 

I have checked the data returned by Handelsbanken, and I can see that they are returning this information as "additionalInformation" thus, we we are displaying it accordingly. 

We cannot assign the data to a different Datapoint as this might cause further errors down the line. 

I hope this clears things up, but in case further questions arise please let me know. `

I will have to look into the bank adapter - see if I can figure out how to do that... Was hoping for a change so it just worked like it did in firefly, but fair if you don't think that is the way to go in actualbudget.

**Comment by MatissJanis** [comment]
👋 Closing this off. Please create a new bank adapter to get this resolved.
