### ISSUE TITLE
[Feature] Show currency symbol

### ISSUE THREAD

**Issue by OlegWock** [actualbudget/actual#1589]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Coming from YNAB, I really miss currency sign in UI. YNAB doesn't support multiple currencies, so it's purely UI gimmick. However, in case if user has multiple budgets in different currencies, this helps a lot to distinct them.

### Describe your ideal solution to this problem

I see this as setting per budget/file in 'Formatting' section. By default, it should be set to 'No currency' which means current behavior (no currency sign). User then can switch currency if they would like to have currency sign displayed.

**This issue doesn't introduce support for multiple currencies.** This is purely visual change.

And to make it clear to user, I propose to add also some kind of 'notice' saying something like 'Actual doesn't support multiple currencies, this is only formatting setting and doesn't change how Actual processes transactions.'

To add currency sign we can simply adjust `Intl.NumberFormat` settings ([caniuse](https://caniuse.com/?search=currencySign) - 92.2%) and to get list of supported currencies we can use `Intl.supportedValuesOf("currency")` ([caniuse](https://caniuse.com/mdn-javascript_builtins_intl_supportedvaluesof) - 89.4%). 

### Teaching and learning

I don't think this issue requires additional effort to be discovered. User will see it when configuring other formatting options for file. However, this will require updating [those docs](https://actualbudget.org/docs/tour/settings#formatting).

**Comment by joel-jeremy** [comment]
I believe this is partially implemented now as an experimental feature in in Actual 25.8.0 (via https://github.com/actualbudget/actual/pull/5167)
