### ISSUE TITLE
[Bug]: Components overlap when editing account name

### ISSUE THREAD

**Issue by joel-jeremy** [actualbudget/actual#1606]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When editing an account's name, the components are overlapping:
![image](https://github.com/actualbudget/actual/assets/20313680/15f258ba-253d-4010-b853-54580d26a5c1)

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by ratishjain12** [comment]
@joel-jeremy assign me this issue I can solve it!!

**Comment by joel-jeremy** [comment]
Thank you for your interest in contributing! We don't usually assign issues to people but please feel free to open up a PR for the fix! :)

**Comment by himanshugoldy** [comment]
Is it done or still open to solve?

**Comment by joel-jeremy** [comment]
I don't see any PRs that address this at the moment. Feel free to open one up! :)
