### ISSUE TITLE
[Bug]: Category autocomplete - filter search matches on category group names

### ISSUE THREAD

**Issue by trevdor** [actualbudget/actual#1615]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Transactions table category autocomplete matches your search term against category group names, which are not selectable. If there are many categories in the matching group, the desired category may not even be visible for a mouse click. Personally, I don't think a mouse click should be necessary, as Actual is all about optimizing speed of transaction entry.

<img width="425" alt="Screenshot 2023-08-30 at 8 41 57 PM" src="https://github.com/actualbudget/actual/assets/5862724/04bebfe2-d09d-4503-a0cb-e89cb48e33ca">

My real-world example: category group `Active Expenses` gets matched when I search for my `Activities` category until I get to the second `i`.

### Workaround
Make sure your category group names share little in common with your category names.

### Maybe not a bug? 
It's working as built, and I could easily understand the argument not to change an existing behavior when it's so easy to work around. Plus, it's possible some folks prefer to find `Bills` in the above example and then click the category. 🤷🏻‍♂️ 
I'd lean on my staying-on-the-keyboard-is-faster argument here. Also, I suspect most people get to know their category names relatively well, and don't try to find by group name. But just a guess.

**Comment by trevdor** [comment]
@Kidglove57 @joel-jeremy @MatissJanis @shall0pass 

Could a couple of you confirm or challenge my classification of this as a bug, please?

**Comment by Kidglove57** [comment]
Whilst this behaviour has never given me any difficulties (and I had not given it a second thought before), I agree that there is an very good argument for category groups to be excluded from the search/filter. I cannot see any situation, in this particular context, where I would be looking for the group name. As you say, they are not selectable.

**Comment by MatissJanis** [comment]
I share @Kidglove57 sentiment. Excluding category groups IMO makes sense.

**Comment by doggan** [comment]
I just stumbled on Actual for setting up my own budget after being a YNAB user for many years, so forgive me if this isn't the right place to post this :)

I'd vote against this change. It can be really useful as-is for certain groupings. For example, I often type "inc" when categorizing to bring up the income categories. The current behavior is also how it works in YNAB:

<img width="400" alt="image" src="https://github.com/actualbudget/actual/assets/517857/2be8f83c-7f34-40bd-8f6b-c8e40ea2651e">


The "which are not selectable" point in the original comment is valid though. YNAB handles this by shrinking the text size of the category group names, as you can see in the above screenshot. Maybe this Issue could be modified to be a UX change (shrinking the category group name text) instead of a functionality change, such that it's clear the category group names are no selectable.

**Comment by Kidglove57** [comment]
> I'd vote against this change. It can be really useful as-is for certain groupings. For example, I often type "inc" when categorizing to bring up the income categories. The current behavior is also how it works in YNAB:

I find this a really helpful perspective - thank you. It does not worry me in the least that the category groups should still appear in the filter and your point about the Income group resonated with me, as that is the group where I am least likely to remember some less used category names.

**Comment by kennylarsen** [comment]
I just discovered this. I think my preference would be for the search to focus on the categories themselves, but still display the groups in the list.

**Comment by shaankhosla** [comment]
I agree that the search should focus on the categories but display the groups. I'm new to the codebase but happy to try and tackle this

**Comment by shaankhosla** [comment]
Looking at the code, this is a super easy change. I'll open a pull request and then we can decide if we want to merge it in

**Comment by shall0pass** [comment]
I've been back and forth on this, but I think I favor the proposed change.  I also don't search by category group and have gotten to know my category names really well.  I do empathize with @doggan on the point being made.  While this change will be welcomed by some, it may be unwelcome by others.  It all comes down to how each of our typical workflows vary.

The one example in my workflow would be adding a transaction to my mobile phone category.  If I search for 'mo', I get all of my 'Monthly Cash Expenses' and 'Monthly Bills' category groups first.  It isn't until 'mob' that it starts to narrow down enough to be useful, which I realize is just 1 letter.
