### ISSUE TITLE
[Bug]: Bank Imports before budget start date

### ISSUE THREAD

**Issue by kennylarsen** [actualbudget/actual#1620]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Using the GoCardless transaction import I am sometimes getting transactions imported prior to the budget start date. This seems a little hit and miss, sometimes they appear sometimes they don't. Do we need some kind of filter which drops everything before the starting balance date?

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

**Comment by youngcw** [comment]
Has this been seen recently? The bank sync logic should check for the first transaction in an account and never pull from further back then that.

**Comment by mosbror** [comment]
I've recently started moving over from YNAB.
In the past I've just not added all account activity. So I have a similar issue.
If there would be some "sync settings" where you could set a "Ignore account activity before: 2024-03-03".
As an alternative, the system could "remember" which transaction you've deleted in the past and just not import them again with the next sync.

**Comment by youngcw** [comment]
Closing this as old.  To put a start date on bank syncing add a starting transaction to the account to set the account balance.  Sync will then not pull from before that.
