### ISSUE TITLE
[Feature] Relative transactions dates filters 

### ISSUE THREAD

**Issue by nmathey** [actualbudget/actual#1624]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Today we can only make filter base on a specific date, month or year.
Thus we are not able to limit transaction display to only show a specific "date window" without having to change the specific date.

### Describe your ideal solution to this problem

It would be great to be able to filter date based on amount of day, month or year.

This way we can for exemple only show transaction from the last 2 month only, current month included.

Exemples:
"date is greater than 30 days"
"month is greater or equal than 3 months"
"year is less or equal than 1 year"

**Comment by jamesspearsv** [comment]
I believe this feature would be a useful addition the the project. I am willing to give implementing this a try.

**Comment by glancep** [comment]
This would be **really** helpful and make saved filters SO much more useful.  I was surprised this didn't already exist and I just hadn't found out how to do it yet....
