### ISSUE TITLE
[Feature] Mobile: Show cleared/uncleared balances in account ledger view

### ISSUE THREAD

**Issue by shall0pass** [actualbudget/actual#1629]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I would like to see the cleared/uncleared balances in the account view.  I use these when checking my bank account balance to my budget account balance.

![Screenshot_20230901-061013-318](https://github.com/actualbudget/actual/assets/20625555/b065b6d1-d440-4e6c-a495-b3d0d03acd7f)

### Describe your ideal solution to this problem

I think turning the centered 'BALANCE' area into a button to toggle the values between balance and cleared/uncleared balance would be best.  For those that don't use cleared/uncleared would be unaffected and those that do use them would have a simple way to show them.

**Comment by Kidglove57** [comment]
Seconded! This would make the mobile view even more useful. Particularly when away from desktop on vacation etc

**Comment by shall0pass** [comment]
I've updated the graphic to include a rendering of a possible implementation.  The center BALANCE field is represented as a button to toggle between the current implementation and the proposed addition.
