### ISSUE TITLE
[Feature] Mobile footer improvements

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#1633]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Not really a feature request, but rather a discussion.

"The mobile footer feels crowded with 4x buttons"

What can we do to make it better?

**Comment by MatissJanis** [comment]
Personally I don't like the "settings" button in the footer. It takes up so much of the prime real estate, but is it really necessary? I suspect most folks using the mobile version won't be playing around in the settings page on a daily basis.

So if we could move that settings button to some other place - that would bring us back to 3x footer items.

But: where can we move it?

**Comment by Kidglove57** [comment]
Is one's view of "crowdedness" very much dependent on the size of the device? On an iPhone 13 Pro (not MX) I do not find the footer to be at all crowded. I am guessing mine is a fairly typical Phone size these days?

Unfortunately I do not have access to a smaller device to test.

**Comment by shall0pass** [comment]
A narrow button that is either a menu or a link to another page could work.  It would still technically be 4 buttons, but the 4th could be 1/4-1/2 the size it currently is and provide room for the remaining buttons to grow.  The menu or page contents could have the settings as a link and would also provide a way to get to reports, schedules, and rules later.  It could have the three vertical dots as the icon to represent a menu to keep it narrow.

**Comment by joel-jeremy** [comment]
Personally I don't mind the 4 buttons in the footer. But I think it could be made smaller by reducing the padding on the bottom of the buttons to make more space for the main content. I'm not sure if it's easily to implement but maybe we could hide the footer when a user scrolls down and show it when scrolling up (similar to show Gmail mobile app hides it's footer when scrolling).
