### ISSUE TITLE
[Bug]: privacy mode - performance in budget page

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#1640]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Performance in the budget page for the privacy mode is pretty bad. Need to investigate what's going on there and fix it.

Reproduction:
1. open budget page
2. show 3 months instead of just one
3. toggle privacy mode
4. notice that the browser freezes for a second or two
5. toggle it again
6. notice that the browser freezes again

Other pages (such as transaction table etc.) seem to be working OK.

### Where are you hosting Actual?

None

### Operating System

None

**Comment by Kidglove57** [comment]
I have experimented with this in a number of browsers on Mac OS with three months selected in the Budget.
1) In Brave, Chrome and Firefox, the selection/deselection of Privacy mode was instantaneous.
However:
2) In Safari I experienced exactly the momentary freezing that you describe.
This was with my own file and 4 years of data. So for me anyhow it is specific to Safari

**Comment by joel-jeremy** [comment]
This seem to be an issue with blur specific to Safari. I will try a solution mentioned here: https://graffino.com/til/CjT2jrcLHP-how-to-fix-filter-blur-performance-issue-in-safari

**Comment by joel-jeremy** [comment]
Created a PR: https://github.com/actualbudget/actual/pull/1646
