### ISSUE TITLE
Actual bridging header missing in iOS project

### ISSUE THREAD

**Issue by seangarita** [actualbudget/actual#165]
`actual-Bridging-Header.h` seems to be missing which causes the iOS build to fail. Was this file excluded on purpose? Another file `ip.txt` is also missing.

**Comment by Empty2k12** [comment]
I have the same issue with the `ip.txt` file missing.

**Comment by rich-howell** [comment]
Hey @seangarita 

Unfortunatley, the iOS & Android apps are no longer supported, we are working on a responsive Web App for Actual which should be merged into main soon.

Cheers
Rich

**Comment by fivestones** [comment]
I understand the iOS app is not longer supported. But where is its (unsupported) code?

**Comment by fivestones** [comment]
Never mind, I found it (https://github.com/actualbudget/actual/tree/01be80d56236776e02f34c59f988660961716725/packages/mobile/ios)

**Comment by subnut** [comment]
> Unfortunatley, the iOS & Android apps are no longer supported, we are working on a responsive Web App for Actual which should be merged into main soon.

@rich-howell How long till this Responsive WebApp is merged? I want to use Actual from my phone but I currently can't because the website doesn't even allow me to login from by mobile browser.

Where is the source code for this webapp? Can I help in some way?

**Comment by Kidglove57** [comment]
200% for this. It is the only thing that keeps me on the fence about Actual. Everything else is brilliant.
