### ISSUE TITLE
[Feature] Open Banking Integration

### ISSUE THREAD

**Issue by corrin** [actualbudget/actual#1661]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Similar to Plaid integration but free.  Banks across Europe and Australia have implemented Open Banking standards, allowing access to their transactions via a common API.

This has a couple advantages:

1. It's free.  
2. It doesn't have your data sent to a third party, your budget communicates straight to your bank
3.  It should scale worldwide as more banks are forced to adopt it.

I see this as complementary to Plaid.  People in countries supporting Open Banking will prefer it, while people who can't use Open Banking will use Plaid.

### Describe your ideal solution to this problem

The API should run locally.  There's no need to have a central server storing transactions or credentials.

One worry I have is that people have trouble with Plaid all the time generating duplicate or missing transactions.  Is Open Banking 100% rock solid?  If not, then some sort of UI will be needed to force re-imports.

### Teaching and learning

Transaction syncing is very popular with users.  Ideally it should be 'set and forget'.

**Comment by Jackenmen** [comment]
Currently, Actual uses GoCardless (previously known as Nordigen) to integrate with open banking APIs. There are plans to make it possible to support other services such as Plaid, SimpleFin, Aiia here: #737

As for supporting the general open banking APIs, I don't think that's particularly feasible - the EU's open banking directive (PSD2) requires you to go through a somewhat expensive and legally problematic certification process to be able to access PSD2 APIs and this process is primarily made for companies, not individuals.

More so, the API interface is not actually universal - it is at the very least defined per country, and specific banks might have various inaccuracies or offer some additional features that one has to account for (+ you need to add the actual bank to the list of supported banks in the first place). I believe that Germany has its own standard (FinTS) for open banking *in addition to* PSD2 which may be somewhat easier to integrate but you would still need someone to implement it and also have someone who can actually maintain it later which may prove hard when talking about a feature that can only be used in a specific country. A quick look into Australia's open banking seems to reveal the need to be an organization accredited by the Australian Competition and Consumer Commission so presumably that's also not easy to do as an individual.

**Comment by daveneeley** [comment]
The [Financial Data Exchange](https://financialdataexchange.org/) standards body which claims to have global membership. Perhaps it's an area to watch. 

> FDX is a non-profit industry standards body operating in the US and Canada that is dedicated to unifying the financial services ecosystem around a common, interoperable and royalty-free technical standard for user-permissioned financial data sharing, aptly named the FDX API. FDX is an independent subsidiary of the Financial Services Information Sharing and Analysis Center (FS-ISAC), and has a global membership that includes financial institutions, financial data aggregators, fintechs, industry utilities, payment networks, consumer groups, financial industry groups and other stakeholders in the financial sector.

**Comment by totti4ever** [comment]
Perhaps one could learn from / reuse firefly 's FinTS import?

**Comment by fed239** [comment]
Hey! @enablebanking CTO here. If you are looking for a free and privacy focused open banking solution, checkout our linked accounts feature: https://enablebanking.com/accounts-api/#linked-accounts. Anticipating questions why we offer this, here a link to my old post on reddit: https://www.reddit.com/r/eupersonalfinance/comments/k4ny3j/free_api_access_to_currrent_cards_accounts_data/ (the post is outdated in terms of supported countries, coverage grew a lot, many thanks to our users)
