### ISSUE TITLE
[Bug]: SharedArrayBuffer Error/Confusion

### ISSUE THREAD

**Issue by JBlocklove** [actualbudget/actual#1667]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

More of a question than a bug, but I seem to have a weird issue with the SharedArrayBuffer that I don't fully understand.

I access my instance of Actual (dockerized) through a reverse proxy using Nginx Proxy Manager, which allows me to force access with HTTPS. I recently wanted to try a new browser on my phone, Hermit (https://hermit.chimbori.com/), and I got an error saying  that "Actual requires access to SharedArrayBuffer in order to function properly".

Looking into this, it seems I needed to add some headers to the proxy for Actual, despite the fact that it's been working fine in both Firefox and Chromium. Adding these headers causes it to give me this error on all browsers that I've tried, no longer just Hermit. To me this indicates that the issue with Hermit is that it doesn't support SharedArrayBuffer but I don't understand why adding those headers would cause the error for other browsers. Both Firefox and Chromium have confirmed support for SharedArrayBuffer so it should still work fine I think. Networking and web development are very much not my areas of expertise so I'm not sure if my particular setup just doesn't require those headers or what.

Can anyone shed some light on what's going on here and help me understand why adding these headers creates the problem they're theoretically supposed to solve?

The exact headers I added are as follows:
```
add_header "Cross-Origin-Opener-Policy" "same-origin";
add_header "Cross-Origin-Embedder-Policy" "require-corp";
```

### What error did you receive?

Actual requires access to `SharedArrayBuffer` in order to function properly. If you’re seeing this error, either your browser does not support `SharedArrayBuffer`, or your server is not sending the appropriate headers, or you are not using HTTPS.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome, Other

### Operating System

Linux

**Comment by Chris1320** [comment]
I also received the same error on Firefox Stable, Nightly, and Nightly on Android. I am running Actual via Podman, and it runs fine when I use Ungoogled Chromium browser.

**Comment by MatissJanis** [comment]
👋 I'd suggest posting this on the support channels of Discord to get some help. We generally don't use Github issues here for support.

And since this is not really a bug report - closing it off.
