### ISSUE TITLE
[Feature] Allow manually entered future transactions to be included with the "upcoming" scheduled transactions for sort/display

### ISSUE THREAD

**Issue by htims05** [actualbudget/actual#1675]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

If you have a bunch of scheduled transactions they show at the top of the register as "upcoming" and date sort ignores these.  However if you manually enter a future dated transaction that transaction is included in with everything else and is included with sort...so you can run into an issue with your running balance being incorrect.

Example:
You have a schedule for your paycheck ever 2 weeks - so it shows upcoming at the top and is excluded from sort.  Say this is scheduled for the 15th of the month.  But you also know you have a one-time bill or another payment that's due on the 16th....so you go ahead and enter it in your Actual Budget (and maybe you even schedule the bill pay from your bank).  If you enter this future bill, it'll go in with your other transactions and be sorted by date accordingly.  However it can make your running balance go negative because that "upcoming" paycheck scheduled transaction is at the top, not included in the transaction sorting.

### Describe your ideal solution to this problem

Any future dated transaction be it manually entered or from a schedule should be considered "upcoming" like the schedule is today...and not included in the sorting of the transactions until that date comes.

### Teaching and learning

None really needed - it's pretty apparent how it works today and if you keep all future transactions at the top together there will be no confusion.

**Comment by tavlima** [comment]
Would something like https://github.com/actualbudget/actual/issues/2296 help?
