### ISSUE TITLE
[Bug]: Transaction import not working anymore

### ISSUE THREAD

**Issue by bstritesky** [actualbudget/actual#1676]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I can no longer import my .QFX files for my credit card or bank accounts from different institutions. This was working last weekend after I had updated to 23.9.0, I'm pretty sure.

I have recently upgraded to the latest version 23.9.0 on Docker. I have tried the following steps to remedy:

- Updating the base Linux machine with all updates
- Remove all cached site data and cookies for my Actual instance
- Multiple different .QFX files, including those that were working last week
- I'm able to make manual updates to transactions or leave notes

I am not seeing much other information about how best to debug or troubleshoot. I'm not familiar with Node.js debugging, nor where I might be able to find more detail error logs to provide more helpful information.

Thanks for any assistance you can provide!

### What error did you receive?

When I attempt to import, I immediately see an error message in the bottom right: "Something internally went wrong. You may want to restart the app if anything looks wrong. Please report this as a new issue on Github." Then what would be the import window showing transactions appears but is blank with a spinning loading icon.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by MatissJanis** [comment]
👋 This bug has been reported a few times already. It has been patched in the `edge` release. You can either wait for the next release (v23.10.0) or temporarily move to the `edge` tag.

**Comment by bstritesky** [comment]
#1653 seems to be the duplicate. Thanks.
