### ISSUE TITLE
[Feature] Groups for accounts 

### ISSUE THREAD

**Issue by nmathey** [actualbudget/actual#1683]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Today we have accounts split in two groups: For budget and Off-budget.
Sometime we might need to arrange accounts in different groups, for categorization or usage.

Groups account usages exemples:
 - Separating check accounts and saving accounts
 - Separating accounts owners
 - Grouping check account and its credit card account attached to it: this way I know I should make sure my check account doesn't have negative balance before credit card debt being paid automatically every month.
 

### Describe your ideal solution to this problem

Being able to arrange accounts into specifics group name for personal usage

**Comment by CrazyKidJack** [comment]
Infinite nesting please!

**Comment by Felixre7** [comment]
i would LOVE this feature!

**Comment by abhiy98** [comment]
Would love this feature especially in off budget

**Comment by Rogue136198** [comment]
I was thinking about how this could be implemented in a basic form. One option that came to mind for an initial implementation is simple sub headings under On budget and Off budget. In my mind, the current headings would be made slightly larger and the new sub headings would be similar sized to the existing ones. This would be a very simple implementation only providing visual organization without any use for filtering. More could be built from there.

In my case it would look like this:

On budget
  -  Joint Chequing Accounts
  -  Credit Cards
  -  My Chequing Accounts
  -  Partner Chequing Accounts

Off Budget
  - House and Vehicle
  - Lines of Credit
  - My Savings
  - Partner Savings
  - Dormant Accounts

**Comment by shaunnope** [comment]
I have an idea for a (hopefully) straight-forward way to support this feature, drawing inspiration from the way Obsidian handles tag groups: using forward slashes akin to filesystem directories.

Example: A hierarchical grouping of accounts might look like below.

```
On budget
├─ Bank A
├─ Bank B
│  ├─ Joint account
│  └─ Personal account
│     └─ Retirement Fund
└─ Cash

Off budget
├─ House & Mortgage
├─ Investments
└─ Savings
```
The full, qualified names of the accounts under Bank B would be `Bank B/Joint Account` and `Bank B/Personal Account/Retirement Fund` resp. 

Minimal changes to the database schema should be needed as the grouping of accounts would be purely visual, performed on the front-end.

Some other related features that come to mind are:
- Balance aggregation of accounts in the same subgroup (similar to the On-/Off-budget totals)
- Treatment of group indices: e.g. in the layout above, can `Bank B` be its own account?

While I am interested in developing this idea further, it might take me a while to prepare a PR for this, to familiarize myself with Actual's project structure.

**Comment by SvenPegels** [comment]
This would be incredibly useful for the way I use accounts as savings jars. I'll have one actual bank account, which has the money for multiple 'savings jars'. Being able to group them under the name of the actual bank account, as well as collapse the group, would make the list of accounts a lot less messy. 

The group showing the total balance of all accounts within that group would be a neat feature as well. It would make it a lot easier to see the actual total of the bank account, while at the same time knowing the amounts in each 'savings jar'.

**Comment by jfdoming** [comment]
> This would be incredibly useful for the way I use accounts as savings jars. I'll have one actual bank account, which has the money for multiple 'savings jars'. Being able to group them under the name of the actual bank account, as well as collapse the group, would make the list of accounts a lot less messy.
> 
> The group showing the total balance of all accounts within that group would be a neat feature as well. It would make it a lot easier to see the actual total of the bank account, while at the same time knowing the amounts in each 'savings jar'.

Are you using envelope budgeting? What you describe sounds like the behaviour of budget categories and category groups.

**Comment by kennydrobnack** [comment]
> I recently moved away from using Quicken for years and this is the one feature I miss. It was very helpful to have all my credit cards grouped, bank accounts grouped, investments grouped, etc. While Quicken for Mac was limited in the ability to truly customize it, the view is still much cleaner than Actual Budget when adding a lot of accounts (especially when it’s both me and my wife).

I've been using Banktivity for a while and it also has this feature. It shows the total balance of the accounts in the group and I've got my on-budget accounts in one group for bank accounts (checking and saving) and another for credit cards. If I see the credit card balance creeping up on what I have in checking, I know it's time to pull back a bit on spending without even needing to check out my budget.

Then off-budget I have one group for retirement accounts and one for all other off-budget accounts (investment, current home value, and also have one for gift cards so I can track transactions mostly for warranty purposes)

**Comment by amelandri** [comment]
+1👍 I would love this feature

**Comment by amit-bh** [comment]
Would love this feature as well. At least for credit cards, I think having a separate credit card category nested under on budget accounts with total balance of all credit cards listed at the subheading would be a great way to assess debts

**Comment by dkershner6** [comment]
I would also suggest adding this as an option in custom reports for the "split".  Likely more useful than account if being used.

**Comment by Str1atum** [comment]
Great idea!
I could use two separate files and consider that at the moment, but I cannot transfer amount between the files for example.

This should also enable different budgets for separate accounts in one actual budget file.

**Comment by tthibus** [comment]
Hello.
This is a great feature I would like to see implemanted.
As already said, this could be useful to group account according each personnal choice (same bank, type of account, etc.).
How to vote for this feature ? This post is enought or should I use another way ?

**Comment by db-src** [comment]
Just thumbs-up the initial post. Anyways, there's a pull request for this in progress that'll hopefully be merged.

**Comment by SvenPegels** [comment]
> Just thumbs-up the initial post. Anyways, there's a pull request for this in progress that'll hopefully be merged.

The link to the PR for convenience: https://github.com/actualbudget/actual/pull/6921

**Comment by shebdon** [comment]
Yes, i would especially like to have my retirement accounts in a group that gets subtotalled at least. It's not a spending/budget account, but i do track them and would at least like a quick subtotal. 

I suppose i could get a subtotal set up as a report, but i spend just of my time in other pages.

**Comment by gagegogan** [comment]
It seems all PRs are stale and closed. Is this being worked on?

**Comment by StephenBrown2** [comment]
> It seems all PRs are stale and closed. Is this being worked on?

related: https://github.com/actualbudget/actual/pull/8297
