### ISSUE TITLE
[Bug]: mobile - scrolling in transaction list and account list

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#1699]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

On mobile

When you first scroll DOWN in the transaction list or account list the scroll does not happen. You need to scroll down one more time for the scroll to register.

### Where are you hosting Actual?

None

### Operating System

None

**Comment by Kidglove57** [comment]
Is anyone else seeing this? I have been trying to reproduce (Safari on iPhone 13 Pro - iOS17.

**Comment by MatissJanis** [comment]
I forgot the mention that this is on `edge` or demo.actualbudget.org

**Comment by shall0pass** [comment]
I am able to repro this on my Edge build.  Strange I hadn't noticed it before though.

**Comment by trevdor** [comment]
I'm seeing it, too. In the Chromium mobile emulator as well as on my iPhone 13 Mini

**Comment by Kidglove57** [comment]
Thanks all - I am in Greece with just a mobile but have reproduced using the Demo.
