### ISSUE TITLE
Publish Docker Image

### ISSUE THREAD

**Issue by m3nu** [actualbudget/actual#17]
Hey @jlongster,

congrats on the big re-launch as open source project! Being a FOSS maintainer myself, I can confirm that this can bring as much fulfillment and joy as a successful startup. So I hope this model  will work for you.

One of the first things I'd recommend is to add a Docker image and do regular releases to make it simple for people to start developing and deploying the project. This would also allow us to add your app to [PikaPods.com](https://www.pikapods.com/), which is a simple way of running FOSS projects for non-technical users. We regularly work with new projects to help them set up their Docker workflow.

So if this (adding Docker, being on PikaPods or both) is interesting for you, I'd start working on a Dockerfile and GH Action to keep it updated.

Cheers,

Manu

**Comment by denysvitali** [comment]
```Dockerfile
FROM node:lts                                                            RUN git clone https://github.com/actualbudget/actual-server.git /app     WORKDIR /app                                                             RUN yarn                                                                 CMD ["yarn", "start"]
```

?

**Comment by m3nu** [comment]
Yes, looks like a good start. Just without the git clone, since usually you keep the Dockerfile in the same repo. Let me try that later.

**Comment by clementduveau** [comment]
There is a Docker image. It is in the actual-server repo !

**Comment by m3nu** [comment]
Yeah, the [Dockerfile](https://github.com/actualbudget/actual-server/blob/master/Dockerfile) is already there and people are already making improvements and added a [GH Action to publish it](https://github.com/actualbudget/actual-server/pull/11). So we should see an official image shortly.

Already added Actual to [PikaPods](https://www.pikapods.com) for one-click setup. Both EU and US regions are avaiable. All files are accessible over SFTP, if you need to migrate or access them. The free welcome credit is enough to run Actual for around 3.5 months.

[![Run on PikaPods](https://files.qmax.us/run-button-sized.svg)](https://www.pikapods.com/pods?run=actual)

**Comment by jlongster** [comment]
Thank you! We are working on this in https://github.com/actualbudget/actual-server/pull/11

**Comment by rich-howell** [comment]
Closing, this is being worked on [here](https://github.com/actualbudget/actual-server/pull/11) as per @jlongster [comment](https://github.com/actualbudget/actual/issues/17#issuecomment-1118898430) above
