### ISSUE TITLE
[Bug]: Incorrect color for errored bank-sync account

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#1702]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

This is a `master` branch (edge) issue. The tagged release seems to be OK.

Most likely a darkmode regression (cc @carkom)

--

When bank-sync fails the status color currently is white. The failure color should instead be red.

<img width="235" alt="Screenshot 2023-09-15 at 20 10 05" src="https://github.com/actualbudget/actual/assets/886567/eb57cfe7-97b0-4d3d-9e75-9f2f8f534f4b">

### Where are you hosting Actual?

None

### Operating System

None

**Comment by carkom** [comment]
Any idea where this resides?

**Comment by carkom** [comment]
I got it. I'll open a PR to fix
