### ISSUE TITLE
[Feature] Mobile UI Ideas

### ISSUE THREAD

**Issue by shall0pass** [actualbudget/actual#1710]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I decided to play around with some possibilities for the future of the mobile UI.  I had some fun anyways, take them or leave them :)

![image](https://github.com/actualbudget/actual/assets/20625555/7db226d5-0687-41df-bb56-dabd12f1d269)

![image](https://github.com/actualbudget/actual/assets/20625555/3479361a-1735-4fb9-b976-4b0bc311a18d)

![image](https://github.com/actualbudget/actual/assets/20625555/0f87ead1-f925-4230-9406-8e224c75a520)

**Comment by Crazypkr1099** [comment]
It's possible to do this, and the creativity is very nice.

I'm not sure if this is what the vision of Actual mobile is though. From what I read from @trevdor , Actual mobile is a way to complement Actual web, and a way to view your budget, add transactions etc. It isn't a way to have every single feature that is on the web integrated.

I could be wrong, curious to what Trevdor has to say.

Thanks for the concept :)

**Comment by Kidglove57** [comment]
Thank you @shall0pass! 

Whilst the minimum requirement for Actual mobile is to enter transactions and view the budget, I personally see no reason why it should not in time develop into something more fully fledged. So long as this is possible within the constraints of a responsive web app. I know many would welcome this.

**Comment by shall0pass** [comment]
The rules page is already super close to being ready for mobile. The header bar needs fixed so it doesn't expand, but other than that it looks really good imo.  But we need a way to get to it. 

 I was trying to think of ways that didn't add to much clutter to the Ui, maybe the buttons in the budget dialogue fall short of that goal?

![Screenshot_20230919-035245](https://github.com/actualbudget/actual/assets/20625555/02bb9e02-8dcf-4f36-9f79-2ee79df4299c)
![Screenshot_20230919-035240](https://github.com/actualbudget/actual/assets/20625555/434af373-ce4e-4157-a0de-2a84175deebc)

**Comment by Kidglove57** [comment]
Thanks! Yes the budget buttons were my main concern too.

**Comment by Kidglove57** [comment]
I love where this is going.

 For some reason I cannot see the updated budget actions image - only the original"set budget" buttons. I may be missing something ...

**Comment by Kidglove57** [comment]
PS Bt the way, I loved the inclusion of the Goal Template button. I rely so much on using the templates at the start of each month!

**Comment by youngcw** [comment]
Closing this since most of the suggestions here are in, or partially in.
