### ISSUE TITLE
[Bug]: visual - searchbar size in schedules page

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#1713]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

The searchbar in the schedules page is noticably smaller than in rules/payees. We should make the schedules search bar bigger.

Schedules page:
<img width="367" alt="Screenshot 2023-09-19 at 17 43 23" src="https://github.com/actualbudget/actual/assets/886567/a6b18a2d-ec71-47e3-a4c2-79b0c07167ec">

Rules page:
<img width="403" alt="Screenshot 2023-09-19 at 17 43 35" src="https://github.com/actualbudget/actual/assets/886567/86c422ad-efda-4ac2-a0ce-e11945820df0">

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Safari

### Operating System

Mac OSX

**Comment by shaankhosla** [comment]
Hm I don't see this issue on demo even with Safari on a Mac.

**Comment by MatissJanis** [comment]
To reproduce you'll need to create a bunch of schedules.

Here's a demo budget: 
[2023-09-22-_test-budget.zip](https://github.com/actualbudget/actual/files/12703753/2023-09-22-_test-budget.zip)

**Comment by Kidglove57** [comment]
On my instance of Actual the height of search field is so truncated that the text does not quite fit within it (I have a great many schedules - not sure if that makes a difference).
