### ISSUE TITLE
[Bug]: Report budget Visual regression

### ISSUE THREAD

**Issue by shall0pass** [actualbudget/actual#1717]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

There appears to be a regression in the Report budget.  The dark line under September used to be a much lighter gray.  I'm also not sure when the month received an underline.  Was that on purpose?

Now:
![image](https://github.com/actualbudget/actual/assets/20625555/f3664900-cfaa-4403-ae1c-66e2f7128d4d)

Before:
![image](https://github.com/actualbudget/actual/assets/20625555/fa8b232d-d205-45f8-8d06-84faf59b6a44)

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by MatissJanis** [comment]
cc @carkom

**Comment by carkom** [comment]
I'm unable to duplicate this. Everything I try shows no underline and no border changes. Can anyone confirm this bug?

**Comment by MatissJanis** [comment]
@carkom you'll need to enable the "budget mode" feature flag and then switch to rollover budget to reproduce.

**Comment by carkom** [comment]
Thanks for directing me. Here is what I see on current master. The dark line is gone and the underscore is not a dark theme regression it's been there long before any dark theme changes were merged. Happy to fix it though!

![image](https://github.com/actualbudget/actual/assets/55785687/26fa2c90-9e60-47e5-8ba1-cadd5f3e79f9)

**Comment by shall0pass** [comment]
I'm still seeing it on master.  It only changes when you collapse the monthly header.  I agree the underline was there a long time and wasn't part of the dark theme PRs.
![Screenshot_20230928-102801](https://github.com/actualbudget/actual/assets/20625555/07be633e-e986-48d8-9d7d-f518b279d828)

**Comment by carkom** [comment]
Ahh, the header collapse! How'd I miss it? I see it now. Thanks!

**Comment by carkom** [comment]
Okay, have the border fixed.

Here is the underline code. Would you like me to remove it?

              currentMonth === month && { textDecoration: 'underline' },
