### ISSUE TITLE
[Bug]: Internal Error when using Import

### ISSUE THREAD

**Issue by mommyofavalor** [actualbudget/actual#1727]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

A bug happened!

When I went to important my normal statement I got a red "Internal Error" message on the bottom asking me to report to Github. 

I tried on both Internet Explorer and Google Chrome. Both allowed me to click "import", choose my statement and then showed the outline of the grey box and a spinner and would not fully upload.

I use PikaPod.

I restarted both PikaPod and restarted my computer. Still same issue in exactly same way.

### What error did you receive?

](url)
<img width="1261" alt="Screen Shot 2023-09-23 at 8 29 29 AM" src="https://github.com/actualbudget/actual/assets/138994055/e108c82a-ff39-4de4-8e75-2539f81e1cb5">

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by MatissJanis** [comment]
👋 Would you mind providing an example import file so we could reproduce? Without being able to reproduce there won't be much we can do to help you.

**Comment by mommyofavalor** [comment]
Github won't let me attach a .qfx file. How can I share it with you?

**Comment by MatissJanis** [comment]
You can upload `.zip` files.

Also: are you able to reproduce this issue in [demo app](https://demo.actualbudget.org). If not: then the issue has already been fixed and will be available in the v23.10.0 release.

**Comment by mommyofavalor** [comment]
[](url)
[activity-12.qfx.zip](https://github.com/actualbudget/actual/files/12707045/activity-12.qfx.zip)

The demo app isnt opening for me when I click on the hyperlink in your comment. Thank you for taking the time to respond.

Is v23.10.0 already released?

**Comment by MatissJanis** [comment]
<img width="870" alt="Screenshot 2023-09-23 at 20 29 13" src="https://github.com/actualbudget/actual/assets/886567/e4e4002a-2fe5-470d-8527-b1e4822b8ed7">

Your example file works on the demo app (which is using the latest changes in `master` branch). So it's safe to assume this has already been fixed.

v23.10.0 will be released in the first few days of September. If you prefer not to wait - you can always use the `edge` tag (but be prepared that things might break): https://actualbudget.org/docs/install/docker#edge-tag

**Comment by m-GDEV** [comment]
I'm also having the same issue as the user above. I'd rather not share my .qfx file but here is the error that showed up in the console. There were two separate errors. I'm using `actual v23.9.0` for both the server and client version. 

I run actual-server on my own vps by cloning the repo and running `yarn start`. Not sure if this helps.

```
[Exception] TypeError: Cannot read properties of null (reading 'fallbackMissingPayeeToMemo')
    at parse-file.ts:135:33


parse-file.ts:135 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'fallbackMissingPayeeToMemo')
    at parse-file.ts:135:33
```

If someone knows what might be causing the issue I'd appreaciate it! Thanks.
