### ISSUE TITLE
[Bug]: OFX transactions offset by 1 day

### ISSUE THREAD

**Issue by bverkron** [actualbudget/actual#1731]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Same issue as https://github.com/actualbudget/actual/issues/1053, was not resolved via the fix.

Dates are offset by -1 day when importing files such as the following. Other files from other institutions work fine.
[statement.6.qfx (1).zip](https://github.com/actualbudget/actual/files/12707451/statement.6.qfx.1.zip)

Still happening in the latest 23.9.0 version

### What error did you receive?

No error dates are just off.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome, Safari

### Operating System

Mac OSX

**Comment by joel-jeremy** [comment]
@bverkron Do you have the experimental OFX parser enabled?

**Comment by bverkron** [comment]
@joel-jeremy I don't believe so. I imagine it would show here in the settings? Or it it set elsewhere?

![image](https://github.com/actualbudget/actual/assets/19174503/a134e8ef-d110-488d-87ec-cc2d106a947e)

**Comment by bverkron** [comment]
Hmm yeah looks like it should be there according to this and it was release in 23.5.0 [according to the release notes](https://actualbudget.org/docs/releases/#features-5). Any idea why I'm not seeing it?

https://github.com/actualbudget/actual/pull/1600

**Comment by joel-jeremy** [comment]
There is a new experimental OFX parser in that page but is only available in edge at the moment. Would you be able to test your import on the edge version and the experimental OFX parser enabled?

**Comment by bverkron** [comment]
That seems to work!

From my institution...

![Screenshot 2023-10-02 at 2 52 53 PM](https://github.com/actualbudget/actual/assets/19174503/1ab94189-4415-447a-a874-87fb1a4af1d6)

In the import dialog (after import the dates matched as well)...

![Screenshot 2023-10-02 at 2 52 17 PM](https://github.com/actualbudget/actual/assets/19174503/5b813289-599a-4373-bab9-fa7b67dd493e)

Side note, is there an open request to have the sort date of the import dialog be in reverse chronological order instead of the current chronological order or allow it to be sortable? I think the default for the accounts is reverse chronological (or at least that's how I have it and most people seem to use it) and same with banking institution usually. Would be nice if it would match in the import dialog. If not I can open a request :)

**Comment by youngcw** [comment]
Can this be closed?  Looks like the new parser doesn't have the same issue.

**Comment by bverkron** [comment]
I'm good to close it yes. Thanks!
