### ISSUE TITLE
[Bug]: mobile - single account - back button is flaky

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#1735]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

The "back" button in single account page when using the mobile version is not always working.

Reproduction;
1. open mobile app
2. go to a single account
3. edit a transaction and click save;
4. edit another transaction and click save;
5. click "go back" - nothing happens

Related to https://github.com/actualbudget/actual/pull/1648

cc @joel-jeremy 

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Safari

### Operating System

Mobile Device

**Comment by joel-jeremy** [comment]
I think this happens because after the transaction is saved, it goes to the account page. This results in 2 same account pages on top of the history stack and pressing back looks like it does nothing because it just goes back to the same page. I'll check it out.

**Comment by DomiJV** [comment]
I think this problem is not yet fixed. When using the mobile layout, after selecting an account and adding multiple transactions, I have to press the back button multiple times before it returns to the budget overview.
