### ISSUE TITLE
[Bug]: Upcoming scheduled entries' are displaying the account name in the payee field

### ISSUE THREAD

**Issue by afv22** [actualbudget/actual#1741]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When viewing the "For Budget" tab, all upcoming scheduled rows are displaying the account name in the payee field. When viewing them in the individual account's tab, the correct payee name is displayed. All non-scheduled rows in "For Budget" are also displaying correctly.

![ActualBug](https://github.com/actualbudget/actual/assets/38698043/56131e19-7b71-4233-a31a-cb6abf9b534e)

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by joel-jeremy** [comment]
@afv22 What version are you using? I can't seem to replicate the issue on https://actualbudget.netlify.app/.

**Comment by youngcw** [comment]
Im not seeing this either.  Ill close this in a few days if there aren't any complaints
