### ISSUE TITLE
[Bug]: GoCardless sync - Couldn't update account transactions - statut_code : 500

### ISSUE THREAD

**Issue by mdrcrch** [actualbudget/actual#1742]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

First, thanks a lot for all your work on Actual !

The bug I encountered is the following : "Failed syncing account “BforBank.” when trying to sync my newly linked BforBank account.
The container logs show : 

```
Something went wrong {
  summary: "Couldn't update account transactions",
  detail: 'Something went terribly wrong on our side - please contact support and provide error id: 521fb2f5b730f1c8322bc1fd257766a2',
  status_code: 500
}
``` 
I red the above message and did what it told me to do : contact support and provide the error id.

Everything when very well with two other bank accounts.

Thanks again and have a nice day :)

### What error did you receive?

Failed syncing account “BforBank" on screen.
And this one in log : 
```
Something went wrong {
  summary: "Couldn't update account transactions",
  detail: 'Something went terribly wrong on our side - please contact support and provide error id: 521fb2f5b730f1c8322bc1fd257766a2',
  status_code: 500
}
``` 

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Linux

**Comment by MatissJanis** [comment]
👋 As the error message states: I'd recommend reaching out to GoCardless support to resolve this issue. This is on their end.

**Comment by sazzadpiash** [comment]
Just Had the same issue, already contacted them...hoping to solve the issue real soon
