### ISSUE TITLE
[Bug]: Uncategorized transactions do not change the amount that can be budgeted

### ISSUE THREAD

**Issue by piotrbelina** [actualbudget/actual#1744]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Hello everybody!

First of all I would like to say hi and thank you for the great work :) 

I noticed a behavior where Actual differs from YNAB in terms of handling uncategorized transactions. In Actual they are not taken into consideration in the amount that can be budgeted. I would like to ask if it is on purpose or it is unwanted behavior?

Below I attach comparison between Actual and YNAB.

**YNAB**
![Zrzut ekranu 2023-09-28 o 11 40 03](https://github.com/actualbudget/actual/assets/1667676/823fe998-bf95-43bb-9799-1ee451df75fc)
![Zrzut ekranu 2023-09-28 o 11 39 52](https://github.com/actualbudget/actual/assets/1667676/73a51515-0fce-4876-8a94-636d2fd2d530)
![Zrzut ekranu 2023-09-28 o 11 40 20](https://github.com/actualbudget/actual/assets/1667676/c419ee54-5a87-4684-8d7a-346de54a2fed)

**Actual**
![Zrzut ekranu 2023-09-28 o 11 41 10](https://github.com/actualbudget/actual/assets/1667676/c08ee722-53cd-448e-b25d-ba9f87296e38)
![Zrzut ekranu 2023-09-28 o 11 41 04](https://github.com/actualbudget/actual/assets/1667676/0c1e51e5-9b1f-4711-9881-1b5bad5c6ae0)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Safari

### Operating System

Mac OSX

**Comment by youngcw** [comment]
closing this.  There is a feature request to add this style of functionality #1794
