### ISSUE TITLE
[Bug]: Split transactions are double counted in off-budget accounts

### ISSUE THREAD

**Issue by CalebBurton** [actualbudget/actual#1746]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When adding a split transaction in a budgeted account that is a transfer to an off-budget account, the off-budget account receives the parent transaction _as well as_ each of the child transactions. The value of the transaction is therefore doubled. Example screenshots below.

Budgeted account making the split transfer:
<img width="840" alt="budgeted_account" src="https://github.com/actualbudget/actual/assets/8314716/127fcfe6-ccd9-4fb8-b1e0-0ba13795f66b">

Off-budget account receiving the split transfer:
<img width="840" alt="off_budget_account" src="https://github.com/actualbudget/actual/assets/8314716/918b9465-1ece-4512-8ead-d5fe4a58548e">

I'm running server version v23.9.0 via docker and client version v23.9.0 via Firefox and Chrome on macOS.

This might be related to https://github.com/actualbudget/actual/issues/1574 and https://github.com/actualbudget/actual/issues/1732, but it's a distinct symptom from what those describe.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Mac OSX

**Comment by joel-jeremy** [comment]
Hi @CalebBurton! Taking for reporting the issue. I have created a fix for this via https://github.com/actualbudget/actual/pull/1751.

**Comment by CalebBurton** [comment]
Wow, thanks for that extremely fast fix! Glad that it wasn't too complicated to resolve

**Comment by joel-jeremy** [comment]
Closing this as #1751 have been merged.
