### ISSUE TITLE
[Bug]: "end of month cleanup" crashes if no db entry exists for first overspent budget

### ISSUE THREAD

**Issue by jlsjonas** [actualbudget/actual#1748]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

If a category was _overspent_ without an initial budget entry (never touched; clearing will preserve the db entry), it can't find the carryover as it doesn't exist yet

### What error did you receive?

> Something internally went wrong. You may want to restart the app if anything looks wrong. Please report this as a new issue on Github.

in console:
```
[Exception] TypeError: Cannot read properties of null (reading 'carryover')
    at cleanup-template.ts:64:17
```

### Where are you hosting Actual?

NAS

### What browsers are you seeing the problem on?

Chrome

### Operating System

Other (Chrome OS)

**Comment by youngcw** [comment]
Fixed by #1750
