### ISSUE TITLE
[Bug]: --color-pageTextLink on settings page hard to read in dark mode

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#1760]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When viewing Actual in Dark Mode as of 23.10.0 the --color-pageTextLink links are really difficult to read

![image](https://github.com/actualbudget/actual/assets/22135084/7197d7ce-f0b5-4d4c-9131-fc67985f3b90)

Proposal is that these are made darker so that they are easier on the eye.

![image](https://github.com/actualbudget/actual/assets/22135084/21b391c3-77bf-4362-bc00-fd5c0000240d)

The above image also uses a strong weight.

### What error did you receive?

None

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

**Comment by Evomatic** [comment]
Hi @rich-howell I am interested in working on this issue if that is alright.

**Comment by paul-ooi** [comment]
My suggestion on when considering "what is easier on the eyes" is look at using webAim's color checker (https://webaim.org/resources/contrastchecker/). To ensure the foreground and background pairing pass (AA) for the size that this text is at.  This way it's "easier on the eyes" for more people.

**Comment by Evomatic** [comment]
> @Evomatic , my suggestion on when considering "what is easier on the eyes" is look at using webAim's color checker (https://webaim.org/resources/contrastchecker/). To ensure the foreground and background pairing pass (AA) for the size that this text is at. This way it's "easier on the eyes" for more people.

Hi @paul-ooi Thank you for sharing, I will take a look!

**Comment by youngcw** [comment]
closing this as fixed with the updated colors.
