### ISSUE TITLE
[Bug]: Dark Mode Server State & Sync State 

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#1761]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Server State & Sync State are missing the color attribute: --color-buttonBareText while dark mode and privacy mode have this applied. 

This is in version 23.10.0

### What error did you receive?

None

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

**Comment by 0xJaskeerat** [comment]
Can we close this issue as PR is merged
