### ISSUE TITLE
[Bug]: Dark Mode upcoming schedules muted

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#1763]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

In light mode upcoming schedules are highlighted in the schedules screen

![image](https://github.com/actualbudget/actual/assets/22135084/22f4e8bf-6b0f-4948-9895-541bfa93cb9b)

However in dark mode they are muted 

![image](https://github.com/actualbudget/actual/assets/22135084/e45e0d58-fe16-4e06-91e0-995d03f75e02)

### What error did you receive?

None

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

**Comment by iceTmZz** [comment]
I will like to be assigned for this task
