### ISSUE TITLE
[Bug]: Blank page on mobile iOS after updating to 23.10

### ISSUE THREAD

**Issue by valterbarreira** [actualbudget/actual#1766]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I'm using yunohost and after updating to 23.10 i can't acess on mobile. Tried safari and firefox and page is blank. I have cleaned cookies and sites data, but didn't worked.

But on desktop, i can acess and using responsive design and choosing my phone it works well.

If it helps i didn't log off on mobile before updating.

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Firefox, Safari

### Operating System

Linux

**Comment by Kidglove57** [comment]
I have tested in mobile safari (I am hosting on Fly) and all is working well.

You may have already done this but have you tried deleting your file locally and then re-downloading it?

**Comment by Kidglove57** [comment]
Got it! I’ll have to leave a response to others who have experienced the same as you.

**Comment by tjfinlinson** [comment]
@valterbarreira 

You will probably get quicker support by posting in the support channle on the discord chat for Actual.

https://discord.com/channels/937901803608096828/1027966372862505021

**Comment by shenxs** [comment]
I have the same issue, I found that 
![image](https://github.com/actualbudget/actual/assets/9768335/51b67657-868e-41db-9dcc-ac01c0d03b05)

**Comment by shenxs** [comment]
I use safari on ios 16.0.3 on iphone 14 pro, but on ios 17 it works fine

**Comment by valterbarreira** [comment]
I'm on ios 15.7.8, but i can't acess on any browser. Where can i see that console on mobile? Is from safari?

**Comment by valterbarreira** [comment]
ok, i have found how to inspect a site on safari ios. I have the same error on my actual and demo site
![Uploading Captura de ecrã 2023-10-12, às 11.29.50.png…]()

**Comment by valterbarreira** [comment]
![Captura de ecrã 2023-10-12, às 11 37 27](https://github.com/actualbudget/actual/assets/16954563/59cb0a27-4bdd-47d8-a0d7-bf45c57c2fcf)

**Comment by valterbarreira** [comment]
Ok I’ll try to update to iOS 15.8

**Comment by LizardList** [comment]
Anecdotally, friend also had this same bug on iOS, and it went away after updating their phone.

**Comment by valterbarreira** [comment]
Updated to iOS 15.8 but didn’t solved the issue

**Comment by prostoprojekt** [comment]
Hi there, can confirm that for Iphone ios  15.5 and Safari \ Chrome shows blank when trying to access to budget server address (via reverse proxy , running on Synology NAS).. Desktop version runs OK

Actual Budget version is 23.10

P.s. I have another Actual server (not being updated, running in the same landscape, v.23.6.0) I can access it from metioned Apple Iphone, but that version supports only reporting no mobile data entry. 

Looks like smth need to be fixed for 23.10

**Comment by valterbarreira** [comment]
not only 23.10 but also 23.11, updated to latest versio and shows the same blank page

**Comment by Darkcrown96** [comment]
Same for me, 23.10 and 23.11 doesn't work on mobile while on desktop everything is fine. I'm on iOS 16.0

**Comment by latetedemelon** [comment]
Another Datapoint:  Mobile appears broken for me as well for versions 23.11 and 23.12

Desktop browsers: no issue

Behaviour:  Everything appears fine until downloading the budget; this takes a very long time but appears to fail.  After several minutes I get budget showing with demo categories.  Clicking sync results in an error.

Tested on:
- iphone 12 pro (safari + chrome)
- iphone 14 pro (safari + chrome + firefox)

**Comment by MatissJanis** [comment]
> @MatissJanis - Any chance of you having a look? I'm more than happy to test / provide logs

Negative. I've not been able to reproduce the issue so far, so unable to help in fixing it. It would best if someone who has already reported this issue and is able to reproduce would look into fixing it.

**Comment by need4swede** [comment]
I'm also having this issue.
Opened a support thread in Discord:
https://discord.com/channels/937901803608096828/1196032197841399808/1196032197841399808

**Comment by latetedemelon** [comment]
Apparent Fix:

Verified by myself and another user in the Discord channel, it appears you need to have the actual service using https, even if you are using a proxy.

I am utilizing NPM as proxy. My experience was it worked just fine under windows, but would not load under iOS. Changing the actual server container to use https as well (in addition to NPM)  seems to have fixed the issue.

**Comment by upbeat-eggplant** [comment]
>  it appears you need to have the actual service using https, even if you are using a proxy.

Thank you for attempting a fix. Unfortunetly the issue still persists for me after setting actual to use https.
I am running actual in a docker container. It is served by another docker container running nginx as a reverse-proxy that already uses https. Additionally setting up https in the actual container seems to have made no difference to me. It also doesn't matter work if I bypass my reverese-proxy and access acutal directly. The issue only arises on my iPhone with iOS 15.8.

**Comment by latetedemelon** [comment]
My experience was that I was unable to access Actual from any any browser on any iOS device either directly or through a https proxy (NPM).  Windows worked for both without an issue.

I set up a new docker instance and confirmed it had the same behaviour.  Then I generated a new certificate,uploaded to the correct directory, updated the docker compose and config.json and restarted. No longer had an issue.  Then did the same with my production instance and confirmed it worked as well.

> >  it appears you need to have the actual service using https, even if you are using a proxy.
> 
> 
> 
> Thank you for attempting a fix. Unfortunetly the issue still persists for me after setting actual to use https.
> 
> I am running actual in a docker container. It is served by another docker container running nginx as a reverse-proxy that already uses https. Additionally setting up https in the actual container seems to have made no difference to me. It also doesn't matter work if I bypass my reverese-proxy and access acutal directly. The issue only arises on my iPhone with iOS 15.8. I am running actual v24.1.0.
> 
> 
> 
> I have the following error, similiar to the ones others have reported above
> 
> <img width="998" alt="image" src="https://github.com/actualbudget/actual/assets/130395888/b9385c59-9b60-47d4-bd5f-7a272306eba9">
> 
> SyntaxError: Duplicate parameter 'e' not allowed in function with destructuring parameters
> 
>

**Comment by latetedemelon** [comment]
@valterbarreira, @need4swede - Can you please comment if adding a certificate for actual proper (not a proxy) fixed this for you?

@MatissJanis - Assuming this is a ‘fix’ would a documentation update be the gap fill until a root cause be tracked down?

**Comment by valterbarreira** [comment]
> @valterbarreira, @need4swede - Can you please comment if adding a certificate for actual proper (not a proxy) fixed this for you?
> 
I'm using actual on yunohost server that implements it's nginx proxy and ssl certificates to apps. I dont know how to add a certificate only to the actual app, or if its possible

**Comment by valterbarreira** [comment]
I have upgraded to 24.2.0 and now it shows the blue page and a loading icon

**Comment by newswangerd** [comment]
I just had the same issue in iOS 16.2 with version 24.2.0. The website just shows an endless spinner.

**Comment by latetedemelon** [comment]
> My experience was that I was unable to access Actual from any any browser on any iOS device either directly or through a https proxy (NPM). Windows worked for both without an issue.
> 
> I set up a new docker instance and confirmed it had the same behaviour. Then I generated a new certificate,uploaded to the correct directory, updated the docker compose and config.json and restarted. No longer had an issue. Then did the same with my production instance and confirmed it worked as well.

I *thought* I had my issue solved but apparently not.  Latest theory is that it might be a Simplesync vs. Fullsync issue.

https://actualbudget.org/docs/migration/simple-sync

Backing up and reimporting my budget resolved my issue on the latest version of edge when it started happening again.

**Comment by chinalichen** [comment]
Same for me, Safari throw a SyntaxError in iOS 16.1.1.

![截屏2024-04-14 20 19 07](https://github.com/actualbudget/actual/assets/2139908/e3188a8a-2e47-421a-8d1e-f95c7f9bbe31)

**Comment by MatissJanis** [comment]
Thanks @chinalichen - the screenshot was very helpful.

I've pushed a few changes to this place in the code. It should now be available in https://demo.actualbudget.org - could you please try it out and see if the issue persists?

**Comment by upbeat-eggplant** [comment]
Thanks for trying to fix this issue! Something seems to have changed. Instead of the previously endless loading icon I now get an error message. (iOS 15.8.2)
![IMG_BD0A3845B0F8-1](https://github.com/actualbudget/actual/assets/130395888/92b20e13-cd1d-415c-90d5-97e5dc919d6c)

<img width="1088" alt="image" src="https://github.com/actualbudget/actual/assets/130395888/87c6eda3-a55d-4460-9f6d-038f6a9dac5b">

**Comment by MatissJanis** [comment]
Thanks! So at this point it's safe to assume that the backend we load via `importScript` is at fault here. I've downgraded the build target in [this pr](https://github.com/actualbudget/actual/pull/2615) to hopefully fix it.

Can you please check if Actual works in this demo link? https://deploy-preview-2615.demo.actualbudget.org/

**Comment by latetedemelon** [comment]
In fairness I haven't had any issues since I swtiched to https (native self
signed, not proxied through caddy / nginx etc.).  But I can confirm this
works for me on Safari 17.4.1 on an iPhone 14 Pro.

**Comment by need4swede** [comment]
> Thanks! So at this point it's safe to assume that the backend we load via `importScript` is at fault here. I've downgraded the build target in [this pr](https://github.com/actualbudget/actual/pull/2615) to hopefully fix it.
> 
> Can you please check if Actual works in this demo link? https://deploy-preview-2615.demo.actualbudget.org/

I get the 'Fatal Error' message as well [including on this test env.] Previously just got endless loading or just white screen on the latest version of Actual.
I tried the self signed cert approach. Works fine on desktop, but didn't fix my iOS issue.

**Comment by chinalichen** [comment]
I have identified the root cause of the error: when swcMinify is configured with mangle set to true and compress set to false, it produces problematic minified code. This issue is described in more detail at https://github.com/swc-project/swc/issues/9015. Currently, there is no fix proposed for this in @swc/core. As a workaround, we can avoid this problem by enabling both mangle and compress simultaneously.

A quick preview version of fixing:
![image](https://github.com/actualbudget/actual/assets/2139908/69419466-fdd4-4ea7-9532-a2ef353cb8a5)

**Comment by chinalichen** [comment]
@eknc What version of Safari are you using? Mine is 16.1.1, and it works with the test file in this demo site. https://deploy-preview-2825.demo.actualbudget.org

**Comment by upbeat-eggplant** [comment]
Hey, I just wanted to confirm that this has fixed the issue for me. Big thank you to everyone! This makes my life much better. Can't wait for the next release.
iOS 15.8.2
