### ISSUE TITLE
[Bug]: Category search no longer finds groups

### ISSUE THREAD

**Issue by andyvandesand** [actualbudget/actual#1767]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

After updating to v23.10.0 I noticed when going through transactions and assigning categories that typing the name of a category group no longer brings up the categories within that group. This was very helpful - for example, I have a cateogry "Other" in a number of different category groups, and can now only type in "other" which will bring up the list of all "other"s that I have to select from, as opposed to typing e.g. "groceries" and having the right one close by. This made the process much quicker.

I'm almost certain this worked in the previous version! 

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

**Comment by Kidglove57** [comment]
@andyvandesand 

I believe this is the result of a different request to have the category groups excluded. See #1681

I guess we all have different use cases. I am easy whether groups are included or excluded in the search to allocate a category to a transaction.

**Comment by andyvandesand** [comment]
Hmm, sorry not sure why this didn't come up in my search, I figured it must have been something like this.
How about making it a setting then?

**Comment by Kidglove57** [comment]
In any event, personally I feel overall it is best to **include** category groups in the search . It helps for orientation and to reassure that the right budget category has been selected for that transaction. 

So personally my vote would be to revert the change or, as you say, make it optional although I have no idea how hard this would be to code.

**Comment by mgrixti** [comment]
I would second reverting the change.  I personally find it easier to remember 10-15ish groups rather than 50+ categories. It seems to me that having strategically named groups to limit search results overlap is more reasonable than limiting all the other users from searching by the parent category.

**Comment by youngcw** [comment]
Closing this in favor of feature request #2324
