### ISSUE TITLE
[Bug]: Issue importing CSV with semicolon deliminter

### ISSUE THREAD

**Issue by RandomByte** [actualbudget/actual#1769]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I'm not sure with which release this started to fail, but the CSV files my (German) bank generates can't be imported to Actual **v23.10.0**. These CSV files generally use semicolons as delimiters and comma as decimal separators.

I created two test files for your convenience, one using comma as delimiter (and period as decimal separator) and one using semicolons. The first can be imported as expected, the second seems to fail some kind of parsing as you can see in the screenshot below.

Files: [Comma.csv](https://github.com/actualbudget/actual/files/12838888/Comma.csv) | [Semicolon.csv](https://github.com/actualbudget/actual/files/12838889/Semicolon.csv)

<img width="791" alt="Actual import CSV with semicolon delimiters" src="https://github.com/actualbudget/actual/assets/1589939/1ad726d7-d2eb-44c5-8dec-8410eb452c0d">

### What error did you receive?

See screenshot above. Import is not possible. After rewriting the CSV to use comma as delimiter (and period as decimal separator), the import was successful.

While I am facing this issue on my personal instance, I was able to reproduce the behavior on the current test server at: https://actualbudget.netlify.app

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Safari

### Operating System

Mac OSX

**Comment by thagorastos** [comment]
I have the exact same issue. No matter whether I use Safari or Firefox. I also self host the server, which apparently makes not difference.
