### ISSUE TITLE
[Bug]: Goals: Templates applying full amount when full amount is already budgeted

### ISSUE THREAD

**Issue by JazzaG** [actualbudget/actual#1771]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Applying budget templates will apply the full amount of the template if the category has greater than or equal to the full amount of the template.

For example, a schedule for an annual charge is $1400. The budget category for this charge has $1500 in the balance. Applying the template for this category adds $1400 to the budget, bringing the balance to $2900. The expected behaviour is that applying the template applies $0 to the budget category as the category already has the required amount.

Server & Client version v23.10.0

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by youngcw** [comment]
Is it specifically the schedule template that is doing this or are other templates also not working as expected?

**Comment by JazzaG** [comment]
Seems like it's just schedules.

I just tried with `#template $50 by 2024-01`:
October, applied template, budgeted $12.50, balance $12.50
November, manually budgeted $60, balance $72.50
December, applied template, budgeted $0, balance $72.50

**Comment by happybikes** [comment]
I'm also having the same issue with the "up to" template. I.e. #template up to 50 budgets $50 this month and $50 next month for a total of $100. It should be capping it at $50, correct?

**Comment by youngcw** [comment]
@happybikes Im not able to replicate your issue at all.  Do you have an example budget or steps to make this happen?

**Comment by happybikes** [comment]
> @happybikes Im not able to replicate your issue at all. Do you have an example budget or steps to make this happen?

![Eating Out](https://github.com/actualbudget/actual/assets/52984564/7af8553e-5ad1-40e1-8f17-a2200f68f02b)

Something like this. It should be capping it at $160 for the subsequent month, no? Even after clicking apply budget template, it doesn't.

**Comment by youngcw** [comment]
You are correct that when applying the template to the second month that it should cap the balance at 160 at the time of application. Are you applying the template to both months or just the one?  Ive tried to recreate this a few different ways and have been unsuccessful.  Are you still seeing the issue if you use demo.actualbudget.org?

**Comment by happybikes** [comment]
I tried it on the demo like you suggested, and the demo works correctly. After messing with it some more, I believe there may be an issue with the “apply budget template” at the top of the month. It doesn’t actually apply the template correctly, whereas the individual “apply budget template” buttons of each item work when I go through and click them one by one.

**Comment by Kidglove57** [comment]
I have been using an “up to” template successfully on my real life budget for a couple of months, including applying all templates at the same time. Perhaps my scenario is slightly different in that my template is along the lines of: “#template 10 up to 50”. In this instance if I have 45 available only 5 is added. Or if I have 50 available 0 is added. This always works for me as it should.

**Comment by happybikes** [comment]
Thanks for doing some troubleshooting and narrowing down the issue to something on my end. I’ve got it installed in a docker container, so I may try to spin up another one and see if I can resolve it that way. If not, it’s not the end of the world to have to apply the template manually to each individual item.

**Comment by youngcw** [comment]
@JazzaG are you still seeing this issue in the current build?  I think I'll close this off for now unless I hear back soon.
