### ISSUE TITLE
[Bug]: Update from 23.10 stopped working

### ISSUE THREAD

**Issue by andreapx** [actualbudget/actual#1773]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I've pulled the last docker container and when I start it in theweb UI I see "Files" and I can select "My Finances" (underneath it I see "Synching), but when I click on it a popup appers saying _We had an unknown problem opening “My-Finances-0de3a9f”_.
In the log I just see `actualbudget     | Listening on :::5006...`, nothing else.

### What error did you receive?

We had an unknown problem opening “My-Finances-0de3a9f”.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

**Comment by salvachiese** [comment]
Hi, Same issue also working docker, try to open GUI in MacOS Sonoma with Safari, and same error "unknown problem opening ....."
Same equipment with Brave works good.
The issue with Safari begins after the upgrade to 23.10

**Comment by Kadenar** [comment]
Same issue being seen here after upgrading to latest docker image in Unraid.. 

Error updating Error: no such table: __migrations__

Error occurs inside of function - loadBudget(id) as part of the await updateVersion() try catch block.

**Comment by MixTecnico** [comment]
from here the same with centos

nodejs 16 and above same problem

first installation!

**Comment by MixTecnico** [comment]
> from here the same with centos
> 
> nodejs 16 and above same problem
> 
> first installation!

mod security in my case

**Comment by MatissJanis** [comment]
Thanks for the report.

Is anyone able to provide reproduction instructions?

**Comment by Kadenar** [comment]
@MatissJanis This issue is resolved by the end user just clearing their cookies / site data.

**Comment by andreapx** [comment]
> Clear your cookies for the site and it fixes the issue. Found the solution on their Discord as other users were running into it. Worked for me as well.

Thanks a lot!!!

**Comment by Neosaurus** [comment]
I'm having this issue on the new version of the MacOS app after updating. Web GUI still works fine. All are on the latest versions of Actual. Not sure how to clear cookies from the MacOS app
