### ISSUE TITLE
[Bug]: Missing category (Credit Card Payments) from YNAB json import

### ISSUE THREAD

**Issue by nicpenning** [actualbudget/actual#1778]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I imported my budget from YNAB and it appears that I am missing the Credit Card Payments (liabilities?) that are budgeted in Actual.

YNAB Screenshot
![image](https://github.com/actualbudget/actual/assets/5582679/9bd10ed8-f8d5-40a0-a52b-a17294d57ff9)

![image](https://github.com/actualbudget/actual/assets/5582679/bd8de508-2189-4395-b5c7-2734b10104ef)

Not shown after import:
![image](https://github.com/actualbudget/actual/assets/5582679/fa0a6559-25e2-45fc-9f78-e3520b8b35e4)

Here is the JSON of the Credit Card Payments object:
```
        {
          "id": "6b968ed6-9b66-489a-9c5a-9698b7103d6e",
          "name": "Credit Card Payments",
          "hidden": false,
          "deleted": false
        },
```

And here is the JSON for the budgeted $219.01 credit card:

```
        {
          "id": "68f35af2-1389-4a79-866e-fdc91ea885c7",
          "category_group_id": "6b968ed6-9b66-489a-9c5a-9698b7103d6e",
          "name": "My Credit Card",
          "hidden": false,
          "original_category_group_id": null,
          "note": null,
          "budgeted": 219010,
          "activity": 407290,
          "balance": 626300,
          "goal_type": null,
          "goal_day": null,
          "goal_cadence": null,
          "goal_cadence_frequency": null,
          "goal_creation_month": null,
          "goal_target": 0,
          "goal_target_month": null,
          "goal_percentage_complete": null,
          "goal_months_to_budget": null,
          "goal_under_funded": null,
          "goal_overall_funded": null,
          "goal_overall_left": null,
          "deleted": false
        }
```

Not a critical issue, but it is the only data that appears that didn't make it over.

I am unsure if this was a built in group/category or if it was something that was created later. Either way, there must be something special about this group.

Thoughts?

### What error did you receive?

No errors were received.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

**Comment by youngcw** [comment]
I believe those categories are skipped because of all the extra trickery YNAB does to dynamically set the balance on those.  Actual doesn't have any way currently to automatically transfer balances between categories so they would very likely be broken when importing.

**Comment by nicpenning** [comment]
Okay. Well it was worth a shot mentioning :) this can be closed if it's not going to be resolved.

**Comment by nicpenning** [comment]
Not likely to be fixed

**Comment by youngcw** [comment]
Feel free to put in a feature request if there isn't one for this already.
