### ISSUE TITLE
[Bug]: mobile - visual - gray box above input box

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#1782]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

<img width="496" alt="Screenshot 2023-10-10 at 22 20 15" src="https://github.com/actualbudget/actual/assets/886567/4c669e48-b97c-43a1-a2bd-1d3ae99ea19e">

There's a weird gray box above the input field for some reason. I think this is new in v23.10.0

### Where are you hosting Actual?

None

### Operating System

None

**Comment by miqh** [comment]
@MatissJanis, I briefly attempted reproducing this and I suspect what you're seeing there might be the result of an overflow scrollbar.

Oddly, I was only able to see it on Firefox under responsive conditions and not Chromium.

![repro](https://github.com/actualbudget/actual/assets/43751307/deefe308-ee15-4864-9831-ee3b395af62c)

I traced it to the following line below and found that if `overflowX: 'hidden'` is added then the scrollbars stop appearing on interaction for me.

https://github.com/actualbudget/actual/blob/4cacc845c0e7323b5e4c8e6df3a5aba0ed4f06b3/packages/desktop-client/src/components/mobile/MobileAmountInput.js#L172

There's some suspect animation code that's commented out, but I don't know enough to work out why the flicker happens for me.

Anyway, I'd be happy to dig further or provide that above suggested change based on what you think.

**Comment by joel-jeremy** [comment]
@miqh Thank you for taking the time to investigate. Please feel free to create a PR with the fix. :)
