### ISSUE TITLE
[Bug]: Mobile: icons overlapping 

### ISSUE THREAD

**Issue by shall0pass** [actualbudget/actual#1786]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

The sync and menu button are overlapping. This is only found in the current Master branch.

CC @joel-jeremy 

![Screenshot_20231011-172153](https://github.com/actualbudget/actual/assets/20625555/67cc9f5d-7e84-4ddc-9af3-580ff6bca9bb)

### Where are you hosting Actual?

NAS

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Mobile Device

**Comment by joel-jeremy** [comment]
Thanks for reporting! This should be fixed by https://github.com/actualbudget/actual/pull/1783 which will be included in the next edge deploy.

**Comment by shall0pass** [comment]
Ah.  Wow, I can't believe how fast you had that fixed. Amazing!
