### ISSUE TITLE
[Bug]: wonky alignment mobile report budget

### ISSUE THREAD

**Issue by youngcw** [actualbudget/actual#1790]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

All this is on the mobile view of the report budget.
On the edge build (maybe latest too), the mobile view of the income categories are not aligned.
![image](https://github.com/actualbudget/actual/assets/28542559/eee4a621-b14f-4cd4-bcee-335c999eed47)

The header also has problems with the projected savings heading.
![image](https://github.com/actualbudget/actual/assets/28542559/5b54c0c7-0b5f-45c0-920e-62e14c311273)

### Where are you hosting Actual?

None

### Operating System

None

**Comment by iceTmZz** [comment]
I will like to be assigned on this one

**Comment by joel-jeremy** [comment]
@iceTmZz We don't assign issues but pease feel free to open a PR with the fix :)
