### ISSUE TITLE
[Bug]: Category Spending Graph runtime Error

### ISSUE THREAD

**Issue by carkom** [actualbudget/actual#1792]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Select "All Time" from the Average drop down menu. Then uncheck any category group (has to be a group not an individual category). As soon as you uncheck the group the app crashes with:

_budgetPerMonth[loot_core_src_shared_months__WEBPACK_IMPORTED_MODULE_4__.subMonths(...)] is undefined_

### What error did you receive?

Uncaught Runtime Errors.

The app crashes

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Windows 10

**Comment by MatissJanis** [comment]
Category spending graph has been removed. So this bug is no longer applicable.
