### ISSUE TITLE
[Bug]: Dark Theme: Split transaction color in category autocomplete is unreadable

### ISSUE THREAD

**Issue by joel-jeremy** [actualbudget/actual#1805]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

This is only currently present in the edge build.

Split transaction option in the category autocomplete is unreadable:
![image](https://github.com/actualbudget/actual/assets/20313680/33906aea-d1c7-455b-b726-d2433574f9bc)

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome, Other

### Operating System

Mobile Device

**Comment by carkom** [comment]
fixed by #1798
