### ISSUE TITLE
[Bug]: Dark Theme: Top bar PR link is unreadable

### ISSUE THREAD

**Issue by joel-jeremy** [actualbudget/actual#1806]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Development top bar PR link is unreadable:
![image](https://github.com/actualbudget/actual/assets/20313680/cf84d7f0-2821-46be-9315-44e278a91403)

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome, Other

### Operating System

Mobile Device

**Comment by carkom** [comment]
Development Theme isn't really meant to be readable or usable. It is meant to help with bug bashing and contrast testing.

**Comment by joel-jeremy** [comment]
I wasn't pertaining to the development theme. I was pertaining to the development/demo build bar that is displayed at the top of the page with a link to the PR. :)

**Comment by carkom** [comment]
fixed by #1798
