### ISSUE TITLE
[Bug]: Dark Theme - global notifications are not included in themes

### ISSUE THREAD

**Issue by carkom** [actualbudget/actual#1807]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

global notifications are not changed by themes. Anything other than light themes are set to "transparent"
![image](https://github.com/actualbudget/actual/assets/55785687/cd2c49ab-342e-489d-8899-058e7cc74b17)

![image](https://github.com/actualbudget/actual/assets/55785687/0db003f3-77aa-4809-9b8d-ca0c2177f5c4)

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Windows 10

**Comment by carkom** [comment]
fixed by #1798

**Comment by joel-jeremy** [comment]
Closing this as PR with the fix has been merged.
