### ISSUE TITLE
[Bug]: CSV Import can corrupt the database by saving invalid entries

### ISSUE THREAD

**Issue by Shazib** [actualbudget/actual#1811]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Originally impacted a user on fly.io, discord support thread [here](https://discord.com/channels/937901803608096828/1162801618115375196)

Importing a CSV with an invalid (huge?) number, corrupts the database, and makes actual fail to load subsequently. 

Reproduce by importing the following as a CSV:

```
Post Date,Description,Category,Reference Number,Amount
7/22/2023,BACKERKIT.COM GLOOMHAV   PACIFIC GROVECA,Miscellaneous General Merchandise Stores,8271116503061807,-15.00
```
Result:
"Fatal Erro" app fails to load permanantly.

Notes:

The parsing logic strips out evertything that isn't a digit with regex and has its own implementation of safeNumber?

https://github.com/actualbudget/actual/blob/master/packages/loot-core/src/shared/util.ts#L327-L353

The CSV Parser should possibly also validate that each row has the same number of columns, as the CSV had comma's in the content body.

### What error did you receive?

![image](https://github.com/actualbudget/actual/assets/4405777/8b5e0497-305e-46e7-8b6d-907a737eb0c0)

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 11

**Comment by MatissJanis** [comment]
👋 I am no longer able to reproduce this. Can you please double check?

Thanks!

**Comment by Shazib** [comment]
Sorry i think my examples wrong or it changed

```
Post Date,Description,Category,Reference Number,Amount
7/22/2023,BACKERKIT.COM GLOOMHAV   PACIFIC GROVECA,Miscellaneous General Merchandise Stores,8271116503061807,-15.00
```

Try that, deffo fails in the same way
