### ISSUE TITLE
[Bug]: Gocardless import adds declined transactions

### ISSUE THREAD

**Issue by benjylxwang** [actualbudget/actual#1812]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

If there are declined bank transactions within the bank import window through GoCardless (I'm using Starling UK), they get added to the list of transactions against the linked account. This happens every time you run the import/sync, so every time I sync the account I need to delete the declined transactions or my budget account balance is out of sync with the bank account balance

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Windows 11

**Comment by benjylxwang** [comment]
Had a quick look through the code and maybe we could just add a filter on the transactions that come back from the `downloadGoCardlessTransactions` so that it doesn't return any of the declined ones?

That's [here](https://github.com/actualbudget/actual/blob/acf44560778fc0202baad538ef7210f81121e476/packages/loot-core/src/server/accounts/sync.ts#L211) in the codebase.

Only thing I'm not sure about is if that information is in the transaction object at this stage - haven't had a chance to test. The other place I could see it working would be in `reconcileGoCardlessTransactions` in the same `sync.ts` file.

**Comment by kyrias** [comment]
> Had a quick look through the code and maybe we could just add a filter on the transactions that come back from the `downloadGoCardlessTransactions` so that it doesn't return any of the declined ones?

If done then this should be done in a bank integration in the sync server. https://github.com/actualbudget/actual-server/tree/master/src/app-gocardless/banks

But if the transaction was declined then it should not be served at all and so if anything you should report this as an issue to GoCardless.

**Comment by benjylxwang** [comment]
> > Had a quick look through the code and maybe we could just add a filter on the transactions that come back from the `downloadGoCardlessTransactions` so that it doesn't return any of the declined ones?
> 
> If done then this should be done in a bank integration in the sync server. https://github.com/actualbudget/actual-server/tree/master/src/app-gocardless/banks
> 
> But if the transaction was declined then it should not be served at all and so if anything you should report this as an issue to GoCardless.

Ah ok thanks for the clarification on that. I'll report it to GoCardless.

**Comment by ACWalker** [comment]
I've just come across this issue myself with Starling too. I have raised a support issue to GoCardless so will see what they say. Otherwise I will make a bank integration for starling as @kyrias mentioned.

**Comment by ACWalker** [comment]
I got a response from gocardless, they said:

```
I have found the transactions in the our response.  We will look into it to see what might bet the cause why these are returning as "Pending".  I will get back to you as soon as we have any news on the matter.
```

Will see what they find
