### ISSUE TITLE
[Bug]: When switching to Report Budget, all budgeted values disappear 

### ISSUE THREAD

**Issue by stan-w** [actualbudget/actual#1816]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When switching to Report Budget, all values entered in the budgeted column disappear.

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Other

### Operating System

Windows 11

**Comment by youngcw** [comment]
This is expected.  The two budget types have separate database tables to save the data.  There is currently a feature request open to allow for migration between the two if you want to add your vote for it. https://github.com/actualbudget/actual/issues/732
