### ISSUE TITLE
[Feature] Ability to upload invoices/receipts

### ISSUE THREAD

**Issue by BinariiStudio** [actualbudget/actual#1818]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I would like to see a option to upload a invoice/receipt to a transaction. 
This will allow us to have everything in one place.

**Comment by youngcw** [comment]
Duplicate of #530
