### ISSUE TITLE
[Bug]: mobile - Category is unselectable for transfers between off-budget and on-budget accounts

### ISSUE THREAD

**Issue by phij** [actualbudget/actual#1822]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Transfers between off-budget accounts and on-budget accounts disable the Category drop-down on mobile, this occurs whether the off-budget account is the Payee or the Account.

For transfers from an off-budget account to an on-budget account (and vice versa), the category needs to be entered for the on-budget account. As such transfers from/to off-budget accounts can’t be properly entered on mobile.

<img width="391" alt="image" src="https://github.com/actualbudget/actual/assets/4382642/227ae111-2589-4040-8e5a-3dc867e8c480">

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Safari, Microsoft Edge

### Operating System

Mobile Device

**Comment by youngcw** [comment]
I am seeing this too.  My guess is that the logic to block the category is simply looking for a transfer, but not taking into account where the transfer is going.

**Comment by joel-jeremy** [comment]
I am seeing this as well and it also happens in the desktop client - you cannot select a category.
![image](https://github.com/actualbudget/actual/assets/20313680/ee207907-01fb-4913-a0d0-22b582af75d9)
 
 The difference is in desktop client you can go to `Bank of America` and assign a category from that end. On mobile, the category selection is disabled.
