### ISSUE TITLE
[Bug]: API doesn't support rules using "notOneOf"

### ISSUE THREAD

**Issue by cpainchaud** [actualbudget/actual#1825]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I am using selfhosted fresh v23.10.0 servers and client.
I am using API to import my banks transactions into. API version 6.2.1
I have setup up one rule which states to change category if payee isNotOneOf X or Y

Transactions are imported BUT said rule is not applied to them as an error message is repeated once per transaction:
`Found invalid operation while ranking: notOneOf
`

### What error did you receive?

Found invalid operation while ranking: notOneOf

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 10

**Comment by Marethyu1** [comment]
Looks like this could be related to #1985  (they might be able to be fixed at the same time if someone looks into it)

**Comment by carkom** [comment]
Can you check that the linked PR fixes your issue?
