### ISSUE TITLE
[Bug]: Problems syncing changes

### ISSUE THREAD

**Issue by ExZiByte** [actualbudget/actual#1826]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Fresh install of Actual trying to import my transactions in OFX format also tried in the CSV format. 

Firefox console has 
```
Error: PostError: <html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

### What error did you receive?

I get a popup stating "We had problems syncing your changes"

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 10

**Comment by hossain-khan** [comment]
For future reference, I have also experienced same issue. 


### Request
```
curl 'https://actual-server/sync/upload-user-file' \
  -H 'DNT: 1' \
  -H 'X-ACTUAL-TOKEN: XYZ' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36' \
  -H 'Content-Type: application/encrypted-file' \
  -H 'Referer: https://actual-server/static/js/browser-server.Kf_xQo8f.js' \
  -H 'X-ACTUAL-NAME: Expense' \
  -H 'X-ACTUAL-FORMAT: 2' \
  -H 'X-ACTUAL-FILE-ID: fda-xyz-1699' \
  --data-raw 4.1MB-encrypted-file
```

### Response
```
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
```

* Server version: v24.8.0
* Installation: Docker

I am guessing having non-synced local version is fine.

**Comment by hossain-khan** [comment]
Quick update - I reported the same issue at Discord `#support`

--- 

I created new server at pikapod - `App: v24.8.0 | Server: v24.8.0`
And imported same 2 budget files, and syncing is working fine for both of them.

Must be something wrong with my installation.

I will go through the doc again at https://actualbudget.org/docs/install/docker and post updates on my findings. Thanks

**Comment by hossain-khan** [comment]
### ℹ️  Update

The issue was specific to my setup of using reverse proxy using Nginx. 

By default, the default value for `client_max_body_size` in Nginx is `1 MB`.

After I set that to `client_max_body_size 50M;` I was able to upload and make the budget file as cloud file. :sweat_smile: ✅

**Comment by pavekovt** [comment]
For someone how's running actual in Kubernetes and using nginx ingress controller you can add annotation to your individual ingress resources to increase `client_max_body_size`:
* Official NGINX Ingress:  `nginx.ingress.kubernetes.io/proxy-body-size: "50m"`
* Official Kubernetes Ingress: `nginx.org/client-max-body-size: "50m"`
    
Annotation depends of which nginx controller you are running:

> If you are using the official NGINX Ingress, the correct annotation is here: https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/advanced-configuration-with-annotations/
> 
> If you are using the official Kubernetes Ingress based on NGINX, the correct annotation is this: https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#custom-max-body-size

Source: https://stackoverflow.com/a/73548785
