### ISSUE TITLE
[Bug]: "back" button on mobile webapp does not work

### ISSUE THREAD

**Issue by Robin-Sch** [actualbudget/actual#1828]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I opened an account and looked at the transactions. After that I wanted to go "back", however, the back button (top left) does nothing.

When I manually make the window "smaller" on my PC, it does work. But on my android phone (browser: bromite) it does not. Also, using the android back button doesn't do anything (well, closes the web app, but doesn't change the page), so now I'm stuck at that account page.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Bromite

### Operating System

Mobile Device (Android webapp)

**Comment by youngcw** [comment]
If you try demo.actualbudget.org are you still seeing the issue?

**Comment by Robin-Sch** [comment]
I get "fatal error". There was a problem loading the app in this browser version. ... Show error: does nothing but only creates more (empty) padding below the button.

**Comment by Robin-Sch** [comment]
I just opened demo.actualbudget.org

**Comment by youngcw** [comment]
weird.  its probably connected to you using a non standard browser.

**Comment by Robin-Sch** [comment]
Yes you're correct, I managed to fix that error (javascript JIT was disabled). Back button works correctly!
