### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by AngeloFrangione** [actualbudget/actual#1830]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Overview the expense in each category of a single month.

### Describe your ideal solution to this problem

Add a report, that is like the category spending one but focus on a single month. Actually if we select one month we cannot clearly see what category is which color. Making for example a bar chart with each bar a category instead of a month would help solve this issue. 

We could also imagine making multiple month by putting them side by side to be able to see which month has the most spending in a category. 
I could make a example chart if I'm not clear enough.

### Teaching and learning

This could be implemented in the existing category spending report, or in a new one more focused on the categories instead of the time.

**Comment by youngcw** [comment]
Have a look at this PR and see if this fits what you are looking for
https://github.com/actualbudget/actual/pull/1791
