### ISSUE TITLE
[Feature] Ability to show imported payee easily

### ISSUE THREAD

**Issue by willoma** [actualbudget/actual#1832]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

When importing data from my bank, the imported payee fields contains some details (date of payment, maybe some details, which credit card has been used, etc). My rules remove this information in order to keep only the payee, but sometimes I need these details to remember what the payment was.

Currently, I select the transaction, and click on "Create rule", in order to see the rule creation popup, where I can see the imported payee.

### Describe your ideal solution to this problem

A tooltip which appears when hovering the payee would be great.

### Teaching and learning

Simply say in the doc that hovering over a payee shows the imported payee, when there is some...

**Comment by youngcw** [comment]
Closing ad duplicate of #782
