### ISSUE TITLE
[Bug]: NYNAB import - importing transaction with a transfer as a split payment causes transfer to get treated as uncategorised payment

### ISSUE THREAD

**Issue by Marethyu1** [actualbudget/actual#1835]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Consider the following transaction: 
<img width="1269" alt="image" src="https://github.com/actualbudget/actual/assets/17978203/c56c1cb3-446a-4d61-8d72-920be07a9985">

It is payment to the store, but it also contains a transaction split which is a transfer of $50 to the savings account. 
If you try to import a transaction like this, the sub transaction gets treated as an uncategorised payment instead:
<img width="1271" alt="Screenshot 2023-10-29 at 12 42 25 PM" src="https://github.com/actualbudget/actual/assets/17978203/2022e65f-6622-4466-9947-74b94fb7a993">

I have attached a modified demo budget which you can use to  reproduce the behaviour. 
~~[ynab5-demo-budget.json](https://github.com/actualbudget/actual/files/13196930/ynab5-demo-budget.json)~~
[ynab5-demo-budget-working.json](https://github.com/actualbudget/actual/files/13257671/ynab5-demo-budget.json)

Expected behaviour: imported transaction contains a sub transaction which is a transfer to the savings account
Actual behaviour: imported transaction contains a sub transaction which is an uncategorised payment.

👋 also hello this is my first issue - let me know if I need to add anything else - thanks

### What error did you receive?

It doesn't result in an error it just doesn't work as expected. 

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome, Safari

### Operating System

Mac OSX

**Comment by youngcw** [comment]
@Marethyu1 Is this fully fixed now that your PR was merged?

**Comment by Marethyu1** [comment]
Hey @youngcw it works for me in master. Im not sure what the process is for closing these issues off. Not sure if it is best to wait until the issue has been included in a full release or if I should be fine to close it now.
