### ISSUE TITLE
[Feature] Sub-accounts

### ISSUE THREAD

**Issue by kabo** [actualbudget/actual#1839]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

We have a revolving credit account. This means we can withdraw up to -$X from the account, but we only pay interest on the money we have withdrawn. If the account balance is $0 or higher we pay zero interest.

So naturally we want to have as much cash as possible in this account. So we dump all my money, my partner's money, etc. into this one account.

It would be great if accounts could have sub-accounts so we can easily see what money is in there, which account or purpose it belongs to.

By purpose I mean we have some payments that are only paid 3/times year. We could create sub-accounts for those things and transfer a quarter of the upcoming payment each month into that sub-account.

This keeps the grand total for the account correct and easily verifiable, money isn't sent of to expenses that haven't happened yet, and lets us know we're on track for upcoming payments.

### Describe your ideal solution to this problem

Accounts should be able to have sub-accounts, accounts that aren't physical accounts, but partitions in a physical account.

This would allow us to save up for future payments or for bigger things, while keeping the money in the same physical account.

Could be nested as well, e.g.

```
All accounts $90
├── BankA $30
│   └── AccX $30
│       ├── Purpose1 $10
│       └── Purpose2 $20
├── BankB $60
│   └── AccY $50
│       ├── Purpose3 $20
│       └── Purpose4 $30
│   └── AccZ $10
└── BankC $0
    └── AccZZ $0

```

### Teaching and learning

I feel like some sort of tree structure should make it fairly clear.

**Comment by normanu** [comment]
same as https://github.com/actualbudget/actual/issues/1320 ?

**Comment by kabo** [comment]
In my mind sub-accounts can go negative. So not sure that needs to be a problem.
