### ISSUE TITLE
[Feature] Online sync free alternatives

### ISSUE THREAD

**Issue by normanu** [actualbudget/actual#1848]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

GoCardless costs money for syncing.
But there are also free alternatives like, Enablebanking / Saltedge or Truelayer(as far as I can see?)

### Describe your ideal solution to this problem

Would it be possible to implement one of those?
Enablebanking is quite fast.

### Teaching and learning

Everybody loves free!

**Comment by Jackenmen** [comment]
> GoCardless costs money for syncing

It does not for typical personal use - you can connect up to 50 different bank logins (where a single login could have multiple bank account, i.e. if you can see currents and savings accounts when you log into online banking) for free.

**Comment by Kidglove57** [comment]
Well worth exploring - thank you!

I cannot find anything about Saltedge being willing to deal  direct with individuals but they do say that their services to integrste with sn app start from $500 per month (see bottom of this linked page):
https://www.saltedge.com/products/account_information

My understanding is that Truelayer are similar but I certainly am no expert on this so happy to be proved wrong.

**Comment by youngcw** [comment]
Looks like Saltedge has a free tier with up to 100 connections

**Comment by Kidglove57** [comment]
I saw the bit about 100 transactions but I read it a bit differently. I took it that this is just to allow a developer to trial Saltedge for a limited period? To quote from their website:
"Start adding bank data to your app with a single API call. Test the integration with 100 live connections for free. The plan is available **during a limited period**."

**Comment by Shazib** [comment]
I know that salt edge sort of unofficially allowed free usage (up to 90 transactions?) for use with firefly-iii.

But you had to create a dev account, wait for it to be approved, and then email them that you wanted to use it with firefly.

I dont know if they've changed or streamlined that process.

**Comment by youngcw** [comment]
Im going to close this.  If there are specific sync providers that would be good to add, make a feature request for them specifically.
