### ISSUE TITLE
[Feature] Don't include hidden transactions in budget totals

### ISSUE THREAD

**Issue by mattdufeu** [actualbudget/actual#1849]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

On the budget page, could we please have a toggle to include/exclude "hidden" categories from the total?

![image](https://github.com/actualbudget/actual/assets/6482195/e4a7660a-8eab-4a11-b101-f38d80271587)

So in this image, rather than "Budgeted" be 3030.00, it would be 1525.00 and "Spent" would be 0 instead of -246.88.

**Comment by youngcw** [comment]
We cant do this for the envelope budget, but it could work on the tracking budget.  Ill close this as there is another feature request for the tracking budget that has more votes #2400
