### ISSUE TITLE
[Feature] Attachments support

### ISSUE THREAD

**Issue by WDMdanila** [actualbudget/actual#1850]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Sometimes (for example for small, 1-person businesses) it is important to keep invoices and bills for future reference. It is quite a problem when those are getting lost somewhere and it would be very helpful if there would be a way to add an attachment to a transaction in Actual Budget.

When it comes to implementation - I could implement that, would need some assistance with regards to code standards and conventions used here :)

### Describe your ideal solution to this problem

I see it as an additional column named "Attachment" for a transaction view:
![image](https://github.com/actualbudget/actual/assets/24762845/12d38f4b-6ad9-445f-a112-17886f1b7704)

Such column could be placed around "cleared" checkbox (maybe on the left side from it?)

### Teaching and learning

If this column would be visible by default it will be straightforward to use, as to some extent, it is the feature that is expected to be present in some way, shape or form

**Comment by WDMdanila** [comment]
Noticed similar feature request which is closed because more upvotes are needed: https://github.com/actualbudget/actual/issues/530

This one may be considered closed

**Comment by youngcw** [comment]
closing as duplicate of #530
