### ISSUE TITLE
[Feature] Check Number column

### ISSUE THREAD

**Issue by BoredGameGeek** [actualbudget/actual#1852]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

For checking accounts, need an extra column for "Check number". This is present in YNAB4 but as far as I can tell is not present in ActualBudget.

### Describe your ideal solution to this problem

Add an additional column for transactions, "Check Number".
- The visibility of this column is hidden by default but can be turned on, similar to "Show Running Balance"/"Hide Running Balance"

### Teaching and learning

The "Show Check Number"/"Hide Check Number" will be in the same menu as the existing "Show Running Balance"/"Hide Running Balance" so users will find it obvious as it is similar/parallel functionality.

**Comment by fref** [comment]
My banks do not provide OFX style export files, barely a CSV. Besides that, the payee can be absent or have a different name than the one I use in my budget. Therefore, I tend to do manual reconciliation. This is greatly helped by entering the transaction number (usually YY/### or YY/#### but it could be arbitrary). Ynab4 has a field for that which it calls "check number", which I use a lot.
