### ISSUE TITLE
[Bug]: Back account syncing imports incorrect data (for two different banks)

### ISSUE THREAD

**Issue by Gaibhne** [actualbudget/actual#1854]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I import (via GoCardless, as per the readme) from two German banks (Sparkasse Aachen and ING DiBa), and both imports are incorrect - for the Sparkasse account, the note field is always empty, meaning the description of the transaction is not available at all, and for ING, all the notes start with `mandatereference:,creditorid:,remittanceinformation:`, making it impossible to see the actual note unless you click each field and scroll to the far right.

Any way to customize the sync details ? Those both seem like easy fixes I could trivially do myself if I could hook in somewhere or change the base config.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 10

**Comment by youngcw** [comment]
If the data it correct from GoCardless, just not importing correct, you will need to setup a custom parser for the banks.  There are a few in the codebase already

**Comment by Gaibhne** [comment]
How would I go about that, and how would I check if the data it gets from GoCardless is correct ?

**Comment by youngcw** [comment]
If you search around the discord you can find what other people have done.  I don't use it so I don't know

**Comment by Jackenmen** [comment]
You can find a document as well as examples for how to do it here: https://github.com/actualbudget/actual-server/tree/master/src/app-gocardless

**Comment by MatissJanis** [comment]
👋 As others mentioned: the solution is to create a custom bank adapter. But best we can do is point you in the right direction. The actual implementation will need to be done by you.

**Comment by s3rglx** [comment]
> You can find a document as well as examples for how to do it here: https://github.com/actualbudget/actual-server/tree/master/src/app-gocardless

Hello,
I've tried to follow these instructions. I guess, the documentation isn't up to date. The description to add new institutionId on client side code is deprecated. As far as I understood the client is fetching the available bank adapter data provided by the bank factory from server. 

Correct me if I'm wrong.

**Comment by MatissJanis** [comment]
No changes are necessary to the client-side anymore. Only server-side :)

I've drafted a PR to update the docs: https://github.com/actualbudget/actual-server/pull/292

Thanks for the callout!
