### ISSUE TITLE
[Bug]: Electron / build (macos-latest) (pull_request) status check appears to be failing intermittently

### ISSUE THREAD

**Issue by Marethyu1** [actualbudget/actual#1861]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

The ```Electron / build (macos-latest) (pull_request) ``` status check on pull requests is failing. 

Steps to reproduce
- Open a pull request
- wait for ```Electron / build (macos-latest) (pull_request) ``` to run
- It reports the following failing (example [here](https://github.com/actualbudget/actual/actions/runs/6756556315/job/18366142959?pr=1860))

## When did it start failing?
Looking at the commit history in master it started failing in the last few days - however it is happening intermittently
![image](https://github.com/actualbudget/actual/assets/17978203/96be088d-be79-427d-989c-c70684733760)

## Extra details
1. Example passing build from 5 hours ago [here](https://github.com/actualbudget/actual/actions/runs/6755713334/job/18364430445) 
It has the following environment details 
```
Current runner version: '2.311.0'
Operating System
  macOS
  12.6.9
  21G726
Runner Image
  Image: macos-12
  Version: 20230921.1
  Included Software: https://github.com/actions/runner-images/blob/macOS-12/20230921.1/images/macos/macos-12-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20230921.1
```
1. Example failing build from 5 hours ago [here](https://github.com/actualbudget/actual/actions/runs/6755815787/job/18364622268)

```
Current runner version: '2.311.0'
Operating System
  macOS
  12.7
  21G816
Runner Image
  Image: macos-12
  Version: 20231029.1
  Included Software: https://github.com/actions/runner-images/blob/macOS-12/20231029.1/images/macos/macos-12-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macOS-12%2F20231029.1
```

I thought it may have been environmental but the fact that it two runners ran but had different results seems to go against that (unless caching is somehow involved). 

I am also able to successfully build it locally on Mac-os so, and nothing has changed regarding the package-electron script so this seems a bit strange to me.

### What error did you receive?

Build Electron logs:
```
- Searching dependency tree
Traceback (most recent call last):
  File "/Users/runner/work/actual/actual/node_modules/@electron/rebuild/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
    import gyp  # noqa: E402
    ^^^^^^^^^^
  File "/Users/runner/work/actual/actual/node_modules/@electron/rebuild/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
    import gyp.input
  File "/Users/runner/work/actual/actual/node_modules/@electron/rebuild/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
    from distutils.version import StrictVersion
ModuleNotFoundError: No module named 'distutils'
Error: `gyp` failed with exit code: 1
    at ChildProcess.onCpExit (/Users/runner/work/actual/actual/node_modules/@electron/rebuild/node_modules/node-gyp/lib/configure.js:325:16)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)

✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
node-gyp failed to rebuild '/Users/runner/work/actual/actual/node_modules/better-sqlite3'

Error: node-gyp failed to rebuild '/Users/runner/work/actual/actual/node_modules/better-sqlite3'
    at ChildProcess.<anonymous> (/Users/runner/work/actual/actual/node_modules/@electron/rebuild/lib/module-type/node-gyp/node-gyp.js:118:24)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
Error: Process completed with exit code 255.
```

### Where are you hosting Actual?

None

### What browsers are you seeing the problem on?

Safari

### Operating System

Mac OSX

**Comment by MatissJanis** [comment]
Thanks for the investigation! Here's some more details from my investigations: https://github.com/actualbudget/actual/pull/1857#issuecomment-1793161974

I suspect we'll have to wait for all downstream dependencies to upgrade `node-gyp` to v10+.

**Comment by Marethyu1** [comment]
Oh amazing! Is it worth keeping this issue around until its fixed or should I close it?

**Comment by MatissJanis** [comment]
Lets keep it around until we get a resolution. Maybe someone else does investigations too and figures out a different solution that we could apply TODAY instead of waiting :)

**Comment by youngcw** [comment]
The electron builds are flaky for me right now, where sometimes they (claim to) work, sometimes they don't
