### ISSUE TITLE
[Bug]: Wealthfront QFX import fails

### ISSUE THREAD

**Issue by mlindgren** [actualbudget/actual#1863]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Client version: 23.10.0
Server version: 23.10.0

When I export a Quicken QFX file from Wealthfront and then try to import it into Actual, I get an error "Failed importing file."  I know there were some bug fixes around this in 23.10.0, but I'm running that version and I still can't import this file. 

Offending file is attached (renamed to .txt so GitHub would let me upload it)

[WealthfrontQuickenExport.txt](https://github.com/actualbudget/actual/files/13261353/WealthfrontQuickenExport.txt)

### What error did you receive?

Failed importing file

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

**Comment by joel-jeremy** [comment]
Thank you for filing a report! At the moment the experimental OFX parser does not support investment transactions that is why it's  failing to import. I'll work on adding support for this and will give updates on this issue.

**Comment by joel-jeremy** [comment]
@mlindgren Can you try importing your ofx files using this testing link? https://deploy-preview-1876.demo.actualbudget.org/

**Comment by mlindgren** [comment]
@joel-jeremy Thanks, it seems to work on the demo link.
