### ISSUE TITLE
[Feature] Support for Android 13

### ISSUE THREAD

**Issue by FMorschel** [actualbudget/actual#1865]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I found this app as a post on Artifact, but could not install it on my phone because it's not available for Android 13.

**Comment by Kidglove57** [comment]
I’m not sure if I have understood you correctly - sorry if not. 

However, the dedicated Android app refers to the old commercial version of Actual (no longer available). The current Open Source version of Actual does not have dedicated mobile apps. Instead, the App works on your phone through your web browser. Complete functionality on mobile is not there yet but it is improving all the time. As a companion to the desktop web app it is excellent.

**Comment by FMorschel** [comment]
Oh, I see. I understood that it was still available. Thanks for the clarification!
