### ISSUE TITLE
[Bug]: Dark Mode Top Menu Blur State

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#1869]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Button to activate the blur is now black instead of white in Darkmode

![image](https://github.com/actualbudget/actual/assets/22135084/cbabaed1-61e5-4258-b515-2da979b43586)

### What error did you receive?

None

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

**Comment by carkom** [comment]
Fixed by #1798

**Comment by youngcw** [comment]
@carkom @rich-howell This is fixed now right?

**Comment by rich-howell** [comment]
> @carkom @rich-howell This is fixed now right?

Fixed in edge yep :)
