### ISSUE TITLE
[Bug]: Dark Mode Budget Sheet Notes Icon

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#1870]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Notes icon is black and not white or whatever other colour it should be. Possibly `--color-altButtonBareText`

![image](https://github.com/actualbudget/actual/assets/22135084/916c0f1c-6d8c-4c97-bf1b-6b0b6a689923)

### What error did you receive?

None

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

**Comment by carkom** [comment]
Fixed by #1798

**Comment by youngcw** [comment]
@carkom @rich-howell This is now fixed, right?

**Comment by carkom** [comment]
fixed by #1798
