### ISSUE TITLE
[Bug]: Experimental OFX Parser: XML entities aren't parsed

### ISSUE THREAD

**Issue by Bryce-MW** [actualbudget/actual#1872]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I import transactions from my banks and credit cards using OFX/QFX. Sometimes payees or memos contain XML entities, often ampersand (as `&amp;`) but I have at least one that uses angle brackets which are double encoded, showing up at `&amp;lt;` and `&amp;gt;`. The double encoding is definitely an issue with my bank since it shows up in the actual qfx file but is displayed properly on their online interface. I have seen the ampersand on multiple banks but not less or greater than signs so I don't know if the double encoding is exclusive to my bank. Unless other people have also encountered the double encoding, I think just doing one round of decoding would be a reasonable idea.

As far as I know, there is no built in way to do the decoding. There is a hacky way that creates a hidden textfield, puts the text in there, and reads it back out, or you can use a library. I'm currently working on another PR but if no one claims this by the time I'm done, I'll work on it.

Here's a zip file containing a qfx file where I have included a couple real entries with those entities that I mentioned. I just changed the amounts.
[example.zip](https://github.com/actualbudget/actual/files/13284878/example.zip)

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

**Comment by twk3** [comment]
@Bryce-MW fix prepared in https://github.com/actualbudget/actual/pull/2364

I happened to also fix the double escaping because it just ends up being a matter of the order you handle the ampersand replacement in.
