### ISSUE TITLE
[Feature] Import transactions from mint export

### ISSUE THREAD

**Issue by twk3** [actualbudget/actual#1873]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Allow importing of mint [transaction exports](https://mint.intuit.com/support/en-us/help-article/bank-transactions/download-transactions/L4VNv2fMR_US_en_US) into actual. 

Mint's export feature works on the current filtered view of transactions. The export is in csv with the following format:

| Date | Description | Original Description | Amount | Transaction Type | Category | Account Name | Labels | Notes |
| ------- | ---------------| -------------------------- | ---------- | ----------------------  | ------------- | ------------------- | --------- | -------- |
| 7/15/2023 | Debit sample debit transaction | Debit sample debit transaction | 200 | debit | Financial | Free Chequing Free Debit XXXX | | |
| 7/14/2023 | Purchase sample purchase transaction |   Purchase sample purchase transaction |  27 | debit | Gas & Fuel | Free Chequing Free Debit XXXX | | |
| 7/12/2023 | Direct deposit sample transaction | direct deposit sample transaction | 12290.02 | credit | Paycheck | Free Chequing Free Debit XXXX | | |
| 7/01/2023 | Interest Paid | Interest Paid | 1.69 | credit | Interest Income | Sample Savings XXXX | | |

The biggest issue  that prevents users from importing any of these transactions today  without editing the csv is the fact that the transaction type is a separate field.

Additionally the category information is all lost.

### Describe your ideal solution to this problem

A mint importer to go alongside the ynab importers.

- Create the accounts from the account name information.
- Create categories for each the the category names found in the csv
- [consider] Auto setting budget to monthly actuals for categories?

What we don't have is the budgets. Or the category groups.

**Comment by youngcw** [comment]
We can start with that file description, but if you have a real file export that would be best.  Its ok if its a reduced size and sanitized, its just needs to be representative of a full file.

**Comment by twk3** [comment]
@youngcw I've updated the description with a sanitised file.

I called the file 2account, but it looks like it actually has three. A chequing, a savings, and a cash (cash is a bad name, but just another account).

Mint has a split transaction features, but the transactions in the export are all post-split. So users will have to be wary of duplicates when they start importing their new transactions.

Split transactions share the same original description, and date. So maybe there is something that can be done there.

**Comment by twk3** [comment]
Based on the likely number of edge cases, and the fact that this will be short lived. (mint ending support in January). I wonder if it's better to just get an easy transaction converter up in gh-pages for folks like https://github.com/aniav/ynab-csv rather than change anything in acutal.

**Comment by youngcw** [comment]
I don't think there is likely to be a full importer because of that.  I like the idea of a csv cleaner to make the import easier.

To be honest my recommendation would be to start fresh in Actual and then either use a separate budget file, or some other storage like excel, for the old stuff.  Since Mint doesn't export any budget data (and its a different budget style iirc), any data import from Mint will result in a borked budget that will be non-trivial to fix.

**Comment by youngcw** [comment]
Here is a quick and dirty importer to try https://github.com/youngcw/actual_mint_importer

**Comment by youngcw** [comment]
Ive tested that larger file and things look to have worked.  Some notes are that the upload failed, probably because of the size.  There are some environment variables that should help with that. But if not, I had success by running the script again and ending early so the end sync didn't happen again and cause duplication.

**Comment by twk3** [comment]
Just to followup https://github.com/youngcw/actual_mint_importer seems to work well enough. I've used it on some other family members mint exports and it's seems to be working pretty good considering it doesn't have any of the budget data. 

For most users, a fresh start is going to be a nicer experience. But being that mint is shutting down. It's nice to have your categorised transactions from mint still available if wanted in actualbudget.

**Comment by psybers** [comment]
Is this request still relevant?  It looks like if I try to directly import a mint-exported CSV file, I can set an option to pick the 'credit/debit' column and it will properly mark the amount as an inflow/outflow as appropriate.  You have to tell it to use the string 'debit' as the outflow.  See this example:

<img width="776" alt="image" src="https://github.com/actualbudget/actual/assets/1115390/fb0c7aaa-217c-4ea9-9ad0-2746f6fdecb1">

The only thing I can see that is a sticking point is the fact there are multiple accounts in a single CSV.  The importer itself does not seem to handle that so you have to split them into separate files.  That can be done with a simple script:

```sh
#!/usr/bin/env bash

awk -F'"' -v OFS='\t' '{print $14, NR, $0}' "${@:--}" |
sort -k1,1n -k2,2n |
cut -f3- |
awk -F'"' '
    { curr = $14 }
    curr != prev {
        close(out)
        out = "file_" (++cnt) ".csv"
        prev = curr
    }
    { print > out }
'
```

This would generate a single `file_#.csv` for each account.  Then you can import them one by one into the proper Actual account.

I played a bit with youngcw's importer.  It works but doesn't quite do what I had hoped.  This approach of splitting the files and then importing them actually seems to work quite well for me.

**Comment by youngcw** [comment]
@psybers I think the only thing missing form the internal csv importer is that it doesn't create categories, where the api importer does

**Comment by youngcw** [comment]
Since Mint is long dead now do we still need this request open?

**Comment by twk3** [comment]
Nope. Not needed anymore at this point.
