### ISSUE TITLE
[Bug]: Scheduled transactions show up in Off Budget Accounts

### ISSUE THREAD

**Issue by ngocphamm** [actualbudget/actual#1877]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

As in the below screenshot, out of the 4 upcoming transactions that I have scheduled, only 1 is coming from my checking account to one of the Off Budget account. Others are credit card transactions. I'm not sure those are in this list.

![CleanShot 2023-11-08 at 11 30 22](https://github.com/actualbudget/actual/assets/395123/2f9b9aa6-173d-4f42-ae94-f088ddc761e3)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Mac OSX

**Comment by joel-jeremy** [comment]
What version are you using? A fix for this should already be in the edge version. See PR: https://github.com/actualbudget/actual/pull/1867.

**Comment by ngocphamm** [comment]
@joel-jeremy I'm using the latest release. I searched for existing issues and I guess I just looked for open ones. Sorry for the duplicate issue created!
