### ISSUE TITLE
[Bug]: Missing last divider bar single category budget drop down

### ISSUE THREAD

**Issue by youngcw** [actualbudget/actual#1878]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When hovering over the last expense category budget field of the table, with no other categories or groups below it, the divider bar is missing below the down chevron. 
![Screenshot from 2023-11-08 12-17-51](https://github.com/actualbudget/actual/assets/28542559/da985988-ca5f-4501-87c8-b2ebebf874a4)

### Where are you hosting Actual?

None

### Operating System

None

**Comment by ShatilKhan** [comment]
I'd like to take this issue
Please assign @joel-jeremy

**Comment by youngcw** [comment]
we don't assign issues.  Just start and put in a PR

**Comment by ShatilKhan** [comment]
Ok then I'm working on it
