### ISSUE TITLE
[BUG] Sync error with scheduled transaction

### ISSUE THREAD

**Issue by shall0pass** [actualbudget/actual#188]
A Sync error can be created when following the steps below.  Changing the system date of the PC is meant to simulate a longer length of time.  This was done on  a PC where the server and web browsers were local, so the system time affects all components equally.

1. Create a new budget.
2. Add an account and one scheduled transaction that does not auto insert.
3. Sync two browsers to the budget. (I used Brave and Firefox)
4. Close one of the browsers (I closed Firefox)
5. Manually advance the computers date to the next scheduled transaction.
6. Refresh "primary browser" and post the transaction.
7. Manually advance the computers date to the next scheduled transaction date.  
8. Refresh "primary browser and post the transaction.
9. Open second browser again.
10. Sync error

I had 3 total transactions in this test.  One for the initial account creation and two for scheduled transaction postings.

This issue was initially discussed on Discord in the #server-setup channel.

**Comment by TomAFrench** [comment]
Potentially closed by https://github.com/actualbudget/actual-server/pull/75

**Comment by rich-howell** [comment]
Marking as fixed as we are no longer able to replicate.
