### ISSUE TITLE
[Bug]: Dark Mode - Mobile Budget Page Headers

### ISSUE THREAD

**Issue by joel-jeremy** [actualbudget/actual#1881]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Dark mode colors in mobile budget page headers:
![image](https://github.com/actualbudget/actual/assets/20313680/ae5b4797-1797-43c1-9561-5b3d89faec79)

### What error did you receive?

N/A

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Other

### Operating System

Mobile Device

**Comment by carkom** [comment]
#1874

**Comment by youngcw** [comment]
fixed in #1874
