### ISSUE TITLE
[Bug]: Dark Mode - Mobile Transactions Page

### ISSUE THREAD

**Issue by joel-jeremy** [actualbudget/actual#1882]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Dark mode colors in mobile transactions page:
![image](https://github.com/actualbudget/actual/assets/20313680/f8f2268a-4f9b-454a-93dd-814e29f311ad)

### What error did you receive?

N/A

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome, Other

### Operating System

Mobile Device

**Comment by carkom** [comment]
#1874

**Comment by youngcw** [comment]
fixed by #1874
