### ISSUE TITLE
[Bug]: Importing a QFX file with multiple months of transactions fail

### ISSUE THREAD

**Issue by anthonyma94** [actualbudget/actual#1884]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When importing QFX files that have multiple months of data collated, the import immediately fails with `Error: Failed importing file`. The data is collated on the bank's website (I've tried multiple banks).

ZIP with valid files (each month is individual)
[qfx valid.zip](https://github.com/actualbudget/actual/files/13302388/ofx.valid.zip)

ZIP with invalid file (same transactions, but combined into a single file)
[qfx invalid.zip](https://github.com/actualbudget/actual/files/13302389/qfx.invalid.zip)

### What error did you receive?

Docker logs show no errors.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Windows 11

**Comment by joel-jeremy** [comment]
Thank you for filing a report! A fix for this is currently being worked on. This is a bug on the experimental OFX parser. To fallback to the previous OFX parser, you can disable the `Experimental OFX parser` in the experimental features setting.

**Comment by joel-jeremy** [comment]
@anthonyma94 A fix has been merged to the main branch. The fix should be available on the edge version when it gets deployed later today and available on the December release.
