### ISSUE TITLE
Is charset/encoding supported when importing qfx files?

### ISSUE THREAD

**Issue by bbigras** [actualbudget/actual#189]
I have qfx files with `CHARSET:8859-1` with transactions having accentuated characters and I think it's not importing correctly.

**Comment by TomAFrench** [comment]
Can you provide an example qfx file (suitably redacted)?

**Comment by rich-howell** [comment]
Hey @bbigras 

To progress this, the dev team has asked if it possible you can provide a example qfx file with your sensitive information removed? 

Cheers
Rich

**Comment by bbigras** [comment]
[releve.qfx.gz](https://github.com/actualbudget/actual/files/9835441/releve.qfx.gz)
