### ISSUE TITLE
[Feature] "Link as Transfer" Option with 2 Selected Transactions

### ISSUE THREAD

**Issue by rydrman** [actualbudget/actual#1891]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I regularly will use a search either by date, amount, or description to find pairs of transactions that are transfers (all data is manually imported). I then mark them as transfers but need to do each one individually and ensure that I match them up symmetrically.

### Describe your ideal solution to this problem

I would love to be able to select pairs of transactions after searching and have them bi-directionally marked as transfers. This is basically a quality-of-life improvement to make it faster to edit both at the same time.

I would also like to suggest using the `T` key as a shortcut for this 

### Teaching and learning

This can easily be a part of the tips and tricks page or any page that mentions the shortcuts available on the transactions page.

**Comment by psybers** [comment]
This could be a partial solution to #1628 as well.

**Comment by twk3** [comment]
PR for first iteration of this is now open for review here: https://github.com/actualbudget/actual/pull/2398

First iteration does not include a hotkey (to simplify the initial PR). And doesn't have a workflow for mobile (we don't have a multi select transaction workflow for mobile I can reuse yet).
