### ISSUE TITLE
[Bug]: ERR_UNSUPPORTED_ESM_URL_SCHEME

### ISSUE THREAD

**Issue by th3c0d3br34ker** [actualbudget/actual#1905]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Unable to run `yarn start` using `actualbudget/actual-server` on windows.

Node version:  `v18.16.1`
`actualbudget/actual-server` version:  `v23.11.0`

### What error did you receive?

```bash
Checking if there are any migrations to run for direction "up"...
Rejection: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file and data are supported by the default 
ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'e:'
    at new NodeError (node:internal/errors:399:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1059:11)
    at defaultResolve (node:internal/modules/esm/resolve:1135:3)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ESMLoader.import (node:internal/modules/esm/loader:525:22)
    at importModuleDynamically (node:internal/modules/cjs/loader:1188:29)
    at importModuleDynamicallyWrapper (node:internal/vm/module:429:21)
    at importModuleDynamically (node:internal/vm:106:46) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```

### Where are you hosting Actual?

Locally via Yarn

### Operating System

Windows 11

**Comment by MatissJanis** [comment]
https://github.com/tj/node-migrate/issues/201

**Comment by MrScriptX** [comment]
Maybe a temporary fork to fix the issue should be done, or maybe a downgrade ? Currently, actual is broken on Windows and the issue link is open since August with no PR opened yet.

**Comment by MatissJanis** [comment]
I don't have Windows, so sadly I can't reproduce and thus fix it. If anyone is able to repro: a patch PR would be more than welcome.

In the meantime I would recommend using the docker version of Actual. That will work in all environments

https://actualbudget.org/docs/install/docker#launch-container-using-docker-command

**Comment by MikesGlitch** [comment]
I fixed the migrate package for windows here (the PR is in draft): https://github.com/tj/node-migrate/pull/202

I think it should work but would someone on Linux be able to check it still works there?

If you clone it down you can just update your Actual Server package.json "migrate" dependency with: 

    "migrate": "file:../node-migrate",

where the path is the path to the repo.

**Comment by MatissJanis** [comment]
Should be solved now. Please let us know if the issue still persists.
