### ISSUE TITLE
[Maintenance] Delete unused variables

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#1907]
We currently use `@typescript-eslint/no-unused-vars` eslint rule which is enabled for most things. However, it is disabled for `args`.

The overall goal here would be to re-enable `@typescript-eslint/no-unused-vars` for `args`. Thus disallowing unuser arguments.

https://github.com/actualbudget/actual/blob/08c80b6f585eaa3237100972f0edc06e45e444d1/.eslintrc.js#L54

**Please do not do this as one-big-bang migration.**

**Comment by Sahad-09** [comment]
I'm working on it

**Comment by jaas666** [comment]
Sorry, didn't saw earlier that @Sahad-09 was working on this. Feel free to close my PR in favor of his.
