### ISSUE TITLE
Android app is not supported on Android 13

### ISSUE THREAD

**Issue by samip5** [actualbudget/actual#1908]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

![Screenshot_20231115-021529](https://github.com/actualbudget/actual/assets/1703002/6ab27cd0-d283-4848-a0a7-3269bbadfc4a)

### Where are you hosting Actual?

Other

### Operating System

Mobile Device

**Comment by youngcw** [comment]
The android app is legacy and doesn't work with open source Actual. For mobile use the regular web page. It is responsive and designed to work on mobile devices as well as desktop devices.
