### ISSUE TITLE
[Bug]: Switching from rollover budget to report budget and immediately back does not work

### ISSUE THREAD

**Issue by joel-jeremy** [actualbudget/actual#1915]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Steps to reproduce:
1. Enable report `Budget mode toggle` experimental feature
2. Switch to a report budget
3. Switch back to a rollover budget

The tooltip just shows a loading indicator but it does not switch.

### What error did you receive?

The budget mode toggle just shows a loading indicator but does nothing

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome, Other

### Operating System

Windows 11

**Comment by youngcw** [comment]
Im seeing this too.  It only seems to happen if you switch style, then immediately switch back.  If you look at a different page or change something it doesn't hang when switching

**Comment by joel-jeremy** [comment]
Yes, I see the same behavior. Switching pages must be resetting something to make the switch logic work.

**Comment by paulsukow** [comment]
I have a fix for this and will create a pr shortly
