### ISSUE TITLE
[Feature] Calendar view for scheduled items

### ISSUE THREAD

**Issue by Yecats** [actualbudget/actual#1928]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

This feature would add a calendar view for items that are scheduled via the Schedules tab.  Having a calendar view is great for people who are living more pay check to pay check (or just want to have a more visual view of their reoccurring bills/income). It gives them some insight into how to balance funds for each check.

### Describe your ideal solution to this problem

On the schedule or budget tab you could have a calendar view at the top that shows the following information on the relevant days:

1. Name of Scheduled item  
2. Amount 

An added bonus would be if you could tie an icon to the scheduled item so that it displays the item. Users could have the option to upload their own (so they can tie it to a logo of the company the bill is tied to) or provide them with ones from something like https://fonts.google.com/icons. (Even more bonus for recoloring options.)

### Teaching and learning

This feature should be a visualization on top of the existing feature set for scheduling - so the documentation is pretty minimal. Just a screenshot and a blurb explaining what drives the data behind what you see.

**Comment by CrazyKidJack** [comment]
I think it would be cool if this were actually turned into a report.
That way if the budget forecasting FR gets implemented, we could see the schedule calendar and the forecast at the same time

**Comment by Juulz** [comment]
I tested Monarch Money and they had this feature, it was very useful.

**Comment by Spaghettio73** [comment]
For anyone still wanting this: I built a small read-only CLI that exports your scheduled transactions to a standard .ics file any calendar app can import or subscribe to. It asks Actual's own schedule engine for the dates via @actual-app/api, so weekend skips and end conditions match the app exactly. MIT, single file: https://github.com/Ildana-ai/actual2ics
