### ISSUE TITLE
[Bug]: QIF File import doesn't parse date correctly, ends up in notes column 

### ISSUE THREAD

**Issue by KyleK1782** [actualbudget/actual#1932]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When importing, the date ends up in notes instead of date column! 
Sample from the import file (snipped to remove private transactions) 
```
!Type:Bank
M11/15/2023
T-7.49
N
PSQ *EQUATOR COFFEE BARRHAOttawa 
^
```

<img width="804" alt="Screenshot 2023-11-19 at 1 46 09 AM" src="https://github.com/actualbudget/actual/assets/81052018/1eb4c672-bd46-4c82-96a5-ede7e8af6af7">

### What error did you receive?

No error. 

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by joel-jeremy** [comment]
Looks like your bank's export is generating a QIF which stores the date in the memo tag (as seen in this line `M11/15/2023`). That is unusual since the date must labeled with a `D` tag e.g. `D11/15/2023`. That is why Actual is (rightfully) setting it in the memo field.

**Comment by KyleK1782** [comment]
Interesting okay, I’m not surprised. My bank supports many formats but isn’t great about labeling or including more information. 

Would it be possible to include a way to switch the memo and date columns in the interface?

**Comment by rolinge** [comment]
I see you are using a Mac, you could send your data file through sed (stream editor) before importing, changing the first character from M to D on the appropriate lines...
Something like
(Open a terminal, navigate to the directory of your bank file)

 cat yourfile.QIF | sed 's/^M/D/' > newfile.QIF .  

Or, get your bank to export with the proper field identifiers.  sed is easier.

**Comment by KyleK1782** [comment]
Thanks @rolinge the sed command seems to be the issue. I'll let my bank know they're not following the standard.
