### ISSUE TITLE
[Feature] Create Payee Rules "begins with" or "contains" conditions. 

### ISSUE THREAD

**Issue by apilbeam101** [actualbudget/actual#1947]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

A number of organisations that have regular payments (in and out of accounts) use a slightly different payee reference each time the transaction occurs. Usually with a one or two digit change each time denoting either the month of the transaction or month of the subscription. For example, the format of "<company-name> <account-reference> <month-MM>".

This makes it difficult to set up automated rules for some types of regular payments since it is not possible to match on Payee. 

For example, regular salary paid from ACME Inc between January and March would see the payee as:
ACME Inc. 12345 01
ACME Inc. 12345 02
ACME Inc. 12345 02

Screenshots as an example:
![image](https://github.com/actualbudget/actual/assets/110603139/97deac23-b4cc-4472-b0ee-6cc0efd771c0)
![image](https://github.com/actualbudget/actual/assets/110603139/f56b0bc6-768e-445a-a3ef-1cffffa8c661)

### Describe your ideal solution to this problem

In the Rule Creation window, provide additional match criteria for payee to include filters for "begins with" or "contains" which would allow future transactions to be automatically mapped to the correct category.

![image](https://github.com/actualbudget/actual/assets/110603139/294037bc-dfca-42d7-a318-a8384dae8222)

### Teaching and learning

Users, when creating rules would see additional items in the drop-down. 

If feasible, it could be possible to "suggest" rules in the UI where payees are almost identical. 

For me, and many others, worked examples always provide the best results when it comes to documentation and screenshots always help (although can be confusing if there are UI changes).

**Comment by apilbeam101** [comment]
You are absolutely correct. 

I hadn't seen the distinction between "payee" and "imported payee" on the rule creation page. Not sure how I missed that one.

**Comment by youngcw** [comment]
@apilbeam101 Ill close this as a feature request if you are happy with the imported_payee method
