### ISSUE TITLE
[Feature] Conditional flip amount in CSV import

### ISSUE THREAD

**Issue by kymckay** [actualbudget/actual#1953]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

See this sample from a set of downloaded credit card transactions:
![image](https://github.com/actualbudget/actual/assets/5459452/ecc4b31b-2d54-427f-9f9d-6489bdf4ed7c)

The amount should only be flipped for rows where `debitCreditCode` is valued `Debit`. It's no big problem in this simple case, but on a much larger file the user either needs to pre-process the CSV or post-process the amounts in Actual after import.

### Describe your ideal solution to this problem

Needs a bit of design thought, but perhaps a secondary checkbox is shown if "flip amount" is ticked. Checking the secondary box enables selection of a column + selection of a value from that column to flip the amount on a simple `if` condition.

Would probably want to consider whether there are possible more complex cases and whether those should be supported too. Overall this isn't an urgent need because the user can open the CSV in spreadsheet software and tweak it before import.

### Teaching and learning

- Should be described at https://actualbudget.org/docs/transactions/importing if added.

**Comment by shall0pass** [comment]
I don't know about your specific file, but the checkbox to "split amount into separate input/outflow columns" has corrected this for me in the past.

**Comment by kymckay** [comment]
> I don't know about your specific file, but the checkbox to "split amount into separate input/outflow columns" has corrected this for me in the past.

Sadly not suitable here. It seems some organisations (this is the second I've come across) only provide CSV statements with all values in a single positive column and a separate debit / credit flag column.

**Comment by youngcw** [comment]
@kymckay I think this is doable now.  Can you confirm?

**Comment by kymckay** [comment]
@youngcw confirmed!
