### ISSUE TITLE
[Feedback]: Schedules with Rules are a solution looking for a problem

### ISSUE THREAD

**Issue by thed0g12345** [actualbudget/actual#1954]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Coming from YNAB desktop app I really have no idea why the Scheduled transactions are so overengineered and complicated, so one has to construct Rules to just have a proper Note applied.

There's also a use-case, how in the f*** to apply a Rule to a scheduled transaction for the same amount of money, same payee and same account on the same date? 

To clarify - I have two bills on the same date (18th), both have different amounts and Payees, Account is the same. I can schedule both of those transactions and apply rules to set the proper note what this transaction is, based on the documentation. This works fine, because the Payee and Amount are different in each case.

Now, both of these transactions are also getting billed at the bank as a transaction fee with the same amount (0.30€ per transaction to pay bill automatically).

### What error did you receive?

If I create two scheduled transactions for both of these transaction fees with same Payee (my Bank, since they're the receiving end), Account and Amount, then create two rules which apply two DIFFERENT notes to the transactions, only one scheduled transaction gets added and the other is missed. Of course I can't apply the Rule based on a Note, because you can't specify a Note when creating the Scheduled transaction. 

Why is this simple thing so overcomplicated? In YNAB you'd set a scheduled transaction with fixed Payee, Account, NOTE, CATEGORY, Date, Amount, reccurence and it was rock solid and applied every single time. 

Reading the Documentation - quote "Many times it's desired to add notes to the scheduled transactions or to assign categories automatically. This is done with the [Rules](https://actualbudget.org/docs/budgeting/rules) tool.)" it's even explained in a way that the whole Rule functionality was implemented to do something YNAB has done simply by just setting the Note with the Scheduled transaction and be done with it. 

Can't this be done immediately when making a Scheduled transaction by just simply typing the Note or setting the Category there?

Otherwise Actual feels a great replacement to the YNAB, only this behaviour has been frustrating me for two months now.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Windows 10

**Comment by MatissJanis** [comment]
👋 While we appreciate the candid feedback, let’s always keep in mind that all the people working on Actual are unpaid volunteers, whereas YNAB is a paid product. This feedback, whilst valid, does unfortunately come across as quite  demanding and without consideration to our hard working volunteers. What we are endeavouring to build is a mutually supportive and friendly community.

If you have a feature request: please feel free to open one [here](https://github.com/actualbudget/actual/issues/new/choose). But please double-check the messaging that you use there. Negative feedback is fine, but please let’s all use friendly and respectful language at all times
In the meantime the issue of the two identical schedules on the same day could be resolved by giving them each very slightly different payee names
