### ISSUE TITLE
[Bug]: Error when creating a category with the same name as a deleted category 

### ISSUE THREAD

**Issue by joel-jeremy** [actualbudget/actual#1963]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Steps to reproduce:
1. Delete a category e.g. `Test`
2. Create a `Test` category under the same group

### What error did you receive?

![image](https://github.com/actualbudget/actual/assets/20313680/fcd72da0-227e-47f5-8b8b-6b5595a64e76)

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome, Other

### Operating System

Windows 11

**Comment by joel-jeremy** [comment]
@Shazib are we not totally removing the categories from DB when deleting?

**Comment by Shazib** [comment]
Hmm, I guess not...

Is this as a result of my recent changes? I will review this evening.

**Comment by meichenf** [comment]
I ran into this problem as well but just edited categories->tombstone for that item 1 to 0 which appeared to fix the issue after I rebooted my container.  I haven't looked at the code but I'm guess Module.insertCategory isn't checking that flag / INTEGER.
