### ISSUE TITLE
[Bug]: Dark Theme - White textboxes in budget screen

### ISSUE THREAD

**Issue by sewbacca** [actualbudget/actual#1966]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When hovering with the mouse above a budget, it appears white and unreadable.

![grafik](https://github.com/actualbudget/actual/assets/15840247/4915959f-64a6-4127-b3e2-7be1943c82b6)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### Operating System

Windows 10

**Comment by MatissJanis** [comment]
I believe this is now fixed in `master` branch. Can you confirm?

**Comment by sewbacca** [comment]
I would, but I don't know how. I tried the local server version, but it used the release version. I cloned actual, however I couldn't run it (localhost:3001 was empty). How would I test the master branch?

**Comment by youngcw** [comment]
You can try demo.actualbudget.org. That should be up to date.

**Comment by sewbacca** [comment]
Oh that is much easier, and yeah it's fixed there.
