### ISSUE TITLE
[Bug]: Transaction list hotkeys stop working sometimes

### ISSUE THREAD

**Issue by kymckay** [actualbudget/actual#1969]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When using keyboard navigation in the transactions list, the hotkeys to interact with transactions (e.g. D for delete, C for edit category, etc.) frequently stop registering and there is no effect when pressed.

Have yet to track down a consistent reproduction for this, but confirmed this happens to at least one other contributor in Discord.

Seemingly once it happens it's permanent, I've been unable to find a way to get them working again beyond restarting Actual.

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

**Comment by cgiacofei** [comment]
I just ran in to this issue. Refreshing the browser page was enough for me to get hotkeys working again.
