### ISSUE TITLE
[Bug]: style - button hover background colors

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#1971]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

~Somewhere along the way to darkmode we have lost hover colors for most buttons in light mode. We should bring them back (maybe not the exact colors as before if they violate the color paletter, but still something)~

We are missing hover color for the primary color buttons. For example: rule creation.

### Where are you hosting Actual?

None

### Operating System

None

**Comment by carkom** [comment]
Can you provide an example?

**Comment by MatissJanis** [comment]
Just checked v23.7.0. Seems the problem is there too. So it doesn't seem to be a regression after all. Just something we've never had I guess. Weird either way.

| Button | Hovered |
|--------| --- |
| <img width="158" alt="Screenshot 2023-11-26 at 15 41 52" src="https://github.com/actualbudget/actual/assets/886567/61bd3dfd-80fa-4c24-b757-87724d4437a9"> | <img width="158" alt="Screenshot 2023-11-26 at 15 41 52" src="https://github.com/actualbudget/actual/assets/886567/61bd3dfd-80fa-4c24-b757-87724d4437a9"> |

**Comment by carkom** [comment]
Good news is that it's really easy to change. It's already assigned in "Button.tsx"

`const backgroundColorHover = {
  normal: theme.buttonNormalBackgroundHover,
  primary: theme.buttonPrimaryBackgroundHover,
  bare: theme.buttonBareBackgroundHover,
  menu: theme.buttonMenuBackgroundHover,
  menuSelected: theme.buttonMenuSelectedBackgroundHover,
  link: theme.buttonBareBackground,
};`

Only change happens in "light.ts" where background and backgroundhover are the same.
`export const buttonPrimaryText = colorPalette.white;
export const buttonPrimaryTextHover = buttonPrimaryText;
export const buttonPrimaryBackground = colorPalette.purple500;
export const buttonPrimaryBackgroundHover = buttonPrimaryBackground;
export const buttonPrimaryBorder = buttonPrimaryBackground;`

**Comment by Ife-Ody** [comment]
Is anyone already working on this? I am looking to make some contributions because I love the vision

**Comment by carkom** [comment]
Not that I'm aware of. Feel free. Please tag me for review.

**Comment by Ife-Ody** [comment]
finally working on this today

**Comment by Ife-Ody** [comment]
The fix was easy. I just picked a shade lighter in the light mode and a shade darker in the dark mode

> Good news is that it's really easy to change. It's already assigned in "Button.tsx"
> 
> _const backgroundColorHover = { normal: theme.buttonNormalBackgroundHover, primary: theme.buttonPrimaryBackgroundHover, bare: theme.buttonBareBackgroundHover, menu: theme.buttonMenuBackgroundHover, menuSelected: theme.buttonMenuSelectedBackgroundHover, link: theme.buttonBareBackground, };_
> 
> Only change happens in "light.ts" where background and backgroundhover are the same.
> 
> _export const buttonPrimaryText = colorPalette.white; export const buttonPrimaryTextHover = buttonPrimaryText; export const buttonPrimaryBackground = colorPalette.purple500; export const buttonPrimaryBackgroundHover = buttonPrimaryBackground; export const buttonPrimaryBorder = buttonPrimaryBackground;_

**Comment by carkom** [comment]
Great! Yea, we implemented the code like that to make color changes really easy. Go ahead and create a PR with your changes. Cheers!

**Comment by carkom** [comment]
fixed by #2123
