### ISSUE TITLE
[Feature] Option to reconcile by date

### ISSUE THREAD

**Issue by tavlima** [actualbudget/actual#1974]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I have a handful of importers that pull data from my banking accounts/credit cards, which are marked as cleared (as they are already processed by the bank). But, sometimes, the balance doesn't match the banking statement and I need to manually reconcile.

It would be much easier if I could use an optional reference statement date when reconciling, so that I could go month by month, instead of clearing all checked status for the other months. I think this would be a great addition, especially now that #1789 is merged.

### Describe your ideal solution to this problem

The reconcile popup would ask not only for the amount, but also the reference date, which would default to "today".

**Comment by ToniCipriani** [comment]
This is needed, not only credit card statements might not get issued on the day of a statement period end date, I have other accounts that don't produce statements for at least a month or two.
