### ISSUE TITLE
[Bug]: Filter Amount formatting issue

### ISSUE THREAD

**Issue by carkom** [actualbudget/actual#1977]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Filtering by ammount (Amount/inFlow/outFlow) is displayed as integer amounts but should be decimal place amounts. Example listed below is using filtering for 200.00.

![image](https://github.com/actualbudget/actual/assets/55785687/d1d48b38-8289-44ec-b0be-bd0d790a565c)

### Where are you hosting Actual?

None

### Operating System

None

**Comment by vishnukaushik** [comment]
@carkom I would like to work on this. Could you please assign this to me?
Thanks!

**Comment by Sanket-Arekar** [comment]
Hey @carkom  I would like to work on this issue. Can you Please assign me this issue?

**Comment by carkom** [comment]
> Hey @carkom  I would like to work on this issue. Can you Please assign me this issue?

I think @vishnukaushik is already working on it.

**Comment by vishnukaushik** [comment]
@carkom thank you!
Could you please explain the issue a bit?

**Comment by carkom** [comment]
I'm not sure what else to say that isn't already written in the OP. Feel free to duplicate the issue in your local to get a better understanding. If you have specific questions, let me know.
