### ISSUE TITLE
Category Spending Report Fatal Error

### ISSUE THREAD

**Issue by Kidglove57** [actualbudget/actual#1981]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I am using the latest Edge tag. In the Reports section when clicking on Category Spending Report I get a fatal error 

### What error did you receive?

Fatal Error
There was an unrecoverable error in the UI. Sorry!
If this error persists, please get [in touch](https://actualbudget.org/contact) so it can be investigated.
tk@https://xxxxx-857.fly.dev/static/js/reports.24d7fc90.chunk.js:1:39473 i2@https://xxxxx-857.fly.dev/static/js/main.dad75dd5.js:37:64290 lF@https://xxxxx-857.fly.dev/static/js/main.dad75dd5.js:37:117586 lD@https://xxxxx-857.fly.dev/static/js/main.dad75dd5.js:37:113204 lj@https://xxxxx-857.fly.dev/static/js/main.dad75dd5.js:37:113132 lE@https://xxxxx-857.fly.dev/static/js/main.dad75dd5.js:37:112986 lp@https://xxxxx-857.fly.dev/static/js/main.dad75dd5.js:37:109298 lh@https://xxxxx-857.fly.dev/static/js/main.dad75dd5.js:37:108250 k@https://xxxxx-857.fly.dev/static/js/main.dad75dd5.js:96:1548 _@https://xxxxx-857.fly.dev/static/js/main.dad75dd5.js:96:1912

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Safari

### Operating System

Mac OSX

**Comment by Kidglove57** [comment]
I can also replicate this on Chrome

**Comment by youngcw** [comment]
I saw this this morning as well.  It was on firefox

**Comment by shaankhosla** [comment]
`https://demo.actualbudget.org` has this error currently as well. I replicated it on Firefox, Chrome, and Safari

**Comment by youngcw** [comment]
This is the output in the console
```
react-dom.production.min.js:189 TypeError: Cannot read properties of undefined (reading 'every')
    at tk (CategorySelector.tsx:38:44)
    at i2 (react-dom.production.min.js:167:137)
...
```

**Comment by youngcw** [comment]
@MatissJanis Is this something that should be fixed before the release? or should we wait as this is experimental

**Comment by MatissJanis** [comment]
Since it's experimental: it's OK to leave it broken.

But if we can fix it in a small PR that's low-risk: it would be very nice to include in the Dec release.

**Comment by 1amtimon** [comment]
I also face this when I try in chrome.

**Comment by cracksys** [comment]
Having the same issue using Edge, Window 11
