### ISSUE TITLE
[Feature] "Add category" button should be easier to access than "Add Group"

### ISSUE THREAD

**Issue by jamesWalker55** [actualbudget/actual#1989]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

In the Budget page, categories are organized by groups. A single group can contain multiple categories:

![image](https://github.com/actualbudget/actual/assets/30405220/9dc79c9f-aec3-493f-8a34-b254df1f72d8)

To create a group, you can directly click the "Add Group" button which is always visible. To add a category, you click on the hidden drop-down menu (that only appears when your mouse hovers over it), then click the "Add category" button.

I'm not sure this user flow makes sense. Given that there must always be more (or equal) categories than groups, I'm creating categories more frequently than groups. However, the creating a category takes 2 button clicks in a hidden menu, while creating a group takes only 1.

### Describe your ideal solution to this problem

The "Add category" button should be made easier to access, preferably with a single mouse click.

I'm no UI designer, but here is an example to demonstrate:

![image](https://github.com/actualbudget/actual/assets/30405220/0bb9e2b6-0563-4908-b4d6-76346a36684e)

(Side tangent: The notes icon greatly resembles the "New document" icon found in many word processors, and makes me think I'm about to create a new file when clicking on it - perhaps that icon could be revised?)

**Comment by kymckay** [comment]
I consistently mistakenly hit this button on intuition when I want to add a new category. Related to #2051 which may be an alternate solution to this (though doesn't address category creation being behind a click).

**Comment by joel-jeremy** [comment]
This is related to: https://github.com/actualbudget/actual/issues/1123
