### ISSUE TITLE
I forgot my password

### ISSUE THREAD

**Issue by Lennert159** [actualbudget/actual#1990]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I forgot my password to sign in for my instances

### What error did you receive?

Invalid password

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 10

**Comment by shall0pass** [comment]
You can reset your password by navigating to the server-files folder in your mapped volume, deleting account.sqlite, and restart the docker container.

**Comment by MatissJanis** [comment]
+1 to what @shall0pass said

Also: https://actualbudget.org/docs/troubleshooting/reset_password

**Comment by poteirard** [comment]
Hello,

I installed Actual Budget using [Proxmox Scripts](https://community-scripts.github.io/ProxmoxVE/scripts?id=actualbudget).
And added SSL later, now it prompts for the passoword and I can't remember it.

I tried:
- Removing 

I know this issue is closed, but since it´s releated maybe it make sense to have it here.

**Comment by Benjythebee** [comment]
Note that the documentation is outdated : npm run reset-password isn't a thing anymore

**Comment by MatissJanis** [comment]
> Note that the documentation is outdated : npm run reset-password isn't a thing anymore

What makes you think that? It should still be working. If it's not - that would be a bug and a bug report for it would be appreciated (with reproduction steps).

**Comment by Benjythebee** [comment]
I agree I should make a ticket. Now, not to sound dick-ish, this is a very simple thing you can check yourself before commenting:
https://github.com/actualbudget/actual/blob/master/package.json#L20-L65

`reset-password` does not exists in package.json

Unless I'm mistaken that's a very easy indicator the documentation might be outdated on that topic.
https://github.com/actualbudget/actual/issues/7943
