### ISSUE TITLE
Manually entered split transactions are not cleared on import

### ISSUE THREAD

**Issue by Cooad** [actualbudget/actual#200]
Usually when I import my bank statement, all the transactions that I entered manually prior to the import get marked as cleared, and they are counted correctly when I reconcile the account.
However, if the manually inserted transaction is splitted into multiple categories, it will be marked as cleared in the UI (it will have the green tick on the right), but it's not counted when I reconcile the account.
I have to unclear and clear the transaction again manually in order for it to be counted correctly.

**Comment by bjornbostrom** [comment]
It seems that this behaviour also occurs when syncing an account through Nordigen. A splitted transaction that I entered manually before syncing got the "green checkbox" upon sync, but it's "splitted subentries" seems to still count as uncleared. If I uncheck the green box and then check it again solves the state.

**Comment by Cooad** [comment]
Yes, I can confirm that syncing through Nordigen exhibits the same behavior

**Comment by youngcw** [comment]
This looks to have been fixed.  Closing
