### ISSUE TITLE
[Feature] Allow Category for Off Budget Accounts

### ISSUE THREAD

**Issue by dylanlive** [actualbudget/actual#2006]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Per [the docs](https://actualbudget.org/docs/accounts/)
>Off budget accounts don't effect the budget and are meant to track stuff like investments and mortgages. Transactions in off budget accounts can't be categorized; they simply track balances over time.

For Investment Accounts, there are certain types of transactions that can be valuable to assign to a category. However, categories currently cannot be set for Off Budget accounts.

An example is Dividend Reimbursement. It would be a nice functionality to search how much you earned in Dividends across all of your investment accounts. This is useful for tax purposes to ensure you're withholding enough.

There could possibly be ways to achieve this (Notes, Tags?) but I think the Dividend category is a cleaner solution, and for something as important as taxes it's best for a clean solution.

Example of this in Mint, in which the time range can be adjusted to gather the total dividends earned:
<img width="985" alt="Screenshot 2023-12-01 at 7 19 15 PM" src="https://github.com/actualbudget/actual/assets/4992944/93043208-a668-4c3c-8120-d8cabed42313">

### Describe your ideal solution to this problem

- Allow for a category to be set on transactions within "Off Budget" Accounts
- Exclude transactions within these accounts from the Budget Ledger, similar to today
- Allow for those account categories to be filtered, similar to regular accounts

Interestingly, it seems the `importTransactions` API still allows Off Budget transactions to be categorized, but it's not editable/displayed in the UI. I'm concerned if this isn't officially supported, it could break in the future.
<img width="1395" alt="Screenshot 2023-12-01 at 7 28 15 PM" src="https://github.com/actualbudget/actual/assets/4992944/eb872568-bf01-41f0-a623-5d6312f19acd">

**Comment by Kidglove57** [comment]
I agree - although for the moment I note the transaction type in the Notes column

**Comment by youngcw** [comment]
Can't you use the payee field to get the same affect? You can filter by a payee of Dividend, Deposit, Market Fluctuation, etc.

**Comment by dylanlive** [comment]
@youngcw I think it's possible, but I'm still not quite sure it's a clean solution. Admittedly I might need to change the way I think after using Mint for 10+ years. I'm trying to think through the Import process - taking a look at Schwab the transactions appear like:
```
Action: Cash Dividend
Description: ORDINARY DIVIDEND (AGG)
```

```
Action: Non-Qualified Div
Description: NON-TAXABLE DIVIDENDS (MUB)
```

I'd consider Schwab's "Action" to be a "Category"

I believe per your current mint importer, the Payee currently would get set as the description. And it might be nice to retain the ETF that paid the dividend (AGG, MUB, etc). Think of the power to search `Category [Is] Dividend & Cap Gains, Payee [Contains] AGG`

I could shift the import to perhaps dump this into notes.

So yes, I think there are alternative ways to achieve this, but from a non-technical standpoint I question why Category can't be applied to Non-Budget Accounts. We don't want the account to be applied to the Budget, but that doesn't mean we can't gain benefits from categorization.

My guess is it might be more technical reasoning and require a refactor for the budget to ignore categories within Off Budget, though as I discovered the Category for `Off Budget` Transactions can be get/set via the API and I'm not seeing an amount in my budget for `Dividend & Cap Gains`. So this might be more of a Philosophical & UI change.

**Comment by youngcw** [comment]
If you want to track individual ETFs or funds you likely would be better served using a dedicated investment tracker. I know ghostfolio is one people like.

Are those actions just a reworded version of the description? Maybe it's just your examples, but if that's the case in you imports setting a category doesn't gain you any information.

**Comment by dylanlive** [comment]
I think ultimately my use case is aggregating all of the dividends I've earned across my accounts, without losing metadata. I believe categorizing the transaction can achieve that in the cleanest way. In the meantime, I'll look into Empower/PersonalCapital but I haven't liked their lack of Trend graph functionality.

**Comment by savionlee** [comment]
I discovered another possible use for off-budget categories. For a student loan, I'd like to categorize the interest accumulated. 

Then I can search by category for Loan Interest.

**Comment by enewbury** [comment]
Another use-case for me is a splitwise integration. I'm working on a script that imports splitwise transactions into an account, and exports specific split transactions to splitwise.  This would let me more accurately track my expenses even when the transaction was made by my partner, but I am responsible for half of it.

I don't want this splitwise account to be on-budget because money that is owed to me is not liquid/spendable, and likewise, we usually don't do a traditional settle-up every month, I just start taking on more expenses when I'm getting behind, so I also don't want to have to allocate money in my budget for paying this down.

But the point of this is to be able to track my spending trends, even if I wasn't the one who made the transaction, so I would need categories for off-budget accounts to do this.
