### ISSUE TITLE
[Bug]: Dark Mode - Note Icon Not White

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#2012]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

On the budget screen the note icon is still black 

![image](https://github.com/actualbudget/actual/assets/22135084/8ad66cf3-b770-4e00-81fa-acf9328f4981)

### What error did you receive?

None

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

**Comment by carkom** [comment]
Mine are all white. Is this a problem only with MS Edge browser maybe? I've tested on Firefox and Chrome.

![image](https://github.com/actualbudget/actual/assets/55785687/2defcd03-73c0-4d36-a502-a7aecb4609d4)

**Comment by carkom** [comment]
Mine are transparent when not hovered. How do I replicate it?

**Comment by youngcw** [comment]
> Mine are transparent when not hovered. How do I replicate it?

Do you not have any notes in your categories?  The icon doesn't show at all if you don't have any notes.  I guess to recreate you add some notes to some categories, then turn on dark mode

**Comment by rich-howell** [comment]
> Mine are all white. Is this a problem only with MS Edge browser maybe? I've tested on Firefox and Chrome.
> 
> ![image](https://private-user-images.githubusercontent.com/55785687/289057938-2defcd03-73c0-4d36-a502-a7aecb4609d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwNTY4NzksIm5iZiI6MTcwMjA1NjU3OSwicGF0aCI6Ii81NTc4NTY4Ny8yODkwNTc5MzgtMmRlZmNkMDMtNzNjMC00ZDM2LWE1MDItYTdhZWNiNDYwOWQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDE3MjkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ZGQwNjllYTJlY2YwYzJjNDE4YTRkNTU2MzY5MjlkMGQ1YWZiNTEyN2JjMTgwMTc0MmQ2NzIxOGU0YTNmNzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vmYQCK_91HlImJjvGRjXzz5WsAvfXdlF_CWc3a5J9iA)

Replicated in Firefox

![image](https://github.com/actualbudget/actual/assets/22135084/00674fbb-30d9-4cac-9695-1bf01a6a4d57)

**Comment by carkom** [comment]
fixed by #2048

**Comment by rich-howell** [comment]
> fixed by #2048

Awesome, that is indeed fixed

![image](https://github.com/actualbudget/actual/assets/22135084/98295c29-85c9-4991-8be2-c0235992771a)
