### ISSUE TITLE
[Bug]: Dark Mode - Upcoming pill wrong colour

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#2013]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

The upcoming transaction pill in the account register is black instead of purple as it is in the schedules screen.

Taken from accounts screen
![image](https://github.com/actualbudget/actual/assets/22135084/018b11f3-3419-4fc7-b051-91c694163957)

Taken from schedules screen
![image](https://github.com/actualbudget/actual/assets/22135084/a8ba6deb-d9e2-48c0-8bed-1f1e6fa9cc13)

### What error did you receive?

None

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

**Comment by carkom** [comment]
So this matches the way light theme functions. Seems like this is less a problem with darkTheme and more a problem in general. It seems they were designed this way (to not match). If we want to change it, we'd be chaning it for both light and dark themes. I'm always a fan of more consistency so you know my vote! Thoughts?

**Comment by rich-howell** [comment]
> So this matches the way light theme functions. Seems like this is less a problem with darkTheme and more a problem in general. It seems they were designed this way (to not match). If we want to change it, we'd be chaning it for both light and dark themes. I'm always a fan of more consistency so you know my vote! Thoughts?

Consistency over the app would be better.

**Comment by carkom** [comment]
fixed in #2048 2048

**Comment by rich-howell** [comment]
> fixed in #2048 2048

To me this looks much better. 

![image](https://github.com/actualbudget/actual/assets/22135084/04dc3a41-7917-44c2-85f2-d6462fa5c9d3)
