### ISSUE TITLE
[Bug]: Dark Mode - Rules text contrast issue

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#2014]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

On the rules page (shown below)
![image](https://github.com/actualbudget/actual/assets/22135084/ed8b9f9d-57e4-4f94-bffc-a3fb4cd0eb45)

The purple text is really hard to read - it actually fails Aa 

![image](https://github.com/actualbudget/actual/assets/22135084/32368941-bda3-436c-ae9a-7a3fae934f50)

### What error did you receive?

Warning that contrast isn't within parameters of Aa https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

**Comment by carkom** [comment]
Changed them. LMK!

**Comment by rich-howell** [comment]
> Changed them. LMK!

Where did you make the change?

**Comment by carkom** [comment]
fixed by #2048

**Comment by youngcw** [comment]
@rich-howell Is the update good enough to close this off?
