### ISSUE TITLE
Budget Spent to Transaction drill down

### ISSUE THREAD

**Issue by 1amtimon** [actualbudget/actual#2018]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Budget Spent to Transaction drill down is working in Desktop web. Clicking on spent amount opens the pre-filtered transactions that totals to that spent amount. But in Mobile browser, this option is not available.

### Describe your ideal solution to this problem

Add drill down functionality from Spent amount to transactions similar to Web in Mobile browser as well. 

### Teaching and learning

Update the Spent to transaction drill down to include its available in both Desktop Web and mobile browser

**Comment by Kidglove57** [comment]
The drill down will work in Landscape mode on Mobile but I fully accept that is not ideal, so have voted.
