### ISSUE TITLE
[Bug]: Dark Mode - Drop Down Menu Colours

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#2019]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

If we look at the date picker it has a nice background 

![image](https://github.com/actualbudget/actual/assets/22135084/09d3d6f6-1ca9-4802-995f-d36f44a778e1)

Payee & Category pickers in the transaction ledger dont have the same background 

![image](https://github.com/actualbudget/actual/assets/22135084/277b19ab-998e-40a2-a979-a72c41e6b56b)

The purple is hard to read as is the green for the category split with the background being so light. 

### What error did you receive?

No error but possibly an Aa warning.

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

**Comment by carkom** [comment]
I agree with making these consistent. The question then becomes do we change the date one to match the autoComplete or vice versa? In light theme they match but they are opposite coloring to the pagebackground where every other menu dropdown background is a lighter color. If we want to follow that idea then these should both be lighter color and all other menus should be darker (closer to page background).

**Comment by youngcw** [comment]
I think the month picker style looks the nicest.  Plus we get some more common ground between light mode to feel more connected.

**Comment by rich-howell** [comment]
> I agree with making these consistent. The question then becomes do we change the date one to match the autoComplete or vice versa? In light theme they match but they are opposite coloring to the pagebackground where every other menu dropdown background is a lighter color. If we want to follow that idea then these should both be lighter color and all other menus should be darker (closer to page background).

The dark background looks better, taken from the date picker, it is also easier to read, the light background is really hard to read and would need work to get the text into a decent state.

**Comment by carkom** [comment]
fixed by #2048

**Comment by rich-howell** [comment]
> fixed by #2048

In my opinion, that is loads better 

**Before:** 

![image](https://github.com/actualbudget/actual/assets/22135084/afe187c5-f878-4118-aa4f-2edf5c226d48)

**After:** 

![image](https://github.com/actualbudget/actual/assets/22135084/11f6393e-69dc-4e1b-8ddd-a6b8d60d176d)
