### ISSUE TITLE
[Bug]: Syncing from GoCardless re-fills notes

### ISSUE THREAD

**Issue by kymckay** [actualbudget/actual#2024]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

1. Link an account with GoCardless.
2. Sync your the transactions.
3. Set some note values to be an empty note.
4. Re-sync from GoCardless.

The notes get re-filled where they were manually edited to be empty. My expectation would be that the user input takes precedence (though I can infer why it is implemented in a way which fills the empty notes for simplicity).

I need to check the data model and the transaction import resolution logic, but if possible it'd be nice to only import notes to resolved transactions which still contain their imported note.

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

**Comment by MatissJanis** [comment]
Tricky. Lets say you import a transaction that does not have notes. But a few days later you perform an import again, but this time there are notes. In this case you would expect the inverse: the empty notes to be replaced with the new notes.

**Comment by kymckay** [comment]
@MatissJanis I think a good compromise solution to this is to not update reconciled transactions when doing transaction resolution. Avoids adding complexity to determine which empty notes have been set by the user, and still enables this kind of workflow where the user doesn't want the imported notes.

**Comment by MatissJanis** [comment]
Makes sense. I've actually already created a patch for this here: https://github.com/actualbudget/actual/pull/2140
