### ISSUE TITLE
[Bug]: Type error in console log "Failed to get subsystem status for purpose"

### ISSUE THREAD

**Issue by CalebBurton** [actualbudget/actual#2026]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

A console log about a type error is generated on each pageload. There are no error messages on the server.

I also had an infinite loading issue, which is what caused me to look at the console logs in the first place, but it seems like that was just a bad cache: When loading the 23.12.0 app frontend for the _second_ time, the loading icon would spin infinitely and a console log was generated. Clearing the browser's indexed db and doing a hard reload fixed the infinite loading, although the console message persists.

Running docker version 23.12.0, accessing it from Firefox 120 on macOS

The console log does **not** appear when accessing the same page from Chrome 116.

### What error did you receive?

Failed to get subsystem status for purpose 
`Object { rejected: true, message: TypeError }` ( content-script.js:95:21 )

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Mac OSX

**Comment by MatissJanis** [comment]
That looks like an issue with one of your content scripts (extensions/plugins) and not Actual. Can you try actual in incognito mode in Firefox with all the extensions turned off and see if that solves it?

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts

**Comment by CalebBurton** [comment]
Ah! Completely right, my mistake. Thanks for the note
