### ISSUE TITLE
[Feature] Group Level Budget 

### ISSUE THREAD

**Issue by ard0gg** [actualbudget/actual#2027]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I would like to be able to assign a budget for a group, while actually assigning transactions to categories within the group. The idea is that expenses of individual categories count against the group budget, if assigned.  See monarch feature:  https://www.monarchmoney.com/whats-new/group-level-budgeting

### Describe your ideal solution to this problem

Would like to be able to assign budget at Group level and have individual category expenditure count against group budget.

**Comment by anatolybobunov** [comment]
Very interested in this feature.
I recently moved from JNAB and I have to keep a general category in the group in the old way. After that I need to deduct from the general category if there are expenses within the group. 

Entertainment:
- money for a month
- PC games
- books

I like how it is implemented in MonarchMoney.

**Comment by youngcw** [comment]
closing in favor of #3438
