### ISSUE TITLE
[Bug]: Fatal Error in "Add new schedule" form when removing "Amount" and pressing any other field

### ISSUE THREAD

**Issue by real-user** [actualbudget/actual#2035]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

This bug is 100% reproducible on my instance. 
How to reproduce: Go to Schedules --> Add new schedule.
Remove 0.00 from the Amount box so that it is empty.
Click on any other field (for example Schedule Name)

Actual will crash with "Fatal Error" and
"
Error: safeNumber: number is not an integer: null at k (https://actual.lan/static/js/main.7e9611a1.js:187:62729) at C (https://actual.lan/static/js/main.7e9611a1.js:187:62978) at b (https://actual.lan/static/js/main.7e9611a1.js:186:19637) at https://actual.lan/static/js/main.7e9611a1.js:186:19768 at v (https://actual.lan/static/js/main.7e9611a1.js:186:105641) at i2 (https://actual.lan/static/js/main.7e9611a1.js:37:64289) at aX
"

Tested on Android Tablet using Samsung Browser (Chromium based)
Running 
docker.io/actualbudget/actual-server:edge

### What error did you receive?

Fatal Error

Error: safeNumber: number is not an integer: null at k (https://actual.lan/static/js/main.7e9611a1.js:187:62729) at C (https://actual.lan/static/js/main.7e9611a1.js:187:62978) at b (https://actual.lan/static/js/main.7e9611a1.js:186:19637) at https://actual.lan/static/js/main.7e9611a1.js:186:19768 at v (https://actual.lan/static/js/main.7e9611a1.js:186:105641) at i2 (https://actual.lan/static/js/main.7e9611a1.js:37:64289) at aX

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mobile Device

**Comment by MatissJanis** [comment]
Do you still have this issue in [demo](https://demo.actualbudget.org/schedules)?

**Comment by MatissJanis** [comment]
I believe this issue has been resolved already and since there is no reply from OP - I'll close it off. 

Please open a new issue and link to this one if you still experience the issue.
