### ISSUE TITLE
[Feature] align "budgeted" to "spent" in budget overview (easy to align on import) 

### ISSUE THREAD

**Issue by nikolajhendel** [actualbudget/actual#2038]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

This may only be relevant for new users importing existing data (like me).

Having imported years of data into account and setup/tagged expense categories - it's really cumbersome to budget align past months (years), because I have to manually set the budgeted amount to actual spent amount "line by line - month by month".

### Describe your ideal solution to this problem

Feature on budget overview (per month) which set's budgeted = spent amount, resulting in balance = 0.

### Teaching and learning

Include in documentation, either as part of installation/import or budget area.

**Comment by hongtron** [comment]
This would also help eliminate friction for users who wish to leverage Actual's excellent import, rules, etc. functionality for expense tracking, but not budgeting.
