### ISSUE TITLE
[Bug]: Mobile menu blocks items

### ISSUE THREAD

**Issue by carkom** [actualbudget/actual#2040]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

The mobile menu auto-hides after you scroll down a certain amount. Problem is that when there's no scroll available it covers up the items at the bottom of the screen and makes them impossible to get to. Account list example below, but I've tested this on the Budget List as well. Seems it will happen on any page where there is no scrolling ability but the list is long enough to end under the menu.

Best Option I can think of is to not overlay the menu. Then when it's hidden you get more screen space for the list you are loooking at.

You can duplicate this quite easily on a test budget file.
![image](https://github.com/actualbudget/actual/assets/55785687/8ae2d5e6-ca2d-4ed5-a81b-d5fb94c47839)

You can see it's covering the last account "vangaurd..."
![image](https://github.com/actualbudget/actual/assets/55785687/ce859822-e19d-4e8f-9377-d78b88679393)

**Comment by carkom** [comment]
@joel-jeremy , tagging you since I know you are actively working on mobile UI. Cheers!

**Comment by Kidglove57** [comment]
There has been a further report of this in Discord which I am able to reproduce in the demo once a certain number of accounts are added. The bottom account (Vanguard in the clip attached) becomes inaccessible.https://github.com/actualbudget/actual/assets/93882449/59312e61-dd89-4ca4-8b61-b796f10fb9af

**Comment by Kidglove57** [comment]
This is also making the last category  in the budget screen inaccessible on mobile

**Comment by joel-jeremy** [comment]
Closing as this was fixed by https://github.com/actualbudget/actual/pull/2352
