### ISSUE TITLE
[Feature] Generic Migration Importer

### ISSUE THREAD

**Issue by youngcw** [actualbudget/actual#2045]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

As of now we have two official importers for migration, YNAB4 and nYNAB.  We could probably cover a lot of potential migration paths just by having a csv importer that allowed creating accounts and categories at time of file creation.

### Describe your ideal solution to this problem

When starting a new file add a generic import option that allows someone to use one of our existing file importers (csv, ofx, qfx, qif) but with extra capability.  The same importers could be setup to create accounts and categories from the file.

For example Mint.com exports one large csv that has accounts and categories inline with each transaction.  The only thing between the current csv importer and a full migration is handling accounts and categories.

**Comment by mcalligator** [comment]
I wholeheartedly support the need for a feature like this.  I have 13 years of transactions from my previous personal finance software (Home Accountz), tens of thousands of them, and I would dearly love to be able to import them without large amounts of subsequent direct database manipulation to massage them into the shape I want.
