### ISSUE TITLE
[Bug]: This file is not a cloud file not resolving.

### ISSUE THREAD

**Issue by zehndi77** [actualbudget/actual#2049]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

On my main and test instance I do encounter various issues.

In my main instance, my productive file most of the payees and accounts were lost. 
However on one client (work laptop) the file was preserved in a usable state, I could download it, reimport it at my main instance and have all transactions, accounts, payees, categories etc. still there.
It was a local file then, so I tried syncing it and registering it, nothing worked.
Also tried to reset / rebuild the stack (docker compose under portainer), still did not work.

I then tried to run a new docker host, add the stack from a fresh start, still the same issue. 

Currently trying to get back a running instance from backups and try to go from there.

### What error did you receive?

This file is not a cloud file
You need to register it to take advantage of syncing which allows you to use it across devices and never worry about losing your data. [Learn more]

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Operating System

Windows 11

**Comment by youngcw** [comment]
Sounds like your https is working.  My next guess would be that you either have an exotic browser setup, or your data volume isn't working properly and cant preserver the syncing.  Both of those things have caused sync issues.

**Comment by zehndi77** [comment]
https should work, i can connect flawlessly also to other services. 

my browser is opera, but I have the exact same issues on MS edge (same device) and mobile (android)
not working data volume might have been an issue, as my docker host recently ran out of space. 

However I have restored the VM (docker host) to a date before that happened, and still have the same issues.
Also uploading a working copy (locally at least) I have the issues both with my "then" host, my "now" host (different dates, but the very same installation) and a completely new build, (new VM, new docker, new stack)... 
How would I find such issues on the data volume? 
As far as I can tell, all other services (some also newly deployed) do not have these issues.

Best

**Comment by youngcw** [comment]
your screenshot and compose file show a different directory name for the mount point.  Is that expected?

**Comment by youngcw** [comment]
I don't have any more ideas, especially if other browsers also don't work.  Unless you are always deleting site data or something.

**Comment by zehndi77** [comment]
so I just today spun up a new instance outsite of docker, (lxc container) and installed the latest version. Still having the same issues. The backup files gets imported/displayed as I expect it to, but it would not let me uplpad/sync it.

Is there the possibility that something is wrong with my file/export in the beginning? 
happy to share it privately if this might help.

**Comment by MatissJanis** [comment]
👋 Feel free to continue continuing to chat, but this isn't really a bug report. As such: I'll close it off.

Looks more like a misconfiguration somewhere along the way. I would recommend reaching out to the community on Discord for this sort of tech-support.

**Comment by zehndi77** [comment]
it was indeed an incorrectly configured nginx-server.
Thanks for your effort!

**Comment by elfensky** [comment]
## ISSUE

> it was indeed an incorrectly configured nginx-server. Thanks for your effort!

What was the fix? I'm having a similar problem now. 

- When I access over https://budget.mydomain.tld, I **can** successfully create a new budget, and it will sync
- When I access over https://budget.mydomain.tld, I **cannot** upload an older .zip file, it will stay local and fail to register

However.

- When I access the server by http:myLocalIP:port, I then **can** successfully upload my old actual .zip file and it will properly sync with the server. And I can then sync it over https.

Very weird, and I can't figure out where it is failing. 

## FIX
After about an hour of trying to figure it out, turns out I had to add ```client_max_body_size 20M;``` in the nginx config. 

## COMMENT
Weird because I thought my global config specified a default client_max_body_size, but it works now so I'm happy. Technically this was PEBKAC, because looking more closely at the docs, the nginx example does specify setting this value.

**Comment by rnorth** [comment]
I had very similar - sync errors after importing a large number of transactions from CSV, and then when I tried to restore from a backup the 'not a cloud file' error that I was unable to resolve.

Thank you so much for this comment, as it was exactly what I needed to fix the problem 🙇:

> EDIT: after about an hour of trying to figure it out:
> I had to manually specify client_max_body_size 20M; in my nginx config. Weird but ok.

**Comment by zehndi77** [comment]
It's a few months ago, so i can not say with certainty it was that, but sounds reasonable.
I think i disabled it fully (set to 0), but setting it to a big enough value will also work.

**Comment by conceptroot** [comment]
> > EDIT: after about an hour of trying to figure it out:
> > I had to manually specify client_max_body_size 20M; in my nginx config. Weird but ok.

Thank you! That helps. Same issue for me.
