### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by Maxiimeeb** [actualbudget/actual#2054]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I want to use the actual API, but it's only available in JavaScript. From what I see, it would be tedious to make this API available in other languages. I want to make this process easier.

### Describe your ideal solution to this problem

In the `actual-server` project, it would be nice to add routes for a RESTful API with OpenAPI 3.0 specifications. With a RESTful API and good specifications, we could use a code generator that takes in OpenAPI 3.0 and outputs a client for use (e.g., https://swagger.io/tools/swagger-codegen/). It would simplify the support for other languages.

### Teaching and learning

We can now interact with Actual in any other languages easily

**Comment by twk3** [comment]
@Maxiimeeb I see that you saw the other issue, but did you also take a look at https://github.com/jhonderson/actual-http-api ?

I wonder if contributing changes there to bring it to align it with openAPI 3 would be better.

For the actual-server, it shouldn't be making changes to the data, as that component is intended as a data storage service primarily, and not a typically backend, but you can optionally have a rest api running a client and api alongside it.

**Comment by youngcw** [comment]
Closing in favor of #1384.  Make some comments there to add more details about openAPI 3 and maybe other languages.
