### ISSUE TITLE
[Feature] Ability to import from CSV and after enable bank sync

### ISSUE THREAD

**Issue by samip5** [actualbudget/actual#2055]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I'm trying to solve the problem of 90 days of transactions. I would like to import multiple years worth.

### Describe your ideal solution to this problem

Simply allow me to create an account, import bank CSV and after enable bank sync to keep it in sync.

**Comment by matt-fidd** [comment]
This has been implemented
