### ISSUE TITLE
[Feature] PWA support 

### ISSUE THREAD

**Issue by edersong** [actualbudget/actual#2060]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

The mobile web APP has evolved a lot, but it still missing PWA support because, as reported before, there is no plan to develop a mobile app.

### Describe your ideal solution to this problem

A PWA application where we can, including, use a pin or even the biometric to unlock.

### Teaching and learning

I don't have code skills, bu I think that this site can help: https://www.pwabuilder.com/

**Comment by youngcw** [comment]
I think the biggest hurdle left to an offline PWA is setting up a service worker.  That manifest is basically ready, but without the service worker only the app wont run offline.

**Comment by j-maas** [comment]
The main thing I desire to use offline is adding a transaction.

I like to add transactions on my phone right after spending money, so sometimes I'm not connected to the Internet. I still want to just add the transaction right away, since later I'll forget.
