### ISSUE TITLE
[Bug]: (v23.12.0) N26 with multiple spaces sync through GoCardless gives "something internally went wrong"

### ISSUE THREAD

**Issue by Arnoud-B** [actualbudget/actual#2061]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I have an N26 account with multiple spaces. When I set it up a few weeks ago with sync via GoCardless I ran into the "something internally went wrong" issue, but I don't think it appeared on every sync in the past weeks. Today it appeared again, and it seemed to be related to a transfer between a space and the main account because the transfer showed up twice in the space (transfer out and transfer in of the same amount, while it should only have been a transfer out).

So I unlinked all three accounts (main account + 2 spaces), I force closed the 2 spaces and recreated them, then linked everything up again through GoCardless. Then I received the "something internally went wrong" message 3 times in a row (see screenshot).

The data looks alright, but the transfers between the spaces and the main account are not recognized as transfers. When I tell Actual that it's a transfer, I get duplicates.

Now, a sync on the spaces gives no error, but a sync on the main account does still give the same error.

### What error did you receive?

![Screenshot 2023-12-11 at 13 06 40 (Actual)@2x](https://github.com/actualbudget/actual/assets/11488458/ac67b312-1481-451a-8582-d6cb2f6a352c)

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Safari

### Operating System

Mac OSX

**Comment by MatissJanis** [comment]
👋 I have N26 and have not observed any issues so far.

Do you have the server logs for the internal error you're experiencing?

**Comment by xocasdashdash** [comment]
@MatissJanis I'm seeing an error too but mine says:
```
Something went wrong {
  summary: "Couldn't update account transactions",
  detail: 'Access has expired or it has been revoked. To restore access reconnect the account.',
  status_code: 401,
  type: 'AccessExpiredError'
}

```

Right after i link the account in N26 website

**Comment by xocasdashdash** [comment]
I pinged gocardless and there's something wrong on N26 side and they're going to be reaching out to them.

**Comment by MatissJanis** [comment]
Great. Yes, this does seem to be on their end, so I'll close the issue.
