### ISSUE TITLE
[Bug]: New collapsed mobile view navigation bar is not user friendly

### ISSUE THREAD

**Issue by kyrias** [actualbudget/actual#2079]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

The new mobile view navigation by default hides the settings page in its expanded view, but there is nothing about the UI implies that it's possible to expand the navigation bar by swiping up.  To find where the settings page link was moved to I ended up having to search through the Discord history for a few minutes until I found references to expanding the menu.

(Matiss wanted this to be filed as a bug since it _is_ a pretty severe UX regression.)

### Where are you hosting Actual?

None

### Operating System

None

**Comment by joel-jeremy** [comment]
We should add a thin horizontal "pill"/"line" icon on top of the navigation bar to indicate that users can pull it up.

**Comment by joel-jeremy** [comment]
Example of what I mean as implemented by discord:
![Screenshot_20240105-204838](https://github.com/actualbudget/actual/assets/20313680/f7593fe3-ad1e-4ad1-93b6-6430a2cca4ff)
