### ISSUE TITLE
[Feature] More match options in rules

### ISSUE THREAD

**Issue by alekslyse** [actualbudget/actual#2083]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I found some older posts that said rules had the "contains" tab, so for example I could match "Amazon" and "Amazon 02.01.23" into one, so I dont have to manually make a rule for something that adds the date as a postfix. 

In my payee I only have a few options, but no option for contains, or any wildcards. Maybe I am blind, but im not sure how to make this a bit more dynamic
<img width="898" alt="Screenshot 2023-12-13 at 21 53 46" src="https://github.com/actualbudget/actual/assets/3678663/de06d5fd-8011-4ed8-af3f-3ba14d014952">

**Comment by youngcw** [comment]
look at the options under imported_payee

**Comment by alekslyse** [comment]
> look at the options under imported_payee

Thank you. Yes I was blind.

You dont happen to know how to set a rule to identify a account to account transfer when importing a transaction? I cant set category to transfer. Is it any way I should rename or setup the rule to get the system to understand its a local transfer? (both accounts are in  budget accounts)

**Comment by youngcw** [comment]
https://actualbudget.org/docs/budgeting/rules/custom
