### ISSUE TITLE
[Feature] Allow filtering out locked transactions when filtering by cleared field

### ISSUE THREAD

**Issue by Jackenmen** [actualbudget/actual#2087]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

After bank sync, new transactions can show up earlier in the transaction history (between other *locked* transactions) and I would like to be able to easily find them. Currently, they don't stand out when you have a long list of locked transactions and a single cleared but not locked transaction somewhere in that list.

### Describe your ideal solution to this problem

I would like to have a way to see only the cleared but not locked transactions using the filters. I suggest changing the current "Cleared" filter from "is true" and "is false" options to a multi-select ("one of") list allowing you to choose which of the "locked", "cleared", and "uncleared" states should be shown in the transaction list.

### Teaching and learning

It's an enhancement to the existing "Cleared" filter so discoverability stays just as easy as it already is.

**Comment by youngcw** [comment]
This isn't a filter but does this work for you? https://github.com/actualbudget/actual/pull/1994

**Comment by Jackenmen** [comment]
I think that a filter would still be preferable but the PR you linked could help, if it takes locked state into account, yes.

For now, though, #1994 doesn't actually take into account whether the transaction is locked or not, I left a comment about it:
https://github.com/actualbudget/actual/pull/1994#issuecomment-1856474882
I'm not sure what order would make it easier to spot, i.e. whether "locked" would be in the center such as in `locked,cleared,uncleared`, or at one of the ends such as in `uncleared,locked,cleared` or `locked,uncleared,cleared`.

**Comment by youngcw** [comment]
@Jackenmen Can this be closed?

**Comment by Jackenmen** [comment]
#2108 solved this, yeah.
