### ISSUE TITLE
[Bug]: Notes preview aren't going away sometimes

### ISSUE THREAD

**Issue by youngcw** [actualbudget/actual#2091]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Im starting to see the notes hover preview not go away sometimes.  The easiest way Ive found to make it happen is to have a few categories with notes, the move the cursor back and forth across the note icons.

This is an extreme case, but it gets the point across.
![image](https://github.com/actualbudget/actual/assets/28542559/1aeacf70-51fb-4cf3-a88c-bbe7052dbbe4)

### Where are you hosting Actual?

None

### Operating System

None

**Comment by Teprifer** [comment]
Can confirm I've observed this behaviour as well, latest release.

**Comment by youngcw** [comment]
Im not seeing this anymore.  I don't know if it was a messed up build or what.

**Comment by Kidglove57** [comment]
I’ve certainly seen it quite a bit in the past but not in the last week or two

**Comment by Teprifer** [comment]
I grabbed the latest edge, still having this issue.

**Comment by MatissJanis** [comment]
Good opportunity to move away from our `Tooltip` component to react-aria: https://react-spectrum.adobe.com/react-aria/Tooltip.html#tooltip

**Comment by joel-jeremy** [comment]
We should probably also consider replacing some of the components we use with the components provided by react aria

**Comment by youngcw** [comment]
Closing since Matiss is most of the way done with the react aria transition
