### ISSUE TITLE
[Feature] Export category groups in csv

### ISSUE THREAD

**Issue by Rebislori** [actualbudget/actual#2095]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I use Actual to keep track of the non-profit organization i manage, and i have to fill a balance with fixed categories, way too broad to be useful in daily accounting.

I'd like to use groups to fill these categories, and actual categories for a more detailed accounting.

### Describe your ideal solution to this problem

When exporting the csv, i'd like the "group" attribute to be in the csv too.

**Comment by mcalligator** [comment]
There's a related issue that could help with this: [[Feature] Support Importing/Exporting in Double-Entry Bookkeeping (plaintextaccounting) format. #3021](https://github.com/actualbudget/actual/issues/3021).  Whilst the output wouldn't be a CSV file, it would be an industry-standard format that inherently incorporates Category Groups in the way you've described.  What do you think?
