### ISSUE TITLE
[Feature] 'exchange rate' for gocardless synced accounts

### ISSUE THREAD

**Issue by rjwonder** [actualbudget/actual#2097]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I have accounts in multiple currencies, but work with 1 base currency. I found that it's possible to use a multiplier when importing csv's, but I dont think it's possible when syncing an account? 

### Describe your ideal solution to this problem

Possibility to indicate per account if a multiplier should be applied.

For me it doesnt have to be per transaction ( i wouldnt want it :)). Instead I use a fixed rate to sync all transactions. Just like the CSV version

**Comment by balintbekefi** [comment]
I'd love for this to be implemented. A simple solution would be to allow for multipliers in rules with "set amount" actions.
