### ISSUE TITLE
[Bug]: Adding transaction on iPad results in zero value

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#2105]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When adding a transaction on iPad and pressing enter the value is entered as `0.00` despite being completed

**Steps to replicate**

- Go to accounts register
- Press add new transaction
- Complete required fields 
- Fill in payment value
- Press enter

![image](https://github.com/actualbudget/actual/assets/22135084/d06b251f-050c-462d-99cc-5df2792b84e0)

If you press Add again the transaction is added a second time but this time with the value. 

![image](https://github.com/actualbudget/actual/assets/22135084/26ef94dd-c3ba-4845-b67f-dc5ee7432d4b)

The above screenshots are taken from Dev Mode in Edge but can be replicated on the iPad

### What error did you receive?

None

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Safari

### Operating System

Mobile Device

**Comment by joel-jeremy** [comment]
This seem to be a duplicate of https://github.com/actualbudget/actual/issues/1185 and is not limited to iOS.

**Comment by rich-howell** [comment]
Closing, this is a duplicate
