### ISSUE TITLE
[Feedback]: Toggle Switch

### ISSUE THREAD

**Issue by carkom** [actualbudget/actual#2107]
I've noticed that there's a few places in the app where we use a static "toggle" menu item but have no way to tell current state of that element (eg show/hide categories on budget page).

Current (both hidden and shown are the same):
![image](https://github.com/actualbudget/actual/assets/55785687/6387a89d-bf4e-4320-8226-e7dff91182e0)

A couple possible options here:
iconology:
<table>
  <tr>
    <td>Hidden</td>
    <td>Shown</td>
  </tr>
  <tr>
    <td><img src="https://github.com/actualbudget/actual/assets/55785687/7c7f960a-95f3-4a55-9f76-ed36fa7cd93f"></td>
    <td><img src="https://github.com/actualbudget/actual/assets/55785687/afc454b4-e5f3-447a-ab76-19f208c64061"></td>
  </tr>
  <tr>
    <td>OR also using dynamic text</td>
  </tr>
  <tr>
    <td>Hidden</td>
    <td>Shown</td>
  </tr>
  <tr>
    <td><img src="https://github.com/actualbudget/actual/assets/55785687/16463076-db2e-4692-aabb-091d6063f35b"></td>
    <td><img src="https://github.com/actualbudget/actual/assets/55785687/f1aa8259-222e-443f-b0ea-e9c2d8e33dd1"></td>
  </tr>
</table>

Dynamic Text (no icons):
<table>
  <tr>
    <td>Hidden</td>
    <td>Shown</td>
  </tr>
  <tr>
    <td><img src="https://github.com/actualbudget/actual/assets/55785687/cc4a5067-c80a-494d-bb0a-b4cd48e40e6a"></td>
    <td><img src="https://github.com/actualbudget/actual/assets/55785687/a4f2f208-19fe-4e7b-b441-c588a563367d"></td>
  </tr>
</table>
Toggle Switch (status follows toggle):
<table>
  <tr>
    <td>Hidden</td>
    <td>Shown</td>
  </tr>
  <tr>
    <td><img src="https://github.com/actualbudget/actual/assets/55785687/02f68359-f56c-4b33-aa08-7cdec526c5b1"></td>
    <td><img src="https://github.com/actualbudget/actual/assets/55785687/59b3d33e-d6e3-4d93-a6d7-f5c95e4c2433"></td>
  </tr>
  <tr>
</table>

**Comment by carkom** [comment]
Maybe there's other ideas or better implementation of any of the above options?

For me, I find the iconology options a bit difficult to understand. The Dynamic text is used often in other places of the app, I don't always like that the actual state of the element in question has to be inferred by the user (example voice in my head: "okay I have an option to show hidden categories, I guess that means that they are currently not shown"). So this leaves the toggle switch which has my vote. It's simple and quick to understand and use.

I'd love to hear everyone's thoughts and preferences. Please feel free to add other options or tweak the ones I have above.

**Comment by Teprifer** [comment]
I agree completely with your analysis.

Iconology contains too little visual differentiation, I at first thought you'd made an error in posting and put the same image in twice as I was only skimming images.

Dynamic text kinda works, but also it means there's effectively twice the UI options.

Toggle switch keeps the one UI element, is visually distinctive, is very instantly recognisable as a toggle(no mental processing). Also I like the splash of colour.

**Comment by jsehnoutka** [comment]
+1 for toggle switch!

**Comment by youngcw** [comment]
@carkom Do you need this to still be open?  If we want to add toggles places maybe we should open issues for those.

**Comment by carkom** [comment]
Implemented in #2174
