### ISSUE TITLE
[Feature] Duplicating a reconciled transaction without locking it

### ISSUE THREAD

**Issue by shall0pass** [actualbudget/actual#2110]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

When using the duplicate feature, I think it would be practical to not duplicate the cleared status if the transaction is reconciled and locked.  If there is a transaction that was reconciled and is not correct, that transaction needs to be deleted and recreated.  It would be a little less inconvenient if we could use the duplicate feature to recreate the transaction without the lock status.

**Comment by MatissJanis** [comment]
> If there is a transaction that was reconciled and is not correct, that transaction needs to be deleted and recreated.

Alternatively (and I know that this is controversial): we just let people to un-lock transactions. Seems like a much simpler solution to the problem.

**Comment by shall0pass** [comment]
> > If there is a transaction that was reconciled and is not correct, that transaction needs to be deleted and recreated.
> 
> Alternatively (and I know that this is controversial): we just let people to un-lock transactions. Seems like a much simpler solution to the problem.

I'm coming around on this.  There isn't much of a difference between invalidating the reconciliation by unlocking a transaction vs invalidating it by deleting a transaction.
