### ISSUE TITLE
[Bug]: Scheduling end of the month doesn't seem to be able to deal with February

### ISSUE THREAD

**Issue by glowtape** [actualbudget/actual#2129]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Noticed while toying with the forecasting PR #2126.

Seems like the scheduler skips the month of February, if you have something scheduled beyond the 28th or 29th. My salary is scheduled on the 30th of each month, before the weekend. I noticed in the graph of the PR above that income was missing. Then I checked the actual schedule and it happens there, too:

<img width="499" alt="schedule" src="https://github.com/actualbudget/actual/assets/4010813/10a94d6b-e445-4735-b225-ded4d2d3d1d5">

Thanks for looking into this.

### Where are you hosting Actual?

NAS

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

**Comment by glowtape** [comment]
Issue is resolved. When selecting specific days, you can define "Last" that does the job.

**Comment by jfdoming** [comment]
> Issue is resolved. When selecting specific days, you can define "Last" that does the job.

Technically I think this doesn't work if you actually have a recurring schedule on the 29th. But for most cases "Last" should work if you don't care about being super accurate
