### ISSUE TITLE
[Bug]: Opening 'Payees' page results in 'Fatal Error'

### ISSUE THREAD

**Issue by erichobson** [actualbudget/actual#2130]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Whenever I try to access the `/payees` page of my actual instance, I end up with a `Fatal Error` page describing an unrecoverable error in the UI. It happens whenever I try to click the `Payees` option in the menu or the `Manage Payees` in an account. I've attempted to restart the application, recreate the Docker container, and reset any cache option I've seen. Worst case, I can try to export the information and import into a new actual instance if helpful.

### What error did you receive?

![image](https://github.com/actualbudget/actual/assets/77306238/5dcc101f-a46a-4e6e-88b9-cc6c4ab690e8)

```
sz/<@https://domain.tld/static/js/main.ea4c7a17.js:200:307233 
sS@https://domain.tld/static/js/main.ea4c7a17.js:42:97465 
sN@https://domain.tld/static/js/main.ea4c7a17.js:42:104913 
sL@https://domain.tld/static/js/main.ea4c7a17.js:42:104753 
sZ@https://domain.tld/static/js/main.ea4c7a17.js:42:104287 
lP@https://domain.tld/static/js/main.ea4c7a17.js:42:114357 
lD@https://domain.tld/static/js/main.ea4c7a17.js:42:113697 
lh@https://domain.tld/static/js/main.ea4c7a17.js:42:109105 
k@https://domain.tld/static/js/main.ea4c7a17.js:109:1548 
M@https://domain.tld/static/js/main.ea4c7a17.js:109:1911 
```

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Operating System

Windows 11

**Comment by Teprifer** [comment]
Are you using the edge version? Saw this earlier: #2128

**Comment by erichobson** [comment]
> Are you using the edge version? Saw this earlier: #2128

I am, yes - didn’t realize that. I’ll try reverting to a release build and see if I have the same issue.

**Comment by MatissJanis** [comment]
Fixed by https://github.com/actualbudget/actual/pull/2128
