### ISSUE TITLE
[Bug]: Error when applying budget templates

### ISSUE THREAD

**Issue by gms461** [actualbudget/actual#2137]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When attempting to apply goal templates using the "Apply budget templates" menu item, I receive an error rather than seeing the budget amount populate as I would expect. I confirmed that my budget templates pass the "check" so it shouldn't be due to any issues with my syntax.

### What error did you receive?

Something internally went wrong. You may want to restart the app if anything looks wrong. Please report this as a new issue on Github.
<img width="529" alt="image" src="https://github.com/actualbudget/actual/assets/15148087/1365b783-3a0f-4fe7-a51f-17214a46984e">

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Safari

### Operating System

Mac OSX

**Comment by youngcw** [comment]
Do you know which of your templates is causing the issue?

**Comment by gms461** [comment]
It happens if I select "Apply all templates" but it also happens for every individual line I try to select and apply templates for, so I'm not sure it's template specific.

**Comment by youngcw** [comment]
Can you try your budget file on demo.actualbudget.org and see if the issue is still there?

**Comment by gms461** [comment]
It has inexplicably fixed itself. 🤷‍♀️ Not sure what happened.
