### ISSUE TITLE
[Bug]: Cannot add new Transaction on mobile in vertical orientation

### ISSUE THREAD

**Issue by upbeat-eggplant** [actualbudget/actual#2139]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

On mobile devices the "Add New" button is hidden when the screen is to small in portrait orientation. To add a new transaction the phone has to be rotated to be horizontal. I think this is a bug because it makes adding transactions from phones considerably more difficult. Possibly related to #2079.

Phone is held normally.
![IMG_FE2933DD14C0-1](https://github.com/actualbudget/actual/assets/130395888/d13c9a33-829e-4ae4-b0d8-2f159b3a92cf)

Phone is horizontal.
![IMG_F344ECE71A9F-1](https://github.com/actualbudget/actual/assets/130395888/548eb7bf-f335-4005-a399-d8d52a064e4f)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Safari

### Operating System

Mobile Device

**Comment by upbeat-eggplant** [comment]
Sorry about this, my fault.

**Comment by joel-jeremy** [comment]
Is this still an issue? What version are you using?
