### ISSUE TITLE
[Bug]: Insufficient detection of number delimiter in CSV import

### ISSUE THREAD

**Issue by lkempf** [actualbudget/actual#2143]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

My bank uses csv files with `;` as a delimiter and `,` as a comma in amounts. When importing the csv via the UI I can select the correct csv delimiter but the number delimiter seems to be selected automatically. This work in almost all cases. But for exact amounts, e.g. `1.000` the detected amount is 1.00, not the correct 1000. For inexact amounts, e.g. `1.111,11` the correct delimiter is selected.

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

**Comment by MatissJanis** [comment]
👋 Could you please provide an example CSV file so folks could reproduce it?

Thanks!

**Comment by MatissJanis** [comment]
Closing due to lack of information.
