### ISSUE TITLE
[Bug]: Split transactions

### ISSUE THREAD

**Issue by ActivelyPassive** [actualbudget/actual#2146]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Once a split transaction is submitted you can no longer edit it to add more categories.

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Safari

### Operating System

Mac OSX

**Comment by youngcw** [comment]
You can add more categories by editing either the total balance to be higher, or editing the existing split entries to not fill the full split amount.
