### ISSUE TITLE
[Feature] Add Notes / Remarks to monthly budget

### ISSUE THREAD

**Issue by gathurian** [actualbudget/actual#2150]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

It would be great if you could add little notes or remarks to the monthly 'spent' amount of your budgeted categories. 
For example if you budgeted $500 for your 'hobby' category and at one month suddenly spent $2000, then you could just add a little note that says why, e.g. 'Yearly golfing club membership' or something.

(example with my - VERY LIMITED - Krita skills)

![image](https://github.com/actualbudget/actual/assets/22455777/ebe1073c-f033-4dfc-9029-9b1e51c7a6ae)

### Describe your ideal solution to this problem

Actual already has the functionality to add notes to categories as a whole. Could this be expanded to also include notes on the 'spent' column that resets every month?

![image](https://github.com/actualbudget/actual/assets/22455777/9e223f9c-f2c2-4312-8f22-9d8ca92f4bfd)

**Comment by psybers** [comment]
Does the ability to add notes to the individual budget month suffice?

<img width="280" alt="image" src="https://github.com/user-attachments/assets/ff60dac2-e913-4ef0-85af-8f71ab82cfff">
