### ISSUE TITLE
[Feature] Add available category balance to mobile category autocomplete chooser

### ISSUE THREAD

**Issue by shall0pass** [actualbudget/actual#2158]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

When manually entering a transaction on mobile, it's useful to see how much is remaining in a category while selecting one. 

### Describe your ideal solution to this problem

It would be helpful if the category balance were shown (right justified) in the autocomplete drop down.

**Comment by youngcw** [comment]
I think this is added now.  Can we close this?
