### ISSUE TITLE
[Bug]: Failed loading available banks: GoCardless access credentials might be misconfigured. Please set them up again.

### ISSUE THREAD

**Issue by ShooTeX** [actualbudget/actual#2159]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Tried to use GoCardless but it fails when trying to load banks. I'm pretty sure the credentials are correct. I also tried to regenerate them and it didn't work. I used GoCardless before in FireFly III.

### What error did you receive?

![image](https://github.com/actualbudget/actual/assets/10850738/65762448-0f02-4275-9aea-4ce7b56f7314)

```
https://......../gocardless/get-banks 500

{"status":"error","reason":"internal-error"}

cn @ https://......../kcab/kcab.worker.676aa69de34599d64b7b.js:130
EI.gocardless-get-banks @ https://......../kcab/kcab.worker.676aa69de34599d64b7b.js:247
aG @ https:/......../kcab/kcab.worker.676aa69de34599d64b7b.js:16
(anonymous) @ https://......../kcab/kcab.worker.676aa69de34599d64b7b.js:16
```

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by mskothari07** [comment]
From where can we get the correct cred

**Comment by ShooTeX** [comment]
> From where can we get the correct cred

https://actualbudget.org/docs/advanced/bank-sync

**Comment by ShooTeX** [comment]
Sorry about that, the issue was some misconfiguration with my DNS server.
