### ISSUE TITLE
Add date format for The Netherlands, India, Ireland, Malaysia and Portugal [Feature] 

### ISSUE THREAD

**Issue by vinstaal0** [actualbudget/actual#2162]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

The dateformat MM-DD-YYYY is not included.

### Describe your ideal solution to this problem

add the dateformat

### Teaching and learning

It's a setting

**Comment by Jackenmen** [comment]
Hi, did you mean DD-MM-YYYY rather than MM-DD-YYYY? That's what you said in #2160 and I think it's the actual format that's used in those countries.

**Comment by vinstaal0** [comment]
Ow yeah, edited the post. The US influences on the internet are fucking up my date formats
