### ISSUE TITLE
[Feature] Budget: Add groups for incomes as well

### ISSUE THREAD

**Issue by chevdor** [actualbudget/actual#2165]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

First of all, thanks for this wonderful project !

I am suprised to see we can create category groups for expenses but that does not seem possible for incomes in the budget page.

Did I miss this an option to enable this features ? Is there a reason for it to be missing ?

### Describe your ideal solution to this problem

Implement category grouping for incomes just like done for expenses.

### Teaching and learning

I think that it is self documented as long as the `Add Group` button shows up under incomes as well.

**Comment by Kidglove57** [comment]
I think it’s more that we need a developer motivated to take up the challenge of adding this! It’s my personal view only but I would like to see grouping for (a) account types and (b) income categories.

The formerly subscription based app that went open source did not have income category groups and there have been so many things to add since then!

**Comment by chevdor** [comment]
I see, I just wondered why this has been implemted asymmetric for the budget with groups for the expenses and none for the incomes. I saw the issues regarding the accounts, which sounds also like a nice feature but this is probably a bigger one than doing things similarly for expenses and incomes.

**Comment by Kidglove57** [comment]
Yes, I see your point. I suppose we would have to ask the original dev to be sure. A lot of our users probably don’t have a large number of different income sources whereas they do have a significant number of expense types - but I’m only guessing.

As an aside, our biggest “paid for rural” (YNAB - You need a budget) for example has no income categories at all. Just an available to budget income figure. 

But yes I do agree with your feature request.
