### ISSUE TITLE
[Bug]: Deactivated Keytrade Bank (BE) account

### ISSUE THREAD

**Issue by tjorim** [actualbudget/actual#2179]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I want to add a new account. I pick "Link bank account with GoCardless". The bank is in Belgium, called Keytrade Bank. After (successfully) authorizing it through GoCardless I end up in Actual again where it keeps spinning. Checking the Docker log (running in Unraid) I found the error below.

Last year I had a joint account that is now closed (and not visible in their bank app). However, I also have a new bank account I want to connect to. Connecting on the GoCardless dashboard works just fine and shows me both accounts and their corresponding transactions.

Preferably it (Actual) just fetches all data available to get a better spending history. If not possible, skip the (probably) first (deactivated) account and continue with the second one. In the current situation it does nothing and keeps spinning.

### What error did you receive?

```

    data: {
      summary: "Couldn't update account details",
      detail: 'Account has been deactivated or it no longer exists.',
      status_code: 401,
      type: 'AccountInactiveError'
    }
```

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Operating System

Windows 11

**Comment by MatissJanis** [comment]
👋 Did you previously link the deactivated account to Actual? If yes: could you try un-linking it and seeing if that solves the problem?

**Comment by tjorim** [comment]
No, this is a clean/fresh/new install. First time set up and other banks work.

**Comment by MatissJanis** [comment]
I see. My recommendation here is to reach out to GoCardless support. AFAIK there's nothing we could do in Actual to fix the 401 error you are receiving from GoCardless.

**Comment by tjorim** [comment]
It should just skip the first account and get data from the second one. They're linked to the same login details. Also, even though the account is closed, the transactions are apparently still available for 6 months.

**Comment by tjorim** [comment]
@MatissJanis Issue still persists. I can simply access the data through the GoCardless Bank Account Data website when testing. The bank account is indeed inactive but there are multiple accounts linked to a single user... Anyway, I reached out to them and will post their reply here.
