### ISSUE TITLE
[Bug]: App crashes when trying to edit an automatically created rule

### ISSUE THREAD

**Issue by JodliDev** [actualbudget/actual#2180]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Hello, I really hope this was not reported before. It was kind a hard to search for the problem, but manually scrolling through the issues does no seem to bring up anything :)

After updating to the most recent version (I might have been on version v23.11.0 or v23.12.0 - I am unsure). The app seems to crash when trying to edit a rule that was automatically edited.
Creating rules manually, seems to work fine.

Steps to reproduce:

- Rename the Payee-name of a unique entry. 
- The message about merging the payees pops up
- Hit "Merge and edit rule"
- The app crashes with a fatal error
Now, when trying to edit the rule that was automatically created, the app always crashes.

Thank you for your hard work! :)

### What error did you receive?

Fatal Error
There was an unrecoverable error in the UI. Sorry!

Stacktrace from the error console:
```
Error: value can be string only if strict = false
    n4 Autocomplete.tsx:41
    children Autocomplete.tsx:659
    renderInput Autocomplete.tsx:658
    children Autocomplete.tsx:419
    e downshift.esm.js:1377
    React 12
    k scheduler.production.min.js:13
    M scheduler.production.min.js:14
[react-dom.production.min.js:189:29](https://budget.jodli.me/node_modules/react-dom/cjs/react-dom.production.min.js)
```

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

**Comment by MatissJanis** [comment]
I think https://github.com/actualbudget/actual/pull/2207 will fix this. Could you please verify on https://demo.actualbudget.org/ ?

**Comment by yoyotogblo** [comment]
> I think #2207 will fix this. Could you please verify on https://demo.actualbudget.org/ ?

Just tested it and looks like this fixed it. Thanks!
