### ISSUE TITLE
[Feature] API call for getting account balance

### ISSUE THREAD

**Issue by MirariFang** [actualbudget/actual#2189]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Hi there, I'm trying to implement my own tools to interact with the Actual, but I didn't find any API calls that could simply give me the total balance of an account. Although I probably could just get all transactions with a super early starting date and sum them up, it's a little bit more tedious than getting the value in one go. 
Just curious, is this intentional by design? Why the `Account` object can't simply include a "balance" field? Or am I missing anything?
Thanks.

### Describe your ideal solution to this problem

Add `balance` field to `Account`, which has the current balance value of that account.

**Comment by turt2live** [comment]
In the meantime, developers can use the [ActualQL] feature:

```js
// Get balances for all accounts as of a certain date
const balancesAllAccounts = (await runQuery(q('transactions')
    .filter({ date: { $lte: '2024-03-31' } })
    .groupBy('account.id')
    .select(['account.id', 'account.name', {balance: {$sum: "$amount"}}])
)).data;

// Get balance for a single account as of a certain date
const balanceMyAccount = (await runQuery(q('transactions')
    .filter({
        date: { $lte: '2024-03-31' },
        'account.id': 'YOUR-ACCOUNT-UUID-HERE',
    })
    .select(['account.id', 'account.name', {balance: {$sum: "$amount"}}])
)).data;
```

If you need the current balance as of 'today', either put that date into the filter or remove that condition entirely.
