### ISSUE TITLE
[Bug]: Sync icon is missing on Mobile view

### ISSUE THREAD

**Issue by shall0pass** [actualbudget/actual#2200]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I no longer see the sync icon in either 24.1.0 or the edge build from Jan-7, 2024 in the Mobile view.

### Where are you hosting Actual?

NAS

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Mobile Device

**Comment by joel-jeremy** [comment]
The sync button in mobile view has been replaced by A "pull down to refresh" functionality. You can now pull down on the budget table to sync your budget.

**Comment by shall0pass** [comment]
I'll close this in light if that, but I will miss the feedback of whether I'm connected and syncing or not.
