### ISSUE TITLE
[Bug]: PWA - Date of a new transaction can't be different than today's date 

### ISSUE THREAD

**Issue by pascalxricher** [actualbudget/actual#2203]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I updated to new latest version and tried to add a new transaction using the PWA.

Regardless of the date I set, the date of the day is persisted.

If I update the transaction using the PWA, the date of the day is always persisted.

If I switch to the desktop version, I can update the date to a date different of today's date.

This seems to be a regression with the previous version.

### What error did you receive?

The wrong value is saved.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mobile Device

**Comment by Kidglove57** [comment]
At the moment I am struggling to reproduce this. I have added four test transactions. Some in Safari and some on Chrome, all in mobile mode (PWA) on iOS17.

 I filled out the amount, payee, category and account. I then clicked date and altered it to 6 January - then Add Transaction. All transactions got added correctly on 6 January.

I am mentioning this in case for some reason it is Mobile OS specific?

**Comment by HansiWursti** [comment]
I can replicate it in Firefox on Desktop  when resizing the browser to go to mobile view.

Change the date but the field is still focused with a purple border and then directly click save transaction.
The date then is the date it was when i entered the field and it got the purple border.

iOS i can not test.

**Comment by pascalxricher** [comment]
Ok, I understand what I did wrong... In the PWA, when I did these steps with the previous version, the date was correctly updated, contrary of the newest version :

1) Go in an account.
2) + sign to add a transaction.
3) Specify the amount.
4) Specify the category.
5) Click the date field, select a date in the past, and click the 'configure' button to confirm the date.
6) Leave the focus on the date field.
7) Click on Save.
8) The saved date is the date of the day instead of the selected date. In the previous version, the selected date was save even if the focus was on the field.

It's probably then NOT a bug, but a change in how to use the screen...

**Comment by Kidglove57** [comment]
I have tried again and again on iOS (in portrait mode/mobile view)  and I’m still not seeing this. Whenever and however I change the date of the new transaction it always sticks. I’m also slightly puzzled in that I see “Add Transaction” and not “Save”.

**Comment by joel-jeremy** [comment]
The way the fields work in the mobile transaction page is that they need to be put out of focus in order for the new values to be applied. Meaning, click/tap out of field after editing it so that it is not focused and then proceed to save/add the transaction.
