### ISSUE TITLE
[Bug]: Swapped the volume on my container. When I restarted with original volume, my budgets are missing

### ISSUE THREAD

**Issue by malewpro** [actualbudget/actual#2205]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I am working on migrating my docker volumes to a more readily accessible and reliable storage system. As a part of doing this for Actual, I copied the data from /actual/data in the volume mounted to the container to the new file system. When I started with the new volume, the web UI prompted me to create a new password and a new budget as though this was a first installation. I figured I did something wrong with the migration and stopped the container, reset the volume to the original one I had been operating on, and restarted the container. I was greeted with the same "create a password" prompt and was sent to the blank budget that was created a moment ago.

I can see the original .blob and .sqlite files in the docker volume folder, but the web app doesn't show them in the list of files. I have tried clearing my cache and loading the page on multiple different browsers.

I have slightly outdated backups of my budgets saved and I suppose I could just import those, but I would like to understand what went wrong here so I can prevent it in the future. 

### What error did you receive?

I didn't receive a specific error message but the budgets that still exist in the original docker based volume no longer appear in the web app. 

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari

### Operating System

Mac OSX

**Comment by MatissJanis** [comment]
👋 This isn't really a bug report and we don't use github issues for support.

Please send a message in the community discord. People _might_ help out there.
