### ISSUE TITLE
[Bug]: Report budget rollover spend summary wrong?

### ISSUE THREAD

**Issue by mk-french** [actualbudget/actual#2210]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Is it just me or do the summary values make little sense when a category has rollover spend enabled in the 'Report budget'?

No rollover enabled - summary values are correct.
<img width="734" alt="Screenshot 2024-01-10 at 7 13 14 am" src="https://github.com/actualbudget/actual/assets/6534113/ff603adf-22fb-40d0-807d-5be95ff3b9d5">

Rollover enabled on 'Food' and summary values are misleading?
<img width="734" alt="Screenshot 2024-01-10 at 7 13 57 am" src="https://github.com/actualbudget/actual/assets/6534113/95b192d8-7d1e-4c04-a4b6-8774e89782ef">

I would expect the summary to show exactly what happened that month, as is shown in the group summary. I.e. What was spent = SUM of all category spends for that month. I can see how we get to -850 (250 + -1,100), it's offsetting the spend in the current month with the rollover balance, which to me doesn't really make sense.

Following that, the summary figures in Feb are also odd... $250 budgeted, $250 rolled over, $500 spent = balance of $0 (okay) but spend = $0 of $250? 
I see this is because rollover is also enabled for Feb and the 0 floor is preventing the $-250 from summing up:
`return carryover
        ? Math.max(0, safeNumber(number(budgeted) + number(sumAmount)))
        : sumAmount;`

Removing the rollover in Feb results in a more correct summary:
<img width="733" alt="Screenshot 2024-01-10 at 8 39 33 am" src="https://github.com/actualbudget/actual/assets/6534113/b7b522cf-7401-49af-9c20-32949e50db34">
But the January rollover is excluded...

So where should the rollover be included? As a deduction on the spend in the subsequent month or an increase to the budget? Or perhaps neither - should it just remain in the balance column and not affect the summaries at all?

Thoughts?

### Where are you hosting Actual?

None

### Operating System

None

**Comment by youngcw** [comment]
In my opinion rollover should be disabled in report budget. The docs do say that this will happen, but it's still really confusing.

**Comment by mk-french** [comment]
Ah yes! Is [this](https://actualbudget.org/docs/experimental/report-budget#how-money-rolls-over) what you're referring to @youngcw?:

> If you utilize the Rollover Overspending feature on a category that is not over spent, the entire spent amount will be forwarded to the next month and the Saved amount will increase for the current month.

Here's the effect on the summary expense (and therefore the saved amount) when rolling over:
Category Overspent - Entire expense is ignored in summary
Category Underspent - Expenses are decreased by the amount **budgeted** for that category

In both cases the balance is carried onto the balance of the next month, but does not affect the next month summary in any way...

Is this true to the docs? And more importantly, does it make sense to anyone?

I take your point that rollover in report budgeting is confusing but I do find it handy in some instances! It gives the ability to track a budget over a few months when the transactions are a bit more inconsistent.

Personally, in the summary I would like to see the expenses as it was in the month and any rollover just be carried onto the next months balance for that category. That makes the most sense to me... This way the summary is still accurate for that month and rollover affects only the rolling balance for that category.

**Comment by youngcw** [comment]
Closing for now.  I may add a ticket in the docs to make this more clear why the math is strange.
