### ISSUE TITLE
[Proposal] Package desktop app as flatpak and publish on flathub.org

### ISSUE THREAD

**Issue by subnut** [actualbudget/actual#2213]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Flatpaks are now becoming the mainstream method of installing software on linux
- It is used by GNOME's Software app for discovering & installing software
- Many immutable linux distros recommend using flatpaks instead of installing via package managers
- Flatpaks allow sandboxing of the running app

https://flathub.org is the de-facto repository for flatpak-packaged software.

### Describe your ideal solution to this problem

The desktop client of Actual is packaged as a flatpak application and distributed on flathub.org

Here are some links that might be helpful -
- https://docs.flatpak.org/en/latest/first-build.html
- https://docs.flatpak.org/en/latest/electron.html
- https://www.electron.build/configuration/flatpak.html
- https://www.electronforge.io/config/makers/flatpak
- https://www.electronforge.io/core-concepts/why-electron-forge

**Comment by youngcw** [comment]
I think this will be the best path forward once we are publishing apps.  There is work ongoing right now to publish to the mac app store, and I believe its planned to publish on the windows apps store as well.

**Comment by deathblade666** [comment]
if it's helpful, here is the docs on how to publish to flathub, according to the their publishing docs you can also use you're own flatpak repo if perferred (flathub would be more accessible though.
https://docs.flathub.org/docs/for-app-authors/submission/

**Comment by MikesGlitch** [comment]
This is on its way: https://flathub.org/en/apps/com.actualbudget.actual

Marking as done. An official announcement will come soon.
