### ISSUE TITLE
[Feature]  request for a piggy bank feature

### ISSUE THREAD

**Issue by tappeh** [actualbudget/actual#2218]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

no piggybank in actualbudget

### Describe your ideal solution to this problem

piggybank where you can put an item you wish to save up for and you can put money in it and it shows your progress in how close you are to getting it

**Comment by gael-vanderlee** [comment]
@youngcw I’m interested in this feature, but I need some clarification.

When I add a category, does it apply to all budgets, including past and future ones? For example, if I'm currently saving for a new phone and create a "phone" piggy bank, I want to track my progress. Seeing the piggy bank fill up is motivating and satisfying. Once I reach my goal, say in 3 months, and buy the phone, the category shouldn't exist anymore. It doesn't make sense to have a "phone" category before I decide to save for it or after I've made the purchase.

Am I understanding this correctly? It seems like the current category system doesn’t fit the "piggy bank" concept I’m looking for. Let me know if I'm missing something!

**Comment by youngcw** [comment]
@gael-vanderlee Categories will exist in all months once you add a new one.  If you have categories that you don't need anymore you can either hide it, or delete it and transfer all the spending/budgeting into a different category.  Some people choose to not ever delete the categories, just hide them so they have a history of all the things they successfully saved for.  

Templates have been extended to have a `goal` option where you can define a goal amount that you are saving towards.
