### ISSUE TITLE
[Feature] All Accounts view is missing "cleared" checkbox

### ISSUE THREAD

**Issue by yoyotogblo** [actualbudget/actual#2220]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Individual accounts transaction registers have the option of showing "cleared" checkboxes but that's missing from the "All accounts" view. I can't think of a reason why it shouldn't be an option there also.

### Describe your ideal solution to this problem

"All accounts" should also have the option to show "cleared" checkboxes

**Comment by Jackenmen** [comment]
There's also no running balance field, I guess it could be because these are especially useful during reconciliation, and doing reconciliation from the all accounts view is unlikely? Still, I would definitely want to see the running balance in all accounts view, clearing transactions would be nice to have too.

**Comment by yoyotogblo** [comment]
I can understand why there's no running balance. If you have 3 accounts, what does it mean to have a running balance? I guess it could be a running balance of your overall accounts (almost your wealth status cash wise). But I understand why that's not typically the concept.

You should be able to clear transactions from the all accounts view. If you can enter transactions there, you should also be able to clear them there

**Comment by Jackenmen** [comment]
> If you have 3 accounts, what does it mean to have a running balance

It means the running balance of the account the transaction relates to. At least that's how all accounts view works in my bank and it makes a lot of sense to me. this way

**Comment by Teprifer** [comment]
This is present in the latest release, so can probably have the need more votes tag removed.

![image](https://github.com/actualbudget/actual/assets/34882928/4643ab1b-20ed-4174-a7de-37fdcf111706)
