### ISSUE TITLE
[Bug]: Dark Theme - wrong color in schedule date settings

### ISSUE THREAD

**Issue by youngcw** [actualbudget/actual#2223]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

This before/after weekend selection is not getting the color set right.  It should match the other buttons/selections
![image](https://github.com/actualbudget/actual/assets/28542559/f000a7c5-23c6-4e7c-a21c-094f6c10da83)

### Where are you hosting Actual?

None

### Operating System

None

**Comment by pranay911** [comment]
Could you please assign this bug to me?

**Comment by youngcw** [comment]
@pranay911 If you would like to work on the issue just put in a PR.  We don't assign issues here.

**Comment by pranay911** [comment]
![image](https://github.com/actualbudget/actual/assets/65008142/82d4e36d-2abc-4728-8b1a-ded92a32c809)
@youngcw Hi, I can't find any Repeat every dropdown can you please mention the path?

**Comment by youngcw** [comment]
@pranay911 you have to open the schedule date settings

**Comment by pranay911** [comment]
can u please share with me the steps to open the schedule date settings
