### ISSUE TITLE
[Bug]: Error importing transactions from 1 bank account

### ISSUE THREAD

**Issue by marcdacosta-UoS** [actualbudget/actual#2229]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

A bug happened! Transactions on all of my other accounts with the same bank sync correctly, but one account doesn't. I get an error message: "There was an internal error. Please get in touch https://actualbudget.org/contact/ for support"

### What error did you receive?

There was an internal error. Please get in touch https://actualbudget.org/contact/ for support

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Operating System

Windows 11

**Comment by MatissJanis** [comment]
👋 Would you mind checking server logs to see what error message you can see there?

**Comment by marcdacosta-UoS** [comment]
Hi,

Thanks for the fast reply. When I click to sync the problem account in the
webpage, I still get the error message and no transactions displaying:
[image: image.png]

Interestingly, in the docker container logs I can see the timestamp for my
attempted sync and the latest transactions for that account. However, I
can't actually see any obvious error messages:

[image: image.png]

Thanks,
Marc

**Comment by MatissJanis** [comment]
What information are you seeing in the server logs? I would appreciate if you could share the full JSON. Feel free to redact some values in it for privacy.

Please also look at the client console and see what error is visible there (if any).

Thanks

**Comment by marcdacosta-UoS** [comment]
Hi,

Sorry, how do I find the server logs?

Thanks

**Comment by MatissJanis** [comment]
That really depends on how you have hosted `actual-server`. There's not much we can help here unless you are able to provide both the server and client logs.

**Comment by marcdacosta-UoS** [comment]
Hi,

Thanks for your reply. I'm running it in Docker Desktop on Windows 11. The
only server log I can find is the Docker container log:

[image: image.png]

Is this the correct server log to send?

When I look at the problem account, the browser console log says:

 [Exception] TypeError: Cannot read properties of undefined (reading
'toLowerCase')
    at pz (index.ts:33:6)
    at _E (sync.ts:332:9)
    at async _T (sync.ts:402:42)
    at async sync.ts:833:22

[image: image.png]

Thanks

**Comment by MatissJanis** [comment]
Can you send the server logs as text instead of an image? The images do not show up in github (please open up github instead of replying via email).

**Comment by marcdacosta-UoS** [comment]
Apologies - I didn't realise that pictures from email don't display in Github.

Here is the console log from my browser (Chrome) when trying to sync the problem account:

Reading meta...
fced0245-2ff6-4e22-a941-01f28e3ac72e:1 Got meta for documents-Actual-My-Finances-7ca9631-db.sqlite: {size: 372736}
sql-wasm.wasm:0xf734f Opened!
sheet.ts:153 Loaded spreadsheet from cache (848 items)
index.web.ts:5 Syncing since 2024-01-15T18:23:09.967Z-0014-bb3810b85e747d5b 0 (attempt: 0)
index.web.ts:5 Got messages from server 0
index.web.ts:5 Syncing since 2024-01-15T18:23:09.967Z-0014-bb3810b85e747d5b 0 (attempt: 0)
index.web.ts:5 Got messages from server 0
index.web.ts:4 [Exception] TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at pz (index.ts:33:6)
    at _E (sync.ts:332:9)
    at async _T (sync.ts:402:42)
    at async sync.ts:833:22
index.web.ts:5 Syncing since 2024-01-15T18:23:09.967Z-0014-bb3810b85e747d5b 0 (attempt: 0)
index.web.ts:5 Got messages from server 0
index.web.ts:5 Syncing since 2024-01-15T18:23:09.967Z-0014-bb3810b85e747d5b 0 (attempt: 0)
index.web.ts:5 Got messages from server 0

As for the server logs, I'm running actual-server in Docker Desktop on Windows 11. The only server log I can find is the Docker container log:
![image](https://github.com/actualbudget/actual/assets/54032450/44027111-add5-4048-bf3a-43557b3c0ac8)

Is this the correct server log to redact and send? 

Thanks

**Comment by MatissJanis** [comment]
Thanks. I believe I've patched the issue in #2238. Would you mind connecting your server to the demo link provided there (in comments) and seeing if your issue is fixed there?

(this will not store your data on Actuals servers; your data will still be both local and stored on your server)

**Comment by marcdacosta-UoS** [comment]
That's worked. Thank you very much!
