### ISSUE TITLE
[Feature] PWA (Progressive web app) support

### ISSUE THREAD

**Issue by edersong** [actualbudget/actual#2232]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

It would be a nice feature to be able to install the website as an app on Android and iOS.

Ref.: https://blog.heroku.com/how-to-make-progressive-web-app 

### Teaching and learning

https://blog.heroku.com/how-to-make-progressive-web-app

**Comment by shall0pass** [comment]
You should find that a lot of the groundwork for this is already complete, though a fully offline experience isn't possible yet.  Looking forward to any PRs you might submit.

**Comment by youngcw** [comment]
closing in favor of #2060
