### ISSUE TITLE
[Feature] Group multiple transactions into a split transaction

### ISSUE THREAD

**Issue by joel-jeremy** [actualbudget/actual#2234]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Allow users to select multiple transactions and have an option to group the transactions into a split transaction:
![image](https://github.com/actualbudget/actual/assets/20313680/26cf5983-7a2d-4a62-af8c-fea655a4ad91)

Selected transaction would then be turned into a split transaction:
![image](https://github.com/actualbudget/actual/assets/20313680/43ff2685-c005-4759-971d-27fc40e99327)

### Describe your ideal solution to this problem

Allow users to select multiple transactions and have an option to group the transactions into a split transaction

**Comment by Nyanino** [comment]
Would be great if the opposite was also true, split a transaction into multiple.
