### ISSUE TITLE
[Bug]: API docs incorrect

### ISSUE THREAD

**Issue by paulocr** [actualbudget/actual#2235]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Hello,

I am a new user and have started playing out with the API in order to migrate from a custom system I developed for my own use. I have encountered a couple methods here and there that are listed in the documentation in the API reference https://actualbudget.org/docs/api/reference but that actually do not exist in the package.

If PRs are welcome I am happy to do a review and submit one.

Thanks!

### Where are you hosting Actual?

Docker

### Operating System

None

**Comment by paulocr** [comment]
Ugh, I guess I just realized that the API reference says in the first paragraph that it's a work in progress. Apologies, just jumped directly into the methods!

**Comment by youngcw** [comment]
Feel free to put in PRs to help improve things
