### ISSUE TITLE
[Bug]: Lost file after update

### ISSUE THREAD

**Issue by jamisonhill** [actualbudget/actual#2236]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I saw a notice in my app that a server update was available.  It was just a dot release so likely not an essential update.  I run Actual in Docker so I pulled the latest and ran it again, but it asked me to enter in my server URL and then create a new password.  It didn't have any option to login, only the new password option.  I am still accessing the same server at the same address as before the update.  When I completed the new password action, it loaded my budget, but only the one I most recently had open.  I had another file that I would typically go to by choosing to "close file" and selecting the other, but now that file is no longer available.  That was my daughter's budget and as much as I would like to hope she did regular backups by exporting her file like I do for mine, alas she has not done so.  Is there any way to point Actual back in some way to the original files that I had shown prior to the update?  In the screenshot you can see that only 1 of my 2 files are showing now.  Please help if there is a way to solve this.  Thanks.

<img width="536" alt="Screenshot 2024-01-16 at 3 10 12 PM" src="https://github.com/actualbudget/actual/assets/79430900/72cda36c-6b08-4200-86c3-c303aecad5a6">

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Operating System

Mac OSX

**Comment by MatissJanis** [comment]
👋 This is not really a bug report, so sadly I'll have to close it. If you're looking for support - I'd recommend reaching out on our community discord. It's quite active and I hope folks will help you there.

**Comment by jamisonhill** [comment]
Understood.  Sorry for the miss.  Thanks for the reply.
