### ISSUE TITLE
[Bug]: Fatal app error clicking on Edit button of a(n auto-generated) rule

### ISSUE THREAD

**Issue by stevehartwell** [actualbudget/actual#2243]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

After I changed some Payee transactions I noticed that a single rule had been generated in the Rules section.

When I clicked on the rule's [EDIT] button, I got a Fatal Error dialog.

Closing the file, re-opening, and clicking on the rule [EDIT] button leads to the same Fatal Error dialog.

### What error did you receive?

Screenshot attached.  Browser console log and contents of the rules table (1 row) in `db.sqlite` below.

Browser console log:
-----------
```
Error: value can be string only if strict = false
    n4 Autocomplete.tsx:41
    children Autocomplete.tsx:659
    renderInput Autocomplete.tsx:658
    children Autocomplete.tsx:419
    e downshift.esm.js:1377
    React 10
        aJ
        aQ
        lB
        l_
        lE
        lT
        lp
        ly
        oI
        lf
[react-dom.production.min.js:189:29](http://localhost:5006/node_modules/react-dom/cjs/react-dom.production.min.js)
    React 11
        az
        callback
        im
        sN
        sL
        sZ
        lP
        lD
        ly
        oI
        lf
```
contents of the rules table (1 row) in `db.sqlite`
----------
```
id	stage	conditions	actions	tombstone	conditions_op
deba75a2-9641-4687-8d8e-344e4816585a	pre	"[{""op"":""oneOf"",""field"":""imported_description"",""value"":[""Capital One Crcardpmt 240101""],""type"":""string""}]"	"[{""op"":""set"",""field"":""description"",""value"":""b1d5eec7-6626-4f17-8361-0b2bf6b79a74"",""type"":""id""}]"	0	and
```

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Mac OSX

**Comment by youngcw** [comment]
can you try out the demo at demo.actualbudget.org?  I believe this issue has been fixed and will be in the next release.  Trying the demo will confirm.

**Comment by stevehartwell** [comment]
I have now imported my file that has the rule that causes the issue into demo.actualbudget.org.

Going to Rules and clicking on the [EDIT] button now **opens the dialog correctly**, so  this seems to have been fixed in the current build.

I will look for the issue number and/or pull request for this fix to update this issue and close as duplicate.  (@youngcw if you know which it is, please let me know :-)

Thanks for your prompt response. 😀

**Comment by stevehartwell** [comment]
Closing as duplicate of #2180

(Sorry :-(, I forgot to search closed bugs)
