### ISSUE TITLE
[Bug]: Can't connect to DKB bank via GoCardless

### ISSUE THREAD

**Issue by sebcourant** [actualbudget/actual#2248]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Was able to connect other accounts (N26), however, when connecting to DKB, the GoCardless connect page just closes and Actual "Link you account" pop up times out and closes.

Not sure if the issue is due to Actual or to GoCardless.

### Where are you hosting Actual?

None

### Operating System

None

**Comment by MatissJanis** [comment]
👋 Would you mind sharing two log files with us to help debug the issue?

1. browser logs
2. server logs

**Comment by MatissJanis** [comment]
Closing due to lack of information.

**Comment by Kontor23** [comment]
Hi, have the same exact problem. @MatissJanis how to send you the log files you need?

**Comment by Karaguya2164** [comment]
I have the same problem, too. Not sure though how to retrieve the right logs.

**Comment by swmatthiasbauer** [comment]
This is not an ActualBudget related issue. GoCardless has switched the DKB integration to a different API, which appears to be causing issues.  In my GoCardless account under "Connect my Bank" no connection could be established either, as no 2FA authentication is offered. 
More information from another tool that uses GoCardless here: https://www.reddit.com/r/lemniscus/comments/1bdr0qa/online_banking_hinweis_f%C3%BCr_dkbkundys/

**Comment by Karaguya2164** [comment]
I tried linking my account today again and it seems to work now.
