### ISSUE TITLE
[Bug]: Pressing return/enter when the checkbox is focused does nothing

### ISSUE THREAD

**Issue by j-f1** [actualbudget/actual#226]
### Verified issue does not already exist?

I have searched and found no existing issue

### What happened?

Pressing return/enter when focused on the payment/deposit columns of a new transaction will cause the transaction to be added/saved. However, this will not happen for the “cleared” checkbox.

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Chrome, Safari

### Operating System

Other

**Comment by rich-howell** [comment]
This has already been resolved and merged as part of https://github.com/actualbudget/actual/issues/29 so I will go ahead and close this out.

**Comment by TomAFrench** [comment]
This is different from #29 as it's referring to entering transactions in the transaction table rather than performing the bootstrap step.

**Comment by rich-howell** [comment]
Apologies.

**Comment by ezfe** [comment]
I've just taken a look at this myself and it's coded to only allow pressing enter on the Credit/Debit fields:

https://github.com/actualbudget/actual/blob/master/packages/desktop-client/src/components/accounts/TransactionsTable.js#L1635-L1642

That being said, adding `cleared` is easy and makes sense. I can open a PR with a patch if that sounds good...

**Comment by jlongster** [comment]
Good find @ezfe! Yes that makes sense to me!

**Comment by ezfe** [comment]
Alright I'll push up the code change and make a PR momentarily

**Comment by TomAFrench** [comment]
Closed as this is fixed by #234
