### ISSUE TITLE
[Feature] upload images, documents for a transaction

### ISSUE THREAD

**Issue by quangvinh1225** [actualbudget/actual#2275]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

i want to keep some documents related to transaction as bill, invoice, receipt,... to proof for transaction

### Describe your ideal solution to this problem

When create a transaction, application should allow to upload some images or documents.
On mobile device, we can take some picture and upload to a transaction

**Comment by Teprifer** [comment]
@quangvinh1225 

This is a duplicate to: #530 You can vote on it there and add your comment about taking photos to it.
