### ISSUE TITLE
[Feature] Support multiple currencies

### ISSUE THREAD

**Issue by joojscript** [actualbudget/actual#2288]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Currently, the app does **not** support multiple currencies.
It would be great if it did so.

**Comment by joel-jeremy** [comment]
Please see discussion in: https://github.com/actualbudget/actual/issues/1132
