### ISSUE TITLE
[Feature] Arithmetic operations on budget cell value without having to move to end of line

### ISSUE THREAD

**Issue by jaarasys-henria** [actualbudget/actual#2315]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

When I already have a value in a budget cell, select that cell, press plus from keyboard and type a number, the existing value in the cell gets obliterated.

At least I'd expect it to be replaced by the new number, but that doesn't sound good either.

Instead what I'd like to see happening is that the arithmetic operation that I was aiming for is applied to the existing number.

Current behavior step by step:
1. Empty cell
2. Input number 20
3. Reactivate the cell that now contains number 20
4. Input +20<ENTER>
5. Cell contents are removed

Desired behavior step by step:
1. Empty cell
2. Input number 20
3. Reactivate the cell that now contains number 20
4. Input +20<ENTER>
5. Cell content becomes 20+20 => 40
6. Input /10<ENTER>
7. Cell content becomes 40/10 => 4

This can be done with the current version of Actual, but you HAVE TO remember to move to the end of line before applying arithmetic operators. Otherwise, disaster.

This imitates the very nice behavior of old YNAB which I think does this very nicely.

I might tackle this myself at some point, but totally up for grabs. Not sure what could go into this, but on the surface level this doesn't sound too bad. Maybe just apply set the cursor to the end of line by default? If so, this would be a very nice Good First Issue.

### Describe your ideal solution to this problem

Desired behavior step by step:
1. Empty cell
2. Input number 20
3. Reactivate the cell that now contains number 20
4. Input +20<ENTER>
5. Cell content becomes 20+20 => 40
6. Input /10<ENTER>
7. Cell content becomes 40/10 => 4

### Teaching and learning

Maybe a mention somewhere, but at least for me, this is the behavior I intuitively expect.

**Comment by youngcw** [comment]
Added by #2523
