### ISSUE TITLE
[Feature] Make comma's and period interchangeable when entering figures

### ISSUE THREAD

**Issue by vinstaal0** [actualbudget/actual#2318]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Currently when you type in a number and you press the period (when comma is the default decimal separator), it will not understand that you mean the comma. Due to differences between international keyboards and country specific keyboard it's not always possible that the comma/period on the keyboard matches with what it logically should be for that country.

For example, the Dutch keyboard layout has a comma on the number since we use commas as decimal seperators. However it does not include the € symbol. However, the international keyboard does have this on the ctrl + alt + 5 keybind.

This makes it so when you type numbers in ,say 1234,56, using the numbpad it will change it to 123456,00.

### Describe your ideal solution to this problem

All finance programs I have worked with (and most other programs where you enter numbers) fix this by making the assumption that if you type in 1234.56 you actually mean 1234,56.

Not sure if it is possible, but if it is you could also check the user's keybinds to see what they have bound to numbpad.

### Teaching and learning

Most people will not notice that this feature is implemented, but people will notice it hasn't been implemented.

**Comment by andriantoeff** [comment]
Seeing the `need votes` label in this issue: Does this feature can be said as implemented or are there still pending subtasks?

**Comment by vinstaal0** [comment]
I can't test if htis is fixed since I can't currently update to the newer version (blame TrueCharts for that).

If anybody wants to test it type in 1.000,00 and see if it makes it a thousand or 100 thousand. (switch the dot and comma depending on your regional settings)
