### ISSUE TITLE
[Feature] Search by Category Including Subcategory

### ISSUE THREAD

**Issue by Crazypkr1099** [actualbudget/actual#2324]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

When searching for a category, it doesn't show the category, causing people who don't remember their subcategory name to have to go back to the report page, remember the category name and then search by it.

This was a feature that was removed to improve the search function for people who memorized their subcategories.

As a person who has tons of subcategories, this makes it extremely difficult, and I would like this reverted.

In addition, this did not follow the proper protocol of being put to a vote, but instead hidden inside a bug feature report. 

### Describe your ideal solution to this problem

Either revert the change or add a setting option to toggle this on/off, as shown in #1767

**Comment by MatissJanis** [comment]
Related: https://github.com/actualbudget/actual/issues/1615

**Comment by yoyotogblo** [comment]
I vote for reverting the change so we can search category groups. When you have the same category in many groups, it's much faster to search by category group. Also, in cases where one can't remember the specific category, it helps to search by the group. Can't think of any real strong reason for the original change to have been made. An extra click isn't too big a deal.

**Comment by youngcw** [comment]
@Crazypkr1099 Is this good to close as a completed feature?

**Comment by Crazypkr1099** [comment]
> @Crazypkr1099 Is this good to close as a completed feature?

Yessir thanks!
