### ISSUE TITLE
Create a burn-up report to manage daily, discretionary expenditure

### ISSUE THREAD

**Issue by TheBlueCircle** [actualbudget/actual#2330]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I have a budget group for fixed costs (like bills) and one for discretionary spend. I'd like to better manage my discretionary spend by providing visual guides and breakdown of spend by day. 

### Describe your ideal solution to this problem

I suggest a simple, intuitive graph that shows me my budget for day-to-day spending for the month in the form of a burn-up chart. Monzo bank has a similar function in the US and the UK, which looks like this (some small edits for privacy)

 
![Screenshot_20240204_153443_Monzo](https://github.com/actualbudget/actual/assets/153461238/42ab5c48-6cf2-4c2b-bd4a-7e68313ed5a6)

In this example, the dotted line is the burn down chart showing the average spend per day for the selected categories if you are to spend your whole budget (which Monzo calls a target). The heavy line is the actual spend. If the heavy line is below the dotted one you are overspending; if it is above you are underspending. 

I suggest that we don't replicate this chart as-is because it has a few fundamental issues. It is not immediately intuitive (probably because it is burn down target than burn up, and there could be better use of colour to show what is good and what is bad) and it suggests that a budget is a target for spending that you should meet (rather than a maximum figure to stay within).

That said, the concept is useful and could be very powerful in Actual to help manage daily, discretionary spend. I suggest we take inspiration from a burn chart, but make it better. Specifically:

* Create a burn-up report (rather than a burn down one)
* Allow this to be driven from the budget assigned to any combination of categories (or category groups)
* Provide helpful psychological nudges (such as the graph being in green if within budget or red if above the budget). 
* Have dynamically updated text that shows for the current day a) the maximum you can spend per day to remain on budget, b) how much you've spent so far on that day, c) how much you're within or above budget.

This would be particularly powerful if available on mobile. 

This could provide the basis for more sophisticated burn charts (for example, the guide line could be non-linear to include expected future transactions or bills) - but it would be helpful to test if this would be a useful addition and, if so, develop the basics and test response to it before considering additional PRs.

### Teaching and learning

Done right, this should be an intuitive and helpful addition to Actual and could helpfully sit alongside the existing reports.

It shouldn't create any additional learning overhead over and above existing reports, however additional documentation would likely be required (I can contribute to that).

**Comment by jsehnoutka** [comment]
#2622 will implement this

**Comment by youngcw** [comment]
Added by #2622
