### ISSUE TITLE
Combined list of transactions across accounts on mobile

### ISSUE THREAD

**Issue by TheBlueCircle** [actualbudget/actual#2333]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I would like to see a combined list of all transactions across different accounts on the mobile view. Currently you can only look at transactions by first selecting an account. 

### Describe your ideal solution to this problem

Amend the mobile accounts screen so that the user can select "all accounts" (or potentially a filtered subset). Transactions would then be listed in a chronological list similar to the existing accounts based screen. 

### Teaching and learning

No additional learning should be necessary. Done right, this should be an intuitive addition. Some minor changes to documentation might be required.

**Comment by bchooxg** [comment]
+1 for this feature
