### ISSUE TITLE
[Feature] Monthly Notes field

### ISSUE THREAD

**Issue by shawalli** [actualbudget/actual#2336]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Budget Category notes are great for organizing stable or long-term information. However, there is often more transient information that pertains to a particular month. Some examples:

- breakdown of category savings for a month, e.g. breaking down specific trip costs for Vacations budget
- breakdown for whom you are saving/spent in your Gifts category
- tracking confirmation/invoice numbers for particular purchases in a month

Sure, this information could go in the Category notes section, but that would fill up pretty quickly over time! Additionally, it can be handy to be able to go back a few months and see pertinent information from that timeframe. This feature is actually available in YNAB, and it is one I used quite a bit when that was my financial tool. I'd love to see the same feature on Actual!

### Describe your ideal solution to this problem

To the left of the dropdown-caret (or possibly in the dropdown itself?) have the notes icon. Clicking the icon displays the notes popup (just like the category notes popup).

**Comment by Kidglove57** [comment]
@shawalli 
I personally use the Monthly Notes field for this (at the top of each months budget screen just to the right of the month name). New YNAB was by recollection exactly the same. Although I agree that YNAB 4 was useful as it offered more flexibility to have a different category note for each month. But then YNAB did away with that …. I missed it for a while and then got used to it.

**Comment by Kidglove57** [comment]
Btw this appears to be the same as:

https://github.com/actualbudget/actual/issues/824

**Comment by shawalli** [comment]
Whoops, I did search but somehow missed that, @Kidglove57. Thanks for pointing it out.

**Comment by youngcw** [comment]
Closing as duplicate of #824
