### ISSUE TITLE
Multilingual version[Feature] 

### ISSUE THREAD

**Issue by Liuzizhang** [actualbudget/actual#2337]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Can a multi-language version be developed to support users in other countries?If not, can you give me guidance and tell me where to modify the text? I will modify it locally for my own convenience.

**Comment by MatissJanis** [comment]
Duplicate: https://github.com/actualbudget/actual/issues/497
