### ISSUE TITLE
[Feature] wildcard or regex in rule

### ISSUE THREAD

**Issue by mercrapper** [actualbudget/actual#2339]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Today, the rules have to match a payee exactly. Many banks will append a unique transaction number or add the amount to the payee so it is different every time the same payment or transfer is made. The rules are unable to match this type of transaction

### Describe your ideal solution to this problem

It would be really powerful to be able to use wildcard matching or regular expression in the rules to so you don't have to keep adding to the matching criteria

**Comment by youngcw** [comment]
Closing as duplicate of #500
