### ISSUE TITLE
[Feature] Open calculator for amount input boxes

### ISSUE THREAD

**Issue by mercrapper** [actualbudget/actual#2340]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

When entering amounts, you are presented with an input box. This forces you to use the keyboard. If you want to add to the amount, you have to do the math first, then edit the amount to the new total.

### Describe your ideal solution to this problem

It would be very useful to pop up a mini calculator when focus has put on one of these amount input boxes. This would allow you to enter the value without a keyboard, but will also let you just add or subtract to/from the existing amount.

**Comment by jfdoming** [comment]
The desktop partially has this feature already! You ca type "100+200" in most numeric fields and it will do the math for you

**Comment by joel-jeremy** [comment]
This would be very handy for mobile users. Maybe this can be used to implement a custom keyboard: https://github.com/hodgef/react-simple-keyboard
