### ISSUE TITLE
[Feature] Goal template flag to add funds to category

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#2351]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Is it possible to apply the budget template to the budget mid month and it apply all the rules within regardless of what has already been budgeted? 

For example, I get paid towards the end of the month (23rd), sometimes towards the end of the following month I will have rolled with the punches and added some money to a category to get petrol or extra groceries but come pay day I still want the budget template to apply what is within each template to the category.

**Here is an example** 

I budget £100 for fuel every month, depending on how busy I am sometimes I need to budget more during the next month (before I get paid) but then when I come to apply the budget template the fuel category will be ignored because I have already applied funds to it.

The existing overwrite behaviour doesn't do what I want either (see below)

![image](https://github.com/actualbudget/actual/assets/22135084/4893b738-a070-4ca1-b9ba-3174b29be4f6)

Then apply the budget template

![image](https://github.com/actualbudget/actual/assets/22135084/3e5e6741-24d6-4432-a6ae-69bbb55635e9)

The TBB was £0.00 after applying the template it is now -25 so all it did was 75+25=100
What I wanted was this

![image](https://github.com/actualbudget/actual/assets/22135084/301e6fc1-f035-4259-adcf-429d09f990ee)

So the 16.86 that was left at the time the template was applied remains and the 100 in the template is added

### Describe your ideal solution to this problem

Templates would have a flag that would allow the application of the template to the category with the flag to have the expected behaviour as explained above. Maybe something like 

`#template 100 force`

### Teaching and learning

After speaking to @shall0pass this wouldn't be default behaviour and would be an additional tag, it would need documenting to show how it works and what it does when used to avoid users incorrectly using goals.

**Comment by rich-howell** [comment]
@shall0pass Some replies to your questions below :)

> Is the #template {amount} line the only template you are wanting this behavior for, or are there others?

I would like any line with the flag to have the behaviour. 

> Would you be open to a new template identifier like #template add {amount} ?

The only thing with ADD is that it implies addition is going to take place. Is that the right wording? E.G. `#template add 33.99 by 2024-10` does that read right? If we are implementing something that goes against the template rule that is a force, I.E. I want to forcefully apply the template rule.

> Also, how do you envision the behavior if there are multiple templates in a category?
>
> Example: #template 50 #template add 50

Good question, I don't use multiple tags per category so not sure how this would work.
 
> In this example, if the current budgeted value is 0, the outcome should be to budget 100. But, if the current budgeted value is 100, what would you expect the budgeted value to be?

As above, I dont use multiples, plus it might not be 100 if money had been applied to the category mid-way through the month which is where this feature came from initially so it might just be 50.

> Or, is this an example of a template where only the #template add {amount} is allowed and multiple templates are not allowed?

Again, I dont use multiples so not sure how this would play out, but for my workflow I only use a single template tag so it wouldn't apply. 
I guess, we would need to test it out and see how it behaves.

**Comment by Midgetwombat** [comment]
I have added a pull request that youngcw has added above. It adds a directive to create a new template called a Pay Distribution template. You can use it as either '#template +$30' to add $30 to the category budgeted column, from available funds each time 'Apply Template' is clicked. Or '#template +10%' to add 10% of the remaining funds to that category. With the multiple templates issue. This new Pay distribution template will not set a goal it is designed to just add. You can use normal templates to set the goal but they will not change the budgeted amount while there is a Pay Distribution template active in that category. Check it out if it's what you're looking for mark it up.
