### ISSUE TITLE
[Feature] Automatic contract identification

### ISSUE THREAD

**Issue by M123-dev** [actualbudget/actual#2367]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

With many transactions, it is difficult to keep track of recurring contracts.
Phone, energy, car, gym membership, Netflix, you get the point

### Describe your ideal solution to this problem

I'm currently using FinanzGuru, a German mobile app with a good overview of contracts. It scans all transactions and looks for patterns, same amount coming from or going to the same destination account, every month, quarter, or year and marks it as a contract.

The app uses this information to:
1. display this in a separate tab (monthly fixed income compared to fixed expenses)
2. track changes (Attention, "GYM xyz" has increased by 33%/month, is that right? - The "Montly income" is already 4 days late!)
3. show predictions for the future (the network graph can be extended into the future, of course only considering the contracts)

In addition, category rules can be created automatically for all transactions from a contract

### Teaching and learning

It must be ensured that incorrectly recognized contracts can be deleted and that unrecognized contracts can be marked manually.

**Comment by youngcw** [comment]
This is partially doable as is.  Actual can find some reoccurring bills via the find schedules option.  These can be budgeted automatically using the schedule goal template.
