### ISSUE TITLE
[Feature] Overflow text tooltip for Bank Account on the SelectLinkedAccounts modal

### ISSUE THREAD

**Issue by hsmeets** [actualbudget/actual#2370]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I found myself looking into devtools too many times to find out the right bank account to match my Actual budget account, so I decided to open this feature request!

Overflow text is hidden with ellipsis, removing crucial Bank Account information from sight.

In my case I need the last part of the bank account to identify and match it:
Account 1: [John Doe and/or Jane Doe (XXX 1234) EUR]
Account 2: [John Doe and/or Jane Doe (XXX 5678) EUR]

### Describe your ideal solution to this problem

My suggestion is to add a tooltip on the "Bank Account To Sync" column for overflow text in the SelectLinkedAccounts modal.

**Comment by youngcw** [comment]
is the for simplefin?

**Comment by hsmeets** [comment]
I'm using it with GoCardless, but the modal looks the same for SimpleFIN according to the docs ("Link Accounts").
