### ISSUE TITLE
Add fields for local currency and exchange rate

### ISSUE THREAD

**Issue by TheBlueCircle** [actualbudget/actual#2373]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I often spend overseas. I'd like to be able to log the spend in the overseas currency in Actual as well as the exchange rate used by my bank and any fees applied. 

### Describe your ideal solution to this problem

Additional fields on Actual against a transaction. (To avoid clutter, it would be helpful for these to be hidden or displayed according to user preferences). 

Ideally:

1. Local currency (to determine what currency you're spending on)
2. Amount in local currency
3. Exchange rate
4. Fees

Ideally, Actual would calculate the exchange rate or the payment amount in the account's currency depending on what data has been entered and what has not.

**Comment by mikejarxyz** [comment]
I agree!

With many different currencies these days, it would be great to track in different currencies and log exchange rates at time of transaction.

I am Canadian and live in Peru for the time being, and so I have accounts in CAD, USD, and PEN. Not to mention BTC and other cryptocurrencies. 

I would love to be able to track my accounts across currencies, maybe use APIs to show current prices of each, and log automatically the exchange rate when moving money between currency/accounts, with the ability to custom set the exchange rate if the automatic data is not 100% accurate.
