### ISSUE TITLE
[Feature] Update Budgeted column based on upcoming Schedules

### ISSUE THREAD

**Issue by gravelfreeman** [actualbudget/actual#2376]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I spent quite some time adding all my upcoming payments under the Schedules tab. After adding my schedules to a category by modifying the rule, I was surprised that I had to manually add them in the Budgeted column.

I think the current behaviour is so that the schedule task creates an entry in the database and then that expense will appear under the Spent column prior to the category line you've set the rule to.

The same logic should apply to the Budgeted column; since I know it'll be an expense and that I took the time to add it as a schedule, I'm expecting to see it there, without manual intervention.

### Describe your ideal solution to this problem

Update automatically the Budgeted column based on the upcoming Schedules.

### Teaching and learning

In reference of [this](https://github.com/actualbudget/actual/issues/1569).

**Comment by Teprifer** [comment]
To add a missing thought, could auto add the goal templates for schedules automatically if a category is assigned as a rule.

**Comment by gravelfreeman** [comment]
At least if we can have a toggle switch as an option to add to budgeted column for the one that wants it.

**Comment by javripley** [comment]
Personally, I'd rather have the budget UI displaying upcoming expenses (so that I can budget ahead for those) rather than automatically setting that amount aside, "just" because I scheduled the transaction. That way you wouldn't be mislead into thinking you will have/not have that money available at the end of the month, since it would be clearly shown that some expenses/incomes are upcoming. I think automated rules for budgeting, unless explicitly set for that, can get confusing real quick.

**Comment by gravelfreeman** [comment]
Another column actually make a lot of sense. I would think it's even better this way! Good idea.

**Comment by youngcw** [comment]
Its closed because of [this](https://github.com/actualbudget/actual/issues/2376#issuecomment-1953101311)

**Comment by TorC8** [comment]
This would be a significant improvement, and best in the form of updating the budget page to a four-column layout.  Budgeted, Spent, Upcoming, and Balance, with the balance reflecting both spent and upcoming.

I think the most useful number for budget balance is how much is available to spend, particularly in the case of a category that has a mix of subscriptions and one-off purchases.  As it is now, I don't see an easy way to get AB to tell me how much I can spend in a category without going over budget by the end of the month.

Budget view as of the thirteenth with $15 spent on the third and a $90 transaction scheduled for the twenty fifth:
Example current:
Budgeted: $200
Spent:     $15
Balance:   $185

Proposed change example:
Budgeted: $200
Spent:     $15
Scheduled: $90
Balance:   $95

I suppose one could separate further:
Budgeted:  $200
Spent:      $15
Current bal: $185
Scheduled:  $90
EoM balance: $95

IMHO, the last example is excessive and the current balance should be an optional view if implemented at all.

**Comment by TorC8** [comment]
I started looking at this, but I'm not entirely sure where to find the relevant files.  Looks like it should be fairly easy, unless the relevant information isn't available to grab from.

First, function to get the needed upcoming transaction data:
for rule
  if $rule action includes set category to $category AND if $schedule is upcoming when upcoming length is end of this month
  let upcomingspend += $amount

Second, change the budget view page to include the fourth column, print the output of of the above function in it, and change budget balance column display to reflect this additional value.

Would someone familiar with the code let me know if I'm on the right track and if so, point me toward the files to look at?
