### ISSUE TITLE
Importer packages don't use the current version of `actual-app/api` 

### ISSUE THREAD

**Issue by TomAFrench** [actualbudget/actual#239]
As shown here, the YNAB importer packages are pulling a version of `actual-app/api` from NPM rather than using the up-to-date version from within the monorepo

https://github.com/actualbudget/actual/blob/9c0df36e16d031501474bc3ee738af24479a02a1/yarn.lock#L25-L59

We should be using [workspace ranges](https://yarnpkg.com/features/workspaces#workspace-ranges-workspace) to ensure that this doesn't happen but when we tried this it resulted in 30min build times (https://github.com/actualbudget/actual/pull/230).

My guess on the cause of this is the cyclic dependency between `loot-core -> actual-app/api -> actual-app/import-ynab4/5 -> loot-core`

**Comment by megawubs** [comment]
Is this the reason why I'm unable to use the workspace version of `actual/api` inside of the YNAB importers? I'm trying to dig into #378, but debugging is a bit confusing right now.

**Comment by MatissJanis** [comment]
This has been solved
