### ISSUE TITLE
[Feature] Show filtering chips when coming from budget

### ISSUE THREAD

**Issue by psybers** [actualbudget/actual#2390]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

When clicking on a category's spent column in the budget view, it takes the user to a list of transactions that match that category for that given month, e.g. clicking here:

<img width="537" alt="image" src="https://github.com/actualbudget/actual/assets/1115390/bbc9ec44-847a-47a3-b876-e89d00b43be0">

will then take you here:

<img width="390" alt="image" src="https://github.com/actualbudget/actual/assets/1115390/f465a49e-12a7-42c1-b86e-0e979533f6a8">

This view filters the transactions.  But it does not show the "chips" that indicate what filter(s) are active, which means users have no way to easily modify that set of filters.  They can add new filters, but if they wanted to drop one of them (say to drop the month and view for all time), they would have to leave the view, go to "All Accounts", then re-add the category filter.

This obviously is more work for the user.  But more importantly, it shows two similar ideas (filtering transactions) with two different UI/UX strategies.

### Describe your ideal solution to this problem

Consistency.  Ideally, both would wind up with the same view.  If I click on a link from the budget page to view filtered transactions, it should look more like this mockup:

![image](https://github.com/actualbudget/actual/assets/1115390/3817f9ee-584a-4a5c-99fc-e550396c7f18)

### Teaching and learning

The feature should be self-discoverable, as it mimics existing behavior.

**Comment by youngcw** [comment]
This was just barely changed in #2408
