### ISSUE TITLE
[Feature] Enhance the Cash Flow report to select future months and to calculate them based on the "budgeted" amounts

### ISSUE THREAD

**Issue by darianf01** [actualbudget/actual#2402]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

A user switched to the Report Budget and budgeted all the expenses and expected income for next 12 months (current + 11 in the future). 
The user would like to identify in which future month there will be a negative cashflow.
Currently the user can see per each future month what are the "Projected Savings", however the user has no way to easily identify in which future month(s) the cashflow might be negative. 

The current Cash Flow report does not allow to select future months, and the report is based on actual transactions and not Budgeted amounts.

### Describe your ideal solution to this problem

Enhance the Cash Flow report to:
1) Allow selecting future months 1 year ahead - currently the user can only select up to current month
2) Calculate the cashflow of future months based on the Budgeted amounts (expenses and income)
The above could be enabled with a toggle/checkbox for "Projected Cash Flow" that when enabled, it would allow to select the future months and perform for those future months the above suggested calculations based on Budgeted amounts.

**Comment by qmph22** [comment]
I would love to see this implemented. I am also looking into future months to see which ones I might end up with negative cashflow on. I find myself having to manually calculate my cashflow for the month based off of my schedules but there should be a way to see the end result of that calculation in Actual.
