### ISSUE TITLE
hide reconciled transactions from account register.

### ISSUE THREAD

**Issue by shourabh** [actualbudget/actual#2407]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I know I can filter it from filter tab as true or false, but I want an option which says, "hide reconciled transactions". And after that only non-reconciled transactions are shown in the register. this will make the register clutter free.

### Describe your ideal solution to this problem

In Ynab4, there is an option to show and hide reconciled transactions. I want it to be implemented in similar fashion.

### Teaching and learning

It will make account registers clutter free.

**Comment by davidkus** [comment]
Implemented here #2542
