### ISSUE TITLE
[Feature] Add "Is uncategorised" (or "is uncategorized") to category filter 

### ISSUE THREAD

**Issue by TheBlueCircle** [actualbudget/actual#2412]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Currently you can select all uncategorised transacations from the red bar at the top of Actual. But there is no easy way to find uncategorised transactions for the current account view. By allowing for a filter of "is uncategorised" I would be able to see a simple list of categories without a filter for the current account (or current account view).

### Describe your ideal solution to this problem

An additional filter of "is uncategorised" when you click on Filter then Category

### Teaching and learning

None required - this is an incremental and intuitive update.

**Comment by matt-fidd** [comment]
This can be achieved with 

<img width="195" alt="Image" src="https://github.com/user-attachments/assets/cab4c136-6550-4615-a632-df7e3b1441fc" />
