### ISSUE TITLE
[Feature] Ability to Sort and Filter Schedules

### ISSUE THREAD

**Issue by qmph22** [actualbudget/actual#2414]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I would like to the ability to sort and filter Schedules. If there are a significant amount of known future transactions that are inputted as a Schedule, it can be difficult to search and manage them unless you know part of the name of the Schedule. Adding in this functionality will make the Schedules feature of Actual much more manageable.

### Describe your ideal solution to this problem

In any Account, we are able to sort any column by clicking the column name and I would like the same functionality to be added to the Schedules.

Similarly, filters are available for any Account and that same functionality should be added to the Schedules. Currently, we can only filter by name but any of the columns in Schedules should be filterable.

### Teaching and learning

A short blurb in the documentation at the link below about sorting and filtering should be sufficient. 
https://actualbudget.org/docs/budgeting/schedules

An alternative is to write a section in the documentation that focuses on sorting and filtering if this same function is used for Accounts or will be used for other sections in the future such as Payees or Rules.

**Comment by rtbick** [comment]
Agreed this is a major UX need for schedules. When I first set up my schedules, I named them with a category as a prefix like "Bills - water", "Bills - electricity", "Subscriptions - Spotify", etc., so I could sort them alphabetically to find a particular schedule more easily.
