### ISSUE TITLE
[Feature]  MOBILE APP

### ISSUE THREAD

**Issue by urkoperez16** [actualbudget/actual#2424]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I have been looking for this in various issues and other repositories and I have not found it, I would like to know if there is or there is a possibility of creating an apk for the phones that connects to the web and to be able to use Actual with more ease and freedom.

**Comment by youngcw** [comment]
Its already avaiable as an offline PWA so you can install the app via the web page and use it offline
