### ISSUE TITLE
[Feature] Allow to exclude selected imported accounts from accounting

### ISSUE THREAD

**Issue by DenisBY** [actualbudget/actual#2431]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I imported accounts from my bank via API but it also imported accounts of my kids, since I have full access to them.

### Describe your ideal solution to this problem

It would be nice to have an option to exclude some accounts from accounting, like "For budget", "Transactions", etc.

### Teaching and learning

Add an option in the same way as other account's options in "three-dots-menu" at the top right.

**Comment by youngcw** [comment]
Is this different then off budget accounts?  It sounds the same to me.
