### ISSUE TITLE
[Feature] Option to set imported/linked account as "off-budget" in linking "wizard"

### ISSUE THREAD

**Issue by DenisBY** [actualbudget/actual#2444]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Currently when you add a new account and select "Link bank account with ..." there is no way to link it as "off-budget" account. You have to create a local account first and then link external account.

### Describe your ideal solution to this problem

Have a checkbox "off-budget" in linking wizard.

### Teaching and learning

As I new user I was wonder how to no to count my saving accounts in budgeting. After reading documentation I found, that I should mark accounts as "off-budget", but it wasn't clear how to do it as there was no such option in linking wizard.  I had to ask on Discord and was told, that I should create a local account as "off-budget" first and then link external account to it.

**Comment by psybers** [comment]
@youngcw We can remove the needs vote tag on this since #2788 implemented similar functionality.
