### ISSUE TITLE
Customisable "Look Ahead" for Scheduled Transactions

### ISSUE THREAD

**Issue by Phil89a** [actualbudget/actual#2458]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Currently "upcoming" transactions are only auto-entered 7 days ahead.  This means when looking ahead for the month, not all scheduled transactions are showing in the account and therefore your budget for that month is not complete.  That is, it is missing regular income and spend. Result is you are not fully sure if you are over or under-spending for that month until the regular transaction come in (which could be at the end of the month)

### Describe your ideal solution to this problem

Option 1 - Suggest a "number of days" field (default 7)  is added to each schedule item, so the user can add the number of days ahead that should be used to test and see if the transaction should be auto-entered.

OR

Option 2 - A global setting added that allows this value to be set - and then applies to all schedule items.

### Teaching and learning

Option 1 - No impact on user education.  Default would be 7 days so no change unless the user changes the value in a schedule item.  When users create or edit a schedule item, the option would be self explanatory.

Option 2 - No impact beyond explaining where the global setting is.  Again default would be 7 days and so if not needed by the user no change required.

**Comment by youngcw** [comment]
duplicate of #1890
