### ISSUE TITLE
Possibility to export reports

### ISSUE THREAD

**Issue by Powersheep** [actualbudget/actual#2477]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I would like to export my fancy custom report as an Excel file, csv file or SVG file.

**Comment by youngcw** [comment]
This is partially implemented.  Some reports allow exporting the report as an image.

**Comment by alexjj** [comment]
csv export for custom table reports would be great.

**Comment by juliuspopp** [comment]
> csv export for custom table reports would be great.

Exactly. I think this utility does that if that helps: https://github.com/dustinmcbride/actual-utils?tab=readme-ov-file

**Comment by alexjj** [comment]
> Exactly. I think this utility does that if that helps: https://github.com/dustinmcbride/actual-utils?tab=readme-ov-file

Oh nice! I've been using chatgpt to format the data that I copy and paste from my browser 😅

**Comment by cclarke591** [comment]
PDF export would be great as well.

**Comment by Wikzo** [comment]
+1 for a PDF export of (custom) reports

My use-case: Being able to print out a multi-year report to a bank meeting to provide an overview of my income and expenses.

(using PNG export doesn't really fit this scenario)
