### ISSUE TITLE
[Feature] Custom "Net Worth" Reports

### ISSUE THREAD

**Issue by jonapoul** [actualbudget/actual#2490]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I'm looking to plot graphs of the "net worth" of multiple sub-accounts on my budget, specifically debts that I'm working down. At the moment I can do this one at a time by opening the main "net worth" report and filtering by account. This works, but it'd be better if I could generate these with the "create custom report" tool too so I can save them individually and come back to them more easily when I want to.

If this is already supported then please let me know, but I've spent a while digging around and I can't get the report tool to generate anything other than per-month cash flows over time, not total value over time.

### Describe your ideal solution to this problem

An option in the Custom Report tool for tracking the total value of an account over time

### Teaching and learning

The "total" mode in the custom reports screen should probably be renamed in this case, but I'm not sure what to.

**Comment by youngcw** [comment]
Added by the customizable dashboards feature.
