### ISSUE TITLE
[Feature] Hide reconciled transactions

### ISSUE THREAD

**Issue by dasunsrule32** [actualbudget/actual#2503]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

YNAB has the option to hide reconciled transactions. It would be nice to have a permanent option that can be toggled off or on the ability to hide reconciled transactions.

You can do it it under a custom filter, but you have to enable every time you switch accounts.

**Comment by davidkus** [comment]
Implemented this here #2542

**Comment by dasunsrule32** [comment]
> Implemented this here #2542 

This is awesome! Can't wait to try it out. Thank you for working on this.

**Comment by ToniCipriani** [comment]
Just updated to 24.5.0 and now have the options. Seems like some transactions are still not properly hidden, specifically split transactions and transfers

**Comment by MatissJanis** [comment]
If there are issues with the feature (or imports, or anything else) - please open a new bug issue. I don't think anyone is actively monitoring feature tickets that are complete.

Also: thanks for implementing this! Great feature!

**Comment by SamRodkey** [comment]
I find the behavior confusing/unexpected when I see my running balances change when I hide/unhide my reconciled transactions. Why do these numbers change?

**Comment by youngcw** [comment]
@SamRodkey please open a new issue detailing what you are seeing
