### ISSUE TITLE
[Feature] Accounts list category

### ISSUE THREAD

**Issue by jeremyforest** [actualbudget/actual#2508]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Accounts are listed in the left toolbar unorganized. I wonder if its possible to be able to organize them in some way.  For example I have retirement accounts and mortgage accounts that are off budget and I would like to group them in the same category 'retirement' while accounts about mortgage (escrow, loan) could go in another category. 

### Describe your ideal solution to this problem

I'm thinking about separators or  a dropdown  but there might be a better solution.

### Teaching and learning

I think it would be a pretty self-explanatory feature that you can group accounts manually however you want (for example by bank or purpose of the accounts)

**Comment by youngcw** [comment]
duplicate #1683
