### ISSUE TITLE
[Feature] Divide amount equally between categories for split transactions 

### ISSUE THREAD

**Issue by maxlandry** [actualbudget/actual#2512]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

It would be much faster to enter transactions that must be divided in equal parts in different categories. Currently, I have to use my calculator when adding split transactions.

### Describe your ideal solution to this problem

When you leave all categories amounts to zero, a modal could ask if you want to divide the transaction amount equally between all the categories.

**Comment by youngcw** [comment]
You can already do this.  There is a distribute button when making a split

**Comment by maxlandry** [comment]
Not on mobile, though.

**Comment by youngcw** [comment]
Then you should had said mobile.  If you edit the request to be for mobile Ill open this up again
