### ISSUE TITLE
[Feature] Clear transactions in bulk on mobile 

### ISSUE THREAD

**Issue by maxlandry** [actualbudget/actual#2513]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Currently, when have to open each transaction individually to clear them on mobile. 

### Describe your ideal solution to this problem

It could be much more efficient to select transactions in the list and mark them as cleared with a click.

Other solution: being able to click on the blue check mark in the transaction list to change its status.

**Comment by youngcw** [comment]
This was added a while ago.  Long press a transaction to start a bulk edit on mobile.
