### ISSUE TITLE
[Feature] Ability to disable automatic rules

### ISSUE THREAD

**Issue by willoma** [actualbudget/actual#2515]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Actual creates rules automatically when it detects we apply the same category to a payee. This has never helped me, because I already have adequate rules, and when I didn't set rules, it means I need to select manually.

Hare is one of my real-life example. My wife works in animation for children. During holidays, our kids go there. So we have the same "payee" for her salary and for our kids holidays activities. I have a rule for her salary (based on the payee and the approximate amount), and no rule for the holidays activities (because sometimes there is also exceptional expenses relative to her job, or reimbursements from her employer, etc). But Actual keeps creating a rule that applies this payee to the "kids holidays" category, therefore her salary is categorized in "kids holidays". And when I remove this automatic rule, it reappears a few weeks/months later because there were kids holidays inbetween...

### Describe your ideal solution to this problem

A checkbox in the configuration in order to disable the automatic rule feature.

**Comment by spuxx1701** [comment]
Hey. I also don't really like the automatic creation of rules. I've found that the rules that are being created are often times problematic. For example, when the Payee is a generic fintech like paypal and I categorize a couple of paypal transactions as "Food", actual will automatically create a rule that categorizes paypal transactions as "Food", which is obvious nonsense. The behavior has lead me to check my rules everytime I have categorized some transactions manually, looking for rules with a single condition and deleting them. This makes things harder for me, not easier. I would really like to be able to disable this behavior.

**Comment by spuxx1701** [comment]
Also, I'd be willing to give implementing this a try. :)

**Comment by mrkwnzl** [comment]
From #3560, to keep things more organized and in one place. I wrote down my issue with it based on the current intended solutions as I understand them and why they don’t really work for me. Thank you!

> For payees with changing categories, the creation of automatic rules is rather hindering instead of helpful. The current solution is to have certain payees that get a post rule with an empty category, but that doesn’t help with all payees, as some get other rules for categorizing and a post rule would overwrite the rule I actually want. So the solution there would be to create other post rules that are more specific. The better solution would be to simply disable the automatic creation of rules, as I can then create the rules I want the way I want.

**Comment by thecount2a** [comment]
I'm very happy to find this issue here, the automatic rules feature is really messing up my data.  Why does it create a rule without even asking for confirmation that a rule ought to be created?  Regardless, it would be GREAT to be able to disable the feature.  I create my own rules so I don't want to just accumulate sneaky rules that have already corrupted my data, I just don't want the rules to be created in the first place. I actually think this should be the default behavior to have automatic rule creation off, to avoid changing people's data who (like me) had no idea that this feature existed. Then they can manually turn it on, or at least pop up a confirmation dialog that asks whether to create the rule or not.

**Comment by matt-fidd** [comment]
Added in https://github.com/actualbudget/actual/pull/4081
