### ISSUE TITLE
[Feature] More flexible filtering for Payee rules, like "starts with" and regex

### ISSUE THREAD

**Issue by mattalxndr** [actualbudget/actual#2525]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

![Screenshot_2024-03-30_03-07](https://github.com/actualbudget/actual/assets/250466/5a7430fe-903b-4eb3-bc89-664a16f5f8f7)

As you can see in the screenshot, I have a ton of entries like `PAYEE-NAME PAYEE-TXN-ID` like "AIRBNB 934274932". I would like to define "If payee starts with `AIRBNB `, then ..." but it's not possible.

### Describe your ideal solution to this problem

Being able to use regular expressions or glob expressions like "starts with" and "contains" would allow for much more flexibility when defining a rule.

**Comment by jfdoming** [comment]
I think you could use 'Imported Payee' for a basic version of this (using `contains`)

**Comment by mattalxndr** [comment]
@jfdoming I did see that, but my "Imported Payee" field is blank on these transactions. I imported them from a [nYNAB dump](https://actualbudget.org/docs/migration/nynab). Maybe that needs its own Issue, I don't know.

**Comment by jfdoming** [comment]
> @jfdoming I did see that, but my "Imported Payee" field is blank on these transactions. I imported them from a [nYNAB dump](https://actualbudget.org/docs/migration/nynab). Maybe that needs its own Issue, I don't know.

Huh, that should definitely have its own issue. It should be a copy of the initial value of 'Payee' normally

**Comment by elkalt** [comment]
I would be willing to try implementing this, but I have no experience with development on Actual.  I can start taking a look early next week, but if someone could help point me in the right direction that would be appreciated :)

**Comment by jfdoming** [comment]
> I would be willing to try implementing this, but I have no experience with development on Actual. I can start taking a look early next week, but if someone could help point me in the right direction that would be appreciated :)

We have regex match on imported payee using the `matches` operator now! Does that fit your use case?

**Comment by elkalt** [comment]
@jfdoming That does, thanks!
