### ISSUE TITLE
[Feature] Smaller UI?

### ISSUE THREAD

**Issue by ilar** [actualbudget/actual#2532]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

The UI for Actual seems to have a significant amount of dead space all around, to the point of where the entire UI has a significant amount of scrolling for the same information that only took half a screen in YNAB4.

Is there a way around this that can be easily done in the files, or a 'compact' mode toggle or something?

You can see the comparison in sheer size here, with both UIs side by side, aligned to the top of the renderable.

![image](https://github.com/actualbudget/actual/assets/1613590/dcb5e07a-b265-4662-90a2-6eb72c1a4ffe)

### Describe your ideal solution to this problem

Are the margins globally set via variable? that could work. Otherwise, a 'compact mode' feature or even just a 'compact' theme?

Not familiar enough with the code base to know the best method.

**Comment by shall0pass** [comment]
There isn't a way to adjust the column widths.

You can collapse the header by mousing over the button in the top left of the monthly summary box at the top of the screen to save some space.

**Comment by ilar** [comment]
That does help, thank you! Maybe I'll make a greasemonkey script to tighten things up a bit more?

Do you know if the classes are consistent, or are they regenerated often?
