### ISSUE TITLE
[Feature] API documentation

### ISSUE THREAD

**Issue by Dagur** [actualbudget/actual#2549]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I have some python scripts that imported transactions into YNAB and I wanted to update them to use the Actual API. 

The [API documentation](https://actualbudget.org/docs/api/) doesn't really tell me anything about any API, just how to use your javascript library. 

### Describe your ideal solution to this problem

It's great that you offer a javascript library but I would like a REST API.

### Teaching and learning

Alternatively you could offer libraries in other programming languages but a normal API would be most useful IMO.

**Comment by youngcw** [comment]
closing as duplicate of #1384

**Comment by youngcw** [comment]
and as an FYI, there is a community built rest api if you want to use that.  There is a link to it in the community section of the docs

**Comment by Dagur** [comment]
Thanks. Sorry about the duplicate.
