### ISSUE TITLE
[Feature] Ability to disable de-duplication logic for CSV/QFX/OFX imports

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#2561]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Sometimes the de-duplication logic gets in the way. This has been discussed in depth here: https://github.com/actualbudget/actual/issues/2420

### Describe your ideal solution to this problem

We should add a checkbox option to the import modal. Checking this option would disable the de-duplication logic.

**Comment by youngcw** [comment]
I had been pondering this and I think this is the best way forward.  The only other thing I was thinking was to change how de-dup handles reconciled transactions. Like reconciled transactions either have to match id's or be a perfect match.

**Comment by keriati** [comment]
So if I understand it right, instead of using

    packages/loot-core/src/server/accounts/sync.ts reconcileTransactions()

in case of imports we should be able to use

    packages/loot-core/src/server/accounts/sync.ts addTransactions()

**Comment by strazto** [comment]
Related to #2679
