### ISSUE TITLE
[Bug]: Net Worth Y Axis values aren't removed in privacy mode

### ISSUE THREAD

**Issue by Teprifer** [actualbudget/actual#2563]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

1. View the net worth graph
1. Enable the privacy mode
1. The Y axis values are still visible.

The Y axis should be replaced with "..." (as how it works for the cash flow report and custom reports).

### Where are you hosting Actual?

Docker

### Operating System

Other

**Comment by ttlgeek** [comment]
Hello,
I'd like to work on this issue,
Can you assign it to me ?

**Comment by youngcw** [comment]
@ttlgeek We don't assign issues.  Just put in a PR for it

**Comment by ttlgeek** [comment]
Ok, will do.
