### ISSUE TITLE
[Bug]: Mobile autocomplete text colors

### ISSUE THREAD

**Issue by shall0pass** [actualbudget/actual#2574]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Dark theme seems mostly ok.  I think the subtle text color change is missing in the Account menu.

Midnight theme and light theme have text color issues when using the Mobile transaction entry page. 

![mobile_autocomplete_colors](https://github.com/actualbudget/actual/assets/20625555/9167166e-f723-40c4-a5df-71f90f6b6cc7)

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Other

**Comment by joel-jeremy** [comment]
Looks like this is a regression from https://github.com/actualbudget/actual/pull/2538
FYI @Jenna59
