### ISSUE TITLE
[Bug]: Income category group has a hide option

### ISSUE THREAD

**Issue by jsehnoutka** [actualbudget/actual#2579]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

After hiding out the entire income group, nothing visually changes in the GUI (the group name doesn't fade out) nor gives any visual signal to the user. 

This can lead to confusion as it effectively disables the ability of adding any income transaction throughout the application in case the "hide" option is selected on the entire Income group unintentionally. 

As per Discord discussion this should be probably fixed by removing the "Hide" option on the Income category group.

![Category](https://github.com/actualbudget/actual/assets/133903243/f363da13-eb26-48a9-8a72-b5673de486ed)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by jsehnoutka** [comment]
also related to #2578

**Comment by youngcw** [comment]
Could the db be updated just by running some aql in the browser console?  That ability was added recently for these kind of db issues

**Comment by psybers** [comment]
It could. So you would recommend just making the change and if someone decides later they wanted their income group not hidden they would have to figure out how to run a query to fix it?

**Comment by youngcw** [comment]
> It could. So you would recommend just making the change and if someone decides later they wanted their income group not hidden they would have to figure out how to run a query to fix it?

Mostly I doubt there are many that have done that, and if it comes up we have a fix ready that is easy enough to share

**Comment by psybers** [comment]
@youngcw Actually, does aql allow updates or is it select-only?

**Comment by youngcw** [comment]
> @youngcw Actually, does aql allow updates or is it select-only?

might just be reads without specific functions in the api

**Comment by youngcw** [comment]
I guess the other good option is to not care about if there hidden flag is set or not so then if someone has it hidden it will just show up going forward

**Comment by psybers** [comment]
I can confirm that!  Mine is hidden but still shows.

The problem is the transactions. You won't be able to classify any as an income category if your income group is hidden.
