### ISSUE TITLE
Importing from YNAB doesn´t handle split transfers

### ISSUE THREAD

**Issue by MathieuDR** [actualbudget/actual#258]
### Verified issue does not already exist?

I have searched and found no existing issue

### What happened?

When importing my budget from ynab some split transactions were ´broken´.

I have a few split transactions that go half to a category and half to a ´lending´ account in my tracking accounts.
However, this split transaction will not be marked as a transfer.

YNAB:
![image](https://user-images.githubusercontent.com/1561671/192999028-b62c902d-772a-45ba-9009-22d9feb41fe7.png)

Actual
![image](https://user-images.githubusercontent.com/1561671/192999448-ed73c908-a894-4d51-9b29-00134b725886.png)

The transaction can be found in the tracking account on actual, but editing this will create a **new** transaction in the original account.

tracking account
![image](https://user-images.githubusercontent.com/1561671/192999959-d51d6e5d-31b4-4e73-aee8-0873a7445902.png)

(after editing the above transaction in the tracking account. This shows up in the original account)
![image](https://user-images.githubusercontent.com/1561671/193000193-19645273-0470-409d-a2a9-3c63af661551.png)

**NOTE**
I´m self-hosting locally with YARN on a LINUX machine and connecting through windows.

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Chrome, Other

### Operating System

Linux

**Comment by MatissJanis** [comment]
👋 Apologies for the super slow response.

Would you mind sharing an example YNAB file showcasing the issue? I'm afraid we won't be able to help without it.

**Comment by MatissJanis** [comment]
Would be definitely nice to do this, but without an example budget this is very difficult to do. Closing this off as abandoned. Please open a new issue and provide example budget (or better yet: a working PR) to see this get done.
