### ISSUE TITLE
Offer to merge transfers to matching transactions

### ISSUE THREAD

**Issue by cclarke591** [actualbudget/actual#2590]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

When setting a transaction as a transfer, and a new transaction is created in the other in budget account, offer to merge the transaction that matches the same date, and amount. Possibly even auto merge if the other accounts transaction has not been catorgorized?

### Describe your ideal solution to this problem

I was thinking a small box that groups the transfer and uncategorized transaction, that prompts the user “Is this the same transaction?” With options “Yes (merge)” and “No (leave separate)” 

### Teaching and learning

I would be more than happy to write documentation for it, as I’m not a JavaScript programmer.

**Comment by UnInfamous** [comment]
It would be ideal to link the two transactions together over merging as currently the date and notes have to be destroyed on the other account. This causes data to be lost for those who want to keep the dates (date of transaction for the different accounts as ACH transfers can take at least a business day, often two; and card network transactions occurring after hours will take the next banking day), and the original notes.

The reason the dates are a big deal for me, is when reconciling the most recent month, or especially past months, the transactions being out of order can become confusing and time-intensive to gain clarity for.
