### ISSUE TITLE
[Bug]: Unable to select date range with static data picker in custom reports

### ISSUE THREAD

**Issue by gsupp** [actualbudget/actual#2592]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

1. Create a new budget file
2. Enable Custom Reports in experimental features
3. Create a new custom report
4. Select "Static" as the date filter
5. For the "From" date, select any month
6. The "From" date changes to the current month, rather than the selected month
7. Subsequent attempts to change the "From" date have no effect, it stays on the current month

This appears to be a regression with v24.4.0, the issue did not occur with v24.3.0. I tested with a new blank budget file and the behavior persists. 

Additionally, I tried modifying an existing report in my live budget file that previously showed data from Sept 2023 to March 2024. I changed the static date filter "To" date to April 2024, which resulted in the report showing data through May 2024. Selecting April 2024 again in the "To" drop-down still resulted in showing report data through May 2024. When I clicked "Update Report" to save these changes, going back into the Reports section of the app now results in the following fatal error:

`RangeError: Invalid time value at ke (https://192.168.14.234:5006/static/js/index.MAk9r4yg.js:114:99862) at sf (https://192.168.14.234:5006/static/js/ReportRouter.mLx3JUh2.chunk.js:65:32413) at Kx (https://192.168.14.234:5006/static/js/index.MAk9r4yg.js:56:19539) at gI (https://192.168.14.234:5006/static/js/index.MAk9r4yg.js:58:44045) at fI (https://192.168.14.234:5006/static/js/index.MAk9r4yg.js:58:39777) at Q4 (https://192.168.14.234:5006/static/js/index.MAk9r4yg.js:58:39705) at Mh (https://192.168.14.234:5006/static/js/index.MAk9r4yg.js:58:39557) at L0 (https://192.168.14.234:5006/static/js/index.MAk9r4yg.js:58:35921) at uI (https://192.168.14.234:5006/static/js/index.MAk9r4yg.js:58:34870) at E (https://192.168.14.234:5006/static/js/index.MAk9r4yg.js:43:1552)`

### Where are you hosting Actual?

NAS

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Linux

**Comment by youngcw** [comment]
Can you try demo.actualbudget.org.  I cant recreate your issue, so its probably already fixed

**Comment by gsupp** [comment]
Good catch, I can't recreate the issue on demo.actualbudget.org either. I also noticed some behavior change with the date picker, such as only showing dates in the drop-down that have transactions within that time period.
