### ISSUE TITLE
[Bug]: Text overlap in Report budget Mode.

### ISSUE THREAD

**Issue by adityatelange** [actualbudget/actual#2600]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Thank you for this tool! :)

I use Report budget Mode and for current month where projected savings are displayed, summary row in the top has text overlap on small screen mobile devices.

![image](https://github.com/actualbudget/actual/assets/21258296/d618b550-e8f5-4fa1-b3e9-afd0fedd92cb)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mobile Device

**Comment by youngcw** [comment]
@adityatelange Can you try using the demo at demo.actual.budget.org?  There were some other mobile changes that probably fixed this issue.

**Comment by sierikov** [comment]
Cannot reproduce. Can you please provide more details?

<img width="642" alt="Screenshot 2024-04-25 at 22 04 09" src="https://github.com/actualbudget/actual/assets/22551739/fd109468-7722-421c-bff6-11ad87661976">

**Comment by youngcw** [comment]
There have been some updates to mobile so its possible this issue was fixed by those updates.

**Comment by adityatelange** [comment]
> There have been some updates to mobile so its possible this issue was fixed by those updates.

Yes this seems to be fixed with #2624. Can be closed.
