### ISSUE TITLE
[Feature] Notes for one-time expenses

### ISSUE THREAD

**Issue by leon-wbr** [actualbudget/actual#2602]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I have expenses that vary from month-to-month and can be budget accurately, but there is no way to note down why a month has a higher expense than another one.

In my old budget sheet, I'd just add a note to the field with the value and it'd remind me. In Actual Budget, there is no way to do so and I have to resort to category / month notes. It is not as easily accessible as I'd wish.

### Describe your ideal solution to this problem

Make it possible to attach notes to each budgeted position. It can be shown on hover with the edit being in the dropdown.

**Comment by MatissJanis** [comment]
Notes can be set on both - budget months and also on specific expenses. Is that what you're looking for?

<img width="504" alt="Screenshot 2024-04-14 at 20 10 35" src="https://github.com/actualbudget/actual/assets/886567/af5baf62-c631-4b01-afb9-b1f0adad6021">
<img width="756" alt="Screenshot 2024-04-14 at 20 11 09" src="https://github.com/actualbudget/actual/assets/886567/68324d4a-715e-4dff-a288-42d6d2260bc0">

**Comment by leon-wbr** [comment]
No, slight misunderstanding. I don't know what the right terminology would be.

I'll just give an example from my old sheet:

![image](https://github.com/actualbudget/actual/assets/8378241/484d6a95-7821-4a84-b916-78ea0c5ae879)

I'm putting a projected expense into my budget for October, which I know will be the Google Drive. I don't want to create a separate category for this as it is a yearly expense that can easily be put into my general "business" category.

In Actual Budget I keep forgetting when exactly I'll have an expense. I could perhaps create a future expense, but that is confusing to me as it skews my budget figures. Perhaps I'm doing it wrong? 

I really prefer report budgeting and have been using that for now.

**Comment by MatissJanis** [comment]
You can use schedules for recurring projected future expenses. Or just plain-old expenses in the transaction table with future dates. For both of these you can set a note.

https://actualbudget.org/docs/tour/schedules

**Comment by leon-wbr** [comment]
Don't both of these options immediately change my account balance? It's not extremely suitable for long-term planning.

I really would prefer to use schedules for that, but the behavior in Actual doesn't make sense to me. I tend to avoid that feature for reaons already outlined by others in #2354.

Budget goal templates with the schedule budgeting would be one way to solve that issue, but it still doesn't allow me to keep a good overview. If I'm thinking a bit further ahead, those templates could even auto-fill the note that I'm hoping to have.
