### ISSUE TITLE
[Bug]: Tooltip scrollbars always showing

### ISSUE THREAD

**Issue by joel-jeremy** [actualbudget/actual#2621]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

![image](https://github.com/actualbudget/actual/assets/20313680/520c045b-3bb9-42be-9bdb-ca92863a751e)
![image](https://github.com/actualbudget/actual/assets/20313680/736e4147-f808-494b-96ab-f1de81787b91)

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome, Other

### Operating System

Windows 11

**Comment by MatissJanis** [comment]
Sadly I can't reproduce on OSX. But my guess would be that updating [this line](https://github.com/actualbudget/actual/blob/1e3fb672fbb86f9823133bc586ee4c193b88fb76/packages/desktop-client/src/style/styles.ts#L138) to `auto` _might_ solve the problem.

<img width="203" alt="Screenshot 2024-04-18 at 20 03 43" src="https://github.com/actualbudget/actual/assets/886567/59a26f77-0537-4ffe-8cf5-a909cea6055e">

**Comment by joel-jeremy** [comment]
That seems to fix the issue but I also seem to remember the scrollbar looks different than before.

**Comment by MatissJanis** [comment]
I'd be more than happy to work on this, but sadly I'm on OSX that doesn't have the issue.

My guess would be that we could apply one of the scrollbar styles here too. That _should_ do the job.

https://github.com/actualbudget/actual/blob/5f77b87b071a38dedfa78f337d59eeedb3778703/packages/desktop-client/src/style/styles.ts#L154
