### ISSUE TITLE
[Bug]: Custom Report - Line Graph in Dark and Midnight themes use different X and Y axis font colours to other custom graphs.

### ISSUE THREAD

**Issue by Teprifer** [actualbudget/actual#2625]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Edge build pulled an hour or so ago:

Midnight theme:

Line graph axis:
![image](https://github.com/actualbudget/actual/assets/34882928/4303897a-25a0-443c-9426-8a004162b4f2)

Other graph axis:
![image](https://github.com/actualbudget/actual/assets/34882928/f3f31b1c-4f3c-404f-bd56-7ba96efb34da)

Dark theme:

Line graph axis:
![image](https://github.com/actualbudget/actual/assets/34882928/a9889a82-e2bb-46c1-9625-a9e8b5a7f407)

Other graph axis:
![image](https://github.com/actualbudget/actual/assets/34882928/a2956288-5c25-47d5-9dc5-afb8c758f8e9)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 11

**Comment by carkom** [comment]
Close by #2636
