### ISSUE TITLE
[Bug]: Filters list isn't in order

### ISSUE THREAD

**Issue by Teprifer** [actualbudget/actual#2626]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

The filters list isn't alphabetical, making it come across incoherent as items aren't where you'd expect to find them in the list:

![image](https://github.com/actualbudget/actual/assets/34882928/d5fc1926-ac4a-4cd0-a2ff-f7ba394fea91)
D, A, P, N, C, A, C, R, S

Alphabetical would be:

Account
Amount
Category
Cleared
Date
Notes
Payee
Reconciled
Saved

(Similar to #1284 but for the filter types themselves)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 11

**Comment by Teprifer** [comment]
Occurred to me these line up to the order of columns in accounts, which provides some reasoning, but the same filter list is used in graphs where that logic doesn't apply so alphabetical seems suitable, and still does on the accounts screen.

**Comment by dangrous** [comment]
I made a draft PR on my fork - https://github.com/dangrous/actual/pull/1 - but I'm not confident we need to fix this... I can see it both ways. Is there a way to bring it up for discussion?

**Comment by Teprifer** [comment]
Could see if anyone chimes in over the next few days. I doubt anyone will have strong feelings on it either way.

It would be good to have them in an order that makes sense in all contexts rather than the one.

**Comment by youngcw** [comment]
@dangrous If you want to open a PR with your change, that could be a good place to discuss

**Comment by dangrous** [comment]
Yeah fair - I'll get that up today!

**Comment by dangrous** [comment]
Linked above!
