### ISSUE TITLE
[Bug]: "," separator not handled in split amount fields

### ISSUE THREAD

**Issue by joklek** [actualbudget/actual#2629]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

On iOS Safari, New Transaction screen, amount field uses the numerical keyboard. On my locale the decimal separator is ",". Entering amounts like "12.34" works fine, as Actual converts the comma into a dot separator after I finish entering the amount. 

The bug happens if I try to split the transaction. When entering amount into the split amount field, it no longer handles "," as a separator, and just deletes it from a number. "12.34" becomes "1234", which is then very hard to edit. Same bug is reproducible in Transactions view on Desktop, not logging a new bug yet because I don't know how components reused, might be the same thing as here.

Client version: v24.4.0

### Where are you hosting Actual?

None

### What browsers are you seeing the problem on?

Safari

### Operating System

Mobile Device

EDIT: From the first look this is what handles my happy case

https://github.com/actualbudget/actual/blob/407ad4deeee9077ce0060d2f5852a43bc369a8a7/packages/desktop-client/src/components/mobile/transactions/FocusableAmountInput.tsx#L70

**Comment by Wizmaster** [comment]
Hello @joklek 

If I understand correctly your issue, you are running Actual with a number format set to dot as decimal separator on a device with the comma separator set in the locale settings.
I believe the easiest would be to set Actual to also use comma as a decimal separator, something you can do in the Settings on the mobile device.

I was working on a feature rather close to your issue, allowing to use comma or dot decimal separator for locales where it's not used as a thousand separator, maybe it could also fit your use-case?
You can test it on #2672

**Comment by joklek** [comment]
@Wizmaster Hmm, somehow I missed the Actual settings for number formats. Will take a look at that and your PR. Closing bug
