### ISSUE TITLE
[Feature] Import C43

### ISSUE THREAD

**Issue by MilorES** [actualbudget/actual#2660]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Import Spanish banks

### Describe your ideal solution to this problem

It has its own standard. Which is why starting the application is complicated

**Comment by mcalligator** [comment]
Could you elaborate on what standard(s) Spanish banks use for account data export?

**Comment by MilorES** [comment]
It seems that now, with the European SD2 regulation, they are required to have an API, so it might be better to explore there, for example:
https://market.apis-i.redsys.es/psd2/xs2a/node/4573

The file is in "Norma 43" or "Cuaderro 43" format. There is information at this link, although in Spanish:
https://getquipu.com/blog/norma-43/

I've tried to find some technical documents but without luck.

Although there are some projects on GitHub (in different languages):
https://github.com/sergief/norma43parser
https://github.com/sequra/norma43_parser
