### ISSUE TITLE
[Bug]: Hotkeys for bulk edit  notes and category do not clear hotkey from input

### ISSUE THREAD

**Issue by matt-fidd** [actualbudget/actual#2662]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?
When using the bulk edit hotkeys to edit notes or categories the input box opens containing the hotkey. E.g.. when I go to edit the category and press "c" the category autocomplete box is populated with a "c" already.

To replicate, select two or more transactions and press "c" to open the category autocomplete modal. It will already contain the "c" from the hotkey press. The same happens with the notes modal.

### Where are you hosting Actual?
Self hosted

### What browsers are you seeing the problem on?
At least Chromium-derived and Firefox

**Comment by shall0pass** [comment]
I don't think this bug exists on the master branch.  Could you verify on https://demo.actualbudget.org ?

**Comment by matt-fidd** [comment]
You're correct, sorry about that! Thank you.
