### ISSUE TITLE
[Bug]: Site crashes when clicking on "Move schedule" text

### ISSUE THREAD

**Issue by HWiese1980** [actualbudget/actual#2678]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

1. I create a schedule
2. I set a date
3. I (accidentally) click on the "Move schedule" text
4. **Chrome** tab crashes

Tried Safari as alternative on MacOS: no issue. Works like expected.

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by HWiese1980** [comment]
To add to this: "other" hosting in my case means a home-lab Kubernetes cluster.

**Comment by HWiese1980** [comment]
Well, now it doesn't anymore... I do not know what I did to make it work again. It just did, all of a sudden.

**Comment by youngcw** [comment]
Ill close this off for now, but if it happens again feel free to reopen the issue.

**Comment by HWiese1980** [comment]
I will. It's really weird. I couldn't even see any error message. The tab just crashed, every time I clicked on the text (not the checkbox, the text only, and only there).
