### ISSUE TITLE
[Feature] Apply Rules for Reconciliation

### ISSUE THREAD

**Issue by nicedevil007** [actualbudget/actual#2686]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

After reconciliation at the end of the month the rules that should apply do not apply.
F.e. I created a rule that should apply on transaction with the Notes "Reconciliation balance adjustment"

### Describe your ideal solution to this problem

Is it possible to let rules run after the reconciliation transaction was added?

**Comment by youngcw** [comment]
#3625
