### ISSUE TITLE
[Feature] Ability to set custom filters on budget page

### ISSUE THREAD

**Issue by montesfjose** [actualbudget/actual#2694]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

My issue stems from being mostly a mobile user.

Making purchases away from the computer for me has to be as convenient as possible, so adding in a way to filter out categories quickly would be ideal. A great way to do that is with **custom filters**. Below is an image from the YNAB4 classic app where I added in a special character to relevant categories to create a thematic "view" of sort, and searched for that special category to filter for them.
<img src="https://github.com/actualbudget/actual/assets/43690521/e6b6d6de-3bed-485a-bc7a-9a0de7431b86" width=25% height=25%>
 The big difference is that from here in Actual I would be able to reallocate funds around, while I could not do that in YNAB4

YNAB SAAS currently has this feature named as "Views."

### Describe your ideal solution to this problem

Ideally in Actual budget, the process would be much simpler. Setting a custom filter with selected categories, and toggling the filter on/off would work.

The filters themselves could live in a carrot dropdown menu when hovering your mouse over the "Category" section (similar to when hovering over a master/subcategory).

On mobile, it could live in the 3 dot menu that sits in the top right corner of the screen.

### Teaching and learning

Nothing to say here, as filters themselves are basic in function.

**Comment by psybers** [comment]
Duplicate of #559.
