### ISSUE TITLE
[Bug]: Mobile transaction entry 'remembers' last category on 2nd entry

### ISSUE THREAD

**Issue by shall0pass** [actualbudget/actual#2697]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

When manually entering a transaction on the mobile pages, on the first transaction entry the payee and category are blank and need to be filled.  This is what I expect.  If you then add a second transaction, the category field remains filled.  I expect this to remain blank.  

Why it matters:
I have rules set up to populate the category based on the payee.  If the category is prefilled, my rules will not apply.  

The mobile entry did not used to prefill the category, so this feels like a regression to me.

### Where are you hosting Actual?

NAS

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mobile Device

**Comment by tasawar-hussain** [comment]
I would like to work on it

**Comment by brasilikum** [comment]
Even if it's a transfer, the category of the last transfer is shown
