### ISSUE TITLE
[Bug]: Offset Category Selector on Desktop (visual indicator) On Transactions

### ISSUE THREAD

**Issue by duplaja** [actualbudget/actual#2701]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

In certain circumstances, the visual indicator for the selected category in the dropdown (when modifying category per transaction) is offset from the actual mouse pointer, on desktop / laptop. 

This is purely a visual bug, because clicking still selects the one the mouse pointer is on. This is more noticeable if you pick transactions further down the screen, visually.

https://github.com/actualbudget/actual/assets/20245408/82765a65-2e15-4927-8c7b-a4f11d19578f

I was finally able to narrow this down to having a hidden category. Steps to recreate:

* Create a hidden category, at the top of the first subgroup.
* Try to edit the category of a transaction on any of the account pages.
* Everything that occurs below the hidden category will be offset, visually

I've been able to recreate this on the newly updated demo instance, as well as my own.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Linux

**Comment by youngcw** [comment]
I believe this is fixed now.

**Comment by duplaja** [comment]
My apologies, had missed this notification. Thank you!
