### ISSUE TITLE
[Bug]: some modals - missing bottom margin/padding

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#2702]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

These modals are missing bottom margin/padding. There might be more that I haven't noticed.

<img width="545" alt="Screenshot 2024-05-04 at 11 59 24" src="https://github.com/actualbudget/actual/assets/886567/21597f8e-5cc4-4529-bd96-92896641b4e3">
<img width="687" alt="Screenshot 2024-05-04 at 12 01 56" src="https://github.com/actualbudget/actual/assets/886567/5ff97374-7546-4490-8f16-f8b7a1f8e28e">

### Where are you hosting Actual?

None

### Operating System

None

**Comment by uniqueeest** [comment]
Hello! @MatissJanis.  I'm interested in this issue. I've done it in that order for my work locally now, but it doesn't work. Is there anything else I need to do?
- Install and start within the desktop-client folder
- "Uncaught TypeError: Cannot read properties of undefined (reading 'onEventFromMain')" error

**Comment by uniqueeest** [comment]
@MatissJanis 
<img width="682" alt="스크린샷 2024-05-05 오전 11 25 15" src="https://github.com/actualbudget/actual/assets/123538138/f170af0e-328e-4c11-8cc3-5dcb6a05ab9a">
<img width="641" alt="스크린샷 2024-05-05 오전 11 25 33" src="https://github.com/actualbudget/actual/assets/123538138/fe10aef7-4e9d-4c6a-ba65-56b115323166">

Which one do you think looks better between the two?

**Comment by MatissJanis** [comment]
First one I think. Ideally we should have consistency across all modals here. Here's an example for schedule creation modal:

<img width="730" alt="Screenshot 2024-05-05 at 19 27 35" src="https://github.com/actualbudget/actual/assets/886567/1fa0bcfa-c055-4c60-b755-1f54cacf6b05">
