### ISSUE TITLE
[Bug]: Hide reconciled transactions - wrong balance shown

### ISSUE THREAD

**Issue by ngocphamm** [actualbudget/actual#2703]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Balance on the account is shown differently when reconciled transactions are hidden.

Not hidden

![CleanShot 2024-05-04 at 10 27 15](https://github.com/actualbudget/actual/assets/395123/27d6b1ea-07ec-4f36-afe0-b8bc314b2a70)

Hidden

![CleanShot 2024-05-04 at 10 27 36](https://github.com/actualbudget/actual/assets/395123/ffb55a0e-f495-409f-8fba-2ccddfbac7b2)

I think another person experienced this too https://github.com/actualbudget/actual/issues/2503#issuecomment-2094151378

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Mac OSX

**Comment by ToniCipriani** [comment]
Issue confirmed on Windows and Android PWA as well.

**Comment by MatissJanis** [comment]
👋 Would you mind providing a demo budget export so folks can reproduce the issue?
Thanks

**Comment by ngocphamm** [comment]
@MatissJanis Please use this one.

[2024-05-06-My-Finances-2befb2e.zip](https://github.com/actualbudget/actual/files/15221673/2024-05-06-My-Finances-2befb2e.zip)

**Comment by joel-jeremy** [comment]
The issue occurs because the running balance calculation runs the calculations based on the queried transactions. In the case of hiding the reconciled transaction, the reconciled transaction are being excluded from the query hence the calculation is returning the wrong results.

I can think of two possible ways to fix this:
1. Revert the query to fetch all transactions (including reconciled) but do not render the reconciled transactions. 
2. When toggling the reconciled transactions, recalculate the starting balance in which the running balance calculation will start from.

**Comment by youngcw** [comment]
> The issue occurs because the running balance calculation runs the calculations based on the queried transactions. In the case of hiding the reconciled transaction, the reconciled transaction are being excluded from the query hence the calculation is returning the wrong results.
> 
> I can think of two possible ways to fix this:
> 
> 1. Revert the query to fetch all transactions (including reconciled) but do not render the reconciled transactions.
> 2. When toggling the reconciled transactions, recalculate the starting balance in which the running balance calculation will start from.

I think either of those would work.  The one small thing with option 1 is that the transactions may not be contiguous and that would make the running balance not align perfectly with the shown transactions.  Option 2 would get around this, but could be annoying to users who would like both.

**Comment by atgrey24** [comment]
> I think either of those would work. The one small thing with option 1 is that the transactions may not be contiguous and that would make the running balance not align perfectly with the shown transactions. Option 2 would get around this, but could be annoying to users who would like both.

I think it's ok if the running balance is not contiguous, so long as it's accurate to what the balance was at time of the transaction. It sounds like option 1 would give this result.
