### ISSUE TITLE
[Bug]: "Show advanced settings" not accessible on mobile

### ISSUE THREAD

**Issue by joklek** [actualbudget/actual#2704]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

"Show advanced settings" link hidden under the actions drawer (the thing which has Budget, Transaction, Accounts). Noticed this in v24.5.0, on iOS, using Safari.

### Where are you hosting Actual?

None

### What browsers are you seeing the problem on?

Safari

### Operating System

Mobile Device

**Comment by youngcw** [comment]
Are you saying that you cant get to the button at all?

**Comment by joklek** [comment]
I should've included a videohttps://github.com/actualbudget/actual/assets/31686813/06f669e2-ee72-4c45-aec6-5f9557f180b0

**Comment by youngcw** [comment]
If you scroll back to the top of the page, then down does the footer not collapse?

**Comment by joklek** [comment]
The footer collapses for a second and then reappears. Here's a video where I accidentaly (for the first time in like 10 minutes) managed to get advanced settings unhidden

https://github.com/actualbudget/actual/assets/31686813/eaa79bf5-eb12-4433-9fc4-764307cae2c0

**Comment by youngcw** [comment]
Weird. That definitely seems broken

**Comment by joel-jeremy** [comment]
Fixed by https://github.com/actualbudget/actual/pull/2733
