### ISSUE TITLE
[Feature] Add loan report with trend lines

### ISSUE THREAD

**Issue by fossum** [actualbudget/actual#2708]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I have a couple loans and being able to see their progress is a huge motivation. 

### Describe your ideal solution to this problem

I'm thinking something simple at first with historical data and then add a trend lines with minimum payment, based on recent payments, etc. 

How one enables the report needs more thought, but maybe an option on an account. This would then have more settings for APR, minimum payment, etc.

I'm not a web developer, but if someone held my hand I could probably try.

### Teaching and learning

I would think finding it would be obvious in the reports page.

**Comment by UnInfamous** [comment]
Yeah, it would be great to help incentivize those who need the extra push to spend higher than the minimum monthly (like my partner) to do so by whatever tool is accessible on a monthly basis (Actual).

**Comment by sexyskinnybitch** [comment]
This is one feature I do miss from YNAB, it allows me to see my progress towards paying my loans off.
