### ISSUE TITLE
[Bug]: Cash flow report labels not rendering properly for new accounts with no transaction history

### ISSUE THREAD

**Issue by sehnsucht13** [actualbudget/actual#2710]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

The `Cash Flow` report labels for `Income` and `Expenses` are rendered on top of each other for new accounts with 0 transactions.

![image](https://github.com/actualbudget/actual/assets/7553015/074904a9-ef0f-42d9-bf1c-3eb4f2475a2b)

# Steps to reproduce:
1. Start a new actual instance using the Docker instructions [in the wiki](https://actualbudget.org/docs/install/docker/#launch-container-using-docker-command).
2. Navigate to `Actual` using firefox (Version: `125.0.3 (64-bit)`)
3. Enter a new password for the instance
4. Navigate to the `Reports` section using the sidebar
5. You should see the `Cash Flow` chart labels on the X-Axis overlapping with one another.

# Notes
- Adding some sort of income fixes the `Cash Flow` graph
- I'm running Actual using Ubuntu via WSL on windows 10.
- The same issue might happen with other browsers but  I haven't tested it.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

**Comment by Tigatok** [comment]
Is hiding the bar graph when income/expense === 0 a valid strategy here? Fixed, with offset stuff looks like this:
![image](https://github.com/actualbudget/actual/assets/3906461/b6462f2b-e4b8-4f13-9f0a-70d051dccacd)

If we remove when 0, 
![image](https://github.com/actualbudget/actual/assets/3906461/36edc312-7a9c-4259-b2ef-1e8e2e690ea3)

Finally, if we stick to offset of 20, we can ensure that the income will always be on the left/expense on the right
![image](https://github.com/actualbudget/actual/assets/3906461/9f7c68f1-cac5-4df7-8c5d-07d3db560638)
