### ISSUE TITLE
Update balance of SimpleFin linked investment accounts when syncing [Feature] 

### ISSUE THREAD

**Issue by mmcc-xx** [actualbudget/actual#2718]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

One of my desired uses cases for Actual Budget is monitoring my net worth. I've been able to link my investment accounts with the brokerages with SimpleFin, and Actual pulls in an initial balance and transactions. However, it does not update the balance when syncing. The new balance is coming in from SimpleFin (see screenshot) but it is not incorporated into the balance of the account.
![actualbudget](https://github.com/actualbudget/actual/assets/1315341/b3c5e537-a1ae-4eb1-85f0-99ea788d4d00)

By the way, I'd be happy to work on this feature, but I could you some advice for how to do in keeping with the goals of Actual. Would a "balance adjustment" transaction be needed?

### Describe your ideal solution to this problem

Every time a SimpleFin linked account is synced, the balance of the account is updated to reflect the balance reported by SimpleFin.

**Comment by mmcc-xx** [comment]
Upon further investigation, I think this is a bug. I'll submit a bug report.

**Comment by mmcc-xx** [comment]
Upon analysis of the bug, this was determined to be a feature request :)

**Comment by gitchap** [comment]
personally I would like this for all accounts, maybe not an auto balance update -- but maybe when reconciling, you would have the OPTION to use the "sync'd balance", OR some manually entered balance.

So the end user work flow would be like this:
1. sync accounts
2. click the reconcile icon
3. choose "fill from synced balance" (or something to that effect)
4. create adjustment entry
5. click done

I suppose if there was a button next to the reconcile button that would do all that in one click that would be pretty nice too.

**Comment by youngcw** [comment]
There is now a fairly simple way to do this, but still not a way for it to happen automatically.
1. (optional) Go to the bank sync settings and the account in question.  Select "Investment Account"
2. After syncing from simplefin, click the reconcile button, then choose the previously synced balance, then Reconlcile
3. Make a reconciliation transaction to bring the account balance up to date, the click Done Reconciling

Only steps 2 and 3 need done each time you update the balance.  Its quick to do as its just a few clicks and you don't need to look up the balance since its already saved in Actual

**Comment by adivardhan1000** [comment]
> There is now a fairly simple way to do this, but still not a way for it to happen automatically.
> 
>     1. (optional) Go to the bank sync settings and the account in question.  Select "Investment Account"
> 
>     2. After syncing from simplefin, click the reconcile button, then choose the previously synced balance, then Reconlcile
> 
>     3. Make a reconciliation transaction to bring the account balance up to date, the click Done Reconciling
> 
> 
> Only steps 2 and 3 need done each time you update the balance. Its quick to do as its just a few clicks and you don't need to look up the balance since its already saved in Actual

This option is available with the v25.x release. It took me a while to realize this.

**Comment by junalmeida** [comment]
@adivardhan1000 Is there a way to update the balance for the reconcile button via the actual budget API? I quit using SimpleFin and I have developed my own importers, but I couldn't find a way to update Actual with the latest account balance for reconciliation.

**Comment by adivardhan1000** [comment]
> [@adivardhan1000](https://github.com/adivardhan1000) Is there a way to update the balance for the reconcile button via the actual budget API? I quit using SimpleFin and I have developed my own importers, but I couldn't find a way to update Actual with the latest account balance for reconciliation.

You could refer to https://github.com/actualbudget/actual/blob/master/packages/sync-server/src/app-simplefin/app-simplefin.js to see how balances are updated or propogated. I think mocking the simplefin api with your own custom endpoint could be one way. 
I am not aware of anything on top of my head.

**Comment by Juulz** [comment]
The synced balance was added here:

https://github.com/actualbudget/actual/pull/4799
