### ISSUE TITLE
[Bug]: Monthly spending report errors

### ISSUE THREAD

**Issue by joel-jeremy** [actualbudget/actual#2732]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Steps to reproduce:
1. Enable Monthly spending experimental feature
2. Open Monthly spending report

![image](https://github.com/actualbudget/actual/assets/20313680/160ca44d-6ee4-4e17-affd-a7d6a72b7c28)

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome, Other

### Operating System

Windows 11

**Comment by Redbox3070** [comment]
Not sure if it is the correct place but I also wanted to report that monthly spending currently includes off budget items

**Comment by carkom** [comment]
Fixed by #2745
