### ISSUE TITLE
[Bug]: Applying budget templates takes 30 seconds

### ISSUE THREAD

**Issue by deermo** [actualbudget/actual#2741]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I set up my budget with templates for each category (around 50 categories), and applying those worked out fine. Then I imported all my old transactions (3500) to a local account. Since then, applying templates takes 30 seconds without producing any error. The browser console does not show any errors.

Initially, I had encryption turned on. I imported the budget without encryption, but the error persists.

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Firefox

### Operating System

Mac OSX

**Comment by youngcw** [comment]
What does it look like while you are waiting those 30s?  Is it nothing then they apply all at once? Or is it pieces at a time?

If you click the sync button in the top right does it stop spinning quickly, or does it take a long time?

**Comment by deermo** [comment]
The interface is completely frozen during this time. When I click sync, the wheel does not spin until the budgets are calculated, an all other actions are „ignored“

**Comment by youngcw** [comment]
For the sync button, I was meaning on its own, not during a template apply.  Im wondering if your server syncing is really slow for some reason and that is why the templates take so long

**Comment by deermo** [comment]
Everything else syncs nice and very fast, I'd say the usual sync is around 0.3 seconds roughly?

**Comment by joel-jeremy** [comment]
I also noticed a bit of a slow down when I tried running some templates recently
