### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by d3relict** [actualbudget/actual#2742]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

`#template up to {value}` does not take recent spendings into consideration, also uses the `{value}` as a max allocatable amount.

example: 
i have a leftover of 10 usd in my category, and i have `#template up to 100` set up. i already spend 10 usd in this month, before i set up my monthly budget.
in this scenario, "up to" will assign 100 usd to match the template, but _in my understanding_, it should've only assigned 90, so raise the budget to 100, regardless of my recent spending in the actual month.
if my current spending is 20, so i have a running balance of -10 in that category, the assigned amount will be 100, and not 110, which seems inconsistent to the previously observed logic.

expectation:
if i set "up to" in my template, and i have a leftover of 10 usd in the previous month, only assign 90 to the category, regardless of my current spending.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 10

**Comment by youngcw** [comment]
Im not able to recreate this.  When I try your example, I get the expected 90  Could you upload an example budget file?

**Comment by d3relict** [comment]
after starting a new budget to repro, i also can not reproduce this. i went back to my original budget, and wanted to make screenshots, but now it also provides proper results. i have no idea what changed, apart from loading/unloading the budget, or the browser being closed in the meantime, etc.
