### ISSUE TITLE
[Bug]: Link your bank scroll list unavailable

### ISSUE THREAD

**Issue by Ap0ph1s-W4ite** [actualbudget/actual#2744]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

A bug happened!

Missing scroll on "Link your bank List". Necessary to use the keyboard arrows to select.
![image](https://github.com/actualbudget/actual/assets/6775289/34f3bcde-fb96-406c-bb66-fdce1e23600e)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 10

**Comment by MatissJanis** [comment]
👋 I am actually unable to reproduce this.

Can you check the issue on https://edge.actualbudget.org and see if it's still there (you'll need to connect it to your server)?

Thanks

**Comment by Ap0ph1s-W4ite** [comment]
Hi,

I am receiving this error `Unable to contact the server`. I have switch off my Cloudflare rules and the password is correct.
Am I doing something wrong?

**Comment by MatissJanis** [comment]
I'm guessing you are missing CORS headers there.

Another option: try deploying the `edge` container (it's a tag). And see if the `edge` version works for you better than whatever you are currently using.

**Comment by Ap0ph1s-W4ite** [comment]
Hi,

I am on vacation but I will try edge version this week. I will give you my
feedback ☺️

Matiss Janis Aboltins ***@***.***> escreveu em sex.,
17/05/2024 às 20:03 :

**Comment by Ap0ph1s-W4ite** [comment]
Hi,

Installed the edge version and seems to be fine. Thanks for your time! 😃 

![image](https://github.com/actualbudget/actual/assets/6775289/4d5564c1-477f-42c5-a9b9-4929a82f9a98)
