### ISSUE TITLE
[Bug]: Web - Clicking category in drop down stopped working

### ISSUE THREAD

**Issue by tiagodj** [actualbudget/actual#2751]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

In the web budget view, I want to transfer some of the balance of one category (or to be budgeted) to another category.

All of the below steps are done using the mouse.

Steps to reproduce:
1. Click balance on end of a Category line
2. Click "Transfer to another category"
3. Enter amount
4. Click "To" field
5. Category pop-up opens
6. Click destination category
7. *pop-up disappears, nothing was transferred*

Notes:
- When selecting the destination using the Category pop-up, if I type arrow down (instead of clicking on a Category) and hit Enter, then the Category is correctly selected and I can click Transfer and it goes through.
- Seems to be an issue specifically when using the mouse/tap.
- This was working before a few versions ago, don't remember exactly which one.
- I am self-hosting it.

Platforms where it was observed:
- Safari browser @ MacOS
- Edge browser @ macOS
- Safari browser @ iOS

Version:
Client version: v24.5.0
Server version: v24.5.0

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Safari, Microsoft Edge

### Operating System

Mac OSX

**Comment by joel-jeremy** [comment]
@MatissJanis This looks related to the popover migration

**Comment by MatissJanis** [comment]
Fix is in #2724
