### ISSUE TITLE
[Bug]: Payee, Notes and Amounts are mixed after syncing new payments

### ISSUE THREAD

**Issue by dawogid** [actualbudget/actual#2752]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I've been using Actual Budget (Server) for about 2 months, and it has been great! I'm syncing my account to import all payments using GoCardless. Everything was working perfectly until yesterday. When I clicked on Sync for my private account, new payments from the last week were imported.

Unfortunately, the Payees, Notes, and Amounts are now completely mixed up in freshly imported payments. I tried clearing the cache and resetting the sync, but it did not help. Even when I remove payments from the last week and re-import them, I still get incorrect results. It seems this issue starts from a specific payment, as all previous payments reimports correctly(when I remove and reimport payments from the last two weeks). I also tried to remove all rules and reimport payments without them, but it also did not help. Is this something that happened in the past?

Used version: **24.4.0**

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Operating System

Windows 11

**Comment by dawogid** [comment]
Response from GoCardless - they are aware of this problem and they are working on it:
![obraz](https://github.com/actualbudget/actual/assets/140388441/a649a1b4-627a-4c16-b78b-759c5594d542)

**Comment by youngcw** [comment]
Since GoCardless is going to fix this, ill close this issue.
