### ISSUE TITLE
[Bug]: Search using Cyrillic symbols is not working in Account view

### ISSUE THREAD

**Issue by mioiox** [actualbudget/actual#2755]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

**Environment overview:**
I use Actual Server v24.5.0, accessed over web and over Electron desktop app v24.5.0. 

**Accounts overview:**
I have over 10 different accounts. Some are connected/bank synced, some are local only.
I use a mixture of Latin and Cyrillic words within payee, notes and category fields.

**Issue description:**
When I am in Account view and I try to search for a specific entry, search displays no entries when search using Cyrillic symbols, and displays the expected ones when searching using Latin symbols.

**Exhibit A: Account Overview (a mixture of Latin and Cyrillic letters can be seen correctly):**
<img width="926" alt="image" src="https://github.com/actualbudget/actual/assets/38386386/9ba246df-01b3-43d5-a264-5067207e4e28">

**Exhibit B: Seach using Latin symbols (works as expected):**
<img width="938" alt="image" src="https://github.com/actualbudget/actual/assets/38386386/c3b55ed1-8d1a-4370-9d64-df507b5d30f9">

**Exhibit C: Search using Cyrillic symbols (shows no result, although there are some results that should match):**
<img width="934" alt="image" src="https://github.com/actualbudget/actual/assets/38386386/6bf28e57-638a-4dce-8338-fdba4ac10e0e">

**Exhibit D: I checked if there are issues with different payees in the Payees node. Seach using Cyrillic symbols in Payees node works fine for the very same payee that could not be found in Account node:**
<img width="878" alt="image" src="https://github.com/actualbudget/actual/assets/38386386/647cfbbc-e48f-4f61-9f17-7217040387e1">

**Additional details:**
The same behavior can be observed in any type of account, no matter if it is synced or local.
The same behavior can be observed on both the web and desktop versions.

**Since you might not even have a Cyrillic-keyboard layout, here is a couple of payees I am currently using:**
Еконт
Икеа
Шел

If there is anything else I can cooperate with or provide additional info, please let me know.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Microsoft Edge, Desktop App (Electron)

### Operating System

Windows 11

**Comment by MatissJanis** [comment]
Related: https://github.com/actualbudget/actual/issues/2347

**Comment by dymanoid** [comment]
The root cause for both issues is this: https://www.sqlite.org/faq.html#q18

> The default configuration of SQLite only supports case-insensitive comparisons of ASCII characters.

To solve this, we need to overload the built-in `NOCASE` collating sequence and the built-in `like()`, `upper()`, and `lower()` functions.

Happy to take this one.
