### ISSUE TITLE
[Feature] Decide from which date to sync bank activities

### ISSUE THREAD

**Issue by mosbror** [actualbudget/actual#2756]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I noticed that, after importing my budget from nYNAB, the account sync gets all historic bank data.

### Describe your ideal solution to this problem

As I haven't had a bank sync when I was using YNAB, I've ignored or worked around some transactions.
It would be great if you could set a "from date" when linking the account.

**Comment by mosbror** [comment]
I guess this feature would make this change obsolete: https://github.com/actualbudget/actual/issues/2289

**Comment by youngcw** [comment]
This was added a while back
