### ISSUE TITLE
[Bug]: Rollover Overspending arrow icon obscured by scroll bar

### ISSUE THREAD

**Issue by matt-fidd** [actualbudget/actual#2757]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

When rollover overspending is enabled, the indicator arrow is obscured by the scrollbar on the right.

Can be reproduced on edge.actualbudget.org with a test file, then enable rollover overspending on a category 

![image](https://github.com/actualbudget/actual/assets/81489167/a86c2eca-ec59-4209-9a50-7775db0d5a7f)

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by youngcw** [comment]
Looks like the arrow is shifted to the right compared what it used to be.  That amount of space between the number and the scroll bar looks basically the same as normal
