### ISSUE TITLE
[Bug]: Menus blend in with other elements

### ISSUE THREAD

**Issue by psybers** [actualbudget/actual#2779]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

The popup menus have no border, which means they tend to blend in with other elements behind them making them less obviously a menu:

<img width="334" alt="image" src="https://github.com/actualbudget/actual/assets/1115390/690aa1cf-d6a9-4176-930f-cfaa51921b40">

Simply open any menu and you can observe it.  This affects the dark theme, though technically the other themes also have the problem.  But in those other themes, the shadow added to the menu is enough to make it have somewhat of a border.

<img width="338" alt="image" src="https://github.com/actualbudget/actual/assets/1115390/78519ca9-564e-4311-b4c6-df5c77f88875">
<img width="350" alt="image" src="https://github.com/actualbudget/actual/assets/1115390/608e2b28-84ed-4582-bad1-3ad65839f6bd">

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome, Desktop App (Electron)

### Operating System

Mac OSX

**Comment by Tigatok** [comment]
I think its mostly due to the searchbar background color being very similar to the popup menu color in dark mode, less about the shadow. That being said, some sort of technique could be applied to differentiate better

**Comment by psybers** [comment]
There are other places where this can happen.  I discovered it while working on a popup menu inside a modal.

The dark theme needs to do something around the menus to help give them a border between them and the things behind them.

**Comment by Tigatok** [comment]
It actually doesn't look too terrible with a white border around in dark mode. Maybe something to consider

**Comment by youngcw** [comment]
Those tooltips in darkmode used to be a different color, but it was getting to be such a middle of the road color that it was really hard to have good contrast with non-white text.  We should do something to fix that color being the exact same as may backgrounds, but imo its better than it used to.

**Comment by VoltaicGRiD** [comment]
@psybers Have a look at these screenshots I pulled from the electron app. Let me know what you think:

![image](https://github.com/actualbudget/actual/assets/58367364/621790e1-b056-4654-8e11-6d991a65259b)
![image](https://github.com/actualbudget/actual/assets/58367364/ea68fa6c-427e-428f-a89e-7b3eeff2fafb)

I'm not convinced on the color of the border in light-mode, but it is visible for sure in my opinion.
Alternatively, I found another color that is far more "vocal" but doesn't look quite as clean:

![image](https://github.com/actualbudget/actual/assets/58367364/548b23bc-0197-4752-8853-761b112585b0)

The first one uses `menuItemBackgroundHover`
The second one uses `menuItemTextHeader`

**Comment by psybers** [comment]
@VoltaicGRiD Dark mode looks good. Do we even need to change the light mode ones? I think they worked as is.

**Comment by youngcw** [comment]
I feel like adding borders would feel out of place since none of the other pop ups use borders.  I second that the light theme has no issues as is and should't be changed.

**Comment by VoltaicGRiD** [comment]
@youngcw I'm definitely not against adding borders. I am all for accessibility and I feel like it adds that without detracting from the overall appearance or making it look "ugly" as one might say. Since they use themed variables, I was simply trying to find one that I could just apply globally to the tooltip windows, so in this case, I don't think either is necessarily a bad choice, especially considering they are mostly just a CSS styling choice. 

@psybers Not necessarily, I do like that it stands out more, but I don't think its a requirement for the light theme. Might not be bad to find a middle-ground. I'll play with some colors,

**Comment by VoltaicGRiD** [comment]
Alright, added a section to the themes for each theme that I think, in my non-designer non-frontend experience looks and feels quite nice:

![image](https://github.com/actualbudget/actual/assets/58367364/febffe80-eb6f-423e-b7e7-44d4e7cd932b)
![image](https://github.com/actualbudget/actual/assets/58367364/cdeec575-d1f4-4927-9a44-6def46834709)
![image](https://github.com/actualbudget/actual/assets/58367364/329b6958-bc92-4af0-8e6a-2835e47b6c3b)

Definitely no need for them all to be identical to the background color. Especially on dark themes like Midnight.

**Comment by psybers** [comment]
@VoltaicGRiD Making progress!  I wonder if the color should match the border in between each row in the spreadsheet?  It should still give a defined border, but would match the existing themes a bit more.

**Comment by VoltaicGRiD** [comment]
> @VoltaicGRiD Making progress! I wonder if the color should match the border in between each row in the spreadsheet? It should still give a defined border, but would match the existing themes a bit more.

I don't hate it, but I think that they'd have to all match as themes, so 
![image](https://github.com/actualbudget/actual/assets/58367364/5efdb467-7454-460b-a025-b775179f1d28)
![image](https://github.com/actualbudget/actual/assets/58367364/bf6ec780-250e-4351-8f28-fce21c775618)

(Light doesn't change here, since it already fits that criteria)

If we just take the color from the table, I had to adjust the color of the background otherwise they were identical.

**Comment by psybers** [comment]
I don't know that these are perfect (to me), but they definitely feel closer than the prior screenshots for me.  I think the issue with the prior ones was there was too much contrast between the border and the menu background.  These, there is still contrast but it is more subtle.

With the prior ones, the border actually has more salience than the menu itself, which is probably backward.  With the new versions that problem seems fixed.

**Comment by VoltaicGRiD** [comment]
> I don't know that these are perfect (to me), but they definitely feel closer than the prior screenshots for me. I think the issue with the prior ones was there was too much contrast between the border and the menu background. These, there is still contrast but it is more subtle.
> 
> With the prior ones, the border actually has more salience than the menu itself, which is probably backward. With the new versions that problem seems fixed.

What a fantastic word
> salience

I'll go ahead and commit these for now, I might add some custom shades that fit that 50% for me (gray750 instead of gray800). I think that'll be the solution that pleases everyone. Unless you had a better suggestion of course.

**Comment by psybers** [comment]
@VoltaicGRiD If you have not already done so, I would recommend opening a pull request for these changes so we can work toward merging them later.

**Comment by MatissJanis** [comment]
Related: https://github.com/actualbudget/actual/pull/2815

**Comment by youngcw** [comment]
fixed by #3298
