### ISSUE TITLE
[Bug]: Category dropdown selection gets messed up by hidden categories

### ISSUE THREAD

**Issue by kyrias** [actualbudget/actual#2780]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

1. Open a demo budget.
2. Hide the "Entertainment" category.
3. Open an account view.
4. Click on the category column of a transaction.
5. Hover over the first four categories.

For the first two categories it works fine, hovering over the third category, where the hidden category would be, highlights nothing.  Hovering over the fourth category actually highlights the third category.

### Where are you hosting Actual?

None

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Linux

**Comment by MatissJanis** [comment]
Possibly related: https://github.com/actualbudget/actual/issues/2761

Can you try to reproduce in https://edge.actualbudget.org ? That's the new master branch. We're slowly transitioning over.

"demo." and "app." are now using the last tagged version (v24.5.0)

**Comment by kyrias** [comment]
Ah damn, I was sure I tested it on edge, but apparently I messed up when switching browsers and I didn't double-check which version I was on.  Seems it's indeed already fixed, sorry about that.  (But it's not related to #2761, that's just a request for having them *not* be hidden.)

**Comment by MatissJanis** [comment]
Ah yes, my bad. #2761 is something different.

This was the one I was thinking about: https://github.com/actualbudget/actual/issues/2701 :)
