### ISSUE TITLE
[Bug]: Hidden Category Lost

### ISSUE THREAD

**Issue by rthacku1** [actualbudget/actual#2783]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

In hiding a category, I was not able to retrieve the category. It does not show up under Hidden Categories. Naturally, it's not "lost" as I see it still contributing to category group balances. I can also locate transactions which are associate with this category. 

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 11

**Comment by carkom** [comment]
You'll need to specify some specifics here. Firstly what page are you looking at? Can you see the category under budget list "toggle hidden" on?

**Comment by rthacku1** [comment]
Attached are a few screenshots. You'll see that in Non Monthly there is a category balance of $1000. This is from the "ghost" category. Yet when I look at the Hidden List Toggled On, nothing shows up. This is taken from a browser on mobile but it is the same on my laptop as well.

**Comment by youngcw** [comment]
@rthacku1 attachments can only be added on github, they don't come through via email replies.

**Comment by rthacku1** [comment]
Thanks for the support. I was able to figure it out. 

It turns out in the import from YNAB 'Hidden Categories' was imported and I assumed it worked the same way as it did in YNAB. I found the toggle for hidden categories in the top menu and it reappeared. 

If this is already mentioned someplace, it might be something to just scrub this category on the import if its not used otherwise.

**Comment by youngcw** [comment]
Glad to hear its working for you.  I forgot that the hidden categories are treated as a group on import.
