### ISSUE TITLE
[Bug]: column titles incorrect when selecting transactions and resizing window

### ISSUE THREAD

**Issue by gschmidl** [actualbudget/actual#2784]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

This is the latest version of Actual on the latest patch level of Windows 11.

Step 1: take any size browser window and select a couple of transactions

![image](https://github.com/actualbudget/actual/assets/20334/8d806f51-ebdd-4082-83c1-d726b3f2a246)

Step 2: resize the browser window to fullscreen by double-clicking it - the column headers will be wrong

![image](https://github.com/actualbudget/actual/assets/20334/89573707-864e-4f1c-9a7a-4bd9c4c05e0b)

As soon as you deselect the transactions, the headers are correct again. Simply resizing the window manually also does not seem to trigger this issue.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

**Comment by lelemm** [comment]
@gschmidl try this version: https://deploy-preview-2867.demo.actualbudget.org/
