### ISSUE TITLE
[Feature] Allow option to exclude off budget accounts from "All Accounts" total.

### ISSUE THREAD

**Issue by Snackington** [actualbudget/actual#2791]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Not so much a problem as it is a small annoyance. I linked a few things to off budget just to keep track of (car payment, bank loan, mortgage, etc) and as great as it is to be able to check all of those things with a quick glance it's kind of a bummer to see my "All accounts" balance so far in the negative. I can absolutely overlook it, but maybe the option to not include the off budget balances in the all accounts total would be helpful.

**Comment by youngcw** [comment]
Would this be any different than the current For Budget total?

**Comment by Snackington** [comment]
No, I suppose it wouldn't, I guess what I was thinking would be like a checkbox of "Add to All Account Total" for each account. Like I said, not even a big thing, just a little QoL improvement.
