### ISSUE TITLE
[Bug]: SimpleFIN sync only executes if MX provides org domain

### ISSUE THREAD

**Issue by cjfagerstrom** [actualbudget/actual#2794]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### Summary
After an initial sync with SimpleFIN, subsequent syncs will only be executed if MX provided an org domain for the bank. This org domain is stored in the `banks` table in the `bank_id` column. Either the `id` column from the `banks` table, or the `account_id` column from the `accounts` table should instead be used to ensure SimpleFIN always syncs when there is a connected external account.

### Reproducing
Export a copy of a budget. Open the `db.sqlite` file and navigate to the `banks` table. Delete the `bank_id` value for an entry. Save the database changes & zip the file. Import back to Actual Budget and attempt to sync accounts and they will not sync. MX does no provide the org domain which is used for the `bank_id` value for all banks.

Alternatively, take a non-syncing `db.sqlite` file and add the url for the bank (www.somedomain.tld) to the missing `bank_id` value and a non-syncing account will begin syncing.

### Fix
Line 1060 in `packages/loot-core/src/server/main.ts` should be changed from `if (acct.bankId) {` to `if (acct.account_id) {`.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome, Other

### Operating System

Mac OSX

**Comment by cjfagerstrom** [comment]
Comment from SimpleFIN regarding this issue:

> Right, it's definitely the case the MX is not providing that domain name. I guess I'm suggesting that I wouldn't rely on the domain name always being there. I would rather rely on the account id embedded in each account.

**Comment by duplaja** [comment]
Submitted a pull request to address this: https://github.com/actualbudget/actual/pull/2836

**Comment by youngcw** [comment]
fixed by #2836
