### ISSUE TITLE
[Bug]: ofx amount parsing does not work for foreign number formats

### ISSUE THREAD

**Issue by Guekka** [actualbudget/actual#2800]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

When importing an OFX file, amounts all appear as NaN. This is due to the code using the naive `Number` parser: [source](https://github.com/actualbudget/actual/blob/master/packages/loot-core/src/server/accounts/parse-file.ts#L140).

### Solution

Using a different parser. I saw [number-parsing](https://www.npmjs.com/package/number-parsing) recommended on SO.

**Comment by youngcw** [comment]
Can you provide an example ofx file?

**Comment by Guekka** [comment]
Of course, gimme a minute. But any number such as `-5,74` will cause a `NaN`

**Comment by Guekka** [comment]
Here you go @youngcw 
[parsing-number-locale-issue.zip](https://github.com/actualbudget/actual/files/15444438/parsing-number-locale-issue.zip)
