### ISSUE TITLE
[Feature] Autofill "last used value" in Notes, Category and Amount

### ISSUE THREAD

**Issue by brtwrst** [actualbudget/actual#2801]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I'm still using good old YNAB4 and have follwed the Actual development for a while now.
There is basically only one feature I can't reproduce.
In YNAB4 when you enter a Transaction and put in the payee, it will autofill Notes, Category and Amount with the data of the last transaction that was entered for that payee (not the most recent transaction by date, the one that was entered most recently)

See here (YNAB4):
![YNAB](https://github.com/actualbudget/actual/assets/6873862/bac1c1a7-faa3-486f-a645-4f726e9491a0)

### Describe your ideal solution to this problem

One solution I can come up with is to have an option when creating/editing rules, that states "use last value for this payee" either via some placeholder text or maybe a checkbox somewhere. (feel free to find a better wording for that)
Of course this means that you have to create the same rule for every payee and a checkbox there would clutter the rules UI.

Therefore it would probably be better to have a global option somewhere that says something like "**If no rule can be found for a payee, autofill Category, Notes and Amount fields with most recently used values**" which can be toggled on or off by the user. 

I have already asked on discord and was told that actual does not keep track of the date a transaction was entered, but the most recently entered transaction (for a specific payee) should have the highest ID of all transactions for this payee, and that would make this feasible.

Rule per payee solution.
![image](https://github.com/actualbudget/actual/assets/6873862/acc28291-e61c-46e8-8084-798abde49d1d)
![image](https://github.com/actualbudget/actual/assets/6873862/937cf847-e422-4bc9-81be-41cf066b3d83)

### Teaching and learning

This feature works pretty intuitively as you can see from the demo video. It could even be turned on by default, it does not really "hurt anything". Worst case would be that a user has to press delete or backspace once or twice while tabbing through the fields. Best case they want to enter a repeat transaction on a different day and it saves several seconds each time because they only enter the payee and press return.

**Comment by Rick-Thomas** [comment]
This is a fantastic time-saver feature...   I've used YNAB4 since it was launched and when you go to the Edit Payees it has a setting where you choose for it to autocomplete **Category** or **Memo** or **Amount** or any combination of them...   This is very useful when entering repetitive payments and by just entering the payee it fills all other fields selected, so you accept the transaction or you change totally or partially the particular data...

**Comment by niceguy4** [comment]
I forgot how convenient that feature was in NYAB4!

**Comment by brtwrst** [comment]
Spread the word and lets get it implemented 🤘

**Comment by shall0pass** [comment]
Can't you already do this with a rule?

**Comment by brtwrst** [comment]
Can you do what is shown in my video with Rules?
No
