### ISSUE TITLE
[Bug]: GoCardLess not working anymore ?

### ISSUE THREAD

**Issue by GregTroar** [actualbudget/actual#2802]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Cannot sync my account anymore with GoCardLess.
When I click sync I have an error message and it tells me to fix the wrong credentials, I put again secret ID and secret Key click on France and again I get the error message "Failed loading available banks: GoCardless access credentials might be misconfigured. Please set them up again."

Anything changed ?

Thanks

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Linux

**Comment by MatissJanis** [comment]
👋  https://discord.gg/pRYNYr4W5A

<img width="1289" alt="Screenshot 2024-05-29 at 20 07 31" src="https://github.com/actualbudget/actual/assets/886567/4ead0305-d059-4862-a4b9-c4c6b039ffbd">

**Comment by GregTroar** [comment]
Thanks I have created on Discord.
Thanks
