### ISSUE TITLE
[Feature] Net Worth Pie Chart

### ISSUE THREAD

**Issue by SimonSomlai** [actualbudget/actual#2804]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I want to visualize the net asset balance of all my accounts in 1 pie chart. This allows me to quickly see the % of my net worth that is allocated to each Account and if something should be rebalanced. Something like;

<img width="849" alt="Screenshot 2024-05-28 at 21 08 40" src="https://github.com/actualbudget/actual/assets/12100448/db4df741-4bc2-4455-bde9-615013288077">

### Describe your ideal solution to this problem

I was thinking to just extend this inside the Custom Reports.

- display mode total
- split on Account
- Type equals Net (currently disabled for some reason)

<img width="443" alt="Screenshot 2024-05-28 at 21 27 39" src="https://github.com/actualbudget/actual/assets/12100448/79b90cf0-1701-45b3-a696-06e90f51721b">

If this sounds good for you! Let me know how to best move forward! :D

**Comment by TheBlueCircle** [comment]
Not sure if net is disabled just because it's not been built yet or for some other reason, but implementing it would be a major win for me! 

(For this sort of report though, I'd need to be able to group different accounts to represent different assets, netting off mortgage and house value for example. I'm not sure if that's supported at the moment?)

**Comment by Teprifer** [comment]
There Net option is disabled because you can't show a negative value on a pie chart.

Accounts don't have types beyond off and on budget, so no information available if it were possible to group.

**Comment by TheBlueCircle** [comment]
I get the point you can't show negative on a pie chart, but we're ruling out all the circumstances where you might have one account at €3000 and one at -€1000 and not being able to show that it nets off at 2k. It feels more logical to keep net in for all chart types but limit the lower range to 0. 

(Just my take on it, anyway)

**Comment by SimonSomlai** [comment]
@Teprifer I think setting a 0 lower bound for "Net" in all pie charts would be a good sensible default OR enabling the "Net" option for users without negative net balances. This would already serve more use cases than disabling the feature all-together. I'm not sure how much people actively work with negative net balances in AB though. 

@TheBlueCircle For me, grouping accounts would also be useful! Both to;
- Generalize accounts (multiple bank accounts, grouped under "Cash" for example)
- Working in AB with a partner (for joint and individual accounts for example)

But I would leave this outside the scope of this feature.

---

Anyway, I would be happy to shoot a PR proposal for this and see where it goes. I think it'll be something that I can easily fix. Could someone point me in the right direction here? I haven't found the docs yet on how to set up the dev server locally. 👀
