### ISSUE TITLE
"Back" Button to return to originating row in budget

### ISSUE THREAD

**Issue by mindtec** [actualbudget/actual#2811]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

From the budget page, when looking for a subset of operations, the "back" button appears on top of the operations page.
When clicking that button, the app goes back to the top of the budget page. This is not handy as soon as the originating budget line is outside the screen.

### Describe your ideal solution to this problem

It would be interesting for the workflow to have that back button to return to the originating row, allowing the user to continue where he/she was.

**Comment by psybers** [comment]
This affects users who have a lot of budget categories/items.
