### ISSUE TITLE
[Bug]: Sync Error Fly.io

### ISSUE THREAD

**Issue by TiedRite** [actualbudget/actual#2813]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

The Fly.io deployment is unable to authenticate server.

My budget is deployed through fly.io and it had been working.  I am not prompted to login through the Actual Login.

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by MatissJanis** [comment]
👋 Please reach out to the community on discord

<img width="1289" alt="Screenshot 2024-05-29 at 20 07 31" src="https://github.com/actualbudget/actual/assets/886567/d3213b99-b2cd-46b9-b927-0cc4f1f229de">
