### ISSUE TITLE
[Bug]: rules appear as (soon) in mobile view

### ISSUE THREAD

**Issue by danielo515** [actualbudget/actual#2824]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Rules are not coming, they are available. If I open my foldable, rules are accessible 
![Uploading Screenshot_20240603_162845_Chrome.jpg…]()

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mobile Device

**Comment by danielo515** [comment]
![Screenshot_20240603_162845_Chrome](https://github.com/actualbudget/actual/assets/2270425/b54fcdcb-e22b-4479-bba5-aaa6c4326788)

**Comment by youngcw** [comment]
The rules editor is not available on mobile view yet.  That is why it says soon.  You can hack your way into that page but it doesn't properly scale to standard phone screens.

**Comment by danielo515** [comment]
It works perfectly fine on my phone. Wish there was an option to activate
it, but probably better to wait for the original release. Thanks

**Comment by Kidglove57** [comment]
I’m not sure about other mobile devices such as yours @danielo515  but, as I expected , Rules are definitely not accessible on my iPhone 15 Pro Max unless zoom out to 75% and then only via the sidebar
