### ISSUE TITLE
[Bug]: After @actual-app/api 6.8.0 npm install fails

### ISSUE THREAD

**Issue by jhonderson** [actualbudget/actual#2829]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

After latest release, installing actual api using npm fails:
```
$ npm install --save @actual-app/api
npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "workspace:": workspace:^
npm error A complete log of this run can be found in: ....log
```

It's probably caused by this commit https://github.com/actualbudget/actual/commit/f604fdaf3616d056b899ae824f97bdda476d4cee.

My env:
```
$ npm --version
7.24.2
$ node -v
v20.10.0
```

`yarn install` works, so I am not sure if the documentation should be updated to switch to yarn.

I have a project installing the actual nodejs library using npm, please let me know if npm will no longer be supported so that I can switch to yarn.

Thanks!

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Other

### Operating System

Mac OSX

**Comment by MattFaz** [comment]
Exactly the same happening to me, with yarn I get the following:

```
yarn install v1.22.22
info No lockfile found.
[1/4] 🔍  Resolving packages...
Couldn't find any versions for "@actual-app/crdt" that matches "workspace:^"
? Please choose a version of "@actual-app/crdt" from this list: (Use arrow keys)
❯ 2.1.0 
  2.0.2 
  2.0.1 
  2.0.0 
  1.0.0 
```

**Comment by jhonderson** [comment]
@MattFaz yep same here for yarn. Since I haven’t used yarn with Actual before, I thought it was normal.

**Comment by MatissJanis** [comment]
@twk3 any ideas?

**Comment by twk3** [comment]
whoops, that use of workspace should have only been there like that if it was a dev dependency. I'll get that fixed.
