### ISSUE TITLE
Make rules able to create transactions (handling debts and loans)

### ISSUE THREAD

**Issue by nacifyas** [actualbudget/actual#2833]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I am trying to keep track of my debt which is not the debt mentioned [here](https://actualbudget.org/docs/budgeting/credit-cards/carrying-debt), but instead those situations on which I borrow or I lend money from someone. To keep track of these transactions I have 4 categories and 2 off-budget accounts. These are the categories:

- Expenses category:
  - Debt: I can budget how much debt I am willing to pay for this month
  - Loans: I can budget how much money I can loan for this month
- Income category
  - Debt: I can see how much money I have got from borrowing money
  - Loans: I can see how much loaned money I have got back

In addition to these previous categories I have got these two off-budget accounts. These act as "offset" or "counterpart" accounts. (In spanish it is called _cuenta de contrapartida_ or _partida doble_).
- Debts: To keep track of all my debts. It grows negative balance whenever I borrow money.
- Loans: To keep track of all my loans. It grows positive balance whenever I borrow money.

If I get into a debt, say I borrowed 500€ from a friend to solve whatever issue, the way I see it, I have 500€ extra in my budget. However I need to reflect somewhere the liability I have with that friend, which consists of 500€. Similarly goes if I am the one loaning the money. Those "liabilities" are the mentioned off-budget accounts, that they don't just keep track of all debts and loans I have got involved into, but they also balance my net worth.

My workflow for each category goes as follows:

- Expenses category:
  - Debt: I pay a debt so I have less in budget money. I write a complement transaction as a deposit in my off budget Debts account.
  - Loans: I loan money so I have less in budget money. I write a complement transaction with the same amount as a deposit in my off budget Loans account.
- Income category
  - Debt: I borrowed money so I have more money for my budgeting. I now have liability to return that borrowed amount, so I write a complement transaction with same exact amount as a payment in my Debts account.
  - Loans: I have got loaned money back, so I have more money for my budgeting. I have lost liability with the loanee therefore I write a complement transaction with same exact amount as a payment in my Loans account.

### Describe your ideal solution to this problem

I would like it if Debts and Loans are handled somehow in Actual Budget. Or at least if I could setup a rule, so whenever a transaction is added to any category of Debts or Loan, the "offset" or "equivalent" transaction gets added automatically on the off-budget accounts Debts or Loans accordingly.

### Teaching and learning

This feature might be documented (here)[https://actualbudget.org/docs/budgeting/rules/].
The interface to change would be:
![image](https://github.com/actualbudget/actual/assets/78434431/672f27f6-7253-493c-84b5-59e34d86806c)
Ideally would it would have an option to create a transaction specifying a new account.

**Comment by FrancisRalph** [comment]
Thanks for sharing your workflow, I was looking into how to handle borrowing/lending money to someone.

Rules that create transactions based on existing transactions would be a great feature to have. If I have the time, I will look into contributing for this.

In the meanwhile, since it's been a few months, are you still using the same workflow or have you found a better way of handling borrowing/lending of money?

Thanks!

**Comment by nacifyas** [comment]
Hi. Thanks for reaching out.

I still indeed have the same workflows. When it grow to several transactions it becomes cumbersome and prone to making mistakes, but it is the best I could came up with in the meanwhile.

Another feature (which deserves its own issue) would be to have the ability to schedule or budget income the same way as one can budget expenses. Currently I have created an "In Budget" account  called "Planification" on which I put my future income (monthly salary for example) alongside an income  category. This helps so I don't get negative numbers all across future months giving me a more accurate look regarding my future financial situation. This was inspired from similarities from the borrowing/lending workflow.

Thanks.
