### ISSUE TITLE
[Feature] Ability to set a "fromdate" when import/sync with back account ( gocardless )

### ISSUE THREAD

**Issue by zookz** [actualbudget/actual#2839]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

The complimentary GoCardless account provides access to 90 days of transactions, which suits my needs. However, today, when I synchronize it with my bank via Actual, it retrieves data from 2 years ago. I suspect this might be an error on GoCardless' end, but it's causing disruptions in my budgeting process. In any case, I believe it would be beneficial to establish a fixed "fromdate" when syncing data with GoCardless.

**Comment by matt-fidd** [comment]
I believe this was a bug, GoCardless will no longer sync further than 90 days
