### ISSUE TITLE
[Bug]: GoCardless syncing way more data then used to (730 days back)

### ISSUE THREAD

**Issue by leikoilja** [actualbudget/actual#2841]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I have had a bank sync (Nordigen/GoCardless) enabled since 2023 - generally all good.
After the last upgrade to 24.6.0, UI has showed me that error happened and to resolve it - I would need to re-connect the sync (i believe it's a normal regular procedure for every Actual docker image update i do). 
Normally, i remember Oauth onboarding modal showing that transactions for the past 90 days will be pulled such as this example image:
<img width="409" alt="image" src="https://github.com/actualbudget/actual/assets/10655107/8d6392a5-0124-49b8-a342-aa936878c461">

However, this time around when i connect bank integration i see that data seems to be pulled for the past 730 days 🤔 
<img width="769" alt="image" src="https://github.com/actualbudget/actual/assets/10655107/f30cc830-87f6-49a8-9c4a-e5cd50eee385">

If i agree and go on - integration pulls tons of random data and all my previously linked accounts go bananas with ~160 new uncategorised transactions and probably many more auto-categorised, which i suppose comes from waaay back in time

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by tmoitie** [comment]
👍  Also seems to be no longer respecting account start date, fetching transactions from long before I started using actual.

**Comment by Brawl345** [comment]
I have the same problem with ING even though I set the "Starting Balance" to 1st February (when I started using ActualBudget) which prevented syncing older entries. This seems to no longer work.

**Comment by leikoilja** [comment]
> I have the same problem with ING even though I set the "Starting Balance" to 1st February (when I started using ActualBudget) which prevented syncing older entries. This seems to no longer work.
> 
> EDIT: Workaround: Create a "pre" rule that zeroes out the amount and set a new category like "invalid transactions" or something and apply that to all before a certain date.

hm, thanks for sharing your workaround. 
i use actual for historical records and would love to avoid extra unnecessary records messing up things. Have disabled GoCardless sync for now... back to manual entries until the issue is fixed haha 😅

**Comment by MatissJanis** [comment]
Folks on Discord have also reported this issue. The current group-think there is that this has to be related with the recent incident/maintenance Nordigen performed.

Apparently folks are able to reproduce the same issue on older versions of Actual (can someone verify?). That would cancel out Actual as the culprit.

**Comment by RoFlame999** [comment]
> Apparently folks are able to reproduce the same issue on older versions of Actual (can someone verify?). That would cancel out Actual as the culprit.

I have the same issue on v24.5.0, so it's definitely a change on the side of GoCardless/Nordigen

**Comment by leikoilja** [comment]
> Folks on Discord have also reported this issue. The current group-think there is that this has to be related with the recent incident/maintenance Nordigen performed.
> 
> Apparently folks are able to reproduce the same issue on older versions of Actual (can someone verify?). That would cancel out Actual as the culprit.

can also verify the same issue on v24.5.0, since i did a roll-back after upgrade and tried there as well :)

**Comment by johnnymerayo** [comment]
Same problem here with Lloyds bank (UK)

**Comment by npasslick** [comment]
Same problem here :(

**Comment by Kidglove57** [comment]
I’m syncing via Go Cardless with Starling (UK) and cards with Amex and Halifax. The only problem  I have had  so far is (a) having to unlink and relink GoCardless (b) a random incorrect import at Starling in July ‘23. Phew!

**Comment by AlfHou** [comment]
I just set up my actual server, and I'm experiencing the same issue. My bank accounts are either not able to sync, or when they are they stop working after a few days.

**Comment by npasslick** [comment]
@all Please try syncing again — the issue might be resolved on GoCardless' end

**Comment by Brawl345** [comment]
Thanks for the reply, it seems to work now, no longer getting older transactions!

**Comment by leikoilja** [comment]
have re-tried it again now and can confirm that the issues is resolved, hence closing this :) 
if someone is still experiencing this issues after re-linking - we ll re-open
