### ISSUE TITLE
[Bug]: Future Months Throwing Off Averages in Custom Reports

### ISSUE THREAD

**Issue by lexieheinle** [actualbudget/actual#2846]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

After  v24.6.0 update, my custom reports are now including the current month/year + 1. This leads to the averages for the month or year being incorrect. 

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome, Safari

### Operating System

Mac OSX

**Comment by carkom** [comment]
Hiya, it's a known issue. Fixed by #2684

**Comment by carkom** [comment]
Hiya, it's a known issue. Fixed by #2684
