### ISSUE TITLE
[Bug]: Weekly Schedules getting stuck as Paid

### ISSUE THREAD

**Issue by Teprifer** [actualbudget/actual#2851]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Noticed x3 weekly schedules a few weeks ago got stuck as 'Paid' and stopped auto-adding transactions each week. I'd been posting these manually with investigation on my 'get around to it list' but saw someone else with this issue in discord so finally gotten around to making the bug report. Reach out if further details are required.

Example of one:
![image](https://github.com/actualbudget/actual/assets/34882928/1f50e551-a4c7-430c-b3ff-1217741ab1ed)
![image](https://github.com/actualbudget/actual/assets/34882928/b73a0291-5859-4607-b202-1f4817748fc9)

Changing settings of this didn't get it un-stuck.

Following a similar report in discord ( https://discord.com/channels/937901803608096828/969693280226906162/1248406393493389322 )

> Carson: has anyone had a schedule get "off" by a period? i have a weekly-on-monday schedule, the last of which was on June 3rd. with the transaction on June 3rd, the June 10th iteration shows as "paid" already (even though it shows as an upcoming instance in the schedules menu), and doesn't appear as upcoming. if i manually change the June 3rd transaction to June 2nd, the one on the 10th all of a sudden kicks in and shows as upcoming. changing the existing transaction back to the 3rd makes it go away again. it seems like it's taking that transaction as the one that's supposed to happen next week 😮

I amended the date of the most recent transaction to be 1 day different, and now the schedule shows as Upcoming again.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Windows 11

**Comment by CarsonHoffman** [comment]
From a bisect, this seems to have been introduced in b0f55fae383f8e2ee3847229644791d70c62d88e. Looking at the 7 in the diff, it seems fairly obvious what's going on, though I'm not entirely sure what the best course of action is going forward, as I'm not familiar with what this was attempting to fix. @joel-jeremy do you have any thoughts?

**Comment by Teprifer** [comment]
Confirmed exporting a file from 24.6 and rolling back to 24.5 is a workaround that can be used until this is fixed.

**Comment by MatissJanis** [comment]
cc @joel-jeremy any objections to reverting #2712 ? I think getting weekly schedules up-and-running again would take prio over the edge-case patch in 2712.
