### ISSUE TITLE
[Bug]: link schedules modal - table width

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#2855]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

The schedules table in the "link schedules" modal seems to be too large. Or the modal is too small. One of the sizes has to change.

<img width="823" alt="Screenshot 2024-06-07 at 19 54 51" src="https://github.com/actualbudget/actual/assets/886567/330d392c-72d1-4427-b112-ea2a93b82759">

Reproduction:
1. select a transaction
2. open the menu
3. "link schedule"

### Where are you hosting Actual?

None

### Operating System

None

**Comment by 27Lia** [comment]
Can i work on this ?

**Comment by MatissJanis** [comment]
Feel free to send a PR for this. We do not assign issues to specific people.
