### ISSUE TITLE
[Feature] Ability to add tags to budget categories and groups

### ISSUE THREAD

**Issue by armanckeser** [actualbudget/actual#2858]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Hi folks!
A discussion has been done on adding tags to notes and such a feature is being implemented in https://github.com/actualbudget/actual/pull/2670. I was hoping we could discuss the same feature but for the budget categories themselves. Say you are like me, trying to do 50/30/20, necessities/wants/savings, but you also would like to categorize spendings by `Transport`, `Food`, etc, and on top of that `Fixed` vs `Variable`... Right now, you have to choose one since all categories have to be under one group. If we could tag these groups and categories, we might get to create much more expressive templates, reports, and limits without having to tag each transaction. 
Let me know what you think and thanks!

### Describe your ideal solution to this problem

The exact implementation of https://github.com/actualbudget/actual/pull/2670, applied to groups and categories.

### Teaching and learning

We could have some default budget items like `Income` start out tagged as income.

**Comment by OuticNZ** [comment]
@armanckeser - not sure if you found a solution to this.  I'm also wanting this as well.   I missed this feature post in my search - https://github.com/actualbudget/actual/issues/8655
