### ISSUE TITLE
[Feature] Linked Loan Accounts

### ISSUE THREAD

**Issue by Agwebberley** [actualbudget/actual#2860]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Loan accounts should be able to be linked in the same way that bank accounts and credit cards are.  I am using the SimpleFin Experimental feature so I am not sure if GoCardless already implements this or not.

**Comment by youngcw** [comment]
This will depend entirely on the sync provider.  Some loan accounts are available in simplefin. Also there are already requests open for adding in special account types.  Because of those, Ill close this one.
