### ISSUE TITLE
[Bug]: Group budget roll-up not right

### ISSUE THREAD

**Issue by dimangi** [actualbudget/actual#2865]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

The picture best explains my problem. The group roll-up budgets (Savings, Just for fun) don't match what's budgeted on the categories.

This only starts May 2024 onwards. I have been able to migrate from YNAB, and all the previous months budgets are fine. I typically budget to zero roll-over except in special cases.

![Screenshot 2024-06-11 015128](https://github.com/actualbudget/actual/assets/3279300/ae693b93-8f9c-4121-bcc2-7f3464eafc4a)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### Operating System

Linux

**Comment by youngcw** [comment]
Are there any hidden categories?

**Comment by dimangi** [comment]
> Are there any hidden categories?

Oh my god, now I feel really stupid. Thanks for the support, let's close this ticket 👍
