### ISSUE TITLE
[Feature] Category Group selectable in Category Autocomplete to filter

### ISSUE THREAD

**Issue by lelemm** [actualbudget/actual#2873]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

When categorizing transactions manually you know the name of the category group, but you don't remember the category exactly. 

### Describe your ideal solution to this problem

The proposal is that you can type the category group inside the autocomplete then press enter show only the group categories inside that group

**Comment by lelemm** [comment]
This is the working example:

https://github.com/actualbudget/actual/assets/15043428/5528d70a-050b-4856-9bdd-841350d8ca3a

**Comment by youngcw** [comment]
Is this different than #2324? They seem the same to me.

**Comment by lelemm** [comment]
Yeah, I closed it after realizing its the same @youngcw
