### ISSUE TITLE
[Bug]: Rollover overspending indicators pushed off screen in mobile view

### ISSUE THREAD

**Issue by matt-fidd** [actualbudget/actual#2879]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

As above, image below.

![image](https://github.com/actualbudget/actual/assets/81489167/30e59f28-f63e-415f-b607-d0f0512a76af)

**Comment by dymanoid** [comment]
Will be happy to work on this. Please also see my comment in #2774.

**Comment by youngcw** [comment]
This is still broken even after #2774.  I think that the a better solution would be to somehow integrate the arrow into the pill around the value.  Maybe the pill should run up against the side of the screen and then the arrow can be inside the pill along with the amount

**Comment by dymanoid** [comment]
Here are three possible solutions. Which one do you prefer?
I don't like the 3rd one where the dark value containers extend to the right to cover the carryover arrow.
I personally prefer the 1st one where the arrows are outside of the value containers, so basically the current design. But the 2nd one is also okay.
So what are your thoughts?
**Variant 1:**
![a1](https://github.com/actualbudget/actual/assets/9433345/58848dd6-090a-4f73-a286-9ea356da247e)

**Variant 2:**
![a2](https://github.com/actualbudget/actual/assets/9433345/5cad212e-5b14-4a66-a6c1-d5f1f8eb0a79)

**Variant 3:**
![a3](https://github.com/actualbudget/actual/assets/9433345/78503c8a-42b0-43a1-a5cf-e96764a5cd5c)

**Comment by youngcw** [comment]
@dymanoid 
option 1 would match desktop the most and is the most similar to existing

**Comment by dymanoid** [comment]
Something like this?

![image](https://github.com/actualbudget/actual/assets/9433345/288c35c4-ea42-4a3b-ac1a-08ff2ba2656a)

**Comment by youngcw** [comment]
@dymanoid Yeah that was what I was thinking.  It still seems a bit weird, but its an option

**Comment by dymanoid** [comment]
After discussing on Discord, this what we decided to implement:
![image](https://github.com/actualbudget/actual/assets/9433345/781358b5-3900-4f41-a09f-59d3d1c1329b)
