### ISSUE TITLE
[Bug]: Bank supported by GoCardLess but not showing in Actual

### ISSUE THREAD

**Issue by sjabby** [actualbudget/actual#2883]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Bank "Jernbanepersonalets Sparebank" in Norway is showing as a supported bank on GoCardless website, but it does not show in the list within Actual:
![image](https://github.com/actualbudget/actual/assets/27990031/107e4d77-2311-4490-8cd6-c8c84508acc7)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Operating System

Windows 11

**Comment by MatissJanis** [comment]
👋 
<img width="1278" alt="Screenshot 2024-06-16 at 18 24 18" src="https://github.com/actualbudget/actual/assets/886567/12b34012-8289-4746-8301-40d68801a742">
