### ISSUE TITLE
[Bug]: focus ring gets "stuck" on last column of /accounts/budgeted screen.

### ISSUE THREAD

**Issue by miclgael** [actualbudget/actual#2885]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Thanks for making Actual!

In the `/accounts/budgeted` screen, when tabbing through each column I get stuck at the end of the row on the [transaction cleared] column.

As a keyboard user, my expectation would be to have additional tab key presses skip down my focus to the cancel button, followed by the submit button - and loop back around to the [date] field again. 

I have recorded a demo tabbing through the budget screen. 

https://github.com/actualbudget/actual/assets/4301358/f3e04004-7c17-410e-86dc-a8582f3cf594

I understand I can press enter/return and this will "submit" the data, however, the visual feedback and satisfying loop of watching the focus ring move to where I expect would be nice to see.

Please let me know if this is a **bug** or if perhaps a **feature request** would make more sense.

Client version: v24.6.0
Server version: v24.6.0

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Mac OSX

**Comment by MatissJanis** [comment]
Thanks for the report!

> Please let me know if this is a bug or if perhaps a feature request would make more sense.

I think this is a bug. We can leave the ticket as-is :)
