### ISSUE TITLE
[Bug]: large tooltips - pushing page down

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#2888]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

<img width="1440" alt="Screenshot 2024-06-16 at 20 45 55" src="https://github.com/actualbudget/actual/assets/886567/3934235c-dfa9-4f2f-aeb2-b9ed9997bfaf">

Tooltips that are very large (in height) cause the page height to increase. Thus resulting in a lot of dead white-space at the bottom of the page.

This is visible when the browser window is resized to be small.

Potential solutions:
1. adding a scrollbar inside the tooltip (kinda like is currently already done in the notes tooltip)
2. enforcing the content to always expand to 100% height (thus there would be no dead whitespace at the bottom)
3. ???

### Where are you hosting Actual?

None

### Operating System

None

**Comment by edmonday** [comment]
@MatissJanis tried to reproduce this and it seems this is resolved now.

**Comment by MatissJanis** [comment]
Thanks for the ping. I am indeed no longer able to reproduce this issue. So it must have been patched somehow.
