### ISSUE TITLE
[Bug]: transactions table - select all not selecting schedules

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#2889]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Reproduction:
1. open transactions table (that has schedules too)
2. click the "select all" box
3. notice only the transactions get selected - schedules are not selected

https://github.com/actualbudget/actual/assets/886567/8141fc53-8f85-4a46-9b8b-e1385ff46dbf

### Where are you hosting Actual?

None

### Operating System

None

**Comment by MatissJanis** [comment]
Looks like it doesn't select split-transaction parent transactions either.

<img width="1435" alt="Screenshot 2024-06-16 at 21 05 07" src="https://github.com/actualbudget/actual/assets/886567/ed5c319a-a9b0-43cf-a1df-32fa601ea05a">

**Comment by youngcw** [comment]
This feels like the correct behavior to me.  Schedules are different than regular transactions and if the split parent is included in the selection the amount calculations get messed up.

**Comment by MatissJanis** [comment]
Interesting perspective. From a usability POV I would expect a "select all" checkbox in the header to do what most other products do - to select all the entries within the table. Is there a good argument for why we should treat schedules differently?

> if the split parent is included in the selection the amount calculations get messed up

IMO this is an unrelated problem. Even if you manually select the parent + children transactions - the calculations get messed up. It definitely should be addressed. But it's not really related to select-all functionality.

**Comment by dangrous** [comment]
To be honest, I would lean towards @youngcw's perspective that - for me - this is the ideal behavior (I never want to include non-current stuff) but, I think overall I'd agree that select all should do what it says on the tin and select all. It'd definitely be worth thinking about some sort of "select real entries" though too in the future!

**Comment by youngcw** [comment]
I don't have any issue with parents of splits being included in the select all, as long as the selected total is calculated right.

For the schedules, I don't think those should be considered transactions since they have yet to be added.  They are in the table for reference purposes.  Also, the bulk options are different for schedules than for regular transactions.

**Comment by joel-jeremy** [comment]
I would then to agree that the parent should not be selected specially with the recent change where the parent transaction is just going to be a shell of its children transactions (no payee, no category)

**Comment by dangrous** [comment]
So it sounds like the current behavior is the expected one then?

I feel like it looks a little weird to have the parents not selected, but it makes more sense that way. Maybe there's a visual cue if all child transactions are selected vs. not - that would be a separate issue though.

**Comment by MatissJanis** [comment]
Yes, looks like the majority prefers to keep the status quo here. Lets do that :)


Closing the ticket as complete
