### ISSUE TITLE
[Bug]: CSV Manual import  ignores "Reconcile Transaction" option

### ISSUE THREAD

**Issue by benquan** [actualbudget/actual#2897]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

When manually importing a CSV file, I try to unselect the "Reconcile Transaction" option. The check mark goes away but when I execute de command, the uploaded transactions get reconciled anyway.

<img width="794" alt="Screenshot 2024-06-18 at 12 07 11 PM" src="https://github.com/actualbudget/actual/assets/3030645/33e42d52-ee80-4782-ade3-9957d1488309">
<img width="1193" alt="Screenshot 2024-06-18 at 12 09 05 PM" src="https://github.com/actualbudget/actual/assets/3030645/48a6934d-05fc-48ec-baef-10beb90c5917">

Expected behavior would be that new transactions are imported without the reconciled checkmark.

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by youngcw** [comment]
The reconcile button means to reconcile against existing transactions, ie deduplicate the transactions.  It is an overloaded name to be fair.
