### ISSUE TITLE
[Feature] Expose an API "getBudgets"

### ISSUE THREAD

**Issue by jeffjose** [actualbudget/actual#2901]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

To get all available budgets on a server, there isnt a top level API. One has to resort to `api.internal.send('get-budgets')`. It'll be nice to expose it at top level, say `api.getBudgets()`

### Describe your ideal solution to this problem

Expose it at top level, say `api.getBudgets()`

### Teaching and learning

The method name is descriptive enough to be discovered organically. We should also include a blurb in the docs with sample usage.

**Comment by psybers** [comment]
So just to clarify: you want a function that would *download* all of the remote budget files locally?

**Comment by psybers** [comment]
Or literally the function `get-budgets`, which I believe just enumerates your local cache?
