### ISSUE TITLE
Weird overbudgeted balance in my furthest future month that I can't get rid of

### ISSUE THREAD

**Issue by Kaboom6253848** [actualbudget/actual#291]
When I skip months until I hit the last month in my budget, I have a weird negative 'overbudgeted' balance that I don't seem to be able to get rid of. My budgets are set to 0, so I assume it's something that started in an earlier month. Problem is though..... Everything adds up (balances and budgets match in my current month). I can press 'hold for next month', but that moves the problem up one month. 

Is this a bug or am I doing something wrong?

**Comment by nickybulthuis** [comment]
@Kaboom6253848 I have the same problem. 

You likely pressed the 'Hold for all future months', it will hold your entered balance for all future months separately. There doesn't seem to be an option to reset it for all future months, just for the next month. Which just moves the problem up one month. 

Using "Hold for all future months" with 0 (zero) or 'empty' doesn't seem to help.

**Comment by Kidglove57** [comment]
The only way I solved this was to go to the furthest month that Actual will allow. And then reset each month moving backwards to this month!

**Comment by nickybulthuis** [comment]
> The only way I solved this was to go to the furthest month that Actual will allow. And then reset each month moving backwards to this month!

@Kidglove57 Thanks, at first I figured it would just add more months, but it seems to stop after a year or so. I've given each month a reset.

**Comment by Kidglove57** [comment]
Glad it worked - it’s come up a number of times over the past few years and isn’t intuitive at all!

**Comment by MatissJanis** [comment]
👋 Looks like this has been solved. Feel free to re-open if the issue still exists.
