### ISSUE TITLE
[Feature] Add a possibility for rules to append to the current notes

### ISSUE THREAD

**Issue by Thiago-Morais** [actualbudget/actual#2912]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I have 2 rules that add tags to the transaction notes.
If the transaction meets both conditions I want to apply both rules.

Example:
The _imported payee_ is "A new Bank 1 transfer to Person 1".
I have a rule "if 'Bank 1' then add '#bank1'" 
And another "if 'Person 1' then add '#person1'"

Currently, there is only a _set_ option so it overrides the first rule.

I can't keep the payee unchanged because I would have a billion payees.
I can't use a single rule to add "#bank1 #person1" because I would need a billion rules for every possibility.

### Describe your ideal solution to this problem

Instead of only _set_, we can have _concat_, _insert into_, and other string manipulation functions

A regex match and replace would also work

**Comment by meonkeys** [comment]
see #3197

**Comment by youngcw** [comment]
Added by #3197
