### ISSUE TITLE
[Feature] View the transactions of all accounts with the mobile website.

### ISSUE THREAD

**Issue by towerhand** [actualbudget/actual#2920]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

On the desktop site, there is an option to see a list of the transactions from all budget and off-budget accounts. However, that's not an option on the mobile website, and we can only see the transactions separated per account.

It would be nice to see all accounts' transactions in a single list since that's probably the quickest way to spot unauthorized transactions while on the go.

### Describe your ideal solution to this problem

The easiest would be to add a link to the “For Budget” and “Off Budget” in the “Accounts” tab.

### Teaching and learning

This feature is quite simple and aligns with the features available on the desktop version.

**Comment by Crazypkr1099** [comment]
I don't believe this feature needs to be added. All you need to do is turn your phone sideways and you have access to all your transactions. Man power could be used elsewhere for now. Maybe in the distant future this could be a thing?

**Comment by Teprifer** [comment]
> I don't believe this feature needs to be added. All you need to do is turn your phone sideways and you have access to all your transactions. Man power could be used elsewhere for now. Maybe in the distant future this could be a thing?

I disagree, more feature parity for mobile should be welcomed. I've seen this specific request a few times in discord now and desktop view on mobile isn't great.

What you're describing as a reason not to do it is a false dichotomy, work done is by volunteers who chose what they want to work on, not allocated.

**Comment by towerhand** [comment]
![image](https://github.com/actualbudget/actual/assets/42445253/400b4463-0d0f-4b08-b8ad-da8a75070d97)
![image](https://github.com/actualbudget/actual/assets/42445253/3cbc3d5f-f34b-4c72-906b-e676e9231cf3)
This is how the desktop view looks for all transactions on mobile. It is not really helpful.

**Comment by TheBlueCircle** [comment]
Duplicate of 2333?

https://github.com/actualbudget/actual/issues/2333

**Comment by towerhand** [comment]
I'm sorry. I didn't see that one when I searched for requests before creating this one.

**Comment by youngcw** [comment]
Closing in favor of #2333
