### ISSUE TITLE
[Feature] The "Link Schedule" window is too narrow

### ISSUE THREAD

**Issue by Thiago-Morais** [actualbudget/actual#2921]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

The "Link Schedule" window is too narrow and cuts off the schedule name too early

If 2 schedules have the same first word, you can't differentiate the two

![image](https://github.com/actualbudget/actual/assets/21369746/ce2df5e7-e74f-4a31-916c-df1dad4c8deb)

### Describe your ideal solution to this problem

The ideal solution is a resizable window + resizable columns + horizontal scroll

But a wider window already helps as well as increasing the Name column's width

Resizable columns + horizontal scroll is a must though

### Teaching and learning

For resizable columns, a simple white vertical line between the columns could be enough of a visual tip

For a resizable window, some pattern in the bottom right corner should do

Like in [this](https://ux.stackexchange.com/a/14444) comment

**Comment by youngcw** [comment]
I believe this is updated already.  Can you try out edge.actualbudget.org?

**Comment by Thiago-Morais** [comment]
Yo, I had no idea about this site. Awesome!

The new window is much better as I can see around 10 more characters in the name column

The window and columns are still static though, but at this point, I think the resizable column should be its own feature request as the window is no longer "too narrow"

**Comment by youngcw** [comment]
> The window and columns are still static though, but at this point, I think the resizable column should be its own feature request as the window is no longer "too narrow"

Ok.  Could you open a new feature request for just that?  Ill close this one off.

**Comment by Thiago-Morais** [comment]
#2931 Opened for resizable columns
