### ISSUE TITLE
[Feature] Resizable columns

### ISSUE THREAD

**Issue by Thiago-Morais** [actualbudget/actual#2931]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Every "spreadsheet" view that lists their data in rows and columns has columns with a fixed column size.

![image](https://github.com/actualbudget/actual/assets/21369746/d6040606-0487-474f-b151-3943959d6435)
> _1920 x 1080 screen_

This works for most cases but it can be a problem with long texts or narrower screens.

![image](https://github.com/actualbudget/actual/assets/21369746/19b5785c-4865-4a31-82b4-450e85deea26)
> _1440 x 1080 screen_

![image](https://github.com/actualbudget/actual/assets/21369746/909412d3-ebb6-49bd-81ac-d9241dcd2e5c)
> _1360 x 768 screen_

![image](https://github.com/actualbudget/actual/assets/21369746/95f2eb37-d815-4c03-b322-9a19a7086c88)
> _1280 x 720 screen_

It also happens on "inner windows" like in "Link Schedule"
![image](https://github.com/actualbudget/actual/assets/21369746/19c869ec-f08c-4800-bf76-12db63fafb86)
> _"Link Schedule" window cropping the long text_

### Describe your ideal solution to this problem

My solution would be resizable columns and a horizontal scroll, like Excel or Google Spreadsheets

![Resizable Columns](https://github.com/actualbudget/actual/assets/21369746/3700cd8c-7bac-44e7-9a26-8671f2bdbf68)
> _Manualing resizing columns_

![Scrollable Columns](https://github.com/actualbudget/actual/assets/21369746/921d7bb4-694d-4c64-b47f-c3243014ac82)
> _Scrolling columns_

The thing is, there is already an auto-resize for the columns
![Resizing Window](https://github.com/actualbudget/actual/assets/21369746/ba2b6b73-6a99-4716-9875-bec07399c2d4)
> _Resizing window_

Changing the column's width could mess that up or not

If manually changing the width could mess that up, a solution could be an option "disable auto width" or "enable manual width" or "[x] Fit columns to screen" so that the users themselves op out of auto-resize

### Teaching and learning

I believe simple vertical lines should do

![image](https://github.com/actualbudget/actual/assets/21369746/c6f77e01-0516-4d5a-a598-783d20b13a93)
> _White vertical bars between each column_

And a scroll bar appearing when the width is bigger than the screen should be self-explanatory

Now for the "disable auto-resize", (if this is the solution we are going with) I don't think this should be on the screen. 
Maybe a global option in Settings.

In this case, we should have this in the documentation
Maybe on "Tips & Tricks"

**Comment by Thiago-Morais** [comment]
I see this seems to be a duplicate of #536 even though this is more general talking about every "spreadsheet" view

If both talk about the same topic we can remove this one

**Comment by MatissJanis** [comment]
👋 Very good write-up, but yea - it's essentially a duplicate of https://github.com/actualbudget/actual/issues/536. Lets vote on that issue.

Also related: https://github.com/actualbudget/actual/issues/655
