### ISSUE TITLE
[Bug]: Schedule reset amount to ten (10) when amount is zero (0)

### ISSUE THREAD

**Issue by Thiago-Morais** [actualbudget/actual#2932]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

When a schedule has the amount of zero it resets to 10

https://github.com/actualbudget/actual/assets/21369746/36e6cef0-f0aa-4b75-9ba8-3ab22c291730
> _Schedule changing the amount to 10 when it is 0_

This only happens when it is 0. Any non-zero amount keeps its value

### Where are you hosting Actual?

None

### What browsers are you seeing the problem on?

Chrome, Desktop App (Electron)

### Operating System

Windows 11

**Comment by Teprifer** [comment]
This is intentional, added in #2360 as a measure to prevent another bug.

**Comment by joel-jeremy** [comment]
I think we should revisit that. It should honor whatever is already saved in database otherwise it's going to be a bad UX as shown in the recording. It should only default to 10 when creating a new schedule.
