### ISSUE TITLE
[Feature] Add colors to budget values

### ISSUE THREAD

**Issue by Thiago-Morais** [actualbudget/actual#2934]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Currently, in the budget tab, if the balance is less than zero it turns _red_
![image](https://github.com/actualbudget/actual/assets/21369746/53bbf662-b758-4f88-9f16-5382c9915358)
> _Negative balance values are red. Positive values are white. Zero is gray._

This is good as it makes it easy to see, at a glance, where we are overspending.

However, every other non-zero amount has the same color.
![image](https://github.com/actualbudget/actual/assets/21369746/3a87018a-1119-466e-a513-330328ec0499)
> _Same color shared between positive `Balance` value, `Spent` non-zero values, and `Budgeted` non-zero value._

Also, the group's title doesn't change colors even on Balance

This makes it harder to quickly gather information at a glance when you have many categories going all over the place.

### Describe your ideal solution to this problem

My solution would be to:

First, apply the same color change to the `Budgeted` and `Spent` columns as well as the Group's title.

Second, Use different colors for Positive values.

[The Goal Indicator part of the Budget Goal Templates](https://actualbudget.org/docs/experimental/goal-templates#goal-indicators) is a great example of color usage.
![](https://actualbudget.org/assets/ideal-img/templates-colors.407fb4e.701.png)
> _Green for "goal met", yellow for "goal not met", and red for "negative balance"._

### Teaching and learning

An addition in the documentation with a legend for each color

**Comment by edmonday** [comment]
I would also find this helpful. Keen to help implement this.

**Comment by edmonday** [comment]
@Thiago-Morais you can check out my implementation here: https://github.com/actualbudget/actual/pull/3047
