### ISSUE TITLE
Enter and Tab keys have different reactions when entering Payee info

### ISSUE THREAD

**Issue by Rick-Thomas** [actualbudget/actual#294]
Using "Add New" transaction form is used, when part of the Payee es selected, the TAB key moves to next field with that Payee selected...  But in the "Schedules" or "Filter" forms, in the same situation the TAB just moves to the next field but does not select the Payee...   The ENTER key must be used for the Payee to remain selected...   It would be comfortable that all forms react the same to the different keys pressed...   I think that in this case with ENTER or TAB, the highlighted Payee should be selected...

**Comment by MatissJanis** [comment]
👋 This _might_ be solved with the new autocomplete component. Please check out the new autocomplete in the preview environment and if this issue still persists - comment on this issue - https://github.com/actualbudget/actual/issues/773

Preview environment: https://actualbudget.netlify.app/
