### ISSUE TITLE
[Feature] Account should have a currency.

### ISSUE THREAD

**Issue by avmesquita** [actualbudget/actual#2947]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

If a have two accounts, one in dollar and other in euro, overall budget will be wrong.

### Describe your ideal solution to this problem

Create currency entity.

**Comment by Mart-Bogdan** [comment]
Duplicate/related to #1132
