### ISSUE TITLE
[Feature] manual CSV import, ignore top lines (and bottom lines)

### ISSUE THREAD

**Issue by benquan** [actualbudget/actual#2950]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I obtain the bank statements by CSV, which I upload manually. But the bank's CSV structure has a multilne header which gives account totals and other details, and the actual CSV data starts on line n+1. Could you add the option to simply ignore the first n lines of the csv?

### Describe your ideal solution to this problem

At the moment, Actual Budget uses a "has a header" boolean. This should be incorporated into a broader solution, using a new input field of "rows to ignore" in the "Import Transaction CSV" form. If your header is 1 line long, you ignore 1 line. If there is no header, it would be 0 lines, and if its multiline, ignore n lines.

Optionally you could also ignore n lines from the bottom of the document in case they add a fixed footer.

I used to work with "Money Manager Ex" and this was their implementation of CSV import:

<img width="927" alt="Screenshot 2024-06-29 at 8 27 05 AM" src="https://github.com/actualbudget/actual/assets/3030645/f0b6d416-f685-4d8d-81f4-6be925869f76">

### Teaching and learning

The feature would be displayed on the CSV import form. Optionally as shown in the example, you can shade the ignored lines to visually show how it all works.

**Comment by youngcw** [comment]
Can you try out PR #2717 and see if that would work for you?

**Comment by benquan** [comment]
Thanks @youngcw I read the PR but it it tackling a different issue. I will add a sample CSV where the header is 8 lines deep, then data starts....

[CreditCardsMovementsDetail-9.csv](https://github.com/user-attachments/files/16042419/CreditCardsMovementsDetail-9.csv)

**Comment by mcalligator** [comment]
This has also subsequently been requested as part of [[Feature] CSV import templates #3886](https://github.com/actualbudget/actual/issues/3886) - adding this note to link these two feature requests.
