### ISSUE TITLE
[Feature] Add option to assign a Schedule to a Category for budgeting

### ISSUE THREAD

**Issue by crankeith** [actualbudget/actual#2958]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

The feature would allow users to assign a Category to a Schedule and the schedule would automatically contribute to the "Budgeted" amount for that Category in the Budget view. This would reduce the work of adding all of the schedules as a "Goal Template".

**Comment by Teprifer** [comment]
Hi,

This can already be done.

1) After saving the schedule, click to edit it again.

2) Click on 'Edit as rule'. 

![image](https://github.com/actualbudget/actual/assets/34882928/e2ff3352-3cb5-42bb-a6c7-5191d3b532f0)

3) Then you can add Set category.

![image](https://github.com/actualbudget/actual/assets/34882928/7b7abf60-c53e-486d-a689-9d0b990818b1)

**Comment by Kidglove57** [comment]
PS: Although the second part of this idea - to add it to the automatically to the budgeted amount would not of course be achieved.

**Comment by youngcw** [comment]
This looks to be a duplicate of #2376.  Ill close this off in favor of that one.
