### ISSUE TITLE
[Feature] Split transactions default to collapsed

### ISSUE THREAD

**Issue by sjmclean** [actualbudget/actual#2959]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I have a number of split transactions in my accounts. I would like the default behavior to be that all entered split transactions are defaulted to collapsed once entered.  Once entered I don't need to know the split breakup every time the account transaction screen is displayed.  I find the default behavior of expanding the split transaction(s) makes the transaction screen ugly and obviously expands the page and shows less transactions without having to scroll. 

### Describe your ideal solution to this problem

I would like to see at least the option of once the split transaction has been entered that the transaction is collapsed rather than expanded by default. I think it should stay collapsed as if I need to check the details of the split I can expand it when required. But otherwise it should stay collapsed. 

### Teaching and learning

There is already a split transaction > v icon next to "split". This perhaps could be made larger and more obvious. However I think its already fairly obvious.

**Comment by jfdoming** [comment]
I think a toggle already exists for this in the top right! 
<img width="380" alt="image" src="https://github.com/actualbudget/actual/assets/9922514/8cf1ec12-e928-48a1-9309-8dfc2d2d0abb">
If you click that button, all splits will be collapsed by default.

**Comment by sjmclean** [comment]
Thanks! Your right! That works for me :)
