### ISSUE TITLE
More info for overspent categories 

### ISSUE THREAD

**Issue by PartyingChair** [actualbudget/actual#2963]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I find it difficult to see if or where I’ve overspent in a category 

### Describe your ideal solution to this problem

As someone coming from YNAB due to price increase I do really love how YNAB has a huge banner at the top saying “OVERSPENT CATEGORY” when I’ve overspent in a category. I don’t need this to copy YNAB exactly, but a clear indication of an overspending would be nice. 

Also, I can open a second feature request for this if necessary, but I think notifications, either from the web app or SMTP email or pushover would all be a nice quality of life improvement. Overspending or new transaction from a schedule would be ideal in my opinion. 

Thank you

### Teaching and learning

I think this is mostly a UI change and doesn’t need much documentation. Just a banner or some UI element to let me know 1) I have overspending and 2) where that overspending is

**Comment by joel-jeremy** [comment]
Partially implemented in https://github.com/actualbudget/actual/pull/4643

**Comment by joel-jeremy** [comment]
Closing https://github.com/actualbudget/actual/issues/3667 as duplicate which has 7 votes

**Comment by joel-jeremy** [comment]
This would be easier to implement now in desktop with the introduction of `useOverspentCategories` hook. The hard part is to figure out where to put the banner to provide the best UX. We need to take in consideration multi-month budget view.

**Comment by youngcw** [comment]
I like the idea of having a "group" on the budget table that is for uncategorized transactions. So same size as a category group line, but probably a different color.  Or just a banner like thing as the first entry in the table that is for uncategorized things

**Comment by Juulz** [comment]
![Image](https://github.com/user-attachments/assets/f57f10ba-9ceb-4a00-9b5c-e4b939b68ada)

Perhaps... banner or flag (better IMO) the month name and put a line in the dropdown (perhaps in red) with the amount and a link to a filtered view.
