### ISSUE TITLE
Cleared/uncleared split lines

### ISSUE THREAD

**Issue by MikeBishop** [actualbudget/actual#297]
Possibly the root cause of actualbudget/releases#242, but it appears that individual lines of a Split are capable of having distinct cleared/uncleared status, even though this isn't exposed in the UI.

To repro in 147:

- Ensure the account is properly reconciled.  Note the cleared total.
- Create and save a split transaction; do not mark it as cleared.
- Edit the split transaction in the following way:
    - Increase the amount of the parent transaction
    - Add split line(s) to the transaction to allocate the additional amount

**Expected:**  The cleared balance does not change, because the edited transaction was uncleared.
**~~Actual~~ Observed:**  The cleared balance increases by the amount of the new split lines.

To confirm, filter the account to show uncleared transactions only.  Note that the newly added split lines are grayed out, indicating they don't meet the filter criteria even though the parent transaction and other split lines do.

![image](https://user-images.githubusercontent.com/4273797/159731248-6aa2779f-0f13-44b8-bfea-f4bc94cba6cb.png)

**Comment by qedi-r** [comment]
I do not believe this is still an issue. I've been able to create a split transaction as uncleared, filter to uncleared, and add split lines. The new split lines correctly show as uncleared. No noted issues with reconciling the split either.

**Comment by matt-fidd** [comment]
Closing as unable to repro now
