### ISSUE TITLE
[Bug]: Electron - Remove broken autoupdate functionality from the Electron app

### ISSUE THREAD

**Issue by MikesGlitch** [actualbudget/actual#2972]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

In the Electron app if you click "Help", then select "About" from the menu it provides this screen:

![image](https://github.com/actualbudget/actual/assets/5285928/d1bfae91-ce6d-4475-ba43-0d0475db1475)

If you select "Check for updates" it always errors. I have never seen it work.

![image](https://github.com/actualbudget/actual/assets/5285928/ef8ff486-8a47-4bfc-8d6f-8311e69cacd1)

It should never be able to work either. 
- The AppImage is a portable file so cannot be updated - I don't think it makes sense to update that
- The Flatpak can be manged in FlatHub so it should be updated there
- The Windows app update doesn't currently work, but when we move it to the Windows Store it will update there
- The Mac app update - I haven't been able to check it - but I'm assuming all app updates should go to the Mac store

## The plan
I believe the plan is to publish Actual to the Windows App store, Flathub, and Mac's store. 

Publishing on the app stores allows the app to be updated without custom code on our end.

## Solution

- We should remove the Electron updater package and all Electron Update functionality as it doesn't work.
- In future we should publish the app to all major app stores.

### Where are you hosting Actual?

Desktop App (Electron)

### What browsers are you seeing the problem on?

Desktop App (Electron)

### Operating System

Windows 10

**Comment by MatissJanis** [comment]
That makes sense!

**Comment by MikesGlitch** [comment]
Yeah I had a deeper look into why it wasnt working on windows and it's because this doesn't exist:

https://[github.com/actualbudget/actual/releases/download/v24.7.0/latest.yml](https://github.com/actualbudget/actual/releases/download/v24.7.0/latest.yml)

I've gone back in history to our first release on here while this was open sourced and that file has never existed, so this has never worked. 

If we're all ok with managing this through the app stores I might start working. I'll start after some of the typescript updates for Electron made their way into master.

**Comment by MikesGlitch** [comment]
Closed by #2983
