### ISSUE TITLE
[Feature] Repeat on specific days of the week

### ISSUE THREAD

**Issue by Medic97** [actualbudget/actual#2977]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I have a transaction that repeats 3 times a week. In order to have a repeat on specific days of the week, currently I would need to add 3 separate schedules. 

### Describe your ideal solution to this problem

I would like the ability to select specific days instead of just an interval of amount of days.

**Comment by youngcw** [comment]
Looks like you could do this now, but you would have to had 5 of each of the specific days so that you don't ever miss them.

So a 1st monday, 2nd monday, 3rd....5th monday
1st wednesday, 2nd wednesday....5th wednesday

and so on for all desired days

**Comment by Medic97** [comment]
> Looks like you could do this now, but you would have to had 5 of each of the specific days so that you don't ever miss them.
> 
> So a 1st monday, 2nd monday, 3rd....5th monday 1st wednesday, 2nd wednesday....5th wednesday
> 
> and so on for all desired days. That should be a built in option and not need this

In my case I need a transaction on Mon, Wed, Fri. I could get away with 3 weekly repeats, one for each day. But I should just be able to select the specific days instead of the day interval. Why have 3 schedules for the same transaction.

**Comment by youngcw** [comment]
> > Looks like you could do this now, but you would have to had 5 of each of the specific days so that you don't ever miss them.
> > So a 1st monday, 2nd monday, 3rd....5th monday 1st wednesday, 2nd wednesday....5th wednesday
> > and so on for all desired days. That should be a built in option and not need this
> 
> In my case I need a transaction on Mon, Wed, Fri. I could get away with 3 weekly repeats, one for each day. But I should just be able to select the specific days instead of the day interval. Why have 3 schedules for the same transaction.

you don't need 3, but its a messy single one with like 15 specific days called out.  But like I said it should be possible without that hacky method

**Comment by Medic97** [comment]
> > > Looks like you could do this now, but you would have to had 5 of each of the specific days so that you don't ever miss them.
> > > So a 1st monday, 2nd monday, 3rd....5th monday 1st wednesday, 2nd wednesday....5th wednesday
> > > and so on for all desired days. That should be a built in option and not need this
> > 
> > 
> > In my case I need a transaction on Mon, Wed, Fri. I could get away with 3 weekly repeats, one for each day. But I should just be able to select the specific days instead of the day interval. Why have 3 schedules for the same transaction.
> 
> you don't need 3, but its a messy single one with 15 specific days called out. But like I said it should be possible without that hacky method

Oh I see what you mean, didn't know that feature was there. But yeah too much of a pain.
