### ISSUE TITLE
[Bug]: The "Spent" header column indented to "Balance" when overbudget in mobile view

### ISSUE THREAD

**Issue by Gaedious** [actualbudget/actual#2979]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Notice the "Spent" header is being pushed to the right towards "Balance" when you have over budget in your template. Perhaps consider removing "Spent"column to simplify the mobile viewing experience? Because I think the "Budgeted" vs "Balance" amount is enough to tell us how much we have left for spending when logging our spending on the go and given the limited screen estate on the phone. 

![image](https://github.com/actualbudget/actual/assets/174672561/bce35a65-da68-4669-bc48-c67ce565f237)

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mobile Device

**Comment by youngcw** [comment]
You are a few versions behind.  I think this has been fixed already

**Comment by Gaedious** [comment]
Alright then. I'll close this one out. Thanks.
