### ISSUE TITLE
YNAB4 Importer omits Notes field in split transactions

### ISSUE THREAD

**Issue by Rick-Thomas** [actualbudget/actual#298]
When importing a split transaction, the YNAB4 importer does not carry over the Notes or Memo field of the child transactions, and leaves it blank...

**Comment by MatissJanis** [comment]
👋 Hi Rick!
Would you mind sharing an example YNAB4 export file that is not working as expected? Without having clear reproduction steps it will be very hard to help here.
Closing the issue for now, but please feel free to re-open when you update us with the example file.
