### ISSUE TITLE
[Bug]: Custom report should not include tranfers between accounts when specfic category selected and Off budget transactions included

### ISSUE THREAD

**Issue by Klice** [actualbudget/actual#2986]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I want to generate a custom income report per payee. Im using the following settings:
![image](https://github.com/actualbudget/actual/assets/2285786/24cf1d84-c670-456f-83e7-9e9842bb2682)

It works as expected when `Show off budget` is disabled, but when it's enabled the resulting report also includes all internal transfers between my accounts in addition to income transactions.

I believe in that case internal transfers should not be included in the report. Only Income transactions from budget and off-budget accounts should be included.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 10

**Comment by carkom** [comment]
Is this still an issue?

**Comment by carkom** [comment]
This is working as intended. You're filtering by category. Internal transfers between accounts do not have a category. If you'd like to only include certain accounts then you can do that in the filter.
