### ISSUE TITLE
[Feature] Add 'notes' fields to the account object

### ISSUE THREAD

**Issue by dimaj** [actualbudget/actual#2987]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I am trying to write some automation around some accounts. To make that automation work, I am annotating accounts with various notes. Automation then reads those notes and does what it needs to do.

For example, I have an investment account that I would like to get updated balance of without connecting my account to the simpleFIN service. So, my idea was to add a note to the account describing how much of each stock I have in my portfolio. Then, have something like a Google Apps Script that would retrieve that note, identify various stock tickers, and update account register with latest portfolio value.

### Describe your ideal solution to this problem

The ideal solution would be to get an account by ID and have a `notes` field in it.

### Teaching and learning

Update API documentation for [Account](https://actualbudget.org/docs/api/reference#account) object

**Comment by dimaj** [comment]
I don't mind taking a stab at implementing this feature, but don't really know where to start. I did find the [account.d.ts](https://github.com/actualbudget/actual/blob/v24.6.0/packages/loot-core/src/types/models/account.d.ts) type definition, but not sure if there's more that is needed to be udpdated/modified.

**Comment by youngcw** [comment]
Could this also work if the existing notes in general were made available to the api?  I don't see a good reason to rework how the notes work vs using what is already there.

**Comment by dimaj** [comment]
sorry, i am not following the question.

web ui has notes for budgets, accounts and transactions. Both [Budgets](https://actualbudget.org/docs/api/reference/#budgets) and [Transactions](https://actualbudget.org/docs/api/reference/#transactions) export `notes` field through API. Account does not.

**Comment by youngcw** [comment]
> Both [Budgets](https://actualbudget.org/docs/api/reference/#budgets) and [Transactions](https://actualbudget.org/docs/api/reference/#transactions) export `notes` field through API. Account does not.

Weird that accounts doesn't since the notes are all stored together in their own table

**Comment by Wingysam** [comment]
Where does it export the notes field? I don't see it here https://github.com/actualbudget/actual/blob/5c0bee6031c081aa8ae573fbbe610611b302757b/packages/loot-core/src/types/api-handlers.d.ts#L39

**Comment by dimaj** [comment]
I was referring to the documentation (https://actualbudget.org/docs/api/reference), but now I do not see the table for budgets return.

**Comment by psybers** [comment]
I do not believe notes are exposed directly in the API.  This is a feature I will probably add.

For now though, you *can* read and update notes via the API by using the debug helpers.  You can see an example of that here: https://github.com/psybers/actual-helpers/blob/7e8cb824375e3b1834cd7ba3b45cc6d9040c514e/utils.js#L120-L141

**Comment by Wingysam** [comment]
Okay thank you!
