### ISSUE TITLE
[Bug]: Number format "1 000.33" is not working

### ISSUE THREAD

**Issue by andriantoeff** [actualbudget/actual#2996]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

When using number format `1 000.33`, both display and edits will still have the numbers behave as if using number format `1,000.33`

Happened in both desktop app and mobile view.

Extra info:
- Client version: v24.7.0
  - Desktop app is on Windows 11
  - Mobile view is on Chrome on Android 14, as PWA
- Server version: v24.7.0
  - Docker tag: latest-alpine

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Desktop App (Electron)

### Operating System

Windows 11

**Comment by MatissJanis** [comment]
Fixed by https://github.com/actualbudget/actual/pull/2981

**Comment by andriantoeff** [comment]
**"Fixed" by #2981 summary:** Number format "1 000.33" has been removed as it came from using "dje" locale format. The "dje" locale format is unfortunately not supported by the Chrome browser.

That's really unfortunate, but "1 000,33" can be an option to use along some efforts to make "," and "." can be used interchangeably as a decimal separator, at least for "1 000,33" number format. Depending on the expected scope, it may have been already implemented for some use-case.
