### ISSUE TITLE
[Bug]: Mobile view: cannot enter number longer than 3 digits when using number format "1 000.33" AND enabling "Hide decimal places"

### ISSUE THREAD

**Issue by andriantoeff** [actualbudget/actual#2997]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Condition:
- Mobile view
- Number format is "1 000.33", but not applied because of #2996
- "Hide decimal places" is checked

#### Case 1:
When user enters 4 digits, it displays in "1,000" number format, and will turn to a rounded 1 digit value after losing focus (e.g. "4,444" becomes "4"; "5,555" becomes "6").

#### Case 2:
And then when user tries to enter the fifth digit, it will turn to a rounded 1 digit value (e.g. "4,444" becomes "4" when keying in the fifth digit; "5,555" becomes "6" when keying in the fifth digit).

Case 1 & 2 combined means: user can only add transactions with 1 to 3 digit values.

Happened only in mobile view. Tested with other number format and show/hide decimal places combination and they are working normally.

Extra info:
- Client version: v24.7.0
  - Mobile view is on Chrome on Android 14, as PWA
- Server version: v24.7.0
  - Docker tag: latest-alpine

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mobile Device

**Comment by MatissJanis** [comment]
Fixed by https://github.com/actualbudget/actual/pull/2981

**Comment by andriantoeff** [comment]
**"Fixed" by #2981 summary:** Number format "1 000.33" has been removed as it came from using "dje" locale format. The "dje" locale format is unfortunately not supported by the Chrome browser.

That's really unfortunate, but "1 000,33" can be an option to use along some efforts to make "," and "." can be used interchangeably as a decimal separator, at least for "1 000,33" number format. Depending on your expectation, it may have been implemented for some use-case.
