### ISSUE TITLE
[Feature] Colorblind Accessible Display Options

### ISSUE THREAD

**Issue by atgrey24** [actualbudget/actual#3003]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

As a user with red/green colorblindness, I'd like to select an alternate color scheme for the display of template goals, so that I can more easily differentiate the status of each category.

I personally find the colors most difficult on the light theme, in particular the green and black are hard to differentiate. The red/orange is also difficult, but at least there's also a minus sign. 
![image](https://github.com/actualbudget/actual/assets/174978803/d6f5beda-f29f-42c3-9f6d-8c3b6a2edf4a)

It's a bit better on the dark and midnight themes, but still have room for improvement.
![image](https://github.com/actualbudget/actual/assets/174978803/1c8dfadf-5755-4db9-ba0c-f83756efad1b)
![image](https://github.com/actualbudget/actual/assets/174978803/c0150f37-d7a1-42fe-bcb5-31df58af731a)

That said, there are multiple types of colorblindess and the solution needs to consider them all.

### Describe your ideal solution to this problem

Allow the user to select an alternate color scheme. Some preset options are good for simplicity, though the ability to fully customize the colors for each status would cover more edge case users.

Secondary indicators are also very helpful. Different surrounding shapes, patterns, underlines, bold font, etc. For example, YNAB maintains Green/Orange/Red, but uses more highly contrasting versions of the colors, adds black borders to the "alert" states, and switches the font to white for "red" categories.
![image](https://github.com/actualbudget/actual/assets/174978803/f9a14708-2aac-4450-af61-e0f9a974f5f3)

### Teaching and learning

This should be places in the settings, grouped with other display options such as "Theme".

At least one preset alternate color scheme would be nice, so that users aren't forced to fiddle with deciding on custom colors for all states if it is not necessary.

**Comment by atgrey24** [comment]
From another user on the discord here is a link to WCAG AA color contrast minimum requirements:
https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum

and a tool for color contrast checks:
https://webaim.org/resources/contrastchecker/

**Comment by Juulz** [comment]
@alex-t-grey Does the new Color-blind theme work well for you? I know it's a dark theme, but it was much easier to build a dark theme.
