### ISSUE TITLE
[Bug]: macOS desktop app not compiled for Apple Silicon.

### ISSUE THREAD

**Issue by samwightt** [actualbudget/actual#3004]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

The desktop app for macOS has not been compiled for Apple Silicon (arm64). This makes the app very slow and sluggish on Apple Silicon devices, as it is having to be compiled by Rosetta 2 to work on arm64. Because the app is written in Electron, it should be able to be compiled for Apple Silicon macOS devices (like Slack is). It would be nice to have a separate arm64 macOS build, or even better, a universal app that works for both Intel and Apple Silicon devices.

<img width="707" alt="image" src="https://github.com/actualbudget/actual/assets/11824150/0a7a3c96-8be6-4e8a-9df8-f69a9a8cbfc5">

(Kind should be "Universal" or "Apple Silicon")

You can find a guide for how to do this [here](https://www.electronjs.org/blog/apple-silicon).

### Where are you hosting Actual?

Desktop App (Electron)

### What browsers are you seeing the problem on?

Desktop App (Electron)

### Operating System

Mac OSX

**Comment by Kidglove57** [comment]
Thank you - I wondered why it was so slow to launch (when the web app is almost instant)!

**Comment by MikesGlitch** [comment]
Attempted a fix here #3015 

Can someone who's experiences this try out the build here and let us know if it works better? https://github.com/actualbudget/actual/actions/runs/9860902928?pr=3015

**Comment by samwightt** [comment]
@MikesGlitch I'll give this a shot later today!

**Comment by michaelhofer** [comment]
I gave it a short try and it seems to work really well. Startup was very quick too.

**Comment by finnove** [comment]
Thanks. I downloaded the wrong version. Improved startup from 20 seconds(!) to 2 seconds by downloading the arm64 👍
