### ISSUE TITLE
[Bug]: Running Balance Display Limit

### ISSUE THREAD

**Issue by nickdzyuba** [actualbudget/actual#3013]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Values greater than $999,999.99 or less than -$99,999.99 cutting off in running balance column

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Chrome, Desktop App (Electron)

### Operating System

None

**Comment by nickdzyuba** [comment]
I saw that issue before I made the post. This is specifically for the running balance column.

![image](https://github.com/actualbudget/actual/assets/58453728/2c72b14d-2b7b-44b7-ae80-b5d8f4449c7e)

**Comment by MatissJanis** [comment]
The solution here is resizable columns. We have a feature request for that here - https://github.com/actualbudget/actual/issues/536
