### ISSUE TITLE
[Feature] Account Types

### ISSUE THREAD

**Issue by gabeklavans** [actualbudget/actual#3025]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Currently, all accounts are the same. Credit card accounts are the same as depository bank accounts, except the balance tends to be negative instead of positive. This isn't that confusing and is functional, but it could be nice to get some more customization in the backend/UI in terms of what "type" an account is.

A very simple benefit is being able to display a little credit card icon next to my credit card accounts in the Accounts list to provide some visual distinction. Potentially, the accounts can be visually grouped beyond "For budget" and "Off budget" using these account types.
Scripting can be made easier using these account types. The same can currently be achieved using account Notes, but those are a more verbose and advanced feature than what I'm proposing. 

### Describe your ideal solution to this problem

Taking a cursory look at the DB structure, it should be as simple as creating a fixed set of account types and adding them as a `type` or `account_type` field to the `AccountEntity`. If account types should be user customizable instead of a fixed set defined by Actual, that can be achieved in a similar way, though with added logic/UI complexity. I think even just providing the following would be a worthwhile start:
- `'depository'`
- `'creditCard'`
- `'investment'`
- `'other'`

### Teaching and learning

I envision a UI element appearing after clicking the pencil edit button next to an account name on an account view that shows the current account type in a drop-down menu that lets the user change the account type. Additionally, an account icon can automatically appear next to the account's name in the Accounts list (can be toggled off globally in settings, perhaps).

**Comment by gabeklavans** [comment]
Just thought of another potential feature. Credit card type accounts can be configured to set a credit line amount, so the current utilization can be displayed in percentage somewhere in the UI.

**Comment by jfdoming** [comment]
Duplicate of #2021. That said, thanks for the technical details and ideas! We'd welcome any PRs if you have time. One thought I had is that we could get the best of both worlds by supporting tagging within account notes (similar to transactions) for custom account "types", and then support a few standard types (your "Credit card" type) with additional features
