### ISSUE TITLE
[Feature] Enter percent instead of amounts when splitting (mobile and desktop)

### ISSUE THREAD

**Issue by astr0lab08** [actualbudget/actual#3030]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Right now, when we enter a split transaction, we have to calculate manually the amounts to make sure every part of the transaction match the total, especially on mobile.

### Describe your ideal solution to this problem

When entering a split transaction, instead of typing an amount, we could add an option to type a percentage instead. The app would calculate the amount automatically based on the percentage entered.

**Comment by atgrey24** [comment]
Just FYI, you can do inline calculations on desktop. So you can type `total * percentage` to calculate the amounts. There's also the "Distribute" function, though it does not allow weighting at this time. 

#2512  Is a similar request to get "Distribute" on mobile.
