### ISSUE TITLE
[Bug]: Custom Reports - Choosing "Last Month" includes current month

### ISSUE THREAD

**Issue by argeljoseph** [actualbudget/actual#3031]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

1. Create a report and choose:
          **Split**: Category
          **Type**: Payment
          **Interval**: Monthly
          **Range**: Last month

Save the custom report. You will see transactions in the report that are this month as well. 
<img width="384" alt="image" src="https://github.com/actualbudget/actual/assets/3426950/90a86eb1-c9ae-400b-a004-36fafbd70d10">

I was surprised with the report showing I spent a lot from last month on this category but it included this month's expenses too. 

### Where are you hosting Actual?

NAS

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Linux

**Comment by youngcw** [comment]
@carkom

**Comment by carkom** [comment]
There is an option to include/exclude current month. I've added an indicator to the sidebar for when it's toggled on.

https://github.com/actualbudget/actual/pull/3117

**Comment by matt-fidd** [comment]
@carkom I don't think that "last month"/"this month" should be eligible for the "include current month" toggle, I'd expect the behaviour to show the transactions for the previous/current month only in those modes.

**Comment by carkom** [comment]
It's already disabled for "This month" so no worries there. 

Why shouldn't people be able to add the current month to the "last month" graph if they want? I don't understand that logic. Another way to write this would be "Last 1 month" - similar to "Last x months" options. If you don't want current month in your saved graph then toggle it off, there's no need to prevent others from including it if they want.

I don't think we need to be unneccessarily restrictive in how people can/can't use the feature. What if someone has a use case where they want a live graph that includes current month and last month?

**Comment by matt-fidd** [comment]
Yep, fair enough! I think it might just be the way that it reads more definitively as "last month". The indicator will help to alleviate any confusion there though, as you say.

**Comment by argeljoseph** [comment]
Thank you! Didn't see that "Option" before! I'm closing this.
