### ISSUE TITLE
[Feature] Apply budget template to whole category

### ISSUE THREAD

**Issue by Neosaurus** [actualbudget/actual#3040]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

For e.g subscriptions, it would be useful to be able to apply a budget template to an entire category, but not necessarily the entire budget. For example, my grocery bill is very low this month, alongside several other bills. I don't want to apply my budget template to my Frequent category, but I do want it to apply to my Subscriptions category, which is unchanging. If I applied it to the whole budget, it would overwrite the existing money I have allocated. It is tedious to manually apply the template to each subscription.

### Describe your ideal solution to this problem

![CleanShot 2024-07-12 at 09 56 21@2x](https://github.com/user-attachments/assets/c4d91353-2449-4bac-b04f-b708a89f6e94)
Include a button here to "Apply budget template to category"

### Teaching and learning

Include in documentation for budget templates, when they are finished

**Comment by tatsumain** [comment]
Adding to this, would be nice if one could have an option to multi-select categories and/or groups where to apply a template. Attached a screenshot to show how it's done on the Other App. 

![Untitled](https://github.com/user-attachments/assets/1074061c-d3dd-4f90-8ec4-bd59befe9e44)

**Comment by Dreptschar** [comment]
I would like to work an this Feature if thats okay
