### ISSUE TITLE
[Bug]: We had problems syncing your changes

### ISSUE THREAD

**Issue by nicolesuet** [actualbudget/actual#3055]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

When trying to sync actual the error "We had problems syncing your changes" appears

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Chrome, Safari, Desktop App (Electron)

### Operating System

Mac OSX

**Comment by MatissJanis** [comment]
<img width="1284" alt="Screenshot 2024-07-14 at 18 18 03" src="https://github.com/user-attachments/assets/d15cee4e-bb5a-4e3e-9b4a-afd2fed8a71b">
