### ISSUE TITLE
[Bug]: Select all doesn't select the parent transaction in a split transaction

### ISSUE THREAD

**Issue by FlyingNovember** [actualbudget/actual#3057]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

When I select all transactions in an account, the split transactions parent transaction don't get selected.
This was a problem when trying to mark all transactions as cleared in one operation - the split transaction wasn't marked as cleared.

Might be related to #1864

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by MatissJanis** [comment]
See the discussion in https://github.com/actualbudget/actual/issues/2889
