### ISSUE TITLE
[Feature] Keyboard shortcut to only add single transaction

### ISSUE THREAD

**Issue by JukeboxRhino** [actualbudget/actual#3060]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Currently, pressing Enter when finishing a new transaction adds your transaction, and then starts a new one. There is no way to only add a single transaction without remaining in the editing state for a new transaction besides entering your transaction and then clicking "Cancel".

### Describe your ideal solution to this problem

I think that there should either be:
1. A dedicated keyboard shortcut (Shift+Enter? Ctrl+Enter?) to only add a single transaction and finish editing.
2. A new keyboard shortcut that maintains the current behavior and continues editing, and pressing Enter will only add one transaction and then finish.

Personally I think 2 is the better option based on the assumption that most people are only adding a single transaction at a time to an account, and that the more common use case should be the one with less friction.

Additionally, I feel like we should ask if adding a transaction by clicking the "Add" button should automatically start another transaction as well. I think the "Add" button should have the same functionality as pressing Enter, whichever way that goes.

### Teaching and learning

The new keyboard shortcut could be included in the help modal which displays keyboard shortcuts implemented in #3033.

**Comment by psybers** [comment]
Perhaps ctrl (cmd on mac) plus enter?

Less than ideal workaround, but for me I can hit ENTER then hit ESC two times and get it done.

**Comment by psybers** [comment]
As far as your '1 vs 2' argument, I honestly don't know the most common case.  I think that if someone is using bank sync (for the account currently being viewed!) then option 2 would be more common.  You rarely add things by hand.  If someone is not using bank sync, they add everything and then option 1 might make more sense?

**Comment by psybers** [comment]
Dupe of #1310. Perhaps close the old one in favor of this one that has conversation in it?

**Comment by JukeboxRhino** [comment]
> As far as your '1 vs 2' argument, I honestly don't know the most common case. I think that if someone is using bank sync (for the account currently being viewed!) then option 2 would be more common. You rarely add things by hand. If someone is not using bank sync, they add everything and then option 1 might make more sense?

Yeah, I can only say that personally I don't use bank sync but rather I'm entering transactions manually on my phone as I make them. If I'm entering a transaction on web, I'm usually entering one at a time. However, I'm not trying to optimize the app for just my use case here. I would like to know how other people use it. We can at least make adding just one transaction a little smoother

**Comment by youngcw** [comment]
duplicate of #1310
