### ISSUE TITLE
[Bug]: Invalid size declaration for two older javascript modals.

### ISSUE THREAD

**Issue by wdpk** [actualbudget/actual#3063]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

PostsOfflineNotification.jsx and ScheduleDetails.jsx both have invalid size size declarations, using only a name. the modal feature is expecting a height, width, or both. 
Because these are javascript, the invalid declarations slipped by. When converted to typescript this shouldn't happen. 
due to not having a size specified, these two modals could end up at full-screen width, making it hard to read.

Fixed by #2946 

### Where are you hosting Actual?

None

### Operating System

None

**Comment by psybers** [comment]
To be clear, the "bug" is fixed (having `size="small"`).  But the feature request to limit the size of those two modals still remains open?

**Comment by MatissJanis** [comment]
#2946 was merged, so I assume this is solved

**Comment by wdpk** [comment]
> To be clear, the "bug" is fixed (having `size="small"`). But the feature request to limit the size of those two modals still remains open?

I think? I can't figure out a way to reliably make these modals pop up to see what the size looks like. based on how the others behave, and how the new ones are called, I *think* the size should be limited to something reasonable?
