### ISSUE TITLE
[Feature] If a schedule has a name, add that name to the notes field when adding the transaction

### ISSUE THREAD

**Issue by amwelles** [actualbudget/actual#3064]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I like to have notes for all my transactions. I'd like it if the scheduled transactions would pull in the name of that schedule if one is provided.

Current implementation:  
![CleanShot 2024-07-16 at 08 45 26@2x](https://github.com/user-attachments/assets/ca7f2c51-2c4b-4616-9165-38caa8d93872)
![CleanShot 2024-07-16 at 08 45 38@2x](https://github.com/user-attachments/assets/10cfef2a-0f45-42f8-a44d-1a2e83a151e2)

Desired outcome:  
![CleanShot 2024-07-16 at 08 45 58@2x](https://github.com/user-attachments/assets/7d9d3ef8-777e-4f2c-a39c-f5534e244423)

**Comment by atgrey24** [comment]
You can edit the Rule associated to the Schedule so that it fills out the Note field however you like.
![image](https://github.com/user-attachments/assets/10e477c5-aa39-4222-8a09-23f626186141)
