### ISSUE TITLE
[Feature] - Additional Flexibility when updating Notes

### ISSUE THREAD

**Issue by latetedemelon** [actualbudget/actual#3068]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

When applying changes to multiple transactions via the UI, there is the option to prepend / replace / append updates to the notes.  I'd like that same functionality to work for the rules as well, it appears that replace it the only current option.

### Describe your ideal solution to this problem

As above.

**Comment by atgrey24** [comment]
I had this thought too. The capability should definitely be expanded to the Rules

**Comment by matt-fidd** [comment]
<img width="877" alt="Image" src="https://github.com/user-attachments/assets/cd28ed21-6e4d-4250-86e5-22e64e89eaa5" />

This has been implemented
