### ISSUE TITLE
[Feature] Remember selected filters

### ISSUE THREAD

**Issue by mchal** [actualbudget/actual#3070]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I'm a user of YNAB4 and there is one feature that I'm missing in Actual Budget - **remembering what filters where set** in "Reports" section (Reports dashboard and individual report pages)

In YNAB if I want to focus on specific accounts and categories I can select whatever I want and during my next session those filters will still apply.

Currently Actual Budget has an option to save filters (in "All accounts" section only; not "Reports" for whatever reason) but every time I'm opening "Reports" I have to apply those filters. They are not persisted, which is a shame in my humble opinion.

### Describe your ideal solution to this problem

1. On "Settings" page add a new check box "remember my last filter"  that would store last used filter in localStorage.
2. by default just remember the filters (still capture the last filters in localStorage) - no need to change anything in settings.
3. capture last filter in database rather than localStorage to use it across multiple devices

### Teaching and learning

If option 1 - by default checkbox "remember my last filter" is true.

**Comment by atgrey24** [comment]
You can create and save custom reports. 
![image](https://github.com/user-attachments/assets/55232708-1f7f-4df3-a52f-8097e14d1fd3)

**Comment by mchal** [comment]
Thank you for the reply. Yes - I should clarify that I was focusing on the default reports, i.e. Net worth, Cash flow, Monthly spending.

**Comment by atgrey24** [comment]
So I just realized that filters  you save on the All Accounts screen are available to be set in the reports!
![image](https://github.com/user-attachments/assets/f2a8f220-be0f-4ee1-b1e6-2f4507eafae5)

It won't remember what you used last, but at least you can now get to your favorite reports easily! I do still think they should add the save/rename filter menu to the report screens.
