### ISSUE TITLE
[Bug]: Pressing "?" gives a fatal error when  on the Budget selection screen

### ISSUE THREAD

**Issue by MikesGlitch** [actualbudget/actual#3083]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

## Reproduction (reproduced on PR environment): 

Navigate to the budget selection screen: 
![image](https://github.com/user-attachments/assets/46d9f3a2-16db-4d2a-af9c-2587c15ba2ae)

Press "?" (attempting to open the keyboard shortcut modal)

Result: "Fatal Error":
![image](https://github.com/user-attachments/assets/e6d15c62-9168-4a16-8202-f99d7c798708)

Expected result: It should show the keyboard shortcut modal.

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 10

**Comment by youngcw** [comment]
@psybers

**Comment by psybers** [comment]
Ahh, yes.
