### ISSUE TITLE
[Bug]: Apple cannot check for malicious software

### ISSUE THREAD

**Issue by jesstokes** [actualbudget/actual#3088]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I downloaded the Mac desktop client here: https://github.com/actualbudget/actual/releases/latest/download/Actual-mac.dmg
I moved the application to the Applications folder.
I double-clicked the application to launch.
A MacOS error message displayed: 
<img width="253" alt="Screenshot 2024-07-17 at 2 26 03 PM" src="https://github.com/user-attachments/assets/406b8d61-af44-4c74-a63e-ac45c7f80a25">

"Actual" can't be opened because Apple cannot check for malicious software.
This software needs to be updated.
Contact the developer for more information.

MacOS Sonoma 14.4.1

### Where are you hosting Actual?

Desktop App (Electron)

### What browsers are you seeing the problem on?

Desktop App (Electron)

### Operating System

Mac OSX

**Comment by wdpk** [comment]
related: https://github.com/contour-terminal/contour/issues/1421
they have a current PR that addresses it. 
https://github.com/contour-terminal/contour/pull/1541


@jesstokes the workaround is; 
> I had the same issue when installing using brew just now on the latest release (Sonoma 14.4.1). If you just open the binary after install you'll get a popup with no option to "Open" and no instructions for how to open. You have to right-click on the binary file (in `/Applications`) and select open there, and then a different popup says something similar except there's also an Open button :)

**Comment by jesstokes** [comment]
Workaround was successful. TY!

**Comment by MikesGlitch** [comment]
Will be fixed in the next release. 

Working artifact:  https://github.com/MikesGlitch/actual/actions/runs/10496563766
