### ISSUE TITLE
[Bug]: clicking on 'Copy last month's budget' should hide the modal after applying

### ISSUE THREAD

**Issue by tcrasset** [actualbudget/actual#3089]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Not sure if bug or feature.

On a budget of a certain month, clicking on `Copy last month's bugdet` (or on any option in that dropdown list) should hide the modal once the the action is completed.

Right now, it doesn't:
[Screencast from 2024-07-17 23-18-51.webm](https://github.com/user-attachments/assets/700c94c8-743c-4450-97ae-14b3a01a4158)

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

**Comment by sleepyfran** [comment]
Taking a look at this, will update with a PR shortly :)

**Comment by sleepyfran** [comment]
PR with the fix: #3092
