### ISSUE TITLE
[Feature] resizable table columns

### ISSUE THREAD

**Issue by danielo515** [actualbudget/actual#3094]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

My transactions have quite long paye names and descriptions. Most of them usually have a prefix, making many table views display useless information.
While I agree that some cleanup is needed, it is quite annoying to not be able to read the whole payee or note on most tables. This is specially annoying in the uncategorized transactions view

### Describe your ideal solution to this problem

I would like either an option to let columns go as wide as needed or an option to automatically resize them to fit their content, or at least the option to resize them.
I know this may be not that useful on mobile, but it's very frustrating to have enough space on my monitor and not being able to read the whole text because "design"

**Comment by shawalli** [comment]
looks like a duplicate of #536

**Comment by danielo515** [comment]
> looks like a duplicate of #536

It is, indeed
