### ISSUE TITLE
[Feature] Balance should be calculated and displayed for filtered values as well

### ISSUE THREAD

**Issue by Thiago-Morais** [actualbudget/actual#3103]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Any sorting that is not "all of the transaction" and "on ascending date order" hides the balance.

This makes sense for the total account balance. But, we could also have a filtered balance, which is calculated on the fly based on the current filtered options.

A very simple example. Let's say I want to know how much I have spent on food in the last 3 months with an account. 
I could filter the category and dates to have all the food transactions on an account:
![image](https://github.com/user-attachments/assets/2e6dadad-83c9-456a-9f54-d20a16204989)
> _All food transactions in the last 3 months_

But I'll have no idea of the total without manually counting

### Describe your ideal solution to this problem

My solution is that we have a "filtered balance" where it dynamically calculates the balance using the current filtered values.

On a really, really long list, it may take a while to calculate all of the transactions on each filter change so it may be wise to use some asynchronous processing of some kind where the person can adjust the filters without having to wait for the whole balance calculation each time.

### Teaching and learning

We can enable the filtered balance by default

**Comment by shall0pass** [comment]
I'm confused.  Isn't the filtered balance shown right there on your screenshot?

**Comment by Thiago-Morais** [comment]
> I'm confused. Isn't the filtered balance shown right there on your screenshot?

Oh, I see where I wasn't clear.

I meant the running balance with each transaction like this one:

![image](https://github.com/user-attachments/assets/c727b3f4-d380-4500-9aab-dd5e4b56be36)
> _Balance calculated for each transaction_

**Comment by shall0pass** [comment]
Ah.  Ok.  That's a known issue.

https://github.com/actualbudget/actual/issues/2703
