### ISSUE TITLE
New transactions often added with $0.00 amount

### ISSUE THREAD

**Issue by Deguello** [actualbudget/actual#311]
<img width="419" alt="Screen Shot 2022-01-29 at 5 26 56 AM" src="https://user-images.githubusercontent.com/16468471/151659204-52d84928-a022-462f-b3fc-31f9d1c09276.png">

Very often when I add a new transaction it is recorded with a $0.00 amount despite my explicitly and definitely entering a non-zero amount.

**Comment by Kidglove57** [comment]
I have not personally been able to reproduce this on web.

**Comment by rich-howell** [comment]
Hey @Deguello 

Thanks for this, I have tried and tried and have been unable to replicate this. If you are still having this issue or have replication steps, please do let me know and I will re-open the issue. 

Cheers
Rich
