### ISSUE TITLE
[Feature] Sort accounts

### ISSUE THREAD

**Issue by TheBlueCircle** [actualbudget/actual#3110]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I have a large number of accounts. I would like to have a better way of ordering them in the left-hand menu (desktop view) rather than relying on drag and drop. 

### Describe your ideal solution to this problem

Ideally, there would be a way to automatically sort accounts under each account group. This could involve an automated function to sort accounts:

* alphabetically 
* By value
* By last transaction

UI options would need to be worked up, but there could feasibly be some icon / option on each category group to access sorting (and potentially other future) options.

**Comment by elijaholmos** [comment]
I have the same use case. Let me propose also that we can have more granular grouping of accounts... on and off budget right now is extremely restrictive. A lot of my accounts have prefixes before them (eg "[C-P1] Account 1") and advanced grouping could let me associate attributes with my accounts for quick search, sorting, and other navigation uses.
