### ISSUE TITLE
can't leave category blank if payee has rule to fill it

### ISSUE THREAD

**Issue by bpaulien** [actualbudget/actual#312]
This is from a bug report on slack.

If I am putting in a transaction for a Payee that autofills a category but actually want to temporarily leave off a category its not possible to delete the category, it autofills back in when I shift focus away.
Instead I have to add it and then remove the category. Would be nice if could remove during initial entry.
Use case is when I know there’s a charge but haven’t figured out the correct split/category.

**Comment by Kidglove57** [comment]
I can reproduce this. It is a minor annoyance for me as I would always replace the category whilst setting up the transaction

**Comment by youngcw** [comment]
I think the best way around this is to create a post rule that unsets the category.  That way the last word is to not have a category.  Its kinda annoying, but for the time being its the best way around this issue.
