### ISSUE TITLE
[Bug]: Bank-Sync Rate Limit error handling

### ISSUE THREAD

**Issue by xrebelox** [actualbudget/actual#3120]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

It seems some institutions set a daily rate limit which is fine, however, Actual provides a generic error `This account is experiencing connection problems. Let's fix it.` when you click to check said error it just shows like this:
![image](https://github.com/user-attachments/assets/47971379-0823-483c-bd91-4006ace29d21)

Checking the docker logs I can see that the error is as follows:
```javascript
{
  summary: "Couldn't update account transactions",
  detail: 'Daily request limit set by the Institution has been exceeded.',
  status_code: 429,
  type: 'RateLimitError'
}
```

I looked into the [code ](https://github.com/actualbudget/actual-server/blob/c19cc56c5503f521e540e8157e845c40fcc6f792/src/app-gocardless/services/gocardless-service.js#L51) and we're already handling the RateLimitError but it seems that the error sent to the front-end is not correct (I checked the network requests and the error was sent when hitting the `/gocardless/transactions`), here's the response from the API:
```json
{
    "status": "ok",
    "data": {
        "error_type": "SYNC_ERROR",
        "error_code": "NORDIGEN_ERROR"
    }
}
```

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Linux

**Comment by totalitarian** [comment]
Same issue

**Comment by totalitarian** [comment]
> It would be nice if this was handled better because GoCardless has begun to heavily rate limit:
> 
> > Starting from 19 August 2024, we will implement a limit of 10 API requests per day for each access scope (details, balances, transactions) on account id level as part of our ongoing efforts to enhance operational effectiveness and minimize potential issues for all our clients. This phased approach will allow us to optimize our services progressively.
> > We plan to establish a limit of four requests per day for each access scope in the next phase.
> 
> From an email they sent out a couple of weeks ago. I still don't see this limit being mentioned in their docs.

Damn, 4 per day is going to hurt

**Comment by matt-fidd** [comment]
This should be fixed in `latest` as long as you're running the most recent server and front end.

![image](https://github.com/user-attachments/assets/076219d7-f896-4e42-8829-36e7f2a05afe)

![image](https://github.com/user-attachments/assets/4092a895-d8ae-4c0f-bb80-04a2ef41a971)

actualbudget/actual-server#439

**Comment by matt-fidd** [comment]
There's an issue tracking this actualbudget/actual-server#431
