### ISSUE TITLE
[Feature] Allow importing QIF/CSV/etc. formats via API

### ISSUE THREAD

**Issue by Scrub000** [actualbudget/actual#3124]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

In ActivePieces, I have a [piece](https://github.com/activepieces/activepieces/pull/5152) which automatically gets bank statements in QIF. I would like to then automatically upload these statements into Actual Budget via the API.

### Describe your ideal solution to this problem

Currently, I need to manually click on "Import" to import these files. I would prefer to do it automatically via ActivePieces.

### Teaching and learning

An additional piece of documentation in the transaction section would be fine.

**Comment by mcalligator** [comment]
A very similar prior feature request for this is captured in [[Feature] Add API support for importing transactions from a file #1085](https://github.com/actualbudget/actual/issues/1085).
