### ISSUE TITLE
[Feature] Payee name "contains" in scheduling

### ISSUE THREAD

**Issue by Neosaurus** [actualbudget/actual#3125]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I donate to Signal every month. The transaction payee includes the date of the transaction. Thus, it is hard to set up a schedule for this. I propose an option under rules for the payee to "contain" a certain word, e.g "Signal Foundation". This could cause unwanted donations I make to Signal outside of my regular be set under the rule, but with other rules (e.g date of transaction, value of transaction) this could be mitigated

### Describe your ideal solution to this problem

Include an option in the rules dropdown to include "contains" 
![CleanShot 2024-07-23 at 13 03 58@2x](https://github.com/user-attachments/assets/cf565758-4289-4727-9ee3-e98f6637af0e)

**Comment by jfdoming** [comment]
Hey! This exists if you switch from "Payee" to "Imported payee"

**Comment by Neosaurus** [comment]
> Hey! This exists if you switch from "Payee" to "Imported payee"

That's great, thank you! I suppose this could be made more clearer - I wouldn't have guessed to check Imported payee ;)
