### ISSUE TITLE
[Bug]: layout issue with firefox (Split transaction)

### ISSUE THREAD

**Issue by wnklmnn** [actualbudget/actual#3126]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

When trying to add a split transaction using Firefox(mobile) the input elements exceed the bounding container. 

![Screen Shot 2024-07-23 at 17 19 00](https://github.com/user-attachments/assets/c717c42e-d2dc-4448-a57b-08183bb9624a)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Mobile Device

**Comment by shall0pass** [comment]
Came here to report the same issue.  I'm using chrome.

**Comment by JL102** [comment]
v24.8.0 update fixed the issue for me, thanks a ton y'all! (using Chrome on Android)
