### ISSUE TITLE
[Bug]: Hidden Categories spends and budget are being shown in summary page

### ISSUE THREAD

**Issue by bchooxg** [actualbudget/actual#3129]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [ ] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Values for budget and spend in hidden categories are being considered in the columnar total summary. 
<img width="683" alt="image" src="https://github.com/user-attachments/assets/9c9e63d7-e98b-4b5f-aea7-d115ec3b8a6d">

As well as the summary top card summary.  

![untitled](https://github.com/user-attachments/assets/60a082bb-df44-46e8-a94b-78dd60c28413)

This makes it hard to tally up or get an accurate representation of the amount spent or budgeted. 

Only once the hidden categories are toggled then we are able to see the reason for the values not tallying

<img width="654" alt="image" src="https://github.com/user-attachments/assets/12b6ffa4-f3dd-4611-b745-a255846c4afb">

Steps to reproduce 
- Create an entry in a future date where there is no transactions
- Assign that spend to hidden category 
- Navigate to the month of the future transaction 

Use case :
Im trying to reconcile my balances in my accounts, however I do not want reconciliation amount to be considered as my spending or expenses for the month . But would rather want to adjust the initial balance of the account ( similar to budget bakers ) 

![IMG_4126](https://github.com/user-attachments/assets/01337830-94e1-4aa4-901f-5387abf96e62)

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Chrome

### Operating System

None

**Comment by youngcw** [comment]
Excluding hidden categories from the calculations would cause the budget to be inaccurate to what the accounts show, so including hidden categories in the totals is by design.

Im don't quite understand what you are meaning about the reconciliation process, so I cant suggest anything that would help.

**Comment by xNS5** [comment]
> Excluding hidden categories from the calculations would cause the budget to be inaccurate to what the accounts show, so including hidden categories in the totals is by design.

For context, I'm using the Budget Mode experimental feature. How would you categorize credit card payments, for example? I could leave them uncategorized, but if I pay off a credit card balance for $500 for example then that would create a new transaction when in reality I'm just moving money around. The choice for myself or another user is to either leave the transaction uncategorized, or include it in the given month's budget. 

Follow up question, if it's possible to hide categories and groups, why include them if they're visually hidden?
