### ISSUE TITLE
"Add new" transaction - tab to cleared flag - enter doesn't "add" transaction

### ISSUE THREAD

**Issue by bpaulien** [actualbudget/actual#313]
When entering transactions, typically once you've entered an amount in either the Payment or Deposit column, you can hit enter, and it will add that transaction, and start a new blank one.  I was just entering one that had already cleared in the bank, and tabbed from the amount to the cleared column and hit space to toggle the checkbox.  I then hit enter, but was unable to enter the transaction.  I had to shift-tab back to the amount, and then the enter key was able to click the add button.  

I think it would be helpful to be able to add the transaction by hitting enter if you're in either of the amount columns OR the cleared column, since sometimes I want to toggle the cleared status as I'm entering the transaction.

**Comment by j-f1** [comment]
This was fixed by #234!
