### ISSUE TITLE
[Feature] Custom reports should have the ability to split based on Tags

### ISSUE THREAD

**Issue by kennydrobnack** [actualbudget/actual#3130]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I am planning to heavily use Tags in my budget now that they are available. With the custom reports, I would like to be able to create reports that show spending based on Tags.

Current options are: group, category, payee, account, and interval.

The only current use of Tags in custom reports is the ability to filter based on Tag names, so the only transactions that would be in the report would be the transactions where the tags match the filter.

### Describe your ideal solution to this problem

For the initial version, just add the ability to split the reports based on tags similar to how groups and categories are handled.

Ideally I'd like to see two levels of splits based on the Donut graph/pie chart with the ability to drill down. For example, you could have splits based off category and tags and it would initial show the categories and when you click on a category it would show tags within the category.

### Teaching and learning

In the "Split" drop-down when creating custom reports, include "Tags" as an option.

In the documentation, it could show samples of what it would look like to use tags, such as tagging transactions as part of your #vacation2024 whether they are in the Groceries, Travel, or Gas Money categories.

**Comment by olaberglund** [comment]
#5633 contains suggestions for how to deal with transactions that have multiple tags, and is also related to creating reports based on a tag split.
