### ISSUE TITLE
[Feature] Provide UI for managing Transaction tagging

### ISSUE THREAD

**Issue by crankeith** [actualbudget/actual#3136]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

When tagging transactions, I forget sometimes what exact phrase I use for various tagging and I have tagged a few transactions with variations of the same word (e.g. Physio, Physiotherapy) and even misspelled it. 

### Describe your ideal solution to this problem

Store used tags somewhere and when you type the "#" symbol in notes, it pulls up a dropdown of the previously used tags so I don't have to remember what I used before OR migrate tags to a new "tags" field for Transactions so that tags can be added, deleted and managed in an admin UI

**Comment by gitchap** [comment]
Yes, this would be great. Additionally, when bulk editing transactions, an option to perform tag related maintenance would be helpful. 

ie. from selected items:
-Remove all tags
-remove select tags
-append select tags
-etc...
