### ISSUE TITLE
[Bug]: Imported pending transactions don't follow bank behavior (SimpleFIN)

### ISSUE THREAD

**Issue by ntsp00** [actualbudget/actual#3138]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Imported pending transactions from SimpleFIN don't follow the bank's behavior if they never post. The transactions on the bank's ledger fall off but they remain on Actual's ledger, resulting in a balance mismatch and the budget being incorrect. 

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by sondregronas** [comment]
Same happens with GoCardless - there is no `transactionId` key in the pending transactions which doesn't help.

```json
"pending": [
    {
        "bookingDate": "2024-08-01",
        "valueDate": "2024-08-01",
        "transactionAmount": {
            "amount": "-100.00",
            "currency": "NOK"
        },
        "remittanceInformationUnstructured": "Redacted",
        "remittanceInformationUnstructuredArray": [
            "Redacted"
        ]
    }
]
```

**Comment by youngcw** [comment]
We have no plans to ever automatically delete transactions that don't appear in the bank sync list since that will likely cause more trouble than fixes.  For now the way to fix this is to delete the transactions that never clear.  In the future we may have options to ignore/delete pending transactions on import.
