### ISSUE TITLE
Split Categories on Scheduled Transaction causes Schedule to update as Missed

### ISSUE THREAD

**Issue by kazzazed** [actualbudget/actual#314]
I have a scheduled transaction which is not linked to a rule and so has no category when it is created (set to auto create). The transaction needs to be split and the amounts vary month to month (principle and interest on a loan). When I select the scheduled transaction and click Split, it creates a whole new transaction which I can update with the splits, but the original scheduled transaction remains and is updated as Missed. It looks like more a record of the scheduled thinking it is missed, it doesn't have an impact on account balance, but I have the icon in my account as a missed scheduled transaction.
How should I be doing this so that the flow works better?

**Comment by youngcw** [comment]
Splits in Rules is in the PR queue at the moment, so that should somewhat fix this.
