### ISSUE TITLE
[Bug]: modals - help modal has weird focus

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#3141]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Originally reported: https://github.com/actualbudget/actual/pull/2946#issuecomment-2241428791

Introduced in #2946 

Only the help modal has this weird focus behaviour. Other modals seem to be OK.

<img width="1440" alt="Screenshot 2024-07-27 at 14 02 49" src="https://github.com/user-attachments/assets/4b9346a2-e34c-4bb7-898a-1d10d245169a">

### Where are you hosting Actual?

None

### Operating System

None

**Comment by xZToxicZx** [comment]
Just done a bit of digging seems its caused by when shift is pressed and does affect all Modals, assuming the "focus" is the white border.

Will investigate further
