### ISSUE TITLE
UI bug: split transaction is created when the window focus is lost and returned

### ISSUE THREAD

**Issue by skrobul** [actualbudget/actual#315]
Every now and then I accidentally create a split transaction which is hard to undo (already discussed in https://github.com/actualbudget/actual/issues/328), but today I have noticed that it's not really me being clumsy but there is a bug in the UI which changes the transaction into a split when it should not.

**Steps to reproduce:**

1. Import some new transactions
2. Click on the 'Categorize' column on any uncategorized transaction (let's call it `TransA`). Don't input anything at this stage. 
3. Switch focus to any other application window
4. Click back into the Actualbudget window, but select any other transaction (for example one below the originally selected. Let's call it `TransB`)

**Expected result**: The cursor moves to a new transaction `TransB` , leaving the original transaction `TransA` uncategorized.

**What actually happens:** Original transaction `TransA` is unnecessarily converted into split. The cursor is also placed there instead of `TransB`.

Example:

https://user-images.githubusercontent.com/183976/149516022-350229ff-b600-483f-a0af-f2b824fd1b1d.mp4

**Comment by MatissJanis** [comment]
👋 This has been fixed in the new autocomplete component.

See this issue for the full release of the new component: https://github.com/actualbudget/actual/issues/773
