### ISSUE TITLE
[Feature] Allow different dates 'transfer' transactions

### ISSUE THREAD

**Issue by radh21301** [actualbudget/actual#3152]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

**The Problem:**

Currently, when you create a 'transfer' transaction, Actual forces them to be on the same day. So, when I try and edit the date of the receiving transaction, it also changes the date of the sent transaction. To me this is not really great.
This is also true when we click on the 'Make Transfer' feature: https://actualbudget.org/docs/transactions/transfers/#make-a-transfer-from-two-existing-transactions. It makes the dates of both the transactions the same.
<img width="859" alt="image" src="https://github.com/user-attachments/assets/67b818e4-6160-4771-9ac7-66a86a397b35">

**Why is this not great:**
* Usually there is a day or two delay before the amount it credited to the receiving account.
* I think this is true for almost all transactions
* Mainly - it bugs the heck out of me since it does not match my actual bank statement - in case I need to double check something :)

### Describe your ideal solution to this problem

**Solution Suggestion:**
* Allow the user to specify different dates in such transactions.

**Comment by radh21301** [comment]
This is a duplicate of https://github.com/actualbudget/actual/issues/661

So people, upvote that one instead.

**Comment by youngcw** [comment]
Closing in favor of #661
