### ISSUE TITLE
[Bug]: Cannot link Barclays account using GoCardless

### ISSUE THREAD

**Issue by planetgong** [actualbudget/actual#3155]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Attempted to link Barclays account. Log into Barclays account. Select account to link. Throws back to Actual with an error message saying raise as GitHub issue. Have tried to link other banks in same browser (Natwest, TSB) and they worked without issue. Have tried in Firefox and Chrome. Desktop and in browser (Brave & Chrome)

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Linux

**Comment by MatissJanis** [comment]
<img width="954" alt="Screenshot 2024-07-28 at 20 36 26" src="https://github.com/user-attachments/assets/3358631b-fa05-45a4-9afa-67e8d5ac2897">
