### ISSUE TITLE
Duplicate Account names should not be possible.

### ISSUE THREAD

**Issue by bpaulien** [actualbudget/actual#316]

**Comment by DistroByte** [comment]
Can confirm you can have duplicate account names screenshot ![here](https://i.dbyte.xyz/firefox_uJVGEksxl.png]

**Comment by CharlesEkkel** [comment]
I've made a PR for this issue as you can see above ^ I figure the simplest way to deal with this is just to add a validation rule when creating accounts.

**Comment by MatissJanis** [comment]
👋 May I ask: why not? Why should I not be able to have two accounts with the same name if I wanted to?

For example: I might have multiple accounts with the same bank. But these accounts might be of different types: checking, savings, mortgage, investments.

**Comment by rich-howell** [comment]
> 👋 May I ask: why not? Why should I not be able to have two accounts with the same name if I wanted to?
> 
> 
> 
> For example: I might have multiple accounts with the same bank. But these accounts might be of different types: checking, savings, mortgage, investments.

How would this work for things like importing? How would you differentiate between the two accounts in a drop down? 

If I look in my bank I have my bank called **starling** but inside that is **current account** and **savings account ** 

Having two accounts in the account register with the same name will become confusing.

**Comment by j-f1** [comment]
> Having two accounts in the account register with the same name will become confusing

Agreed, I name mine “USAA Checking” and “USAA Savings” to disambiguate.

Since people might already have duplicate account names I think we should just block any new attempts to save an account name that’s already used rather than having some preemptive approach.

**Comment by MatissJanis** [comment]
Ok, you convinced me. For import purposes it does make sense to require unique names so we could map 1:1 (we could also use account iDs for that, but it would be.. quite "clunky" experience).

Should we make this a feature request?

**Comment by rich-howell** [comment]
> Should we make this a feature request?

Or is it a bug?

**Comment by rich-howell** [comment]
> > Should we make this a feature request?
> 
> Or is it a bug?

Took an executive decision, it is a bug.

**Comment by CanardContent** [comment]
Hello, I volunteer to solve this :) This is the first time I'll contribute to an open source project so I might need some time :D

**Comment by Tigatok** [comment]
We can handle this on the front-end if we want a quick win, not sure how intense this would be for the backend/at the API level. Let me know if you want me to move to BE.

https://github.com/actualbudget/actual/assets/3906461/80f56440-1b09-4823-bc09-e785e07668b3
