### ISSUE TITLE
[Bug]: Positive transactions importing as negative via SimpleFIN

### ISSUE THREAD

**Issue by ntsp00** [actualbudget/actual#3162]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I have my Addition Financial car loan linked via SimpleFIN and loan payments are importing as expenses on the account, which is increasing the loan balance rather than decreasing it. In the screenshots, 7/26 is when I created the manual transfer entry and 7/29 is when the transaction imported:

![Untitled2](https://github.com/user-attachments/assets/682eebb9-7f65-42c3-9455-d5a3635a6882)

![Untitled3](https://github.com/user-attachments/assets/a42a0348-0342-45db-9bdf-c1b201d52f31)

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by MatissJanis** [comment]
<img width="954" alt="Screenshot 2024-07-28 at 20 36 26" src="https://github.com/user-attachments/assets/433e9e29-3c68-4b9a-b3d0-c0b9708dc98e">
<img width="1307" alt="Screenshot 2024-07-28 at 20 35 52" src="https://github.com/user-attachments/assets/17af5226-21fd-4eea-8054-cf20c8cb8ac0">
