### ISSUE TITLE
Ability to print the generated reports on Actual

### ISSUE THREAD

**Issue by FSNaval** [actualbudget/actual#3174]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I could not find a way for printing the generated reports on Actual

The ability for having printed reports will help current users to have a hard copy of their economic history/transactions in case they need to proceed with their financial auditing, especially during the last month of the year where the planning for the following month is being made.

### Describe your ideal solution to this problem

On the Center Menu of the custom reports, an additional button could be placed that could give the opportunity to the user to print the generated reports using the deafult printer settings of the computer/browser etc.

### Teaching and learning

In the current documentation, under the Rports & Filters Section, you can add a paragraph describing the printing function/capabilities.

**Comment by atgrey24** [comment]
You can already use the build in Print capabilities of the browser to print the page or save as pdf
![image](https://github.com/user-attachments/assets/31b9a3bd-64bb-4034-b472-e6c184c13ae5)

Screenshot/capture tools could similarly be used to get just the snip you need.

What additional capabilities are you hoping for that are not currently met by these available options?

**Comment by rossp** [comment]
Printing the Data Tables is not functional as only the currently viewed portion of the table is printed.  eg the below should probably be a 4-5 page report given the number of categories our budget has, but it only prints on a single page. 

We'd prefer to print our budget (or this report) to sit down away from our devices to discuss family finances. 

![Image](https://github.com/user-attachments/assets/e0838408-b10f-4cc7-8c03-2acbe306ad64)
