### ISSUE TITLE
When selecting Upcoming transactions the "Selected balance" does not sum the payment/deposits

### ISSUE THREAD

**Issue by rmarkoff** [actualbudget/actual#319]
On my credit card I can see 4 upcoming transactions, but when selected the value is 0. When selecting already entered transactions the value is correct.

**Comment by rich-howell** [comment]
This is replicatable. 

![image](https://user-images.githubusercontent.com/22135084/196491423-cc06998b-681a-4f76-95be-e01dd5ca6827.png)
