### ISSUE TITLE
[Feature] Add a Return to Current Month button & icon

### ISSUE THREAD

**Issue by Teprifer** [actualbudget/actual#3192]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Make it easier to return to the current month when you've scrolled to look at a month in the long past(or future), and alert which direction it is relative to the current month(s) currently being viewed.

Originally from this discord thread: https://discord.com/channels/937901803608096828/1263002765131776001

### Describe your ideal solution to this problem

Add a button mocked up as below,  Clicking it would be the equivalent of clicking the current month.
The intent is to show which direction the current month is, and that it is off screen.

_The red arrow is just a place holder to indicate the general idea and is not a design suggestion._
![image](https://github.com/user-attachments/assets/faa7f296-d9f5-4d75-9bc1-0828023804fa)

The indicator would only show if the current month is off screen, and not visible when the current month is visible but not in current selection, and not visible if the current month is in current selection (3111 has improvements there).

An alternative would be to just show a button in that area to return to current month(without indicating direction) - with the same visibility rules as outlined.

### Teaching and learning

Only show when the current month is off screen.

**Comment by Hydro8** [comment]
I vote for this 👍 ! Very useful when you browse through your history and want to quickly get back to current month.

**Comment by UnderKoen** [comment]
This has been implemented with: https://github.com/actualbudget/actual/pull/3703
