### ISSUE TITLE
[Bug]: out of sync with migrations

### ISSUE THREAD

**Issue by FlorineC** [actualbudget/actual#3195]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Hello,

I locally installed Actual yesterday (v24.8.0) and created my first budget.
Then I tried to put my budget online by creating a pod on PikaPods (which is using v24.7.0). However when I try to sync my budgets I have an error:
![image](https://github.com/user-attachments/assets/8bf1a54e-da3c-401e-9555-246a102a1c9c)

I think it may be due to the budget being created on a newer version. Could someone confirm me this and help me please?

Sincerely,

Florine C 

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by Kidglove57** [comment]
It certainly sounds like it is! Only a few days to wait until PikaPods will be on 24.0.8 and should open with no probs.
