### ISSUE TITLE
[Bug]: nYnab Import Produces "An unknown error occurred while importing. Please report this as a new issue on Github." 

### ISSUE THREAD

**Issue by teakdecks** [actualbudget/actual#3196]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

While importing my nynab JSON file it came up with an error report, seems to have been during transaction importing. 

JSON created using the recommended tool.

[ynab-budget-export-2.json](https://github.com/user-attachments/files/16488250/ynab-budget-export-2.json)

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Safari

### Operating System

Mac OSX

**Comment by youngcw** [comment]
Do you have any duplicate categories between your used and hidden categories?  That will break the import.  Best way to fix it is to change the category names in ynab of the hidden categories and then do the import

**Comment by youngcw** [comment]
I tried the file and it worked just fine for me

**Comment by teakdecks** [comment]
Very weird, I have no duplicates, and I'd tried on both my mac and on iphone. What browser/OS are you using?

**Comment by teakdecks** [comment]
Worked in Chrome just fine. Should have thought to do that sooner! Guess that means theres a bug in safari?

**Comment by youngcw** [comment]
I guess.  If you want to try on safari again and see what the browser console says is the problem and paste it here, that maybe could help

**Comment by teakdecks** [comment]
Ugh, weirdly it worked this time. Not sure if it was gremlins or someone coincidentally solved it?! I'll mark as closed either way.
