### ISSUE TITLE
[Bug]: Transfer Transactions no longer auto-fill category as "Transfer".

### ISSUE THREAD

**Issue by SaveYourMoney** [actualbudget/actual#3201]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Since updating to v24.8.0 I've noticed that when I enter a transfer transaction the category no longer fills automatically with "Transfer" as the category.  Instead it looks as though I need to choose a category.

![image](https://github.com/user-attachments/assets/77cf49b4-4ddb-479e-a8ff-a09884d48668)

Searching the list of categories yields no results for "Transfer", so I entered the transaction with no category.  Once I clicked "Add" to finalize the transaction, it was assigned the category of Transfer even though it was not shown during entry and wasn't even a choice during entry.

![image](https://github.com/user-attachments/assets/fa4e12c9-d3a0-407c-9cd8-f948859fab3e)

The end result is correct.  The money is moved from checking to credit card and I'm left with no uncategorized transactions, but at time of entry it is confusing because prior to v24.8.0 any time a transfer payee was selected, Transfer was hard-coded into the category field and from what I remember, was not able to be edited.  I would suggest that if this new behavior is by design, it should be changed to avoid confusion and people trying to categorize the transaction and not being able to find Transfer in the list of categories.  If it is a bug, not an expected change, well then, it just needs fixed.

Also of note, the behavior is the same whether I choose a transfer payee from the list, or click on Make Transfer at the bottom of the payee list dropdown.

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Other

### Operating System

Windows 10

**Comment by Kidglove57** [comment]
I have also noted this behaviour ie a category is requested for an “on budget” transfer:
1) I have checked and it is only in 24.8.0 (24.7.0 is fine)
2) Oddly on mobile it still correctly populates the category box as “transfer”.

**Comment by MatissJanis** [comment]
The behaviour only happens in the "new transaction" creation flow. After the transaction is created - it correctly shows the "Transfer" label in category column.

Definitely a regression.

**Comment by SaveYourMoney** [comment]
I should have also noted that this is also an issue on self-hosted on Windows.  My main budget is hosted by Fly but I keep a local server copy on my PC for testing purposes.
