### ISSUE TITLE
[Feature] Support newer versions of OFX format

### ISSUE THREAD

**Issue by faroguy** [actualbudget/actual#3208]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

All of my banks lets me download my transactions in OFX format. However, earlier this year (April I think?) Actual budget started refusing to import anything from one bank in particular. Only today did I figure out that my bank is providing the information in the OFX V2 format, while other institutions are still providing the V1 format. The specification is laid out here: https://financialdataexchange.org/FDX/About/About-FDX.aspx?WebsiteKey=deae9d6d-1a7a-457b-a678-8a5517f8a474&hkey=dffb9a93-fc7d-4f65-840c-f2cfbe7fe8a6&a315d1c24e44=5#a315d1c24e44 
Sorry for the long link.
As more banks move to the new format, it would benefit Actual to be able to import from those files.
Any thoughts?

### Describe your ideal solution to this problem

Implementing the new format would be wonderful.
At least being able to recognize the file and provide a meaningful error would be a great start.

### Teaching and learning

Implementing this feature, or at least providing an error, would help users understand that nothing is wrong with their file.
Adding some documentation about the new version would also help. Currently there is nothing.

**Comment by vinstaal0** [comment]
There are a shit ton of bank formats that are used, I see the use of MT940 and CAMT053 the most for my clients.

**Comment by faroguy** [comment]
That is true and I'm not saying that every format needs to be supported. However, Actual supports one version of the OFX format and not another. In my case, this was a huge source of confusion for me as the file I downloaded used to work and then suddenly didn't. In the case of less technical users, they would not be able to understand the reason. For this reason alone, it would be worthwhile to give an error message saying this version of OFX is not yet supported and to import the transactions another way.
