### ISSUE TITLE
[Bug]: Wrong payeeNamee since 24.8.0 (logic)

### ISSUE THREAD

**Issue by Soulplayer** [actualbudget/actual#3216]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

After upgrading from 24.7.0 to 24.8.0 I have problems with the payeeName logic. Actualbudget chooses the wrong one. 

Log version 24.7.0:
`[{"transactionId":"2024-08-07-10.24.47.258375","bookingDate":"2024-08-07","valueDate":"2024-08-07","transactionAmount":{"amount":"414.04","currency":"EUR"},"creditorName":"name-name S & I","creditorAccount":{"iban":"Accountnumber","currency":"EUR"},"debtorName":"FONS (VUTG) - GROEIPAKKET","debtorAccount":{"iban":"Accountnumber","currency":"EUR"},"remittanceInformationUnstructured":"FONS (VUTG) - GROEIPAKKET Overschrijving TRIERSTRAAT 9 1000 BRUSSEL BE46 3751 1175 9136 BIC: BBRUBEBB /C/ GROEIPAKKET - 1.00.318.245 GEZINSBIJSLAGEN 07/2024","bankTransactionCode":"code","internalTransactionId":"code","date":"2024-08-07"`

screenshot from actual 24.7.0
![image](https://picsur.verhaeghe-steyaert.be/i/1ca596d1-8779-4bfd-8074-6a5cb9bef908.jpg)

Log version 24.8.0:
`[{"transactionId":"2024-08-07-10.24.47.258375","bookingDate":"2024-08-07","valueDate":"2024-08-07","transactionAmount":{"amount":"414.04","currency":"EUR"},"creditorName":"name-name S & I","creditorAccount":{"iban":"Accountnumber","currency":"EUR"},"debtorName":"FONS (VUTG) - GROEIPAKKET","debtorAccount":{"iban":"Accountnumber","currency":"EUR"},"remittanceInformationUnstructured":"FONS (VUTG) - GROEIPAKKET Overschrijving TRIERSTRAAT 9 1000 BRUSSEL Accountnumber BIC: BBRUBEBB /C/ GROEIPAKKET - 1.00.318.245 GEZINSBIJSLAGEN 07/2024","bankTransactionCode":"PMNT-RCDT-ESCT","proprietaryBankTransactionCode":"0150000","internalTransactionId":"8e0909d3ef902f82721696f6eea042e0","**payeeName":"name-name S & I (BE47 XXX 5180)","date":"2024-08-07"},**`

screenshot from actual 24.8.0 - same transaction fresh banksync
![image](https://picsur.verhaeghe-steyaert.be/i/34dc88d7-4269-4f17-9383-c98c3d98c963.jpg)

https://discordapp.com/channels/937901803608096828/1270082226750754977

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 11

**Comment by Soulplayer** [comment]
Paypal and revolut work as expected but two of my banks are not: 
KBC - KREDBEBB
VDK - VDSPBE22XXX

**Comment by MMichotte** [comment]
Got the same issue after updating to 24.8.0. 
Payee is now always my own account instead of the actual payee..
Bank: 
CBC - CREGBEBBXXX

**Comment by Soulplayer** [comment]
Not to sound ungrateful because I love actualbudget, but is this being looked at? This is a really annoying bug for me :( .

**Comment by tcrasset** [comment]
The logic for determining the payeeName is now all in this function https://github.com/actualbudget/actual-server/blob/baf04a4d48a6abd667874f14f978abd6e086a41e/src/util/payee-name.js#L7


```js
  if (trans.amount > 0 || Object.is(Number(trans.amount), 0)) {
    name = trans.debtorName;
    account = trans.debtorAccount;
  } else {
    name = trans.creditorName;
    account = trans.creditorAccount;
  }

  // use the correct name field if it was found
  // if not, use whatever we can find
  name =
    name ||
    trans.debtorName ||
    trans.creditorName ||
    trans.remittanceInformationUnstructured ||
    (trans.remittanceInformationUnstructuredArray || []).join(', ') ||
    trans.additionalInformation;
```

As far as I understand it, the only way that the creditorName is chosen even if the amount seems positive, is that the amount (`trans.amount`) is either parsed as a string, or is not parsed correctly and `undefined` is being returned, which leads to the else branch being taken,and `name = trans.creditorName` being used.

**Comment by Soulplayer** [comment]
Is there a way I can help to debug this issue?

**Comment by matt-fidd** [comment]
I think I've found the bug, there's a PR up now in actual-server

**Comment by Soulplayer** [comment]
Can i download a docker build with this fix in it?

**Comment by Teprifer** [comment]
@Soulplayer  There is an edge (and edge-alpine) build created daily, you can grab that. I think there is a migration in it which means you won't be able to go back to a release version until the next release.

**Comment by ArnaudWeyts** [comment]
@Soulplayer, is this working for you again? I've updated to the latest edge version but new transactions still have a payee name that is one of my own accounts instead of the actual payee. Wondering if it's related to my setup 🤔

**Comment by psybers** [comment]
> @Soulplayer, is this working for you again? I've updated to the latest edge version but new transactions still have a payee name that is one of my own accounts instead of the actual payee. Wondering if it's related to my setup 🤔

Check your rules, they might be applying to your transactions and changing the payee.

**Comment by Soulplayer** [comment]
> @Soulplayer, is this working for you again? I've updated to the latest edge version but new transactions still have a payee name that is one of my own accounts instead of the actual payee. Wondering if it's related to my setup 🤔

The issue is fixed for me.

**Comment by Soulplayer** [comment]
I thought it was fixed but I'm wrong. I'm still seeing this issue. I deleted all my rules to make sure it was not related to my setup. But I think it is only with payments now. Deposits seems to be showing the right information.
 
This shows the right name (with the account number from wich the deposit comes, I don't think this used to be shown):
![image](https://picsur.verhaeghe-steyaert.be/i/b65d693d-5c12-4208-9152-a8b1e9525d63.jpg)

Payment shows my account and name:
![image](https://picsur.verhaeghe-steyaert.be/i/86ad12ce-2464-49a9-9ca7-07ed404235e7.jpg)

**Comment by Soulplayer** [comment]
> @Soulplayer, is this working for you again? I've updated to the latest edge version but new transactions still have a payee name that is one of my own accounts instead of the actual payee. Wondering if it's related to my setup 🤔

Do you still have this issue? I'm now only seeing it with KBC (so I made a new issue).

**Comment by ArnaudWeyts** [comment]
@Soulplayer, I'm indeed still seeing this issue. Upvoted your new issue, deposits are fixed but not payments.
