### ISSUE TITLE
[Feature] Additional keyboard shortcuts

### ISSUE THREAD

**Issue by bobokun** [actualbudget/actual#3217]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I've been using Actual Budget for some time now, and as someone who loves using keyboard shortcuts I think adding a couple new shortcuts would help improve the workflow for a lot of users who prefer to use keyboard shortcuts.

1.  Shortcut for View/Posting/Skipping scheduled transactions after highlighting a scheduled transaction
2. Reconciling accounts

These two things I do multiple times weekly as I like to keep my accounts reconciled often.

### Teaching and learning

Adding this to the shortcut help menu will allow users to see new keyboard shortcuts

**Comment by psybers** [comment]
Item 1 is already covered in a PR: #3188

**Comment by bobokun** [comment]
@psybers while this does create a shortcut for view/link schedule it doesn't allow post transaction or skip scheduled date which is what I'm requesting in this FR
