### ISSUE TITLE
Color-only indications

### ISSUE THREAD

**Issue by MikeBishop** [actualbudget/actual#322]
The general accessibility guidance I've been given in the past is never to have something indicated purely by a color difference.  The account list handles this nicely, with a mark next to the selected account as well as a different color on the selected account.  As part of the work on improving reconciliation, I'd like to suggest you use icons for cleared/uncleared which differ by more than green vs. gray.

Any colorblind users this affects or people with more professional background in accessibility might be able to chip in with more concrete suggestions.

**Comment by rich-howell** [comment]
Pr has been created https://github.com/actualbudget/actual/pull/272

**Comment by trevdor** [comment]
Fixed by #272
