### ISSUE TITLE
[Feature] Custom Reports - add option of financial tax year for time period

### ISSUE THREAD

**Issue by themegaphoenix** [actualbudget/actual#3222]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Custom Reports allow you to create reports with the following date ranges:
![image](https://github.com/user-attachments/assets/d749b525-0949-4b9f-8618-acd58b019d29)

It would be useful to add the financial year, as the UK tax year is from 6 April to the following 5 April. This could then be useful to tax reports etc, so allowing to add custom date ranges

### Describe your ideal solution to this problem

Add option for custom date ranges, or add predefined tax year as a setting and be able to use that in the drop down

**Comment by KonigSeppy** [comment]
In Australia the financial year is 1 July to 30 June. It would be great to be able to set the start date of your FY, then dynamically choose This FY, Last FY, etc in reports.
