### ISSUE TITLE
[Feature] Adding attachments to a transactions 

### ISSUE THREAD

**Issue by vinstaal0** [actualbudget/actual#3223]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

There are lot of documents that people need to keep track of that correspond to financial transactions.

For example people need to keep track of certain invoices for tax, insurance or warranty reasons.

Having the ability to add these documents to the transactions makes it easier to keep track of these documents. It can also help you remember what the transaction was if the description isn't clear.
Especially when splitting payments it can be handy to have the document in the same place.

### Describe your ideal solution to this problem

one possible way of achieving this result is to allow the add a link to where the file is stored and embed it when you click on the transaction.

The better solutions would be to make it so you can attach a file to the transactions and when you click on the attach filed it will show the file so you can then see it.

Preferably you would want to see the transaction on one side and the document next to it (or below it)

### Teaching and learning

It should probably be disabled by default since using this will increase the storage space used on the server which might not be something people realise at first.

After it being enabled it could just be a small paperclip or link icon next to the transactions when there is a document attached. Clicking on it will show the document.

The feature should be self explanatory, but writing some quick documentation woudln't hurt it.

**Comment by youngcw** [comment]
duplicate of #530.  Closing
