### ISSUE TITLE
[Feature] Add "Recent Moves" to see recently assigned $

### ISSUE THREAD

**Issue by A1ba70r** [actualbudget/actual#3225]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Between my partner and I budgeting money, sometimes we miss where some of the $ were assigned and would like to know how much money was assigned and to which category and when.

### Describe your ideal solution to this problem

Similar to YNAB, a *Recent Moves* section allows you to keep track of where money has been assigned.

**Comment by youngcw** [comment]
duplicate #3043.  Closing
