### ISSUE TITLE
[Bug]: Rules not being applied on transfer transaction

### ISSUE THREAD

**Issue by bchooxg** [actualbudget/actual#3229]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I have a rule setup to set the Cleared status to true on any amount >0 or <0.

However I've noticed that when creating a transfer transaction, the record on the other end is not being set to cleared status
i.e if i transfer from Acc A -> Acc B 
Acc B's deposit transaction is not cleared and the rules are not being applied on this transaction 

Which leads me to think that rules are not being applied on this other record inserted

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by youngcw** [comment]
I think the issue is that the Acc B side of the transfer isn't a new transaction and therefor doesn't trigger rules to run.  So rules will only be run on the Acc A side since that is the transaction that is actually being added/updated.

**Comment by bchooxg** [comment]
> I think the issue is that the Acc B side of the transfer isn't a new transaction and therefor doesn't trigger rules to run. So rules will only be run on the Acc A side since that is the transaction that is actually being added/updated.

Is there any fix or workaround to get rules to be applied for the other side of the transfer transaction ?
