### ISSUE TITLE
[Bug]: Unable to import from Actual export

### ISSUE THREAD

**Issue by judge** [actualbudget/actual#3233]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I'll try to move away from fly.io because of the unrelability gocardless sync to a self hosted solution. I did a fresh actual install with docker and did an export from fly.io. When I try to import the file into my self hosted version I get an error message.
<img width="1503" alt="Screenshot 2024-08-11 at 09 35 06" src="https://github.com/user-attachments/assets/c484c28f-e124-4c51-8e1b-0992fc388af3">

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Safari

### Operating System

Mac OSX

**Comment by judge** [comment]
Added a screenshot from Google Chrome
<img width="1511" alt="Screenshot 2024-08-11 at 09 39 20" src="https://github.com/user-attachments/assets/0e6ecf75-e3be-4b6c-9ea2-1a1fca00598c">

**Comment by youngcw** [comment]
A migration error is caused by version miss-match. Is your fly instance on a newer version than your new instance?

**Comment by judge** [comment]
Both my fly instance and the newly installed versions are: App: v24.8.0 | Server: v24.8.0

**Comment by MatissJanis** [comment]
In both of the screenshots we can see you're using v24.7.0. So I'm guessing you exported from v24.8.0 and are trying to import into v24.7.0. Sadly that won't work - we don't support back-porting budgets to an earlier version.

If you upgrade back to v24.8.0 - you should be able to import it.

**Comment by judge** [comment]
Yes the screenshot was taken when I tried to roll back to 24.7.0.
I attached a new screenshot.
<img width="1506" alt="Screenshot 2024-08-11 at 20 09 47" src="https://github.com/user-attachments/assets/ca59e387-3ffe-4db0-b131-c52fc80493a3">

**Comment by MatissJanis** [comment]
1. try importing it in https://edge.actualbudget.org and see if that works
2. would you be open to uploading the file here so I could debug?

**Comment by judge** [comment]
On edge, I was able to import successfully. Should I try to upgrade my self hosted to edge?

**Comment by youngcw** [comment]
Upgrade to Edge for now in your local instance. You can move to latest at the next release if you want. Is your fly instance on Edge? That would explain the import issues.

**Comment by judge** [comment]
Upgraded to edge locally, it works! Thanks a lot! Do you need my export for debugging?

**Comment by MatissJanis** [comment]
No, that's fine. We've confirmed now that the issue is not a bug. Actual is not able to migrate budget files down to a previous version (i.e. `edge` export version > v24.8.0).
