### ISSUE TITLE
[Bug]: Unsupported browser (Mull for Android)

### ISSUE THREAD

**Issue by BlizzBlu** [actualbudget/actual#3243]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I recently switched my mobile browser from Firefox to Mull (which is a Firefox fork). I can open my self-hosted instance through Firefox just fine, but Mull fails with a "Fatal Error". Trying to "Show Error" gives me a blank box, so that's unfortunately all I know.

To reproduce:
- Download Mull from F-Droid
- Go to any self-hosted instance

If it's of any help, I also use LibreWolf on desktop (another Firefox fork), where I can use Actual without any problems.

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Firefox, Other

### Operating System

Mobile Device

**Comment by youngcw** [comment]
Is JS enabled for the site?

**Comment by youngcw** [comment]
I would recommend asking on discord if anyone knows what to do.  My guess is that its a security setting in the browser.  

Ill close this for now.  Feel free to open it again if people on discord find a bug that can be fixed.

**Comment by M1scer** [comment]
Sorry if I am bringing this issue back to life. I have exactly the same problem, with the same browser. 

Have you managed to solve the problem or was a different browser needed?

**Comment by tclbe** [comment]
In about:config, change javascript.options.wasm to true.
