### ISSUE TITLE
[Bug]: Selected transactions count not rendered properly

### ISSUE THREAD

**Issue by joel-jeremy** [actualbudget/actual#3247]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Selected transactions count is not rendered correctly:

![image](https://github.com/user-attachments/assets/f75c8262-f991-4f52-9fe9-6e7d6ba71504)

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome, Other

### Operating System

Windows 11

**Comment by youngcw** [comment]
I think this is the same as #3240.

**Comment by joel-jeremy** [comment]
Oops, missed that. Closing this ticket then.
