### ISSUE TITLE
[Feature] Exclude accounts from net worth

### ISSUE THREAD

**Issue by leon-wbr** [actualbudget/actual#3254]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I'd like to be able to exclude certain accounts from my net worth, which I'd consider "virtual" or "external accounts."

One of these for example is debt that is owed to me, but I'm not sure when or if it will be paid back. I don't have this money and I don't want to plan with it. Another one is projects that I manage with their own money, but that aren't large enough to warrant their own budgeting. All I do is keep track of the remaining money and transactions, separate from my own, but most of which are done from my personal account. It's easy to transfer the money in Actual but have an overview of "what's mine and what's not."

So I use Actual Budget for these use cases, but it's becoming cumbersome to always manually subtract numbers from my total account balance or net worth. I'd prefer to be able to exclude these accounts as a setting.

Off-budget is simply not enough, because my savings account is definitely part of my net worth, same for the debt that I owe.

### Describe your ideal solution to this problem

I believe the easiest solution would be to just add a setting on each account whether or not it should be included in the total account balance (which to me is synonymous to net worth). It'd be good to also separate them in the sidebar into a new category, such as "Other," "Additional" or "Excluded from net worth."

**Comment by youngcw** [comment]
For the time being you can make filters that include/exclude certain accounts, then use those filters inside the net worth report.  The filters need to be applied every time, but its something.

**Comment by youngcw** [comment]
This is now doable with saved filters using the reports dashboard feature to save reports.
