### ISSUE TITLE
[Feature] Support for 3 decimal currencies.

### ISSUE THREAD

**Issue by NNNSSS3** [actualbudget/actual#3255]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I use a 3 decimal currency and as such can't accurately budget using Actual Budget.

### Describe your ideal solution to this problem

Added support for 3 decimal currencies which are Bahrain, Iraq, Jordan, Kuwait, Libya, Oman and Tunisia..

**Comment by XahidEx** [comment]
I think many of us need this.
