### ISSUE TITLE
[Feature] Allow configuration of User ID and Group ID used to run service in Docker

### ISSUE THREAD

**Issue by RyanMelena** [actualbudget/actual#3256]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Would like to be able to configure the user and group Actual runs under within Docker for improved security and volume mount file permissions.

### Describe your ideal solution to this problem

Support PUID and PGID arguments from Docker as standardized by linuxserver.io: https://docs.linuxserver.io/general/understanding-puid-and-pgid/

### Teaching and learning

Update `Configuring the Server` documentation ( https://actualbudget.org/docs/config/ ) with new PUID and PGID environment variables.

**Comment by RyanMelena** [comment]
Example implementation here: https://github.com/RyanMelena/actual-server-custom

**Comment by m3Lith** [comment]
You can kind of achieve that by passing `--user PUID:PGID`, or by using the `user` directive inside compose file. Just would need to create the root config dir manually first (or `chown` and restart container).

**Comment by dasunsrule32** [comment]
This should definitely happen. If you create new files, even with `PUID` and `PGID` defined, the new files will be owned by `root` and the new files have to be `chown`'d. Not ideal.
