### ISSUE TITLE
Keyboard Shortcuts don't work

### ISSUE THREAD

**Issue by kazzazed** [actualbudget/actual#326]
As described at https://actualbudget.com/docs/overview/tips-&-tricks/ Keyboard Shortcuts
In the App, in Account and select Ctrl-1 - expect it to show the budget. Actual result: nothing happens.

**Comment by MatissJanis** [comment]
:wave: keyboard shortcuts such as `cmd`+`1` work only in the electron (desktop app) version. They are not enabled for the WEB version.

Given we currently do not publish desktop version releases - I'll close this off.

We will still need to address it once we start publishing desktop versions. But lets cross that bridge when we get there.. :)
