### ISSUE TITLE
[Bug]: Persistent floating "Distribute / Add Split" on desktop browser 

### ISSUE THREAD

**Issue by b-neufeld** [actualbudget/actual#3261]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

When splitting transactions, I see a persistent floating "Distribute / Add Split" pop-up: 

![image](https://github.com/user-attachments/assets/e868cae3-6824-4238-a2e1-86d519018f1b)

After splitting a transaction in Chrome browser, this little window would not close. 

After splitting a few more transactions, I had three floating split pop-ups. 

After signing in to Edge browser, all of my split transactions had these little floating pop-ups. 

Not an issue on mobile. 

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Operating System

Windows 11

**Comment by youngcw** [comment]
you must have budgeted a few cents extra.  Turn on decimal amounts to see what the amount is off by

**Comment by b-neufeld** [comment]
Thanks, that's the issue. 

Will let someone else decide if this issue should be closed... an improvement would be doing the distributions automatically if decimal places are hidden.
