### ISSUE TITLE
[Feature] Reapply selected/all rules to existing transactions

### ISSUE THREAD

**Issue by TDurrr1** [actualbudget/actual#3269]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I recently created a few dozen rules via the API. However, now that the rules have been created, there doesn't seem to be an easy way to apply those rules to existing transactions. Through the UI, it looks like I would need to click to edit each rule, select all transactions, and click "Apply actions". I can't see a way to do it via the API.

### Describe your ideal solution to this problem

Two thoughts:

- In the API, add a boolean parameter to `createRule` and/or `updateRule` (maybe this should be an array for feature parity with the UI?)
- In the UI, after selecting one or more rules from the list of rules, provide a button to apply the rule(s) to existing transactions.

### Teaching and learning

There is a dropdown on the Payees page:
![image](https://github.com/user-attachments/assets/78e16c69-aa65-4165-8ac4-43a67c57b6d3)

I imagine this should go in the analogous place on the Rules page (and the button to delete rules should go in there as well).

**Comment by olets** [comment]
This might be met by 25.3.0's https://github.com/actualbudget/actual/pull/3805, which as I understand it lets you select transactions (not rules, as the OP described) and —then from the "n transaction(s)" menu— run all rules which it matches. Doesn't make it easy to selectively run newly created rules, but does provide a three-clicks path to rerunning all rules ("all accounts" -> select-all checkbox -> "n transaction(s)" -> "run rules").
