### ISSUE TITLE
[Feature] Export report data as csv

### ISSUE THREAD

**Issue by EconomistMike** [actualbudget/actual#3272]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

In YNAB users are able to export the data in the reports as csv. This feature doesn't seem to be available in ActualBudget.  

I'd like to be able to, for instance, create a monthly Income v Expense report in the app and download the data as a csv for further analysis. 

### Describe your ideal solution to this problem

Ideally users can simply export the underlying data shown in the reports. But failing that at least being able to download monthly income v expense data with the groups and categories would be fabulous. 

<img width="1155" alt="image" src="https://github.com/user-attachments/assets/81af9d4f-8661-4129-b724-7d7e3001ed9e">

**Comment by NumbersLady** [comment]
Would like to move off YNAB 4 to Actual Budget, but this feature is a must for me. Exporting an annual budget spending by category summary to a CVS (then Excel) is critical to budgeting for the new year. Also need listing detail for contributions for tax purposes.

**Comment by tekumara** [comment]
Same request as #2477

**Comment by youngcw** [comment]
Closing as duplicate is #2477
