### ISSUE TITLE
Split transaction can't change to a normal single category transaction.

### ISSUE THREAD

**Issue by bpaulien** [actualbudget/actual#328]
I set up a transaction as a split between 2 categories.  Then I realized I wanted to categorize it as one of my Income categories, and then budget it into those other 2 categories.  But I can't find a way to remove the split.  I can change one of the split categories to the Income one, but I can't delete the other category, or change it from "split" type of transaction.  

If I change the first split category to the income category that I want, and change the Deposit amount to the full amount received, and remove the 2nd category and zero out its Deposit amount, It does show up as income, but the transaction still displays as a split, and now has an empty category.

**Comment by MatissJanis** [comment]
👋 Two things discussed here:

1. ability to un-split a transaction - this can be achieved by deleting all the sub transactions by either using "d" keyboard shortcut or by clicking on the "x" besides the sub-transactions;
2. transactions "disappearing" - if this happens again the latest version - please let us know with more information (repo steps) so we could investigate; but until then I'll consider this as done.
