### ISSUE TITLE
Handling Investments

### ISSUE THREAD

**Issue by nikohd12** [actualbudget/actual#329]
I don't know if this feature is meant to be but when transferring funds from Checking/Cash/Savings to an Off-Tracking Account such as 401k, BTC/ETH, IRA or other investments, the mobile application (iOS) will not allow me to categorize the transaction.

So what I usually do as a workaround is:
1. Set the Category to a retirement category first - "Retirement Fund"
2. Set the Payee to "Transfer: 401k"
3. Add Transaction

On Desktop (Windows), I was able to categorize this.

**Comment by rich-howell** [comment]
Hey @nikohd12 

The iOS application is no longer supported, we are working on a responsive version of the actual web application which should be available in the open source version soon.

Cheers
Rich
