### ISSUE TITLE
[Feature] Themes

### ISSUE THREAD

**Issue by maralihart** [actualbudget/actual#3291]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Interested in switching from YNAB to Actual and looked up threads to compare. This comment talks about how the only thing missing is the YNAB color scheme. 

https://www.reddit.com/r/ynab/s/Gp6p9L7He6

Users below agree.

**Comment by MatissJanis** [comment]
Important note: Actual is not YNAB. We do not claim the be YNAB and we do not intend to become a clone of YNAB.

That being said - if there was a "theme marketplace" that allowed the community members to create their own themes and share them - we could not stop people from making Actual _look_ like YNAB.

**Comment by radh21301** [comment]
I was looking for this exact feature. Not really looking for a ynab inspired style - just something that is not too purple :)
