### ISSUE TITLE
[Bug]: this budget cannot be loaded with this version of the app.  make sure the app is up to date

### ISSUE THREAD

**Issue by drtyjrsy** [actualbudget/actual#3293]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I use pikapods.  both the server and client (desktop and phone) v24.8.0.  when I go to the server address on phones browser, I get this warning when I click on my budget file.  this budget cannot be loaded with this version of the app.  make sure the app is up to date.  Ive seen this related to a docker image but im not sure what that is 
![2024-08-19 19 33 02](https://github.com/user-attachments/assets/a9250a62-0d27-4fb1-b50e-212b7f1ca711)

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Safari

### Operating System

Mac OSX

**Comment by youngcw** [comment]
it means that your file has been opened in a higher version of the app than what your current client is.  Either a newer full version or an edge version of the app.

**Comment by drtyjrsy** [comment]
Do you have any info on how to resolve this?

Best,

Mike Sheurs

**Comment by youngcw** [comment]
You need to either load up a backup that was not used in a new version or use a newer version of the client.  If you don't have a backup, your best bet is probably to use edge.actualbudget.org as your front end and point that to your pikapods server until the next release.

**Comment by youngcw** [comment]
I don't know but that error is what happens when the file has newer settings than the client can use.  Either than or the file got some sort of corruption that is causing trouble.
