### ISSUE TITLE
[Bug] Wrong payeeNamee

### ISSUE THREAD

**Issue by Soulplayer** [actualbudget/actual#3303]
I thought this issue was fixed, but I'm wrong. I'm still seeing this issue. I deleted all my rules to make sure it was not related to my setup. But I think it is only with payments now. Deposits seem to be showing the right information.
 
This shows the correct name (with the account number from which the deposit comes, I don't think this used to be shown):
![image](https://picsur.verhaeghe-steyaert.be/i/b65d693d-5c12-4208-9152-a8b1e9525d63.jpg)

Payment shows my account and name:
![image](https://picsur.verhaeghe-steyaert.be/i/86ad12ce-2464-49a9-9ca7-07ed404235e7.jpg)

I did not know to reopen the issue or post a new one, so I used the 'reference in a new issue' button. If this is the wrong way, please delete this post and I'll open a new issue. 

_Originally posted by @Soulplayer in https://github.com/actualbudget/actual/issues/3216#issuecomment-2299358407_

**Comment by Soulplayer** [comment]
So this now only happens when I make a payment and not a deposit. Specifically, with one bank:
KBC - KREDBEBB
![image](https://picsur.verhaeghe-steyaert.be/i/0d6a592e-d9b2-444c-af3a-e3fa521b5fe4.jpg)

Deposits are shown correctly.

**Comment by matt-fidd** [comment]
Hi @Soulplayer - please could you provide the JSON object for the transaction that's giving wrong information?

**Comment by Soulplayer** [comment]
@matt-fidd is it this information you mean:
`'[{"transactionId":"2024-08-28-09.10.56.275689","bookingDate":"2024-08-28","valueDate":"2024-08-28","transactionAmount":{"amount":"-37.77","currency":"EUR"},"debtorName":"ver-stey S & I","debtorAccount":{"iban":"BE47736002475180","currency":"EUR"},"remittanceInformationUnstructured":"Proxy Poel BE Gent Betaling met Apple Pay via Maestro 23-08-2024 om 14.03 uur 6703 42XX XXXX X401 3 6790 28XX XXXX X901 4 ver san","bankTransactionCode":"PMNT-CCRD-POSD","proprietaryBankTransactionCode":"0402000","internalTransactionId":"4cc0a7d5124bd51ef967f98498f63a94","payeeName":"ver-stey S & I (BE47 XXX 5180)","date":"2024-08-28","booked":true},{"`

The unstructured information contains the information that should be the payee (Proxy Poel BE)

**Comment by matt-fidd** [comment]
GCL would normally return a creditor name with a negative amount but as it's not populated, we now fall back to the debtor name (in some of the integrations I was able to test, GCL just returned the wrong one).

The best way to resolve this would be a bank specific handler in actual-server, a similar change to the one just merged in actualbudget/actual-server#428

If you're confident implementing this, feel free to submit a pull request. If not then I'd be happy to help you, or submit the change myself - whichever you'd prefer.

**Comment by Soulplayer** [comment]
I’m not confident in programming this. This is an expertise that I don’t have. I would be grateful if this could be implemented.

**Comment by ArnaudWeyts** [comment]
@matt-fidd I'll take a look at creating a pull request!

**Comment by MMichotte** [comment]
Hi @ArnaudWeyts, 
Could check this out sooner as I was on vacation but I just updated to 24.9.0 and still got the issue. 
I quickly went through your PR and it looks like you had to add an exception for KBC. 

Since I have the same issue but with CBC (CBC - CREGBEBBXXX) I'll have to check to provide the same fix. 

Correct-me if am wrong ;)

**Comment by ArnaudWeyts** [comment]
Hi @MMichotte That's possible, I also had to add some specific string matching (e.g. "Betaling met") so that the Payee name isn't the full long string with the entire transaction info. But technically that should only work for dutch KBC accounts. I'm not sure if it's possible to use the same bank exception for multiple banks 🤔 I think @Soulplayer Also requires the a similar fix for VDK bank

Example transaction for VDK:

```
{"transactionId":"24630434001","bookingDate":"2024-09-02","valueDate":"2024-09-02","transactionAmount":{"amount":"-250.20","currency":"EUR"},"creditorName":"NV vdk bank","debtorName":"VerS. - Stet I.","debtorAccount":{"iban":"BE4xxxxxxxxxxx45"},"remittanceInformationUnstructured":"7763 CO&GO GENT 9000 GENT BE%nl%Shopping op 02/09/24 17:48%nl%Kaart 893-9855859-45-0117","internalTransactionId":"8a12ffa2f1252c97a7f17c5148d6e819","payeeName":"Nv Vdk Bank","date":"2024-09-02","booked":true}
```

**Comment by MMichotte** [comment]
@ArnaudWeyts, indeed, I added the same logic as yours but with the appropriate matching strings. (see: [actualbudget/actual-server#451](https://github.com/actualbudget/actual-server/pull/451)
Maybe in the future a more generic way of dealing with this could be implemented.

**Comment by MMichotte** [comment]
@Soulplayer , I can have a look at it. 
I'll at the same time look to generalize it as much as possible to support other banks with different patterns. (or provide some kind of helper function)

Do you have any JSON extracts for VDK I can base myself off ? Try to have a few different scenarios if possible. (Transfers, Standing orders, ...)

**Comment by MMichotte** [comment]
@Soulplayer, @ArnaudWeyts,
I updated my PR ([actualbudget/actual-server#451](https://github.com/actualbudget/actual-server/pull/451)) by adding a helper function in order to prevent code-duplication and to be able to more easily add new banks with the same issue ;) 

Waiting for it to be approved. 
I'll gladly add `VDK` once I get the necessary info.

**Comment by Soulplayer** [comment]
Hello,

So with VDK most work but some do not. **This one does not work** and gives Nv Vdk Bank as payee. 

"transactionId":"25130432342","bookingDate":"2024-09-07","valueDate":"2024-09-07","transactionAmount":{"amount":"-140.97","currency":"EUR"},"creditorName":"NV vdk bank","debtorName":"verS. - steI.","debtorAccount":{"iban":"BE4xxxxxxx85945"},"remittanceInformationUnstructured":"C&A Online 40468 Dusseldorf DE%nl%Shopping op 07/09/24 15:13%nl%Kaart 893-xxxxx-xx-0117%nl%Ref 6MGMWAX 576891130 C A Online S","internalTransactionId":"c7b04b63d2bf9333c8a3500cbc9d12b7","payeeName":"Nv Vdk Bank","date":"2024-09-07","booked":true},

I have a feeling that if I pay by card it gives me the Nv VdK Bank but if I pay from account to account then it uses the right information. This is an automatic payment and this **works**.

{"transactionId":"25396805518","bookingDate":"2024-09-09","valueDate":"2024-09-09","transactionAmount":{"amount":"-16.87","currency":"EUR"},"creditorName":"HELAN ONAFHANKELIJK ZIEKEN","debtorName":"verS. - steI.","debtorAccount":{"iban":"BE4xxxxxxx85945"},"remittanceInformationUnstructured":"DENTALIA 0819007918196","internalTransactionId":"ca4fb30d57600d7457a990c3c8a6dafe","payeeName":"Helan Onafhankelijk Zieken","date":"2024-09-09","booked":true},

This is a manual payment using the app and this **works**;
"transactionId":"25230510461","bookingDate":"2024-09-08","valueDate":"2024-09-08","transactionAmount":{"amount":"-48.00","currency":"EUR"},"creditorName":"verP. - Rommelaere","creditorAccount":{"iban":"BE4xxxxxxx7445"},"debtorName":"verS. - steI.","debtorAccount":{"iban":"BE4xxxxxxx85945"},"internalTransactionId":"91e1e061af9fa467f4ae423fb7cc34a1","payeeName":"verP. - rom(BE44 XXX 7445)","date":"2024-09-08","booked":true},

I removed some information.

**Comment by MMichotte** [comment]
Mmmm this doesn't really seem to be the same issue as for KBC and CBC. I can nevertheless have a look at it. Hopefully this weekend!

**Comment by Soulplayer** [comment]
@MMichotte did you find the time to take a look at it?

**Comment by MMichotte** [comment]
I did not have the time previous weekend nor will I be able to the two following weekends... 
I'll keep you posted !
