### ISSUE TITLE
[Bug]: Adding Easybank / Austria doesn't work

### ISSUE THREAD

**Issue by clutwo** [actualbudget/actual#3307]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Adding Easybank / Austria through gocardless produces an error.

It seems the "/gocardless/create-web-token" fails with a 500 error. it simply responds:

`{"status":"error","reason":"internal-error"}`

The request body is:

`{"institutionId":"EASYBANK_BAWAATWW","accessValidForDays":90}`

In the backend, the whole thing fails with a ERR_BAD_REQUEST (and some very long logs).

I doubt this is on gocardless, because I can add my other Bank Account from a different bank (DKB / de) no problem. I also tried adding Easybank in the gocardless web ui for test data and it worked straight away.

Installation method is Docker with "latest" tag (also tried it on "edge").

Steps to reproduce:

1. Try to add Bank Account for Austria - Easybank. It fails with the following message:

![image](https://github.com/user-attachments/assets/b4708bcc-565a-4e95-b336-e39fbbefd495)

Find the relevant server log attached. 

[actual.txt](https://github.com/user-attachments/files/16731768/actual.txt)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome, Desktop App (Electron)

### Operating System

Linux

**Comment by MatissJanis** [comment]
<img width="1372" alt="Screenshot 2024-08-24 at 12 50 40" src="https://github.com/user-attachments/assets/0be0d026-b55a-4058-892f-bcc367aaf92a">

**Comment by clutwo** [comment]
I did reach out and waited 2 days. Noone is answering.
