### ISSUE TITLE
Pressing tab doesn't select or create Payee in schedules

### ISSUE THREAD

**Issue by lillianhorin** [actualbudget/actual#331]
So excited about Actual. Just have found a recurring bug that makes scheduling transactions a bit of a pain.

As of now, I can't just type the payee (or create a new one), hit tab, and have that payee updated. I have to specifically click on the payee. Here is an example via creating a new payee, but this is also the case for existing payees.

First, I type in the payee I want. Right now, this is prompting me to create a new payee.
![image](https://user-images.githubusercontent.com/24489520/143927966-b1247936-08d6-41cc-a6cf-07eb5bc97936.png)

Then I hit tab. Intuitively, hitting tab is to select that option and then go to the next row. But as you can see, not only is no payee entered, but the payee actually is not created. Like I said, existing payees don't get selected either.
![image](https://user-images.githubusercontent.com/24489520/143928040-a47f82ed-5805-40e8-8383-2cebf93563d0.png)

I can only move forward if I click the payee I want (or click "make new").
![image](https://user-images.githubusercontent.com/24489520/143928216-e291cd5f-a815-4b96-b191-a2abd77dd924.png)

Thanks so much!

**Comment by MatissJanis** [comment]
👋 We should be able to address this with the new autocomplete component. See more info here for the full release of it: https://github.com/actualbudget/actual/issues/773
