### ISSUE TITLE
[Feature] Allow the creation of Categories when in the ledger

### ISSUE THREAD

**Issue by SeventhUnderhand** [actualbudget/actual#3315]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I am going through and importing all my data for the year after switching from a different program. I am having to go back and forth between my accounts and the budget tab to create categories. 

Having a way to just add a category just like adding Payees would make this way easier

**Comment by savionlee** [comment]
This would be very nice
