### ISSUE TITLE
[Bug]: deleted payees still show in suggested list

### ISSUE THREAD

**Issue by psybers** [actualbudget/actual#3317]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

If you have a commonly occurring payee and then you delete it, it will still show in the list of suggested payees.

For example here, I actually deleted "Kroger" from my payees list (all transactions now show blank payee):

<img width="370" alt="image" src="https://github.com/user-attachments/assets/b73f3400-3e69-4db2-8afd-77f23d52d9b5">

<img width="272" alt="image" src="https://github.com/user-attachments/assets/9c510ec6-c533-4c85-881e-4790308be8c6">

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by psybers** [comment]
Probably the query needs to filter with `p.tombstone = 0`, but in my test it looks like there is a caching issue with that in place and it will not work until you refresh the page.

**Comment by qedi-r** [comment]
Yeah. We'd need some way to control the cache on the accounts page. It looks like both just the normal payee list and the common payee list cache the result until the page is reloaded.
