### ISSUE TITLE
Lag when creating scheduled transactions -> creates duplicates

### ISSUE THREAD

**Issue by lillianhorin** [actualbudget/actual#332]
When I create a new scheduled transaction, there's a pretty significant ~5 second delay from when I hit the create button to when it is processed. Sometimes I'm not sure whether it even went through so I click it again. This leads to two of the same scheduled transaction being created.

Increasing the speed and/or preventing the creation of duplicate transactions because of the lag would be great!

**Comment by Kidglove57** [comment]
For me (in the open source version) the new schedule seems to enter pretty much instantly.

**Comment by rich-howell** [comment]
Hey @lillianhorin 

I have been unable to replicate this, if you are still having issue with this on the Open Source version, please let me know and I will re-open this issue for you.

Cheers
Rich
