### ISSUE TITLE
Split income transaction  is not included in the total for the Income (month year) page

### ISSUE THREAD

**Issue by Clarke44** [actualbudget/actual#333]
Basically, I have entered income for November, some of this I have split off into a specific category, some is just income. 

The correct income amount is reported at the bottom of the budget page for November, but if you click on this number, the income page you are taken to reports the incorrect number in the top left corner. It looks like it doesn't include any of the transaction that was split.

**Comment by MatissJanis** [comment]
👋 I think this is fixed in one of the latest versions. But if you still experience this issue after upgrading: please open a new issue and provide an example budget export and reproduction steps.

Thanks!
