### ISSUE TITLE
[Bug]: Reconciliation box closing immediately when using return key to open

### ISSUE THREAD

**Issue by matt-fidd** [actualbudget/actual#3330]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

To reproduce:
1. Open an account
2. Open initial reconcile amount input
3. Enter amount different to account balance
4. Press enter/return
5. Main reconciliation box opens then immediately shuts

Does not happen when reconcile button clicked with mouse

https://github.com/user-attachments/assets/17377407-f382-4879-851b-607906ca9661

Possibly related to #2974 

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by matt-fidd** [comment]
Confirmed caused by #2974

**Comment by psybers** [comment]
Interesting. Probably the key down event triggers the primary button of that dialog, and then the key up event immediately triggers the primary of the next dialog.

**Comment by psybers** [comment]
@MatissJanis to be clear, #3338 fixes the bug by reverting the prior change. Thus, the functionality is sub-optimal still just in a different way.

**Comment by MatissJanis** [comment]
What’s the sub-optimality? I couldn’t spot any issues when spot checking.

**Comment by psybers** [comment]
> What’s the sub-optimality? I couldn’t spot any issues when spot checking.

@MatissJanis Press enter twice to reconcile. The second one fails and opens the menu:
![bug](https://github.com/user-attachments/assets/85c34cbc-2d8f-4c0d-8105-60fd3a6711ad)
