### ISSUE TITLE
[Bug]: Payees should sort favorite payees before other suggested payees.

### ISSUE THREAD

**Issue by qedi-r** [actualbudget/actual#3331]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Right now, payees are sorted in three groups, suggested payees, payees and transfers. All are sorted alphabetically. Suggested payees draws from two different sources though, users can either mark payees as favorites, or the most frequently used payees in the past 12 weeks, if users haven't marked at least five payees as favorites. 

Since users have specifically marked favorites as desired payees, they should be shown in the suggested payees first. Then common payees should be added. Both subsections should remain otherwise unmarked and be sorted alphabetically.

### Where are you hosting Actual?

Docker

### Operating System

Windows 11

**Comment by youngcw** [comment]
Didn't this get fixed?

**Comment by qedi-r** [comment]
No, I spent too much time figuring out the component test framework. I've created a PR for it now.

**Comment by youngcw** [comment]
If there is an open PR then you should like it to this issue by adding "fixed #<this issue>" to the description
