### ISSUE TITLE
[Bug]: Actuall install fails on Ubuntu 22.04 and Debian 12

### ISSUE THREAD

**Issue by cwross** [actualbudget/actual#3335]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I have tried installing Actual following the instructions here: https://actualbudget.org/docs/install/local

On both Debian 12 and Ubuntu 22.04, I have tried using Node 18, 20, and 22. All versions fail similarly.

Error is below.

`➤ YN0002: │ actual-sync@workspace:. doesn't provide @babel/core (p89c81), requested by @babel/preset-typescript.`
`➤ YN0086: │ Some peer dependencies are incorrectly met by your project; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.`
`➤ YN0086: │ Some peer dependencies are incorrectly met by dependencies; run yarn explain peer-requirements for details.`

Forgive me if I am missing something obvious; I don't know much about Node at all; just an old Unix admin trying to follow the instructions provided.

### Where are you hosting Actual?

Locally via Yarn

### Operating System

Linux

**Comment by tcrasset** [comment]
Are you sure this isn't just a warning? I get these warnings too during `yarn install`, but `yarn start` is able to start the app no problem

**Comment by cwross** [comment]
Yes, when I run `yarn start`, I get the following error:

`Usage Error: Couldn't find the node_modules state file - running an install might help (findPackageLocation)`

I should also clarify that the Debian and Ubuntu systems I tried this on were both fresh installs created specifically for this purpose.

**Comment by youngcw** [comment]
how are you installing the dependencies?  Im on mint and haven't ever had install issues.  Im currently using node18

**Comment by a7son** [comment]
i had same problem on my UBUNTU, i use node 18 and node 22 have same problem
when i use yarn install it said this error
