### ISSUE TITLE
[Bug]: Import fails claiming "Something internally went wrong."

### ISSUE THREAD

**Issue by prashmohan** [actualbudget/actual#3345]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

When try to import a CSV file with transactions from my account, it shows me a red butter bar at the bottom claiming "Something internally went wrong. You may want to restart the app if anything looks wrong. Please report this as a new issue on Github.". I have tried refreshing the browser page, as well as restarting the docker app. I am not sure how I can get it to provide any additional logs that indicate what the issue is. FWIW I finished importing the details for 2 other accounts, and they seem to work fine.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Mac OSX

**Comment by MatissJanis** [comment]
👋 Could you please share an example CSV file that is failing import? Without getting the file there is very little we could do to help here.

**Comment by prashmohan** [comment]
Attaching a sample CSV that causes this error. Note that this error only shows up when trying to import the CSV into this particular account. I previously setup 2 other accounts, if I try to import it to either of them they seem to parse fine.
![error_screen](https://github.com/user-attachments/assets/25db63b8-8bdd-4a62-9fba-09ecc7ba1886)
[test.csv](https://github.com/user-attachments/files/16841391/test.csv)

**Comment by prashmohan** [comment]
I added a "Payee" field with empty values in the CSV. This seemed to make the import tool happy for some reason. I still dont know why it was fine with the original format in the other accounts - the only thing I can think of is that this account is largely unpopulated (apart from linked transactions in the other accounts) and there is something special in the first import.

**Comment by MatissJanis** [comment]
What steps should I take to reproduce this on https://edge.actualbudget.org?

I tried creating a new account and import the file above. That worked OK.
