### ISSUE TITLE
[Bug]: Report Budget "Saved" amount after month end makes no sense

### ISSUE THREAD

**Issue by sabellwind** [actualbudget/actual#3346]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I use the report budget as it helps me forecast my spending power over a period of time and helps me plan for future goals. As I like to roll-over some category's spending/saving, I am noticing that it comes up with a pretty non-sensical dollar value after the month ends. I aim to keep my "Projected Savings" value at $0 throughout the month as this tells me I have allocated my funds perfectly across my spending, goals and savings categories.

**Expected behaviour:** 
Projected Savings value is always shown and not replaced by the "Saved" value.

**Actual behaviour:** 
As attached below, I have to mouse over to see the "Projected Savings" value and this is not even available on mobile
![image](https://github.com/user-attachments/assets/5715aee5-cffa-4f32-9bc3-9698d53282aa)

If I could continue to see the "Projected Savings" value, I can keep track to whether my month's actual spendings stayed within the boundaries of my budget, and if not, make adjustments to the budgeted amounts to square off the month.

Please let me know if there's a better way to handle this as my interpretation of the report budget may be different to yours.

Cheers.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome, Other

### Operating System

Windows 10

**Comment by MatissJanis** [comment]
👋 Thanks for the feedback. Moving it to the general feedback tracker here: https://github.com/actualbudget/actual/issues/2999

**Comment by sabellwind** [comment]
> 👋 Thanks for the feedback. Moving it to the general feedback tracker here: #2999

Thanks for that. Happy to partake in any testing or provide anymore information if you need. Appreciate all you do for the project!
