### ISSUE TITLE
[Bug]: Some filter types return no results

### ISSUE THREAD

**Issue by oddstr13** [actualbudget/actual#3347]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Running `edge` (due to CSV import not working in `latest`), I pulled and re-tested just now, so should be the most recent nightly build.

Create rule from transaction does not actually create a rule that matches the selected transaction.
At least the `is` and `matches` filters don't behave as expected.

`matches` with `.*` on `imported payee` pulls up transactions, but `.*Store.*` does not.
The `is` filter does not match the exact payee string populated by the «create rule» button, but `contains` does match it.

![image](https://github.com/user-attachments/assets/0803d139-06fd-488a-8001-ad10519ad401)
![image](https://github.com/user-attachments/assets/4d61d21b-eebf-4433-aacf-f6c56c30266b)
![image](https://github.com/user-attachments/assets/d47324cb-a172-4147-b177-e6bc70f968ca)
![image](https://github.com/user-attachments/assets/f35ad12c-3755-48e5-beb7-11062776008d)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

**Comment by bvanelli** [comment]
Have been having weird issues too (version 24.9.0):

The following matches:

<img width="600" alt="image" src="https://github.com/user-attachments/assets/ba5e9c22-f839-4c34-83e8-4f8837bb934d">

But one more character and it does not work:

<img width="600" alt="image" src="https://github.com/user-attachments/assets/9e512ed7-18d5-4c19-aae6-5832533cb7dc">

Perhaps related to https://github.com/actualbudget/actual/issues/3392

**Comment by oddstr13** [comment]
Yes, #3392 looks like the exact same issue, except I was seeing it with more than only regex queries

**Comment by juanrapmc** [comment]
I think it's not just because of case-sensitivity

## Example that gets matches -- removed the first letter of the payee
![Screenshot 2024-09-15 103230](https://github.com/user-attachments/assets/e0f7ff79-fc18-41fa-ac5d-4c04185bc7dd)
## Example that uses all small
![Screenshot 2024-09-15 103217](https://github.com/user-attachments/assets/a557d8ea-5ca4-484a-a26d-22582a56610b)
## Example that matches casing
![Screenshot 2024-09-15 103205](https://github.com/user-attachments/assets/8a0c3113-b5ea-4276-889b-746f3ef655bd)

**Comment by jfdoming** [comment]
> I think it's not just because of case-sensitivity
> 
> ## Example that gets matches -- removed the first letter of the payee
> ![Screenshot 2024-09-15 103230](https://private-user-images.githubusercontent.com/53954739/367572221-e0f7ff79-fc18-41fa-ac5d-4c04185bc7dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MTMyNTUsIm5iZiI6MTcyNjQxMjk1NSwicGF0aCI6Ii81Mzk1NDczOS8zNjc1NzIyMjEtZTBmN2ZmNzktZmMxOC00MWZhLWFjNWQtNGMwNDE4NWJjN2RkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDE1MDkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0ZmVmMzMwY2FmMTEyNjY0NGY4ZjcxYTNiMDhhYWFjNzcyZGFhYTlmOTA2MjJiZGUxN2I2NjQ0MjA0NjMyNmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ess-FiAxAV-WjkQTgdwaVlwONxFUrF-4o06WWKL_z0M)
> 
> ## Example that uses all small
> ![Screenshot 2024-09-15 103217](https://private-user-images.githubusercontent.com/53954739/367572222-a557d8ea-5ca4-484a-a26d-22582a56610b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MTMyNTUsIm5iZiI6MTcyNjQxMjk1NSwicGF0aCI6Ii81Mzk1NDczOS8zNjc1NzIyMjItYTU1N2Q4ZWEtNWNhNC00ODRhLWEyNmQtMjI1ODJhNTY2MTBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDE1MDkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAxN2ZiZmQ0YTUxZjA4YWIxMzc2OTU5NmFkNGExZThhNmYxYzg2MWM5YmRmNDRjZDk3OTg0YzJlMDNhNGNlOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rrVacdbM-hS4w56xw2IZrFsAkGzuc5qmovu2_CHrH3Q)
> 
> ## Example that matches casing
> ![Screenshot 2024-09-15 103205](https://private-user-images.githubusercontent.com/53954739/367572224-8a0c3113-b5ea-4276-889b-746f3ef655bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MTMyNTUsIm5iZiI6MTcyNjQxMjk1NSwicGF0aCI6Ii81Mzk1NDczOS8zNjc1NzIyMjQtOGEwYzMxMTMtYjVlYS00Mjc2LTg4OWItNzQ2ZjNlZjY1NWJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDE1MDkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkNzBkZjUwOWVhNWQ1NTlhODY0YTVjMTZiMmMzNjg1MjAxMDk1NDZkOGQ3Yzc2NGQwNWQ2YjRjNWQwYTllMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jOISkmUtKbsLGtZU6QYBdJwegwHUE6FVGkA5CYzdMi8)

It is due to case sensitivity, but in a weird way (value is converted to lowercase, but the regex isn't). Sorry for the delay on pushing this PR out. Working on getting tests to pass, then will post.

**Comment by jfdoming** [comment]
hey folks, any chance you could try out the linked PR (deployed [here](https://deploy-preview-3399.demo.actualbudget.org/)) and let me know if it fixes the issue you were seeing?

**Comment by juanrapmc** [comment]
![Screenshot 2024-09-15 212108](https://github.com/user-attachments/assets/6fa28f02-cd04-460c-a136-aeeefa8fd28d)

Looks good to me! Thanks for this!

**Comment by oddstr13** [comment]
I tested with the demo data, so haven't tested the imported payee field (as it doesn't seem to be populated there), but both exact matches and regex matches on the notes field seems to be working just fine on the deployed test instance.
