### ISSUE TITLE
Movement of money between budget categories disappeared

### ISSUE THREAD

**Issue by Deguello** [actualbudget/actual#335]
I know this is basically impossible to duplicate, but here it is anyway...

Last night, my budget was flawless. All the balances in all the categories were as I expected and matched those in the budgeting app I'm transitioning away from.

This morning, I was overbudgeted in November by $13 on the desktop. This didn't show up in the mobile app. I tried a manual sync. Nothing changed. I closed the app and reopened it. The overbudgeted amount went away for November, but now it said that I'd overspent by $13. After going through my categories one by one, I found the issue. 

I have a Fun category that serves as a pool for Restaurants, Socializing, etc. Last Friday, I spent $13 at a restaurant and covered that spending by transferring from Fun. For almost a week, everything was kosher. This morning, that transfer had apparently disappeared and Restaurants was $13 short and that $13 was back in Fun. Redoing the transfer resolved the issue, but if I weren't so familiar with the whole process, I'd have been lost and freaked out.

Again, I get that there's likely nothing to do be done about the particular occurrence, but I figured it was worth throwing out here anyway.

**Comment by rich-howell** [comment]
Hey @Deguello 

I am going to close this, there have been a number of improvements to the Sync in the closed version, if this still persists, please let me know and I will re-open it. 

Cheers
Rich

**Comment by islami00** [comment]
@Deguello , you mentioned "moving" money between categories, may I ask how you did that? I'm also trying to do this, and actual doesn't seem to allow explicitly moving money between categories unless you add/remove from the budget (which doesn't leave a trail). An example of this is ynab money moves

**Comment by Kidglove57** [comment]
@islami00 there is no trail as such (it would be nice to have!) but then YNAB only added this quite recently.

You have probably seen this already, but if you click on the right column in Budget (Balance) there is a tool right there, to move money to another category.

See also the subsection on moving money around in these help notes:

https://actualbudget.org/docs/budgeting/

**Comment by islami00** [comment]
thanks! I'll go with the $0 split transactions as it leaves a trail
