### ISSUE TITLE
[Bug]: CSV import says there are no transactions TypeError: d.match is not a function

### ISSUE THREAD

**Issue by ekamil** [actualbudget/actual#3350]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I'm trying to import a CSV file from my bank. The same file works with one account (as in shows the list to transactions to import) but doesn't work with another nor on a blank new budget.

I'm attaching a minimal not working file along with an empty budget with one account. I get the same issue on this brand new budget as on the real one.
[minimal.csv](https://github.com/user-attachments/files/16840843/minimal.csv)

![Screenshot 2024-09-02 at 21 26 04](https://github.com/user-attachments/assets/08527e4e-44ab-4da0-a3a7-8e569dc8c676)
[2024-09-02-My Finances.zip](https://github.com/user-attachments/files/16840844/2024-09-02-My.Finances.zip)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Mac OSX

**Comment by matt-fidd** [comment]
This looks to be fixed on edge, could you verify on https://edge.actualbudget.org please?

**Comment by ekamil** [comment]
Yup, works there, very cool :)

**Comment by oddstr13** [comment]
Yep, this is why I'm testing out edge right now

**Comment by matt-fidd** [comment]
@ekamil A new release is cut at the start of every month. It should be out for you either today or shortly after!
