### ISSUE TITLE
[Feature] Multi-currency support

### ISSUE THREAD

**Issue by djhtml** [actualbudget/actual#3351]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

If you live outside of the US it's common that you have multiple accounts with multiple currencies. (Especially if you have Revolut, Wise, etc.) It's usual that you order something online in different currencies or travel. It'd be nice to have this feature in Actual.

I read that it was planned, here:
https://github.com/actualbudget/releases/discussions/112

### Describe your ideal solution to this problem

Making a transfer between two accounts with different currency is not straightforward, since the amount won't match.
Eg.: debit: 11 USD, credit: 10 EUR.

Also, addig something to the budget in a foreign currency is not straightforward, what exchange rate do you use?

Option A:
- daily exchange rates for each currency.
- e.g.: 2024.08.15. 1 EUR = 1.12 USD
- you buy something for 10 EUR in that day it will show up as 11.2 USD in the budget

Option B:
- you use FIFO
- you made a transfer/change between two accounts: 120 USD -> 100 EUR
- all later spending in EUR (as long as the 100 EUR last) will be considered in 1.2 rate

Daily exchange rates could be manually added or fetched from a server.

**Comment by jfdoming** [comment]
Duplicate of #1132
