### ISSUE TITLE
[Feature] OIDC/SSO service support.

### ISSUE THREAD

**Issue by Shazib** [actualbudget/actual#3357]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

My instance of actual (self-hosted) is exposed to the internet via a cloudflare tunnel which is protected by authelia.

In essence, trying to access my actual instance first redirects to the auth portal before allowing access to actual.

When you first login this works, including the client apps access to actual server. However if you refresh the page it loses its connection to the backend.

It also doesn't work at all in the desktop app as it has no idea how to handle the redirect to the login page.

Thanks

### Describe your ideal solution to this problem

- Desktop app understands the redirect for the authelia login
- Server is aware of the redirect for auth

### Teaching and learning

Should be quite intuitive to use without additional input when needed.

**Comment by youngcw** [comment]
have you tried #3286?

**Comment by Shazib** [comment]
> have you tried #3286?

Oh wow this looks like exactly what I might need, I did do a search for various terms in the existing issues list but didn't spot that!

And that didnt exist when i tried to implement my own fix a few months back

I'll check this out and let you know if it addresses this.

**Comment by youngcw** [comment]
the web app handles authentication now, and the multi user work will also build in OIDC.  Ill close this in place of those.
