### ISSUE TITLE
[Feature]: Option to disable imported payee tooltip 

### ISSUE THREAD

**Issue by csenel** [actualbudget/actual#3358]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Since v24.9.0, a tooltip to show imported payees is added. This underlines payees if they are imported.

One of the use cases of import & export functionality is to switch between Actual servers. Since I moved between Actual servers in different cloud providers before, almost all of my payees are marked as imported but their imported and actual payee names are identical. So the tooltip provides no benefit but it takes away from the aesthetics of the app and hinders user experience.

I would rather have this option under a setting so we can disable it by preference or a setting in payee options to unmark payees as imported.

<img width="151" alt="image" src="https://github.com/user-attachments/assets/461cbc28-2b74-47a1-aa9e-22fa52eed245">

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Operating System

Mac OSX

**Comment by youngcw** [comment]
Moving to a feature request
