### ISSUE TITLE
Long pressing accounts button not same as hitting + while in accounts tab

### ISSUE THREAD

**Issue by bpaulien** [actualbudget/actual#336]
As I recently discovered, long pressing the accounts icon at the bottom of the mobile app will pull up the "new transaction" page. Which is awesome. Although I noticed something that's missing. If you are in any given account register and hit the plus sign at the top right of the page, it will pull up the "new transaction" page, and the the Account field will be pre populated with the currently selected account.  But if you are in a given account register and long press the "accounts" icon at the bottom of the page, that account field is not populated with the account you're currently viewing. 

Edited for clarity.

**Comment by rich-howell** [comment]
Hey @bpaulien 

The mobile apps are no longer supported, we are working on a responsive version of the web app for Actual which we hope to have merged into main soon.

Cheers
Rich
