### ISSUE TITLE
[Feature] Off Budget Reporting

### ISSUE THREAD

**Issue by JamiesonRoberts** [actualbudget/actual#3360]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

It would be fantastic to be able to create ongoing reports to track the value and changes of off budget accounts over time to be able to see slow progress towards investment and savings goals in a more detailed way beyond just the net worth view.

There is no granularity in terms of tracking specific investments growth or stagnation beyond just a very broad overall number.

**Comment by youngcw** [comment]
You can now modify the net worth type of report to track single accounts, then save that modified report.  You need to enable the reports dashboard feature to do that.

**Comment by JamiesonRoberts** [comment]
@youngcw is it possible to have more than one net worth report on the report dashboard?

**Comment by youngcw** [comment]
It may just be in the edge build currently
