### ISSUE TITLE
Category selection is inconsistent

### ISSUE THREAD

**Issue by Deguello** [actualbudget/actual#337]
I haven't made a complete list, though I probably should, but in some places in the (Mac) app, a category can be selected by partially typing the name and hitting TAB once there's only one option and other places require ENTER to make the selection.

IMO, TAB is preferable but consistency is even more preferable.

**Comment by MatissJanis** [comment]
:wave: We're slowly moving things over to the new autocomplete component. That should address _some_ of the usability issues. So I'll close this one off for now so people don't accidentally pick it up and start implementing yet another autocomplete component :)

Tracking here: https://github.com/actualbudget/actual/issues/773
