### ISSUE TITLE
[Feature] Create a "this month" button for the budget summary page

### ISSUE THREAD

**Issue by Jonathan-Fang** [actualbudget/actual#3370]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

In multiview mode, which really helped me debug an issue with balances and for budget numbers in actual, i thought i was operating on september 2024 when in fact i was operating on september 2025. When I open actual, it defaults to wherever i left off or sometimes in random months, so I'm in like March 2024 when I want to know about my current month.

### Describe your ideal solution to this problem

I think we can adapt Google Calendar's solution, make a button called "This Month" and have it go to the current month. If it's multiple months view, have the current month be the leftmost month.
It can be placed left of the "choose number of months shown at a time" button, not in the sidebar.

Google Calendar also specifies it's September 2024 not September 2025, and that would be great as well.

![image](https://github.com/user-attachments/assets/81430553-3fc2-428b-9cc5-37029b5c14f3)

### Teaching and learning

The button should be quite intuitive, although it could be added to the main overlay documentation.

**Comment by Hydro8** [comment]
👍

**Comment by youngcw** [comment]
This has been added.
