### ISSUE TITLE
[Bug]: net worth report date-ranges

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#3373]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

![sfdafda](https://github.com/user-attachments/assets/96572501-dbf4-4cd2-a274-5eb5286f7bb7)

### Where are you hosting Actual?

None

### Operating System

None

**Comment by MatissJanis** [comment]
cc @carkom I tracked this down to `validateStart` somehow returning an unexpected date value. Maybe you have any quick ideas how we could patch it?

**Comment by carkom** [comment]
#3379
