### ISSUE TITLE
[Feature] privacy mode: decrease visual legibility of redacted content

### ISSUE THREAD

**Issue by olets** [actualbudget/actual#3376]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

The post-launch privacy mode conversation to date (starting at https://github.com/actualbudget/actual/issues/1360#issuecomment-1705283827) has focused on blurring not being secure.

Per https://github.com/actualbudget/actual/issues/1360#issuecomment-1705496000, opening this issue to track enhancing the visual privacy of privacy mode.

### Describe your ideal solution to this problem

I propose that instead of blurring numbers, we replace them with something else.

Since the effect is purely visual, a convenient way to do this is to switch to a visually illegible font.

https://github.com/christiannaths/redacted-font is a popular visually illegible font. The "script" face works reasonably nicely with the Actual UI.

**Comment by olets** [comment]
Released in https://github.com/actualbudget/actual/releases/tag/v24.10.0

Screenshot:

<img width="1145" alt="screenshot of new privacy mode" src="https://github.com/user-attachments/assets/417e6046-c1dc-4a0c-8052-1be366b5bc84">

&nbsp;

And a video

https://github.com/user-attachments/assets/0be1ffdb-4371-4994-b5f4-76374b39b3d3

**Comment by joel-jeremy** [comment]
@olets Thank you for your awesome work on this!

**Comment by jakob11git** [comment]
Just in case there's someone else out there that was wondering how illegible this particular font actually is in this case. There are four distinct symbols/scribbles. 0, 1, 2, 3, 4 cannot be distinguished (set 1), as well as 5, 6, 7, 8 and 9 (set 2). Then comma (,) and dot (.) is another set (set 3) and the minus (-) symbol is unique (set 4).

For example if we take this part from the screenshot above:

<img width="297" alt="スクリーンショット 2024-10-03 19 51 09" src="https://github.com/user-attachments/assets/ca232c46-4d47-41c4-a24d-5e4403f11684">

You can discern that is some amount between 1,550.55 and 4,994.99 -- should be secure enough for almost all use cases, but maybe to make this 100% solid in all cases some further refinement could be made. In any case shoutout to the contributor working on this I love seeing these improvements.
