### ISSUE TITLE
[Feature] Reconcile on Mobile

### ISSUE THREAD

**Issue by Cascadian-Dave** [actualbudget/actual#3385]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I reconcile my accounts often, but I use my phone most of the time. I don't see any way to reconcile my accounts from my phone. I hope that feature can be added soon.

### Describe your ideal solution to this problem

My first thought was to look in the top right corner, where there is currently a + sign, for an option to reconcile. Maybe turn that plus sign into a menu with three dots? I'm open to other ideas though. 

### Teaching and learning

Hopefully the UI design is intuitive enough that it doesn't require much documentation

**Comment by hedonic-unadaptation** [comment]
Any updates on this issue?

**Comment by Cascadian-Dave** [comment]
You can now rotate your phone into landscape view and access the desktop view of your budget. From there, you can access the reconciliation button.

**Comment by db-src** [comment]
> Any updates on this issue?

If there were, they would've been posted. These questions don't add anything except noise and spammy emails to subscribed users.

> You can now rotate your phone into landscape view and access the desktop view of your budget. From there, you can access the reconciliation button.

Or various browsers have an option to switch into desktop mode i.e. out of mobile mode, even while staying on portrait orientation.
