### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by tmryvz** [actualbudget/actual#3403]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

A bug happened!

### Where are you hosting Actual?

Desktop App (Electron)

### Operating System

None

**Comment by youngcw** [comment]
Unless you add some details we can't do anything.

**Comment by MatissJanis** [comment]
Please open a new issue with specific instruction on 1) what went wrong? and 2) how do we reproduce the issue (step-by-step instructions)?
