### ISSUE TITLE
[Bug]: Total failure of bank sync

### ISSUE THREAD

**Issue by JustinPallo** [actualbudget/actual#3409]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

A bug happened!

I went to the bank accounts tab and clicked "bank sync." After I hit sync, I get a bunch of red boxes that pop up and say: 

<!DOCTYPE html> <html> <head> <title>PikaPods - Pod is Loading</title> <meta charset="UTF-8"> <style> @font-face { font-family: system; font-style: normal; font-weight: 300; src: local(".SFNSText-Light"), local(".HelveticaNeueDeskInterface-Light"), local(".LucidaGrandeUI"), local("Ubuntu Light"), local("Segoe UI Light"), local("Roboto-Light"), local("DroidSans"), local("Tahoma"); } body, a { background-color: white; color: #333; font-family: 'system' }
.centered { margin-top: 10%; display: block; text-align: center; vertical-align: middle; }
</style> </head> <body>
<div class='centered'> <img style="max-height: 100px;" src="https://www.pikapods.com/static/502_logo.png" />
<h1>Pod is loading<span style="width: 4em;" id="loading-dots">.</span></h1> <p> Your Pod is stopped or loading in the background. This page will refresh automatically. </p> <p> If you see this page for more than a few minutes, please check the status and logs of your pod in the control panel or contact support. </p> </div> <script> setTimeout(function(){location.reload()}, 5000);
// dot animation document.addEventListener("DOMContentLoaded", function(event) { var x = 0; setInterval(function () { var dots = ""; x++; for (var y = 0; y < x % 4; y++) { dots += "."; } document.getElementById("loading-dots").innerHTML = dots; }, 500); }); </script> </body> </html>

It blows through all the accounts, each one fails, and then bank sync goes offline.

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by MatissJanis** [comment]
<img width="1261" alt="Screenshot 2024-09-09 at 19 20 14" src="https://github.com/user-attachments/assets/04fbf6ee-6d44-4853-a794-a66024e8b72a">

Sounds like your pikapods server is offline. Please reach out to the community on discord if you need tech support.
