### ISSUE TITLE
[Bug]: Bank Pekao (supported on GoCardless) is missing in the bank selection dropdown

### ISSUE THREAD

**Issue by newkind** [actualbudget/actual#3419]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

One of the Polish banks that's supported via GoCardless as stated on their website (https://gocardless.com/bank-account-data/coverage/) doesn't appear in the dropdown when I want to link my account to it.

![CleanShot_2024-09-10_at_11 44 16](https://github.com/user-attachments/assets/1ffc335d-faf5-4cb9-9527-22b84fc7343f)

![CleanShot_2024-09-10_at_11 44 39](https://github.com/user-attachments/assets/4f1d43c4-1836-4289-8078-8e61491084bf)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge, Desktop App (Electron)

### Operating System

Mac OSX

**Comment by youngcw** [comment]
The list of banks comes directly from goCardless.  Have you reached out to them to ask why its not available?

**Comment by newkind** [comment]
Yep, you are right, I checked the API and it doesn't return this institution. I'll contact the GoCardless.
