### ISSUE TITLE
[Bug]: Categories of the transactions are not getting imported in CSV Import tool

### ISSUE THREAD

**Issue by AshwinPras** [actualbudget/actual#3428]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I am attempting to import my old transactions using a CSV file from my old budgeting app. But in the import screen, while all the other information is getting mapped correctly, there are missing categories. In fact, only 2 out of around a dozen categories are being recognised. Find screenshots below:

As you can see here, besides _Bills_ and _Food_, all the other categories are missing. 
<img width="1280" alt="Screenshot 2024-09-13 at 11 16 19 PM" src="https://github.com/user-attachments/assets/0d622a4c-194b-4971-acf5-9c5081c35f18">

The original source has other categories also:
<img width="657" alt="Screenshot 2024-09-13 at 11 17 29 PM" src="https://github.com/user-attachments/assets/ddac9c36-79d1-40b0-9ab7-adbc0b63136e">

App version: 24.9.0

A sample of the CSV file: 
[Bank Account.csv.zip](https://github.com/user-attachments/files/16997734/Bank.Account.csv.zip)

Kindly check. Appreciate any and all inputs. 

### Where are you hosting Actual?

None

### What browsers are you seeing the problem on?

Desktop App (Electron)

### Operating System

Mac OSX

**Comment by youngcw** [comment]
It will only import categories that exist on your budget.  If you want the others to import with a category you need to add those to your budget.

**Comment by AshwinPras** [comment]
Thanks a lot for your reply. That makes total sense and I’m embarrassed
that I missed it.

**Comment by webberian** [comment]
This information should be on the help pages, e.g. https://actualbudget.org/docs/transactions/importing

**Comment by balthanon** [comment]
Adding a link to the enhancement request that covers automating this process:  https://github.com/actualbudget/actual/issues/557
