### ISSUE TITLE
[Feature] Allow budgeting groups

### ISSUE THREAD

**Issue by CrazyKidJack** [actualbudget/actual#3438]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

There are many times where I don't want to have to assign a specific dollar amount to each category, but rather just to the group.
For example, I may have a group called "groceries" and within that categories for different types of grocery store items. Having the fine-grained categories is helpful to know exactly what i'm spending my money on which can help me make decisions in the moment... but when I'm actually doing my budget, I don't know exactly how many dollars I'm going to spend on produce vs junk food. I just know that total I want to spend say $200 on groceries. If I find I'm spending more than the $200, then I can look at the individual categories to figure out where that money is going and where I might be able to cut back.

If multi-level groups were ever implemented, I'd like the same idea to be applied to every level of grouping.

### Describe your ideal solution to this problem

I think how it would work is self-explanatory except when multiple levels have budgeted amounts at the same time that do not add up to the same amounts.

I think the top-level group budget (and not the category budgets) should always be the thing that is used for the calculations in the cards at the top of the budget page.

If you don't assign a group budget, it automatically gets set to the sum of its child category budgets.

If you do assign a group budget, then there is the opportunity for a mismatch, which could be handled (I think intuitively) as follows:

In this case I think AB should force the group budget to be greater than or equal to the sum of the category budgets. This would allow users the option to
- only assign a group budget,
- assign a group budget and allocate some but not all of that to individual categories,
- assign all of it to individual categories (which could be done automatically by just not manually assigning a group budget)

This would allow current users to keep using exactly how they have up until now with no change in behavior (if they never assign a budget to a group... then they will always default to equaling the sum of their categories... just like they do now)

But it would also allow users like me to decide, for each group, how specific we want to go with our budgeting independently of how specific we want to go with our spend tracking.

### Teaching and learning

Would probably need to add some documentation to the budgeting docs about the 3 cases:
- assigning a budget to categories only
- assigning a budget to a group only
- assigning budgets to both groups and categories

**Comment by CrazyKidJack** [comment]
I did not select the checkbox for "Would you like to implement this feature?".
That said, I have significant development experience and would be willing to do so. But I would need/want significant assistance getting started navigating the AB code. Once I get going, I code quickly and (I like to think) with high quality... but I always have a hard time getting into other people's code, figuring out how it works, and figuring out the best way to set up the dev environment for that project. It's really a momentum problem. If someone could help guide me to a point where I understand the code base, then I would be more than happy to hop in on this and also other features.

**Comment by wetrustinprize** [comment]
Would really like to see this in Actual, currently I just have 3 categories to follow the 50/30/20 rule, but I can't have a fine report about my expenses since they are just three categories.

**Comment by ArtwoXYZ** [comment]
I'm very interested in this feature as well. For my budget management, this would be the single most important and useful improvement Actual could make.

I want to keep detailed categories for tracking and reporting, while assigning one flexible budget to the whole group instead of guessing in advance how much I will spend in each category. Right now, this requires a holding category and manual transfers or cleanup. Being able to budget the group directly would fit my workflow much better.
