### ISSUE TITLE
[Bug]: Filters are overwriting each other

### ISSUE THREAD

**Issue by youngcw** [actualbudget/actual#3440]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

In edge you can't add more than one filter at a time.  If you add one filter, then make a second one and add that, it replaces the first filter.

Replicate:
1. Open a test file in edge
2. View an account and make a filter such as category:food 
3. Make another filter such as date is >=09/01/2024
4. See that the original category filter gets replaced

### Where are you hosting Actual?

Other

### Operating System

None

**Comment by youngcw** [comment]
@MatissJanis Looks like #3311 caused this.

**Comment by MatissJanis** [comment]
Good catch! Thanks
