### ISSUE TITLE
[Feature] Importing categories

### ISSUE THREAD

**Issue by kriswdue** [actualbudget/actual#3446]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I noticed that in the response to the bug reported here: https://github.com/actualbudget/actual/issues/3428#issue-2525372326 you answered that categories needed to be in place before importing transactions through files. However, this makes importing transactions cumbersome in migration cases where categories already exists, or in other cases where banks actually provide a precategorized column in the data (like mine does). 

### Describe your ideal solution to this problem

This should be handled so that if new categories are encountered during import, they should be automatically added.

### Teaching and learning

When presented with the importing interface, the wanted behaviour would probably be naturally assumed to be the default.

**Comment by youngcw** [comment]
Looks like you found an existing request. Ill close this one as duplicate.

**Comment by balthanon** [comment]
Adding a link to the existing feature request so that others who find this issue can go directly there:  https://github.com/actualbudget/actual/issues/557
