### ISSUE TITLE
[Bug]: Focus/hover in select component not working on edge

### ISSUE THREAD

**Issue by jfdoming** [actualbudget/actual#3447]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

## Steps to reproduce
1. Visit https://edge.actualbudget.org.
2. Open the Rules page and create a new rule.
3. Hover/click on the "Payee" button—the hover effect flickers and then disappears

## Expected behaviour
On https://demo.actualbudget.org, the effect displays on focus and doesn't disappear.

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by MatissJanis** [comment]
cc @joel-jeremy probably related to `Button` migration
