### ISSUE TITLE
[Feature] Regex Mode Modifiers for Rules

### ISSUE THREAD

**Issue by elkalt** [actualbudget/actual#3454]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

It would be nice to have mode modifiers for regex in rules, namely `(?i) (?-i)` for case insensitivity.

**Comment by jfdoming** [comment]
> ### Verified feature request does not already exist?
> * [x]  I have searched and found no existing issue
> 
> ### 💻
> * [x]  Would you like to implement this feature?
> 
> ### Pitch: what problem are you trying to solve?
> It would be nice to have mode modifiers for regex in rules, namely `(?i) (?-i)` for case insensitivity.
> 
> ### Describe your ideal solution to this problem
> _No response_
> 
> ### Teaching and learning
> _No response_

Hey! Regex match is normally case insensitive, but there is a bug in the most recent release which caused it not to be. We'll have it fixed by the next release
