### ISSUE TITLE
[Bug]: Desktop Client closes after loading a self-signed certificate

### ISSUE THREAD

**Issue by tapmay95** [actualbudget/actual#3461]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

So I've been attempting to setup the Actual desktop application on my Linux laptop with both the AppImage and the Flatpak to connect to my Actual server running on my local network. Trying to load a certificate to it causes the application to close (probably crash).

What is happening:
1. Actual reports that I have not set up HTTPS properly, and prompts me to add a self-signed certificate,
2. I browse to the certificate (PEM format) on my local directory and "open" it, 
3. Actual closes itself, and does not report any error message,
4. Reattempts to connect following 1 through 3 using both PEM and DER formatted root certificates and server certificates

I am not sure where or how I can increase the logs to help find the source of the issue, but am happy to try! It's been working great through the browser so far.

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Desktop App (Electron)

### Operating System

Linux

**Comment by Teprifer** [comment]
@tristanm95 You might find this thread in discord helpful: https://discord.com/channels/937901803608096828/1281484103580909621

Otherwise check out: https://github.com/actualbudget/actual/pull/3431
And associated files: https://github.com/actualbudget/actual/actions/runs/10855982981

**Comment by tapmay95** [comment]
That build was extremely helpful in debugging my certificate issues, thank you! Console logs showed what was wrong with the cert (it was expired). Looking forward to being able to work on my budgets offline on the road now!
