### ISSUE TITLE
[Bug]: privacy mode is broken

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#3470]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Privacy mode no longer working for the majority of elements (i.e. side nav, transaction table, budget rows, etc.)

Possibly related to: https://github.com/actualbudget/actual/pull/3374

### Where are you hosting Actual?

None

### Operating System

None

**Comment by matt-fidd** [comment]
It'd be good to get some VRT tests in for privacy mode as part of any fix; not sure how trivial that is though. I thought about it the other day too when looking at the PR to change the font instead of blur.
