### ISSUE TITLE
[Bug]: Monthly spending report - Renderer Issues

### ISSUE THREAD

**Issue by TerborX** [actualbudget/actual#3473]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

The monthly spending report causes the Actual Helper (Renderer) process to have high CPU utilization. Both Actual Helper and the Renderer kick way up (Renderer @ 62%+ CPU and Helper @ 42%+)

I'm running the MacOS desktop app and my computer's fan revs up to high speed to cool things down when this report is included on the dashboard. Without the report, CPU utilization is 1% or less for both processes

Custom bar graph reports, income statement-style reports, and the net worth report all on the dashboard at once are fine (low CPU).

Hosting on PikaPods, running Desktop App (Electron) on MacOS

How to reproduce:

- Enable Monthly spending report
- Include report in report dashboard
- View in Desktop App (Electron) on MacOS

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Desktop App (Electron)

### Operating System

Mac OSX

**Comment by MatissJanis** [comment]
_Something_ in the `SpendingCard` component is causing never-ending re-renders. Fortunately the changes I'm doing as part of [this PR](https://github.com/actualbudget/actual/pull/3432/) is also fixing the CPU issue here.
