### ISSUE TITLE
[Bug]: e2e tests have become flaky

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#3482]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

The e2e tests have become increasingly more flaky in the past few days. Need to look into what's the issue and address it.

### Where are you hosting Actual?

None

### Operating System

None

**Comment by joel-jeremy** [comment]
One this I noticed is that the rules page is crashing on VRT but when you open the page in the browser it works just fine.
![image](https://github.com/user-attachments/assets/22805ff3-d563-4984-aead-ff162f5def0a)

**Comment by joel-jeremy** [comment]
This change also appears randomly:
![image](https://github.com/user-attachments/assets/b48ca5f2-6bd5-42f2-a1cb-539e103c6528)

**Comment by matt-fidd** [comment]
![image](https://github.com/user-attachments/assets/1b5997cb-04d6-45e0-9c2a-1a05ac41f060)

Got it! This is the error on the rules page that's causing it to fail.

**Comment by UnderKoen** [comment]
One thing I noticed with https://github.com/actualbudget/actual/pull/3499 was that the css classes of glamour weren't applied with the same precedence as in the browser. This can be caused by the order of the css in the final css changing

**Comment by MatissJanis** [comment]
Another issue I'm seeing semi-frequently: onboarding test.

Sample failing ci job: https://github.com/actualbudget/actual/actions/runs/11037117182/job/30657293317

Trace: 
[trace.zip](https://github.com/user-attachments/files/17137709/trace.zip)


View the trace here: https://trace.playwright.dev

**Comment by MatissJanis** [comment]
Both the rules & onboarding e2e should be more stable now. Haven't been able to reproduce the settings one yet. If anyone sees a failing CI job with it - please post it here.

Or if you also see other e2e ci jobs failing (that use the latest changes in master) - please post them here.

**Comment by MatissJanis** [comment]
Related https://github.com/actualbudget/actual/pull/3506
