### ISSUE TITLE
[Bug]: Duplicate transfer transaction is created after bank sync

### ISSUE THREAD

**Issue by kftb** [actualbudget/actual#3485]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Step by step: 

- I run bank sync via SimpleFin
- Actual creates an imaginary transaction to match a "transfer" between two accounts despite there being an actual matching transaction

**Expected behavior:** 
- Bank sync only imports real transactions
- Actual matches transfers automatically but only with real transactions

**Actual behavior:** 
- Bank sync imports all transactions
- Actual creates a net new transaction as transfer to match an actual one
- This throws off account balances since the real counterpart transaction remains unmatched
- This can't be easily fixed, since deleting the duplicative one, deletes both transaction marked as "transfer"

**on Screenshot:** 
- Highlighted transaction: Duplicative transaction created by Actual
- The two above: The actual ones
![Screenshot 2024-09-22 at 14 55 40](https://github.com/user-attachments/assets/476df0ef-61f0-41f8-bee7-fb3d13fc769d)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by youngcw** [comment]
You need to use rules to tell Actual that the two sides match
https://actualbudget.org/docs/budgeting/rules/custom#q-i-use-bank-sync--how-do-i-create-transfers-and-not-make-duplicates

**Comment by kylepyke** [comment]
This rule is still not working. Seems like Actual's dedupe isn't triggering?
