### ISSUE TITLE
[Feature] Make transfer on different amounts (fees)

### ISSUE THREAD

**Issue by SodaSyrup** [actualbudget/actual#3486]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Transfer payments that have different values (fees) cant be made to transfers

![{66329B1A-6661-437B-BB8E-283976803596}](https://github.com/user-attachments/assets/8b20b152-4a4c-4baf-9da5-ca155b2b1748)
(i used some weird workaround to have it display properly, but if i didnt have to do it it would be awesome)

### Describe your ideal solution to this problem

Select two payments, press "make transfer" and have it understand (with my example pic above) the 4 cents are some sort of fee and it not changing the 5 on the recieiving account

**Comment by youngcw** [comment]
The fix is probably to make a split on the side that has a fee and split the transaction between fee and transferred funds.
