### ISSUE TITLE
[Feature] Improve handling of pending transactions for SimpleFIN sync

### ISSUE THREAD

**Issue by wfg** [actualbudget/actual#3502]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Currently, if a pending transaction syncs into Actual from SimpleFIN and ends up not clearing, it remains in the Actual account ledger. I can't think of any situation in which these transactions should be in the ledger.

related issue: https://github.com/actualbudget/actual/issues/3138

### Describe your ideal solution to this problem

Ideally these transactions would be removed from the Actual ledger.

An acceptable alternative solution would be to optionally disable syncing pending transactions from SimpleFIN. That may be a flag or UI option that sets [this value](https://github.com/actualbudget/actual-server/blob/c01e229bd7190c4576d2be109edac571196f0f00/src/app-simplefin/app-simplefin.js#L334) appropriately (instead of hard-coding it to `1`).

**Comment by gabeklavans** [comment]
Given actual's stance is to never automatically delete things, I'm a strong proponent of the second option to just add a toggle to prevent pending transactions from being synced at all.

**Comment by youngcw** [comment]
> Given actual's stance is to never automatically delete things, I'm a strong proponent of the second option to just add a toggle to prevent pending transactions from being synced at all.

@gabeklavans Have you tried out the edge build lately? 🙂

**Comment by gabeklavans** [comment]
> > Given actual's stance is to never automatically delete things, I'm a strong proponent of the second option to just add a toggle to prevent pending transactions from being synced at all.
> 
> @gabeklavans Have you tried out the edge build lately? 🙂 

I have not! But I'm assuming something has been merged in to address this! Maybe I'll check it out

**Comment by youngcw** [comment]
Optional import was implimented by #4253.  Closing.
