### ISSUE TITLE
[Bug]: Import hangs

### ISSUE THREAD

**Issue by fantasygoat** [actualbudget/actual#3519]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Fresh docker-based server setup.  Imported YNAB4 budget without issue.  Attempting to import a file, clicking the Import link and selecting a quicken file leads to a black box with spinner that never finishes.  

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome, Safari

### Operating System

Mac OSX

**Comment by fantasygoat** [comment]
I just did a CSV import and it worked.  Seems to not like Quicken files.

**Comment by MatissJanis** [comment]
👋 Would you mind providing an example import file so we could try and reproduce?

**Comment by fantasygoat** [comment]
[accountactivity-7.qfx.zip](https://github.com/user-attachments/files/17176769/accountactivity-7.qfx.zip)

**Comment by MatissJanis** [comment]
Thanks! I was able to reproduce and patch the issue here: https://github.com/actualbudget/actual/pull/3541

However, sadly your file is malformed so it will still not work when importing in Actual. But at least now it will show an error message.

**Comment by fantasygoat** [comment]
How is it malformed?  It's from my bank and it loads in NYAB4 and NYAB Web just fine.  So basically I can't use my bank's downloaded files?

**Comment by MatissJanis** [comment]
The problem is on line 38: `<ACCTTYPE>`. Remove that empty tag and your imports will work :+1:

**Comment by fantasygoat** [comment]
Wouldn't it be better to ignore empty tags?

**Comment by MatissJanis** [comment]
Technically `<ACCTYPE>` is invalid XML syntax for empty values. The correct syntax would be either `</ACCTYPE>` or `<ACCTYPE></ACCTYPE>`. So the XML parser correctly _breaks_ when it parses the file.

Though I can see that it would be better in this case to auto-magically ignore such elements. Feel free to either contribute with a PR or submit a feature request for this.
