### ISSUE TITLE
[Feature] Add Financial Institution Column to Link Accounts Screen

### ISSUE THREAD

**Issue by UnInfamous** [actualbudget/actual#3529]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Legibility in knowing what financial institution which accounts belong to. For example, I added a new account to SimpleFIN and going back to add a new account, I can't see which account it is. For some additional context, my partner and I have our accounts setup in separate files. I just added Apple Card and when I went to add the account, I can't tell at a glance what financial institution/account it is.

### Describe your ideal solution to this problem

Would like to add a column named Financial Institution to the right of 'Bank Account To Sync' that would specify the FI name as SimpleFin has it if that is passed along.

I don't have years developing a pre-existing app, and not fully familiar with all of the languages at play, so I'll need some help to get started.

### Teaching and learning

It would be immediately noticeable when opening the 'Link bank account with SimpleFIN' button.

**Comment by tinng81** [comment]
With the new introduction of label from SimpleFIN, accounts can have labels appended after the institution (see photo). Here is the raw data pulled indicating the applied labels. Maybe what's best is a similar approach of a fixed institution column with labels from SimpleFIN and another column for "friendly name" that user can edit?

```

Wealthsimple WS TIN - CASH

{'id': 'TRN-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', 'posted': 1708689600, 'amount': '0', 'description': 'description', 'payee': 'payee 'memo': '', 'transacted_at': 1708689600}
--------------------------------------------------

Wealthsimple WS TIN - SELF_DIRECTED_XXXX
{'id': 'TRN-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx', 'posted': 1708689600, 'amount': '0', 'description': 'description', 'payee': 'payee 'memo': '', 'transacted_at': 1708689600}

--------------------------------------------------
```
![Screenshot 2024-10-05 at 9 05 17 AM](https://github.com/user-attachments/assets/b19ce5f0-712e-4181-acd3-e69a7962b59c)

**Comment by UnInfamous** [comment]
I believe adding more than one column would go against Actual's minimalist design strategy. Even adding one with the information I would like to get across might be too much.

As an aside, from how Actual pulls financial institution names from SimpleFIN, they come with the labels attached.

I believe my difficulty here will be validating with GoCardless as well. I thought I saw a test account in the codebase somewhere, but can't currently recall.

**Comment by youngcw** [comment]
this has been added
