### ISSUE TITLE
[Feature] change dashboard view of default reports

### ISSUE THREAD

**Issue by nikolajhendel** [actualbudget/actual#3537]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

The reports section is getting really good (imo), but the default 2 reports on the dashboard are fixed and can't be replicated with the current report creation interface.
- Net Worth graph on dashboard defaults to last 6 months
- Cash flow graph on dashboard defaults to current month

### Describe your ideal solution to this problem

Allow Net Worth and Cash Flow graphs on dashboard to be customized (time filter). This can be done when clicking on report and changing time filter - but it can't be saved/updated on dashboard.

Especially the Cash Flow graph is valuable as the detailed view is a composite graph with income/expenses bar chart and balance line graph (which afaik. cannot be replicated in the reporting tool). 

### Teaching and learning

A stretch goal could be to offer the built in functionality of those 2 reports into the create report interface. That would offer a lot more flexibility - but for a start, having those 2 reports updatable from a time filter perspective would enhance the experience for users.

**Comment by Teprifer** [comment]
With the exception of specifally creatimg via the same custom reports way, what you're requesting is already in the edge build, and will be released shortly.  

Note that being able to customise the dashboard was added as an experimental feature in the last release.

**Comment by nikolajhendel** [comment]
that is great news.

I'm so impressed with the reporting/dashboard features that I've forgotten that it's so new :)

**Comment by youngcw** [comment]
Closing as this is already added and will be in the next release.

**Comment by nikolajhendel** [comment]
@youngcw and @Teprifer - great to see the features released in v24.10.0.

I know this topic is closed but wanted to check. 
Is there a way to get the detailed view of cash flow exposed in dashboard (it basically combines cash flow and net worth in a really nice way)?

Happy to create a new task/feature request.

**Comment by Teprifer** [comment]
@nikolajhendel Is #3630 what you're thinking of?
