### ISSUE TITLE
[Bug]: Cannot create rules from existing transaction

### ISSUE THREAD

**Issue by reneald** [actualbudget/actual#3538]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

**Server OS**: Ubuntu 24.04
**Docker image used**: actualbudget/actual-server:edge-alpine *(sha256:d11e0d37d64956289821be2d32a31267a16f1bc017cff31e0b83fe87a16818bd)*

As of today, I am unable to create new rules by selecting a transaction in an account view.
I'm still able to create rules by going to the Rules view and clicking 'Create new rule'.
New rules also still get added automatically when creating a schedule.

#### Steps to reproduce:
* Start a new budget file, add some accounts and add some transactions to those accounts
* Select a transaction, open the '1 transaction' menu and click 'Create rule'
* Fill in the conditions and actions as needed
* (Optional): select matching transactions, click 'Apply actions' > this works
* Click 'Save'

#### Actual result:
* The rule is not created
* Error message: 'Something internally went wrong. You may want to restart the app if anything looks wrong. Please report this as a new issue on Github.'

#### Expected result:
The rule is created successfully without error message.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 10

**Comment by matt-fidd** [comment]
Can confirm:

![image](https://github.com/user-attachments/assets/b5db0b52-a57d-4893-9b07-0d5e25905758)

**Comment by matt-fidd** [comment]
Potentially related:

https://github.com/actualbudget/actual/blame/4df03984bd64ac11acd70326321540967602bfb1/packages/desktop-client/src/components/accounts/Account.tsx#L1193

**Comment by matt-fidd** [comment]
@reneald - thanks for reporting this, it will be fixed in the next release, and edge builds

**Comment by reneald** [comment]
@matt-fidd thanks for fixing this!
