### ISSUE TITLE
[Bug]: "Show running balance" toggle is not maintained correctly when switching between accounts

### ISSUE THREAD

**Issue by ljrafols** [actualbudget/actual#3550]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

# Context
When toggling the "show running balance" option for a given (first) account, switching to another (second) account causes that second account to have the option enabled as well. However, switching back to the first account will cause the option to disable itself for that first account. The other account will then have the "show running balance" option toggled, **but only when switching from the first to the second - switching from a third/another account that does not have "show running balance" toggled to the second one does not invoke this bug**

# Reproduction Steps
Reproduction steps were done on my local desktop app using the Test Budget file.
This also happens on my Docker-hosted personal budget as well (both client/server upgraded to **v24.10.0** released today), reproducible on both the Desktop app and Firefox PWA.

1. Enabling "show running balance" on Ally Savings 
![image](https://github.com/user-attachments/assets/6e4bd15a-cc21-4ac1-b046-10b4a171ac02)

2. Showing running balance enabled on Ally Savings
![image](https://github.com/user-attachments/assets/c570b146-3ae1-4e4e-a787-0121bcb9814e)

3. Switching to Capital One Checking (this did not have "show running balance" toggled), with balance shown
![image](https://github.com/user-attachments/assets/3d9192b4-02be-45d7-b9f4-088582dfa5cc)

4. Switching back to Ally Savings from Capital One Checking, with no running balance shown
![image](https://github.com/user-attachments/assets/88897bcc-28cd-452b-bdfc-4cb5c07ad307)

5. Switching to HSBC from Ally Savings, which like Capital One Checking, does not have "show running balance" enabled
![image](https://github.com/user-attachments/assets/d80f475d-0076-43f7-b9ef-580775f3a43a)

6. Switching back to Capital One Checking from HSBC, where the balance is not shown unlike step 3
![image](https://github.com/user-attachments/assets/1353541d-a0b4-4e4c-8311-5714d37dcc29)

# Budget file used to reproduce
Sample Budget file:
[2024-10-03-Test Budget.zip](https://github.com/user-attachments/files/17249126/2024-10-03-Test.Budget.zip)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Desktop App (Electron)

### Operating System

Windows 11

**Comment by ngocphamm** [comment]
I was going to create a ticket for the "Hide reconciled transactions" toggle with similar behavior but I think those are all related.

**Comment by MatissJanis** [comment]
Can you check if this PR solved the issue?

https://github.com/actualbudget/actual/pull/3544

**Comment by ngocphamm** [comment]
@MatissJanis Took me a while to figure out how to pull the code, and test, but it looks like the PR fixes both the issue mentioned by @ljrafols and myself.

**Comment by ljrafols** [comment]
> Can you check if this PR solved the issue?
> 
> #3544

@MatissJanis This PR does resolve the issue. I wasn't able to replicate the bug with this in any way.

**Comment by csenel** [comment]
@MatissJanis any chance of a new patch version?
