### ISSUE TITLE
[Feature] Option to disable creation of automatic rules

### ISSUE THREAD

**Issue by mrkwnzl** [actualbudget/actual#3560]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

For payees with changing categories, the creation of automatic rules is rather hindering instead of helpful. The current solution is to have certain payees that get a post rule with an empty category, but that doesn’t help with all payees, as some  get other rules for categorizing and a post rule would overwrite the rule I actually want. So the solution there would be to create other post rules that are more specific. The better solution would be to simply disable the automatic creation of rules, as I can then create the rules I want the way I want.

### Describe your ideal solution to this problem

A simple switch in the settings, which, if enabled, will turn off the automatic creation of rules and schedules (if that is a thing as well).

### Teaching and learning

I think a switch in the settings called “Disable the automatic creation of rules“ is self-explanatory.

**Comment by mrkwnzl** [comment]
After I found out how feature requests are handled, I was able to find a request already here: https://github.com/actualbudget/actual/issues/2515

Please upvote there.

**Comment by youngcw** [comment]
This was added a few releases ago
