### ISSUE TITLE
[Bug]: cannot switch budget files on mobile

### ISSUE THREAD

**Issue by yauyenching** [actualbudget/actual#3562]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Hi all! Anyone else experience an issue that they are unable to switch budget files when using the web app on mobile?

Steps to Reproduce:
1. Clear cookies on mobile
2. Log in
3. See budget files
4. Choose one
5. Try to switch budget file
6. Budget file list is empty

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Mobile Device

**Comment by youngcw** [comment]
Im seeing the file list, but its really slow to load.  Do you see the file list if you wait like 5 seconds?

I did find a different bug in this process, but Ill open a ticket for that.

**Comment by yauyenching** [comment]
# Budget file choice page upon login
![photo_2024-10-05_00-05-42](https://github.com/user-attachments/assets/d2e4b695-92dc-4dfd-af5d-4e09d2c9cead)
# Not being able to switch to other budget files after choosing budget
![photo_2024-10-05_00-05-48](https://github.com/user-attachments/assets/f3657732-e1cb-401d-8f31-bbaf2fa000e2)

**Comment by youngcw** [comment]
it might not show the other files if you haven't downloaded them.  Try having two files downloaded before switching.

**Comment by yauyenching** [comment]
hey @youngcw -- thanks for your quick response! unfortunately, i'm not sure how to download budget files before opening them (upon initial log in after clearing cookies). clicking on the three dots to the right (kebab menu) immediately downloads the file and opens it, without giving more options as would be expected from that UI element.

**Comment by youngcw** [comment]
You can close the file from the settings menu and open a different one.  I found that kebab menu issue too just now.

**Comment by yauyenching** [comment]
@youngcw ah -- got it! i'm not very used to finding settings on mobile (scrolling up the transaction menu to reveal more actions). but it works! and i echo your #3563 bug!

**Comment by youngcw** [comment]
Glad it worked!
