### ISSUE TITLE
[Bug]: Balance color doesn't change to default after removing template and budget amount

### ISSUE THREAD

**Issue by Pheggas** [actualbudget/actual#3582]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

It is really simple to reproduce so i'll not provide budget file.
1. Enable templates in experimental features
2. Write some template, eg. `#template 10`
3. Apply budget
4. Remove the template and budget amount as well
5. See in the desired category 0 in all columns but the cell in `Balance` column is still yellow / green even if the template doesn't exist anymore

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 10

**Comment by shall0pass** [comment]
Have you tried applying the template button again for that category?  There's a drop down menu button in the budget cell for each category that has the option to only apply a template to that category.

**Comment by Pheggas** [comment]
It fixes by clicking the `Apply budget template` but i think it's not a great approach to do this. As the template doesn't exist, i would expect it to change the color to default (grey) one.

**Comment by shall0pass** [comment]
Keep in mind that using the notes section is a short term solution and the notes field is a general purpose text area.  The flow will be different with the goals UI being built out.

**Comment by youngcw** [comment]
Needing to re apply the template is expected for now until we stop using the notes section for templates.
