### ISSUE TITLE
[Bug]: Unable to connect to server behind auth proxy

### ISSUE THREAD

**Issue by deathblade666** [actualbudget/actual#3586]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

get the following error when trying to connect to my actual server that's behind an auth proxy for the header auth.

```
Server does not look like an Actual server. Is it set up correctly?
If the server is using a self-signed certificate select it here.
```

Assumably this is because its hitting my auth provider and not the actual server so its erroring out, im using Authentik to provide authentication which then passes the header to actual to authenticate with actual.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Desktop App (Electron)

### Operating System

Linux

**Comment by MatissJanis** [comment]
👋 Please reach out to the community on Discord for tech support.
<img width="1298" alt="Screenshot 2024-10-06 at 20 34 04" src="https://github.com/user-attachments/assets/c1393540-fd0b-4dea-bf3c-76266310c2e9">
