### ISSUE TITLE
[Bug]: Gocardless Setup with German bank "Hanseatic Bank" leads to blank page opening

### ISSUE THREAD

**Issue by yo-less** [actualbudget/actual#3592]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I've tried several times to add a German Hanseatic Bank account, but I'm not even being redirected to the Gocardless setup page, the logs are pretty extensive and I guess this should be easy to reproduce, but let me know if I can provide more information. Any other bank account that is supported by GoCardless and that I've tried is added without problems.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### Operating System

Windows 11

**Comment by MatissJanis** [comment]
Most likely an issue on Gocardless end, but either way - reaching out to the community on discord will be much more productive to get tech support for this than opening a bug here.

<img width="1261" alt="Screenshot 2024-09-09 at 19 20 14" src="https://github.com/user-attachments/assets/481a10db-078d-4c21-a2e1-f7de3ede1057">
