### ISSUE TITLE
[Bug]: OFX import with multiple accounts in file only lets one import one account

### ISSUE THREAD

**Issue by diktomat** [actualbudget/actual#3604]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

With YNAB, I'm used to importing all accounts at once by exporting all new from MoneyMoney as OFX and importing the file in YNAB. First time it asked which account in the file is which in YNAB and remembered that info.

With Actual, I can sync two accounts and tried the same procedure for the rest. Actual, however, only lets me import one of the accounts in the OFX file (may be the first credit card account in file).

As multiple accounts in one file is part of the spec, I decided to file it as a bug instead of a feature request.

### Steps to reproduce:
1. Export multiple accounts at once in MoneyMoney (or probably other sources?).
2. Try importing in Actual, only one account's statements are offered.

### Sample file
Zipped, as GitHub won't upload .ofx directly: [minimal.ofx.zip](https://github.com/user-attachments/files/17289217/minimal.ofx.zip)

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Safari

### Operating System

Mac OSX

**Comment by youngcw** [comment]
This is the expected behavior currently.  If you would like the ability to import multiple accounts at once you can open a feature request for it.
