### ISSUE TITLE
[Bug]: We had problems syncing your changes.

### ISSUE THREAD

**Issue by aisforaaron1** [actualbudget/actual#3614]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

My budget hosted on PikaPods isn't syncing. I get an error saying "we had problems syncing your changes. Please report this as a bug by opening a GitHub issue."

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 11

**Comment by matt-fidd** [comment]
There are reports in the Discord of PikaPods being down, they've said they'll post on their Twitter when it's back up and running

**Comment by matt-fidd** [comment]
> The server hosting this pod is currently offline after a failed scheduled reboot to apply needed updates. We are waiting for the data center to investigate.
> 
> There are recent backups and there is no indication of a drive failure. So no data loss is expected.
> 
> There is no need to send additional messages. We will post important updates on our Twitter page: https://twitter.com/pikapods
> 
> Thanks you for your patience and understanding!
