### ISSUE TITLE
[Bug]: Custom Report Total Mode not showing offbudget transactions

### ISSUE THREAD

**Issue by UnderKoen** [actualbudget/actual#3627]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

1. On edge create a test file
2. Create a custom report
3. Select mode: total
4. Select split: interval
5. Select type: net
6. Add filter: account is vanguard 401k (or any other offbalance account)
7. No data

I would expect there to be some data in the graph.

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by youngcw** [comment]
I tried this an got no data, but got data when I enabled off budget accounts in the options.  Is that still not showing all the data you expect?

**Comment by UnderKoen** [comment]
Ah, didn't test this with the test budget. Tried this in my own instance. The problem with the test budget is that the offbudget transactions have categories that why it shows here.
