### ISSUE TITLE
[Feature] Ability to Attach Files (e.g., Receipts) to Transactions

### ISSUE THREAD

**Issue by dgsouzabr** [actualbudget/actual#3628]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Managing reimbursable expenses and tracking proof of purchase for expensive items can be cumbersome when receipts and invoices are stored separately from the actual transactions. Currently, when logging expenses related to a business trip or other reimbursable activities, I must manually store receipts in an external app or physical location, making it difficult to match them to transactions later on. Similarly, for expensive purchases, I often need to keep proof of purchase for warranty claims or returns, but there’s no easy way to store these directly with the relevant transaction in the app.

If I could attach files (like photos of receipts) directly to transactions in the app, it would streamline the process of organizing reimbursable expenses and storing proof of purchase for returns or warranty claims. This feature would eliminate the need to use external apps or manual systems for receipt tracking.

### Describe your ideal solution to this problem

The ideal solution would allow users to attach files (such as photos of receipts or invoices) directly to individual transactions in Actual Budget. This feature should be accessible when creating or editing a transaction, and the attached files should be exportable alongside the transaction data, making it easy to retrieve when submitting expense reports or warranty claims.

For instance:

I could log a transaction for a business trip expense and attach a photo of the receipt.
When making an expensive purchase, I could attach the receipt or invoice directly to the transaction, ensuring I have easy access to the proof of purchase for future warranty claims or returns.

### Teaching and learning

To make this feature discoverable, a clear option to "Attach File" or "Add Receipt" could be added in the transaction entry screen. It could also be highlighted in the app’s documentation or tutorials about tracking reimbursable expenses or managing large purchases.

Additionally, a help section or tooltip could explain how to attach files and how to retrieve them when exporting or viewing transactions. The feature could also be introduced via a blog post or email update, showcasing how it simplifies common tasks like expense reporting or managing warranties.

**Comment by youngcw** [comment]
Duplicate of #530.  closing
