### ISSUE TITLE
Unable to enable Report/Rollover budget type switch

### ISSUE THREAD

**Issue by Megasteel32** [actualbudget/actual#363]
On the desktop subscription app, by adding "flags.reportBudget":true to the metadata.json file, a new setting on the Budget page will appear. This setting allows the user to switch between a Report budget and a Rollover budget (the default mode of Actual). 

When adding this flag to the metadata.json file under the relevant folder located in /actual-server/user-files, the setting on the Budget page does not appear, even after closing the file or restarting the container actual-server is running in. 

When copying the directory of the desktop app's data to the /actual-server/user-files directory via SFTP, the setting also does not appear. 

However, when sending the desktop app's data to a zip file, and importing said zip file using the self hosted web interface, the setting does appear under the Budget page.
![Screenshot](https://user-images.githubusercontent.com/20888678/174682812-da198506-0667-484c-a3b2-6e30de6f8512.jpg)

**Comment by j-f1** [comment]
I believe this was recently fixed by https://github.com/actualbudget/actual/pull/467, there is now a checkbox to enable the toggle button.
