### ISSUE TITLE
Setup DockerHub organization

### ISSUE THREAD

**Issue by boushley** [actualbudget/actual#364]
Docker supports open source projects for free on DockerHub. We should look at setting that up so we can have an officially supported docker container. Once we've got that I can setup a GitHub Action that automatically publishes the container when changes are merged to `master` on this repo.

I can go through the application process if that's helpful, but I didn't want to end up with maintainer access to it if that would cause concerns.

https://www.docker.com/community/open-source/application/

**Comment by MatissJanis** [comment]
👋 Sorry for the long time of inactivity folks!

We're currently looking to do this.

cc @trevdor

**Comment by trevdor** [comment]
Ah! Thanks for the tag. @boushley I'm sorry this was left unaddressed so long. It's definitely the direction we'd like to go, so thanks for the suggestion and the offer to apply. I certainly didn't mean to cut you out, I just didn't see this issue...but: 

I submitted the application with Docker last week. Supposed to hear back within 30 days. 

I'll keep this issue updated with any news until we have a resolution.

**Comment by trevdor** [comment]
Un-exciting update: no news yet from Docker (our application went in Jan 14th)

**Comment by Flightkick** [comment]
Does the transition to a dedicated Docker Hub org deprecate the current [`jlongster/actual-server`](https://hub.docker.com/r/jlongster/actual-server) images?
If so, it may be nice to inform current users to migrate.

**Comment by rich-howell** [comment]
> Does the transition to a dedicated Docker Hub org deprecate the current [`jlongster/actual-server`](https://hub.docker.com/r/jlongster/actual-server) images? If so, it may be nice to inform current users to migrate.

If it does it will be fully comunicated :)

**Comment by trevdor** [comment]
Another non-update, but I don't want folks to think this was forgotten again: no update from Docker yet on our application

**Comment by trevdor** [comment]
Still nothing. Emailed Docker today for an update on the status of our application.

**Comment by trevdor** [comment]
We've been accepted. 🥳  
Docker says we'll have an official Open Source org in the next couple weeks.  

Of COURSE they email the same day as the big Docker Hub Open Source kerfuffle goes down. 🙄 
My personal gut feel is Docker Hub is still the standard and we already use it, so we ought to start out there.
We'll just need to be careful in the future if anyone monetizes Actual. 
We already have GHCR as a backup plan, but it seems sensible to plant our flag on Docker Hub as long as this fits our project's structure and needs.

Let's keep this issue open till we actually get the org set up.
