### ISSUE TITLE
[Bug]: Some sort of weird sync thing

### ISSUE THREAD

**Issue by corrin** [actualbudget/actual#3656]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Some funny sync issue after attempting to connect an app.

Here's what I see on the command-line 
```
User@corrin-zephyrus MINGW64 ~/PycharmProjects/akahu_to_actualbudget (main)
$ node akahu_actual_mapping.js 
[2024-10-12T08:27:11.973Z] Fetched 21 Akahu accounts.
Actual API initialized successfully
Database is out of sync with migrations: {
  appliedIds: [
    1548957970627, 1550601598648, 1555786194328,
    1561751833510, 1567699552727, 1582384163573,
    1597756566448, 1608652596043, 1608652596044,
    1612625548236, 1614782639336, 1615745967948,
    1616167010796, 1618975177358, 1632571489012,
    1679728867040, 1681115033845, 1682974838138,
    1685007876842, 1686139660866, 1688749527273,
    1688841238000, 1691233396000, 1694438752000,
    1697046240000, 1704572023730, 1704572023731,
    1707267033000, 1712784523000, 1716359441000,
    1720310586000, 1720664867241, 1720665000000,
    1722717601000, 1722804019000, 1723665565000
  ],
  available: [
    '1548957970627_remove-db-version.sql',
    '1550601598648_payees.sql',
    '1555786194328_remove_category_group_unique.sql',
    '1561751833510_indexes.sql',
    '1567699552727_budget.sql',
    '1582384163573_cleared.sql',
    '1597756566448_rules.sql',
    '1608652596043_parent_field.sql',
    '1608652596044_trans_views.sql',
    '1612625548236_optimize.sql',
    '1614782639336_trans_views2.sql',
    '1615745967948_meta.sql',
    '1616167010796_accounts_order.sql',
    '1618975177358_schedules.sql',
    '1632571489012_remove_cache.js',
    '1679728867040_rules_conditions.sql',
    '1681115033845_add_schedule_name.sql',
    '1682974838138_remove_payee_rules.sql',
    '1685007876842_add_category_hidden.sql',
    '1686139660866_remove_account_type.sql',
    '1688749527273_transaction_filters.sql',
    '1688841238000_add_account_type.sql',
    '1691233396000_add_schedule_next_date_tombstone.sql',
    '1694438752000_add_goal_targets.sql',
    '1697046240000_add_reconciled.sql',
    '1704572023730_add_account_sync_source.sql',
    '1704572023731_add_missing_goCardless_sync_source.sql',
    '1707267033000_reports.sql',
    '1712784523000_unhide_input_group.sql',
    '1716359441000_include_current.sql',
    '1720310586000_link_transfer_schedules.sql',
    '1720664867241_add_payee_favorite.sql',
    '1720665000000_goal_context.sql',
    '1722717601000_reports_move_selected_categories.js',
    '1722804019000_create_dashboard_table.js'
  ]
}
Error updating Error: out-of-sync-migrations
```

A search found this which might be related?? https://github.com/actualbudget/actual/issues/3384

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Chrome, Other

### Operating System

Windows 11

**Comment by itsnotrisky** [comment]
Same issue on @actual-app/api@6.10.0

```
Error updating Error: out-of-sync-migrations
    at checkDatabaseValidity (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:42879:31)
    at Module.migrate (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:42887:17)
    at async runMigrations (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:46737:17)
    at async updateVersion (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:46756:17)
    at async loadBudget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:42484:21)
    at async handlers.load-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:42314:29)
    at async handlers.api/download-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:32562:21)
TypeError: Cannot read properties of undefined (reading 'timestamp')
    at _fullSync (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:46076:98)
    at /usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:45988:38
    at /usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:46934:38
    at initialFullSync (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:45974:38)
    at handlers.sync-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:42299:94)
    at handlers.api/download-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:32565:65)
[Exception] TypeError: Cannot read properties of undefined (reading 'timestamp')
    at _fullSync (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:46076:98)
    at /usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:45988:38
    at /usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:46934:38
    at initialFullSync (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:45974:38)
    at handlers.sync-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:42299:94)
    at handlers.api/download-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:32565:65)
/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:32567
                        throw new Error((0, _shared_errors__WEBPACK_IMPORTED_MODULE_2__.getSyncError)(result.error, localBudget.id));
                              ^
Error: We had an unknown problem opening “My-Finances-b62c7a2”.
    at handlers.api/download-budget (/usr/src/app/node_modules/@actual-app/api/dist/app/bundle.api.js:32567:31)
```

**Comment by matt-fidd** [comment]
Are your web version and API versions in line? Latest is v24.10.1 for both (versioning strategy for the API changed as of this release)

**Comment by itsnotrisky** [comment]
That's good to know re versioning - thanks @matt-fidd upgrading to latest v24 fixed it.

**Comment by matt-fidd** [comment]
No problem!

**Comment by MaxwellJP** [comment]
Is there any way to fix this? After updating to 24.12.0 I am consistently running into a similar situation?

Error updating Error: out-of-sync-migrations
    at checkDatabaseValidity (C:\Users\max\node_modules\@actual-app\api\dist\app\bundle.api.js:47811:31)
    at Module.migrate (C:\Users\max\node_modules\@actual-app\api\dist\app\bundle.api.js:47819:17)
    at async runMigrations (C:\Users\max\node_modules\@actual-app\api\dist\app\bundle.api.js:51716:17)
    at async updateVersion (C:\Users\max\node_modules\@actual-app\api\dist\app\bundle.api.js:51735:17)
    at async loadBudget (C:\Users\max\node_modules\@actual-app\api\dist\app\bundle.api.js:47408:21)
    at async handlers.load-budget (C:\Users\max\node_modules\@actual-app\api\dist\app\bundle.api.js:47238:29)
    at async handlers.api/download-budget (C:\Users\max\node_modules\@actual-app\api\dist\app\bundle.api.js:37349:21) {stack: 'Error: out-of-sync-migrations
    at checkDat…-app\\api\\dist\\app\\bundle.api.js:37349:21)', message: 'out-of-sync-migrations'}

**Comment by youngcw** [comment]
> Is there any way to fix this? After updating to 24.12.0 I am consistently running into a similar situation?
> 
> Error updating Error: out-of-sync-migrations at checkDatabaseValidity (C:\Users\max\node_modules@actual-app\api\dist\app\bundle.api.js:47811:31) at Module.migrate (C:\Users\max\node_modules@actual-app\api\dist\app\bundle.api.js:47819:17) at async runMigrations (C:\Users\max\node_modules@actual-app\api\dist\app\bundle.api.js:51716:17) at async updateVersion (C:\Users\max\node_modules@actual-app\api\dist\app\bundle.api.js:51735:17) at async loadBudget (C:\Users\max\node_modules@actual-app\api\dist\app\bundle.api.js:47408:21) at async handlers.load-budget (C:\Users\max\node_modules@actual-app\api\dist\app\bundle.api.js:47238:29) at async handlers.api/download-budget (C:\Users\max\node_modules@actual-app\api\dist\app\bundle.api.js:37349:21) {stack: 'Error: out-of-sync-migrations at checkDat…-app\api\dist\app\bundle.api.js:37349:21)', message: 'out-of-sync-migrations'}

You must have a version mismatch between one of your client/server/api versions.  Once that is fixed you may need to clear your browser cache if things are still not working.

**Comment by MaxwellJP** [comment]
> > Is there any way to fix this? After updating to 24.12.0 I am consistently running into a similar situation?
> > Error updating Error: out-of-sync-migrations at checkDatabaseValidity (C:\Users\max\node_modules@actual-app\api\dist\app\bundle.api.js:47811:31) at Module.migrate (C:\Users\max\node_modules@actual-app\api\dist\app\bundle.api.js:47819:17) at async runMigrations (C:\Users\max\node_modules@actual-app\api\dist\app\bundle.api.js:51716:17) at async updateVersion (C:\Users\max\node_modules@actual-app\api\dist\app\bundle.api.js:51735:17) at async loadBudget (C:\Users\max\node_modules@actual-app\api\dist\app\bundle.api.js:47408:21) at async handlers.load-budget (C:\Users\max\node_modules@actual-app\api\dist\app\bundle.api.js:47238:29) at async handlers.api/download-budget (C:\Users\max\node_modules@actual-app\api\dist\app\bundle.api.js:37349:21) {stack: 'Error: out-of-sync-migrations at checkDat…-app\api\dist\app\bundle.api.js:37349:21)', message: 'out-of-sync-migrations'}
> 
> You must have a version mismatch between one of your client/server/api versions. Once that is fixed you may need to clear your browser cache if things are still not working.

A bit confused how this is possible. I should have clarified, I am using PikaPods to host Actual, and I tried using the API on multiple devices. A Linux VM (where the scripts normally run, and my personal Windows computer). It also wasn't exactly when I updated to 24.12.0, it was really yesterday morning my scripts started failing to run. How would I go about resolving a version mismatch.

Note, I have no issues using app itself (across my phone and computer it syncs fine), it only seems to be related to the API.

**Comment by tdomhan** [comment]
I ran into the same problem. Updating to the API to `24.12.0` did seem to resolve the issue though.

**Comment by FloBlablabla** [comment]
I have the same problem, but I'm using version 25.11.0 (client and server). So the problem obviously still exists. Is there a solution yet?

**Comment by vmnds** [comment]
I faced a similar error message while importing a backup (not during sync). I didn't have a version mismatch between the 3 layers. Updating the server to the latest version fixed my issue.
