### ISSUE TITLE
Version label redirects to non existing blog url

### ISSUE THREAD

**Issue by hasanhakkaev** [actualbudget/actual#366]
The version label on the right bottom corner currently is 4.0.2 and redirects to a [non-existing blog page](https://actualbudget.com/blog/4.0.2).
The web version shows 0.0.148 and redirects [here](https://actualbudget.com/blog/0.0.148)

![image](https://user-images.githubusercontent.com/14126525/166122419-51e6254e-1b61-46d2-948d-3e12fff24017.png)

**Comment by rich-howell** [comment]
If we keep the releases as they are now it could just point to http://actualbudget.github.io/docs/release-Notes/{version number}

**Comment by rich-howell** [comment]
This has been resolved to point to the versions of each part of the application, this no longer directs to any link.
