### ISSUE TITLE
[Bug]: Imported CSV spending appears in other months

### ISSUE THREAD

**Issue by krumjahn** [actualbudget/actual#3661]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I have imported a bunch of expenses using CSV from various sources. It works fine initially then all of a sudden the expenses start appearing in random months that are not related. I've only started and only imported all my expenses for september but expenses started appearing in march and April. Then when I click on it, it shows no record.

For example. I somehow have -$868.56 for transportation in March. I click on it and it shows no records. 

<img width="1001" alt="Screenshot 2024-10-14 at 9 53 23 AM" src="https://github.com/user-attachments/assets/f8bf9c9a-1337-48dc-b2b8-78a5568452f2">
<img width="805" alt="Screenshot 2024-10-14 at 9 53 16 AM" src="https://github.com/user-attachments/assets/19eb05b1-1c64-4e6e-9a07-b8badc8e91b2">

This makes the software essentially unusable as the records are all over the place. I'm on the latest version of a self hosted actual budget.

Example of the CSV file I imported:
`
date,payee,notes,category,amount,currency
2024-09-28,NETFLIX.COM,,Subscription,-89.72,HKD
2024-09-27,AMAZON,,Purchase,-63.42,HKD
2024-09-22,Audible,,Purchase,-118.81,HKD
`

### Where are you hosting Actual?

NAS

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by MatissJanis** [comment]
👋 Would you mind uploading a demo budget file showcasing the issue? Thanks

**Comment by krumjahn** [comment]
I fixed it by clearing the cache!
