### ISSUE TITLE
[Feature] Apply Budget Template for all Budgets in Category

### ISSUE THREAD

**Issue by Dreptschar** [actualbudget/actual#3663]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

So i have a category which contains my budgets i need to fill, like rent and stuff. So when i get my money i need to manually apply the budget templates for all budgets in that category which is annoying. 

### Describe your ideal solution to this problem

Add a button to the category dropdown like "apply all budget templates" which applies all templates of the budgets in the category

**Comment by youngcw** [comment]
Im confused.  The apply button does apply all templates in a category.

You're talking about this "Apply Budget Template" button right?
![image](https://github.com/user-attachments/assets/5a77ab1a-5c20-4a2d-b03f-334b7222e146)

**Comment by Dreptschar** [comment]
@youngcw Sorry i confused some terms :D Ill Adjust the title. So what i actually mean is that i would love to have a button on a GROUP so that the button triggers all Templates inside of the group

**Comment by Dreptschar** [comment]
I will try to add that feature myself but im not really a react dev so i hope i can get it to work :D

**Comment by Dreptschar** [comment]
ahh there is already a feature request https://github.com/actualbudget/actual/issues/3040

**Comment by youngcw** [comment]
Ill close this one as duplicate.
