### ISSUE TITLE
[Feature] add overspent categories banner/screen on mobile and desktop

### ISSUE THREAD

**Issue by MarcAroni81** [actualbudget/actual#3667]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

If you overspent one or more categories in your budget it is easy to miss if you have a long list of categories. The only indication of a red text with negative numbers is easy to miss. 
Same as the already implemented feature of a banner for uncategorized transactions, it would be really nice to have a "warning" banner if you have one or more overspent categories. 
(this feature also is implemented in YNAB btw. ) 

### Describe your ideal solution to this problem

A banner - same as in feature (issue) 2656 - happens to appear if on ore more categories in your budget list is overspent. 
Clicking on that banner a list of overspent categories would be listed which makes it more easy to cover them by other categories.

**Comment by joel-jeremy** [comment]
Partially implemented in https://github.com/actualbudget/actual/pull/4643. This might also be a duplicate of https://github.com/actualbudget/actual/issues/2963.
