### ISSUE TITLE
[Bug]:  Gocardless does not work, whitescreen after bank login credentials

### ISSUE THREAD

**Issue by splnkr** [actualbudget/actual#3673]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Tried to linked it my Germany - DKB account. Does not work. After the login with my bank account and clicking on the purple successful linked button I only got a whitescreen

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Chrome, Safari, Desktop App (Electron)

### Operating System

Mac OSX

**Comment by MatissJanis** [comment]
<img width="1307" alt="Screenshot 2024-07-28 at 20 35 52" src="https://github.com/user-attachments/assets/64b3aea0-ea14-472e-9bae-4a36298b1ae5">
