### ISSUE TITLE
[Bug]: Syncing issue

### ISSUE THREAD

**Issue by Amikayama** [actualbudget/actual#3677]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

A bug happened! 
I am requesting help to resolve my current syncing issue, I have been using Actual for a little over 2 weeks when my data has been erased and now I cannot sync my expenses. 

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 10

**Comment by youngcw** [comment]
What do you mean erased?  Can you access your pikapods server?

**Comment by youngcw** [comment]
Closing because of lack of info.
