### ISSUE TITLE
[Feature] Rules should have the ability to match partial dates

### ISSUE THREAD

**Issue by djryanj** [actualbudget/actual#3687]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I have mortgage payments that come out twice a month, on the 15th and 30th. I have my budget set up so that this exists in 2 categories, one for the 15th and one for the 30th. I would like to set up 2 rules so that when these are seen, they are correctly categorized based on the date they happen.

Right now, the date rule only allows you to select a specific date. (I know, I could create scheduled transactions for this as well, but rules that allow for a more general date match would be good).

### Describe your ideal solution to this problem

The "date" rule should allow you to say "the 15th of the month" instead of requiring a specific date. Alternatively, a "day of month" or "week of month" or "month of year" rule could be created as options.

**Comment by Hydro8** [comment]
I searched for the same thing !
