### ISSUE TITLE
[Bug]: Copy last month's budget not working

### ISSUE THREAD

**Issue by psybers** [actualbudget/actual#3688]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I am using tracking budget (might not be a bug for envelope).

Normally, I go to the next month around now (half way through the current month) and copy the budget over, using "copy last months budget" in the menu:

<img width="266" alt="image" src="https://github.com/user-attachments/assets/c7ff7948-0c81-423e-a273-cac38cf5547a">

When I try that now, nothing happens. No errors in the JS console.  Literally nothing.  Just stays as zero's.

I can select the last option and set it to the 3 month average, and that works. And then I can select the second and zero it back out.  But the first option does nothing at all.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by psybers** [comment]
Ok interesting follow-up: if I manually set some value in November, I can 'copy last months budget' in December and it copies it over.

So only November is broken...

**Comment by corrosive4354** [comment]
Make sure you try to copy the budget at the right time (for example, in the middle of the current month).
Try to operate in different pages or different budget files to see if you can reproduce the problem.

In addition, it may be a compatibility issue between Docker and Mac environments. You can use [servbay](https://servbay.com) to solve it

**Comment by psybers** [comment]
First, there would be no "compatability issue" between the server in Docker and running the client in Mac. If there was any incompatibility, it would simply be the fact the client is running on mac.

Second, why would it be a "right time" issue? I already mentioned I tried it "in the middle of the month".  But why would other months copy just fine and not this single month?

**Comment by youngcw** [comment]
@psybers what happens if you switch to the envelope budget and add in a budget for October, then switch back to tracking and do the copy?

**Comment by psybers** [comment]
@youngcw Ohhhh fun. So if I do that, it copies the envelope's budget over and not the tracking budget!

**Comment by youngcw** [comment]
It does that in the edge deploy too.  I don't know what would have broke that, or if its just some weird edge case that just happened to come out this month

**Comment by psybers** [comment]
@youngcw Are you sure about that? If I load the demo budget on edge, enable tracking, set a tracking budget, then try to copy it seem to work as expected.

**Comment by psybers** [comment]
Oh interesting. It doesn't do it with the demo data, but it does it with my exported/imported data.

**Comment by youngcw** [comment]
I recently merged in a copy template.  Maybe try that.  I don't think I tested it with the tracking budget, so it might do the same thing

**Comment by psybers** [comment]
I'm not looking for a way to fix this single month in my own budget. As I mentioned, it is *only* November that has this problem. December seems to copy just fine.  I can just manually copy over the values for a single month.

I'm just trying to figure out what the bug is so we can fix it, in case it occurs more frequently later on.

**Comment by youngcw** [comment]
can you try #3694 and see if it fixes your issue?

**Comment by psybers** [comment]
@youngcw Bingo, that fixed it. Nice job!
