### ISSUE TITLE
[Bug]: Upcoming scheduled transfers missing payee

### ISSUE THREAD

**Issue by matt-fidd** [actualbudget/actual#3692]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

![image](https://github.com/user-attachments/assets/e245be1e-d7a0-4125-883b-8fbf5d84b40d)

Reproducable on edge too, test budget below:
[2024-10-19-My Finances.zip](https://github.com/user-attachments/files/17447052/2024-10-19-My.Finances.zip)

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by matt-fidd** [comment]
First is expected behaviour (seen on v24.10.1), second in dark mode is edge behaviour.


https://github.com/user-attachments/assets/8ffc8854-5249-449c-8771-3a8895cb4f7e

**Comment by matt-fidd** [comment]
First is expected behaviour (seen on v24.10.1), second in dark mode is edge behaviour.


https://github.com/user-attachments/assets/3c9abe17-b79b-42a0-ae52-9bd3ab422923

**Comment by youngcw** [comment]
I think #3619 is the source of this bug
