### ISSUE TITLE
[Feature] Ability to split transfer transactions

### ISSUE THREAD

**Issue by irandamay** [actualbudget/actual#370]
It's not immediately obvious if you want to create a new split transfer that you need to choose to split the transaction first before you enter the payee/transfer.  Once you choose the transfer account as the payee, it's then locked into being a single transfer transaction, even though the category field can be selected like it can be changed.

**Comment by rich-howell** [comment]
There was some confusion with this issue, I moved it to documentation as I thought it needed explaining better on how something worked, then tagged the wrong issue when resolving a docs PR. 

Spoke to @irandamay who confirmed this should be more of a "you should be able to change it and you can't" type thing. 

Raising as a bug.

**Comment by MatissJanis** [comment]
:wave: I would consider this more of a feature request than a bug. So I'll label it as such and lets see if we can get more support from the community to get this implemented.
