### ISSUE TITLE
[Bug]: Sync is not working with Gocardless - two accounts in one bank account, Unhandled Promise Rejection: [object Object]

### ISSUE THREAD

**Issue by thelastoth** [actualbudget/actual#3700]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I have a debit and credit account in my bank and while credit account seems to be synced just fine, I can not get my debit account synced, although Actual offer to sync both account, when I'm trying to sync the debit one, I keep getting an error without any specific error message. I found in the development window: Unhandled Promise Rejection: [object Object]

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge

### Operating System

Mac OSX

**Comment by thelastoth** [comment]
Here is what I catch in browsers dev console: <img width="531" alt="Screenshot 2024-10-23 at 7 40 29" src="https://github.com/user-attachments/assets/456a5ad8-40db-4a1f-aad3-92740ee2959b">

**Comment by matt-fidd** [comment]
Closing as helping in Discord
