### ISSUE TITLE
[Bug]: Bulk Edit Fields with Split transactions affect the whole Split transaction

### ISSUE THREAD

**Issue by shall0pass** [actualbudget/actual#371]
### Verified issue does not already exist?

I have searched and found no existing issue

### What happened?

If one of the splits in the split transaction is selected and the Edit Field actions are used, every transaction in the split transaction is affected even if they are not selected.  I expect only the selected transactions within a split to be affect for notes, category, or payment fields since those can be unique to the transaction.

![bug_report_selectAll_category2](https://user-images.githubusercontent.com/20625555/197346698-aa46a781-b94c-4b31-8f5d-3fa323f023be.png)

![bug_report_selectAll_category3](https://user-images.githubusercontent.com/20625555/197346703-a6e431a7-7e3c-4a46-a3aa-9020942685bb.png)

![bug_report_selectAll_category4](https://user-images.githubusercontent.com/20625555/197346705-81879bd0-4fc8-47bf-8076-1928d13c5658.png)

Edit:  Moved "select all" when filtering to another bug report.  https://github.com/actualbudget/actual/issues/381

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Other

**Comment by yoyotogblo** [comment]
Shouldn't these be 2 separate bugs? I noticed the first one because I use that quite a bit in YNAB 4.

**Comment by shall0pass** [comment]
> Shouldn't these be 2 separate bugs? I noticed the first one because I use that quite a bit in YNAB 4.

Yes.  You're probably right.  I'll split them.

**Comment by j-f1** [comment]
I believe this was fixed by #383. If you’re still experiencing this issue, let us know and we’ll reopen!
