### ISSUE TITLE
[Feature] Frequency modifier for `up to` targets

### ISSUE THREAD

**Issue by ColinHebert** [actualbudget/actual#3711]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I am trying to replicate a behaviour of YNAB that allows doing a `refill budget by $x weekly`.

This would, for example, allow you to set a budget for, say, "eating out" over a month based on the number of weeks and re-fill the budget based on the number of weeks in the month.

### Describe your ideal solution to this problem

Currently `up to` is only working "monthly" (implied), I'm wondering whether it'd be possible to have an explicit frequency set:

- `#feature up to $3 daily` (which would be the equivalent to `#feature up to $84` in February or `#feature up to $93` in August)
- `#feature up to $50 weekly` (which would be the equivalent to `#feature up to $200` in a month with 4 weeks or `#feature up to $250` in a month with 5 weeks)
- `#feature up to $100 [monthly]`

In terms of implementation, I'm not sure it'd make sense to have frequency for longer periods of time than monthly.

**Comment by youngcw** [comment]
How would you suggest determining if there are 5 weeks or just 4 in a month?  The other templates count weeks from a starting day.

**Comment by ColinHebert** [comment]
That's a really good point.

Maybe for weekly the wording should be `weekly on Monday` which would allow to count the number of Mondays in the month.

I'm not sure what a sensible default would be if we wanted just `weekly`, it could either be the weekday of the first day of the month (I don't know if this would have any strong side effects) or a default to Sunday (I'm not American but ultimately when we count the number of weeks, Sunday is just as good as any other day). Alternatively no sensible default could work as well but I think it's a worse option.

**Comment by youngcw** [comment]
@ColinHebert Can you try #3714 and see if it is everything you hoped for?

**Comment by Teprifer** [comment]
I like `weekly on Monday` type as it allows for weeklies that are on different days.

**Comment by ColinHebert** [comment]
Tested and it indeed fixes this. Nicely done @youngcw !
