### ISSUE TITLE
[Bug]: Add transaction page displays when it shouldnt

### ISSUE THREAD

**Issue by deathblade666** [actualbudget/actual#3712]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

on Mobile, specifically im seeing this on Android using Firefox (havent tested other browsers yet), after adding a transaction (inacted via the nav bar) it'll bring you to the account page of which you added the transaction against which makes sense. However if at this point you press the back button (top left) it brings the add transaction screen back up instead of going to the all accounts page. This is on the most current Edge release (updated last night at 1am Est). per others in the discord this is not an issue in the current stable release.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Mobile Device

**Comment by shall0pass** [comment]
This exists in 24.11.0 too.

**Comment by JukeboxRhino** [comment]
I'm also seeing this issue

**Comment by deathblade666** [comment]
It appears this "loop" will happened for each transaction entered. if you enter 3 transactions it'll loop back and forth 3 times. I have not tested against adding transactions across several accounts though. only with a single account.

**Comment by deathblade666** [comment]
So just tried the fix out running the edge build from last night (11/16/24). It seems that the issue isn't quite fixed in its entirety, while it no longer brings up the add transaction page anymore, you do still need to press the back button for each transaction you just added (need to add 2 or more transactions)
