### ISSUE TITLE
[Bug]: Cant enable templates

### ISSUE THREAD

**Issue by youngcw** [actualbudget/actual#3715]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Open a fresh test on edge, then enable goal templates in the settings.  Page crashes.

I think this is because of the new goals help page. @jfdoming @deathblade666 

### Where are you hosting Actual?

None

### Operating System

None

**Comment by jfdoming** [comment]
Yep, it was a merge race. Already got a PR out [here](https://github.com/actualbudget/actual/pull/3713), just waiting for a review

**Comment by matt-fidd** [comment]
Fixed with #3713
