### ISSUE TITLE
[Bug]: Type check error on newly merged branch

### ISSUE THREAD

**Issue by tlesicka** [actualbudget/actual#3716]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

The newly merged branch #3699 has a type check error in HelpMenu.tsx:93:38.  This error creates a type check fail when it is merged into new PRs.

To duplicate, merge current master branch into an existing PR and the PR will fail type check.

### Where are you hosting Actual?

None

### Operating System

None

**Comment by Teprifer** [comment]
@tlesicka  Sounds like #3713

**Comment by tlesicka** [comment]
Oops, sorry.  I checked the Issues, but didn't check the PRs.  I'll close this issue.
