### ISSUE TITLE
[Bug]: payees overlaying notes

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#3719]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

<img width="400" alt="Screenshot 2024-10-23 at 18 11 49" src="https://github.com/user-attachments/assets/64e95b27-7171-4022-823c-2c5be2ad769e">

Longer payee names are overlaying notes in the transaction table. We used to have ellipsis for long payee names.

### Where are you hosting Actual?

None

### Operating System

None

**Comment by Dreptschar** [comment]
I've tried to reproduce it but couldn't do so

**Comment by JahJoey** [comment]
Also have not been able to reproduce this issue.

**Comment by MatissJanis** [comment]
Budget file for easy reproduction:
[2024-10-26-My Finances 1.zip](https://github.com/user-attachments/files/17531624/2024-10-26-My.Finances.1.zip)

**Comment by JahJoey** [comment]
I see now that that this looks like it's only an issue when the payee displayed is the "Imported Payee". If you made another transaction but selected the same payee from the dropdown list it doesn't reproduce the same.

I plan on giving this a look later today/this week and attempting to find a solution for it.
