### ISSUE TITLE
[Feature] Tracking budget should treat Savings and Investments differently

### ISSUE THREAD

**Issue by valeriocost** [actualbudget/actual#3726]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

In the Budget section, each categories balanced is colored in red if it exceeds the budget and white otherwise.
For Savings and Investments, however, the logic should be inverse. If I "spent" more in these categories I should be rewarded (green color?) and if I spent less the color should be red.

Moreover, I would exclude those transactions from the Expenses pie chart at the top.

### Describe your ideal solution to this problem

Add a property to a category (or group of categories) with the inverse logic.

**Comment by rodrigost23** [comment]
I would love this. Is there any workaround for now?

**Comment by RonanPresle** [comment]
> I would love this. Is there any workaround for now?

You can use a Formula Card (experimental) for now and set the color green!

**Comment by enoordam** [comment]
The best workaround I have found was to set the investments and savings category as hidden. Once you do that, it works mostly as you'd like for expense tracking.
