### ISSUE TITLE
[Feature] Configuration option to disable new version notification

### ISSUE THREAD

**Issue by ancoron** [actualbudget/actual#3727]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I do manage the update of services/apps in one place, so I get notified of new releases outside of Actual.

Therefore, I never want to see the new version notification in the web UI.

In addition, I don't want the application (neither client nor server) to attempt a remote connection to any API outside of the server that I host myself.

### Describe your ideal solution to this problem

Since I am running a container and access it through browser, the solution ideally allows me to simply specify an environment variable for the container.

**Comment by MikesGlitch** [comment]
Thanks for the feedback. 

This should prevent the update notification showing up https://github.com/actualbudget/actual/pull/5725

It will also prevent the app from attempting an API call to get the latest version
