### ISSUE TITLE
[Bug]: Reports cards are showing the wrong months in the dashboard

### ISSUE THREAD

**Issue by youngcw** [actualbudget/actual#3733]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

All reports that list a month or month range in their cards are off by one.  Opening the report list the correct months.
![image](https://github.com/user-attachments/assets/51e3d93a-4985-4746-a49e-8b9911932b07)
Default report, taken in October

Inside the report
![image](https://github.com/user-attachments/assets/1c199e55-437b-44df-9d60-7235a003eb21)

### Where are you hosting Actual?

None

### Operating System

None

**Comment by carkom** [comment]
I know we've discussed this before and we even had a PR merged at one point to fix it (#3295). 

What browser is it? My cards are fine on Windows - Firefox. However, if I check the same server with the same budget on Windows - Chrome, I experience the issue you show above. Is this something wrong with the browser in some way?

**Comment by carkom** [comment]
I did some digging. Chrome is in explicably subtracting 7 hours when we parse the date using `new Date(date)` which is giving us the day before. So 2024-10-01 becomes 2024-09-30. I'll put in a fix for it.
