### ISSUE TITLE
[Bug]: Category overspend is ignored in the cummulative overspend for the month

### ISSUE THREAD

**Issue by mbrijun** [actualbudget/actual#3740]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

One of my categories is in the red, meaning that I have spent more than I have budgeted for that category. Despite this, the field "Overspent in Sep" shows "-0.00". As far as I understand, this is incorrect.

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Firefox
Edge

### Operating System

Windows 11

**Comment by youngcw** [comment]
Is the overspending in october or september?  The overspending will show up in the next months header not the current month

**Comment by mbrijun** [comment]
@youngcw - thank you, I see your point now. I got confused between months (facepalm).
