### ISSUE TITLE
[Bug]: 404 link to the open source version

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [actualbudget/actual#3742]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

On this page: https://actualbudget.com/ the link whose string is "open-sourced it" points to http://open-source.actualbudget.com/ which is a 404. I think it's probably supposed to point to https://actualbudget.org/ ?

### Where are you hosting Actual?

None

### Operating System

None

**Comment by matt-fidd** [comment]
The actualbudget.com website is not managed by us, however the more recent link added at the top of the website does point correctly to actualbudget.org. I believe the other URL is probably an old one.
