### ISSUE TITLE
[Bug]: Wrong documentation regarding the gocardless setup

### ISSUE THREAD

**Issue by informancer** [actualbudget/actual#3743]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

When trying to setup the gocardless connection according to https://actualbudget.org/docs/advanced/bank-sync/gocardless/, I was unable to setup the connection because the Developper menu on the left only has the options "Developpers" and "Events", no "Developper Secrets":

![image](https://github.com/user-attachments/assets/2eee8fcf-1712-4051-9321-cfac3f8e140a)

One can create API Tokens, but it only contains a token and no Secret ID or Secret Key as in the screenshot:

![image](https://github.com/user-attachments/assets/d59c8f12-f70f-49e7-ab5e-3e0d9e1ccfbf)

As such, the setup steps in the documentation cannot be followed.

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

**Comment by matt-fidd** [comment]
It looks like you've created an account with the wrong side of GoCardless, you'll need to follow the link in the documentation to set up an account with the bank account data side. 

https://bankaccountdata.gocardless.com/overview/
