### ISSUE TITLE
[Feature] Show Template/Goal Funding Amounts in Mobile

### ISSUE THREAD

**Issue by RahulShagri** [actualbudget/actual#3746]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Currently, the goals and templates tooltip is only shown on the webapp when hovering over the balance of a particular category. This info is not available to view anywhere on the mobile version of the webapp.

![Screenshot 2024-10-27 230025](https://github.com/user-attachments/assets/dbc21fd0-cda4-4f0d-b619-d438ffb9654f)

### Describe your ideal solution to this problem

Add the goals and template info in the balance menu that pops up when tapping the balance of a particular category on mobile.

![Screenshot_20241027_230416_Chrome](https://github.com/user-attachments/assets/5eb482e1-655f-41e4-afe5-a94d1f809a36)

### Teaching and learning

It's very straightforward. Just adding more info to a window that is already used very often.

**Comment by youngcw** [comment]
This has been added

![Image](https://github.com/user-attachments/assets/97e8d7f6-73da-4bc6-be04-bf6da199899d)
