### ISSUE TITLE
[Bug]: Minor error on Report settings

### ISSUE THREAD

**Issue by tcpr1** [actualbudget/actual#375]
### Verified issue does not already exist?

I have searched and found no existing issue

### What happened?

When you go to Reports, open the Net Worth graph and select "1 year", it sets the graph to 13 months (example: october/21 to october/22).

### Where are you hosting Actual?

Docker

### Operating System

Linux

**Comment by rich-howell** [comment]
Hey @tcpr1 

Thanks for raising this issue, not sure I follow here, Is Oct22-Oct23 not 12 months? 

Have I misunderstood? 

![image](https://user-images.githubusercontent.com/22135084/198713267-30758408-cc4e-468a-b9ea-92437a3c6b8c.png)

**Comment by tcpr1** [comment]
Hello Rich,

You are correct if you count as you did, counting day by day, but in this
particular case, on Actual, we use the full month and it is going from
month Oct21(included) to Oct22(included), which is 13 months long. Should
be Nov21 to Oct22.


Em sex., 28 de out. de 2022 16:06, Rich Howell ***@***.***>
escreveu:

**Comment by rich-howell** [comment]
@tcpr1 thanks for the clarification. I will mark this as a bug.

**Comment by winklevos** [comment]
This issue will likely be resolved in my overhaul of the reporting filters. 
[Working branch](https://github.com/winklevos/actual/tree/reports-overhall-parent)
