### ISSUE TITLE
[Feature] Sort field in Custom Reports (particularly data table views) 

### ISSUE THREAD

**Issue by b-neufeld** [actualbudget/actual#3750]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I've built a handful of Custom Reports (great feature, love it!) but one missing feature is sort fields on the columns. 

The report where this is most attractive is my "Expenses by Payee" where I'm curious to see the biggest individual payees. At present, this list cannot be sorted (to my knowledge), so it's a lot of scrolling to drill down to the insights of top payees. 

![image](https://github.com/user-attachments/assets/1a6e76ef-2ef9-47cf-8f75-46d22d16e1dd)

### Describe your ideal solution to this problem

1. I think the most intuitive solution would be having little up/down arrows appear beside the column headers, which can be clicked to trigger ascending/descending sorts on the selected column. This feels fairly standard in UI. 
2. Another idea might be having a sort order fly-out menu in the existing filter drop-down. I have only been using Actual for less than a year but I could potentially see cases where multiple levels of sort might be desired for certain reports (e.g. first by category, then by payee). 

### Teaching and learning

Option #1 I described above would be the most intuitive and require the least documentation, in my opinion.

**Comment by matt-fidd** [comment]
This was added in https://github.com/actualbudget/actual/pull/4141
