### ISSUE TITLE
[Bug]: Automatic rule for categorizing transactions is not working

### ISSUE THREAD

**Issue by kerhbal** [actualbudget/actual#3760]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

So according to doc https://actualbudget.org/docs/budgeting/rules/#automatic-rules
> Actual also creates/updates rules for categorizing transactions. When you categorize a transaction, it will determine the best category for a transaction (basically the most common one) and create a rule that sets the category for the payee. If a rule already exists for the payee, it updates the category to set.

But after playing with it for a couple days, I find out that it did not automatically create rule when I categorized transactions.
Steps to reproduce:
1. import csv from bank
2. change category manually
3. check if there is any rule auto-created for this payee
Thanks

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome, Safari

### Operating System

Mac OSX

**Comment by youngcw** [comment]
Have you set the same payee to the same category multiple times?  It wont make a rule unless you do the same thing a few times

**Comment by kerhbal** [comment]
@youngcw thanks for the lightning comment. No I probably didn't do multiple times for the same payee as I was also trying to create my own rules at the same time.
I tried again with some test samples and it worked! It created rule at around 3rd/4th categorizing
Will close the issue. Though it will be even better if there is a frontend msg to tell user a rule has just been created.
