### ISSUE TITLE
[Bug]: Payees can no longer be renamed from payee page

### ISSUE THREAD

**Issue by matt-fidd** [actualbudget/actual#3767]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Regression, only seen on edge

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by matt-fidd** [comment]
Looks like it could have been https://github.com/actualbudget/actual/pull/3507

**Comment by jfdoming** [comment]
Fixed by #3768
