### ISSUE TITLE
[Feature] support filtering transactions view by category group

### ISSUE THREAD

**Issue by olets** [actualbudget/actual#3791]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Would like to be able to easily filter transactions to just those in a category group.

Currently, have to add multiple "category" filters.

### Describe your ideal solution to this problem

Two ideas:

- Add a category group filter to the filter dropdown. Would list all category groups and would filter to show transactions in any category in that group.
- Or allow choosing category groups in the category filter. Currently, clicking on a group name does nothing.
  - Clicking on a group name could add filters for every category in the group
  - Or clicking on a group name could add one filter, for the group

**Comment by Rick-Thomas** [comment]
I agree...   Category Group is an **esencial** part of AB, but only to give the Budget some order...   Then it is totally ignored...  It is not part of the .csv import or export process, I cannot filter by it, etc...   The only place I've seen it as an option on its own, selectable, is in the Custom Report...
