### ISSUE TITLE
[Bug]: Probleme d'affichage

### ISSUE THREAD

**Issue by gael1980** [actualbudget/actual#3795]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Bonjour,

Depuis la dernière mise à jour, un bug d'affichage est apparu : les colonnes se chevauchent, ce qui les rend illisibles. J'ai essayé de vider le cache des navigateurs, mais cela n'a pas résolu le problème.

Avez-vous une solution pour résoudre ce problème ?
Merci

![image](https://github.com/user-attachments/assets/a4291c2b-5cc1-49b7-b904-880f570f6e38)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge, Other

### Operating System

Windows 10

**Comment by Teprifer** [comment]
#3719 

-> #3753 

Google Traduction. Corrigé pour la version de décembre.

**Comment by gael1980** [comment]
Merci
