### ISSUE TITLE
[Bug]: Text in Budget View No Longer Wraps, instead spills and overlaps between columns

### ISSUE THREAD

**Issue by pcchristie** [actualbudget/actual#3807]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

In budget view, long Payee text will no longer truncate and "cut off" before the Notes column if Notes is used.

v24.11.0, Windows Store version on Win 11

![image](https://github.com/user-attachments/assets/0f352138-88e0-46d2-ad4c-3c73edad09e7)

### Where are you hosting Actual?

Desktop App (Electron)

### What browsers are you seeing the problem on?

Desktop App (Electron)

### Operating System

Windows 11

**Comment by Teprifer** [comment]
#3719 

=> #3753 

Fixed for the next release.
