### ISSUE TITLE
Migrate from Personal Capital or Mint. 

### ISSUE THREAD

**Issue by Rathna-K** [actualbudget/actual#3809]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Hi, just found this app from a social media post. Interested in trying it out as I see it also connects to banks. Does it let you migrate / download historical transactions after connecting the bank account from mint or personal capital? 

I tried to post this question in discord general chat or support. Both gave me this message and wouldn’t post my message there. 
Clyde bot: Your message could not be delivered because you don't share a server with the recipient or you disabled direct messages on your shared server, recipient is only accepting direct messages from friends, or you were blocked by the recipient. 

### Describe your ideal solution to this problem

Looking for guidance.

**Comment by Rathna-K** [comment]
anyone ? @MatissJanis  maybe ?

**Comment by youngcw** [comment]
You should ask on discord instead of opening a feature request.  I don't know how personal capital exports its data.  Mint is long dead, do you still have data from that?  There is a 3rd party mint importer you can use.  You can always import transactions via csv.

**Comment by Rathna-K** [comment]
I tried sending message in discord but please see my above message on that. 
Personal capital, you can export as csv. here is a sample row (including Header row):  
Date	Account	Description	Category	Tags	Amount
11/10/2000	Citbank - Ending in 0123	Autozone	Automotive		-10.00

**Comment by youngcw** [comment]
You can make lots of csv formats work.  There are lots of settings to get it right.  It seems like you didn't actually join the discord if it gave you issues.
