### ISSUE TITLE
[Bug]: Payee names overflow into other columns

### ISSUE THREAD

**Issue by NikxDa** [actualbudget/actual#3813]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

In the latest version (24.11.0), payee names clip into the next columns.

![CleanShot 2024-11-10 at 02 43 49@2x](https://github.com/user-attachments/assets/ac173e5e-eb68-41ef-aa2e-aff6183840f0)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by Teprifer** [comment]
#3719 

=> #3753 

Fixed for the next release.
