### ISSUE TITLE
[Feature] Group accounts into arbitrary categories

### ISSUE THREAD

**Issue by Felixre7** [actualbudget/actual#3819]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

It would be super helpful when looking at the account balances on the left bar to be able to group them somehow. Then have sub totals of the grouped account's current balances displayed.

### Describe your ideal solution to this problem

Ideally sub headers under "for budget" where you could create categories like "credit cards", "checking", "saving", etc. Makes it easier to scan over the currently linked accounts to see where your money is currently located.

**Comment by Felixre7** [comment]
This is a duplicate of an already created issue, please delete it! sorry for not finding that other one sooner!

**Comment by youngcw** [comment]
duplicate of #1683
