### ISSUE TITLE
[Bug]: iOS app doesn't build

### ISSUE THREAD

**Issue by fivestones** [actualbudget/actual#382]
### Verified issue does not already exist?

I have searched and found no existing issue

### What happened?

I understand that the iOS app is not supported. I understand that someone here is working on a responsive web app. I understand that this will work much better for 99% of people who are wanting to just use actual and who are selfhosting the server.

But,

Some of us (or at least me) want to learn how to make offline-first apps for iOS and see an actual working product that we can then mess around with and use as a base to make other offline-first apps. And along the way, if I happened to be able to use actual as an app on my iPhone, that would be great too.

So, I'm not asking for support for a non-supported feature. But there are missing files in the iOS/xcode project, and it so doesn't build. Is there some chance these files could be added to the open source repository? Or that some pointer could be given as to how to get it to build?

I'm happy to hack away at it on my own, but I don't know enough about iOS development to get it to work without the missing files--or maybe I'm just missing something and that's why it won't build.

Has anyone else gotten the iOS app to build?

Thanks!

**Comment by MatissJanis** [comment]
👋 Sadly we won't be able to provide these files. The react native mobile apps have been fully deprecated now.

However, if you'd like to work on improving the responsive mobile version we have available in the latest release: I'll be more than happy to review your PRs!
