### ISSUE TITLE
[Bug]: Stacked by templates don't function properly

### ISSUE THREAD

**Issue by mbrijun** [actualbudget/actual#3834]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I am testing a template (shown at the botton of the post), consisting of multiple one-off goals. This is what it manages to budget:

```
Nov = 950.00 (total: 950.00)
Dec = 808.33 (total: 1758.33)
Jan = 704.17 (total: 2462.50)
Feb = 179.17 (total: 2641.67)
Mar = 0.00 (total: 2641.67)
Apr = 0.00 (total: 2641.67)
```

As we can see, instead of saving 4000 by April, we have managed to save only 2641.67. It is important to note that none of the money has been "spent" in this simulation.

```
#template 1000 by 2025-01
#template 1000 by 2025-02
#template 1000 by 2025-03
#template 1000 by 2025-04
```

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 11

**Comment by youngcw** [comment]
Your issue is that there aren't charges in the expected months, so the templates think you are good since there is enough money in the time its needed.  If you add in the 1000 charge in each of the months you said you need it the template works right.

**Comment by mbrijun** [comment]
> Your issue is that there aren't charges in the expected months, so the templates think you are good since there is enough money in the time its needed. If you add in the 1000 charge in each of the months you said you need it, the template works right.

@youngcw - thank you very much for looking into this issue.

While I fully understand there are other opinions, in my view this behaviour is unintuitive at best, and dangerous at worst. What if the circumstances have changed and instead of spending 1000 in Jan, 1000 in Feb and 1000 in March, I now need to make a single payment of 3000 in March? I would be short, as only 2641.67 is in that envelope. On the other hand, I would not have any shortfall if I was using 4 individual savings goals, each with their own template.

**Comment by youngcw** [comment]
If your goals change wouldn't you then need to change the template to match?  The primary issue at hand is that the template only has so much information to go off of.  It doesn't know that your spend date changed and can only assume that the balance going forward is available to the remaining templates.
