### ISSUE TITLE
[Feature] Bluecoins importer

### ISSUE THREAD

**Issue by Nehemoth** [actualbudget/actual#3836]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I'm using an app called Bluecoins, I would like to migrate to Actual budget, I would like to import my data from Bluecoins to actual budget

### Describe your ideal solution to this problem

The ideal solution would be an option inside Actualbudget to import a Bluecoins backup file.
Also, there's a python script that it's intended to import Bluecoins data to Firefly III, maybe it can be modify for Actualbudget
[https://github.com/dreautall/bluecoins-to-fireflyiii](https://github.com/actualbudget/actual/issues/url)

### Teaching and learning

Would be an option for actual Bluecoins users to migrate to a better platform

**Comment by youngcw** [comment]
duplicate of #3835
