### ISSUE TITLE
[Feature] Configurable GoCardLess imports

### ISSUE THREAD

**Issue by gael-vanderlee** [actualbudget/actual#3838]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

When importing data from GoCardLess, Actual does a great job determining which data belongs in which columns. However, I've noticed that some banks, including mine, do not format their data consistently. This can lead to messy imports. For example, my bank also places the payee information in the "Note" section, resulting in duplicated columns.

### Describe your ideal solution to this problem

1. A menu to modify how the data is imported through GoCardLess, in a similar way to the menu that is shown when importing files.

### Teaching and learning

Same discoverability and documentation as provided for the file import.

**Comment by matt-fidd** [comment]
This can be achieved, although not with a UI, with custom bank importers https://github.com/actualbudget/actual-server/tree/master/src/app-gocardless/banks.

Will leave this open though as a UI for it sounds like a cool idea!
