### ISSUE TITLE
RFC: account notes (accepted)

### ISSUE THREAD

**Issue by jlongster** [actualbudget/actual#384]
### Discussed in https://github.com/actualbudget/actual/discussions/374

<div type='discussions-op-text'>

<sup>Originally posted by **MatissJanis** October 24, 2022</sup>
# Description
YNAB has a nifty feature where you can add notes to accounts. This allows to add certain tags to accounts and then add programatic functionality to them. For example: [automatic investment account update](https://github.com/MatissJanis/sls-ynab-stock-updates).

This proposal is to add `notes` to accounts so that similar functionality could also be achieved in Actual.

# Backend

The existing backend API would be used for the notes: the `notes` table.

# UI

Here is a demo of the proposed UI:
![Kapture_2022-10-06_at_20 44 50](https://user-images.githubusercontent.com/886567/197610439-fa4994ba-03a7-4ba0-ba21-13d9956bfbb8.gif)
.. it might take a second to load due to gif filesize. [direct link](https://user-images.githubusercontent.com/886567/197610439-fa4994ba-03a7-4ba0-ba21-13d9956bfbb8.gif) ..

# Parting thoughts

Please let me know what you think. If you are happy with the proposal and the UI, I'll gladly prepare a PR and send it over.</div>

**Comment by MatissJanis** [comment]
Done: https://github.com/actualbudget/actual/pull/385
