### ISSUE TITLE
[Feature] Add an option to choose default Account when creating a new transaction

### ISSUE THREAD

**Issue by hrv231** [actualbudget/actual#3843]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Less steps, faster input when creating new transactions

Every time I'm outside buying something and take my phone to add a new transaction, I have to choose the Payee, Category and Account.
I would like a way to choose a default Account and possibly also a default Category to do this process faster.

If my new transactions are generally the same category ( ex: Groceries ) and the Account I use to pay almost everything is one specific credit card, then I would like that to appear by default, saving me time and steps.
That way, I will need to input only two things, the Amount and Payee, in most cases.

### Describe your ideal solution to this problem

- A way for the user to choose a default account or default credit card under the "For budget" to visually see it
or
- A way for the user to choose a default account or default credit card in the settings

At the same time, the system needs to have a way to check that only 1 default Account is used and alert/deny the user in case the user tries to have another Account to be the default

### Teaching and learning

When creating a new Account , having an option to choose it as your default.
or
By Editing one of your Accounts, having an option to choose it as a default.

**Comment by janssenvdh** [comment]
This can be done by setting up a rule and specific instructions are [in the documents](https://actualbudget.org/docs/budgeting/rules/custom#q-how-do-i-set-a-default-account-when-i-add-transactions). It works perfectly for me.
