### ISSUE TITLE
[Bug]: Payee Field Overlapping with Notes

### ISSUE THREAD

**Issue by stevenjson** [actualbudget/actual#3845]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

For a couple versions now, payee names have been overlapping with other columns when the text gets too long, instead of being cropped.

<img width="631" alt="image" src="https://github.com/user-attachments/assets/fd63a034-35a8-4f6c-9c29-a53fdf98fbe4">

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Firefox

### Operating System

Mac OSX

**Comment by Teprifer** [comment]
#3719

=> #3753

Fixed for the next release.
