### ISSUE TITLE
[Bug]: Category Labels Not Scaling Correctly On Small Screen

### ISSUE THREAD

**Issue by fahnestd** [actualbudget/actual#3849]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

On smaller screen sizes, the category background tags do not scale correctly with the container. 
![image](https://github.com/user-attachments/assets/e395d9c8-2ae6-408c-a23b-57f71129d08e)
The missed categories are only filling part of the expected container size.

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by annechoww** [comment]
Hi @joel-jeremy  and @fahnestd, could I help with this issue? It is my first time contributing to open-source so this seems like a great project to start with!

**Comment by joel-jeremy** [comment]
> Hi @joel-jeremy and @fahnestd, could I help with this issue? It is my first time contributing to open-source so this seems like a great project to start with!

Please feel free to open up a PR and we'll review :)
