### ISSUE TITLE
[Bug]: Menu Option Disappears Completely On Certain Screen Size

### ISSUE THREAD

**Issue by fahnestd** [actualbudget/actual#3850]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

On Screens of width in the range of roughly 668px - 750px wide, the menu dropdown on the account view page dissapears visually, leaving no way clicking unless you find it by hovering over it.
The menu missing from the right side:
<img width="467" alt="image" src="https://github.com/user-attachments/assets/7fd6d255-3087-4b52-8643-a33c07f8715f">

The menu seen by hovering:
<img width="474" alt="image" src="https://github.com/user-attachments/assets/4a153eac-1718-4f14-9c7b-f80fc56ecbc4">

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by ericji1326** [comment]
Hey, can I try tackling this issue?

**Comment by ericji1326** [comment]
Hey @fahnestd, can you elaborate on this issue?

**Comment by ericji1326** [comment]
Hey! I'm going to give this issue a go!
