### ISSUE TITLE
[Bug]: Cash Flow report not including transfers on widget

### ISSUE THREAD

**Issue by cantrol** [actualbudget/actual#3852]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I am looking into reports section and wanted to raise a question:
When in main screen with widgets, Cash Flow widget reports income and expenses, showing change in balance.
However, when going into details, it starts to include transfers and then the balance is different.

Checking transfers details I can see they match my installments which I pay to my debt. This is because I have set all my debt as off-budget accounts, so payments are categorized in budget but seen as transfers in terms of payees.

Can we change this so the cash flow will also reflect transfers on the widget?
![obraz](https://github.com/user-attachments/assets/9425fb3d-634c-4e38-b0df-fcd85ee3ce90)
![obraz](https://github.com/user-attachments/assets/99788f38-78d2-4fcf-a405-320fccb7da38)

### Where are you hosting Actual?

NAS

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Windows 10

**Comment by jsehnoutka** [comment]
I am pretty sure this is intended behaviour. I remember a PR from months ago which established this. I can't find it though, sorry :(

**Comment by youngcw** [comment]
I think this is what you are looking for
https://github.com/actualbudget/actual/pull/2485

**Comment by cantrol** [comment]
> I think this is what you are looking for #2485

Yes, that's it. Thank you for sharing this.
However, as said in my original post, this is strange behavior as I am keeping my debt accounts as off-budget, and they are categorized against budget. So maybe it would be possible to make a trigger for user to choose if transfers are to be included in expense report or not?
