### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by soloam** [actualbudget/actual#3858]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

When I make a budget to a schedule, It's implied that it should be respected, it's bill... If not payed this month, I will need to pay it next month! So in the next month the budget should be the month template, plus the unmet bill from the previews month.

### Describe your ideal solution to this problem

Exemple:

Bills Category: 
`
#template schedule Gas Bill
#template schedule Light Bill
`

Schedules:
Gas Bill: 50
Light Bill: 100

October:

Bills Category Budget: 150
Payed 100

November  

Bills Category Budget: 150 + 50 (From October)

To avoid breaking changes, we could add a "important" tag for exemple to the template to say that the template MUST be met, or it will be added to the budget in the next month

**Comment by matt-fidd** [comment]
The rollover should take care of this for you already - there will be 50 remaining in the bills category that will be rolled over to the next month.

Month 1 (none paid):
![image](https://github.com/user-attachments/assets/3ea15fb3-7ab2-4201-9273-2d5ea96fac1c)

Month 2 - shows 200 budgeted:
![image](https://github.com/user-attachments/assets/79e02174-0e89-4079-a4ea-c4057e2cd3e6)

**Comment by soloam** [comment]
I see my problem... I think this is not a Feature But a Bug... Look at my exemple:

I have a bill that only applies to December, so I have this template:

#template schedule Bill Month
#template schedule full Bill December

this is my November:
![image](https://github.com/user-attachments/assets/fe6c3b38-c2f5-4c76-a0af-629f32a3bd42)

Both Bills are 12 Euros.

In December the template should generate 24.

When I start December I see this:
![image](https://github.com/user-attachments/assets/a596d478-04dd-4865-9779-5c4bcaf41b69)

The 12 Euros ate there from November... But when I generate the template:
![image](https://github.com/user-attachments/assets/6a51165b-3c85-46ac-8b91-7988d88463a6)

It only generates the amount to fill 24...

![image](https://github.com/user-attachments/assets/a9a8743c-8ce6-456f-b20e-f2c9c2c86e51)

**Comment by matt-fidd** [comment]
@youngcw - could you have a look at this please? I'm not sure on the inner workings of schedule based templates

**Comment by soloam** [comment]
If that's the case it could be a bug! if needed I can fill a bug issue, since this is marked as "Feature" and its closed

**Comment by youngcw** [comment]
Calculating the schedules is really complicated with all the edge cases, so my real recommendation is to not use multiple schedules on top of each other if the schedules don't get auto payed and the months the money comes out isn't consistent.  The other option maybe is to use 'full' on both of them.

**Comment by soloam** [comment]
> Calculating the schedules is really complicated with all the edge cases, so my real recommendation is to not use multiple schedules on top of each other if the schedules don't get auto payed and the months the money comes out isn't consistent. The other option maybe is to use 'full' on both of them.

I tested out with full in both and the result is the same! Not using staked schedules, for me, would not be manageable, I would need a category for each schedule, and I use it in other categories, for exemple Bills, Streaming services etc... All works ok if all is payed on the previews month...The problem is when it fails a payment and is transferred to the next month.

**Comment by soloam** [comment]
Probably that's what I'll end up doing... but that is a "hack" to what end's up on being a bug!

**Comment by soloam** [comment]
> If the schedule is consistent amounts and monthly then you could probably use a `#template 50` kind of thing and stack those.

But now that I think about this... This would not solve the extra bill on December! I would still need to stack the anual template to be processed in December! Because the bill is 12 every month and a extra one in December!

**Comment by soloam** [comment]
Ok I did a extra test and this only seems to be related when you stack a month and a yearly bill! If both schedules are daily or both are yearly... it works ok.

# Test 1
Test1 - Montly 12 Euro In November
Test2 - Montly 12 Euro in December

## November
![image](https://github.com/user-attachments/assets/abd8f319-05a3-4c1a-bf1b-8ae35191b099)
OK

## December
![image](https://github.com/user-attachments/assets/ed664447-c414-4ca9-afc0-e34a7509d183)
Ok

# Test 2

Test1 - Yeatly 12 Euro In November
Test2 - Yearly 12 Euro in December

## November:
![image](https://github.com/user-attachments/assets/d81a8554-c952-479a-b313-5fc8745d1120)
Ok

## December
![image](https://github.com/user-attachments/assets/e98085d4-8b0c-45b0-bb27-ce87c59ded00)
Ok
