### ISSUE TITLE
[Bug]: Sync is broken on iOS when upgrading to 24.11 and files cannot be deleted manually

### ISSUE THREAD

**Issue by mgajdo** [actualbudget/actual#3861]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Sync on iOS Safari does not work after upgrading Docker container to version 24.11. Cannot delete and manually re-add the file either.

Aftetr upgrading my macOS version worked and still does. On my iPhone I received a yellow-label warning that my current version is not up-to-date and that I should upgrade (?). As far as I know I can only upgrade my Docker container (and I did).

To resolve the issue I wanted to reset my setup on iOS. I tried the following: 
- ActualBudget > Settings > Advanced Settings > Reset Budget Cache (on iOS)
- ActualBudget > Settings > Advanced Settings > Reset Sync (on macOS)

This did not help with my issue. As a last resort, I wanted to delete the file on iOS and add it again. I backed up the files on macOS in order to save my current state. Then the following happened:

https://github.com/user-attachments/assets/aab4862e-9b27-4dd5-a0ba-b465fbfbe5fe

In the video you can see two files that cannot be deleted: For verification purposes I tried to add another file. This time the UI did not even show the "Delete" option. 

Summary: On iPhone upgrading to version 24.11. causes issues; A reset by deleting the file is not possible due to faulty UI.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Safari

### Operating System

Mobile Device

**Comment by matt-fidd** [comment]
Your app looks to be on version 24.9, you'll need to update it to use a later version of the server

**Comment by mgajdo** [comment]
Dear Matt,

Many thanks. I did not know there is an iOS app nor did I find any reference to why there might be different versions for the app and the server in the provided documentation. 

I was able to solve the error by deleting shortcut from my homescreen and re-adding it. 
To clarify: I am using the web version. For convenience purposes I added the web app to my home screen. 

Please let me know if I should delete the bug report or if I should add a comment there. 

(I am relatively new to contributing to using Github for collaboration on app development.)

Kind regards,
Martin
