### ISSUE TITLE
[Bug]: Payee if long goes across column

### ISSUE THREAD

**Issue by esseti** [actualbudget/actual#3869]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

When a payee is long (my bank love to use very long names) it's printed in a way that does not respect columns, resulting in overlapping with other columns text.

![image](https://github.com/user-attachments/assets/3962b032-5886-432f-aecd-8efd3c41a503)

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by matt-fidd** [comment]
This has been fixed in edge and will be fixed in the next release
