### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by Treawlony** [actualbudget/actual#3877]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

As probably everyone in the budgeting world is also doing investments, and most likely investments into ETF, I'd like to have an automatic price tracking system where you can add title and amount of the purchased ETF and over time (once a day) fetch the current price and updates the account total

### Describe your ideal solution to this problem

As mentioned above, a system where you can add the Title / ISIN and quantity and fetch the price. You could have a look at how ETF is handled in the Wallet by BudgetBakers

### Teaching and learning

Live price tracking :) I can help in testing and making the documentation

**Comment by JamiesonRoberts** [comment]
@matt-fidd this is probably similar to https://github.com/actualbudget/actual/issues/3698
