### ISSUE TITLE
[Bug]: Length of payee too long to be read

### ISSUE THREAD

**Issue by Vbacquey** [actualbudget/actual#3885]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Hello
In the lastest version (24.11.00), the length of the payee is too long and is overwriting on the notes field either in computer or mobile version. I search any option or bug report but didn't find. I had not this bug with previous version. I'm using GoCardless automatic import maybe it's the point.

### Where are you hosting Actual?

Docker

### Operating System

None

**Comment by youngcw** [comment]
This is already fixed in edge and will be fixed in the next release.

**Comment by Vbacquey** [comment]
I'm using edge and got the issue. Got it in Firefox on PC and on Chrome on android.

Waiting for the update
