### ISSUE TITLE
[Feature] CSV import templates

### ISSUE THREAD

**Issue by QazCetelic** [actualbudget/actual#3886]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

It would be nice to be able to select the bank in the import dialog and automatically apply the right options.

### Describe your ideal solution to this problem

A crowdsourced collection of import templates (just a large JSON file people can write PR's for), perhaps something like this.

```json
{
  ...
  "SNS": {
    "columns": {
      // column can be a number (no header) or name (with header)
      "date": 1,
      "payee": 3,
      "notes": 18,
      "category": null,
      
      // either only the amount (depending on seperate-in-out-column & select-in-out-column)
      "amount": 11,
      // or
      "in": null,
      "out": null,
      // or the amount with
      "is-in": null,
    },
    "date-format": "DD-MM-YYYY",
    "delimiter": ";",
    "skip-lines": 0,
    "has-header-row": false,
    "multiplier": null,
    "flip-amount": false,
    "seperate-in-out-column": false,
    "select-in-out-column": false,
  }
  "ING": {
  ...
}
```

I've also made a mockup:
![mockup](https://github.com/user-attachments/assets/936a26d4-9594-4aa1-b488-b9b60b0bde3b)

I've chosen to go with an apply button so the user can change things if they have a specific import that partially deviates from the default format for some reason (like picking commas as separators instead of semicolons). 

### Teaching and learning

The template button will be featured prominently in the import page as shown in the mockup

**Comment by mcalligator** [comment]
One aspect of this has previously been requested in [[Feature] manual CSV import, ignore top lines (and bottom lines) #2950](https://github.com/actualbudget/actual/issues/2950).  Adding this note to link these two feature requests.
