### ISSUE TITLE
[Bug]: Cannot link N26 account using GoCardless

### ISSUE THREAD

**Issue by zimt28** [actualbudget/actual#3888]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I was able to link a bank account and my PayPal using GoCardless. When I try to sync my N26 account, the following happens:

- I select my country (Germany) and bank (N26)
- GoCardless opens in a new tab and shows a page (N26 Bank, Follow instructions to authenticate yourself: Confirm on your device)
- I confirm on my devide
- The GoCardless page seems to redirect to Actual, the tab closes automatically 
- The "Link Your Bank" modal shows "Success! Click here to continue ->" and I click the button
- The page turns white, the console shows the following errors:
```
[Error] TypeError: undefined is not an object (evaluating 't.sort')
EOe — SelectLinkedAccountsModal.jsx:32
lk — react-dom.production.min.js:167:139
sO — react-dom.production.min.js:290:340
rO — react-dom.production.min.js:280:392
LU — react-dom.production.min.js:280:323
mm — react-dom.production.min.js:280:184
$b — react-dom.production.min.js:271:91
Aj — react-dom.production.min.js:273:303
ka — react-dom.production.min.js:127:107
(anonymous function) — react-dom.production.min.js:267:273

	mb (index.IdL7Qzmn.js:59:167)
	(anonymous function) (index.IdL7Qzmn.js:59:390)
	pj (index.IdL7Qzmn.js:57:9892)
	Dj (index.IdL7Qzmn.js:59:32050)
	J4 (index.IdL7Qzmn.js:59:31469)
	BU (index.IdL7Qzmn.js:59:31019)
	FU (index.IdL7Qzmn.js:59:40910)
	Wa (index.IdL7Qzmn.js:59:40268)
	Aj (index.IdL7Qzmn.js:59:36876)
	ka (index.IdL7Qzmn.js:57:3281)
	(anonymous function) (index.IdL7Qzmn.js:59:34253)

[Error] TypeError: undefined is not an object (evaluating 't.sort')
	ka (index.IdL7Qzmn.js:57:3372)
	(anonymous function) (index.IdL7Qzmn.js:59:34253)
```

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Chrome, Safari

### Operating System

Mac OSX

**Comment by marcosrosse** [comment]
Facing the same issue. I found this message in the log file:
`data: {
        summary: "Couldn't update account details",
        detail: 'Daily request limit set by the Institution has been exceeded.',
        status_code: 429,
        type: 'RateLimitError'
      }`
      
 This was my first ever try.

**Comment by marcosrosse** [comment]
Hi @zimt28, 

Now I'm able to connect my N26 account to ActualActual. If you have directly connected your account to the GoCardless before, make sure to disconnect it and only connect again through the ActualBudget account setup.

**Comment by zimt28** [comment]
@marcosrosse Thanks, I was able to sync the account now, too. Not sure, what the problem was, I haven't done anything differently now :)
