### ISSUE TITLE
[Bug]: Schedule skipping months

### ISSUE THREAD

**Issue by MattFaz** [actualbudget/actual#3890]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

When scheduling a recurring transaction, starting 30 November 2024 and repeating every 3 months it is skipping the February transaction.

Strangely, it works fine when you select 2 months _(correctly shows next transaction in January)_, and it's fine when you select 4 months _(correctly shows next transaction in March)_. Yet when I select 3 months, it shows the next transaction in May _(skipping the February transaction)_.

![image](https://github.com/user-attachments/assets/4eb9db34-8f93-457d-8b7c-e268e87634a6)

https://github.com/user-attachments/assets/ababc261-8e31-47a7-9867-cdc3fccdbeb0

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Linux

**Comment by MattFaz** [comment]
I've just realised my above screenshots show the 30th _(which doesn't exist in Feb)_ but the issue still remains when I check the 'Move scheduled after/before weekend'. It skips the Feb transaction regardless of if I select before/after.

If I change the date to the 28th repeating every 3 months it works fine, it appears to be due to the first transaction being on the 30th and repeating every 3 months. How should this be handled?

**Comment by youngcw** [comment]
Can you do last day of month instead of the 30th?

**Comment by MattFaz** [comment]
> Can you do last day of month instead of the 30th?

That works thank you.
It's not 100% correct as I'm billed every 3 months on the 30th, so Nov 30, Feb 28, May 30, etc.
Using last day of the month will make it off by a day sometimes (e.g. May 31), but its not a big deal.

Thanks @youngcw
