### ISSUE TITLE
[Bug]: Amount of upcoming entry with split categories is doubled in the running balance 

### ISSUE THREAD

**Issue by atopley** [actualbudget/actual#3897]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

When viewing the running balance on an account, if an upcoming entry is showing from the Schedule, but has not yet been posted, and it has a rule to split the transaction into multiple categories, the split amounts are added to the total transaction amount when calculating the running balance (e.g. a transaction with total value £300 would change the running balance by £600).

Recreatable as follows:

1. Enable "Show running balances" on an account
2. Create a scheduled against that account that is due within 7 days (or within the period specified under the experimental feature "Scheduled transaction upcoming length adjustment")
3. In the schedule click "Edit as rule"
4. Click "Split into multiple categories" and add 2 or more splits then save the rule
5. Check the running balance against the upcoming transaction

A demo budget files showing the issue is attached
[2024-11-25-My Finances 1.zip](https://github.com/user-attachments/files/17909107/2024-11-25-My.Finances.1.zip)

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

**Comment by joel-jeremy** [comment]
I've done some work on the running balance on this PR: https://github.com/actualbudget/actual/pull/3708. Can you please try the demo link on the PR to see if the issue still persists?

**Comment by atopley** [comment]
Thanks Joel, unfortunately the issue still exists in PR: #3708.  See example screenshot, transaction with split categories and total value 1,000 reduces the running balance by 2,000:

![image](https://github.com/user-attachments/assets/b6fe428e-cd25-47ca-a4a5-d814da04f968)

**Comment by joel-jeremy** [comment]
@atopley Can you check now? I've pushed some updates. Thanks!

**Comment by joel-jeremy** [comment]
By the way, this is related to https://github.com/actualbudget/actual/issues/3508

**Comment by atopley** [comment]
Hi Joel, your updates appear to have fixed the issue, thanks!  Apologies for missing #3508 - I did do a search before submitting the issue, so I'm not sure how I missed it
