### ISSUE TITLE
[Bug]: Expenses are doubled / counted twice on the budget page

### ISSUE THREAD

**Issue by sNiXx** [actualbudget/actual#3914]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I was keeping track of my latest transactions and noticed that **Expenses** are exactly twice the actual amount (see screenshot). For October, the amounts from all categories add up to 5'679, but the sum on the budget is 11'358. The same can be observed for the other months and I am positive that this was not the case previously.

I have already tried resetting the budget cache.

![image](https://github.com/user-attachments/assets/eaf80f76-2cdc-465c-aee4-22b599d3788f)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Linux

**Comment by youngcw** [comment]
Does this still persist if you export and import the file?

**Comment by sNiXx** [comment]
Exporting and importing it again corrected the amounts. Thank you :pray: :grin: 

Is there an underlying issue that needs solving?

**Comment by youngcw** [comment]
Unless you can consistently recreate the issue there isn't much we can do to fix anything underlying

**Comment by tbradsha** [comment]
This is happening on my end as well. I cleared the budget cache with no change, but I haven't exported/reimported as I'm worried this would affect transactions linked as transfers between accounts, etc.

**Comment by youngcw** [comment]
Something that might help, that helped a different tracking budget issue, is to change back to envelope budget and then back to tracking.
