### ISSUE TITLE
Hide or Lock Off Balance Accounts Only

### ISSUE THREAD

**Issue by phneeley** [actualbudget/actual#3917]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I’d love to see the ability to completely hide or lock off-balance accounts. There are various people in my household (including minors) who contribute to the tracking and management of our shared finances. It’s fine for all to see those shared finances, but not everyone needs to have such a detailed view or view at all of off-budget investment accounts that I’d like to keep in there to track overall net worth.

### Describe your ideal solution to this problem

Actual has the ability to hide or lock off-balance accounts behind a password or PIN code.

**Comment by dequally** [comment]
Would be nice with an option just to hide accounts as a start. 
This would make it so that people, including me, don't get dragged down by the many accounts that are not used day to day (for example foreign accounts).
