### ISSUE TITLE
[Bug]: Error after updating to 24.11.0 - TypeError: path must be absolute or specify root to res.sendFile

### ISSUE THREAD

**Issue by ykiran** [actualbudget/actual#3919]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I've updated to the latest version 24.11.0 following these steps:
- Stop server
- Run git pull
- yarn install
- yarn start

And then I opened the browser to: localhost:5006

Message shown was "Initializing connection to local database....." seemed stuck so I refreshed the page and now the page asks me to "Download File" and I do so. Again, the page is stuck on "Downloading" message.

Here is the output I see currently in the terminal:

>Kiran@Kiran-PC D:\Actual\actual-server git:(master)
(0) > yarn start

> Checking if there are any migrations to run for direction "up"...
> Migrations: DONE
> Listening on :::5006...
> 2024-12-01T11:46:35.498Z info: GET 200 /account/validate
> 2024-12-01T11:46:35.510Z info: GET 200 /sync/list-user-files
> 2024-12-01T11:46:35.565Z info: GET 304 /account/validate
> Rejection: TypeError: path must be absolute or specify root to res.sendFile
>     at ServerResponse.sendFile (D:\Actual\actual-server\node_modules\express\lib\response.js:441:11)
>     at file:///D:/Actual/actual-server/src/app-sync.js:297:7
>     at Layer.handle [as handle_request] (D:\Actual\actual-server\node_modules\express\lib\router\layer.js:95:5)
>     at next (D:\Actual\actual-server\node_modules\express\lib\router\route.js:149:13)
>     at Route.dispatch (D:\Actual\actual-server\node_modules\express\lib\router\route.js:119:3)
>     at Layer.handle [as handle_request] (D:\Actual\actual-server\node_modules\express\lib\router\layer.js:95:5)
>     at D:\Actual\actual-server\node_modules\express\lib\router\index.js:284:15
>     at Function.process_params (D:\Actual\actual-server\node_modules\express\lib\router\index.js:346:12)
>     at next (D:\Actual\actual-server\node_modules\express\lib\router\index.js:280:10)
>     at jsonParser (D:\Actual\actual-server\node_modules\body-parser\lib\types\json.js:113:7)
> 2024-12-01T11:46:37.086Z info: GET 200 /sync/get-user-file-info

Please help.
Thanks in advance.

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 10

**Comment by MatissJanis** [comment]
👋 Please reach out via the community discord for tech support. You'll hack much more luck there.

Closing as this isn't a bug as far as I can see.
