### ISSUE TITLE
[Bug]: Critical security vulnerabilities found in package dependencies

### ISSUE THREAD

**Issue by biohzrddd** [actualbudget/actual#392]
### Verified issue does not already exist?

I have searched and found no existing issue

### What happened?

Google Cloud vulnerability scan found the following:
1x critical
1x High
5x Medium
Many x Low

The dependencies for actual-* need updated/replaced to fix vulnerabilities.

![image](https://user-images.githubusercontent.com/10577752/202287640-5ffc03c2-1cbf-46ed-a424-3984f3842296.png)

### What error did you receive?

See What Happened?

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Other

### Operating System

Linux

**Comment by jlongster** [comment]
This is very vague. Please dig in and provide concrete steps for what we need to do. Often, these kinds of vulnerability scans are useless as they find thing that are only run in development mode, etc. We have _very_ few binary deps and none of those packages look relevant to Actual. If you can't give us more concrete steps or description of what's wrong, we'll close this issue.

**Comment by biohzrddd** [comment]
It appears Google Cloud's Container Scanning API was scanning the OS and not any of the node.js packages Actual depends on. Closing, sorry for the confusion!
