### ISSUE TITLE
[Feature] Manual review of imported transactions

### ISSUE THREAD

**Issue by mullermn** [actualbudget/actual#3924]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Apologies if this exists as a request. I'm sure I saw it once before but I have not been able to find it.

I would like it if newly imported transactions can be flagged for manual review and ticked off. Actual has some very powerful automatic rules features, but especially as the complexity of the matching and outcome actions increases (eg, with the action rule templating) it brings in a risk that one of these rules will get something wrong and it will slip by unnoticed. 

### Describe your ideal solution to this problem

I would like a 'to review' flag that can be set on a transaction level, with newly imported transactions having this flag set automatically.

It would be doubly useful if users can set this flag themselves as sometimes there are transactions that you want to remember to look into further. This feature could be further extended to allow multiple categories of review - but this is not necessary to support the feature request above; a single category would do.

This function could in essence be very similar to the flags-in-notes already supported but it would ideally have a punchier UI to enable toggling the tag and removing it to be much quicker than editing free text.

### Teaching and learning

Content should be added to the application help, but I think the UI for this should be pretty self explanatory - a narrow column with the icon of a flag above it on the transaction view, with a popup with the available categories on it when that section of a row is clicked.

**Comment by mcalligator** [comment]
I agree that being able to review manually transactions being important would be extremely useful.  Until recently, my daily driver for personal finance was Home Accountz, which although dreadful in many respects, did give you the chance to preview all the transactions about to be imported, and edit any aspect of any one of them before going ahead.  That was a life-saver on many an occasion (especially when the amount sign was the wrong way round!)

**Comment by Spuddy** [comment]
We could have a different colour on the clear flag for this?

- Grey uncleared
- Yellow cleared but not reviewed
- Green cleared and reviewed.
