### ISSUE TITLE
[Feature]: Custom Data Table report values should be right justified

### ISSUE THREAD

**Issue by kcollett** [actualbudget/actual#3925]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I have a custom report I call Income and Expense (Time, Group, Payment, Monthly, Include Current Month, Live, Last Three Months (+1)), configured to display as a Data Table. When rendering the table, all the values are left-justified; they should be right-justified. 

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

**Comment by youngcw** [comment]
This isn't really a bug.  Im moving it to a feature request.
