### ISSUE TITLE
[Feature] Delete budget category only for transactions/budgets going forward.

### ISSUE THREAD

**Issue by Yowaishi** [actualbudget/actual#3926]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Delete budget category only going forward with no need to mess up historical data. If I stop paying for something and have no intention of paying for it before, I should just be able to remove it from my budget. I shouldn't have to mess up previously balanced months of work by transferring historical transactions to another category. For example, If I attempt to use historical spending patterns to budget for future spending the historical data is then inaccurate. If I were to budget using a simple spreadsheet I would be able to stop including a category without messing up previous months. People's budgets do change as life changes so this seems like it would be useful for everyone and not a one-off use case.

### Describe your ideal solution to this problem

When you delete a budget category, give an option to leave the historical transactions as they are, without requiring I transfer them. The budget category should simply stop existing going forward as an option if not included on the budget page. 

If pertinent: Why I dislike the hidden budget category as a solution: 
1. They seem to be for something you might use again in the future, as opposed to a car payment or subscription that you will not use again in the feature. 
2. Hidden budgets also have the issue where, if you try to zero out the budget by transferring to "to budget" category, will carry over that budget if you use the 'copy last month's budget feature. I was apparently budgeting for a category without realizing it for months because it was hidden. (a separate issue perhaps but given that is how the app currently functions I feel it is pertinent as a reason).

### Teaching and learning

The option to delete a budget category already exists as a drop down, so it would be change in the pop-up that already exists. Documentation around budget categories could be updated to explain the process.

**Comment by atticcat** [comment]
I think one way to solve this would be for categories to have an attribute of which months the category is active, that is, you can edit a category and say "active Oct 2023 through Dec 2024" and it will only show on the budgets for those months. This would allow categories to end when they become no longer useful, but it would also allow the inverse situation - a new category to be created and only take effect after a certain date, also without having to affect previous, completed budget months.
