### ISSUE TITLE
[Bug]: Transaction order is incorrect after importing data with the same date

### ISSUE THREAD

**Issue by youaintnobody** [actualbudget/actual#3928]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I'm running the following:
Client version: v24.11.0
Server version: v24.11.0

I'm new to Actual Budget. This happens on both local and server. Is there a fix for this or an option to easily re-order the transaction?
This happens when you import transactions for bank or from and account export/import from CSV. You end up with the incorrect running balance.

Would it be possible to fix this during the import process or an addition to be able to reorder the transaction. The only workaround is change the date to a different date and change the date back in the correct order of transaction.

Manually entered data with the correct order.
![392200553-edd585ba-fc3f-4d43-be96-5dc580fce686](https://github.com/user-attachments/assets/af003837-0f53-42e9-b198-ff0e8aebdf6d)

Another account with the exported data after it has been imported.
![392201059-6bc75965-866c-48bb-9247-7347b9eabc3e](https://github.com/user-attachments/assets/26b59239-c365-4719-8cec-5696997cdb51)

### Where are you hosting Actual?

Docker

### Operating System

Windows 10

**Comment by youngcw** [comment]
You found the only work around.  It think there are feature requests open for reordering already if you want to go vote for them.

**Comment by tekumara** [comment]
Also hit this. The `sort_order` is correct in the database but when the UI sorts by date it's not using `sort_order`.

**Comment by tekumara** [comment]
Also hit this. The `sort_order` is correct in the database but when the UI sorts by date it's not using `sort_order`.

I think this is a different issue from #1165 and feels more like a bug?

**Comment by travisw3** [comment]
I just ran into this also when I realized that the imported transactions only take a date and ignore the times in the transaction csv from my bank. Example CSV below (for some reason the bank ordered them this way - I have a bug report with them also)

```
"2024-10-01 04:18:03+00:00","REDACTED",400.00
"2024-09-25 13:22:11+00:00","REDACTED",-107.93
"2024-09-30 14:01:07+00:00","REDACTED",-6.00
"2024-09-30 17:41:45+00:00","REDACTED",-14.46
"2024-10-01 22:12:54+00:00","REDACTED",-25.38
"2024-10-01 13:52:23+00:00","REDACTED",-6.00
"2024-10-01 16:39:35+00:00","REDACTED",-17.09
"2024-10-02 18:13:45+00:00","REDACTED",-25.00
```
