### ISSUE TITLE
[Bug]: Payee cell overflows on to other cells

### ISSUE THREAD

**Issue by tgf9** [actualbudget/actual#3929]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

The payee cell overflows. It spills onto the other cells making it impossible to read the row.

![image](https://github.com/user-attachments/assets/70f2e6f6-a227-42a0-ba59-3a777fda9d7d)

Steps to reproduce:
1. Create a fresh Actual file.
2. Click add account
3. Click import
4. Import test.csv, provided below

test.csv
```
"Date","Payee","Notes","Amount"
"2024-12-04","Really long payee name it's very long look omg, like i mean really really long just wow","This is a note","0.00"
```

Version:
```
App: v24.11.0 | Server: N/A
```
Using this AUR: https://aur.archlinux.org/packages/actual-appimage

### Where are you hosting Actual?

Desktop App (Electron)

### What browsers are you seeing the problem on?

Desktop App (Electron)

### Operating System

Linux

**Comment by youngcw** [comment]
This has been fixed and will be in the next release
