### ISSUE TITLE
[Feature] Create New Category on the fly

### ISSUE THREAD

**Issue by adivardhan1000** [actualbudget/actual#3947]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

When starting new and categories don't exist, we need to go all the way to the home page, create a new category under a particular group, go back to the transactions page and set category. This increases the friction and the number of clicks it takes to create a category.

### Describe your ideal solution to this problem

When we search for a category and it doesn't exist, it should show in the list of categories [New category?] and when a user clicks or presses enter, a new category with the name searched for gets created.

**Comment by saveman71** [comment]
Similar to #4240 and #2787

**Comment by youngcw** [comment]
duplicate of #2787. Closing
