### ISSUE TITLE
[Bug]: Link to docs for tracking budgeting leads to 404

### ISSUE THREAD

**Issue by DessertOverlord** [actualbudget/actual#3949]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Currently, the link in the settings page under Learn More... for Tracking Budgeting leads to: https://actualbudget.org/docs/experimental/tracking-budget which 404's. The correct link appears to be: https://actualbudget.org/docs/getting-started/tracking-budget.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 10

**Comment by youngcw** [comment]
this has already been fixed in github and will be fixed in the next release.

**Comment by DessertOverlord** [comment]
Oh okay great. Sorry for the dupe then, I didn't see an issue for it. Thanks!
