### ISSUE TITLE
[Bug]: Windows 11 Desktop application unable to locate server but same url opens actual budget just fine

### ISSUE THREAD

**Issue by Yowaishi** [actualbudget/actual#3963]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [ ] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

After the latest update (24.12.0-alpine) to my actual server, my windows 11 desktop app version of Actual is unable to find the server. I checked that the app, installed via the Microsoft store, is up to date and it does not show any updates available.
I know it is an issue with the desktop app and not the server, because navigating to my actual budget via a webpage on the same computer works just fine, other devices are not having the same issue (a mobile phone, Mac etc). just the windows desktop app.

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Desktop App (Electron)

### Operating System

Windows 11

**Comment by youngcw** [comment]
do you have a self signed cert with your server?  

Also, it may be better for you to install on you PC via the PWA instead of the windows store.  That way your app version is always the same as your server version.

**Comment by youngcw** [comment]
are you accessing your web view over http or https?

**Comment by youngcw** [comment]
what is your server version?

**Comment by youngcw** [comment]
I don't know then.  Maybe try clearing out all the data for the app to start fresh.  

Really, if you are running a server I recommend using the PWA instead of the desktop app the are fewer issues that way.
