### ISSUE TITLE
[Feature] Hide reconciled transactions in mobile

### ISSUE THREAD

**Issue by Brodieman** [actualbudget/actual#3967]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Currently, when on mobile, you see all reconciled transactions, I would like to be able to hide them.

### Describe your ideal solution to this problem

Hide reconciled transactions on mobile

**Comment by youngcw** [comment]
Duplicate of #2969.  Closing
