### ISSUE TITLE
[Bug]: Creating rule causes error

### ISSUE THREAD

**Issue by techcat-hub** [actualbudget/actual#3981]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Creating a rule causes error.
Re-creation steps: 
1.) Select rules
2.) Create new rule
3.) Stage of rule "pre"
**Conditions match**
4.) select "imported payee"
5.) select "contains" --- **This causes error message**

<img width="1422" alt="Screenshot 2024-12-13 at 15 13 10" src="https://github.com/user-attachments/assets/b0e3f1c2-0f26-44df-b7b7-373882089d4c" />

### Where are you hosting Actual?

Desktop App (Electron)

### What browsers are you seeing the problem on?

Desktop App (Electron)

### Operating System

Mac OSX

**Comment by youngcw** [comment]
I believe this is fixed in the edge build. Can you try edge.actualbudget.org and see?

**Comment by techcat-hub** [comment]
Tested in edge build and it does seem to be fixed. Thanks!
