### ISSUE TITLE
[Bug]:  Schedule fatal error

### ISSUE THREAD

**Issue by ArmandoAmmar** [actualbudget/actual#3989]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I tried to create a Schedule to get all month days to see if I receive the correct amount of money, but when I tried this, i got a error for schedule, and this error blocked me to use the system.

TypeError: Cannot read properties of null (reading 'num1') at IC (app://actual/static/js/index.rtiWlUvs.js:98:43758) at g9 (app://actual/static/js/index.rtiWlUvs.js:263:90084) at kk (app://actual/static/js/index.rtiWlUvs.js:57:19539) at BM (app://actual/static/js/index.rtiWlUvs.js:59:44045) at MM (app://actual/static/js/index.rtiWlUvs.js:59:39777) at iW

### Where are you hosting Actual?

Desktop App (Electron)

### What browsers are you seeing the problem on?

Desktop App (Electron)

### Operating System

Windows 10

**Comment by matt-fidd** [comment]
Did you delete the amount in the rules page?

It should look something like this, if there isn't an amount you'll need to add it back
![image](https://github.com/user-attachments/assets/d3c303be-3465-452e-b84d-b47bc3c266be)

**Comment by cjfagerstrom** [comment]
Just wanted to note that I'm having the same issue. `TypeError: Cannot read properties of null (reading 'num1') at IC`

**Comment by youngcw** [comment]
I believe this has been fixed in edge. Can someone test their budget on edge.actualbudget.org?

**Comment by cjfagerstrom** [comment]
Can confirm edge has resolved the issue.
