### ISSUE TITLE
[Bug]: Importing YNAB4 budget forces transaction to cleared status

### ISSUE THREAD

**Issue by biohzrddd** [actualbudget/actual#399]
### Verified issue does not already exist?

I have searched and found no existing issue

### What happened?

When importing a YNAB4 budget with uncleared transactions (e.g. a scheduled transaction that hasn't yet occurred), they import as cleared. 

### What error did you receive?

None.

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 10

**Comment by MatissJanis** [comment]
Hi,
Would you mind sharing an example YNAB file?
Thanks

**Comment by biohzrddd** [comment]
> Hi, Would you mind sharing an example YNAB file? Thanks

See attachments and screenshots here:
https://github.com/actualbudget/actual/pull/88#issuecomment-1356842027

**Comment by MatissJanis** [comment]
Should be fixed here: https://github.com/actualbudget/actual/pull/490

Please test it and let me know if you spot any issues.
