### ISSUE TITLE
How to add upcoming budget items >1year into the future?

### ISSUE THREAD

**Issue by openSourcerer9000** [actualbudget/actual#3994]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

![image](https://github.com/user-attachments/assets/fbfb032d-fe2b-47c3-b97d-b058431b46a9)
The main thing I need a budget for is medium to long term goals. I need to understand which funds I can tie up into a CD until which date etc. I'm modeling buying a CD as liquid capital leaving the "for budget" realm, and going off into the market. Upon maturation, it magically appears back into the cash portion of a brokerage account, as if a windfall counted as "income". The month by month "to budget" number is just about the best way I could see how much excess liquid funds I have in the moment - the minimum of these could be set aside for retirement, upon recalculating, the new minimum could be tied up in a CD or bond until X date of future expense. 

First of all, how to enable adding budget items beyond 1 year into the future? Doesn't matter if it's through the GUI, as long as there's a straightforward way.

Second, how should one model the maturation of CD's/bonds? Would it be through schedules? it doesn't seem there's a way to schedule income in envelope mode.

Thanks,

**Comment by youngcw** [comment]
Sounds like you are looking for budgeting advice, not requesting a feature or reporting a bug. The best place for budgeting advice is the discord server or there is also a Reddit page.

**Comment by openSourcerer9000** [comment]
@youngcw Well so how do you unblock dates > 1 year in advance? That's very much related to the app itself

**Comment by youngcw** [comment]
You can view +1 year from your most recent transaction.

**Comment by openSourcerer9000** [comment]
@youngcw Yes how do you change that limit? I'm not finding it in the code.

**Comment by x-rous** [comment]
@youngcw @matt-fidd @MatissJanis  I see we have the future budget maintenance set at 12 months to control the number of entries we get in `createAllBudgets()`  and extending it (let's say to 24/36 months) could substantially increase spreadsheet creation time and memory usage.

But this decision was done early in the product lifecycle, and I'm not sure if it is still applicable today, can we try an experimental feature to extend the budget period to 24 months (mainly for tracking budget users where future commitments planning beyond 12 months is required). I'm happy to open the PR for this and test it with my 8 years budget file, but would rather know if you would consider it .
