### ISSUE TITLE
[Feature] Open Banking from Brazil

### ISSUE THREAD

**Issue by phalkmin** [actualbudget/actual#3995]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

So, I noticed that Actual Budget doesn't have a way to integrate with open banking / open finance from Brazil, even as it has connections with European and North American banks. That would make integration from local users a lot easier	

### Describe your ideal solution to this problem

There is extensive documentation for this https://www.bcb.gov.br/estabilidadefinanceira/openfinance and https://openfinancebrasil.atlassian.net/wiki/spaces/OF/overview 

I don't have the means and knowledge to fully integrate this by myself, but it would be appreciated. 

### Teaching and learning

With this option, everyone in Brazil would be able to integrate their bank accounts automatically

**Comment by lelemm** [comment]
Hi @phalkmin I tried to register myself as a developer in open finance and that's a no deal. 

There are so many requirements from Banco Central to be a partner that is marginally impossible to a opensource software to become one.
- It would need Actual to be a company and have a branch here in Brazil
- It must be a fintech or a bank located in Brazil

There are other requirements that I can't remember. I tried this like 6 months ago.

Probably would be more feasible to connect into an already partner and pay monthly for their service

**Comment by phalkmin** [comment]
Bro, that's a bummer :(

I'll check this SimpleFin solution, anything that keeps me from uploading CSVs is good, thanks!

**Comment by lelemm** [comment]
simplefin does not work in Brazil. you would have to find a company here I Brazil that does this. As far as I can tell, for pessoal fisica the is none, just for pessoa juridica

**Comment by lelemm** [comment]
> anything that keeps me from uploading CSVs is good, thanks!
Since I don't use money (paper), I almost at the point to start importing bank notifications from my phone into Actual to not deal with CSV and OFX lol

**Comment by phalkmin** [comment]
🥺

**Comment by phalkmin** [comment]
> Since I don't use money (paper), I almost at the point to start importing bank notifications from my phone into Actual to not deal with CSV and OFX lol

I'm going to use a self-hosted solution, don't know how much work I'll need to automate this. Let me try Actual for a few weeks and see how it goes.

**Comment by felipeagc** [comment]
@lelemm I found a solution called pluggy.ai, they have a free API for developers that you can use to fetch your bank transactions through open finance in brazil (haven't tested through). I'm wondering if we could add this to Actual, I'm very interested as well.

**Comment by lelemm** [comment]
> @lelemm I found a solution called pluggy.ai, they have a free API for developers that you can use to fetch your bank transactions through open finance in brazil (haven't tested though). I'm wondering if we could add this to Actual, I'm very interested as well.

Based on the API, it does work for personal accounts, not only for companies like most.
BUT
![image](https://github.com/user-attachments/assets/6a7c56f9-b666-43ab-a27e-d61f7f87b147)

and the price outrageous:
![image](https://github.com/user-attachments/assets/0fff2223-802a-4b2c-becf-897ab6fbd585)

**Comment by lelemm** [comment]
@felipeagc I found a interesting site that lists all partners in open banking
https://dashboard.openfinancebrasil.org.br/transactional-data/ranking/receivers

One idea is navigate into each site and check if they sell something affordable for a normal person lol

**Comment by felipeagc** [comment]
@lelemm They seem to have two different offerings, the one you looked at is for companies :P. The other is this one: https://meu.pluggy.ai/en - it seems to be free for individual developers. I haven't tested it yet, though.

<img width="1120" alt="image" src="https://github.com/user-attachments/assets/0a493642-1143-46e1-8f0e-f057e3d8084f" />

(Source of the screenshot is just scrolling down this page: https://www.pluggy.ai/en)

**Comment by lelemm** [comment]
oh, thats look nice

**Comment by lelemm** [comment]
https://github.com/OpenBanking-Brasil/specs-directory/tree/main/conformance
I can't find pluggy there. looks sus

**Comment by felipeagc** [comment]
> https://github.com/OpenBanking-Brasil/specs-directory/tree/main/conformance I can't find pluggy there. looks sus

I think that's because they're not a bank, they just consume the open finance APIs from the banks (after you give them consent to fetch data from your accounts) and hand the response back to you.

**Comment by lelemm** [comment]
I tried to add an account, didn't work.
I will try again in the morning

**Comment by lelemm** [comment]
https://github.com/pluggyai/meu-pluggy

**Comment by lelemm** [comment]
![image](https://github.com/user-attachments/assets/40b67309-f108-4234-b341-8ff7b9c5903d)

does work @felipeagc 

When I have some time I will do this if someone else doesnt

**Comment by phalkmin** [comment]
oh god it's happening

**Comment by felipeagc** [comment]
@lelemm @phalkmin I made a quick and dirty solution: https://github.com/felipeagc/pluggy-actual-export. It can either export transactions directly to Actual or to OFX files that you can import into Actual. I also deployed it to AWS lambda and made it run on a schedule every night at 00:00. Seems to work pretty well so far :)

**Comment by lelemm** [comment]
just a teaser:

![image](https://github.com/user-attachments/assets/9025248f-1270-4311-a724-b74a8af8d24d)

**Comment by lelemm** [comment]
> @lelemm @phalkmin I made a quick and dirty solution: https://github.com/felipeagc/pluggy-actual-export. It can either export transactions directly to Actual or to OFX files that you can import into Actual. I also deployed it to AWS lambda and made it run on a schedule every night at 00:00. Seems to work pretty well so far :)

Nice one!!! I started the final solution on my spare time at work. There is a lot to do yet, but its taking shape :)

**Comment by phalkmin** [comment]
Can't wait to finally use Actual with automatic sync :D

**Comment by lelemm** [comment]
![image](https://github.com/user-attachments/assets/1b2472f5-547f-4804-add8-4a66326c6247)

👀

**Comment by phalkmin** [comment]
Let me know if you want a tester

**Comment by lelemm** [comment]
If you wanna try it:
https://github.com/lelemm/actual/tree/pluggy.ai
https://github.com/lelemm/actual-server/tree/feature/pluggy.ai

**Comment by igorsantos07** [comment]
Damn, this is not fair. I've just spent a couple of days updating my spreadsheets for 2025, and now I just discovered Actual. I'll have to spend a couple of days more to get Actual into shape for automatic syncing with pluggy??? Why didn't any of you guys tell me of this amazing development before I started updating my budget spreadsheets??? Damn :joy: 

I'll look around about installing Actual and could very well sign up for testing too!

**Comment by douugdev** [comment]
Just bumping this as it will be such a useful feature. Thanks for looking into it @lelemm!

**Comment by lelemm** [comment]
> Damn, this is not fair. I've just spent a couple of days updating my spreadsheets for 2025, and now I just discovered Actual. I'll have to spend a couple of days more to get Actual into shape for automatic syncing with pluggy??? Why didn't any of you guys tell me of this amazing development before I started updating my budget spreadsheets??? Damn 😂
> 
> I'll look around about installing Actual and could very well sign up for testing too!
> 
> **Edit:** after spending a couple of hours trying out the live demo, it turns out I wouldn't be able to migrate my spreadsheet workflow to Actual - I have separate savings objectives (emergencies, trips, time-off, etc) which doesn't seem to correlate well with either accounts or categories under Actual.
> 
> I might come back in the future, though, in case I really need a detailed tracking of my expenses, but so far the high level tracking I do with Excel is enough, albeit sometimes error-prone 😂 No luck finding a way to automate credit card bill payments on Actual, either. Good luck, though, as supporting OpenBanking with such app would be gorgeous!

Did you check the goal templates? https://actualbudget.org/docs/experimental/goal-templates
This is probably what you are missing

**Comment by lelemm** [comment]
> No luck finding a way to automate credit card bill payments on Actual,

what do you mean @igorsantos07 ? 
The OpenBanking integration imports credit card data too

**Comment by igorsantos07** [comment]
@lelemm I expected Actual to ask me the day my statement closes, and when my credit card bill is paid on a specific account (as Organizze used to do, at least when I used it many years ago), but it doesn't do that. So it seems a bit more troublesome to handle credit cards than I expected.

**Comment by lelemm** [comment]
@piloadami , pluggy is being reviewed by the maintainers, soon it will be part of the bank sync options

**Comment by lelemm** [comment]
> > Amazing, meaning AB will make connecting to 'pluggy.ai' as easy as connecting to gocardless?
> 
> Yep!

Pluggy to be used on the free plan requires you to do a lot of stuff on their platform before.
You can check the steps here:
https://github.com/pluggyai/meu-pluggy

**Comment by phalkmin** [comment]
oh god 😎

**Comment by carmolim** [comment]
Do you guys think there’s any risk of accessing all you financial data over pluggy? I know that i be a part of the OpenFinance you need to follow several security measures but AB is a local first privacy focused application and I don’t feel so comfortable exposing all my financial information to pluggy, someone has any thoughts about this aspect?

**Comment by phalkmin** [comment]
You can just not use pluggy and continue adding the data manually. AB has connections to other services like pluggy, but more focused on EU and USA, and they also give you the option of not using it.

**Comment by lelemm** [comment]
> Do you guys think there’s any risk of accessing all you financial data over pluggy? I know that i be a part of the OpenFinance you need to follow several security measures but AB is a local first privacy focused application and I don’t feel so comfortable exposing all my financial information to pluggy, someone has any thoughts about this?
> 
> In other words do you trust pluggy?

That's a risk of using third party softwares. If you don't feel like trusting it, better not use it
