### ISSUE TITLE
[Bug]: SimpleFin account balance does not update for investment accounts

### ISSUE THREAD

**Issue by enewbury** [actualbudget/actual#3997]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

For instance when linking a vanguard account, it links with the correct starting balance, but as the value of the stock goes up and down over time, the balance is not synced to actual budget and stays at the original value when first linked.

### How can we reproduce the issue?

Link an investment account like Vanguard, trigger sync the next day and observe that balance changed in vanguard but not in acutal

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Mobile Device

**Comment by youngcw** [comment]
Actual requires transactions to update balances, so the regular sync doens't change the balance on investment accounts because there aren't new transactions.

There are some community scripts to do this that you can look into.

**Comment by enewbury** [comment]
I've been searching and haven't been able to find the scripts you're referring to...would you be willing to add some links for me and future users looking for a similar solution?

**Comment by youngcw** [comment]
https://github.com/psybers/actual-helpers
