### ISSUE TITLE
Docker Image?

### ISSUE THREAD

**Issue by quaintdev** [actualbudget/actual#4]
First issue!

Thank you for making this open source! I have not used it yet but the application looks fantastic.

I was hoping to host this on my Raspberry Pi the way I host half a dozen other services but looking at repository it seems docker image for actual is currently not present. It would be good to have docker image for this so that anyone can quickly spin this up and take this for a quick drive. I can build image for ARM but I need the initial docker support.

Thanks again for sharing this with the community.

**Comment by chrishoage** [comment]
There is a Dockerfile here https://github.com/actualbudget/actual-server/blob/master/Dockerfile

With a little effort it can be modified to run on ARM (since it appears that this is just a node.js project)

**Comment by jlongster** [comment]
Yes, the `actual-server` project is the one that actually has a server
