### ISSUE TITLE
[Bug]: Imported YNAB4 budget loses scheduled transactions

### ISSUE THREAD

**Issue by biohzrddd** [actualbudget/actual#400]
### Verified issue does not already exist?

I have searched and found no existing issue

### What happened?

When importing a YNAB4 budget with scheduled transactions (some accounts with them and some without) that haven't been added to the register, none of the scheduling transfers (in Actual, going to Schedules shows "No schedules").

### What error did you receive?

None

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 10

**Comment by MatissJanis** [comment]
Hi,
Would you mind sharing an example YNAB file?
Thanks

**Comment by MatissJanis** [comment]
Linking these two together as they both relate to the YANB4 importer: https://github.com/actualbudget/actual/issues/399

**Comment by biohzrddd** [comment]
I see nothing in the [API docs](https://actualbudget.github.io/docs/Developers/API) about add/modify/delete schedules. Importing uses the API so currently this isn't possible.

**Comment by MatissJanis** [comment]
👋 Closing this ticket for now as we don't have a way to reproduce the issue (missing reproduction import file).

Please open a new issue with the reproduction file if you're still experiencing this problem.
