### ISSUE TITLE
[Bug]: Overwrite/Apply Budget Template Not Working

### ISSUE THREAD

**Issue by parkel42** [actualbudget/actual#4006]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Clicking on either "Apply budget template" or "Overwrite with budget template" does nothing, only the "Everything is up to date" message appears on the bottom right corner: 
![image](https://github.com/user-attachments/assets/9feacbdb-a07b-48c0-8db6-edeafa316c8d)
![image](https://github.com/user-attachments/assets/f661e111-fc89-494b-9148-595193baee56)

No issues with templates when checking, not too sure what is going on. 

The same issue presents itself across all browsers, including the mobile PWA. 

### How can we reproduce the issue?

1. Click on either the "Apply budget template" or "Overwrite with budget template" option in the month settings dropdown
2. Nothing happens when the budget templates should have been applied

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Firefox, Chrome, Desktop App (Electron), Other

### Operating System

Windows 11

**Comment by youngcw** [comment]
First off most templates don't work right in the tracking budget since the tracking budget doesn't rollover funds.

Can you upload an example budget that shows the issue or list what templates you have in your categories that you are trying to run?

**Comment by parkel42** [comment]
Hmm.. the weird thing is that templates applied properly in the previous version (24.11.0 iirc), with the budgeted amounts filling in correctly.

I'm using templates very simply, only to help me fill in my monthly budget, examples are: 
- #template schedule full <schedule name>
- #template 400

I have made a sample budget attached here: 
[2024-12-18-Example.zip](https://github.com/user-attachments/files/18184434/2024-12-18-Example.zip)

**Comment by youngcw** [comment]
You're right its not working.  It does work if you apply then to individual categories though which is strange.
