### ISSUE TITLE
[Feature] Duplicate a rule

### ISSUE THREAD

**Issue by sinoop** [actualbudget/actual#4011]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I have a rule defined and want to duplicate that and then edit it to save some keystrokes than starting from scratch
At the same time I would prefer to have ability to export and import rules as well

### Describe your ideal solution to this problem

Add a UI dropdown option to duplicate a rule

**Comment by Thiago-Morais** [comment]
This is a must-have

When I have to create multiple complex rules, it is a pain
