### ISSUE TITLE
[Bug]: Fatal Error in UI after editing a transaction rule.

### ISSUE THREAD

**Issue by Interrupting-Seal** [actualbudget/actual#4013]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

After editing the rule for a scheduled transaction to run when the amount is greater than $0.00, the pikapod app crashed and can't be opened again. The mobile phone version still works but if I attempt to launch  the normal web version on a computer or the ipad I get the same fatal error.

Edit for further information. I can get Actual to run if I manage to select the Budget page in the split second between it opening and then crashing. If I then select the Schedules page it crashes with the Fatal Error.

Edit 2: I've fixed it! I found the rule by going to the rules page rather than the schedules page and then edited the rule to have a specific amount. It seems it doesn't like having an "Amount Greater than $0.00". I can now access the Schedules page without the app crashing.

TypeError: Cannot read properties of null (reading 'num1') at IC (https://peridot-mole.pikapod.net/static/js/index.JHeog5K2.js:98:43758) at v9 (https://peridot-mole.pikapod.net/static/js/index.JHeog5K2.js:263:90084) at kk (https://peridot-mole.pikapod.net/static/js/index.JHeog5K2.js:57:19539) at LM (https://peridot-mole.pikapod.net/static/js/index.JHeog5K2.js:59:44045) at BM (https://peridot-mole.pikapod.net/static/js/index.JHeog5K2.js:59:39777) at IW (https://peridot-mole.pikapod.net/static/js/index.JHeog5K2.js:59:39705) at $m (https://peridot-mole.pikapod.net/static/js/index.JHeog5K2.js:59:39557) at zb (https://peridot-mole.pikapod.net/static/js/index.JHeog5K2.js:59:35921) at eE (https://peridot-mole.pikapod.net/static/js/index.JHeog5K2.js:59:36725) at Ea (https://peridot-mole.pikapod.net/static/js/index.JHeog5K2.js:57:3279)

### How can we reproduce the issue?

I haven't been able to reproduce the error because I haven't been able to use the app again. All I know is that the error occurred after editing a scheduled transaction rule and the one thing I did a bit differently was have the rule run if the amount was greater than zero.

### Where are you hosting Actual?

Pikapods

### What browsers are you seeing the problem on?

Chrome, Safari

### Operating System

Mac OSX

**Comment by youngcw** [comment]
This has been fixed and will not be an issue in the next release.  See PR #3958

**Comment by Interrupting-Seal** [comment]
Thank you.
