### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by LRuffati** [actualbudget/actual#4015]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When running the latest version from docker (v24.12.0) on a desktop browser (both Firefox on linux and Arc on macos) trying to:

- See "all account"
- See "for budget"
- Seeing the expenses in one envelope for any month

Results in an "unrecoverable error in the UI", with the following error:

```
IC@https://******/static/js/index.JHeog5K2.js:98:43756 yRe/d</<@https://******/static/js/index.JHeog5K2.js:98:123249 yRe/d<@https://******/static/js/index.JHeog5K2.js:98:123180 cM@https://******/static/js/index.JHeog5K2.js:57:23922 Ye.useMemo@https://******/static/js/index.JHeog5K2.js:10:6208 yRe@https://******/static/js/index.JHeog5K2.js:98:123141 v@https://******/static/js/useAccountPreviewTransactions.EORsFDeG.chunk.js:1:117 Jo@https://******/static/js/wide.k1vKSsoJ.chunk.js:1:89662 kk@https://******/static/js/index.JHeog5K2.js:57:19539 Db@https://******/static/js/index.JHeog5K2.js:59:3139 LM@https://******/static/js/index.JHeog5K2.js:59:44820 BM@https://******/static/js/index.JHeog5K2.js:59:39779 IW@https://******/static/js/index.JHeog5K2.js:59:39707 $m@https://******/static/js/index.JHeog5K2.js:59:39557 zb@https://******/static/js/index.JHeog5K2.js:59:35921 MM@https://******/static/js/index.JHeog5K2.js:59:34870 j@https://******/static/js/index.JHeog5K2.js:44:1553 N@https://******/static/js/index.JHeog5K2.js:44:1911 EventHandlerNonNull*@https://******/static/js/index.JHeog5K2.js:44:2077 @https://******/static/js/index.JHeog5K2.js:44:3813
```

From mobile everything works as expected

### How can we reproduce the issue?

I don't know what might be causing the issue or how to reproduce (this has been happening for around a week so I'd be surprised if it went unobserved until now if all it took was to press the "All accounts" button

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Other

### Operating System

Linux

**Comment by youngcw** [comment]
Have you tried other browsers or resetting your browser cache?

**Comment by LRuffati** [comment]
Resetting the browser cache didn't help but I only tried those two browsers

**Comment by LRuffati** [comment]
Unfortunately (or fortunately) I can't reproduce the issue anymore. Nothing
changed so I'm not sure what fixed it but I won't be able to get a new
error trace

**Comment by youngcw** [comment]
I was wondering if it was a bad value in the db or cache causing this so maybe it cleared up somehow.  Ill close this for now
