### ISSUE TITLE
[Bug]: [Mobile] Add Transaction requires multiple tap on Amount to display keyboard

### ISSUE THREAD

**Issue by ninokierulf** [actualbudget/actual#4017]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

> Browser: Safari, Firefox, Brave
> iOS Version: 18.1
> Model: iPhone 14 Pro Max
> Client version: v24.12.0
> Server version: v24.12.0
> Self-host: Synology NAS, Container Manager

Trying to add new transaction but entering a number requires several toggle/tap of Amount number input field.
Expectation: When out and about, entering a new transaction should make it easy to input the positive or negative transaction.
Additionally, even while in keyboard mode a user should be able to switch between making it positive or negative 

### How can we reproduce the issue?

When tapping `+ Transaction`
1. Amount is focused, purple border, 0.00 red color. Keyboard is not showing
2. Tap on Amount field (0.00), defocuses Amount, no border, 0.00 gray color. Keyboard is not showing
3. Tap Amount field again, purple border, 0.00 red color. Keyboard showing.

### Where are you hosting Actual?

NAS - Synology

### What browsers are you seeing the problem on?

Safari, Firefox, Brave

### Operating System

iOS - iPhone 14 Pro Max

**Comment by youngcw** [comment]
duplicate #2392
