### ISSUE TITLE
[Bug]: Server offline 

### ISSUE THREAD

**Issue by LolDotPdf** [actualbudget/actual#4020]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Greetings! Every so often my iOS safari Actual client goes offline but the server is running and should be available. Any changes I make aren’t synced to the server. Deleting my local instance then gives me a “Server is not running at this URL. Make sure you have HTTPS set up properly” error when I try to set it up again. The only fix is to delete all website data from safari. This is becoming very cumbersome to do and is causing me to not trust entering transactions manually on mobile if I end up losing them anyway due to the connection issues. When this happens to one device the other devices I own remain connected. I’m hosting actual on my home server and manually set up https using the actual documentation. I connect via my local server ip and port. Is something wrong with my certificate setup?

### How can we reproduce the issue?

Server offline listed in settings while connected to the home network > server doesn’t regain connection until local client is deleted and safari website data is deleted. 

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Safari

### Operating System

Mobile Device

**Comment by youngcw** [comment]
For tech support I recommend reaching out on discord.

**Comment by kaichevannes** [comment]
Getting the same issue, any idea why?

**Comment by kaichevannes** [comment]
@LolDotPdf

**Comment by LolDotPdf** [comment]
@kaichevannes I opened a thread on Discord but here’s what I posted there as a follow up:

When I posted this last week I was using a servername.local:port address and decided to switch to using the serverIP:port url instead. It’s been a week and the client on all my devices have maintained an active connection to the actual server. Previously the server offline message would show up only after a few days. I suppose only time will tell if the .local address was causing issues with Safari actual clients. I’ll report back if the issue pops up again.

**Comment by kaichevannes** [comment]
Thank you for the reply, I got the bug with a serverIP:port address so I don't think that's a fix. I reset my server and cleared my safari website data as you recommended which worked as a temporary measure. Here's hoping it's a rare bug.

**Comment by LolDotPdf** [comment]
@kaichevannes Unfortunately I spoke a day too soon as the Actual client on my phone just lost connection to the actual server. Bummer.

**Comment by qu4cks4lb3r** [comment]
Have you checked your certificate is still valid? The last time this happened to me was because of my selfsigned certificate was expired. 

Creating a new certificate and cleaning the browser data might do the trick.

**Comment by kaichevannes** [comment]
Oh that could certainly be it, I'll give it a shot. Thanks for the suggestion.

**Comment by kaichevannes** [comment]
@LolDotPdf I just realised that I had never fully trusted my self signed certificate on my IPhone, the instructions to do it are here: https://support.apple.com/en-nz/102390

From the mkcert docs https://github.com/FiloSottile/mkcert?tab=readme-ov-file#mobile-devices

I installed the profile but never actually trusted it! I'm hoping that was the problem.

**Comment by LolDotPdf** [comment]
@kaichevannes I’ve been running off this method with success for over a week. Time will tell if it did the trick but so far so good. 

1. Install MKCERT
2. Generate a certificate then locate the installed file by using mkcert -CAROOT
3. Point actual to the pem using the docker compose file and the actual.config file
4. Save the auto generated rootCA.pem to files app to be installed on iOS/MAC
5. On iOS/Mac double click on the rootCA.pem file to open it and then go to settings > search for VPN & Device Management and install the certificate 
6. Clear safari website data
7. Setup actual client on the device

**Comment by N214** [comment]
If using Cloudflare warp, you have to trust the certificate manually.
https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/user-side-certificates/automated-deployment/
https://developers.cloudflare.com/cloudflare-one/connections/connect-devices/user-side-certificates/automated-deployment/#macos

**Comment by N214** [comment]
It still shows server is offline....
