### ISSUE TITLE
[Bug]: Create Rule with more than one "contains" filter and match "any" condition

### ISSUE THREAD

**Issue by sinoop** [actualbudget/actual#4022]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Trying to add a new Default Rule with 2 contains filter crash the application

![image](https://github.com/user-attachments/assets/8de91e37-1df2-40a0-a541-ed80bca2e4d7)

### How can we reproduce the issue?

Try creating a new rule with 2 contains filter

### Where are you hosting Actual?

Desktop App (Electron)

### What browsers are you seeing the problem on?

Desktop App (Electron)

### Operating System

Windows 11

**Comment by youngcw** [comment]
Does the still happen if you try edge.actualbudget.org?

**Comment by sinoop** [comment]
> Does the still happen if you try edge.actualbudget.org?

Doesnt seem to be happening here. 
I was using the Desktop app where I faced the issue

**Comment by youngcw** [comment]
Ok I'll close this for now as your issue should be fixed in the next release.

**Comment by sinoop** [comment]
> Ok I'll close this for now as your issue should be fixed in the next release.

Please let me know what the code was change as well. 
Interested to contributing to Actual codebase. 
Not familiar with scripting languages (scala/java developer) but can pick up these things in future.
