### ISSUE TITLE
[Bug]: Changes not syncing and transactions not imported

### ISSUE THREAD

**Issue by jmvbrown** [actualbudget/actual#4027]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Changes to the budget are not being synced and now transactions are not imported

### How can we reproduce the issue?

Just says charges not synced not sure how to recreate

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Safari

### Operating System

Linux

**Comment by youngcw** [comment]
Does it say your server is online?

**Comment by jmvbrown** [comment]
I think it was not and simplefin was having issues with my bank accounts,
but it’s all sorted now

**Comment by youngcw** [comment]
Glad its working!
