### ISSUE TITLE
[Feature] Disable Automatic Rule Creation

### ISSUE THREAD

**Issue by leecbryant** [actualbudget/actual#4034]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Automatic rule creation doesn't align with payments from multiple sources (Credit Cards) for multiple different reasons.

### Describe your ideal solution to this problem

Add a setting that allows the user to disable automatic rule creation (but still allow for manual rule creation - this feature is great!)

**Comment by youngcw** [comment]
duplicate #2515
