### ISSUE TITLE
PWA quick action for "Add Transaction" doesn't work properly when "hide decimal places" is enabled

### ISSUE THREAD

**Issue by coldblade2000** [actualbudget/actual#4037]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I've struggled to identify this bug for a while but right now that I'm on a trip I identified it, I believed it to be a locale issue until now. On a mobile PWA (on Android Chrome at least), if you have "hide decimal places" enabled, the "add transaction" quick action for the PWA will have a breaking bug when entering the amount of money for the transaction. Essentially, only the first digit will be input correctly, every next click on any number afterwards only increments the transaction value by +0.01. 

This does NOT occur when "hide decimal places" is disabled. The "Add Transaction screen" does work properly if accessed from within the PWA. It only has issues from the quick action.

### How can we reproduce the issue?

Reproduction video: https://youtu.be/gKgE_ALOSX0?si=UqdxIopsWJtKffs6

1. Install the Actual PWA and create a budget with at least 1 account.
2. Enable "hide decimal places" in the settings page of the PWA.
3. Go to home screen, hold the Actual icon and add the "Add Transaction" quick action to your homepage.
4. Click the "add transaction " quick action icon.
5. The view opens up with "0.00" in the value (this is incorrect. It should be "0".
6. Try to input 761234". You will be shown a value of 7.04 instead.
7. Now access the view from the Actual PWA without quick actions. Input 761234 in the value field
8. You will see the correct value of 761234

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Mobile Device

**Comment by jfdoming** [comment]
Hey! Can you help confirm that https://deploy-preview-4038.demo.actualbudget.org/ (from the linked PR) fixes the bug for you?

**Comment by coldblade2000** [comment]
> Hey! Can you help confirm that https://deploy-preview-4038.demo.actualbudget.org/ (from the linked PR) fixes the bug for you?

Yes, I can confirm it does fix the bug!
