### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ozansari89** [actualbudget/actual#404]
### Verified issue does not already exist?

I have searched and found no existing issue

### What happened?

1. There is a sync issue. I cannot success to sync .
2. ı cannot use mobile apps both ios and android. When i try to open android app, it throws out me from the app. 
please fix that issues. I love actual budget so much
I am running actual budget on my docker. 

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 10

**Comment by Kidglove57** [comment]
Unfortunately this is not a Bug. The mobile apps were designed for the old paid for/hosted version of Actual. They do not work with the open source version. See:

https://actualbudget.github.io/docs/FAQ

There is a work ongoing for a “responsive “ web version that will work on mobile.

**Comment by MatissJanis** [comment]
Hi

As kidglove57 already mentioned, sadly mobile apps are no longer supported. We _might_ think of bringing them back later, but currently our dev capacity is very limited. So we are focusing it mostly on fixing issues with the web version as well as releasing a responsive version as an alternative for the mobile apps.

**Comment by ozansari89** [comment]
I solved the problem. 
I don't remember how but i did. Thank you for your relevancy.
