### ISSUE TITLE
[Bug]: Manage Files causes the app to be unable to load the database

### ISSUE THREAD

**Issue by quarklark** [actualbudget/actual#4040]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I wanted to back up my file, so I opened Manage Files, (a note for design: I was expecting this function to be here.) Seeing that this was not where I create backups, I looked to close the menu. Since there was no close or cancel, I clicked the name of the file. This then caused the app to try and load the same file that was open. It hung in this state, and eventually I quit the application. (Not forced.) On re-opening, I got the default welcome screen and no option to load my file. Creating a new file works, but it cannot find my original file, even though the data is there in the data folder. 

### How can we reproduce the issue?

My guess for how to reproduce: 

1. Create a new database
2. Add a typical set of transactions
3. Click Manage Files
4. Click the currently open file

Note that I cannot reproduce this myself, so I'm not sure what happened. Perhaps I need more transactions? 

### Where are you hosting Actual?

Desktop App (Electron)

### What browsers are you seeing the problem on?

Desktop App (Electron)

### Operating System

Mac OSX

**Comment by quarklark** [comment]
Looks like it cleared `metadata.json`. Restoring a previous version fixed the issue. Unclear why this happened in the first place though

**Comment by tlesicka** [comment]
@quarklark not sure what happened for you, but I can't reproduce the issue either.  I've tried the electron app on both Mac and Windows.

When you click manage files, the current budget closes (database connection is closed and a few other housekeeping items happen).  When you click on a budget file from the manage files screen, then the database connection is opened (plus a few housekeeping items happen).  So, not sure exactly what happened for you.

As far as expected function, starting in version 25.1.0, there will be a Duplicate budget function added to the manage files screen.  It is currently in edge and will be released with the next release.

Under the settings page, there is an export function.  This exports the currently open budget to a zip file that contains the database file plus metadata.json.
In the electron app, a "backup" is taken every 15 minutes.  These can be accessed under the file menu "Load Backup...".  You can also create an instantaneous backup or retore a previous backup from this modal popup.  Really, this is more of a snapshot than a backup, but the app calls it backup.
Then as stated before a new "Duplicate" function will be added to the manage files screen in the next release.  This allows you to create an exact copy of your budget to play around with.

Hope that clarifies the way files are managed.

I would suggest closing this issue as both you and I couldn't reproduce it.  If you are able to reproduce this issue, let us know the steps.

**Comment by quarklark** [comment]
Sounds good - closed
