### ISSUE TITLE
[Feature] Add time to transactions

### ISSUE THREAD

**Issue by travisw3** [actualbudget/actual#4046]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

From what I am seeing transactions currently only consist of a date. In the CSV that is generated from my bank, it includes both a date and time for transactions. This is causing transactions that when showing a running balance that is negative at times when it should not be and also causes me problems when trying to reconcile transactions from the CSVs.

Including an example below

Account Starting Balance = $135.22

CSV transactions
```
"2024-10-01 04:18:03+00:00","REDACTED",400.00
"2024-09-25 13:22:11+00:00","REDACTED",-107.93
"2024-09-30 14:01:07+00:00","REDACTED",-6.00
"2024-09-30 17:41:45+00:00","REDACTED",-14.46
"2024-10-01 22:12:54+00:00","REDACTED",-25.38
"2024-10-01 13:52:23+00:00","REDACTED",-6.00
"2024-10-01 16:39:35+00:00","REDACTED",-17.09
"2024-10-02 18:13:45+00:00","REDACTED",-25.00
```

### Describe your ideal solution to this problem

Transactions should have both a date and time and the time should be able to be imported and used from CSVs

**Comment by bchooxg** [comment]
This is a needed feature for me
