### ISSUE TITLE
[Feature] End date for templates

### ISSUE THREAD

**Issue by jpjonte** [actualbudget/actual#4048]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I have a subscription with a monthly charge that is canceled and will end in February.

Currently I have a template for this monthly charge: `#template 20`

If I forget to remove this line when the subscription ends, it will keep adding the 20 € and I might not realize it.

### Describe your ideal solution to this problem

Templates get a new `ending` modifier:

`#template 20 ending 2025-02`

### Teaching and learning

Add another line to the template docs table.

Users might end up with a lot of "dead" template lines if they don't check their templates regularly. A warning could be added to the "check template" function that tells the user about already ended templates.

**Comment by jfdoming** [comment]
Hey! If you use `#template schedule` instead, schedules have an end date feature

**Comment by jpjonte** [comment]
@jfdoming thanks! Looks like we don't need a new feature then.
