### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Awersang** [actualbudget/actual#4050]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

The schedules panel is not loading, instead I get ne error. Restarting app doesn't change anything, so is reinstallation. Rest of the application works just fine. 

Schedules works fine on the new file, but I have everything in my old file and it would be good not to lose it. 

Fatal Error
There was an unrecoverable error in the UI. Sorry!
If this error persists, please get [in touch](https://actualbudget.org/contact) so it can be investigated.
Restart app
Show Error
TypeError: Cannot read properties of null (reading 'num1') at IC (app://actual/static/js/index.rtiWlUvs.js:98:43758) at g9 (app://actual/static/js/index.rtiWlUvs.js:263:90084) at kk (app://actual/static/js/index.rtiWlUvs.js:57:19539) at BM (app://actual/static/js/index.rtiWlUvs.js:59:44045) at MM (app://actual/static/js/index.rtiWlUvs.js:59:39777) at iW (app://actual/static/js/index.rtiWlUvs.js:59:39705) at Cm (app://actual/static/js/index.rtiWlUvs.js:59:39557) at Hb (app://actual/static/js/index.rtiWlUvs.js:59:35921) at Jj (app://actual/static/js/index.rtiWlUvs.js:59:36725) at ja (app://actual/static/js/index.rtiWlUvs.js:57:3279)

![image](https://github.com/user-attachments/assets/519d8962-4b35-4491-9a91-c7273d2ce2a7)

### How can we reproduce the issue?

I created some automatic schedules, then tried to modify something in them.  The program froze. After restart the error appears in the schedules tab. 

### Where are you hosting Actual?

Desktop App (Electron)

### What browsers are you seeing the problem on?

Desktop App (Electron)

### Operating System

Windows 11

**Comment by Awersang** [comment]
I cleared the schedules tables in the db.sqlite. Everything seems to work now. So the issue probably now is how to not let this happen again.

**Comment by youngcw** [comment]
There was a fix in the edge build that should clean up this issue. If you have a copy of the file before you removed the schedules you can try it. You might have broken rules now if you force removed the schedules.
