### ISSUE TITLE
[Feature]: Number in custom report should be aligned to the right

### ISSUE THREAD

**Issue by vvvlc** [actualbudget/actual#4053]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

The numbers in the custom report are not aligned to the right see screenshot.
![image](https://github.com/user-attachments/assets/5ffdc7a0-26bb-4c11-a22b-b779a993b7d7)

### How can we reproduce the issue?

1. Create a custom report
2. specify `data table` report type

### Where are you hosting Actual?

None

### What browsers are you seeing the problem on?

Desktop App (Electron)

### Operating System

Windows 11

**Comment by youngcw** [comment]
This isn't really a bug, but I'll move it to a feature request

**Comment by kcollett** [comment]
Note potential duplicates #4132 and #3925. (Maybe just fix the bug?)
