### ISSUE TITLE
[Bug]: Date filtering by month triggers crash

### ISSUE THREAD

**Issue by biohzrddd** [actualbudget/actual#406]
### Verified issue does not already exist?

I have searched and found no existing issue

### What happened?

See below video. In accounts: Filter > Date > Change Date to Month > RangeError

Additionally, we should be consistent in the date format used for filtering Date, Month and Year and converting between them should pick a sane value based on the previous selection.
**Currently**
Date: yyyy/mm/dd
Month: mm/yyyy
Year:

**Ideally**
Date: yyyy/mm/dd
Month: yyyy/mm
Year: yyyy

https://user-images.githubusercontent.com/10577752/209000486-d58d8652-0b6b-43c9-a60a-7151f1957610.mp4

### What error did you receive?

RangeError: Invalid time value
format
node_modules/date-fns/esm/format/index.js:363

  360 | var originalDate = toDate(dirtyDate);
  361 | 
  362 | if (!isValid(originalDate)) {
> 363 |   throw new RangeError('Invalid time value');
      | ^  364 | } // Convert the date in system timezone to the same date in UTC+00:00 timezone.
  365 | // This ensures that when UTC functions will be implemented, locales will be compatible with them.
  366 | // See an issue about UTC functions: https://github.com/date-fns/date-fns/issues/376

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 10

**Comment by Kidglove57** [comment]
This is odd in that personally I cannot reproduce this crash. I have tried in both Firefox and Safari.

**Comment by manuelcanepa** [comment]
This can be fixed editing this file: https://github.com/actualbudget/actual/blob/master/packages/loot-design/src/components/DateSelect.js#L331

Adding an if:

```
              if (date instanceof Date && !isNaN(date)) {
                onSelect(d.format(date, 'yyyy-MM-dd'));
              }
```
