### ISSUE TITLE
[Feature] Choose budget frequency

### ISSUE THREAD

**Issue by ElDubsNZ** [actualbudget/actual#4060]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Most budgeting apps are based around the American system of being paid monthly. But in many places, paycheques are weekly or even fortnightly (2-weekly for Americans).

For people paid monthly, this works great, they can plan ahead for their next paycheque, but for the rest of us, we have to awkwardly plan 2-4 "and a bit" paycheques in one budget period. It really diminishes the usefulness of the budget for me as a fortnightly paid person.

### Describe your ideal solution to this problem

Allow us to choose our budget frequency by setting a start date and an end date that match our pay period. For example, my last pay day was 24 December, so I would pick 2024-12-24 to 2025-01-06. Actual would then set pay periods every 14 days.

I have no doubt this would be a major restructure of how budgets are coded and organised, but it would bring so much benefit to those of us who aren't paid monthly.

Switching between budgets might have to be impossible. Merging from smaller periods to larger periods is easy enough, just combine the periods, however splitting down, Actual would have no way to know which fortnight to put the budgeted amount into. So I suspect it'd be easier if there's just different budgeting databases for each frequency.

As for UI, instead of showing the month, it would show the period you've selected.

### Teaching and learning

Depending on how it's built, this would be either something chosen when creating a new budget, or it's something you can change in the budget menu. You could recommend people set it based on their pay frequency.

**Comment by rotech** [comment]
Just another note here.  This would make reporting useful for those of us not paid monthly.  I (along with most people in my country) are paid fortnightly every second Monday, this means most months I get two pays, but occasionally there are three pays in a month, this skews most of the reports.
