### ISSUE TITLE
[CI] Automatic tagging

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#449]
Small task:

We should create a github action that auto-labels new PRs that are opened with the "waiting for review" label.

**Comment by c00kie123** [comment]
I can try this!

**Comment by rich-howell** [comment]
We already have this - https://github.com/actualbudget/actual/blob/master/.github/workflows/opened-issues-triage.yml

**Comment by MatissJanis** [comment]
> We already have this - https://github.com/actualbudget/actual/blob/master/.github/workflows/opened-issues-triage.yml just needs amending to include PR's

@rich-howell that workflow works for **issues**. I'd like something similar for **PRs**.

**Comment by rich-howell** [comment]
> > We already have this - https://github.com/actualbudget/actual/blob/master/.github/workflows/opened-issues-triage.yml just needs amending to include PR's
> 
> @rich-howell that workflow works for **issues**. I'd like something similar for **PRs**.

Yes but we don't need a whole other workflow :) just add into this one.

**Comment by MatissJanis** [comment]
Ah. Yes, that works for me too.

--

**Another related feature request:** tag PRs as "stale" after 1 month of inactivity (is this even possible?).

**Comment by rich-howell** [comment]
Opened a pull request for this https://github.com/actualbudget/actual/pull/474

**Comment by MatissJanis** [comment]
Done
