### ISSUE TITLE
[Feature Request] Outdated version

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#463]
As a customer I want to be notified that the version of Actual I am using is outdated.

From an engineering POV we can use the Github releases API for this (at least for the frontend part).

When the customer opens the app: make a request to [Github releases API](https://docs.github.com/en/rest/releases?apiVersion=2022-11-28). Compare the "latest" version from there with what the current version is. If the version is outdated - show a "outdated" label somewhere (perhaps besides the "sync" label?) with a link to update instructions.

**Comment by j-f1** [comment]
It might be nice to have an “API” for this (like by hosting a JSON file on `actualbudget.github.io` somewhere) since it could also enable a server-provided notification in case there’s some sort of emergency issue in the future.

**Comment by winklevos** [comment]
If we used github releases could we plug in to that? But good idea, I have it through docker in the host, but certainly beneficial
