### ISSUE TITLE
[Feature Request]: Surpress welcome modal when budget exists.

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#476]
### Verified issue does not already exist?

I have searched and found no existing issue

### What happened?

I would like the ability to be able to disable the welcome to actual modal that appears when you login to Actual on a new device. If I had an active budget already configured and I log in on a new device don't show me the welcome modal.

**Comment by j-f1** [comment]
There are a couple of ways to approach this:

- check if you have any accounts before showing the dialog, and skip it if you do. **Pro**: guarantees you’ll never see the dialog again after you start using Actual. **Con**: people who start by importing a budget from YNAB/elsewhere won’t see the welcome dialog. Also requires some code changes to load the list of accounts before attempting to show the dialog.
- save both a per-browser and per-file setting for if you’ve seen the dialog, and propagate them to each other if one is `true`. **Pro**: first time users will always see the dialog if they start by creating/importing a budget. **Con**: if multiple people use the same budget, only one will see the dialog. Also, if you ever open a budget from someone else you will miss out on the dialog.

**Comment by 4-Leafs-Code** [comment]
What about saving a list of users per in the database and just cross-referencing to the user to the list. This way if the user has been welcomed he will not be again no mater what device or browser they log in from but if they access a different budget they would be welcomed. Also, if multiple user are accessing the same budget then they would all be welcomed only once for that budget. I do not know your code or what Database you are using but this is similar to "likes counter" we made for out post.

I think this solve your "con" concerns but that on my assumption that you have a user data base with login capabilities. I hope this helps.

**Comment by j-f1** [comment]
We don’t really have multiple users at this point (since there’s just one password for the server) but that could be an interesting future direction!

**Comment by 4-Leafs-Code** [comment]
Okay so another option is have the user sign in with a simple screen name like First.LastNames while your user base is small and set the list up so the user will only see the welcome screen 1 time when they set up their screen name and in the future when your user base grows move the welcome list validation to each of the budgets and off from the login.

**Comment by MatissJanis** [comment]
Jed has recently done some changes to the onboarding workflow and we no longer have the welcome modal. So this is done :)
