### ISSUE TITLE
[Bug]: mobile - budget page is broken (master branch)

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#488]
### Verified issue does not already exist?

I have searched and found no existing issue

### What happened?

- the budget header style is broken (too large compared to last release)
- budget sub-categories are no longer visible

<img width="266" alt="Screenshot 2023-01-20 at 20 48 47" src="https://user-images.githubusercontent.com/886567/213802598-c43304fd-95bc-4a04-bfd1-e60049360304.png">

### Where are you hosting Actual?

None

### Operating System

None

**Comment by MatissJanis** [comment]
Last release: 
<img width="274" alt="Screenshot 2023-01-20 at 20 50 11" src="https://user-images.githubusercontent.com/886567/213802803-9f428d29-70cf-46f9-9d1f-aa798cd4b1b4.png">

**Comment by j-f1** [comment]
Bisecting now, 4b90e371869120a43adb9ef378b6d72c3691eb81 is good and 20c7abc1504d18f1498c771284d5deb60557880d is bad.

**Comment by j-f1** [comment]
31792b32828da5aebca483fa47cfb0c297eb9cb3 is the first bad commit
commit 31792b32828da5aebca483fa47cfb0c297eb9cb3
Author: Trevor Farlow
Date:   Mon Jan 16 11:41:47 2023 -0700

> mobile: disable edit on tap of category balance (#471)
> * mobile: disable edit on tap of category balance
> * fixup! mobile: disable edit on tap of category balance

`.../desktop-client/src/components/budget/MobileBudgetTable.js | 11 -----------`
 1 file changed, 11 deletions(-)

**Comment by j-f1** [comment]
Weird, not sure why that should cause the issue (cc @trevdor?)

**Comment by MatissJanis** [comment]
I think this line is bad:
https://github.com/actualbudget/actual/commit/31792b32828da5aebca483fa47cfb0c297eb9cb3#diff-60e094a44d38fac03fb722c1cf8eb9ddafcf42fbd2d15c0c9f4c3b7d1ec90474R337

Should be:
```diff
- return <div>{() => content}</div>;
+ return <div>{content}</div>;
```
