### ISSUE TITLE
[Feature] Wildcard on payee

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#493]
### Discussed in https://github.com/actualbudget/actual/discussions/445

<div type='discussions-op-text'>

<sup>Originally posted by **freefrank** January 12, 2023</sup>
Like options on note, need to filter out payee for rules.
In my case, there are payees like 
`Online Banking Transfer - 9533` which 9533 is the transaction number, and I have alot of these transaction which should be classified into the same category.</div>

**Comment by j-f1** [comment]
This is somewhat covered by “Contains” but there is definitely room for improvement!

**Comment by MatissJanis** [comment]
Given the defined problem is already solvable by the usage of "contains" - I'll close this feature request.
