### ISSUE TITLE
[Bug]: Transfer allowed from same account

### ISSUE THREAD

**Issue by biohzrddd** [actualbudget/actual#495]
### Verified issue does not already exist?

I have searched and found no existing issue

### What happened?

I'm not seeing a valid reason to "transfer" money from account A to account A and think we should remove the current account from the list. 

### What error did you receive?

Account > Add transaction > Payee/Make Transfer button > Listing accounts allowed for transfer includes the current account.

![image](https://user-images.githubusercontent.com/10577752/213930625-4c0404eb-aa23-4540-ac85-fbc45df3068b.png)

Adding the account A to A transfer gives two pointless transactions.

![image](https://user-images.githubusercontent.com/10577752/213930759-bcaea6c9-6b21-4a41-b77b-671e4f0ec5ee.png)

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 10

**Comment by rich-howell** [comment]
Confirmed, this is still present in the latest 2023.1.xx version of Actual.

**Comment by rich-howell** [comment]
This is still an issue.
