### ISSUE TITLE
[Feature Request] Implementing Goals

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#496]
### Discussed in https://github.com/actualbudget/actual/discussions/169

<div type='discussions-op-text'>

<sup>Originally posted by **mohammedshariqnawaz** July  4, 2022</sup>
Hey guys, I have been going over all the information over the past few days and I see that implementing "Goals" is in the roadmap. I wanted to ask if there is a timeline to it? And guidelines if I wanted to help implement it.</div>

**Comment by rich-howell** [comment]
This is being tested with an experimental feature here https://github.com/actualbudget/actual/pull/573

**Comment by j-f1** [comment]
Status report: a few contributors have been working on enhancing the experimental feature, both in terms of increasing the feature set of the `#template` DSL and sorting out bugs in how goal templates are evaluated. Once the feature set is relatively complete, we’d like to see a UI built out to allow people to set up goal templates without having to learn to use magic syntax in the category notes. When the UI is in place and we have some sort of migration from the existing DSL to the UI-based goals, we would love to enable this by default.

**Comment by MatissJanis** [comment]
Since we already have budget templates - converted this issue to "UI for goals".

Please vote on the issue if you want to see this eventually implemented.

**Comment by youngcw** [comment]
A related issue #1337.  When a UI is started this would also be a good addition.

**Comment by youngcw** [comment]
related #2965

**Comment by wdpk** [comment]
related #2028

**Comment by youngcw** [comment]
related #1006.

**Comment by Chrobrego7** [comment]
I'm really hoping that this feature gets implemented.

**Comment by totallynotjon** [comment]
Related issue #6873 

When moving to a dedicated UI, we will lose the notes next to the template definition. So it will be useful to include a notes field in the goal UI so information about the purpose can be saved.

Another QOL addition would be numeric input fields that support arithmetic expressions
like "1000 / 12" to get a monthly value from a yearly, etc.
