### ISSUE TITLE
[FEATURE REQUEST] Translation

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#497]
### Discussed in https://github.com/actualbudget/actual/discussions/199

<div type='discussions-op-text'>

<sup>Originally posted by **manuelcanepa** August 22, 2022</sup>
Is planned to have text translations?</div>

**Comment by MatissJanis** [comment]
Some work to make this happen:
- https://github.com/actualbudget/actual/pull/249
- https://github.com/actualbudget/actual/pull/205

**Comment by MatissJanis** [comment]
Some notes here:

First, personally me (maintainer) am not sold on the idea that Actual needs localization support. Main reason being that it increases the burden on us (maintainers) to keep the languages up-to-date, invalidate old translations, etc. However if the community _really_ wants to have this: I'm not 100% against it.

Second, if we do decide to go ahead with localizations: I do not want to see `general.title.message` (dot notation) type strings in the codebase. Those just make things terribly difficult to understand. Prefer actual english text over a cryptic key (i.e. "Hello World!" over "home.title").

**Comment by gravelfreeman** [comment]
Just wanted to say that many users won't take the time to come to the Github but will install actual-server, notice it's only English and will immediately uninstall it. I would have liked to use it but it lacks accessibility. The #1 rule in accessibility is language. I'm available to do the French translation and maintain it, just contact me on Github.

**Comment by Kiskadee-dev** [comment]
Translation are a must have, it seems to be a cool project but sadly i can't implement it to common users here due to the lack of accessibility.

**Comment by MatissJanis** [comment]
https://github.com/actualbudget/actual/issues/3329
