### ISSUE TITLE
[Feature] Detect when running under actual-server and set up server automatically

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#499]
### Discussed in https://github.com/actualbudget/actual/discussions/424

<div type='discussions-op-text'>

<sup>Originally posted by **j-f1** January  2, 2023</sup>
If the Actual web app is running under the Actual server, it should automatically configure the current domain as the server when first run. This is a sensible default IMO, and people can always change the domain if they want to. It might make sense to expose the default domain as an option on the server, with the default being `location.origin` from the client side.</div>

**Comment by MatissJanis** [comment]
This would be a great addition IMO. Especially for first-time users. It essentially reduces the set-up by 1 step.
