### ISSUE TITLE
"Your data is still out of sync"

### ISSUE THREAD

**Issue by slater1** [actualbudget/actual#5]
If I import a YNAB4 budget from zip file in Firefox 99.0.1 on Windows 19043, I get the error 

```
Your data is out of sync
There was a problem syncing your data. We can try to repair your sync state to fix it. [Learn more](https://actualbudget.com/docs/overview/syncing-across-devices/#debugging-sync-issues)
```

![image](https://user-images.githubusercontent.com/2089725/166070289-a3629539-bde4-4ce7-bcf0-a7f328dce348.png)

If I click `Repair` I get the error

```
Your data is still out of sync
We were unable to repair your sync state, sorry! You need to reset your sync state. [Learn more](https://actualbudget.com/docs/overview/syncing-across-devices/#debugging-sync-issues)
```

![image](https://user-images.githubusercontent.com/2089725/166070340-50d3a5a2-dc46-44b1-9a3b-295faf460526.png)

If I click `Reset sync` and refresh the page, the first dialog is shown again. After I refreshed the page, my budget was lost and a previously deleted budget has taken its place.

**Comment by cuken** [comment]
@slater1 can you provide a simple ynab4 export for us to help troubleshoot with. Nothing with your actual data on it.

**Comment by slater1** [comment]
@cuken I created an anonymized YNAB4 file (transactions and PII removed) but the bug does not occur. Attaching anyway. I did notice when importing this anonymized budget that my already-added budget disappeared from the budget list, just like before
[2022test~5C8D4E6C.ynab4.zip](https://github.com/actualbudget/actual/files/8595435/2022test.5C8D4E6C.ynab4.zip)
.

**Comment by slater1** [comment]
I'll follow up if I can create a good repro

**Comment by jlongster** [comment]
I figured it out. So sorry about this. See https://github.com/actualbudget/actual-server/issues/23

**Comment by slater1** [comment]
Resolved per comment

**Comment by rich-howell** [comment]
This has been resolved as per https://github.com/actualbudget/actual-server/issues/23 closing with resoloution.
