### ISSUE TITLE
[Feature] Regex Rules -

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#500]
### Discussed in https://github.com/actualbudget/actual/discussions/395

<div type='discussions-op-text'>

<sup>Originally posted by **snovak** December  1, 2022</sup>
I think it would be very powerful to introduce Regex matching, or some simple pattern matching, for Rules.

Here is a mockup of what the UI might look like.  The two bottom rules should achieve the same result with far less configuration.
![RuleMatches](https://user-images.githubusercontent.com/317561/205163741-364535f6-ae70-4621-b25a-92e398eb62ea.png)
</div>

**Comment by Bryce-MW** [comment]
Additionally, it would be very useful to be able to use captures from the regex in the actions. I have quite a few rules checking for `notes is DEPOSIT;XYZ;Electronic Funds Transfer -> set payee to XYZ` because my bank doesn't always set the payee. Though of course this would be more difficult to implement. I can take a look at some point but I don't exactly use JS often.

**Comment by quangkieu** [comment]
From reading the code, Actual already support sql "like" function. Use "_" for single char wildcard, % for multiple character wildcard. I do not see any escape character so right now you would not able to search for literally % or _

**Comment by quangkieu** [comment]
From reading the code, Actual already contains rules is sql "like" function, which use "_" for single char wildcard, % for multiple character wildcard. I do not see any escape character so right now you would not able to search for literly % or _

**Comment by esseti** [comment]
Will this also be able to do a rule to remove, or partially remove, a string from notes?
such as:

`Payment via ATM DATE-TIME OP. 02-07-2024 12.17.00 GAMESTOP" -> "[02-07-2024 12.17.00] GAMESTOP"

**Comment by CrazyKidJack** [comment]
Hasn't this already been implemented?
I mean I don't know if the capture groups are implemented... but there is a "matches" option for rules isn't there?

From current desktop app:
![image](https://github.com/user-attachments/assets/aeb81964-82cb-43e5-bcb1-5a866370d01b)

**Comment by DenizUgur** [comment]
Not sure if it's related to this feature as well but having the ability to use RegEx match groups would be fantastic. For example, I have intra-account transfers marked with a 4-digit transfer code on the payee, and receiving transactions makes that available in the notes. So matching those numbers via regex would be a godsend.
