### ISSUE TITLE
[Feature] Allow to change account type

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#501]
### Discussed in https://github.com/actualbudget/actual/discussions/419

<div type='discussions-op-text'>

<sup>Originally posted by **crorodriguezro** January  1, 2023</sup>
Allow to change account type and off / for budget.</div>

**Comment by MatissJanis** [comment]
👋 This sounds like an easy thing to do, but in fact it's very complex and hence, in my opinion, not worth the effort to build and maintain it. The easy solution is: create another account and then just transfer over all the transactions.

If that doesn't work, then I'd be interested to hear more details about the problem you're trying to solve.

I'll close this feature request in the meanwhile. But please feel free to reopen.

**Comment by rgkirch** [comment]
I just installed actual-server and I was pretty excited to see what it can do. I added an account and then started reading some docs. I realized that I wanted to change the account to off-budget and looked around the ui for a way to do that. After a while, I'm here and I'm feeling frustrated and sad.

**Comment by j-f1** [comment]
Does bulk-moving the transactions to an off-budget account not work for you @rgkirch?

**Comment by Kidglove57** [comment]
@rgkirch  believe the method recommended by @j-f1 is that which is also used in apps like YNAB. This issue is certainly not unique to Actual.

Although great care is needed to adjust the allocations in the budget itself where necessary.

**Comment by Kidglove57** [comment]
That is very fair @rgkirch. @j-f1 and developers - how difficult would it be to help new users by adding some dialogue in the Create Accounts screen alongside the "off budget"" tick box? Perhaps along the lines of:
[ ] "Off Budget (cannot be changed later)

**Comment by rgkirch** [comment]
Thank you!
