### ISSUE TITLE
[RFC] Auto Categorisation Behaviours

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#502]
### Discussed in https://github.com/actualbudget/actual/discussions/461

<div type='discussions-op-text'>

<sup>Originally posted by **winklevos** January 14, 2023</sup>
## Description
Add setting to configure the auto categorization mode and add additional modes of auto categorization.

Currently Actual will automatically create a rule to categorize a payee, I will call this `Automatic Learning`. It functions as described under Automatic Learning.

---

I would like to add the below additional options, configurable in the settings page. 

Auto Categorization Mode:
- `Automatic Learning` (default)
- `User Directed`
- `Always Prompt`

### Automatic Learning

Actual will automatically create a rule once you have categorized a payee enough times. 

#### Logic

1. You categorized the latest transaction for that payee.
2. You have manually categorized that payee to that category 3 or more times
3. This is scoped to the last 6 months and 180s forward.
https://github.com/actualbudget/actual/discussions/246

### User Directed

This option would be my personal preference 

#### Logic
1. If you categorize a transaction and the payee does not have a rule setting a category. Create a rule and update any other matching uncategorized transactions.
2. If you re-categorize a transaction with a rule setting another category prompt to update rule. (edit-rule modal)

### Always Prompt

Whenever a category is set or changed on a transaction ask for action. 
- Just this transaction
- This and future transactions
- This, uncategorized, and future transactions
- All matching transactions (re-categorize if required)

## Parting thoughts

Please let me know what you think, or if you have another bit of logic to suggest</div>

**Comment by MatissJanis** [comment]
👋 Closing this off due to inactivity.
