### ISSUE TITLE
[Feature] Dashboard and Charts

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#503]
### Discussed in https://github.com/actualbudget/actual/discussions/402

<div type='discussions-op-text'>

<sup>Originally posted by **winklevos** December 12, 2022</sup>
Adding this here to capture ideas for charts in Actual.

Some ideas in https://github.com/actualbudget/actual/discussions/39 </div>

**Comment by MatissJanis** [comment]
Closing as duplicate of: https://github.com/actualbudget/actual/issues/507
