### ISSUE TITLE
[Feature Request] Indicator for negative category balance

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#509]
### Discussed in https://github.com/actualbudget/actual/discussions/171

<div type='discussions-op-text'>

<sup>Originally posted by **shall0pass** July  2, 2022</sup>
It would be a nice enhancement if there was some sort of indicator that a category was over spent.  This flag would ignore categories that are marked for rolling over a negative balance to the next month.  The attached screenshot is one example of how it could be implemented, though I'm sure it could be made to look much nicer.
The flag would not be visible if there is no overspending found. 

<img width=360 src=https://user-images.githubusercontent.com/20625555/177001912-a80ba1c9-53b3-48ff-beb8-b1f47190c1db.png>
.</div>

**Comment by j-f1** [comment]
I think the existing red coloring of overspent categories could be enough here but maybe we should adjust the coloring of rolled over overspent categories to make them less severe looking?
