### ISSUE TITLE
[Feature] Customizable backup naming template

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#510]
### Discussed in https://github.com/actualbudget/actual/discussions/261

<div type='discussions-op-text'>

<sup>Originally posted by **rich-howell** October  3, 2022</sup>
Ability to select or create a custom backup naming template. 

When you export your data from actual, a template to enable custom naming and versioning if the backup is taken more than once per day E.G. yyyy-mm-dd-1.zip, yyyy-mm-dd-2.zip</div>

**Comment by rich-howell** [comment]
I have submitted a PR that solves this #580

**Comment by MatissJanis** [comment]
> I have submitted a PR that solves this #580

IMO your PR is a step in the right direction, but not fully what the feature request was about.

How I read the feature request: the person wants to have a new field where you select the export format. And then depending on your selection - you either get `yyyyMMdd`, `MM-dd-yyyy` or some other format.

But your PR is still a step in the right direction and I think it's worth releasing it. :)

**Comment by rich-howell** [comment]
It was actually my idea to begin with, I changed my mind and thought just adding the date would be good enough.

**Comment by MatissJanis** [comment]
Oh. haha, I did not notice that :)

Sorry for my assumption.
