### ISSUE TITLE
[Feature] Manually categorise transactions as Upcoming

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#514]
### Discussed in https://github.com/actualbudget/actual/discussions/253

<div type='discussions-op-text'>

<sup>Originally posted by **isiko** September 26, 2022</sup>
I don't see a good way to add one-time Transactions that haven't happened yet. If the Transactions are part of a schedule, they are shown as "Upcoming", it would be nice to be able to flag manually added transactions like that too.</div>

**Comment by joaociocca** [comment]
second that! I don't know how to help on coding, but I can help on testing... since I suffer from this terribly =p I didn't even knew there was a "Upcoming" feature, until I saw this one today... and it's really weird that things with a date AFTER the new "Upcoming" transaction show as before it. Maybe make it so all transactions beyond current day show up as Upcoming?
![image](https://user-images.githubusercontent.com/6473725/229247586-3317c9f2-3695-4863-93e7-0086ffdca3f5.png)

**Comment by Kidglove57** [comment]
May also link in with [550]()display running balance against upcoming transactions (as a forecast feature?)

**Comment by atgrey24** [comment]
Reviving this old request. I don't like the current behavior where future transactions post immediately and are available to be budgeted, and creating schedules for one time transactions is clunky. I would go so far as saying future transactions should be treated as scheduled/upcoming by default, but understand if that's a step too far.

**Comment by BreaklessMonkey** [comment]
I would also like future transactions entered manually, not to be taken into account for the balance of the accounts
This issue is marked as closed but I did not find a way to change this in Actual

**Comment by alex-t-grey** [comment]
> I would also like future transactions entered manually, not to be taken into account for the balance of the accounts This issue is marked as closed but I did not find a way to change this in Actual

@BreaklessMonkey You can use schedules to enter future transactions without affecting current balances. It's a bit clunky when all you want to do is enter a one-off transaction, but it does work.

**Comment by youngcw** [comment]
You can now create schedules inline in the budget table.  Set a transaction date to be in the future and you will get prompted if you want that transaction to be a schedule or not.
