### ISSUE TITLE
[Feature] Import date format to match settings data format on default

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#516]
### Discussed in https://github.com/actualbudget/actual/discussions/216

<div type='discussions-op-text'>

<sup>Originally posted by **winklevos** August 28, 2022</sup>
It would be nice if the date format default for imports matched the set date format in the settings. 

I have `DD/MM/YYYY` in the settings but it defaults to `MM/DD/YYYY` when i import transactions. </div>

**Comment by MatissJanis** [comment]
👋 @winklevos this sounds like a bug to me. Would it be possible for you to provide the reproduction steps + example import file?

Thanks!

**Comment by j-f1** [comment]
Here’s the relevant code:

https://github.com/actualbudget/actual/blob/b6d8f867a86f0c819dd4532f507ba1e65f86f7e1/packages/loot-design/src/components/modals/ImportTransactions.js#L136-L149

**Comment by MatissJanis** [comment]
👋 I think this has been fixed in one of the last releases. If the issue still exists after updating - please let us know by opening a new issue.
