### ISSUE TITLE
[Feature] Custom amount on post transaction

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#518]
### Discussed in https://github.com/actualbudget/actual/discussions/248

<div type='discussions-op-text'>

<sup>Originally posted by **manuelcanepa** September  8, 2022</sup>
I was thinking that will be nice set the amount on `post transaction` instead of just modifying after post. That way you can post on just one step.</div>

**Comment by MatissJanis** [comment]
👋 @manuelcanepa I don't quite understand this. Could you please clarify what you mean?

**Comment by manuelcanepa** [comment]
Sometimes, the schedule is like a reminder, you have the energy bill that need to be paid once a month, usually pay around $100, some months you pay $140, on the next you pay $90. What i suggest is to focus on amount field or even a popup to set the real amount when you choose `post transaction` on the selected schedule. If you missed the date and pay later, the transaction will be posted on the past, the date that you set and the amount that you set, but need to be finded and changed (Date and amount)

**Comment by MatissJanis** [comment]
Got it: so we're talking about this option in the schedules table

<img width="368" alt="Screenshot 2023-01-25 at 20 41 53" src="https://user-images.githubusercontent.com/886567/214671219-e3fce7e5-53ff-471c-8b93-edde3dff4db4.png">

IMO makes sense to add some extra functionality here for people manually "posting" the transactions. Scheduled transactions can have exact amounts, aproximate amounts and a range. When it's an exact amount: we can just "post" without any extra modal. If it's aproximate or range - we could open a small window asking to provide the exact amount that will be posted.

**Comment by j-f1** [comment]
Here’s an example of the code to make that sort of UI:

https://github.com/actualbudget/actual/blob/686369868e20a93a75b68aa55c5959786dabaf4b/packages/desktop-client/src/components/accounts/Account.js#L190-L221

<img width="305" alt="Screenshot_2023-01-25 14 47 05" src="https://user-images.githubusercontent.com/25517624/214672923-8c7b7d3b-097f-4264-adad-c9b2d6928664.png">
