### ISSUE TITLE
[Feature] Checkbox to swap Payee/Notes on file import.

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#521]
### Discussed in https://github.com/actualbudget/actual/discussions/210

<div type='discussions-op-text'>

<sup>Originally posted by **pcchristie** August 25, 2022</sup>
Hi guys, 

I seem to remember this feature was in YNAB4. Unfortunately the QIF/OFX files are read incorrectly (or maybe created incorrectly) on my family member's bank account. The CSV import doesn't work seamlessly either. To avoid having to manually download and transform CSV data or begrudgingly accept all Notes being payees (and Payee fields being empty) it would be great to have a checkbox on the File Import Wizard in transactions.

Thanks</div>

**Comment by MatissJanis** [comment]
👋 @pcchristie would you mind providing an example YNAB4 export that is not working as expected? Without getting a way to reproduce it's pretty tricky to debug the problem.

I'll close this ticket for now, but please reopen if/when there is a way for us to reproduce the problem.

**Comment by corysell** [comment]
I hate to reopen this, BUT I'm running into this same problem in that my wonderful Credit Union loves putting all the real data in the Memo/Notes when I use my Debit Card, and the Payee is always "Withdrawal Debit Card W/D".

With YNAB, I literally told it to just swap them regardless of both fields having data, and this made the effort a LOT smoother.

Is there any way we can get that swap feature to occur even if the fields AREN'T blank?
