### ISSUE TITLE
[Feature] Add a filter to rules UI

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#523]
### Discussed in https://github.com/actualbudget/actual/discussions/160

<div type='discussions-op-text'>

<sup>Originally posted by **winklevos** August  7, 2022</sup>
Add a filter to the rules UI for quick searching, maybe support custom names</div>

**Comment by MatissJanis** [comment]
This is done.

Available in v23.2.5.

**Comment by sNiXx** [comment]
I can see that it is now possible to filter rules by using search-like functionality - nice!

I was wondering if adding groups or quick filters would make sense? I just started using Actual and already have quite a large number of rules. If I ever wanted to revise them - to see if they still make sense or if they are still needed - it would be quite time-consuming.
Or another idea: Have another field that stores when a rule was last applied?
