### ISSUE TITLE
[Feature] Add user support to Actual

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#524]
### Discussed in https://github.com/actualbudget/actual/discussions/157

<div type='discussions-op-text'>

<sup>Originally posted by **winklevos** August  6, 2022</sup>
User enhancements
    - User sign-in support
    - Multiple users per server support
    - Shared access to account support</div>

**Comment by rich-howell** [comment]
Discussed in https://github.com/actualbudget/actual/discussions/123

Originally posted by Quigley-Brendan July 5, 2022
I was one of those YNAB people who got their friends and family using YNAB. After a few price increases etc I'm finding it harder to recommend. But I could totally self-host an Actual Server (just found this app the other day). If accounts could be enabled on the server I could give the people in my circle their own account, potentially saving them a bit each year on the YNAB referral.

Any plans to make this happen?

**Comment by j-f1** [comment]
That’s a good idea! Thinking about how that would work, we’d fetch all of the encrypted keys from the server, then try the password against all of them. I’m not sure if there would be a way for us to grant access to only the budgets encrypted with a given key in the backend since there isn’t exactly a way to prove that we can decrypt that key. But I think that’s definitely a good approach to investigate more!

**Comment by jakobbouchard** [comment]
@j-f1 I haven't checked how the backend works at all (very new to Actual Budget), but considering the encryption keys are in a database already, couldn't it be possible to add a table to know which key is related to which file? Or it could also just use multiple databases, just split into subfolders according to the username (i.e. `username/account.sqlite`).

**Comment by Scot-Survivor** [comment]
I'm surprised the demand for this isn't higher. With those with families. It would be brilliant to have a little raspberry pi hosting actual for the whole family to be able to use (and safely, without worrying about other family members) 

Shared files allowing to budget with roommates or partners. 

And obviously the fact that not everyone has the ability to set this up, but the chances are they have a nerdy friend who can, but having to setup 1 server (and this subdomain) per user is more work than it's worth to say the least. 

Is there a branch or current PR where this is being worked on, I'd love to help out.

**Comment by j-f1** [comment]
@jakobbouchard We already store separate encryption keys for every file that has encryption enabled (it’s optional).

**Comment by j-f1** [comment]
@Scot-Survivor I don’t know of anyone working on this at the moment, but feel free to pitch your idea for how this would work!

**Comment by j-f1** [comment]
Potentially relevant: https://github.com/actualbudget/actual-server/pull/219 (we hope to merge that PR soon)

**Comment by Scot-Survivor** [comment]
Just pulling the discussion from Discord, as per @j-f1 , it would be possible to add a username field when logging, and only serve the associated files to that user. 
However, some additional things would be required:
- Admin Account (and management?)
- Admin Dashboard (Reset user passwords, remove users, add users?)
And then from me myself I'd like to see:
- See stats, such as storage per user. 
- Enforce End to End Encryption.
- Enforce 2FA on the admin (this should probably be added for all users, I think I saw an issue with this?)

Does anyone else see something I'm missing?

**Comment by j-f1** [comment]
Seems reasonable except for the 2FA bit — would like to see use of passkeys instead of requiring more complex security measures if possible.

**Comment by Scot-Survivor** [comment]
True, if I recall correctly there's a library that can handle both 2FA & Passkeys, I personally don't own a pass key so I'm left with having to use 2FA codes.

**Comment by Gandalf-the-Blue** [comment]
I am currently sharing my instance of Actual with my sister. We use the same password for logging in but then have our separate budget files, E2E encrypted. The only problem I see with this setup is either user can delete the others' file without problem. If a temporary fix to input the E2E password before deleting a file is added it would solve this issue at least temporarily.

**Comment by Scot-Survivor** [comment]
Is there anyone working on this at the moment?

**Comment by akshay7394** [comment]
+1 on this from me too

**Comment by S4GU4R0** [comment]
This has the second most upvotes outside of Plaid integration. When perusing other feature requests with less votes, there are tasks done. Is it possible to get an update and some clarification on this? Thank you.

**Comment by rich-howell** [comment]
> This has the second most upvotes outside of Plaid integration. When perusing other feature requests with less votes, there are tasks done. Is it possible to get an update and some clarification on this? Thank you.

Unfortunately, the up votes never seem to mean anything, feature requests are done on a contributor basis based on what someone fancies doing, the core team rarely looks at the top voted features and implements them. 

- Dark mode for example got implemented because someone knew how to do it and wanted it not because it had lots of votes.
- Transaction lock was implemented because a fork of Actual implemented that and pushed the changes upstream, again not because it had a lot of votes. 

Have a read of this https://actualbudget.org/docs/contributing/leadership/new-core-contributors-guide "We do not assign specific roles or responsibilities but instead allow people to choose what they want to work on."

**Comment by Kidglove57** [comment]
> Unfortunately, the up votes never seem to mean anything, feature requests are done on a contributor basis based on what someone fancies doing, the core team rarely looks at the top voted features and implements them.

Like you, I’m not clear as to what (or whether) there is a process for looking at up votes but I guess the hard reality is the volunteer developers will only work on those things that really appeal to their particular use case. Regrettably, I’m not clear how in an open source, volunteer led, project it can really be much different.

**Comment by rich-howell** [comment]
> > Unfortunately, the up votes never seem to mean anything, feature requests are done on a contributor basis based on what someone fancies doing, the core team rarely looks at the top voted features and implements them.
> 
> 
> 
> Like you, I’m not clear as to what (or whether) there is a process for looking at up votes but I guess the hard reality is the volunteer developers will only work on those things that really appeal to their particular use case. Regrettably, I’m not clear how in an open source, volunteer led, project it can really be much different.

What is the point in the votes then? 

You could still have a team of volunteer developers who volunteer their time to work on Actual, tasks could be assigned to that team but that isn't how it works, however some aspects of the project are structured in a way that makes it seem like that is how it works.

I volunteer at a local railway, I don't get to just turn up and do what I want, the railway has a plan and I have to do what I am told, I couldn't just draw a pretty picture of a train in a different colour walk around the yard and get 100 signature's and then paint the train like my picture.

**Comment by ElDubsNZ** [comment]
If we can get multiple accounts, it'd be great if we could also jointly control accounts.

i.e. I'd love if my wife and I could have our own accounts, but on top of that, if our shared account were added, it could show up on both our accounts, and sync with each other. It would make budgeting shared spending way easier.

**Comment by urjeetpatel** [comment]
One more item that user management should ideally add is to allow user accounts to be disabled. This way external authentication / sso at the reverse proxy level can be used. I.e. Forward auth using Traefik etc.

Would it be possible to add this to the user support wishlist.

**Comment by o-mintaka** [comment]
I was looking if there's any option to give read-only access to a budget. This feature request seems to be a good fit for that, wdyt?

In my particular case, my wife wants to have access and check our budget status but she isn't very comfortable with all the edit options that are possible (she is a mobile user and it annoys her that when she's looking around, she misclicks and opens edit boxes). I can also imagine that this would be a nice feature for other cases, like sharing budgets with your kids.

And alternative option could be to use a kind of public key for the budget, where it's possible to read data but all write/edit options are not possible and disabled.

**Comment by youngcw** [comment]
🎉 initial support for multi user and OIDC was added in #3878 and will be available starting in v25.1 🎉
