### ISSUE TITLE
[Feature] Support importing transactions over multiple accounts at once

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#525]
### Discussed in https://github.com/actualbudget/actual/discussions/158

<div type='discussions-op-text'>

<sup>Originally posted by **winklevos** August  6, 2022</sup>
In import UI select specific account or use a column of the data to define the related account</div>

**Comment by MatissJanis** [comment]
@winklevos could you please elaborate on your idea?

Thanks

**Comment by lanmaster53** [comment]
I'll provide some context. When I export an OFX file from my bank, it includes transactions for 4 different accounts. When I import that OFX into YNAB or other budgeting software, they allow me to select which local account is associated with each account listed in the OFX file, then imports the transactions accordingly. When I try to import the same OFX in Actual, whichever account I am in when I import receives all of the transactions.

I think the OP was referring to a way to do this with CSV files by having all transactions in a CSV file, with a column that indicated which account each transaction should be imported into. Same thing I'm after, but a different file type.

Does that help?

**Comment by j-f1** [comment]
Can you share an example of one of these files (with any identifying details you’re not sharing redacted)? It will be a fairly significant undertaking to add an account field to the import dialog since the current import logic is fairly tightly designed around importing to a single transaction, but the underlying parser does seem to support pulling out the account name. Opened https://github.com/actualbudget/actual/pull/670 but I don’t plan on working on this too much more in the near future.

**Comment by lanmaster53** [comment]
Just a standard OFX file. You can find them on the internet, but see a simple one attached. I had to change the extension to txt for Github, but should be ofx.

[sample.txt](https://github.com/actualbudget/actual/files/10786197/sample.txt)

**Comment by lanmaster53** [comment]
Also, this isn't nearly as urgent as the other issue I posted about transaction merging. I can make do with individual account importing, but I can't use Actual without manual transaction merging. Thanks for what you're doing. As a fellow open source developer, I know the thankless work you put in.

**Comment by djcurley89** [comment]
[Multiple Account Transaction Example - Piere.csv](https://github.com/user-attachments/files/25472118/Multiple.Account.Transaction.Example.-.Piere.csv)

Here's an example of a CSV with transactions from multiple accounts that I get from Piere. Would really love if this could be integrated into AB as a way of importing regularly.
