### ISSUE TITLE
[Feature] New UI for creating and modifying Categories and Category Groups

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#526]
### Discussed in https://github.com/actualbudget/actual/discussions/150

<div type='discussions-op-text'>

<sup>Originally posted by **winklevos** August  6, 2022</sup>
A stand-alone UI page for Category management

Ideally also support importing categories and groups for migrations</div>

**Comment by MatissJanis** [comment]
👋 @winklevos May I ask: why? What problem would this solve?

**Comment by MatissJanis** [comment]
Closing as inactive.
