### ISSUE TITLE
Reports provide a table view of the transactions

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#527]
### Discussed in https://github.com/actualbudget/actual/discussions/156

<div type='discussions-op-text'>

<sup>Originally posted by **winklevos** August  6, 2022</sup>
Add UI elements to access table of transactions in scope of the viewed report</div>

**Comment by MatissJanis** [comment]
@winklevos would you mind elaborating your idea?

**Comment by MatissJanis** [comment]
Closing it off due to inactivity.
