### ISSUE TITLE
[Feature] Split transcation based on %

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#528]
### Discussed in https://github.com/actualbudget/actual/discussions/155

<div type='discussions-op-text'>

<sup>Originally posted by **winklevos** August  6, 2022</sup>
Allow splitting of the transaction by % for cases where you may be expected to get paid for part of the transaction

additionally 
 - Ability to relate a part of a split transaction to a person
 - Ability to share/send detail of transaction split to person</div>

**Comment by MatissJanis** [comment]
👋 May I ask: why? What problem are you trying to solve with this proposed solution? Generally when you make a transaction: you pay in **X** amount, not **% of X**. Same thing about receiving money. You don't get 50% of 1$. You get 50 cents.

cc @winklevos

**Comment by rich-howell** [comment]
@MatissJanis This is for splitting a transaction by % I think, so you could split it based on a % instead of having to work out how much each person should pay. 

Maybe you went out for food with friends, you pay the total bill and split it by 5 which is 20% each.

**Comment by MatissJanis** [comment]
Ok, but still in your budget you would see a precise number of how much YOU paid, right? Not the grand-total of all the friends.

Or am I missing something?

**Comment by shall0pass** [comment]
If the desire is to split a transaction by %, Actual already supports math inside the cells.  So if you had a bill of $50, you could type in "0.2*50" for Derek, "0.2*50" for Tommy, "0.5*50" for Dan, etc. 

It doesn't really address sharing the split with a friend, but I don't know what that would look like.

**Comment by rich-howell** [comment]
@MatissJanis @shall0pass For a BUDGET I think this request isn't relevant here.

**Comment by MatissJanis** [comment]
@rich-howell you think this is relevant for the transactions table? I see the situation there being the same.

**Comment by rich-howell** [comment]
> @rich-howell you think this is relevant for the transactions table? I see the situation there being the same.

No, I don't think it is relevant at all.

**Comment by MatissJanis** [comment]
Great! So we're in agreement that this is a wont-fix (or wont-do?).
