### ISSUE TITLE
[Feature] Upload Attachment support for transactions

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#530]
### Discussed in https://github.com/actualbudget/actual/discussions/152

<div type='discussions-op-text'>

<sup>Originally posted by **winklevos** August  6, 2022</sup>
Ability to upload attachments to a transaction, tax receipts, invoices, etc for record keeping and easy tax time 

- add the ability to download .zip of all attachments related to tax tagged transactions for period</div>

**Comment by MatissJanis** [comment]
This is an interesting idea, but it will be very complicated to implement as you need to consider a lot of moving pieces (i.e. how will this work in dockerized environments? How will it work when using only the local version without sync? etc.)

(as an idea): would be interesting to allow implementing 3rd party integrations for this. So you're able to upload directly to google drive/dropdbox/other from the UI and then it links the uploaded file to a specific transaction.

**Comment by j-f1** [comment]
> how will this work in dockerized environments?

It should be fine, we could dump them in a subfolder of `user-files` (optionally as encrypted blobs if e2e is enabled).

> How will it work when using only the local version without sync?

I think for features like this (& bank syncing if we decide to do that) it makes sense to require a server.

**Comment by AuspeXeu** [comment]
This would be amazing so I could attach invoices etc. to transactions.

**Comment by WDMdanila** [comment]
Did not notice this one when opening this: https://github.com/actualbudget/actual/issues/1850
Closed my feature request

**Comment by TheBlueCircle** [comment]
I very much like the idea of linking to Google Drive or another provider. 

I could imagine selecting a specific folder in a cloud provider, then Actual handling the read/write from there (so you could upload to Actual but it actually stores it in Google Drive) without having to worry about copying/pasting a link for each file.

**Comment by vinstaal0** [comment]
Personally I would like to just store the files on my own server instead of the cloud, but that could be me

**Comment by croomacc** [comment]
Add Markdown support in Transaction Notes.  This will allow the user to add a link to a document/receipt stored at the location of their choice such as Google Drive.

**Comment by thiswillbeyourgithub** [comment]
Am too interested in this feature. For example for linking bills, pictures, screenshots, receipts, etc.

**Comment by AustinHarisch** [comment]
I echo what others have said here—being able to upload receipts, invoices, etc. in the same spot where I'm budgeting for and recording those transactions would be killer. I'm not opposed to integrating with a cloud storage option like others have mentioned, but it would be great if we had the ability to store those uploads to a local network resource like a NAS instead/in addition.

**Comment by diraol** [comment]
Hey folks, passing by to second this one too. It would make a huge difference for tracking things over here.
Either upload the file itself or be able to add a "link/local-file-link".

I am using nextcloud over here to save the receipts, synced locally, then it would be awesome to be able to at least have a field for the receipt link (or other "attachments").

**Comment by IeuanK** [comment]
Any movement on this? Other issues (as recent as #4782 last week) led me here, but this issue is also closed and the 'discussed in' link is dead. Would be a phenomenal feature to have.

**Comment by idolpx** [comment]
These are a few of the ideas I've been thinking about for this feature.
 
1. Simply store link in notes to receipt/invoice/etc from a network resource
2. Directly upload and link to one or multiple transactions
3. Integrate with Receipt Wrangler or Paperless-ngx to link transactions to documents in those systems

#1 is easiest and probably what I'm going to do for now but ideally I would like to link it up to Paperless-ngx.
I would like to have a way to expand the notes field to a multiline editor on the transactions page to display text, links, tags, attachments.

**Comment by dna113p** [comment]
Really like the paperless-ngx idea. It would be amazing if you could snap a receipt and use it as a transaction, or even be able to link it to an existing transaction and give some ability to auto split that transaction into different categories by receipt line item.

**Comment by vinstaal0** [comment]
> Really like the paperless-ngx idea. It would be amazing if you could snap a receipt and use it as a transaction, or even be able to link it to an existing transaction and give some ability to auto split that transaction into different categories by receipt line item.

This would be very nice, but basically the only way of doing this is with a UBL invoice.
Or the devs at AB will developed another solutions which isn't implemented in business software yet

**Comment by IeuanK** [comment]
> > Really like the paperless-ngx idea. It would be amazing if you could snap a receipt and use it as a transaction, or even be able to link it to an existing transaction and give some ability to auto split that transaction into different categories by receipt line item.
> 
> This would be very nice, but basically the only way of doing this is with a UBL invoice. Or the devs at AB will developed another solutions which isn't implemented in business software yet

That's not true, it'd be incredibly simple to allow inserting a receipt picture using a generic 'store pictures and do OCR' module, which could then feed back what is most likely on the receipt or at the very least attach the picture. Building it as a generic service module would then allow tying in Paperless, Receipt Wrangler, or any other image hosting service (could even just be an SMB share or even a local data directory) with OCR being an optional addition.  
Plenty of budgeting/bookkeeping tools support this, you do not need UBL invoices.  

I don't think anyone has to worry about 'business software' because Actual is a budgeting tool, not a business bookkeeping tool.

**Comment by codekiln** [comment]
> I have been working for nearly 10 years in the field with different software and different OCR software and it just doesn´t work that well

Wow, really? Even today with the latest omni models at Anthropic and Openai? Every time I drop in a pic and ask for a transcript, it seems like a perfect translation. I'm guessing, but it seems like fewer than 3% of images even have a single problem in my experience.

**Comment by vinstaal0** [comment]
> > I have been working for nearly 10 years in the field with different software and different OCR software and it just doesn´t work that well
> 
> Wow, really? Even today with the latest omni models at Anthropic and Openai? Every time I drop in a pic and ask for a transcript, it seems like a perfect translation. I'm guessing, but it seems like fewer than 3% of images even have a single problem in my experience.

The technology is there, but there is no implementation of it in a workflow or have it work together with things like bookkeeping software etc. Probably because most software is driven by the US and doing administration in the US sucks.

**Comment by kaizenlov** [comment]
Hi all, coming back to this in 2026. 

I am a new user of Actual and came in hoping this would be a feature. I note there are more upvoted / pressing work being done, but have added my vote for this and back the thinking.

For most people using Actual, I assume they have a) bank accounts with banks that have crap or non-customisable end user apps, and b) Actual. Especially if you have accounts with multiple banks etc., it's great that Actual becomes a source of truth...

...But if those people wanted to track receipts, invoices, digital order emails etc. in a central place against transactions they relate to, they are forced to create a **third** place to hold transaction data outside of A) and B). This very quickly becomes a large headache.

Seeing as though Actual has become the source of truth for a lot of us, it'd make sense to do this too.

Cheers
