### ISSUE TITLE
[Feature Request] Show better indication for inflow transfer or outflow transfer

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#533]
### Discussed in https://github.com/actualbudget/actual/discussions/166

<div type='discussions-op-text'>

<sup>Originally posted by **ariccb** August  2, 2022</sup>
is it possible to indicate as "in" or "out" or choose which direction these arrows point for transfers? For some reason my brain always associates going "right" as in, and "left" as out. That's the opposite of the default direction and makes things confusing for me. If there was a setting to choose the arrow direction, or to change from arrow to say "in" or "out" that'd be cool.
![image](https://user-images.githubusercontent.com/48956351/182409777-1a6e2469-efcf-404d-98f1-4185e623a00a.png)
</div>

**Comment by j-f1** [comment]
I see this can be confusing — and it might make sense to swap the arrows, but I’m not sure. I definitely don’t think adding an option is the right solution here.
