### ISSUE TITLE
[Feature Request] UI Change: Display category balance when assigning transaction

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#534]
### Discussed in https://github.com/actualbudget/actual/discussions/168

<div type='discussions-op-text'>

<sup>Originally posted by **meditatingCybermind** July  4, 2022</sup>
When creating a new transaction entry, display the current total of each category next to the category name in the category dropdown.

![image](https://user-images.githubusercontent.com/7494538/177220662-b0dfb3dc-0dca-4846-af9e-52f59d0c3eb0.png)

Implementation example in YNAB 4

![image](https://user-images.githubusercontent.com/7494538/177220700-f612073c-482c-402f-93b5-45eb004f7a88.png)

</div>

**Comment by MatissJanis** [comment]
I like this idea. But should we display the running balance there? Or perhaps how much is remaining in the budget? For me it would be more beneficial to know how much is remaining.

**Comment by JavaDogWebDesign** [comment]
I would also love to have this feature. This is how it is set up on Financier:
![image](https://github.com/actualbudget/actual/assets/50428613/d2084863-7d35-4687-813c-a4c8336ff071)

It uses the month's budgeted amount. Not the month's total spent.

**Comment by tjfinlinson** [comment]
> I like this idea. But should we display the running balance there? Or perhaps how much is remaining in the budget? For me it would be more beneficial to know how much is remaining.

I agree that seeing the remaining amount for the category/budget would be a nice addition to the transaction screen.

**Comment by SaveYourMoney** [comment]
This is the one thing I miss the most from YNAB.  Seeing the remaining amount in the budget category while entering transactions is something that I greatly miss.

**Comment by sebastiansaccount** [comment]
This feature requests points to [#555](https://github.com/actualbudget/actual/issues/555) (closed) while #555 points to this #534 which is closed as well.

I would highly appreciate the requested feature, because it's an elementary component of envelope budgeting imho. I can go into more detail, but the reasons given are already quite significant and I just wanted to ask if there is feature request loop with both feature requests being closed by purpose?

**Comment by youngcw** [comment]
@sebastiansaccount this request doesn't point anywhere.  I think what you are referring to is that this ticket was mentioned in the other duplicate one.

Actual uses a Lodash style of feature requests for organization. This feature request is still active since it still has the "needs votes" tag.

**Comment by sebastiansaccount** [comment]
Oh, I see 💡. Thank you very much for pointing it out. 
I gave it my upvote and maybe it will find its way into Actual at some point.
