### ISSUE TITLE
[Feature] Legacy Auto Transaction Scraper

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#535]
### Discussed in https://github.com/actualbudget/actual/discussions/144

<div type='discussions-op-text'>

<sup>Originally posted by **winklevos** August  2, 2022</sup>
I know scraping from HTML is not ideal. However, the proposed Plaid integration does not cover all countries or banks. 

A fallback, but less reliable method would be appreciated. 

I have a working model of this built on python django and selenium. I will look to port it over in a framework that is easily manageable for additions and fixes. </div>

**Comment by MatissJanis** [comment]
👋 @winklevos Actual already supports CSV imports. You should be able to create a python script that converts your HTML into a CSV and then you can go ahead and import that.

Closing this as we have no plans to support "HTML" type imports.
