### ISSUE TITLE
[Feature request] Resizable columns

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#536]
### Discussed in https://github.com/actualbudget/actual/discussions/172

<div type='discussions-op-text'>

<sup>Originally posted by **mekkanik** June 17, 2022</sup>
Currently when my balances or transaction values run into six digits, they are not showing up in the columns properly. It gets cut off with a '...' Resizable columns would go a long way in alleviating this issue.</div>

**Comment by cacti23** [comment]
@rich-howell please assign me this issue

**Comment by bstritesky** [comment]
Just leaving a comment so it has a few more keywords: resize, wider, width

**Comment by danielo515** [comment]
I wonder why nobody mentioned the word "tables", that is what I was looking for to upvote 😄

**Comment by sidoshi** [comment]
I was trying to work on this to get introduced to the codebase.

The balance values only show the ellipsis when there is no more room left on the screen. If we have a 2 month view, the balances are shown fine as there's more room available. Even if we add the feature to resize the columns, some balance will still have to show the ellipsis as there isn't enough room for all the columns to breathe. 

Looking at the number of votes on this feature request, I think I am missing something obvious. What is the motivation behind wanting to resize the columns instead of decreasing the visible months to create more space? Is it to have more control over which columns are fully visible and which are hidden while maintaining a higher visible months count?

<img width="1435" alt="image" src="https://github.com/user-attachments/assets/4523d5ad-ad6b-435f-8a1f-932edb888e8a" />
<img width="1431" alt="image" src="https://github.com/user-attachments/assets/12e1c4e8-b010-4de4-b7a0-debd9bcb1d4e" />

**Comment by danielo515** [comment]
> What is the motivation behind wanting to resize the columns instead of decreasing the visible months to create more space?

Some of us are willing to do horizontal scroll. I prefer to be able to see the whole information, even if for that I need to scroll horizontally back and forth. That is still easier than having to move from one month to another

**Comment by bstritesky** [comment]
> What is the motivation behind wanting to resize the columns instead of decreasing the visible months to create more space? Is it to have more control over which columns are fully visible and which are hidden while maintaining a higher visible months count?
I think the budgets area is fine. The transactions views should allow for resizing/reordering of the columns.

**Comment by alcroito** [comment]
My main use case would be to allow resizing the category names on the budget page, because i have some very long category names, especially when importing hidden category names from ynab4, and it's not possible to distinguish them because each 'subcategory' is prefixed with the main 'category'.

**Comment by Gepstra** [comment]
> I was trying to work on this to get introduced to the codebase.
> 
> The balance values only show the ellipsis when there is no more room left on the screen. If we have a 2 month view, the balances are shown fine as there's more room available. Even if we add the feature to resize the columns, some balance will still have to show the ellipsis as there isn't enough room for all the columns to breathe.
> 
> Looking at the number of votes on this feature request, I think I am missing something obvious. What is the motivation behind wanting to resize the columns instead of decreasing the visible months to create more space? Is it to have more control over which columns are fully visible and which are hidden while maintaining a higher visible months count?
>

For me this is the main issue: 
![firefox_K2vrJyVfMx](https://github.com/user-attachments/assets/91d7dc26-6099-4784-adb0-036367a0a54b)

Category names.

**Comment by Rick-Thomas** [comment]
> I think the budgets area is fine. The transactions views should allow for resizing/reordering of the columns.

I agree with you, but it is not only with the Account Registers where Resizing Columns would be useful, but also in the Schedules, where the amount ends up with "..." and there is a lot of room in Name, Payee and Account...

**Comment by JonoSK** [comment]
Why did this get closed? It hasn’t been implemented yet has it?

**Comment by lelemm** [comment]
> Why did this get closed? It hasn’t been implemented yet has it?

All feature request are closed and tagged as "need votes"

**Comment by dynek** [comment]
So we're stuck with fixed size columns?
No https://github.com/actualbudget/actual/pull/3445 and no https://github.com/actualbudget/actual/pull/3309 ?

Let's hope https://github.com/actualbudget/actual/pull/4573 progressed further.

**Comment by wfolta** [comment]
The OP mentions dollar columns, which evidently have ben fixed in 29.6.0, but I would like the other columns to be resizable. Account and Category can be much smaller and Payee and Notes would benefit from larger. At least for me, so resizable (with memory) would be quite nice.

**Comment by StephenBrown2** [comment]
> The OP mentions dollar columns, which evidently have ben fixed in 29.6.0, but I would like the other columns to be resizable. Account and Category can be much smaller and Payee and Notes would benefit from larger. At least for me, so resizable (with memory) would be quite nice.

Yes, that will probably come with the table rewrite that's been impending for a while. Lots of other things have been higher priority though, so it hasn't seen much movement.
