### ISSUE TITLE
[Feature] Schedules Summary

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#537]
### Discussed in https://github.com/actualbudget/actual/discussions/103

<div type='discussions-op-text'>

<sup>Originally posted by **raphaelbernhart** June 28, 2022</sup>
Hello there,

as I am currently playing with actual to maybe adopt it as my financial system I noticed a few basic features that are not yet implemented. Since the main goal of a financial system is that you can do a monthly planning, I'm missing a schedules summary, where you can see how many expenses you for sure have per month.

The simplest solution for this would be a simple summary at the end of the Schedules table. Something like this (of course I would have to work further on the UI):

![Bildschirmfoto 2022-06-28 um 14 49 02](https://user-images.githubusercontent.com/48283236/176182934-14b04ff8-d582-4cf9-baeb-15d01cd79bc0.png)

In a further step we could move the whole thing to the reports page.

If this idea is accepted, I will see if I can find time to work on this feature.
I also look forward to suggestions :D</div>

**Comment by rich-howell** [comment]
Would make more sense to have "Upcoming Transactions" shown in the budget overview, if we start showing monetry values in various places the budget becomes a nightmare to manage and maintain. 

![image](https://user-images.githubusercontent.com/22135084/215786857-e7035382-7931-4eb0-9f12-a9c1bfa166a4.png)

**Comment by Kidglove57** [comment]
1) I think somewhere there may be a feature request to have a running balance against those scheduled transactions that are showing as due soon on an account. I find this a great way to check when money needs to be moved across to an account to avoid going overdrawn.
2) This together with a goals feature to create a budget at the start of each month should go a long way to making sure that users are aware of upcoming costs and any issues in funding these. I.e. not budgeting to spend more cash than is available to you?

**Comment by joaociocca** [comment]
I came here to suggest both these features (the schedule summary and the upcoming showing on budget).
It's bittersweet to learn it's already been suggested :rofl: count me in to test these if needed =)

**Comment by Keviddle** [comment]
@youngcw This is not one of the most upvoted feature requests, but its a feature that I am personally interested in. I wasn't entirely sure whom of the main contributors to mention, so I chose you, because you classified this ticket at least :D and i did not find any other specification on whom to ask in the wiki

If this is a feature that the maintainers would generally appreciate or approve to have in the app, then I would like to implement it

**Comment by youngcw** [comment]
Feel free to put in a PR
