### ISSUE TITLE
[Feature request] Running balance update for upcoming transactions

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#539]
### Discussed in https://github.com/actualbudget/actual/discussions/173

<div type='discussions-op-text'>

<sup>Originally posted by **mekkanik** June 17, 2022</sup>
Letting the running balance column show a value for upcoming transactions would be a good way to look out if the account is gonna get slapped with overdraft fees, or worse, bounced payments.</div>

**Comment by youngcw** [comment]
I believe this can be closed.  Any objections?
