### ISSUE TITLE
[Feature] Please add the ability to change the currency

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#541]
### Discussed in https://github.com/actualbudget/actual/discussions/362

<div type='discussions-op-text'>

<sup>Originally posted by **Joeharrison94** May  7, 2022</sup>
Please allow the user to change the currency to GBP if posisble, thank you.</div>

**Comment by j-f1** [comment]
As far as I can tell, the app does not use currency symbols anywhere, I’m closing this feature request.

**Comment by neilmccreery** [comment]
In this same vien what about incorporating a feature to combine currencies? I have accounts in 2 currencies that I'd like to incorporate into the same server.

**Comment by Kidglove57** [comment]
Just so I understand more what it is folk are looking for here.

Actual does not currently set any specific currency - so the implication is that you simply budget in your home currency. No currency symbol therefore needed.

So am I right in thinking that what is being requested is multi currency support? At the moment (and I am happy to be corrected) that seems quite a leap into the future for what is fundamentally and envelope budgeting app.

**Comment by j-f1** [comment]
Agreed — how do you see this working? Do you want to be able to spend e.g. GBP from an account with a balance in USD? Can you transfer money from one account to another if they have different currencies? How do you compute the over/under budget amount for a category if the spending and the budget don’t match?

I’m honestly not sure this is a feature Actual will ever support because of the complexity. You might be better off manually labeling your accounts and categories with their currencies and then using split transactions to deal with inter-currency transfers.

**Comment by Kidglove57** [comment]
And how would Net Worth be calculated or a budget be created without pulling in currency exchange rates?

**Comment by neilmccreery** [comment]
I agree, multi-currency support is a step too far and adds too much complication to a very user-friendly app.

In keeping with the simplicity of the app, I'd suggest a simple solution: in the import window, when choosing field mappings, offer some sort of "exchange rate" input that the user can manually input/adjust. Then the software multiplies all the imported transactions by that number, thus effectively bringing those transactions into matching the "home currency" of the user. 

This would allow the user power over how often they want to adjust the exchange rate. If you're happy for it to be constant for the entire year, then import all of 2022 in one go. If you want a more accurate number then import each month individually with it's corresponding rate. Manually entered transactions are up to the user to adjust to the correct currency.
