### ISSUE TITLE
[Feature Request] Larger screen usage on budget

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#544]
### Discussed in https://github.com/actualbudget/actual/discussions/175

<div type='discussions-op-text'>

<sup>Originally posted by **RogerSik** May 31, 2022</sup>
Would be cool if more screen could be used. 

My categories have long names + the monthly to add sum and so the categories are abrupt.</div>

**Comment by cacti23** [comment]
@rich-howell assign me this issue.
