### ISSUE TITLE
[Feature Request] Ability to hide Categories

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#545]
### Discussed in https://github.com/actualbudget/actual/discussions/176

<div type='discussions-op-text'>

<sup>Originally posted by **sdrichter** May 12, 2022</sup>
One thing I found useful in YNAB was the ability to hide categories that are no longer needed. My use case for this is creating a category as a sinking fund to save towards some one-time purchase. Once that purchase is made, I want to permanently hide that category. Deleting the category is not ideal because it forces reallocation of the transactions in that category to another category.</div>

**Comment by MatissJanis** [comment]
👋 Agree with the idea: this would be a nice improvement in the budgets page.

**Comment by joel-jeremy** [comment]
@j-f1 Isn't this already implemented?

**Comment by j-f1** [comment]
Good catch!
