### ISSUE TITLE
click on arrow of transfer should take you to corresponding transaction in other account

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#547]
### Discussed in https://github.com/actualbudget/actual/discussions/340

<div type='discussions-op-text'>

<sup>Originally posted by **bpaulien** March  5, 2022</sup>
Since you're working on transfers, I moved this over from discussion 

When I do a transfer, the transaction has an arrow pointing to the account that the transfer came from.  I think it would be great if we could click on that arrow, and be taken instantly to the corresponding transaction in the other account.  See below for screen shot of transfer transaction.

![image](https://user-images.githubusercontent.com/6487363/144270010-3c75e827-eed9-4584-b78f-ddde0451daa3.png)

_Originally posted by @bpaulien in https://github.com/actualbudget/releases/discussions/133_</div>

**Comment by cacti23** [comment]
@rich-howell please assign me this issue.

**Comment by j-f1** [comment]
*impersonates bot since it isn’t working for some reason*

:tada: This feature has been implemented in #1228 and will be released in the next version. Thanks for sharing your idea! :tada:
