### ISSUE TITLE
[Feature] Request to duplicate transactions

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#548]
### Discussed in https://github.com/actualbudget/actual/discussions/341

<div type='discussions-op-text'>

<sup>Originally posted by **triplejranch** February 28, 2022</sup>
I searched and didn't find this, but forgive me if I missed it.  It would be really handy if we could select a transaction and duplicate it so we could just change the date and be on our way.  I'm thinking of transactions I have that have multiple splits and I repeat monthly.  A big time saver.</div>

**Comment by gsumpster** [comment]
I've started some work on this feature request tonight! I'm planning to add this function to the bulk edit and delete menu, and implementing it in a similar fashion. 

I've got a rough idea of the steps required to make this work but the PR might require some careful attention as this is the first time I'm diving into working with Actual's queries and data structure!

**Comment by rich-howell** [comment]
This was completed in #582
