### ISSUE TITLE
[Feature] Allow users to set "Budgeted" values to "Spent" so that "Balance" == 0 for a category

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#553]
### Discussed in https://github.com/actualbudget/actual/discussions/181

<div type='discussions-op-text'>

<sup>Originally posted by **siegfriedpammer** May 29, 2022</sup>
This would be useful for categories like rent and other fixed monthly spending where there is no need to budget more than needed.

I would be fine with a button in the budget screen next to the input field for the category.</div>

**Comment by MatissJanis** [comment]
Could you please elaborate on the idea @siegfriedpammer? Perhaps even you have an example in another budgeting app that does this already? 

Thanks!

**Comment by rich-howell** [comment]
I think what is being requeseted is what nYNAB has, for example Rent needs $150 every month, so you would press a button when you are budgeting and it would fill the category with $150. 

Sounds like #573 covers alot of this.

**Comment by shall0pass** [comment]
YNAB4 has a feature like this.  There's a context menu on the category budget cell that would set the budgeted amount to the spent amount, thus having a 0 available balance for that category and removing or returning those funds to "To Budget".

![image](https://user-images.githubusercontent.com/20625555/216445843-120b06e5-e0b9-49c1-b169-716a37436889.png)

**Comment by j-f1** [comment]
It looks like there’s a “Cover overspending” option that shows up if you spend more than you have budgeted, which covers some of the use cases here but not all.

**Comment by youngcw** [comment]
This looks similar to #508.  The only difference seems to be that this one is asking for a manual option vs a more automated one.

**Comment by youngcw** [comment]
End of month cleanup can do this.  Closing.
