### ISSUE TITLE
[Feature] Proposal: Add category balance display.

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#555]
### Discussed in https://github.com/actualbudget/actual/discussions/360

<div type='discussions-op-text'>

<sup>Originally posted by **summingyu** May 23, 2022</sup>
When I add a transaction and select a category, I can show the balance of the category, just like YNAB.</div>

**Comment by rich-howell** [comment]
I think this might have been relating to the mobile apps, @summingyu are you able to confirm? If that is the case this might be something that needs to be considered for the responsive app once the read only version is progressed.

**Comment by youngcw** [comment]
Closing as a duplicate of #534
