### ISSUE TITLE
[Feature] Add Transaction window should have some data validation

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#561]
### Discussed in https://github.com/actualbudget/actual/discussions/346

<div type='discussions-op-text'>

<sup>Originally posted by **Deguello** December 17, 2021</sup>
After bringing up the New Transaction window, you can immediately press Add Transaction, which will add an essentially blank transaction to the selected account. There's no validation on Payee or Category and there should be, imo. I suppose a $0 amount might be an edge case that could be allowed but, even then, some sort of confirmation dialog might be called for.</div>

**Comment by MatissJanis** [comment]
I see people discussing various solutions how this could be solved, but to me it looks like a solution in search of a problem.

So I'll ask the big question: why? Why should we disallow creating empty transactions? What problem does it solve?

Will close this off for now. We can re-open if someone is willing to explain why this should be done.
