### ISSUE TITLE
[Feature] Synced files don't belong in synced locations

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#562]
### Discussed in https://github.com/actualbudget/actual/discussions/347

<div type='discussions-op-text'>

<sup>Originally posted by **MikeBishop** December  6, 2021</sup>
I could swear I've seen this elsewhere, but I can't find the issue, so I'm making sure it's not missed.  The Actual files are kept in sync using Actual's own processes and service.  Therefore, they should be stored in explicitly-local folders rather than in folders which are prone to syncing by some other service.  Both Windows and Mac have services to sync the Documents folder; colliding changes from two different sync services produce results like this:

![image](https://user-images.githubusercontent.com/4273797/144867149-935c96f9-732e-4ec4-a334-754a52acd633.png)

![image](https://user-images.githubusercontent.com/4273797/144867333-d535513b-acca-4b82-802d-43fcb0ec3715.png)

I don't know what the proper location would be on a Mac, but in Windows, you probably want %LOCALAPPDATA% -- this contains files which are synced neither by OneDrive nor by Roaming User Profiles.  (There's perhaps an argument for %APPDATA% instead, which *is* synced by Roaming User Profiles, but the sync is completed before login.)</div>

**Comment by MatissJanis** [comment]
👋 We currently do not support desktop (electron) version of Actual. We might sometime in the future support it again, but lets cross that bridge when we get there.

Cleaning up the backlog of issues for now, so closing this off.
