### ISSUE TITLE
[Feature] Category Notes - Reveal on hover

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#563]
### Discussed in https://github.com/actualbudget/actual/discussions/344

<div type='discussions-op-text'>

<sup>Originally posted by **Kidglove57** December  1, 2021</sup>
When allocating budgeted amounts each month, I rely on my category notes which are helpfully stored in the budget screen. At present I need to click into each note individually to check the amount. It would be SO helpful if my notes could be revealed by just hovering the mouse over the notes icon instead. See YNAB4 purely as an example of where this has been done before.</div>

**Comment by TechwizEE** [comment]
Agreed on making it easier to reveal the notes.  Would this "hover view" also be the way to edit the notes?  Or would it still required a click? (Seems a click might help prevent accidental editing)

**Comment by Kidglove57** [comment]
100% agree on click to edit note.
I would use the hover mainly to double check the note for what I need to enter as a new month category budget amount.

**Comment by gsumpster** [comment]
Hey, I was interested in taking a stab at this, here's what I put together. 
![CleanShot 2023-01-27 at 01 20 16](https://user-images.githubusercontent.com/3413011/215051856-153a1b70-03c7-4d32-b2e2-b6c542e1504f.gif)

The preview tooltip will pop up on hover of the notes button and display the tooltip (smaller, limited to 220px in width, not restricted on height). If you move your cursor into the text, you'd be able to copy and interact with the text without the tooltip disappearing (easy to change, but think this would be my preference!). Clicking on the notes button will flip the tooltip into editing mode and act as it already does in Actual.

Here are my changes; happy to create a PR if we're happy with this interaction:
https://github.com/actualbudget/actual/compare/master...gsumpster:gsumpster.reveal-notes-on-hover

I didn't modify the Tooltip component directly (scary file!), felt that introducing another event there would impact the rest of the application a little too much given its usage elsewhere.

**Comment by Kidglove57** [comment]
I love what you have done here! Thank you very much.
It is exactly what I envisaged when I first raised this a couple of years ago (I think on Slack). A great addition in my view.

Unfortunately, I have no skills to comment on the technicals so this is just a user perspective.

**Comment by j-f1** [comment]
@gsumpster That looks great! I think the only nitpick I have would be to rewrite lines 31–54 as a ternary but otherwise it looks great :)

**Comment by gsumpster** [comment]
Sweet, thank you both for taking a look! I'll switch those lines over to a ternary and put up a PR!
