### ISSUE TITLE
[Feature] [UI] Re-order columns in Schedules and Accounts views

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#564]
### Discussed in https://github.com/actualbudget/actual/discussions/278

<div type='discussions-op-text'>

<sup>Originally posted by **stevenzez** November 23, 2021</sup>
Firstly I must thank you for the incredible application thus far, and for weathering the storm of recent YNAB refugees. I can see the potential and I'm excited to be along for the ride!

I think it would be nice to have a drag-n-drop feature or menu to customize the order of the columns in the Schedules and Accounts view. For example, in the Schedules view I'd like to move the Date and Status columns all the way to the left. In Accounts, I would like to move the Category column before the Notes column. That would be more intuitive and easier to glance through for me, but some people might like it in another order.

Perhaps this could be part of the table rewrite you mentioned? @jlongster in https://github.com/actualbudget/releases/issues/109#issuecomment-976734482</div>

**Comment by bstritesky** [comment]
Resizing the column widths would also be appreciated, especially for some columns that can be larger, such as running balances for a mortgage that may reach into six figures. I know that we can hide decimals to "fix" this per issue #725, but I like seeing decimals.

**Comment by derekantrican** [comment]
Just in case someone (maybe me? If I can find time) comes to edit this later, this seems to be the source of the transactions table: https://github.com/actualbudget/actual/blob/master/packages/desktop-client/src/components/transactions/TransactionsTable.tsx

**Comment by lazynooblet** [comment]
I've been using actual for 11 months now and I still keep editing the category column to put in my notes. I saw this issue a few months ago and was hoping it would be implemented soon.
