### ISSUE TITLE
[Feature] Usability:  Transaction selection and options

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#565]
### Discussed in https://github.com/actualbudget/actual/discussions/351

<div type='discussions-op-text'>

<sup>Originally posted by **MikeBishop** November 15, 2021</sup>
Currently, clicking over any editable field of a transaction starts editing that field.  Clicking the three-dot menu while focus is in a transaction field unselects the field and shows options for the account.

The only way to select a transaction is the (very small) checkbox in the left-hand column, and the only way to select multiple transactions is to select multiple very small checkboxes.  Options for a transaction (or transactions) only appear when they're selected.

I'd suggest that:

- Focus in a transaction field also select that transaction, causing the transaction options to appear in the menu
- Ctrl-click and Shift-click be supported ways of selecting multiple transactions</div>

**Comment by MatissJanis** [comment]
First: ctrl/shift clicking. This was previously a bug that has been fixed.

Second: selecting transactions on focus - IMO we should not do that. It leads to some very weird behaviour. For example: what if I had selected 2x transactions and I focus on a different one? Should the 2x be unselected? Should all 3x be selected now? It makes the UX harder to reason about. Generally one customer interaction should result in one state change (i.e. clicking a button opens a modal; clicking a transaction opens the edit menu; clicking the checkbox changes its state, etc.).

Given this: closing the feature suggestion.
