### ISSUE TITLE
[Feature] Usability:  GUID tooltips are not useful to most users

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#567]
### Discussed in https://github.com/actualbudget/actual/discussions/350

<div type='discussions-op-text'>

<sup>Originally posted by **MikeBishop** November 15, 2021</sup>
The GUID which appears when the mouse cursor hovers over a transaction is presumably useful when debugging sync.  That's a vanishingly small fraction of users.  I'd suggest the GUID be hidden without enabling dev tools or otherwise specifically seeking out advanced options.

Instead, perhaps the tooltip should display the full text of whatever it's over if it's too wide for its column, and not appear otherwise.</div>

**Comment by gsumpster** [comment]
Hey, I'm interesting is taking this on, just to get my feet wet a bit with this codebase. I wanted to clarify that we're referring to the GUID that appears (as a `title` attribute) on the PayeeCell, right? I think the only change we'd need to display the contents of the row here would be to change this line to `title={payee.name}` (might also need to handle transferAccounts, judging from the `getPayeePretty` fn)

https://github.com/actualbudget/actual/blob/093dbeb8a6ddfeb05df8b3fbba2ecbfb2830a032/packages/desktop-client/src/components/accounts/TransactionsTable.js#L412

**Comment by MatissJanis** [comment]
@gsumpster yes, you are absolutely correct. And thanks for the initiative to contribute to Actual! :)
