### ISSUE TITLE
[Feature] Allow customizing “notes” field directly from schedules 

### ISSUE THREAD

**Issue by j-f1** [actualbudget/actual#578]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

When I have multiple recurring transactions paid out to a single payee (for example, I have several subscriptions to different apps through the App Store, but the payee for all of those payments ends up being Apple), it is confusing to look at the schedule list because I can’t easily differentiate between the different schedules except by trying to remember their pricing.

### Describe your ideal solution to this problem

- Add a new field to the schedules editor called “Name” or “Notes” that allows entering a custom name for a schedule
- This value would be automatically entered into the “notes” field of any matched transactions (probably using the standard “set note to” action on the underlying rule)
- The schedule list would gain a new column that shows this field for disambiguation purposes

### Teaching and learning

I think people would naturally notice the feature the next time they create a new schedule. They’d also be likely to notice the new column in the schedules UI if this affects them. No documentation should be needed.

**Comment by j-f1** [comment]
Check out my initial attempts at #268. The code isn’t likely to be worth using, but someone working on this feature might find my learnings there valuable.

**Comment by Kidglove57** [comment]
This issue has been a problem in a number of Finance Apps that I tried. In the absence of a solution, such as is proposed here,I developed a work around that has "stuck" for me. I include the extra description in the Payee name. Do:
Apple (iCloud)
Apple (Music)
Apple (1Password)
And so on.

Just commenting in case this helps anyone in the interim.
