### ISSUE TITLE
[Bug]: old budget files getting deleted

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#596]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

https://actualbudget.netlify.app/

1. create a test file (with demo data)
2. close
3. create a new EMPTY file
4. close
5. open the new DEMO file
6. it's empty 🤔

**This issue might exist only in the offline version of the product. It _might_ not exist in the versions that sync files with a backend server.** Either way - this is a pretty bad bug that we should address ASAP.

### What error did you receive?

Previous budget files get deleted when a new one is created.

### Where are you hosting Actual?

None

### Operating System

None

**Comment by j-f1** [comment]
I believe this may be an issue with Netlify not setting the COOP/COEP headers.

**Comment by MatissJanis** [comment]
Tested locally: yes, that seems to be working OK.

Also when deployed with actual-server that seems to be OK.

So possibly only Netlify affected. Which is good news. Phew..

**Comment by TechwizEE** [comment]
Tested `master` locally (`yarn start:browser`) with Firefox and Chrome
A. `http://localhost:5006` the test budget and adding multiple new budget files works without issue
B. `http://<serverIP>:5006` I see the issue described at the top

I did see in Firefox debug console (but not in Chrome's debug console) `Error: Fallback mode unable to write file changes` with test B.

**Comment by TechwizEE** [comment]
Also tried tag `v23.1.12` on `actual-server`, performed the A/B tests again, saw the same result I reported just above.

**Comment by trevdor** [comment]
Dug through the old Netlify deploys. 
It seems deploys of `master` (`https://master--actualbudget.netlify.app/config-server`) exhibit the buggy behavior.
Preview deploys do not (e.g. the very recent build `https://deploy-preview-602--actualbudget.netlify.app/`)

**Comment by j-f1** [comment]
Yep, it was an issue where the `_headers` file was getting deleted during the build. I changed the config on the backend so future builds will no longer have this issue.

**Comment by MatissJanis** [comment]
Even though this was fixed for Netlify, I'll re-open it. IMO we need to address the problem that _sometimes_ a budget file can be unintentionally deleted because of misconfiguration. 

So we should 1) identify if creating a budget file will corrupt other existing files and 2) show a warning message OR perhaps even disable creating a new file.

**Comment by MatissJanis** [comment]
Even though this was fixed for Netlify, I'll re-open it. IMO we need to address the problem that _sometimes_ a budget file can be unintentionally deleted because of misconfiguration. 

So we should 1) identify if creating a budget file will corrupt other existing files and 2) show a warning message OR perhaps even disable creating a new file.

**Comment by j-f1** [comment]
#600 should handle this, right?

**Comment by MatissJanis** [comment]
> #600 should handle this, right?

There are three cases when budget files get deleted without people noticing (AFAIK):

1. missing SharedArrayBuffer support
2. lacking Cross-Origin-Opener-Policy headers
3. http vs https (haven't looked into this much myself, but this keep popping up as a bug report pattern)

With #600 we solved only (1) IMO. Still need to figure out how we can identify (2) and (3)

**Comment by j-f1** [comment]
2 and 3 cause 1. The underlying issue is — just like with #511 — that SharedArrayBuffer is disabled when the headers or secure context are missing. So checking for missing SharedArrayBuffer should be catching all the possible cases.

**Comment by MatissJanis** [comment]
Looks like you're right. Tested here: https://github.com/actualbudget/actual/pull/619

Thanks @j-f1 ! Great job as always!
