### ISSUE TITLE
OAuth2, OIDC, LDAP, SSO support

### ISSUE THREAD

**Issue by alexanderadam** [actualbudget/actual#61]
I guess it would be great to have support for external authentication (i.e. via Authelia, Keycloak, GitLab, Authentic etc)

**Comment by rich-howell** [comment]
This can now be found [here](https://github.com/actualbudget/actual/discussions/174) closing this issue.

**Comment by amirasyraf** [comment]
> This can now be found [here](https://github.com/actualbudget/actual/discussions/174) closing this issue.

Link is dead, where can I find the discussion?
