### ISSUE TITLE
[Bug]: Rule definition after category is deleted is bogus

### ISSUE THREAD

**Issue by shall0pass** [actualbudget/actual#614]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

If a rule has been created using a category and then the category is deleted, the rule still exists in a weird state.  The rule points at the old category is, which no longer exists.  This will cause the rules search box to throw an error.

![Screenshot_20230203-052619-792](https://user-images.githubusercontent.com/20625555/216593456-08a01895-10ae-4ecb-8b44-47d717fd521c.png)

Request: create a tool that automatically checks for an affected rule and deletes it when a category is deleted.

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by j-f1** [comment]
Looking into this, I think it would be pretty challenging to handle deleting rules (or stripping out conditions/actions) on delete of a category, since the category delete happens at a fairly low level. I think the best route would be to improve the display in the UI and fix the search crash.

**Comment by shall0pass** [comment]
Ok.  FYI.  If you delete a payee, it has the same behavior.

**Comment by MatissJanis** [comment]
👋 I've added "priority:high" label because IMO this is a blocker for the upcoming release as it will crash the rules page for some people.
