### ISSUE TITLE
Remove the “payee rules” feature

### ISSUE THREAD

**Issue by j-f1** [actualbudget/actual#615]
I looked through the code, and the `payee_rules` table appears to be unused. I think it would be safe to remove the table and associated code, although I would like @jlongster to weigh in on if it has some purpose that I’ve missed in my search.

**Comment by rich-howell** [comment]
Did some exploring...

Created a new rule in a test budget on one of the Netlify deployments

![image](https://user-images.githubusercontent.com/22135084/216809699-9a0b5755-8626-4799-9785-53b0572be6c1.png)

Downloaded the database once the rule was created

![image](https://user-images.githubusercontent.com/22135084/216809715-800ef919-684a-4171-9ffe-73a37cd0b63d.png)

Confirmed that rules lives simply in rules only and not in payee_rules

![image](https://user-images.githubusercontent.com/22135084/216809750-f04859fd-f48c-42bc-983b-bc63899c4f12.png)

**Comment by MatissJanis** [comment]
Looks like this is unused. Feel free to 🔥
