### ISSUE TITLE
[Bug]: editing closed account names

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#616]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When you edit a closed account name - it adds "closed:" prefix to it. Which then gets saved as the real account name.

<img width="400" alt="Screenshot 2023-02-03 at 19 05 48" src="https://user-images.githubusercontent.com/886567/216686326-9c11b23c-eb95-42c1-8a03-141c1f38978d.png">

Reproduction:
1. close an account
2. open the closed account
3. click on the closed account name to edit it
4. observe "closed: xxxx" appearing in the edit field
5. change it to "closed: xxxx yyyyy" (add something at the end)
6. click "enter" to save
7. notice that the new account name is "closed: closed: xxxx yyyyy"

### Where are you hosting Actual?

None

### Operating System

None

**Comment by Kidglove57** [comment]
I have run into this quite a number of times and I am ashamed to say never reported it.

**Comment by n1thun** [comment]
Hi, can i pick this one up? i think i have the fix for the issue, we can either prevent the string concat for previously closed accounts or disable the edit button for closed account. This is my first contribution for this repo, are there any standard guide lines for PRs?

**Comment by j-f1** [comment]
Hi @n1thun, that would be awesome! I think the ideal outcome would be that the title still looks the same (e.g. “Closed: [name]”) when viewing it, but when you go to edit the prefix should be removed. We don’t have any particular guidelines for PRs, aside from making sure that you have a reasonably descriptive PR title.
