### ISSUE TITLE
[Enhancement]: Replace reference to actualbudget blog with release notes.

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#626]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Replace all references to https://actualbudget.com/blog/ + version with a link to the documentation release notes https://actualbudget.github.io/docs/Release-Notes.

**Comment by rich-howell** [comment]
##Desktop Client

https://github.com/actualbudget/actual/blob/master/packages/desktop-client/src/components/UpdateNotification.js
https://github.com/actualbudget/actual/blob/master/packages/desktop-client/src/components/manager/ManagementApp.js

**Comment by rich-howell** [comment]
Thinking about this, should we just replace it with a direct link or should we get the version number and point to the section in the release notes that matches the version we are on. 

I am worried you all might say the latter, which might be beyond my capabilities in Java ha

**Comment by j-f1** [comment]
I think either one could work!

> I am worried you all might say the latter, which might be beyond my capabilities in Java ha

GitHub Copilot works really well :) I hadn’t used Go before and it helped out a lot

**Comment by cacti23** [comment]
@rich-howell please assign me this issue.

**Comment by j-f1** [comment]
@cacti23 Rich opened #633 to fix this already!
