### ISSUE TITLE
[Bug]: sync issue

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#628]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Both me and my wife use Actual from different devices. Sometimes I have noticed that sync just breaks on one of the devices. 
<img width="569" alt="Screenshot 2023-02-04 at 17 54 06" src="https://user-images.githubusercontent.com/886567/216782229-5e53928b-8844-4b8b-9f3b-1354f0655fdc.png">

Actual v23.1.x

### What error did you receive?

```
Error: UNIQUE constraint failed: messages_crdt.timestamp
    at r.handleError (sql-wasm.js:89:129)
    at t.step (sql-wasm.js:80:69)
    at t.run (sql-wasm.js:82:56)
    at Module.c (index.web.js:72:12)
    at Module.j (index.js:99:18)
    at index.js:327:9
    at Module.d (index.web.js:103:20)
    at Module.k (index.js:127:10)
    at index.js:306:3
```

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by MatissJanis** [comment]
False alarm :) 

After doing some investigation I figured out the root-cause here. I am doing automatic investment account updates. A script is pushing messages to actual-server. 

If 2x computers are opened and then pull the messages from actual-server and then attempt to sync them back up - this will cause conflicts to arise in 1x of the devices.

**Comment by j-f1** [comment]
Ideally that would be supported though, the devices shouldn't come into conflict.
