### ISSUE TITLE
SharedArrayBuffer and HTTPS

### ISSUE THREAD

**Issue by Marcus-Schubert** [actualbudget/actual#637]
Hey there,

I'm currently running actual server in a local network on HTTP via Docker. Since the latest update (23.2.5), I get the SharedArrayBuffer info page and can't access my actual server instance.

When looking into the [documentation](https://actualbudget.github.io/docs/Troubleshooting/SharedArrayBuffer/), it says that actual requires SharedArrayBuffer and that HTTPS is required for SharedArrayBuffer.

Does this mean, actual server will no longer work with HTTP but only HTTPS?

**Comment by Marcus-Schubert** [comment]
Thank you for the quick response. I guess I will switch to HTTPS now :+1:

**Comment by hofq** [comment]
@j-f1 
Hey Jed,
is automatic cert generation in the code/ docker image planned?

the automatic certificate generation on Unraid is mostly fiddly and not everyone has a reverse proxy with a domain and auto certificate generation.

**Comment by j-f1** [comment]
> Could you make configuration via Environment Variables Possible? At least the HTTPS one since you can't add specific files to an Unraid Deployment unless you rebuild the image

Yep! In the latest version (not tagged yet, but you can use `edge` for now) you can specify `ACTUAL_HTTPS_KEY` and `ACTUAL_HTTPS_CERT` environment variables with the path to the key or the key content itself. See [the updated config docs](https://deploy-preview-96--zingy-bonbon-b1b286.netlify.app/Installing/Configuration) which will hopefully be merged soon

**Comment by hofq** [comment]
Does it automatically generate self signed certs or do you have to do it yourself?

**Comment by j-f1** [comment]
You’ll have to do that yourself (partially because we didn’t implement that functionality, partially because I don’t want people to get used to clicking through certificate errors). It might be nice to have a tool to do that automatically somehow though!

**Comment by MatissJanis** [comment]
We have added a way to bypass this error in version 23.2.9. Please use it at your own risk.

**Comment by Presjar** [comment]
I use traefik2 to generate certificates for each of my services. Is anyone else using traefik for similar so they can access for example https://actual.foobar.com ? I could see that enabling https on actual would perhaps conflict with the https of traefik? But to stop the SharedArrayBuffer issue I need to enable https in Actual?

**Comment by j-f1** [comment]
You don’t need to enable HTTPS in Actual itself, as long as you have something adding HTTPS between you and the server.

**Comment by Presjar** [comment]
Oh great! This should work easily then!
Thanks for letting me know.
