### ISSUE TITLE
[Maintenance] build script upgrade

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#656]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

We currently use a very old version of webpack. We should either upgrade it + the other dependencies or move to a better build system.

Some alternatives to consider:
- esbuild
- vite
- back to create-react-app managed version
- swc
- ?

Some more info:
https://github.com/actualbudget/actual/blob/40a23f326341b665298561f4dbd8b4d8296e3365/CONTRIBUTING.md#ditching-babel

**Comment by j-f1** [comment]
Earlier attempts:

- https://github.com/actualbudget/actual/pull/142
- https://github.com/actualbudget/actual/pull/108
- https://github.com/actualbudget/actual/pull/84

**Comment by MatissJanis** [comment]
`desktop-client` has been moved back to CRA.

We still need to figure out a solution for `loot-core`. Maybe we should consider rollup for it? Or another bundler that's good for building small libraries? TBD

**Comment by j-f1** [comment]
Current status: we’re using the latest version of Webpack at the moment for all packages. I think we’re in a much better place than we were before, but it would be nice to switch to something that builds a bit faster so development can be easier.

**Comment by MikesGlitch** [comment]
My vote is for Vite

**Comment by MatissJanis** [comment]
We're now using vite which is a significant improvement.
