### ISSUE TITLE
[Feature] Allow different transfer dates

### ISSUE THREAD

**Issue by garygreen** [actualbudget/actual#661]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Currently when creating a transfer when you change the "Date" value it will also change the date on receiving account.

This can be problematic because there are cases where the date a transfer was sent is different to the date it's actually received in the payees account (maybe it takes a few days to clear, and then the receiving account date is different)

My suggestion here is to (somehow) allow for the date to not be kept "in sync" and allow for different dates for the transfer. Hope that makes sense.

![image](https://user-images.githubusercontent.com/1702638/219123760-9023b9c6-0e37-4003-8a66-867951b849bb.png)

**Comment by Nyanino** [comment]
Really feeling the need for this feature right now. I use the running balances feature to reconcile against statements I receive. The linked transactions can have different dates for two accounts ruining the usefulness of the running balances feature as it can only favor one account but not both.

In addition, it would be great to reorder transactions like #1165

**Comment by kcollett** [comment]
One way I've run into this is in relation to the ability to use drag and drop to reorder transactions with the same date. I had a scenario where I wanted to use this to shift the position of the transfer match that in the statement of the receiving account. To do this, I had to change the date on the transfer to be the posting date in the receiving account, but of course that meant the date of the transfer in the sending account was now incorrect.
