### ISSUE TITLE
[Feature] Disable split transaction feature

### ISSUE THREAD

**Issue by garygreen** [actualbudget/actual#662]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

This seems like a complex feature and clutters up some of the UI popups for those who don't need to split transactions.

### Describe your ideal solution to this problem

It would be good to be able to "disable" this feature in the settings, hiding it from appearing in the popups, etc, or make it less prominent.

![image](https://user-images.githubusercontent.com/1702638/219125326-f838a160-0822-483d-899f-11a4787f2488.png)

**Comment by MatissJanis** [comment]
👋 Could you explain more of the "why"? What problem are you experiencing?

**Comment by garygreen** [comment]
Outright disabling it probably isn't the desirable option, but more a suggestion to make it less prominent in the UI for those that don't use it too often. For example - it appearing in the Category dropdown at the top each time is a bit cluttered and doesn't make much sense being there imo. It's a minor thing, and based on previous comment sounds like I'm likely in the minority, so closing this.
