### ISSUE TITLE
[Feature] Search bar reset button

### ISSUE THREAD

**Issue by snovak** [actualbudget/actual#664]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I'm currently tackling the repetitive task of assigning categories to my "leftover" transactions.  After searching for something, clearing the search field to reveal the uncategorized transactions requires 3 actions.  

- mouse click to refocus on the search field
- Ctrl+a to highlight the text in the field
- Press 'delete' to clear the field
...

Ordinarily this isn't a big deal.  But for something that is done 100's of times in the course of the processes, streamlining the user experience would really help.

### Describe your ideal solution to this problem

Simple problem, simple solution:  
Add a clear button to the search field. 

Additionally, maybe assign the 'Esc' button to the same functionality, or something else if 'Esc' is assigned to something else.  A simple key stroke would further improve the process, not having to use the mouse to hunt and peck the clear button.
This might save the user a few seconds each time, but it adds up. 

![ClearButton](https://user-images.githubusercontent.com/317561/219363864-a403c76f-2897-42af-8ead-4348dd7dadf1.png)

**Comment by j-f1** [comment]
Interesting! I like this idea, but also want to explore a couple of related possibilities:

- auto-select the filter field when it is clicked (like browser URL bars)
- expose the filter field as a special “anything contains *foo*” filter that you can click the X on to remove

**Comment by MatissJanis** [comment]
> Simple problem, simple solution:
> Add a clear button to the search field.

Love it!
