### ISSUE TITLE
[Feature] Add ability to append notes instead of overwriting them 

### ISSUE THREAD

**Issue by shall0pass** [actualbudget/actual#667]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

There are times when I want to add a note to a batch of transactions.  If any of the transactions already have notes in them, applying the operation to add a note will overwrite the note that is already on that transaction.  I am looking for the ability to append more text to a note so that any existing notes aren't lost.

### Describe your ideal solution to this problem

Ideas:
1. Change the current behavior to append instead of replace.
2. Add a second button to distinguish from append or replace.
3. Maybe a popup during a note action to ask if append or replace is preferred.

**Comment by themadman0980** [comment]
Perhaps a good alternative would be to add a new field called 'description' and move any imported text from the bank data into the description field. This would free up the notes field for user-created notes only.

The description field could effectively be a read-only column which can optionally be hidden by the user (not sure if that functionality exists?).

**Comment by shall0pass** [comment]
I didn't specifically have bank imports in mind when I wrote this idea down.  I do manual transaction entry only and being able to append a note rather than replace would be useful.  I can see how having a code path for appending notes could be useful for bank imports though.  

I'm not a huge fan of two text fields by default simply because it feels redundant.  You may be interested reading what is in this closed idea.  https://github.com/actualbudget/actual/issues/504

**Comment by Kidglove57** [comment]
I am also not a fan of more note fields. However, I would certainly support the idea of a tag field to keep track of specific projects or tax deductibles
