### ISSUE TITLE
[Feature] Average category expenditure by year

### ISSUE THREAD

**Issue by zbuc** [actualbudget/actual#682]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Currently you can pre-populate a category with spending for the last three months, but in some categories my spending is a bit more spiky and it would be nicer to be able to set based on an average over an entire year.

### Describe your ideal solution to this problem

It would be nice to at least have a "set budgets to 1 year average" next to the existing "set budgets to 3 month average".

Ideally, you'd be able to set a specific category's spending without affecting any other categories, but that would probably make sense as a separate issue.

**Comment by j-f1** [comment]
That seems reasonable!

> Ideally, you'd be able to set a specific category's spending without affecting any other categories, but that would probably make sense as a separate issue.

Yes, please open a separate issue for this. It would be nice to expose more options for auto-filling budgets per-category but there would need to be some discussion about the design since we don’t want to clutter up the budget table unnecessarily.

**Comment by youngcw** [comment]
It is now possible to set a single category to a 1 year average.  That was the preferred solution.  Unless there are any that want a 1 year average for the whole budget, Ill close this off.
