### ISSUE TITLE
[Feature] Advanced Rule Filters

### ISSUE THREAD

**Issue by themadman0980** [actualbudget/actual#685]
The addition of an "AND" / "OR option box at the top of the rule creation view would be extremely helpful. Users could then pick to use all of the listed conditions or any of them. This may cause issues if you want anything complicated, but should help with basic use cases.

In the image below, this would change the fixed "If ALL these conditions match" to "If ALL/ANY OF these conditions match".

![image](https://user-images.githubusercontent.com/107305060/220827597-d5724ca6-0bfd-4104-88a4-238f5f3d191e.png)

Alternatively, if a major overhaul is an option, something similar to the Plex interface would be incredibly useful. This would allow multiple combinations of and/or conditions when accepting rule matches.

![image](https://user-images.githubusercontent.com/107305060/221031395-35c6c17f-f49e-4617-80bf-ae659ec3fcc9.png)

**Comment by clonejo** [comment]
Feature is implemented, the "needs votes" tag is here erroneously, i believe?

**Comment by MatissJanis** [comment]
Thanks @clonejo . Label removed
