### ISSUE TITLE
Two distinct files behaving as one.[Bug]: 

### ISSUE THREAD

**Issue by musiq021** [actualbudget/actual#698]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I have two distinct files. But suddenly one has become the other. Closing it and opening the other, same data, changes and all. Exporting either puts out the same data with different IDs. 

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by MatissJanis** [comment]
What version of actual are you using? You can access this information by opening the "settings" page.

**Comment by musiq021** [comment]
22.12.03

**Comment by musiq021** [comment]
i'm an idiot, just found the issue with SharedArrayBuffer and serving over http causing budgets to merge.
