### ISSUE TITLE
Request to bulk select filters

### ISSUE THREAD

**Issue by carkom** [actualbudget/actual#699]
I'd also be interested in being able to select all categories, but selectively eliminate a few.  I.E. Select all Monthly Spending categories, but not my long term goals or income categories.  There isn't an easy way to bulk select.  This may be outside of the scope of this PR though, since I can't think of any other area of the app that allows this type of interaction so the user interaction code probably isn't written.

_Originally posted by @shall0pass in https://github.com/actualbudget/actual/issues/688#issuecomment-1445449588_

**Comment by j-f1** [comment]
I can think of 2 ways to address this:

- Add a “negate” or similar checkbox to filters
- Add a way to select category groups in the category picker

(probably both would be needed to get the right behavior here? i.e. select “Income” as the category and then negate)

**Comment by carkom** [comment]
Fixed by #1287

**Comment by j-f1** [comment]
Given that #1093 covers the PR more directly, how do you feel about reframing this to be about selecting a category group?

**Comment by youngcw** [comment]
@carkom Can this be closed as a feature request?
