### ISSUE TITLE
[Feature] Do not roll-over money month-to-month

### ISSUE THREAD

**Issue by sinistersnare** [actualbudget/actual#722]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

We do not use the 'Cover overspending' feature, because we don't like that it changes the amount of money _in_ the budget. But, when moving to the next month, the negatives go back just fine, but the positives balloon, which seems wrong.

### Describe your ideal solution to this problem

If the positives could be made to not roll over, that would be amazing. Month-to-month, we just try to have the same budget, and its nice when the "Balance" column is simply "Budgeted" - "Spent".

### Teaching and learning

I think having a drop-down context menu somewhere (possibly adding one to the "Balance" column header) which just changes the calculation? I made a [docs issue](https://github.com/actualbudget/docs/issues/107), but on continuing inspection, this feature does not exist. So I will be adding docs for this as well.

**Comment by shall0pass** [comment]
You might be interested in the experimental feature to toggle the budget type.  The other budget type doesn't carry balances from one month to the next.  You can switch it on in the experimental features section on the settings page.

**Comment by sinistersnare** [comment]
Ah I noticed [this issue](https://github.com/actualbudget/actual/issues/363) but I misunderstood cause I could not find the button. I still can not find it. I think I need to update my Actual. Will report back!

**Comment by sinistersnare** [comment]
Neat, that works! It doesnt transfer the budget numbers themselves, but I can do that by hand. Awesome, this works so much better than I was hoping for, the UI changes in this mode make the top bit super helpful.

Thanks!

**Comment by Kidglove57** [comment]
@sinistersnare Glad you got it working! Genuine question - how do you manage irregular spending (clothing for example) if the monthly budget allowance is not carried forward?

**Comment by sinistersnare** [comment]
I wanted to use the 'cover overspending' feature, to take advantage of the envelope style of budgeting, but it fully changes the amount of money in the budget in such a way that 'copy last months budget' in the next month puts not-nice numbers in.

So currently, I just make sure that the header in the "Balance" column is > 0. If the 'cover overspending' worked slightly differently, Id love to use it.

What I think would be cool would be:

| Category | Budgeted  | Spent | Balance |
| --- | --- | --- | --- |
| Food | 300 | 200 | 100 | 
| Clothes | 50 | 75 | -25 | 
| Misc | 100 | 0 | 100 | 

And then when I 'Cover Overspending' by moving some money from Misc into Clothes, it would say

| Category | Budgeted  | Spent | Balance |
| --- | --- | --- | --- |
| Food | 300 | 200 | 100 | 
| Clothes | 50 | 75 | -25 | 
| Misc | 75 (100) | 0 | 100 | 

Or something like that. And then when the next month rolls around (this is report mode ofc where 'cover overspending' doesnt seem to exist) it will use the `100` to fill the Misc. That way I can still use the 'Cover Overspending' which seems like a great feature that fits with the envelope style, while still maintaining a consistent budget

**Comment by Kidglove57** [comment]
Thanks for explaining. I think I have just used envelope budgeting for so long that I did not question that feature any more!

I know of one app that covers overspending in the way that Actual, Ynab etc does but which also keeps a record of each money movement between categories. You can edit the movement after the event and even add a note to it explaining what it's purpose was.
