### ISSUE TITLE
[Feature] Add functionality for migrating between Report and Rollover budget types

### ISSUE THREAD

**Issue by j-f1** [actualbudget/actual#732]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

The data associated with the two budget types is completely separate despite both being somewhat similar. This means I’ll either have to abandon my old budget data or painstakingly copy it over one cell at a time.

### Describe your ideal solution to this problem

- When first enabling the report budget offer to transfer over the existing budget figures from the rollover (default) budget
- Also offer this at any time? (not sure how it should handle overwriting existing months?)
- Add an option to the per-month menu that wipes out the existing budget for that month and transfers it from the rollover budget. (I have several years of history so this could be a bit of a pain but ¯\\\_(ツ)\_/¯)

### Teaching and learning

It should be included in the docs, once we have them (https://github.com/actualbudget/docs/pull/121)

**Comment by jsehnoutka** [comment]
I've been using both the Rollover and Report Budgets extensively and synchronizing budgeted amounts between these two by hand is kind of hard (I usually need several screenshots of the 'main' one and update the other one manually after switch. Having a 'synchro' button or drop-down option implemented would be amazing! I suppose Report Budget would be always updated from Rollover as the second mentioned is the 'default' Actual approach.
