### ISSUE TITLE
[Feature] nordigen bank sync historic data

### ISSUE THREAD

**Issue by foremny** [actualbudget/actual#748]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I want to sync my transactions from my bank to actualbudget via nordigen integration with as much history as the bank allows. Currently it is hardcoded to 31 days or the creation date of the account. [see](https://github.com/actualbudget/actual/blob/master/packages/loot-core/src/server/accounts/sync.js#L769)
``` js
let date = monthUtils.subDays(db.fromDateRepr(latestTransaction.date), 31);
// Never download transactions before the starting date. This was
// when the account was added to the system.
if (date < startingDate) {
  date = startingDate;
}
```

### Describe your ideal solution to this problem

An Option to choose how far back the initial sync will pull data.

**Comment by fstybel** [comment]
It should be straightforward to do it. 
We have this data in the Nordigen API response from `/institutions` endpoint ([doc](https://nordigen.com/en/docs/account-information/integration/parameters-and-responses/#/institutions/retrieve%20all%20supported%20Institutions%20in%20a%20given%20country)). We use currently this endpoint to fetch all institutions. 
We could extend the modal where we select our Bank and add there for example checkbox to fetch all possible history or we can use just a textfield filled with max period

**Comment by youngcw** [comment]
GoCardless currently pulls in 90 days, which I believe is the max allowed.  Closing.
