### ISSUE TITLE
[Feature] Clarify that on/off budget status can’t be changed later

### ISSUE THREAD

**Issue by j-f1** [actualbudget/actual#753]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Currently when creating a new account, there’s no warning that it can’t be changed later:

![](https://github.com/actualbudget/docs/blob/master/static/img/add-account/CreateAccount.png?raw=true)

### Describe your ideal solution to this problem

Add a small warning below the checkbox saying that it can’t be changed later and linking to a section (which would also need to be written) on [the Accounts → Overview docs page](https://actualbudget.github.io/docs/Accounts/overview).

Here’s the code that creates the checkbox:

https://github.com/actualbudget/actual/blob/ec89279509a0c05e23ba917639dc626d6f5f983c/packages/loot-design/src/components/modals/CreateLocalAccount.js#L120-L129

**Comment by pmamberti** [comment]
Hello! Have not done much frontend work, but would something like this work?

![off-budget-warning](https://user-images.githubusercontent.com/22891384/226049737-f24c0be3-1193-4045-8eeb-3123d0039c6e.jpg)

**Comment by j-f1** [comment]
I would avoid using red (which we use to indicate errors) for this. Maybe gray? And also maybe drop the parentheses? Otherwise it looks great!

**Comment by pmamberti** [comment]
Oh wow that was quick, I did remove the parenthesis and great shout on the color, I thought I did read it in the issue description (but I have imagined it instead 🤦🏻 ).

Will fix the color and put together a PR :)
