### ISSUE TITLE
[Feature] Add All accounts/For Budget/Off Budget views to mobile version

### ISSUE THREAD

**Issue by Jackenmen** [actualbudget/actual#757]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Similar to how you can click on the "All accounts"/"For Budget"/"Off budget" tabs in the sidebar on the desktop version of the web app, I would like to be able to do the same on the mobile version so that I can view transactions across all my accounts in a single view.

### Teaching and learning

I'm expecting this to be available in the accounts list screen so I imagine it would be easily discoverable there.

**Comment by joel-jeremy** [comment]
It's this similar to https://github.com/actualbudget/actual/issues/2333?

**Comment by Jackenmen** [comment]
It is similar but this issue is limited to the pre-defined views while #2333 suggests adding a way to choose any subset of accounts.
Also, #2333 doesn't explicitly talk about the On Budget and Off Budget views.

**Comment by matt-fidd** [comment]
On/Off budget have been added this release cycle
