### ISSUE TITLE
[Bug]: SharedArrayBuffer error when using http despite setup being correct (as far as I can tell)

### ISSUE THREAD

**Issue by bverkron** [actualbudget/actual#760]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Recently updated the docker image to the latest (as of March 15, 2023) and I now get the `Actual requires access to SharedArrayBuffer in order to function properly.` error. I've enabled the settings in my browser (Brave) as well as another browser (Chrome) to no avail.

<img width="735" alt="image" src="https://user-images.githubusercontent.com/19174503/225486497-a53e6000-8e07-40c5-8c61-38d6f6171f8c.png">

I'm using http not https and according to this message in the doc I don't think I should have to do anything else
> If you’re using the default actual-server package as your server, you don’t have to worry about this (the headers will always be enabled).

I was using the `jlongster/actual-server` image but also tried the `ghcr.io/actualbudget/actual-server` image but no change.

Maybe I'm missing something?

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Brave v1.49.120 (March 9, 2023)

### Operating System

Mac OSX

**Comment by j-f1** [comment]
If you want to access your server from another device, you’ll need to use HTTPS. As described in the HTTPS section of our SharedArrayBuffer docs, you can only use plain HTTP when connecting to `localhost` due to browser security policies. (You shouldn’t need to enable any experimental flags in your browser and I would recommend leaving those off).

**Comment by bverkron** [comment]
My apologies, must have missed that in the doc. Thanks. Closing.
