### ISSUE TITLE
[Bug]: New version notification fails to display

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#764]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Since version 23.3.2 the green pop up box no longer appears on the budget screen despite the settings screen showing a new version is available. 

### What error did you receive?

No error received. 

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

**Comment by MatissJanis** [comment]
Looking at the code we do have a check for showing the outdated version message only one time (per version).

https://github.com/actualbudget/actual/blob/f76a07c3cf72b35c2f47d243eeb1b8d764b6514b/packages/loot-core/src/client/update-notification.js#L13

However, the update notification is not "sticky". It is shown only one time. If you refresh the page - it will no longer show up.

I wonder if we should change that.. to show the update notification forever until a user explicitly clicks on "dismiss".
