### ISSUE TITLE
[Bug]: OFX with payee information in MEMO field not parsed correctly

### ISSUE THREAD

**Issue by damomato** [actualbudget/actual#767]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When importing an OFX file with credit card transactions the payees are remaining blank and no rules are created. Everything else seems to be working fine apart from that,

According to the docs:
"When importing transactions, by default it will create new payees based on the given name."

However this isn't happening. Apologies if I've misunderstood how this is supposed to work.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

**Comment by j-f1** [comment]
Can you upload an example OFX file (with any sensitive information redacted)? We may not be parsing it correctly.

**Comment by damomato** [comment]
Thanks for the quick response. The file type wasn't supported so I zipped the OFX file. Just a single day of data.

[Example.zip](https://github.com/actualbudget/actual/files/11008667/Example.zip)

This is how it looks in Actual after I import it. Payee is empty.
![image](https://user-images.githubusercontent.com/85538685/226110206-f06f4214-6cc1-4474-bc26-117738c58f42.png)

And these are the options for downloading the data from my bank. I've tried both MYOB and Quicken OFX files. It's an Australian bank if that makes any difference.
![image](https://user-images.githubusercontent.com/85538685/226110258-c198fa1c-926d-44ee-a3e9-5b1056a02f45.png)

**Comment by j-f1** [comment]
Thanks for that! It looks like the difference is that we’re expecting the payee to be the `NAME` of the transaction but your data has it as the `MEMO` instead (which we put in the notes field). I’m not sure what we should do — maybe interpret the memo as the payee if the payee is missing?

**Comment by Jackenmen** [comment]
If this happens for all transactions then generalizing the UI for CSV imports (with default columns prefilled) could make sense, perhaps?

But if it happens only for some transactions then I think that falling back to `MEMO` is currently the only option. The rules engine doesn't currently support templating so it isn't possible to use the value of Notes field in Payee. A suggestion for templating was recently made in the Discord server but it doesn't sound like something that would be easy to implement so adding a fallback would make most sense, at least for now.

**Comment by damomato** [comment]
I would think it's happening on all transactions for this particular bank, when I have some time later I'll download transactions for another bank and see if it's the same.

Of course an Aussie bank does it different 😵

**Comment by damomato** [comment]
I tried another bank and it uses Memo as well. Not only that, it doesn't even import any transactions. It sometimes shows zero transactions and sometimes shows an error. Should I open a new separate issue for that?

![image](https://user-images.githubusercontent.com/85538685/226153793-eebdbfeb-bfb6-4d5e-bff3-cc1dd16f290b.png)

![image](https://user-images.githubusercontent.com/85538685/226153781-f33b288b-8faf-4758-8a2c-43d037fed64e.png)

**Comment by j-f1** [comment]
Yes, please open a separate issue for that and attach the files that can’t be imported.

**Comment by damomato** [comment]
Thanks, I've added it now. I also removed the OFX file from this issue as I realised there was sensitive data I forgot to remove. Let me know if you need it again and I'll clean it up and upload.

**Comment by damomato** [comment]
I just installed the new release (v23.5.0) but am still having the same issue, Payee remains blank

I'm using the normal 'Import' button in the account. Is there a different import method as part of this release?

**Comment by rafacla** [comment]
Here aswell, other apps have the option to disable/enable payee/memo swap, looks like it's a standarlization problem across the globe

**Comment by Shazib** [comment]
@damomato can you try this after the latest fix? then we can close this off

**Comment by damomato** [comment]
I can confirm that this issue is now fixed in v23.7.1, thanks for the great work guys!

However issue #764  is still not fixed, same issue there with "no transactions found".
