### ISSUE TITLE
[Feature] Add 'Day of Week' to rules option

### ISSUE THREAD

**Issue by shall0pass** [actualbudget/actual#788]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

It would be nice if i could add the day of the week to a rules option.

For example, my wife and I have separate fuel categories so we can monitor individual usage by vehicle.  I usually only visit Hucks on M-F and my wife only visits on Sat-Sun.  If i could write the rule to check against the day of the week the transaction is entered, i could have it auto categorize the transaction more accurately more often.

**Comment by youngcw** [comment]
Maybe try the new templating thing to see if you can make that work
