### ISSUE TITLE
[Bug]: OFX returns 'no transactions found'

### ISSUE THREAD

**Issue by damomato** [actualbudget/actual#794]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Similar to another issue I posted https://github.com/actualbudget/actual/issues/767 as this OFX also uses MEMO field for payee.

When trying to import the attached OFX file it returns 'no transactions found' and after enough tries just displays an error. OFX file zipped below.

[Transactions.zip](https://github.com/actualbudget/actual/files/11014996/Transactions.zip)

![error1](https://user-images.githubusercontent.com/85538685/226269183-13c138b1-df25-4413-aab0-5cb23e798f40.png)

![error2](https://user-images.githubusercontent.com/85538685/226269192-79ef3df6-ac12-4211-8a9e-47c613a54a89.png)

Would really like to use this service so hope the fix isn't too difficult :)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

**Comment by j-f1** [comment]
Update: I spent a few hours trying to rebuild the `libofx.wasm` file in [`node-libofx`](https://github.com/actualbudget/actual/tree/master/packages/node-libofx), but it unfortunately seems like modern versions of Emscripten are not capable of building libofx/opensp anymore, so it will be very difficult to turn on the debugging flags in `libofx`. As a result it will not be very possible to debug why exactly libofx is failing to parse this file (or update it to a newer version). If you (or anyone else reading this) enjoys working with emscripten and wants to get the build working again that would be much appreciated!

**Comment by MatissJanis** [comment]
I just tested this with the new OFX parser (enabled by default in latest release) - this has been fixed. 🎉
