### ISSUE TITLE
Can't have multiple finances[Bug]: 

### ISSUE THREAD

**Issue by Lennert159** [actualbudget/actual#796]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I added and renamed a second finance, then added multiple accounts with a starting bugdet.

When I then go back and forward in the finances, it just becomes the same, I add a transaction in the first finance, and it shows up in the second one and vice versa.

I host my own server on Unraid - docker.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Linux

**Comment by j-f1** [comment]
This is a known issue when running in the unsupported mode where SharedArrayBuffer is unavailable. See [our documentation page on this issue](https://actualbudget.github.io/docs/Troubleshooting/SharedArrayBuffer) for an explanation of what’s going on and how to fix it.

**Comment by Lennert159** [comment]
Hello,

Can I add the "SharedArrayBuffer" manually on UnRaid, or will this be done automatically with an update?

Cause I really like the style of the app.

Thanks in advance
Lennert
________________________________
Van: Jed Fox ***@***.***>
Verzonden: maandag 20 maart 2023 22:05
Aan: actualbudget/actual ***@***.***>
CC: Lennert159 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [actualbudget/actual] Can't have multiple finances[Bug]: (Issue #796)


This is a known issue when running in the unsupported mode where SharedArrayBuffer is unavailable. See our documentation page on this issue<https://actualbudget.github.io/docs/Troubleshooting/SharedArrayBuffer> for an explanation of what’s going on and how to fix it.

**Comment by j-f1** [comment]
Once you set up HTTPS, you will no longer see the error page or run into new data corruption issues.

**Comment by Lennert159** [comment]
I was able to setup HTTPS, the error page is gone.

But I'm still not able to manage 2+ finances separate
________________________________
Van: Jed Fox ***@***.***>
Verzonden: donderdag 23 maart 2023 21:20
Aan: actualbudget/actual ***@***.***>
CC: Lennert159 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [actualbudget/actual] Can't have multiple finances[Bug]: (Issue #796)


Once you set up HTTPS, you will no longer see the error page or run into new data corruption issues.

**Comment by j-f1** [comment]
Any merging of data that has already occurred will not be fixed by enabling HTTPS. If you’ve cleared your browser’s cache and are still seeing new data being merged, please let me know any other details you can provide — I don’t think we’ve seen that before.
