### ISSUE TITLE
[Feature] Import CSV with amount and in/out flow column

### ISSUE THREAD

**Issue by Rayvw** [actualbudget/actual#805]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Hi,
I recently discovered Actual and I'm really interested in using it. I love the simplicity and ease of use. However, the following issue makes me not able to use it.
My bank (ING Netherlands) provides a CSV file with two columns regarding the amount: Debit/credit (Af / Bij in Dutch) and Amount. The first column specifies whether the amount stated in the second column is either inflow or outflow. The second column is always a positive number (so, no minus sign for outflow). Currently, I cannot import this file because this format is not supported.
[ing_example_nl.csv](https://github.com/actualbudget/actual/files/11037614/ing_example_nl.csv)
[ing_example_en.csv](https://github.com/actualbudget/actual/files/11037615/ing_example_en.csv)

### Describe your ideal solution to this problem

I am in doubt about what would be a nice solution that doesn’t compromise the simplicity of the import modal. I think the most flexible solution would be to consider the Debit/credit column as a per-column multiplier. In that case the contents have to be transformed during the import process: 'Credit' will be a multiplier of 1 and 'Credit' will be a multiplier of -1. The import modal should have the option to define this. I’d like to hear your opinion on this and possible other solutions!
I attached a sample CSV file both in English and Dutch.

**Comment by Rayvw** [comment]
I just realized a very simple solution that works for me. Probably a bit ugly solution but maybe it helps others or is the key to an implementation in actual.

As the the columns are next to each other, using find & replace one can easily add the minus sign to outflow (Debit). I open the file in notepad and use find & replace: find: `Credit";"`, replace with: `Credit";"-`. For the Dutch CSV file: find `Af";"`, replace with: `Af";"-`.

**Comment by j-f1** [comment]
I believe this bank also supports CAMT.053, which will be supported once #740 is finished and merged.

**Comment by Rayvw** [comment]
Unfortunately that's only supported for business accounts. Private accounts can export the transactions as either CSV or PDF.

**Comment by youngcw** [comment]
This feature was added in #1788. Closing
