### ISSUE TITLE
[Feature] Import: recognize parentheses as negative amount, e.g. ($12.00)

### ISSUE THREAD

**Issue by aharbis** [actualbudget/actual#807]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

From Account > Import, attempted to import a CSV which uses the following format for the Amount column:

- debit/outflow: `$(12.34)`
- credit/inflow: `$12.34`

This is not recognized by Actual, and both amounts are treated with the same polarity (positive, by default).

This can be recreated with the following CSV: [test.csv](https://github.com/actualbudget/actual/files/11045729/test.csv)

```csv
Date,Transaction Type,Description,Amount
01/01/2023,Credit,Paycheck,$400.00
01/02/2023,Debit,Restaurant,($30.00)
```

This produces the following:

![image](https://user-images.githubusercontent.com/20443310/227067285-86780139-230c-4588-badf-973f4fc6bfd7.png)

### Describe your ideal solution to this problem

During the Import process, when parsing the `Amount` column values, recognize the format `($30.00)` as negative.

For example: `($30.00)` should be equivalent to `-$30.00`

### Teaching and learning

This could be automatic imo, but a toggle could be added similar to what's shown here if necessary:

![image](https://user-images.githubusercontent.com/20443310/227068311-1ce828a8-2f8b-4db3-bfa4-56ca19227132.png)

**Comment by Jackenmen** [comment]
Out of curiosity, which bank uses such a format?

**Comment by aharbis** [comment]
Truist (formerly BB&T) - https://www.truist.com/

**Comment by Jackenmen** [comment]
While not a solution to this issue, there's one possible workaround - I believe that Truist should support the QFX format (Quicken) which can be imported by Actual.
