### ISSUE TITLE
[Bug]: Budget Template Not Applying To All Categories

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#809]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When applying my budget template, not all categories were populated. 

On further inspection it seems as though categories that had money "Budgeted" during the current month are ignored if the "Apply Budget Template" is run again in the same month. 

This could pose a problem for people who are paid off a regular schedule, weekly pay for example or fortnightly, this would need testing on a test budget of course but it does seem to point to that being the reason and could do with being resolved. 

I wouldn't want the category overwritten if the template was run again in the same month but the budgeted amount would be incremented onto the template value. 

### What error did you receive?

None

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

**Comment by Kidglove57** [comment]
My only initial comment would be that there are already example templates given in the documentation for those who need weekly or two weekly fills.
https://actualbudget.github.io/docs/Advanced/Experimental-Features/goal-templates
