### ISSUE TITLE
[Feature] Number format, multiple accounts on the same CSV, currencies, others

### ISSUE THREAD

**Issue by joaociocca** [actualbudget/actual#810]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

From what I'm seeing, I'm coming from two scenarios never before imagined for Actual:

1. YNAB import with several accounts (I see Actual supports multiple accounts, but not CSV importing with this)
2. Brazilian number format (Brazilians use `,` for decimals and `.` for thousands and up, along with our currency (Brazilian Real) being shown as R$)
3. Multiple currencies (beyond my BRL account, I also have USD and EUR accounts)

From 1, I noticed a couple improvements for the CSV importer:

a. map an "Accounts" field to import each transaction on their respective account (since Actual already supports multiple accounts, it's all a matter of adding it's mapping to the importer, I'd guess)
b. allow using `\t` and other characters as the CSV separator (maybe automatically identify which character is being used to separate (single? double?) quotes, and suggest that to be used for importing the file)
c. (this is where 2 comes in) correctly read values from different currency formats (a field with a value of `R$1652,29` will currently be read by Actual as `29`  - which I find really curious, because I just noticed that I have already set Actual to use the decimal comma, so both my current budget and inputting a new transaction already use decimal comma)
d. add Group/Category import (I see Actual's budget already has groups + categories, so they'd just need to be supported on the importer itself)
e. support for UTF8 and emoji in all text fields (from what I'm seeing at the import preview screen, an emoji like 🔴 or ⚡will currently be ignored - I see they are already supported on Actual's transaction notes, but they don't seem to be read from the CSV)
f. allow outflow to be read from absolute values (YNAB, for instance, exports an outflow as `R$1652,29` instead of `-R$1652,29` or `(R$1652,29)`)

For 3 I haven't had issues currently because I wasn't really tracking my foreign accounts on YNAB, but I did take a look at a competitor (Money Manager Ex) and that one allows it, and I really liked that option, along with showing exchange rates (which a button click will query somewhere on the internet and update - sounds like a nice addition too)

### Describe your ideal solution to this problem

I think I already did problem + ideal solutions up there, np?

### Teaching and learning

I think most of my suggestions affect the import CSV function, so it'd mainly be used by new users

**Comment by j-f1** [comment]
Thanks for all the feedback! I think I’ve addressed all of your points below, but definitely let me know if I’m missing anything:

- CSV importing for multiple accounts is being tracked by #525. If you want to import from an existing YNAB file, close your existing budget and choose “import” on the file screen to import from YNAB.
- Adding a tab as a separator option is a good idea, we currently support `,` and `;`. Do you have any other possible separators?
- This should already work correctly, the [underlying code](https://github.com/actualbudget/actual/blob/ba778c9e9f102f301099b3e7e29de54e9fb6c190/packages/loot-core/src/shared/util.js#L375-L389) grabs everything after the last `.` or `,` along with everything before that separator, then remove everything besides digits, then parse the number. Can you share the exact value from the CSV that is failing to parse?
- We’re tracking importing categories in #557
- What encoding is your file using? It’s possible we’re not parsing the correct encoding, which would cause the emoji to be corrupted.
- What do you mean by “allow outflow to be read from absolute values?”
- We don’t have a tracking issue for multiple currency support at the moment but it is a request that we’re aware of. It would require significant changes to many core parts of Actual that would make developing and using it more complicated, so we’re unlikely to implement it in the near future.

**Comment by j-f1** [comment]
> but this does not explain why Outflow isn't being read from the remaining R$1652 value?

It doesn’t apply any filtering if it can’t detect a comma or period in the currency amount, so it doesn’t know how to handle the `R$` part. We should change that!

**Comment by joaociocca** [comment]
Considering there's the actual (tumdumts) nYNAB importer, I don't really see an issue there - specially considering that thinking about it now, well rested, after sleeping on it, feels to me like it's YNAB who did the CSV wrong - value fields should be value only, shouldn't contain strings, specially if the currency itself isn't used... and if the currency is used, it stops being a value and becomes a string, and so should be quoted.
But I guess that simply implementing the tab delimiter should be enough to clear this issue...

Moving on, I got to import my json and start using Actual... but it feels really weird for it to consider everything as executed, despite having scheduled transactions. The lack of a separator between past/today transactions and scheduled ones is also confusing. We have to really pay attention and look at the date to understand what is future scheduled transactions. And the accounts value already considers scheduled transactions as if they affected the balance today.

I think it's easier to show:

![image](https://user-images.githubusercontent.com/6473725/227529846-6301a89f-e637-4947-8aa2-2105343ea9b2.png)
