### ISSUE TITLE
[Bug]: onboarding loading screen

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#812]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

This is only in `master` branch.

The "loading" indicator when creating test budget or your first budget used to be on a separate page. Now it overlays the existing page which creates this weird state.

<img width="687" alt="Screenshot 2023-03-24 at 19 38 03" src="https://user-images.githubusercontent.com/886567/227623517-608d3259-04b5-4434-aa4f-b538b8417761.png">

### Where are you hosting Actual?

None

### Operating System

None

**Comment by j-f1** [comment]
I’ve seen this too. I think I must have done something wrong in #676. There’s some other weird issues with things not appearing/disappearing when they should. I don’t know when I’ll be able to take a closer look and get this fixed since I will be on vacation for about the next week.

**Comment by MatissJanis** [comment]
> I’ve seen this too. I think I must have done something wrong in #676. There’s some other weird issues with things not appearing/disappearing when they should. I don’t know when I’ll be able to take a closer look and get this fixed since I will be on vacation for about the next week.

Take your time! Well deserved :)

Hopefully someone else in the community picks it up in your absence.

**Comment by j-f1** [comment]
I think his was fixed by #853
