### ISSUE TITLE
[Feature] Option not to delete linked transfer transaction

### ISSUE THREAD

**Issue by winklevos** [actualbudget/actual#814]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [x] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

If you delete a transaction from account B which is a transfer which has been linked to another transaction in account A it will delete both the transactions. 

This is problematic if you are correcting an account where it would be easier to delete transactions back to a date where it was reconciled and import the source from that date. However, this would break any accounts transferred from or to the account. Making it very painful to fix. 

This is especially prevalent when you import multiple accounts which have many transfers between them.

If you don't mark transfers and link them they show as categorized and throw off budgets 

### Describe your ideal solution to this problem

Either scope delete to the account that the delete is originating from, or an option in settings to change the behavior.

**Comment by MatissJanis** [comment]
👋 Could you pitch **the problem** once more? The current problem definition reads more as a solution to problem X. But I don't understand what the problem X is. Sounds like it has something to do with imports?

> If you delete a transaction from account B which is a transfer which has been linked to another transaction in account A it will delete both the transactions.

This is by-design and should not be tampered with. A transfer between accounts will always create 2x linked transactions. The alternative approach you can take is to manually create 2x single transactions (one per each account). But again: I don't yet understand the problem you're facing, so my suggestion might not work for you.

**Comment by MatissJanis** [comment]
Sorry to ask again, but could you spell out **the problem** once more? I still don't understand the problem you're facing. Maybe provide an example import file as an illustration.

**Comment by MatissJanis** [comment]
Did you consider removing the rule that creates the transfers from your imports? If the transactions are not transfers - you can delete them as you want and it will not affect the other accounts.

**Comment by MatissJanis** [comment]
Right, but that would solve your problem. You would have 2x un-linked transactions and you could delete/modify them as you pleased. Changes in one account would not affect the other.

-

I see why you want to delete the transfer transaction in one account, but keep it in the other, but this opens up a whole world of additional problems. For example: what exactly happens if you delete only one side of the transfer? Where does that money go? It won't appear in the budget. But it will be deducted from the account total. So it sort of just "disappeared". Is it even still a "transfer" if it only has one side of the transaction? How does that reflect in reports? 

I don't expect to get answers to these questions btw. They are rhetorical in order to give you a sense of the complexity of doing the proposed change.

And this is why I am against doing the proposed change. Money should not just "disappear". There should be a precise log of transactions of how money moves in to the budget. Later on from account to account. And how it flows out of the account.

**Comment by Jackenmen** [comment]
As I understand the problem, winklevos wants to delete transactions (some of which are transfers) from one account and later re-add them by importing transactions starting from some date. So presumably, that would mean that after the deletion, the transfer on the other side would become a regular transaction, counting against the budget (this is the only sensible solution, as the money obviously can't disappear). *However*, after importing, they would most definitely need a way to (manually, I imagine) transform two transactions on different accounts into a transfer again. This does seem like a rather complex problem to resolve in a user-friendly way.

I do have an alternative suggestion that, based on my understanding of the problem, would still resolve it, just in a bit different way. How about we extend the transactions filter functionality to support filtering based on whether transactions are transfers? This way, @winklevos could filter their transactions with a new "is not transfer" option and be able to easily select all other transactions, delete them, and then import transactions again. This way, the transfers would just not get removed making the feature proposed here unnecessary, and, after the import, those transfers would just get reconciled appropriately.

**Comment by Jackenmen** [comment]
> I'll test again but I think that's how it behaved in my dev branch

I haven't looked at your PR but do you actually clear the payee after transforming a transfer into a regular transaction? And I guess I should also ask whether you even transform it into a regular transaction.

**Comment by shall0pass** [comment]
I've been quietly following along.  I'm not going to argue for or against unless it totally breaks things, but I am a bit confused about what's going on here.  Interestingly enough, it doesn't affect the "To Budget" amount and only breaks the account balances.

![deleteTransfers](https://user-images.githubusercontent.com/20625555/230920762-ed53281d-f231-45ab-8e15-6dc779d5101b.gif)

**Comment by MatissJanis** [comment]
👋 I'll close off this specific feature request as not-planed. Money in a budget should never "disappear", so one-sided transfers are not a feature we plan on supporting.

However, the _real_ problem that was outlined can be solved by other means (see discussions above). What's more: [this feature request](https://github.com/actualbudget/actual/issues/904) might also solve the original problem in a more sensible way.
