### ISSUE TITLE
Transfer linking not always working

### ISSUE THREAD

**Issue by carkom** [actualbudget/actual#820]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When I import transactions half the transfers are correctly linked to existing accounts and the other half do not. These are linked between the same 2 accounts. Transfers in both accounts happen on same day for exact same amount. 

Firstly, this bug should be fixed.

Secondly, there should be a way to link 2 transactions as the same transfer so that they are not duplcating eachother. I haven't not found a way to manually link the transfer. Is it possible?

### What error did you receive?

No errors, just not functioning correctly.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 10

**Comment by carkom** [comment]
You can see that all the other payments show a link symbol on the left and correctly linked to the transfer from the checking account. So what prevented this one from working? 

- Also, in cases where this happens we should have a way to manually link transfer transactions. 
- We should also have a way to manually unlink them in cases when some manual manipulation is needed to get everything correct.

![image](https://user-images.githubusercontent.com/55785687/228188646-ccbbccd3-035a-4a30-93bc-800d6a66ecb7.png)

**Comment by j-f1** [comment]
Related: #669
