### ISSUE TITLE
[Tech Debt] remove `@reactions/component` dependency

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#821]
Remove `@reactions/component` dependency.

**Comment by martinyis** [comment]
Hey, I can do it, assign it to me!

**Comment by j-f1** [comment]
Hi Martin! Thanks for your interest. We don’t typically assign issues to new contributors, but if you want to open a PR we’d be happy to review it! We’d also be happy to help out if you run into any problems when working on this issue.

**Comment by joel-jeremy** [comment]
Was this already done? If not, what package is this on? I don't see @reaction/component in the dependencies.

**Comment by j-f1** [comment]
Yes, I forgot to tag this issue in https://github.com/actualbudget/actual/pull/1036. Thanks for catching!
