### ISSUE TITLE
[Tech Debt] Upgrade `react-router` to v6

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#822]
Upgrade `react-router` to v6. There is already some work started here, but not finished. Search for `react-router-dom-v5-compat`

**Comment by trevdor** [comment]
Work-in-progress on [branch `trevdor-react-router-6`](https://github.com/actualbudget/actual/tree/trevdor-react-router-6)

Following the steps advised in https://reactrouter.com/en/main/upgrading/v5#introduction
Also referencing mjackson's [Composing Routes](https://gist.github.com/mjackson/d54b40a094277b7afdd6b81f51a0393f)
