### ISSUE TITLE
I can't get HTTPS working

### ISSUE THREAD

**Issue by Lennert159** [actualbudget/actual#823]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I'm trying to setup HTTPS.
For the certificates I use the ones from "SWAG", which I use for my Nextcloud, Plex, ... Servers. So it should be valid certificates.
I followed the guide for the rest, but still can't get HTTPS running.

I run Actual and SWAG on my own UnRaid server.

I added pictures how I've setup everything:

The Actual map
![Actual-map](https://user-images.githubusercontent.com/65245123/228038141-54221635-e078-42ac-8b07-1e8628c0cd7a.PNG)
The data map
![Data-map](https://user-images.githubusercontent.com/65245123/228038140-d2bd2862-bda1-4540-8ed4-fb61fb326c1a.PNG)
config.json file
![config-file](https://user-images.githubusercontent.com/65245123/228038135-45691560-7a8e-4a2e-b400-07302eb5bae0.PNG)
Docker settings
![Docker settings](https://user-images.githubusercontent.com/65245123/228039137-8d8830e9-d45d-4297-b785-4b91c5cb2169.PNG)

### What error did you receive?

![HTTPS-error](https://user-images.githubusercontent.com/65245123/228038558-abc3a290-6b19-4f60-9a0a-acda83acbfe9.PNG)

### Where are you hosting Actual?

NAS

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Operating System

Linux

**Comment by j-f1** [comment]
I would recommend setting up your files like this:

```
/mnt/user/appdata/actual-server/:
  server-files/
  user-files/
  config.json
  selfhost.crt
  selfhost.key
```

Then remove your existing volume mounts and mount `/mnt/user/appdata/actual-server` to `/data` in the container. Everything should work once you do that — let me know if you run into any additional problems!

**Comment by Lennert159** [comment]
Hello,

I still struggled a bit, but it works now!

Thank you so much!!
Lennert
________________________________
Van: Jed Fox ***@***.***>
Verzonden: dinsdag 28 maart 2023 1:33
Aan: actualbudget/actual ***@***.***>
CC: Lennert159 ***@***.***>; Author ***@***.***>
Onderwerp: Re: [actualbudget/actual] I can't get HTTPS working (Issue #823)


I would recommend setting up your files like this:

/mnt/user/appdata/actual-server/:
  server-files/
  user-files/
  config.json
  selfhost.crt
  selfhost.key


Then remove your existing volume mounts and mount /mnt/user/appdata/actual-server to /data in the container. Everything should work once you do that — let me know if you run into any additional problems!

**Comment by j-f1** [comment]
Glad you got it working!
