### ISSUE TITLE
[Feature] Per-month budget category notes

### ISSUE THREAD

**Issue by biohzrddd** [actualbudget/actual#824]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I need to keep track of category-to-category money moves that don't have a transaction. Examples:

- My kids have "savings" and "fun money" categories. When I "pay" my kids for babysitting, I move money from my "fun money category" to theirs with no bank transaction. In the note I can add the date they did the babysitting and amount added.
- Moving money between categories to cover unexpected expenses, and you want to remember why (maybe to replace that money later).

### Describe your ideal solution to this problem

YNAB4 had this feature and I use it regularly (with better grammar of course :)). There would be a note icon next to each category amount that behaves the exact same as the main category notes -- no icon if empty, show icon on hover, keep the icon if there is a note.
![image](https://user-images.githubusercontent.com/10577752/228071009-f436cdf4-65c4-48e4-93da-57a0767e727e.png)

While this could be done with the month notes, it is less visible when paying attention to category amounts flipping through months.

### Teaching and learning

The note icon will appear on hover of the budget category amount, users will notice after update and use it like the other notes available for category and months.

**Comment by Kidglove57** [comment]
I am one of those who at present add this to the monthly notes.

However, I rather like the way a number of other apps do this (Moneywiz, Moneywell, GoodBudget) in that they have a complete audit trail of all movements between budget categories, to which a note can be added (and retrospective adjustments made if needed). However, it may well be that they are completely different in their "architecture" so as to give this visibility.

**Comment by mullermn** [comment]
I want to add support for this.

In YNAB if I had to do something odd with a category (eg, pulling a large amount out of a category because future plans changed) I would add a note so that the figure made sense next time I looked at it.

Actual is acquiring some really powerful abilities (templates, sink/source) for automatically changing budgeted figures but I feel like it's certain that at some point I'm going to accidentally overwrite an exceptional figure with a script-based one. A narrative record about what I was thinking when I did the original budget is very useful.

**Comment by cybergrimes** [comment]
YNAB4 user for past 10 years, just found Actual last week and really like it. Great work. I am terribly missing this ability to make notes on individual budget items. I will use the monthly notes option but setting them at the budgeted line level would be amazing.
