### ISSUE TITLE
[Feature] Added Rule Option: Add percentage of Income to budget category when entered

### ISSUE THREAD

**Issue by youngcw** [actualbudget/actual#828]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I would like to be able to set a percentage of income to go to a certain category automatically.  EX 10% to a savings category, or charitable donations category.  For now the closest thing is a dollar amount estimation based on a mostly consistent income.

### Describe your ideal solution to this problem

A new rule action would have to be made other than "set".  A "distribute" or "budget" action could be made and the parameter would be a percent value.

Example: 
Condition=Category is Income     and
Condition=Payee is My_employer

Action=Budget apply 10% to "Long Term Savings"

### Teaching and learning

The docs would need updated to show the new rule action possibly with an example

**Comment by j-f1** [comment]
Would the [experimental goal template feature](https://actualbudget.github.io/docs/Advanced/Experimental-Features/goal-templates) work for your use case?

**Comment by youngcw** [comment]
I could get a good ballpark with the templates.  I do worry about if the income comes in multiple pieces or inconsistently the templates would probably not match the true goal very well any more.  That's still a bit better than manually handling categorizing the percentage every time.  

Having a rule that runs every time new income is entered would confirm that the percentage is based on true income and that nothing gets missed and needs manual intervention later.

**Comment by youngcw** [comment]
PR: #858 Is working on this in template form instead of a rule.

**Comment by youngcw** [comment]
Closing for the time being as the template version is working well.
