### ISSUE TITLE
[Bug]: Unable to use Safari as a client

### ISSUE THREAD

**Issue by chowhi123** [actualbudget/actual#829]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Using safari client it is continuing to prompt for update which doesn't seem to be a problem on the chrome on same machine. M2 macbook air with ventra. I will update the post with screenshot.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Safari

### Operating System

Mac OSX

**Comment by j-f1** [comment]
Can you add that screenshot? I haven’t personally seen this issue in Safari.

**Comment by chowhi123** [comment]
> 

Hi the problem persist for a day and was resolved. I am assuming this was due to pihole which cache the issue when happened. I can't seem to reproduce the issue so I will close this and comeback if I ever face the problem again.
