### ISSUE TITLE
[Bug]: Monthly navigation arrows

### ISSUE THREAD

**Issue by shall0pass** [actualbudget/actual#830]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

This is only in the master branch and is not present in the last stable release. 

The monthly navigation arrows appear to be missing.

Latest stable
![Screenshot_20230330-144736-415](https://user-images.githubusercontent.com/20625555/228948592-b6eaa6f8-5105-4a79-854f-ae7ddd413125.png)

Master branch using actualbudget.netlify.app
![Screenshot_20230330-144846-873](https://user-images.githubusercontent.com/20625555/228948693-65d9e6a7-9a24-4576-ade9-37e4d79cb521.png)

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Chrome

### Operating System

Linux

**Comment by MatissJanis** [comment]
<img width="582" alt="Screenshot 2023-03-30 at 20 54 28" src="https://user-images.githubusercontent.com/886567/228949347-ec88bde3-2587-4c83-a89b-1b03a5970d42.png">

CSP violations on Netlify preview builds. This does not affect the release or local development.

**Comment by j-f1** [comment]
I was wondering why the checkmarks in checkboxes weren’t showing up… that explains it!

**Comment by shall0pass** [comment]
Closing based on feedback.
