### ISSUE TITLE
[Feature] Credit Card Category

### ISSUE THREAD

**Issue by adbsmith** [actualbudget/actual#833]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I think it would be great to have Actual be able to create a credit card category in your budget that is linked to a credit card account. This request has been discussed at further length in the Discord here: https://discord.com/channels/937901803608096828/1089553698008604752. The impetus for this feature would be to help users remember to allocate money they actually have from their bank account to cover the money they have borrowed on their credit card in order to maintain a $0 balance on credit cards as much as possible. Based on feedback from other users, perhaps this could be an option that is either switched on or off when creating a credit card account so not everyone has to use it?

### Describe your ideal solution to this problem

A possible solution could be that transactions entered on your credit card process as usual (i.e. the amount is categorized under the spent column for the spending category it falls under), but then the amount spent is also auto-budgeted under the the credit card's spending category. This would allow us to maintain the analytics of seeing where money has been spent while also effectively reallocating money from a spending category to the credit card category.

**Comment by youngcw** [comment]
closing in favor of #1995
