### ISSUE TITLE
[Feature] Enable single transaction dropdown to make changes 

### ISSUE THREAD

**Issue by adamkelly86** [actualbudget/actual#871]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Currently, you have to select an item on the left hand side to adjust the transaction status using the xx transactions selected on the right hand side.  Whilst this makes sense for multiple transactions, there isn't a way to do this without moving from one side of the screen to the other. 

![image](https://user-images.githubusercontent.com/37782715/230621649-9f3360bf-6ea3-4898-b0ed-f872561ebe68.png)

### Describe your ideal solution to this problem

A possible solution is a contextual menu for single transactions (using a ... or a down arrow icon) for making changes to the right of the calendar icon (similar to below)

![image](https://user-images.githubusercontent.com/37782715/230621451-c88495ab-e8e3-4f7f-81b7-d3922771cdbd.png)

**Comment by j-f1** [comment]
Wouldn’t the “…” button be right next to the dropdown button anyway?

**Comment by j-f1** [comment]
This is an interesting idea! I’m not sure it would be worth losing that amount of horizontal space (especially on narrower screens) for this feature, but it would be nice to have some way to do this — maybe a right-click menu?

**Comment by adamkelly86** [comment]
A right-click context menu is a possible solution, however I don't believe there are any right-click context menus anywhere else in the web interface currently.

**Comment by rich-howell** [comment]
If this issue is specific to changing the status of upcoming transactions? You can already post multiple transactions at once by selecting each upcoming transaction then selecting the dropdown and pressing **Post Transaction**

![image](https://user-images.githubusercontent.com/22135084/231673959-ffaa53d9-1ca3-4ab4-ab75-41b469396b25.png)

I think as @j-f1 said adding a `...` menu on the transaction row would take up valuable space and would more than likely be excluded on mobile.

**Comment by adamkelly86** [comment]
The issue is changing a single transaction. 

Whilst I agree that mobile should be considered, going ~1800 pixels right on a 1080p monitor isn’t really a good UI experience for accounts such as fixed savings or regular savings accounts that may only see 1 / 2 transactions a month.

Another possible desktop solution is to enable a keyboard shortcut such as (P) for post or (A) for approve when selecting a single transaction.  This covers a desktop use without interfering with a mobile view.

**Comment by tjfinlinson** [comment]
I am a fan of keyboard shortcuts on a computer vs needing to grab the mouse and click a menu. It can speed up data entry and keep you in a good flow. The idea of having a keyboard shortcut for this seems like a great idea.

**Comment by matt-fidd** [comment]
You can now right click for most options
