### ISSUE TITLE
[Bug]: Switching a rule condition from “payee is” to “imported payee is” clears its value

### ISSUE THREAD

**Issue by j-f1** [actualbudget/actual#872]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

1. Select a payee in the payees list with no rule. Click “Create rule.”
2. Change the condition from “payee is” to “imported payee is”

Expected behavior: the value field is filled with the name of the payee
Actual behavior: it is cleared

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Safari

### Operating System

Mac OSX

**Comment by MatissJanis** [comment]
I'm torn on this one. Practically `imported_payee` is different from `payee`. For example:

```
imported_payee: CRV*Starbucks Dublin Docks
payee: Starbucks
```

But from another perspective.. they are very related fields.

Maybe we keep this as-is? That makes the logic simpler to reason about. Switching from ANY field to ANY OTHER field just clears the value. With no exceptions.

**Comment by aaroneiche** [comment]
In this case, I think the experience for the user is degraded when this happens. They approached the "create rule" interface from payees, rather than just starting with a blank rule. I'm kind of inclined to say that the field should not be cleared regardless of changing the key. Kind of...

**Comment by youngcw** [comment]
I don't think there is a way to gracefully transition from payee to imported payee when changing the rule condition.  Seems like, at best, it would only give a sometimes right imported payee and, at worst, be a useless rule that never triggers.  

@MatissJanis I think this should be closed, what do you think?
