### ISSUE TITLE
[Bug]: Template application throws error when values with 1 decimal digit used

### ISSUE THREAD

**Issue by mkalamarz** [actualbudget/actual#888]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

How to reproduce:
1. Create a template with 1 decimal digit e.x. "#template 50.5"
2. Try to apply it
3. Get an error

I understand that the solution is to input "50.50" but from a UX perspective it's quite intuitive that 0.5 should expand to 0.50.

Version: v23.4.0

### What error did you receive?

There were errors interpreting some templates:
Bills: Expected end of input or space but "." found.
#template 50.5

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 10

**Comment by youngcw** [comment]
This has been fixed.  I imagine the issue should be closed.
