### ISSUE TITLE
[Bug]: Enter key no longer works after latest update

### ISSUE THREAD

**Issue by Kurokha** [actualbudget/actual#892]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Since the latest update of v23.4.0 the enter key (bottom right of the numeric keypad) can no longer be used in Actual to post a transaction, submit a value to the budget or to move up or down in the budget categories. Nothing happens when that key is pressed. Instead, the return key (right edge of the main alphanumeric keyboard portion) has to be used.

The enter key can still be used to confirm a selected a value from a drop-down like payee or category.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### Operating System

Windows 11

**Comment by j-f1** [comment]
I believe this was fixed by #883, can you test out on https://actualbudget.netlify.app to confirm?

**Comment by j-f1** [comment]
Thanks for confirming!
