### ISSUE TITLE
[Bug]: update a "missed" upcoming transaction

### ISSUE THREAD

**Issue by joaociocca** [actualbudget/actual#897]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I forgot to mark an upcoming transaction on the day it happened... and now there's a red skull there and I can't do anything with it? Am I missing something?

![image](https://user-images.githubusercontent.com/6473725/232080948-dcbb249b-7a29-4dfa-83ee-f2cf20622538.png)

![image](https://user-images.githubusercontent.com/6473725/232081056-fa4403c6-7ac9-4da1-9ec6-7e4084789d9a.png)

Ok, granted I can manually add a new transaction and it'll overwrite the "dead/missed" upcoming entry... but shouldn't I be able to just change the missed upcoming into an actual (heh) transaction?

(selected Browser as Other,  it's Vivaldi, Chromium based - normally I'd select Chrome for it, but since there's also an option for Edge...)

### What error did you receive?

None

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Other

### Operating System

Linux

**Comment by shall0pass** [comment]
You should be able to select "Post transaction" to add it.

**Comment by joaociocca** [comment]
for some reason I understood "post transaction" as... how can I put this? post in after, not post in posting it. Does that make any sense?
