### ISSUE TITLE
Docker Support

### ISSUE THREAD

**Issue by cuken** [actualbudget/actual#9]
Something I may try to tackle myself but:

It would be nice to have each component in a docker container so self hosting would be easier to adopt.
I'm still trying to understand all the moving parts of the server but if possible, a container for:

- Sync Server
- API (does this need to run separately now?)
- UI

**Comment by andymcblane** [comment]
Thinking docker-compose?

**Comment by Nsttt** [comment]
Adding a docker-compose will be quite helpful indeed.

**Comment by cuken** [comment]
Looks like actual server already has a working [DockerFile](https://github.com/actualbudget/actual-server/blob/master/Dockerfile)

**Comment by cuken** [comment]
Submitted pull request via   #11 to add the docker-compose file.
