### ISSUE TITLE
Replace `currency-formatter` with `Intl.NumberFormat` to reduce dependencies

### ISSUE THREAD

**Issue by TomAFrench** [actualbudget/actual#90]
We've currently got a dependency on a fork of `currency-formatter` which in turn depends on a fork of `
accounting.js` (both maintained by jlongster). This is only used twice in the entire codebase.

https://github.com/actualbudget/actual/blob/b4696ce5989a79065f6ef30dd32cff7e59044852/packages/loot-core/src/shared/util.js#L289-L294

https://github.com/actualbudget/actual/blob/b4696ce5989a79065f6ef30dd32cff7e59044852/packages/loot-core/src/shared/util.js#L322-L324

As mentioned in the comment if we switch to use [Intl.NumberFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat) then we can ditch these dependencies as they're not particularly necessary. Intl is [well supported](https://caniuse.com/?search=intl.numberformat) in the main mobile browsers now.

**Comment by trevdor** [comment]
Ooh, that could sound like, "Why don't you hurry up and do it!?!" I meant, I have formatting working with `Int.NumberFormat` on a branch of mine, and can open a PR if I won't be stepping on your work already completed.

**Comment by TomAFrench** [comment]
Nope, I was planning on tackling it this weekend. If you've got a branch ready then feel free to make a PR, I'd be happy to take a look and give feedback.
