### ISSUE TITLE
[Bug]: Using filter "category is (nothing)" displays transactions with category "Transfer"

### ISSUE THREAD

**Issue by mkalamarz** [actualbudget/actual#901]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

How to replicate:

1. Assuming you have at least two accounts with at least one transaction for each category of "Transfer", "[Catgorize]" (no category) and some other category.
2. Select "Filter" then "Category" then use default comparison type of "is" and don't specify category. This creates filter "category is (nothing).
3. List of transations displays ones without category (cool!) and those with category set to "Transfer" (not cool).

It is especially inconvinient because there is no way to set an additional filter of type "category is NOT Transfer".

Version: 23.4.0

### What error did you receive?

No error just unexpected behavior.

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 10

**Comment by j-f1** [comment]
Good catch! I opened #904 to track adding an explicit way to filter for these transactions, but this definitely be fixed.

**Comment by anthonyronda** [comment]
Came to report a related (likely the same) issue: when sorting transactions by category, [Categorize] and Transfer are treated as the same category for sort purposes 

Example
<img width="196" alt="image" src="https://github.com/actualbudget/actual/assets/1410433/46acec1d-4e6e-40c4-a9fe-fd20b305a5d2">

**Comment by carkom** [comment]
Due to the way the transactions are stored, category = null for these transactions types:

Transfer
Uncategorized (shown as "Categorize" in the table)
Parent Split (the children have categories but the parent is null)

Should we add these as options at the bottom of the autocomplete category list under a new group heading "Uncategorized"?

**Comment by youngcw** [comment]
It looks to me like splits also count when filtering this way.

**Comment by hui-zheng** [comment]
To add to this. currently, there is no way to set a filter to display only those transactions with category set to "Transfer"
