### ISSUE TITLE
[Feature] Add a “transfer” option to the category dropdown when filtering transactions

### ISSUE THREAD

**Issue by j-f1** [actualbudget/actual#904]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### Pitch: what problem are you trying to solve?

There is currently no way to filter for all transfer transactions (either in a rule or in the UI. See #901 for some related discussion.

### Describe your ideal solution to this problem

Either:

- Add a new item to the category dropdown (only for rule conditions/filters, not rule actions/the budget table) labelled “Any Transfer” or “Transfer” (possibly italicized?)
- Add a new filter method that filters for transfer/non-transfer transactions

### Teaching and learning

I think people will be able to find it in the appropriate location when they want it.

**Comment by Jackenmen** [comment]
One thing to think about is how would this filter work for budgeted <-> off-budget transfers where the budgeted side has a normal category but is still a transfer. Would it make sense to add a separate (from categories) filter for all transfers? Maybe it would make sense to, in addition to the separate filter, still allow filtering by the "Transfer" category to allow differing between budgeted<->off-budget and budgeted<->budgeted. Might be a bit confusing that such a "Transfer" category wouldn't actually show all transfers, as opposed to the separate filter.

Anyhow, [per my understanding of the problem in 814](https://github.com/actualbudget/actual/issues/814#issuecomment-1501769701), this could help solve it as well.

**Comment by kjohnsen** [comment]
Related: it would be nice that "Transfer" would be searchable, without filtering. i.e., typing "transfer" in the search box would bring up transfer transactiosn
