### ISSUE TITLE
[Bug]: after update v23.4.0 enter no longer adds transactions

### ISSUE THREAD

**Issue by joaociocca** [actualbudget/actual#907]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Previously, while filling a transaction, pressing <kbd>enter</kbd> would add the transaction, but now I need to pick the mouse and click on "Add"

### What error did you receive?

no error, <kbd>enter</kbd> just "won't work" anymore.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chromium-based, Vivaldi

### Operating System

Linux, Arch, Garuda

**Comment by j-f1** [comment]
I believe this was fixed by #883. We are planning to do another release soon but would you be able to check https://actualbudget.netlify.app and confirm that the issue has been fixed there?

**Comment by joaociocca** [comment]
Confirmed, both work on that! Any ETA on docker update?
![image](https://user-images.githubusercontent.com/6473725/232325920-9d57db77-8a31-4785-9c49-6b6f357b0561.png)

**Comment by j-f1** [comment]
soon! Matiss said he’d work on it. You can also temporarily use the `edge` Docker image if you don’t want to wait.

**Comment by j-f1** [comment]
The new release should be out now.

**Comment by joaociocca** [comment]
nice, `docker pull actualbudget/actual-server` updated stuff. I'm on 23.4.1 already and enter's working again!
