### ISSUE TITLE
[Bug]: payees not selectable in schedule creation modal

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#912]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

<img width="835" alt="Screenshot 2023-04-16 at 18 18 51" src="https://user-images.githubusercontent.com/886567/232329589-9e09acf1-4e44-4630-bcfa-c939fdc75599.png">

Possibly related to the autocomplete migration in https://github.com/actualbudget/actual/issues/773

### Where are you hosting Actual?

None

### Operating System

None

**Comment by j-f1** [comment]
May be related to https://github.com/actualbudget/actual/pull/902 — perhaps the modal is not providing the payee/account list?

**Comment by biohzrddd** [comment]
Confirming this is likely related to #902 as I removed loading the cached payee and account list from inside the function, meaning the calling function must provide it, which the modal is likely not. Might be worth reverting #902 until we find a fix as this is a breaking change.

**Comment by MatissJanis** [comment]
Fixed in the next release
