### ISSUE TITLE
[Bug]: reconciling with new balance of "0" (zero) does not reconcile.

### ISSUE THREAD

**Issue by chrispazz** [actualbudget/actual#913]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

If you reconcile an account setting the new balance to "0", it does nothing (not set the balance to zero and does not ask for reconciliation transaction).

### What error did you receive?

No explicit errors.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by j-f1** [comment]
Thanks for finding this! Give the preview in #915 a try.
