### ISSUE TITLE
[Feature] Rule Ability: Delete Transaction

### ISSUE THREAD

**Issue by wjbridge** [actualbudget/actual#917]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I am trying to avoid duplicate transactions from my savings account to my credit cards. When I import my credit card and bank transactions. If I create a rule for my savings account that converts a payment to a transfer (Bank -> Credit Card, this transfer ends up showing in the credit card account which will be a duplicate of what is imported. I import my credit card and bank as QFX files.

### Describe your ideal solution to this problem

I would like the ability to delete a transition using a `rule`.

**Comment by j-f1** [comment]
Transactions should be merged upon import if they have the same date/payee/amount. If you set up another rule in your credit card that labels the transactions as transfers from your savings account, does the merging work OK?

**Comment by j-f1** [comment]
As long as they’re 4 days or less apart they should merge.

**Comment by wjbridge** [comment]
I will experiment tmr and see if it works. Thanks for your help!
