### ISSUE TITLE
[Bug]: New Payee isn't selected by Enter

### ISSUE THREAD

**Issue by MikeBishop** [actualbudget/actual#925]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

While entering a transaction, type the name of a Payee that doesn't exist:
![image](https://user-images.githubusercontent.com/4273797/233398507-2c0fdd20-b8ed-459d-9605-2ef27c48a37a.png)

If, at this point, you tab to the next field, the right things happen -- the Payee is created and selected for the new transaction.

However, if you press Enter (a logical interaction since Create Payee is the highlighted option), the new Payee is created but the first Payee in the list is selected:
![image](https://user-images.githubusercontent.com/4273797/233398862-dbd1ab38-b332-410d-b64c-33e5fd0c34d0.png)

If you now tab away, that selected payee overwrites the name of the new Payee in the new transaction:
![image](https://user-images.githubusercontent.com/4273797/233399118-8638303d-2a26-40b0-a2ac-90391a54dbec.png)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Other

### Operating System

Windows 11

**Comment by j-f1** [comment]
This issue may have been fixed by reverting to our old autocomplete input. Can you test out https://actualbudget.netlify.app and confirm that is the case?

**Comment by MikeBishop** [comment]
Yes -- the behavior there is that pressing Enter creates the Payee and dismisses the Payee list, leaving the correct Payee in the transaction.

**Comment by j-f1** [comment]
Thanks for confirming!
