### ISSUE TITLE
[Feature] Option to set monthly schedules to occur `on the last weekday`

### ISSUE THREAD

**Issue by MSBack** [actualbudget/actual#929]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Most of my automated transactions in my bank occur on the last weekday of the month (last day of the month, except if that day a weekend day).

As is, I cannot reflect this in my Actual Budget schedules, because I can only pick a specific day of the month. For example, this current April, the last weekday of the month is the 28th, as the month ends with a weekend, but next month in May, the last weekday is the 31st. If I set up the schedule today, it will run again on the 28th next month, which doesn't match when the transaction actually occurs.

I moved from Money Manager Ex, which has a feature to schedule transactions either on the last day of the month, or the last weekday of the month. Therefore, I am surprised that this hasn't been implemented or requested here yet, as far as I can tell.

### Describe your ideal solution to this problem

My solution would be to have an option to schedule transactions / transfers on the last weekday. Perhaps this could be set by making the `add specific days` button into a dropdown where you could choose `on the last weekday`. The result would look like so: "Repeat every `1` `month` `on the last weekday`". Or else `on the last weekday` could be an option under `add specific days`.

**Comment by MSBack** [comment]
A similar option would also be useful for the first weekday of the month. In many experience, many expenses are withdrawn on the first weekday of the month.

**Comment by Kidglove57** [comment]
I agree this would be useful. Moneywiz (for example) gives the option for a schedule falling on the weekend to be posted either on the day before or the day after that weekend.

**Comment by mkalamarz** [comment]
> I agree this would be useful. Moneywiz (for example) gives the option for a schedule falling on the weekend to be posted either on the day before or the day after that weekend.

Adding on top of that, in my opinion there should be a separate field/option with three choices:

1. Post on the day before weekend
2. Post on the day after weekend
3. Post on this date anyway

**Comment by MSBack** [comment]
@mkalamarz @Kidglove57 Please indicate your support for this feature request by upvoting the first comment, as per the github action notice below.

**Comment by Shazib** [comment]
@MSBack, is this not covered by setting to repeat on the last friday of every month?

![image](https://github.com/actualbudget/actual/assets/4405777/69b079a4-bea6-4285-a214-926b01bd9804)

**Comment by MSBack** [comment]
> @MSBack, is this not covered by setting to repeat on the last friday of every month?

No. Consider the case of a 30 day month. If Friday occurs on the 24th, for example, then the last Friday six days before the last weekday, which would be the 30th.

**Comment by youngcw** [comment]
I believe this request is currently doable with the following settings in the schedule
![image](https://github.com/actualbudget/actual/assets/28542559/04a4c861-af56-42ed-a8ea-e1f861884987)

Is there something Im missing? If not this should be closed as completed.
