### ISSUE TITLE
[Bug]: j/k ledger navigations no longer work

### ISSUE THREAD

**Issue by youngcw** [actualbudget/actual#937]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Ever since release 23.4.1 using j/k to navigate down/up account ledgers doesn't work.  Arrow keys still work.  Its not a big deal, but my docs PR that called this out got merged today.  I like having the option to use j/k to move around since its quick.

### Where are you hosting Actual?

NAS

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Linux

**Comment by j-f1** [comment]
Works fine in 649b4c90e036bc4c6637fa7eebc541c06258fd45, bisecting…

**Comment by youngcw** [comment]
I tried the netlify deploys of 23.4.2 and 23.4.1 and neither of them worked for me, but 23.4.0 did.  If that helps

**Comment by j-f1** [comment]
#939!

**Comment by youngcw** [comment]
Cool, ill give that a try
