### ISSUE TITLE
[Bug]: Unable to clear category with "delete" key; must use mouse

### ISSUE THREAD

**Issue by bsmarsh333** [actualbudget/actual#938]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

If you attempt to clear the "Category" field of a transaction with the "delete" key, nothing happens. It appears that you must use a mouse to select the "x" to remove the category.

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by j-f1** [comment]
This has been fixed by reverting back to the new autocomplete input, make sure you’re running the new release (as of today/yesterday).

**Comment by bsmarsh333** [comment]
Looks like if you hit the delete key twice, it will clear the category. However, for it to save you must hit enter. If you hit tab or shift+tab, it will not save.

**Comment by bsmarsh333** [comment]
Thanks! I am on PikaPods so I have to wait a couple of weeks to get the update.
