### ISSUE TITLE
[Bug]: Transaction, pressing enter in notes field doesn't add transaction

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#943]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When adding a transaction, add some notes and press enter, nothing happens. 

This used to add the transaction but it doesn't anymore. 

### What error did you receive?

None

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

**Comment by j-f1** [comment]
It looks like only pressing enter on the payment column works.

**Comment by MatissJanis** [comment]
I don't think this is a regression, but nonetheless: here's the fix - https://github.com/actualbudget/actual/pull/992
