### ISSUE TITLE
[Bug]: Accounts, adding account and changing type resets off budget

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#944]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When changing an account type on the add account dialog, the off budget checkbox is reset to an unchecked state.

### What error did you receive?

None

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

**Comment by j-f1** [comment]
I believe this is expected since the account type defines whether it should be on/off budget by default. That said, I don’t think there is much value in having the different account types so maybe we can just remove the dropdown?

**Comment by rich-howell** [comment]
In my head I created an account, went through the motions, clicked the off budget checkbox then thought, "Ah this should be savings" changed it and pressed add. It ended up **On Budget**

As I was in auto pilot I didn't notice the checked change state. 

Removing the drop down works if it doesn't create any other functional implications, is that data used in reporting etc?

**Comment by j-f1** [comment]
> Removing the drop down works if it doesn't create any other functional implications, is that data used in reporting etc?

I checked pretty thoroughly and it seems to only be displayed on the mobile account list and nowheere else

**Comment by MatissJanis** [comment]
I don't think removing account type entirely is the way to go here. Right now splitting between on/off budget is a very handy feature to distinguish between accounts that need to be considered in the budget and "other accounts" (i.e. investments, savings, loans, etc.). In the future I can see even more distinctions between the various types, so I do think we should keep around the account `type` field.

**Comment by j-f1** [comment]
I think if we do want to expand this, it would be good to start with a clean slate and think carefully about exactly which categories we want to have. Additionally, we should not use the `type` key because it is basically impossible to code search for.

**Comment by MatissJanis** [comment]
Ok, I have changed my mind about this. Lets kill the `type` field. `offbudget`/`onbudget` is sufficient.

**Comment by rich-howell** [comment]
> Ok, I have changed my mind about this. Lets kill the `type` field. `offbudget`/`onbudget` is sufficient.

Are you sure? What happens in the future if/when we wanted to do some other bits with Credit Cards? How would that work?

**Comment by MatissJanis** [comment]
> > Ok, I have changed my mind about this. Lets kill the `type` field. `offbudget`/`onbudget` is sufficient.
> 
> Are you sure? What happens in the future if/when we wanted to do some other bits with Credit Cards? How would that work?

So right now the account type field is unused (as in: you set it when creating an account, but then it's not used anywhere else). For the sake of simplicity of the product - I think it makes sense to cut it.

AND: if in the future we want to build some special functionality for account-types - we can then bring it back. But even then - maybe it won't be `account_type`, but rather a toggle. Similar as we currently have with on-budget/off-budget.
