### ISSUE TITLE
[Feature] Apply template to single category

### ISSUE THREAD

**Issue by youngcw** [actualbudget/actual#958]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I would like the option to apply a template to just a single category.  Possibly only the override template option.  This can kinda be done currently by deleting the budgeted amount then reapplying the template.  Making on option to apply to a single category would be more obvious than the delete->reapply method.

### Describe your ideal solution to this problem

Add an option to the category drop down to apply its template.

### Teaching and learning

Call out the option in the template section of the docs.

**Comment by youngcw** [comment]
This is probably unnecessary if #961 gets merged.

**Comment by shall0pass** [comment]
Removing the needs votes label since this was merged in #1350.
