### ISSUE TITLE
[Bug]: Transaction selection checkbox no longer appears on hover

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#965]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When hovering over a transaction in the transaction register a checkbox used to appear to show you where to click to check it, this no longer happens. 

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

**Comment by Kidglove57** [comment]
Thanks for raising this Rich - I noticed this the other day and then got distracted.

Basically the check box is now not discoverable for a new user.

**Comment by MatissJanis** [comment]
A hotfix is available here: https://github.com/actualbudget/actual/pull/966

A better fix will be to port this component to TypeScript. This would have been prevented then. But we'll get there.. @albertogasparin has already ported loads of our code to TS, so eventually we will get there.
