### ISSUE TITLE
[Bug]: mobile - first day of the week

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#971]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Styling could be improved.
Scrunched up layout on mobile and on desktop at narrow widths with the sidebar open.

<img width="369" alt="Screenshot 2023-04-29 at 18 47 00" src="https://user-images.githubusercontent.com/886567/235316801-79bafeb6-e57f-4588-a34e-9c18005cfe3f.png">

<img width="739" alt="Screenshot 2023-05-06 at 11 57 30 AM" src="https://user-images.githubusercontent.com/5862724/236639691-1ff07ed4-f1cb-422b-ba18-8a6a394706e0.png">

### Where are you hosting Actual?

None

### Operating System

None

**Comment by trevdor** [comment]
I keep seeing this over in #964 . I’ll find the right breakpoint and fix it there, since I’m already messing with the Settings styles.
