### ISSUE TITLE
[Feature] Change first day of month

### ISSUE THREAD

**Issue by Jeremy-Pichon** [actualbudget/actual#975]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Month budgets are not always tight to actual month (1st to 31th), but more to payday.
In my country salary is on 25th (or last working day before this day)m therefore my actual month budget is from 25th of previous month to 24th of current month.

### Describe your ideal solution to this problem

I would add a section in settings to pick first day of month.
Maybe in the same section as `Numbers` and `Dates`.
Implementation could be a global setting or a budget related setting.

### Teaching and learning

Probably same as Dates and Numbers it would have a default value (eg: `1st day of month`).

Here is an example of the same feature on Money Wizz.
![moneywizz](https://user-images.githubusercontent.com/10031871/235335310-d322ad65-2ffc-440c-b697-89f3e1bc1537.jpg)

**Comment by fillwe** [comment]
Yes this is so needed! Have tried the recommended way in the docs and hold the money for the 1st of the month but you become so out of sync with the rest of society. In Sweden it’s set in stone that you count your budget from the 25’th - 24’th, and all the bills for the next month is due before 1st usually.

**Comment by frbrigagao** [comment]
Same! In Brazil there isn't a standard. Some receive their salaries in the 1st, 5th, 10th, 20th or some other day. Having a monthly budget with a fixed 1st day of the month doesn't make sense in this scenario.

**Comment by napoleonjumprope** [comment]
I could not agree more. Actual holds so much promise that I tried moving to a calendar month way of budgeting but it just does not work* when the payday cycle starts on the 25th. 

* it works of course if you stick to it, but as you said you become completely detached from how the rest of society works.

**Comment by TheBlueCircle** [comment]
Excellent idea, but we probably want to disaggregate two concepts here: budget month and payroll period. In particular:

* A payroll period may not be a month. In the US, weekly and fortnightly pay is still most common. 
* Some banks allow you to receive your paycheck early
* Actual might need reference to bank or public holidays in different countries (because if you're usually paid on a fixed date then usually - but not always - you'll not be paid that date. Usually the working day before but not always. 
* In some countries you get paid early for religious holidays (like Christmas)
* The logic can be complex (for example  "paid the day before the last working day of the month". 

Perhaps a simple fix would be to create a new budget period based on rules? So if I receive > $€¥£x from y then it's recognised as my salary and a new budget period starts automatically? 

The question about pay periods could then be a separate question which might be needed for future period projection, but which would be more complex.

**Comment by fillwe** [comment]
Thanks for the reply, you might be right about this. But it isn't possible to set a rule to start a new budget period in the current release, right? If it is i can't seem to be able to find it.

**Comment by rare-magma** [comment]
Is this a matter of making the startDate of the createSpendingSpreadsheet() function customizable ([link](https://github.com/actualbudget/actual/blob/b253246fe2e78a2c496f8dbe9bc1e0080d32563a/packages/desktop-client/src/components/reports/spreadsheets/spending-spreadsheet.ts#L25))? Is there any change required in the backend / database? I couldn't find any other references to this in the codebase. If the maintainers are willing to accept this change and provide some pointers I could work on a PR to implement this feature.

**Comment by napoleonjumprope** [comment]
> Is this a matter of making the `startDate` of the `createSpendingSpreadsheet()` function customizable ([link](https://github.com/actualbudget/actual/blob/b253246fe2e78a2c496f8dbe9bc1e0080d32563a/packages/desktop-client/src/components/reports/spreadsheets/spending-spreadsheet.ts#L25))? Is there any change required in the backend / database? I couldn't find any other references to this in the codebase. If the maintainers are willing to accept this change and provide some pointers I could work on a PR to implement this feature.

This would be AMAZING. :)

**Comment by ElDubsNZ** [comment]
I also support being able to create non-month based budget periods. I'm paid fortnightly on a Tuesday, so fortnightly budgets would make so much more sense for me.

**Comment by Th3K1ngP1n** [comment]
Upvoting this !!

**Comment by garyabrahams** [comment]
Agree this is a must and is the only reason why I can't use this product as I need a budget from 14th to 13th.  Calender month does not work for me

**Comment by Haasie** [comment]
+1

**Comment by Th3K1ngP1n** [comment]
I stopped using this app due to the missing feature that probably most of Europe requires. Almost 6 months...

**Comment by Mansarde** [comment]
> I stopped using this app due to the missing feature that probably most of Europe requires. Almost 6 months...

I live in Europe and I've never needed to change the first of the month to my payday.
Just curious for why you deem this to be an essential feature for your budgeting?

**Comment by Th3K1ngP1n** [comment]
> > I stopped using this app due to the missing feature that probably most of Europe requires. Almost 6 months...
> 
> I live in Europe and I've never needed to change the first of the month to my payday. Just curious for why you deem this to be an essential feature for your budgeting?

Well that's my point. I don't need to change to the 1st of the month. The app starts the payroll from the 1st which is no good if you get paid on the 16th for example.

**Comment by Mansarde** [comment]
> The app starts the payroll from the 1st which is no good if you get paid on the 16th for example.

But *why* is that no good? What problem does that create for you?

For example, I also get paid pretty late, in the last week of the month.
Sometimes I need some of that money for the current month, so I distribute a portion to where it's needed.
But most of it I don't need in the current month, so I simply forward it for use next month.
That's what Actual's `Hold for next month` option is for when you click on the "To Budget" number at the top of the budget screen.

**Comment by TateWalker** [comment]
When I get paid midway through the month (once a month), I fund everything I'll need until my next paycheck. This includes expenses tracked per month (groceries for August). So if my water bill is due the last day of the month, I want my budget templates to fund that for the current month when I get paid. There will be another paycheck before the next month's water bill, so I don't need to fund it now.

I get the idea of "hold enough money for all expenses in the next month", but I personally like to run my bank account lean and invest any extra money. By running budget templates on the first of the month, I'm forced to hold money to cover the entire next month's bills.

I'd rather change my "month" to my pay date. Or have an income template that says "Run budget templates when income received from this payer"

**Comment by youngcw** [comment]
> When I get paid midway through the month (once a month), I fund everything I'll need until my next paycheck. This includes expenses tracked per month (groceries for August). So if my water bill is due the last day of the month, I want my budget templates to fund that for the current month when I get paid. There will be another paycheck before the next month's water bill, so I don't need to fund it now.
> 
> I get the idea of "hold enough money for all expenses in the next month", but I personally like to run my bank account lean and invest any extra money. By running budget templates on the first of the month, I'm forced to hold money to cover the entire next month's bills.
> 
> I'd rather change my "month" to my pay date. Or have an income template that says "Run budget templates when income received from this payer"

@TateWalker You can use template priorites to do what you are asking.  Also, there is no reason you cant be aggressive with investing and still be a month ahead.  The budget doesn't care what account the funds are in, so you can be budgeting funds that are in savings accounts or a CMA/brokerage if they are on budget.

**Comment by darkporpoise** [comment]
I found this a point of friction when trying to adopt AB as my first budgeting app. If AB is locked to a calendar month then it doesn't really support true envelope budgeting. AB is implicitly expecting me to budget money that I don't yet have.

I have played with a few workarounds for this:

1. Ignore the red numbers that tell me I have overbudgeted and just make sure my monthly budget equals my paycheck
    1. This is a pain if I am spending faster at the beginning of the month as I may run out of money whilst AB shows budget remaining.
    1. I end up doing calculations outside of AB. e.g. how much do I have left to spend on groceries before pay day.
1. Add a "fudge" on-budget account with just the right balance to make my available funds match my expected pay check
    1. Doesn't really solve any problems but looks better.
1. Have savings...
    1. This is the implied solution in a lot of the responses to bridge the gap between pay day and start of next month.
    1. It still doesn't solve the mismatch between the AB budget and available funds as that assumes I can spend from my savings without notice or penalty.
    1. If I don't want to spend from my savings I may still need to manage my spending outside of AB.

I'm loving AB and it's really helping me to get a handle on my finances but I'm still having to manually calculate and track things that AB would do for me if I happened to be lucky enough to be paid on the 1st of each month.
