### ISSUE TITLE
[Bug]: UI Hangs when using 'schedule' keyword with goal templates

### ISSUE THREAD

**Issue by shall0pass** [actualbudget/actual#983]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

The UI freezes when applying goal templates that use the 'schedule' keyword in the month that the schedule is due.  This is present in the master branch.
![schedules_uiHangup](https://user-images.githubusercontent.com/20625555/235519609-887bdc04-44ad-468f-abba-36cf789cc39e.gif)

### What error did you receive?

There are no errors in the dev console.

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by j-f1** [comment]
Can you export that file and attach it here so we can more easily reproduce?
