### ISSUE TITLE
[Feature] "Copy last month's budget": ignore any values already set for that month

### ISSUE THREAD

**Issue by bstritesky** [actualbudget/actual#986]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I sometimes vary budgeted amounts for categories month-to-month, manually populating those values in budgeted amounts for the current month prior to performing the copy action. Currently, the "Copy last month's budget" action pulls all budgeted amounts from the last month, regardless of what I have manually set for the current month.

### Describe your ideal solution to this problem

It would be nice if the "Copy last month's budget" action would respect any values I have already set for the current month, and only pull budget amounts from the previous month if the current month has no budget value set.

**Comment by glancep** [comment]
+1.  I would love this feature.  Coming from YNAB4, this is exactly how it worked.  Our workflow is very similar as described above--if we need to make a one-off change, we'll manually enter the "go-forward" budget amount into next month's as a reminder of what it should be.  When we went to budget that next month, we copied from the prior month and almost missed that it overwrote our manually entered value.
