### ISSUE TITLE
[Bug]: Selecting popover item on iPad closes popover without selecting value

### ISSUE THREAD

**Issue by LarsStegman** [actualbudget/actual#989]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Trying to select an item from a popover like Payee, Category, Cover Overspending, etc, dismisses the popover without selecting the tapped item. It looks like the touch event is passed to the elements underneath the popover. 

This is the same issue as here, but it was closed without the problem being solved: #274 

I'm on iPadOS 16.4.1

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Safari

### Operating System

Mobile Device

**Comment by Kidglove57** [comment]
I have also been noticing this (and on my iPhone in desktop mode also). I may be misremembering but I believe it worked correctly before the last update?

**Comment by LarsStegman** [comment]
I don't know if it worked before, I only started using Actual yesterday :)

**Comment by shall0pass** [comment]
Is fixed in the master branch and the edge release.  It'll be in the next stable release.

**Comment by Kidglove57** [comment]
Thank you both!
