### ISSUE TITLE
[Bug]: Split Transaction Focus

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#996]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When entering a transaction that ultimately is a split you work along the transaction row until getting to the category, here you select split and the focus is moved into the split row, this happens before the amount is added in the parent row which seems incorrect. The focus should stay on the parent row until it is completed and the user move into the split once completed with entry.

### What error did you receive?

None

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

**Comment by Kidglove57** [comment]
Great point Rich! Another "bug" that I have got so used to over the years that I forget to raise.
