### ISSUE TITLE
[Improvement]: Surface Help Link

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#998]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I think we should surface the help link in the budget somewhere more profound, there have been multiple instances of people being unable to find it under the budget name drop down.

Why don't we do what YNAB does and have a floating question mark in the bottom right corner? 

### What error did you receive?

No errors

### Where are you hosting Actual?

None

### Operating System

None

**Comment by youngcw** [comment]
I like this setup (Icons in the bottom left).  It feels less intrusive to me than the big floating "?".  It also adapts to collapsing the side bar.

Taken from my instance of paperless-ngx.
![image](https://github.com/actualbudget/actual/assets/28542559/a749f968-eb37-4128-85d8-71de627788d3)
